-- words テーブル INSERT文 (No.1 ~ No.50)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1, 'lucrative', '利益の大きい、もうかる', '/ˈluːkrətɪv/', 'ルークラティヴ',
  'The company discovered that investing in renewable energy was far more lucrative than they had initially anticipated.',
  'その会社は、再生可能エネルギーへの投資が当初予想していたよりもはるかに利益が大きいことに気づいた。',
  'She abandoned her lucrative career in finance to pursue her passion for marine biology.',
  '彼女は海洋生物学への情熱を追求するために、もうかる金融のキャリアを捨てた。'),
(2, 'squander', '(金・時間・機会など)を浪費する', '/ˈskwɒndər/', 'スクウォンダー',
  'He squandered his entire inheritance on extravagant vacations and luxury automobiles within just two years.',
  '彼はわずか2年で豪華な旅行と高級車に全遺産を浪費してしまった。',
  'The government was criticized for squandering taxpayer funds on projects that yielded no tangible results.',
  '政府は具体的な成果を生まないプロジェクトに税金を浪費したと批判された。'),
(3, 'flimsy', '(物が)壊れやすい、薄っぺらな;(根拠などが)説得力を欠く', '/ˈflɪmzi/', 'フリムジー',
  'The prosecutor dismissed the defendant''s alibi as flimsy and lacking any corroborating evidence.',
  '検察官は被告のアリバイを薄弱で裏付ける証拠がないとして退けた。',
  'The flimsy wooden bridge swayed dangerously under the weight of the hikers crossing it.',
  'その壊れやすい木製の橋は、渡るハイカーの重みで危険なほど揺れた。'),
(4, 'incision', '切開', '/ɪnˈsɪʒən/', 'インスィジョン',
  'The surgeon made a precise incision along the patient''s abdomen to access the inflamed appendix.',
  '外科医は炎症を起こした虫垂にアクセスするため、患者の腹部に正確な切開を行った。',
  'Thanks to advances in minimally invasive surgery, the incision required was remarkably small.',
  '低侵襲手術の進歩のおかげで、必要な切開は驚くほど小さかった。'),
(5, 'lethargic', 'けだるい、無気力な', '/ləˈθɑːrdʒɪk/', 'レサージック',
  'After the heavy meal, the students felt lethargic and struggled to concentrate during the afternoon lecture.',
  '重い食事のあと、学生たちはけだるさを感じ、午後の講義に集中するのに苦労した。',
  'The prolonged heatwave left the entire population feeling lethargic and unable to perform their daily tasks.',
  '長引く熱波のせいで住民全体が無気力になり、日常の仕事をこなせなくなった。'),
(6, 'pinnacle', '(権力・名声などの)頂点、絶頂', '/ˈpɪnəkl/', 'ピナクル',
  'Winning the Nobel Prize represented the pinnacle of her distinguished career in molecular biology.',
  'ノーベル賞の受賞は、彼女の分子生物学における輝かしいキャリアの頂点を象徴していた。',
  'The empire reached the pinnacle of its power in the sixteenth century before gradually declining.',
  'その帝国は16世紀に権力の絶頂に達した後、徐々に衰退していった。'),
(7, 'allay', '(恐怖など)を鎮める;(苦痛・悲しみなど)を和らげる', '/əˈleɪ/', 'アレイ',
  'The prime minister held a press conference to allay public fears about the economic downturn.',
  '首相は景気後退に対する国民の不安を鎮めるために記者会見を開いた。',
  'Nothing the doctor said could allay her concerns about the risks associated with the surgery.',
  '医師が何を言っても、手術に伴うリスクに対する彼女の懸念を和らげることはできなかった。'),
(8, 'feat', '功績、偉業、離れ業', '/fiːt/', 'フィート',
  'Climbing Mount Everest without supplemental oxygen remains one of the most remarkable feats of human endurance.',
  '補助酸素なしでエベレストに登ることは、人間の忍耐力における最も驚くべき偉業の一つである。',
  'The construction of the transcontinental railroad was an extraordinary engineering feat for its era.',
  '大陸横断鉄道の建設は、その時代にとって驚異的な工学的偉業であった。'),
(9, 'ransack', '(場所)をくまなく探す、引っかき回す', '/ˈrænsæk/', 'ランサック',
  'Burglars ransacked the entire house, leaving drawers open and belongings scattered across the floor.',
  '強盗が家中を引っかき回し、引き出しは開けっ放しで持ち物が床中に散乱していた。',
  'She ransacked her office looking for the misplaced contract before the client''s arrival.',
  '彼女はクライアントが来る前に、置き忘れた契約書を探してオフィスをくまなく探した。'),
(10, 'caustic', '(批判が)辛らつな;腐食性の', '/ˈkɔːstɪk/', 'コースティック',
  'The critic''s caustic review of the novel discouraged many potential readers from purchasing it.',
  'その評論家の辛らつな書評のせいで、多くの読者候補がその小説の購入をためらった。',
  'His caustic remarks about his colleagues'' incompetence created a hostile atmosphere in the workplace.',
  '同僚の無能さに対する彼の辛らつな発言が、職場に敵対的な雰囲気を生み出した。'),
(11, 'frivolous', '(人・行為などが)軽率な、ふまじめな', '/ˈfrɪvələs/', 'フリヴォラス',
  'The judge dismissed the lawsuit as frivolous, stating that it had no legal merit whatsoever.',
  '裁判官はその訴訟を軽率なものとして却下し、法的根拠が全くないと述べた。',
  'Rather than engaging in frivolous pursuits, she devoted her weekends to volunteering at the local shelter.',
  '軽率な活動に興じるのではなく、彼女は週末を地元のシェルターでのボランティアに捧げた。'),
(12, 'latitude', '自由、裁量;緯度', '/ˈlætɪtjuːd/', 'ラティテュード',
  'The new manager gave employees considerable latitude in deciding how to organize their workflow.',
  '新しいマネージャーは、社員に業務の進め方について大幅な裁量を与えた。',
  'Teachers in this progressive school are granted wide latitude to develop their own curricula.',
  'この進歩的な学校では、教師が独自のカリキュラムを開発する幅広い自由が与えられている。'),
(13, 'adept', '熟練した、抜け目のない', '/əˈdɛpt/', 'アデプト',
  'She proved remarkably adept at navigating the complex bureaucratic procedures required for international trade.',
  '彼女は国際貿易に必要な複雑な官僚的手続きをこなすのに極めて熟練していることを証明した。',
  'The diplomat was adept at diffusing tensions between conflicting parties during delicate negotiations.',
  'その外交官は繊細な交渉の場で対立する当事者間の緊張を和らげることに熟練していた。'),
(14, 'avid', '熱心な、熱烈な', '/ˈævɪd/', 'アヴィッド',
  'An avid reader since childhood, she amassed a personal library of over ten thousand volumes.',
  '子供の頃からの熱心な読書家であった彼女は、1万冊以上の個人蔵書を集めた。',
  'The documentary attracted avid supporters of environmental conservation from around the world.',
  'そのドキュメンタリーは世界中から環境保全の熱烈な支持者を引きつけた。'),
(15, 'asylum', '亡命、(亡命者の)保護', '/əˈsaɪləm/', 'アサイラム',
  'Thousands of refugees sought asylum in neighboring countries to escape the escalating civil war.',
  '何千人もの難民が激化する内戦から逃れるために近隣諸国に亡命を求めた。',
  'The government''s asylum policy has been the subject of intense debate in parliament for months.',
  '政府の亡命政策は数ヶ月にわたり議会で激しい議論の的となっている。'),
(16, 'placate', '(人)をなだめる;(怒り・敵意など)を鎮める', '/ˈpleɪkeɪt/', 'プレイケイト',
  'The airline offered free upgrades in an attempt to placate passengers stranded by the delayed flight.',
  '航空会社は遅延便で足止めされた乗客をなだめるために無料アップグレードを提供した。',
  'His apology did little to placate the furious shareholders who had lost substantial investments.',
  '彼の謝罪は、多額の投資を失い激怒した株主たちをなだめるにはほとんど役に立たなかった。'),
(17, 'pristine', '新品同様の、汚れていない;原始の、元の状態の', '/ˈprɪstiːn/', 'プリスティーン',
  'The national park has managed to preserve its pristine wilderness despite growing tourist numbers.',
  'その国立公園は観光客数の増加にもかかわらず、手つかずの原生自然を保つことに成功している。',
  'He kept his vintage automobile in pristine condition, polishing it meticulously every weekend.',
  '彼はヴィンテージカーを新品同様の状態に保ち、毎週末入念に磨いていた。'),
(18, 'blatantly', '公然と、露骨に', '/ˈbleɪtəntli/', 'ブレイタントリー',
  'The corporation blatantly disregarded environmental regulations, dumping toxic waste into the river.',
  'その企業は環境規制を公然と無視し、有毒廃棄物を川に投棄した。',
  'He blatantly plagiarized sections of the published research paper without citing the original author.',
  '彼は原著者を引用せずに、出版された研究論文の一部を露骨に盗用した。'),
(19, 'attire', '(特別な)服装、衣装', '/əˈtaɪər/', 'アタイアー',
  'Guests were advised to wear formal attire to the charity gala held at the grand ballroom.',
  'ゲストは大広間で開催されるチャリティーガラにフォーマルな服装で出席するよう案内された。',
  'The traditional attire worn during the festival reflected centuries of cultural heritage.',
  '祭りの期間中に着用される伝統的な衣装は、何世紀にもわたる文化遺産を反映していた。'),
(20, 'offshoot', '(より大きな組織から)派生したもの、分派', '/ˈɒfʃuːt/', 'オフシュート',
  'The startup began as an offshoot of the university''s artificial intelligence research laboratory.',
  'そのスタートアップは大学の人工知能研究所から派生したものとして始まった。',
  'The political party was originally an offshoot of a larger movement advocating for social reform.',
  'その政党はもともと社会改革を唱えるより大きな運動の分派であった。'),
(21, 'gullible', 'だまされやすい、信じやすい', '/ˈɡʌləbl/', 'ガリブル',
  'Scammers often target gullible elderly individuals who are unfamiliar with modern technology.',
  '詐欺師は現代のテクノロジーに不慣れなだまされやすい高齢者をしばしば標的にする。',
  'She was too gullible to recognize that the investment scheme was an elaborate fraud.',
  '彼女はだまされやすすぎて、その投資スキームが精巧な詐欺であることに気づかなかった。'),
(22, 'hindsight', 'あと知恵、あとから判断する能力', '/ˈhaɪndsaɪt/', 'ハインドサイト',
  'In hindsight, the decision to expand into foreign markets without adequate research proved disastrous.',
  '振り返ってみると、十分な調査なしに海外市場に進出する決定は壊滅的であったことが判明した。',
  'Hindsight revealed that the warning signs of the financial crisis had been apparent for years.',
  'あと知恵で見れば、金融危機の警告サインは何年も前から明らかだったことがわかった。'),
(23, 'ambush', '待ち伏せ;~を待ち伏せする', '/ˈæmbʊʃ/', 'アンブッシュ',
  'The soldiers narrowly escaped an ambush that had been meticulously planned by the insurgents.',
  '兵士たちは反乱軍が入念に計画した待ち伏せからかろうじて逃れた。',
  'Journalists ambushed the politician outside the courthouse, demanding answers about the corruption scandal.',
  'ジャーナリストたちは裁判所の外で政治家を待ち伏せし、汚職スキャンダルについての回答を求めた。'),
(24, 'zenith', '頂点、絶頂;天頂', '/ˈzɛnɪθ/', 'ゼニス',
  'The Renaissance is widely considered to represent the zenith of artistic achievement in Western civilization.',
  'ルネサンスは西洋文明における芸術的達成の頂点を象徴すると広く考えられている。',
  'The athlete reached the zenith of her career when she won three consecutive Olympic gold medals.',
  'その選手はオリンピックで3連続金メダルを獲得したとき、キャリアの絶頂に達した。'),
(25, 'prognosis', '(病気の)予後、(経過)予測;(情報による)予測', '/prɒɡˈnoʊsɪs/', 'プログノーシス',
  'The doctor offered an optimistic prognosis, suggesting the patient would make a full recovery within months.',
  '医師は楽観的な予後を示し、患者は数ヶ月以内に完全に回復するだろうと述べた。',
  'Economic analysts gave a grim prognosis for the housing market, predicting a prolonged downturn.',
  '経済アナリストたちは住宅市場について厳しい予測を示し、長期的な低迷を予想した。'),
(26, 'meticulous', '細心の注意を払った', '/məˈtɪkjʊləs/', 'メティキュラス',
  'The archaeologist''s meticulous documentation of the excavation site earned widespread acclaim from her peers.',
  'その考古学者の発掘現場に対する細心の注意を払った記録は、同僚たちから広範な称賛を得た。',
  'He was meticulous in his preparation for the trial, reviewing every piece of evidence multiple times.',
  '彼は裁判の準備に細心の注意を払い、すべての証拠を複数回確認した。'),
(27, 'acrimony', '(言葉・態度などの)とげとげしさ', '/ˈækrɪmoʊni/', 'アクリモニー',
  'The acrimony between the two political factions intensified as the election drew closer.',
  '選挙が近づくにつれ、二つの政治派閥間のとげとげしさは激しさを増した。',
  'Despite the acrimony of their divorce proceedings, both parents remained committed to their children''s welfare.',
  '離婚手続きのとげとげしさにもかかわらず、両親とも子供たちの福祉に尽力し続けた。'),
(28, 'propensity', '(好ましくない)傾向、性癖', '/prəˈpɛnsɪti/', 'プロペンシティ',
  'His propensity for making impulsive decisions often led to unnecessary complications in his professional life.',
  '衝動的な決断を下す彼の傾向は、しばしば仕事上の不必要な複雑さを招いた。',
  'Researchers identified a genetic propensity for certain autoimmune disorders in the studied population.',
  '研究者たちは調査対象の集団において、特定の自己免疫疾患に対する遺伝的な傾向を特定した。'),
(29, 'entice', '~を誘惑する、おびき寄せる', '/ɪnˈtaɪs/', 'インタイス',
  'The restaurant enticed customers with a generous opening promotion offering half-price meals for a month.',
  'そのレストランは1ヶ月間半額の食事を提供する寛大なオープニングプロモーションで客を引きつけた。',
  'Tech companies entice top talent with lucrative salaries, stock options, and flexible working arrangements.',
  'テック企業は高額な給与、ストックオプション、柔軟な勤務形態で優秀な人材を引きつける。'),
(30, 'alienate', '(人)を遠ざける、疎外する', '/ˈeɪliəneɪt/', 'エイリアネイト',
  'The CEO''s authoritarian management style gradually alienated even his most loyal supporters on the board.',
  'CEOの権威主義的な経営スタイルは、取締役会の最も忠実な支持者さえも次第に遠ざけた。',
  'The controversial policy risked alienating a significant portion of the party''s traditional voter base.',
  'その物議を醸す政策は、党の伝統的な有権者基盤のかなりの部分を疎外する危険があった。'),
(31, 'exonerate', '(人)の無罪を証明する', '/ɪɡˈzɒnəreɪt/', 'イグゾナレイト',
  'DNA evidence collected from the crime scene ultimately exonerated the man who had spent fifteen years in prison.',
  '犯罪現場から採取されたDNA証拠が、15年間刑務所にいた男性の無罪を最終的に証明した。',
  'The independent investigation exonerated the officer of all charges related to misconduct.',
  '独立した調査により、その警官は不正行為に関するすべての容疑で無罪が証明された。'),
(32, 'clamor', '(群衆・交通などの)騒音、騒ぎ;(大きな声で)求める、要求する', '/ˈklæmər/', 'クラマー',
  'Citizens clamored for immediate government action following the devastating earthquake that struck the region.',
  '地域を襲った壊滅的な地震の後、市民は政府の即座の対応を強く要求した。',
  'The clamor of protesters outside the parliament building could be heard several blocks away.',
  '国会議事堂の外の抗議者たちの騒ぎは数ブロック先まで聞こえた。'),
(33, 'respite', '(仕事などの)小休止、休息', '/ˈrɛspɪt/', 'レスピット',
  'The ceasefire provided a brief respite for civilians who had endured months of relentless bombing.',
  '停戦は何ヶ月もの容赦ない爆撃に耐えてきた民間人にわずかな休息を与えた。',
  'The weekend retreat offered a welcome respite from the pressures of her demanding corporate position.',
  '週末のリトリートは、彼女の厳しい企業での職務のプレッシャーからの歓迎すべき小休止となった。'),
(34, 'huddle', '(寒さ・恐怖で)身を寄せ合う、群がる;集まり、寄せ集め', '/ˈhʌdl/', 'ハドル',
  'The refugees huddled together for warmth inside the makeshift shelter as temperatures plummeted.',
  '気温が急落する中、難民たちは仮設シェルターの中で暖を取るために身を寄せ合った。',
  'The executives held a quick huddle in the conference room to discuss their response to the crisis.',
  '幹部たちは危機への対応を話し合うために会議室で素早い集まりを持った。'),
(35, 'figment', '空想、作り事', '/ˈfɪɡmənt/', 'フィグメント',
  'The psychiatrist assured the patient that the voices he heard were merely a figment of his imagination.',
  '精神科医は、彼が聞いた声は単なる想像の産物に過ぎないと患者を安心させた。',
  'What initially appeared to be a figment of conspiracy theorists turned out to have a basis in fact.',
  '当初は陰謀論者の作り事に思えたものが、実際には事実に基づいていることが判明した。'),
(36, 'tenacious', '粘り強い、あきらめない', '/tɪˈneɪʃəs/', 'テネイシャス',
  'Her tenacious pursuit of justice for the victims eventually led to landmark legislative reform.',
  '被害者のための正義を粘り強く追求した結果、画期的な立法改革につながった。',
  'The tenacious investigative journalist spent three years uncovering the corporate fraud scheme.',
  'その粘り強い調査報道記者は3年かけて企業詐欺のスキームを暴いた。'),
(37, 'extol', '~を絶賛する、激賞する', '/ɪkˈstoʊl/', 'イクストール',
  'The keynote speaker extolled the virtues of interdisciplinary collaboration in advancing scientific research.',
  '基調講演者は科学研究の発展における学際的協力の美徳を絶賛した。',
  'Critics universally extolled the director''s latest film as a masterpiece of contemporary cinema.',
  '批評家たちはこぞってその監督の最新作を現代映画の傑作と激賞した。'),
(38, 'aversion', '嫌悪、反感', '/əˈvɜːrʒən/', 'アヴァージョン',
  'His deep aversion to public speaking prevented him from accepting the prestigious award in person.',
  '人前で話すことへの深い嫌悪感のせいで、彼はその名誉ある賞を自ら受け取ることができなかった。',
  'Many consumers have developed a strong aversion to products tested on animals.',
  '多くの消費者が動物実験された製品に対する強い反感を抱くようになっている。'),
(39, 'immaculate', '(場所・服などが)清潔な、汚れていない', '/ɪˈmækjʊlət/', 'イマキュレット',
  'Despite having three young children, she maintained an immaculate household that impressed every visitor.',
  '3人の幼い子供がいるにもかかわらず、彼女はすべての来客を感心させる清潔な家を維持していた。',
  'The hotel''s immaculate rooms and impeccable service justified its reputation as a five-star establishment.',
  'そのホテルの汚れのない客室と非の打ちどころのないサービスは、五つ星施設としての評判を正当化していた。'),
(40, 'gregarious', '社交的な、人づきあいのよい', '/ɡrɪˈɡɛəriəs/', 'グリゲアリアス',
  'Her gregarious personality made her ideally suited for a career in public relations and event management.',
  '彼女の社交的な性格は、広報やイベント管理のキャリアに理想的に適していた。',
  'Unlike his gregarious twin brother, he preferred solitary activities such as reading and painting.',
  '社交的な双子の兄弟とは異なり、彼は読書や絵画などの一人での活動を好んだ。'),
(41, 'ostracize', '(人)をのけ者にする', '/ˈɒstrəsaɪz/', 'オストラサイズ',
  'The whistleblower was ostracized by former colleagues who viewed his actions as a betrayal of trust.',
  '内部告発者は、彼の行為を信頼の裏切りと見なした元同僚たちからのけ者にされた。',
  'Communities that ostracize individuals for expressing dissenting opinions stifle intellectual growth.',
  '反対意見を表明する個人をのけ者にするコミュニティは知的成長を抑圧する。'),
(42, 'uncouth', '(人・行為などが)無作法な、粗野な', '/ʌnˈkuːθ/', 'アンクース',
  'His uncouth behavior at the diplomatic reception embarrassed his entire delegation.',
  '外交レセプションでの彼の無作法な振る舞いは、彼の代表団全体を当惑させた。',
  'She found his uncouth table manners so appalling that she declined a second dinner invitation.',
  '彼女は彼の粗野なテーブルマナーをあまりにもひどいと感じ、2度目のディナーの招待を断った。'),
(43, 'salient', '(特徴・事実などが)顕著な、目立った', '/ˈseɪliənt/', 'セイリアント',
  'The report highlighted the salient differences between the two proposed approaches to urban development.',
  '報告書は都市開発に対する二つの提案されたアプローチの間の顕著な違いを強調した。',
  'One of the most salient features of the new legislation is its emphasis on corporate transparency.',
  '新しい法律の最も目立った特徴の一つは、企業の透明性に重点を置いていることである。'),
(44, 'mayhem', '騒動、大混乱', '/ˈmeɪhɛm/', 'メイヘム',
  'The sudden power outage in the stadium caused complete mayhem as thousands of spectators rushed toward the exits.',
  'スタジアムの突然の停電により何千人もの観客が出口に殺到し、完全な大混乱が生じた。',
  'The announcement of the company''s bankruptcy created financial mayhem in the stock market.',
  '同社の破産発表は株式市場に経済的な大混乱を引き起こした。'),
(45, 'defunct', '現存しない、消滅した;死亡した、故~', '/dɪˈfʌŋkt/', 'ディファンクト',
  'The building that once housed the now-defunct newspaper has been converted into a modern art gallery.',
  'かつて今は消滅した新聞社が入っていた建物は、現代美術のギャラリーに改装された。',
  'Several defunct satellites continue to orbit the Earth, contributing to the growing problem of space debris.',
  'いくつかの機能停止した衛星が地球の周回を続け、増大する宇宙ゴミの問題に寄与している。'),
(46, 'petrify', '(恐怖などで)~をすくませる;~を石化する', '/ˈpɛtrɪfaɪ/', 'ペトリファイ',
  'The sight of the enormous spider petrified her, leaving her completely unable to move or scream.',
  '巨大なクモを目にして彼女は恐怖ですくみ、全く動くことも叫ぶこともできなくなった。',
  'The volcanic ash petrified the ancient forest, preserving its trees in remarkable detail for millennia.',
  '火山灰が古代の森を石化し、その木々を何千年にもわたり驚くべき詳細さで保存した。'),
(47, 'invoke', '(法・権利など)を行使する、発動する;(感情など)を呼び起こす、想起させる', '/ɪnˈvoʊk/', 'インヴォーク',
  'The president invoked emergency powers to mobilize the military in response to the natural disaster.',
  '大統領は自然災害に対応して軍を動員するために緊急権限を発動した。',
  'The defense attorney invoked the constitutional right to remain silent on behalf of her client.',
  '弁護人は依頼人に代わって黙秘権という憲法上の権利を行使した。'),
(48, 'rebuke', '(人)を強く非難する、叱責する;非難、叱責', '/rɪˈbjuːk/', 'リビューク',
  'The committee issued a formal rebuke to the senator for his inappropriate conduct during the hearing.',
  '委員会は公聴会での不適切な行為について、その上院議員に正式な叱責を出した。',
  'She rebuked her subordinate for repeatedly failing to meet the project deadlines.',
  '彼女はプロジェクトの期限を繰り返し守れなかった部下を強く非難した。'),
(49, 'accolade', '称賛', '/ˈækəleɪd/', 'アコレイド',
  'The film received numerous accolades at international festivals, including the coveted Palme d''Or.',
  'その映画は名高いパルムドールを含む国際映画祭で数々の称賛を受けた。',
  'Winning the industry''s highest accolade validated years of tireless research and innovation.',
  '業界最高の称賛を勝ち取ったことは、長年の絶え間ない研究と革新を証明した。'),
(50, 'solace', '慰め、癒し', '/ˈsɒlɪs/', 'ソリス',
  'After the tragic loss of her husband, she found solace in the unwavering support of her closest friends.',
  '夫の悲劇的な死後、彼女は最も親しい友人たちの揺るぎない支えに慰めを見出した。',
  'Music provided him with a source of solace during the most turbulent period of his life.',
  '音楽は人生で最も激動の時期に彼にとって慰めの源となった。');
