-- words テーブル INSERT文 (No.101 ~ No.150)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(101, 'irate', '激怒した、怒り心頭の', '/aɪˈreɪt/', 'アイレイト',
  'The irate customer demanded to speak with the manager after being kept waiting for over an hour.',
  '激怒した顧客は、1時間以上待たされた後、マネージャーとの面談を要求した。',
  'Residents became irate when the city council approved the construction of a landfill near their neighborhood.',
  '市議会が近隣にごみ埋立地の建設を承認したとき、住民たちは怒り心頭になった。'),
(102, 'clique', '徒党、派閥', '/kliːk/', 'クリーク',
  'The exclusive clique of senior executives made all the important decisions behind closed doors.',
  '上級幹部の排他的な派閥が、密室で重要な決定をすべて下していた。',
  'She felt ostracized by the clique that dominated the academic department.',
  '彼女はその学部を牛耳る派閥から排斥されていると感じた。'),
(103, 'sporadic', '散発的な、不定期に起きる', '/spəˈrædɪk/', 'スポラディック',
  'Sporadic outbreaks of violence continued to disrupt the peace negotiations.',
  '散発的な暴力の発生が和平交渉を妨げ続けた。',
  'The region experienced sporadic rainfall throughout the dry season, insufficient to sustain the crops.',
  'その地域では乾季を通じて散発的な降雨があったが、作物を維持するには不十分だった。'),
(104, 'abate', '(嵐・雨などが)弱まる;(痛みなどが)和らぐ', '/əˈbeɪt/', 'アベイト',
  'The storm showed no signs of abating, so the authorities extended the evacuation order.',
  '嵐は弱まる兆しを見せなかったため、当局は避難命令を延長した。',
  'Public outrage over the scandal did not abate despite the politician''s repeated apologies.',
  'スキャンダルに対する国民の怒りは、その政治家が繰り返し謝罪したにもかかわらず和らがなかった。'),
(105, 'idyllic', '(場所などが)牧歌的な、のどかな', '/aɪˈdɪlɪk/', 'アイディリック',
  'They spent their honeymoon in an idyllic village nestled among the rolling hills of Tuscany.',
  '彼らはトスカーナのなだらかな丘陵に囲まれた牧歌的な村で新婚旅行を過ごした。',
  'The idyllic setting of the countryside retreat belied the tensions simmering within the family.',
  'のどかな田舎の別荘の風景は、家族内でくすぶる緊張を覆い隠していた。'),
(106, 'exquisite', '精巧な、繊細で美しい', '/ɪkˈskwɪzɪt/', 'イクスクウィジット',
  'The museum displayed an exquisite collection of hand-carved ivory figurines from the Edo period.',
  'その美術館は江戸時代の精巧な手彫りの象牙製小像のコレクションを展示していた。',
  'Her exquisite attention to detail earned her a reputation as one of the finest artisans in the country.',
  '彼女の繊細な細部へのこだわりが、国内有数の名工としての評価をもたらした。'),
(107, 'tarnish', '(評判・名声など)を傷つける;(金属など)の光沢を失わせる', '/ˈtɑːrnɪʃ/', 'ターニッシュ',
  'The corruption allegations tarnished the reputation of the once-revered institution.',
  '汚職疑惑は、かつて尊敬されていた機関の評判を傷つけた。',
  'Exposure to humidity will gradually tarnish silver jewelry if it is not properly stored.',
  '適切に保管しなければ、湿気にさらされることで銀のジュエリーは徐々に光沢を失う。'),
(108, 'vindicate', '(主張・行為など)の正しさを立証する;(人)の潔白を証明する', '/ˈvɪndɪkeɪt/', 'ヴィンディケイト',
  'The newly discovered evidence vindicated the scientist whose theory had been dismissed for decades.',
  '新たに発見された証拠が、何十年も否定されてきたその科学者の理論の正しさを立証した。',
  'The court ruling vindicated the whistleblower who had risked her career to expose the fraud.',
  'その判決は、不正を暴露するためにキャリアを危険にさらした内部告発者の潔白を証明した。'),
(109, 'auspicious', '幸先のよい、吉兆の', '/ɔːˈspɪʃəs/', 'オースピシャス',
  'The successful launch of their first product was an auspicious beginning for the startup.',
  '最初の製品の成功した発売は、そのスタートアップにとって幸先のよい出発だった。',
  'In many Asian cultures, the number eight is considered auspicious and associated with prosperity.',
  '多くのアジア文化において、数字の8は吉兆とされ、繁栄と結びつけられている。'),
(110, 'fastidious', '①細心の注意を払う ②潔癖な', '/fæˈstɪdiəs/', 'ファスティディアス',
  'The fastidious editor scrutinized every sentence for grammatical errors before approving the manuscript.',
  '細心の注意を払うその編集者は、原稿を承認する前にすべての文の文法的誤りを精査した。',
  'He was so fastidious about cleanliness that he wiped down every surface in his office twice a day.',
  '彼は潔癖すぎて、オフィスのあらゆる面を1日2回拭いていた。'),
(111, 'encapsulate', '(思想・事実など)を要約する;~をカプセルに包む', '/ɪnˈkæpsjʊleɪt/', 'インキャプシュレイト',
  'The documentary encapsulates the struggles and triumphs of the civil rights movement in just ninety minutes.',
  'そのドキュメンタリーはわずか90分で公民権運動の苦闘と勝利を要約している。',
  'Her closing remarks perfectly encapsulated the essence of the three-day conference.',
  '彼女の閉会の辞は、3日間の会議の本質を完璧に要約していた。'),
(112, 'deferential', '敬意を払う、丁寧な', '/ˌdefəˈrenʃəl/', 'デファレンシャル',
  'The young diplomat maintained a deferential tone throughout the negotiations with the senior officials.',
  '若い外交官は、高官との交渉を通じて終始敬意を払った口調を保った。',
  'In Japanese business culture, employees are expected to be deferential toward their superiors.',
  '日本のビジネス文化では、従業員は上司に対して敬意を払うことが求められる。'),
(113, 'annex', '(武力で)(領土・国など)を併合する、編入する', '/əˈneks/', 'アネクス',
  'The empire annexed the neighboring territory following a swift military campaign.',
  'その帝国は迅速な軍事作戦の後、隣接する領土を併合した。',
  'The decision to annex the disputed region provoked international condemnation and economic sanctions.',
  '紛争地域を編入する決定は、国際的な非難と経済制裁を引き起こした。'),
(114, 'pungent', '①(におい・味などが)刺激の強い ②(批評などが)辛らつな', '/ˈpʌndʒənt/', 'パンジェント',
  'The pungent aroma of fermented fish sauce permeated the entire kitchen.',
  '発酵した魚醤の刺激の強い香りがキッチン全体に充満した。',
  'The critic delivered a pungent review of the film, calling it pretentious and vacuous.',
  'その批評家は辛らつな映画評を発表し、気取っていて中身がないと評した。'),
(115, 'conjecture', '推測、憶測(すること);…と推測[憶測]する', '/kənˈdʒektʃər/', 'コンジェクチャー',
  'In the absence of concrete evidence, the investigators could only offer conjecture about the cause of the accident.',
  '具体的な証拠がない中、調査員たちは事故の原因について憶測を述べることしかできなかった。',
  'Scientists conjectured that the newly discovered exoplanet might harbor conditions suitable for life.',
  '科学者たちは、新しく発見された太陽系外惑星が生命に適した条件を持つ可能性があると推測した。'),
(116, 'muster', '(勇気など)を奮い起こす;(助力など)を求める;(兵隊など)を召集する', '/ˈmʌstər/', 'マスター',
  'She mustered the courage to confront her supervisor about the unfair working conditions.',
  '彼女は不公平な労働条件について上司に立ち向かう勇気を奮い起こした。',
  'The general mustered his remaining troops for one final assault on the enemy stronghold.',
  '将軍は敵の要塞への最後の攻撃のために残りの部隊を召集した。'),
(117, 'forfeit', '(罰として)(財産・権利など)を失う、はく奪される', '/ˈfɔːrfɪt/', 'フォーフィット',
  'The athlete was forced to forfeit her medal after testing positive for a banned substance.',
  'その選手は禁止薬物の陽性反応が出た後、メダルを剥奪された。',
  'Companies that violate the terms of the contract may forfeit their right to future government tenders.',
  '契約条件に違反した企業は、将来の政府入札への権利を失う可能性がある。'),
(118, 'murky', '①(水が)濁った、見通せない ②(闇・霧などが)濃い、暗い', '/ˈmɜːrki/', 'マーキー',
  'The divers struggled to navigate through the murky waters of the flooded cave system.',
  'ダイバーたちは浸水した洞窟系の濁った水の中を進むのに苦労した。',
  'The murky details of the financial transaction raised suspicions of money laundering.',
  'その金融取引の不透明な詳細が、資金洗浄の疑いを引き起こした。'),
(119, 'bigotry', '偏狭、偏屈な行為[考え]', '/ˈbɪɡətri/', 'ビゴトリー',
  'The organization was founded to combat bigotry and promote tolerance in multicultural communities.',
  'その団体は偏狭と闘い、多文化コミュニティにおける寛容を推進するために設立された。',
  'His speech was widely condemned as an expression of bigotry masquerading as political commentary.',
  '彼のスピーチは、政治的論評を装った偏狭の表明として広く非難された。'),
(120, 'augment', '~を増加[増大]させる', '/ɔːɡˈment/', 'オーグメント',
  'The company decided to augment its workforce by hiring three hundred additional engineers.',
  'その会社は300人の追加エンジニアを雇用して労働力を増大させることを決定した。',
  'The researcher augmented the dataset with satellite imagery to improve the accuracy of the model.',
  '研究者はモデルの精度を向上させるために、衛星画像でデータセットを増強した。'),
(121, 'reiterate', '(要求・命令など)を何度も繰り返して言う', '/riːˈɪtəreɪt/', 'リイタレイト',
  'The chairperson reiterated the importance of adhering to ethical standards in all business dealings.',
  '議長はすべての商取引において倫理基準を遵守することの重要性を繰り返し述べた。',
  'Despite the backlash, the minister reiterated his commitment to the proposed reforms.',
  '反発にもかかわらず、大臣は提案された改革への決意を繰り返し表明した。'),
(122, 'compunction', '良心の呵責、悔恨', '/kəmˈpʌŋkʃən/', 'コンパンクション',
  'The CEO showed no compunction about laying off thousands of employees to maximize profits.',
  'そのCEOは利益を最大化するために数千人の従業員を解雇することに良心の呵責を示さなかった。',
  'Without the slightest compunction, the spy betrayed his country for a substantial sum of money.',
  'そのスパイはわずかな良心の呵責もなく、多額の金銭のために祖国を裏切った。'),
(123, 'deluge', '①大量、殺到 ②大洪水;豪雨', '/ˈdeljuːdʒ/', 'デリュージ',
  'The customer service department was overwhelmed by a deluge of complaints following the product recall.',
  'カスタマーサービス部門は製品リコール後に殺到した大量の苦情に圧倒された。',
  'The unprecedented deluge caused rivers to burst their banks and inundate entire villages.',
  '前例のない豪雨により河川が氾濫し、村全体が水没した。'),
(124, 'diffident', '自信のない、気後れした', '/ˈdɪfɪdənt/', 'ディフィデント',
  'Despite her brilliant academic record, she remained diffident about speaking in public.',
  '輝かしい学業成績にもかかわらず、彼女は人前で話すことに自信がなかった。',
  'The diffident young author struggled to promote his debut novel at the literary festival.',
  '気後れした若い作家は、文学祭でデビュー小説を宣伝するのに苦労した。'),
(125, 'mollify', '(人)をなだめる;(感情)を和らげる', '/ˈmɒlɪfaɪ/', 'モリファイ',
  'The government issued a formal apology in an attempt to mollify the protesters.',
  '政府は抗議者たちをなだめるために正式な謝罪を発表した。',
  'Offering a generous compensation package helped mollify the concerns of the displaced residents.',
  '手厚い補償パッケージの提供が、立ち退きを迫られた住民の懸念を和らげるのに役立った。'),
(126, 'torment', '~を苦しめる、悩ませる;苦悩、苦痛', '/ˈtɔːrment/', 'トーメント',
  'The memory of the tragic accident continued to torment him long after the physical wounds had healed.',
  'その悲惨な事故の記憶は、身体の傷が癒えた後も長く彼を苦しめ続けた。',
  'Years of torment at the hands of his oppressors left indelible scars on his psyche.',
  '抑圧者たちの手による長年の苦悩が、彼の精神に消えない傷跡を残した。'),
(127, 'douse', '①(水をかけて)(火)を消す ②(明かりなど)を消す', '/daʊs/', 'ダウス',
  'Firefighters managed to douse the blaze before it engulfed the neighboring buildings.',
  '消防士たちは、火災が隣接する建物を飲み込む前に消火することに成功した。',
  'The captain ordered the crew to douse all lights as the ship entered hostile waters.',
  '船が敵対水域に入る際、船長は乗組員にすべての灯火を消すよう命じた。'),
(128, 'debacle', '(試みなどの)大失敗;(選挙などの)大敗', '/dɪˈbɑːkəl/', 'ディバークル',
  'The failed product launch was described as the biggest debacle in the company''s history.',
  '失敗した製品の発売は、同社の歴史上最大の大失敗と評された。',
  'After the electoral debacle, the party leadership resigned en masse to take responsibility.',
  '選挙の大敗の後、党の指導部は責任を取って一斉に辞任した。'),
(129, 'backlog', '(仕事などの大量の)やり残し、未処理分', '/ˈbæklɒɡ/', 'バックログ',
  'The court system faces a significant backlog of cases that could take years to resolve.',
  '裁判制度は、解決に何年もかかりうる大量の未処理案件を抱えている。',
  'After returning from maternity leave, she was confronted with a daunting backlog of unanswered emails.',
  '産休から復帰した後、彼女は膨大な未返信メールのやり残しに直面した。'),
(130, 'resplendent', 'きらびやかな、まばゆい', '/rɪˈsplendənt/', 'リスプレンデント',
  'The palace ballroom was resplendent with crystal chandeliers and gilded decorations.',
  '宮殿の舞踏室はクリスタルのシャンデリアと金箔の装飾できらびやかだった。',
  'The bride looked resplendent in her hand-embroidered silk gown as she walked down the aisle.',
  '花嫁は手刺繍のシルクのガウンを身にまとい、バージンロードをまばゆいばかりの姿で歩いた。'),
(131, 'quaint', '(古風で)趣のある', '/kweɪnt/', 'クウェイント',
  'The quaint fishing village with its cobblestone streets attracted tourists from around the world.',
  '石畳の通りのあるその趣のある漁村は、世界中から観光客を引きつけた。',
  'What was once considered a quaint tradition has now become a major cultural festival.',
  'かつては趣のある伝統と見なされていたものが、今では主要な文化祭になっている。'),
(132, 'tepid', '①(飲み物・液体が)なまぬるい ②(感情などが)熱意のない、しらけた', '/ˈtepɪd/', 'テピッド',
  'The audience gave the performance a tepid reception, applauding politely but without enthusiasm.',
  '観客はその演技に熱意のない反応を示し、礼儀正しくも冷めた拍手を送った。',
  'She took a sip of the tepid coffee and grimaced, wishing she had reheated it.',
  '彼女はなまぬるいコーヒーを一口飲んで顔をしかめ、温め直せばよかったと思った。'),
(133, 'malleable', '①(金属が)可鍛性の、容易に変形できる ②(人・考えが)従順な、人に影響されやすい', '/ˈmæliəbəl/', 'マリアブル',
  'Gold is one of the most malleable metals, capable of being hammered into extremely thin sheets.',
  '金は最も可鍛性の高い金属の一つで、極めて薄いシートに打ち延ばすことができる。',
  'Young children are particularly malleable, easily absorbing the values and attitudes of those around them.',
  '幼い子どもは特に影響されやすく、周囲の人々の価値観や態度を容易に吸収する。'),
(134, 'poignant', '心に強く訴える、感動的な', '/ˈpɔɪnjənt/', 'ポイニャント',
  'The documentary featured a poignant interview with survivors of the disaster.',
  'そのドキュメンタリーは災害の生存者たちとの心に強く訴えるインタビューを特集していた。',
  'Her poignant memoir about growing up in poverty resonated with readers across the globe.',
  '貧困の中で育った彼女の感動的な回顧録は、世界中の読者の共感を呼んだ。'),
(135, 'exude', '(感情・自信など)をあふれ出させる', '/ɪɡˈzuːd/', 'イグズード',
  'The newly appointed ambassador exuded confidence as she addressed the assembly for the first time.',
  '新たに任命された大使は、初めて議会で演説する際に自信をあふれ出させた。',
  'The ancient temple exuded an atmosphere of serenity that calmed even the most restless visitors.',
  'その古代の寺院は、最も落ち着きのない訪問者をも穏やかにする静寂の雰囲気を漂わせていた。'),
(136, 'plague', '[be plagued]悩む、苦しむ;(多くの死者を出す)疫病、伝染病', '/pleɪɡ/', 'プレイグ',
  'The project has been plagued by delays and cost overruns since its inception.',
  'そのプロジェクトは発足以来、遅延と費用超過に悩まされ続けている。',
  'The bubonic plague devastated Europe in the fourteenth century, killing an estimated one-third of the population.',
  'ペスト（腺ペスト）は14世紀にヨーロッパを壊滅させ、推定で人口の3分の1を死に至らしめた。'),
(137, 'detrimental', '有害な、不利益な', '/ˌdetrɪˈmentəl/', 'デトリメンタル',
  'Prolonged exposure to excessive noise levels can be detrimental to one''s hearing.',
  '過度な騒音レベルへの長期間の曝露は、聴力に有害となりうる。',
  'The trade embargo proved detrimental to the country''s already fragile economy.',
  'その貿易禁輸措置は、すでに脆弱だった同国の経済に不利益であることが判明した。'),
(138, 'inadvertently', 'うっかり、不注意に', '/ˌɪnədˈvɜːrtəntli/', 'イナドヴァータントリー',
  'The journalist inadvertently disclosed classified information during the live broadcast.',
  'そのジャーナリストは生放送中にうっかり機密情報を漏らしてしまった。',
  'By inadvertently deleting the database backup, the technician caused a major system failure.',
  'データベースのバックアップを不注意に削除したことで、その技術者は重大なシステム障害を引き起こした。'),
(139, 'culminate', '達する、終わる;最高潮に達する', '/ˈkʌlmɪneɪt/', 'カルミネイト',
  'Years of painstaking research culminated in a groundbreaking discovery that revolutionized the field.',
  '長年の入念な研究が、その分野に革命をもたらす画期的な発見に結実した。',
  'The festival will culminate in a spectacular fireworks display over the harbor.',
  'その祭りは港上空での壮大な花火大会で最高潮に達する。'),
(140, 'mundane', '①平凡な、ありふれた、つまらない ②現世の、世俗的な', '/mʌnˈdeɪn/', 'マンデイン',
  'She longed to escape the mundane routine of her office job and travel the world.',
  '彼女はオフィスワークの平凡な日常から逃れて世界を旅することを切望していた。',
  'Even the most mundane tasks can become meaningful when approached with the right mindset.',
  '最もありふれた作業でも、正しい心構えで取り組めば意義あるものになりうる。'),
(141, 'succumb', '(誘惑・圧力・攻撃などに)屈する、負ける', '/səˈkʌm/', 'サカム',
  'After months of relentless pressure, the government finally succumbed to the demands of the opposition.',
  '何か月にもわたる容赦ない圧力の後、政府はついに野党の要求に屈した。',
  'Many small businesses succumbed to the economic downturn and were forced to close permanently.',
  '多くの中小企業が景気後退に負けて、恒久的に閉業を余儀なくされた。'),
(142, 'vicinity', '付近、近辺', '/vɪˈsɪnɪti/', 'ヴィシニティ',
  'Police cordoned off the vicinity of the explosion and urged residents to remain indoors.',
  '警察は爆発現場の付近を封鎖し、住民に屋内にとどまるよう促した。',
  'There are several renowned research institutions in the vicinity of the university campus.',
  '大学キャンパスの近辺にはいくつかの著名な研究機関がある。'),
(143, 'perk', '(通常の給与に加えて受け取る)手当、特典', '/pɜːrk/', 'パーク',
  'One of the most attractive perks of the job is the generous housing allowance provided by the company.',
  'その仕事の最も魅力的な特典の一つは、会社が提供する手厚い住宅手当である。',
  'Free meals and on-site childcare are among the perks that help the firm retain top talent.',
  '無料の食事と社内保育は、同社が優秀な人材を維持するのに役立つ特典に含まれる。'),
(144, 'fluctuate', '変動する、上下する', '/ˈflʌktʃueɪt/', 'フラクチュエイト',
  'Oil prices fluctuate dramatically in response to geopolitical tensions and supply disruptions.',
  '原油価格は地政学的緊張や供給途絶に反応して劇的に変動する。',
  'Her mood tended to fluctuate throughout the day, making it difficult for colleagues to predict her reactions.',
  '彼女の気分は一日を通して上下する傾向があり、同僚が彼女の反応を予測するのは困難だった。'),
(145, 'insurmountable', '(困難・障害などが)乗り越えられない、克服できない', '/ˌɪnsərˈmaʊntəbəl/', 'インサーマウンタブル',
  'What initially appeared to be an insurmountable obstacle was overcome through innovative engineering.',
  '当初は乗り越えられない障害に見えたものが、革新的な工学によって克服された。',
  'The refugees faced seemingly insurmountable challenges in rebuilding their lives in a foreign country.',
  '難民たちは外国での生活再建において、一見克服できない課題に直面した。'),
(146, 'impending', '差し迫った', '/ɪmˈpendɪŋ/', 'インペンディング',
  'The government issued warnings about the impending typhoon and advised coastal residents to evacuate.',
  '政府は差し迫った台風について警告を発し、沿岸住民に避難を勧告した。',
  'A sense of impending doom pervaded the financial markets as the debt crisis deepened.',
  '債務危機が深刻化するにつれ、差し迫った破局の予感が金融市場に蔓延した。'),
(147, 'contentious', '(問題などが)論議を呼ぶ、物議をかもす', '/kənˈtenʃəs/', 'コンテンシャス',
  'The contentious proposal to build a nuclear power plant divided the community into fierce opposing camps.',
  '原子力発電所を建設するという物議をかもす提案が、地域社会を激しく対立する陣営に分裂させた。',
  'Immigration policy remains one of the most contentious issues in contemporary politics.',
  '移民政策は現代政治において最も論議を呼ぶ問題の一つであり続けている。'),
(148, 'retaliation', '報復、仕返し', '/rɪˌtæliˈeɪʃən/', 'リタリエイション',
  'The country imposed heavy tariffs in retaliation for the trade restrictions placed on its exports.',
  'その国は、自国の輸出に課された貿易制限への報復として重い関税を課した。',
  'Whistleblowers are legally protected from retaliation by their employers under federal law.',
  '内部告発者は連邦法の下で雇用主からの報復から法的に保護されている。'),
(149, 'circumvent', '(法・規制など)をかいくぐる;(問題・困難など)を回避する', '/ˌsɜːrkəmˈvent/', 'サーカムヴェント',
  'The corporation devised an elaborate scheme to circumvent the new environmental regulations.',
  'その企業は新しい環境規制をかいくぐるために精巧な策略を考案した。',
  'Engineers found a way to circumvent the technical limitations of the existing infrastructure.',
  '技術者たちは既存のインフラの技術的制約を回避する方法を見つけた。'),
(150, 'tout', '~を褒めちぎる、もてはやす', '/taʊt/', 'タウト',
  'The pharmaceutical company touted the new drug as a revolutionary treatment for chronic pain.',
  'その製薬会社は新薬を慢性痛の画期的な治療法として褒めちぎった。',
  'Critics accused the media of touting the candidate''s achievements while ignoring his controversies.',
  '批評家たちは、メディアがその候補者の実績をもてはやす一方で論争を無視していると非難した。');
