-- words テーブル INSERT文 (No.1051 ~ No.1100)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1051, 'unwitting', '無意識の、知らず知らずの', '/ʌnˈwɪtɪŋ/', 'アンウィティング',
  'She became an unwitting accomplice to the fraud by signing the documents without reading them.',
  '彼女は書類を読まずに署名したことで、知らず知らずのうちに詐欺の共犯者となった。',
  'The unwitting victims of the scam lost their life savings overnight.',
  'その詐欺の無意識の被害者たちは、一夜にして貯蓄を失った。'),
(1052, 'espouse', '(主義・説など)を支持する、採用する', '/ɪˈspaʊz/', 'イスパウズ',
  'The senator openly espoused the cause of environmental protection throughout her career.',
  'その上院議員はキャリアを通じて環境保護の大義を公然と支持した。',
  'He espoused a philosophy of nonviolence that won him widespread admiration.',
  '彼は非暴力の哲学を支持し、広く称賛を集めた。'),
(1053, 'inept', '能力に欠ける、不器用な', '/ɪˈnɛpt/', 'イネプト',
  'The inept handling of the crisis only exacerbated public anger.',
  '危機への不手際な対応は国民の怒りを悪化させるだけだった。',
  'He proved so inept at negotiations that the deal fell through entirely.',
  '彼は交渉に全く不向きであることが判明し、取引は完全に破談となった。'),
(1054, 'ostensible', '表向きの、建前の', '/ɒˈstɛnsɪbəl/', 'オステンシブル',
  'The ostensible reason for his resignation was health, but political pressure was the real cause.',
  '彼の辞任の表向きの理由は健康だったが、実際の原因は政治的圧力だった。',
  'Her ostensible calm belied the turmoil she felt inside.',
  '彼女の表向きの冷静さは、内面の動揺を隠していた。'),
(1055, 'haphazardly', '無計画に、でたらめに', '/hæpˈhæzərdli/', 'ハプハザードリー',
  'The books were haphazardly stacked on the floor, making it impossible to find anything.',
  '本が床にでたらめに積まれており、何も見つけることができなかった。',
  'Resources were allocated haphazardly, resulting in severe inefficiencies across departments.',
  '資源が無計画に配分され、各部門で深刻な非効率が生じた。'),
(1056, 'opaque', '(ガラス・液体などが)不透明な、光を通さない', '/oʊˈpeɪk/', 'オペイク',
  'The opaque glass of the bathroom window ensured complete privacy.',
  '浴室の不透明なガラスは完全なプライバシーを確保した。',
  'The committee''s decision-making process remains opaque to the general public.',
  '委員会の意思決定プロセスは一般市民には不透明なままである。'),
(1057, 'latent', '潜んだ;潜在的な', '/ˈleɪtənt/', 'レイテント',
  'The investigation revealed latent defects in the building''s foundation.',
  '調査により建物の基礎に潜在的な欠陥があることが明らかになった。',
  'Her latent talent for music emerged only after she began taking lessons at the age of forty.',
  '彼女の潜在的な音楽の才能は、40歳でレッスンを始めてからようやく開花した。'),
(1058, 'extradite', '(犯人・亡命者など)を(本国などに)引き渡す、送還する', '/ˈɛkstrədaɪt/', 'エクストラダイト',
  'The government agreed to extradite the suspect to face trial in his home country.',
  '政府はその容疑者を本国での裁判に臨ませるために引き渡すことに同意した。',
  'Efforts to extradite the fugitive were hampered by the lack of a bilateral treaty.',
  '逃亡者を送還する取り組みは、二国間条約の欠如により妨げられた。'),
(1059, 'revile', '(人・もの)を非難する、あしざまに言う', '/rɪˈvaɪl/', 'リヴァイル',
  'The politician was reviled by the press for his dishonest conduct.',
  'その政治家は不誠実な行為のためにマスコミからあしざまに言われた。',
  'Once reviled as a traitor, he was later vindicated by newly discovered evidence.',
  'かつて裏切り者として非難された彼は、後に新たに発見された証拠により汚名を晴らした。'),
(1060, 'configuration', '(部分・要素の)配置、配列', '/kənˌfɪɡjəˈreɪʃən/', 'コンフィギュレイション',
  'The unusual configuration of the rooms made the house difficult to furnish.',
  '部屋の変わった配置のせいで、その家は家具を入れるのが難しかった。',
  'Engineers altered the configuration of the circuit to improve its efficiency.',
  '技術者たちは効率を改善するために回路の配列を変更した。'),
(1061, 'veracity', '正直さ;正確さ、真実性', '/vəˈræsəti/', 'ヴェラシティ',
  'The journalist questioned the veracity of the government''s official statement.',
  'そのジャーナリストは政府の公式声明の真実性を疑った。',
  'Historians have long debated the veracity of the ancient manuscript.',
  '歴史家たちはその古代の写本の正確さについて長年議論してきた。'),
(1062, 'odious', '忌まわしい、嫌悪感を催す', '/ˈoʊdiəs/', 'オウディアス',
  'The dictator''s odious regime was finally overthrown by a popular uprising.',
  'その独裁者の忌まわしい政権はついに民衆蜂起によって打倒された。',
  'She found the very idea of betraying her colleagues odious and refused outright.',
  '彼女は同僚を裏切るという考え自体を忌まわしく思い、きっぱりと拒否した。'),
(1063, 'languid', '(人・動きなどが)元気がない、気だるい', '/ˈlæŋɡwɪd/', 'ラングウィッド',
  'The languid pace of life in the village was a welcome change from the hectic city.',
  '村の気だるい生活のペースは、慌ただしい都会からの嬉しい変化だった。',
  'After the heavy meal, the guests grew languid and retreated to the shade.',
  'たっぷりの食事の後、客たちは気だるくなり日陰に引きこもった。'),
(1064, 'mangle', '~をひどく傷つける、ずたずたにする;~を台無しにする', '/ˈmæŋɡəl/', 'マングル',
  'The machine mangled his hand so severely that surgery was required immediately.',
  '機械が彼の手をひどく傷つけたため、直ちに手術が必要になった。',
  'The translator mangled the original poem, stripping it of all its beauty.',
  '翻訳者は原詩を台無しにし、その美しさをすべて奪ってしまった。'),
(1065, 'extrapolate', '(既知の事実・観察から)~を推定する', '/ɪkˈstræpəleɪt/', 'イクストラポレイト',
  'Scientists extrapolated future climate trends from decades of temperature data.',
  '科学者たちは数十年の気温データから将来の気候傾向を推定した。',
  'It would be unwise to extrapolate too much from such a small sample size.',
  'そのような小さなサンプルサイズから過度に推定するのは賢明ではないだろう。'),
(1066, 'terse', '(人・言葉が)ぶっきらぼうな、素っ気ない', '/tɜːrs/', 'ターース',
  'His terse reply suggested that he was unwilling to discuss the matter further.',
  '彼の素っ気ない返答は、その件についてこれ以上議論する気がないことを示唆していた。',
  'The general issued a terse command, and the soldiers immediately obeyed.',
  '将軍がぶっきらぼうな命令を下すと、兵士たちは直ちに従った。'),
(1067, 'distend', '(肺・腹部などが)膨らむ、膨張する;~を膨張させる', '/dɪˈstɛnd/', 'ディステンド',
  'The child''s abdomen was visibly distended due to severe malnutrition.',
  'その子どもの腹部は深刻な栄養失調のために目に見えて膨らんでいた。',
  'The balloon distended to an alarming size before it finally burst.',
  '風船はついに破裂する前に驚くほどの大きさに膨張した。'),
(1068, 'scoff', '(人の考えなどを)あざ笑う', '/skɒf/', 'スコフ',
  'Critics scoffed at the proposal, calling it utterly impractical.',
  '批評家たちはその提案をあざ笑い、まったく非現実的だと言った。',
  'She scoffed at the notion that money alone could bring happiness.',
  '彼女はお金だけで幸せになれるという考えをあざ笑った。'),
(1069, 'felony', '(殺人・強盗などの)凶悪犯罪、重罪', '/ˈfɛləni/', 'フェロニー',
  'He was charged with a felony and faced up to twenty years in prison.',
  '彼は重罪で起訴され、最長20年の懲役に直面した。',
  'Committing a felony permanently disqualified her from holding public office.',
  '重罪を犯したことで、彼女は公職に就く資格を永久に失った。'),
(1070, 'bucolic', '田園的な、田舎の', '/bjuːˈkɒlɪk/', 'ビューコリック',
  'The painter captured the bucolic charm of the countryside in vivid detail.',
  'その画家は田園的な田舎の魅力を鮮やかな細部にわたって描き出した。',
  'They abandoned their urban lifestyle in favor of a more bucolic existence.',
  '彼らは都会の生活を捨て、より田園的な暮らしを選んだ。'),
(1071, 'truncate', '(文章など)を切り詰める;(幹・円すいなど)の先端を切って短くする', '/ˈtrʌŋkeɪt/', 'トランケイト',
  'The editor truncated the manuscript to meet the publisher''s strict word limit.',
  '編集者は出版社の厳しい語数制限を満たすために原稿を切り詰めた。',
  'The database automatically truncates entries that exceed the maximum character count.',
  'データベースは最大文字数を超えるエントリーを自動的に切り詰める。'),
(1072, 'cordially', '心から、真心を込めて', '/ˈkɔːrdʒəli/', 'コージャリー',
  'The host cordially invited all the delegates to the evening reception.',
  '主催者はすべての代表者を心から夕方のレセプションに招待した。',
  'She cordially thanked the volunteers for their tireless efforts during the campaign.',
  '彼女はキャンペーン中のたゆまぬ努力に対してボランティアたちに真心を込めて感謝した。'),
(1073, 'amity', '(特に国家・集団間の)友好、親善', '/ˈæməti/', 'アミティ',
  'The treaty was signed as a symbol of amity between the two nations.',
  'その条約は両国間の友好の象徴として調印された。',
  'A spirit of amity prevailed at the summit, paving the way for future cooperation.',
  '首脳会談では友好の精神が支配的で、将来の協力への道が開かれた。'),
(1074, 'truculent', '攻撃的な、好戦的な;残忍な', '/ˈtrʌkjələnt/', 'トラキュレント',
  'The truculent protesters clashed violently with the police outside the parliament.',
  '攻撃的な抗議者たちは議会の外で警察と激しく衝突した。',
  'His truculent demeanor made it impossible to hold a civil conversation with him.',
  '彼の好戦的な態度のせいで、彼と穏やかな会話をすることは不可能だった。'),
(1075, 'luminous', '(暗いところで)光を発する、輝く', '/ˈluːmɪnəs/', 'ルーミナス',
  'The luminous dial of the watch made it easy to read the time in the dark.',
  '時計の光を発する文字盤のおかげで暗闇でも時間を読み取るのが容易だった。',
  'Her luminous prose captivated readers and earned her the prestigious literary award.',
  '彼女の輝くような散文は読者を魅了し、名誉ある文学賞をもたらした。'),
(1076, 'ruffle', '(心など)をかき乱す、(人)をいら立たせる;(髪など)をくしゃくしゃにする、(羽など)を逆立てる', '/ˈrʌfəl/', 'ラッフル',
  'The unexpected criticism ruffled the normally composed chairman.',
  '予期せぬ批判が、普段は冷静な議長をいら立たせた。',
  'A sudden gust of wind ruffled the pages of the open book on the table.',
  '突風がテーブルの上の開いた本のページをくしゃくしゃにした。'),
(1077, 'incongruous', '場にそぐわない、調和しない', '/ɪnˈkɒŋɡruəs/', 'インコングルアス',
  'The modern glass tower looked incongruous amid the ancient stone buildings.',
  'その近代的なガラスの塔は、古代の石造りの建物の中で場にそぐわなく見えた。',
  'His jovial laughter seemed incongruous at such a somber occasion.',
  '彼の陽気な笑い声は、そのような厳粛な場にそぐわないように思えた。'),
(1078, 'bellow', '怒鳴る、叫ぶ', '/ˈbɛloʊ/', 'ベロウ',
  'The sergeant bellowed orders at the recruits standing in formation.',
  '軍曹は整列している新兵たちに命令を怒鳴った。',
  'He bellowed in pain when the heavy crate fell on his foot.',
  '重い木箱が足の上に落ちたとき、彼は痛みで叫んだ。'),
(1079, 'decree', '~を(法令で)命じる、布告する;(政府などの)法令、布告;判決', '/dɪˈkriː/', 'ディクリー',
  'The emperor decreed that all citizens must pay the new tax by the end of the month.',
  '皇帝はすべての国民が月末までに新しい税金を納めなければならないと布告した。',
  'A royal decree abolished the outdated law that had been in effect for centuries.',
  '王の法令が何世紀にもわたって有効だった時代遅れの法律を廃止した。'),
(1080, 'remuneration', '報酬、謝礼', '/rɪˌmjuːnəˈreɪʃən/', 'リミューナレイション',
  'The remuneration offered for the position was far below industry standards.',
  'そのポジションに提示された報酬は業界水準をはるかに下回っていた。',
  'She demanded fair remuneration for the additional hours she had worked.',
  '彼女は追加で働いた時間に対する公正な報酬を要求した。'),
(1081, 'coarse', '(生地・肌などが)きめの粗い、ざらざらした', '/kɔːrs/', 'コース',
  'The coarse fabric of the blanket irritated her sensitive skin.',
  '毛布のきめの粗い生地が彼女の敏感な肌を刺激した。',
  'Years of manual labor had left his hands coarse and calloused.',
  '長年の肉体労働で彼の手はざらざらでたこだらけになっていた。'),
(1082, 'dissertation', '(学位)論文、(特に)博士論文', '/ˌdɪsərˈteɪʃən/', 'ディサテイション',
  'She spent five years researching and writing her doctoral dissertation on medieval history.',
  '彼女は中世の歴史に関する博士論文の研究と執筆に5年を費やした。',
  'The committee praised the dissertation for its originality and rigorous methodology.',
  '委員会はその論文の独創性と厳密な方法論を称賛した。'),
(1083, 'conveyance', '運搬、輸送;(情報・感情の)伝達;乗り物、輸送手段', '/kənˈveɪəns/', 'コンヴェイアンス',
  'The conveyance of goods across the border was delayed by customs inspections.',
  '国境を越える物品の輸送は税関検査により遅延した。',
  'Horse-drawn carriages were once the primary conveyance in rural areas.',
  'かつて馬車は地方での主要な輸送手段だった。'),
(1084, 'periphery', '周囲、外縁(部)', '/pəˈrɪfəri/', 'ペリフェリー',
  'New housing developments sprang up on the periphery of the city.',
  '新しい住宅開発が都市の周縁部に出現した。',
  'The issue remained on the periphery of political debate for decades.',
  'その問題は数十年にわたって政治的議論の周辺にとどまっていた。'),
(1085, 'extraneous', '非本質的な、(本質に)無関係の', '/ɪkˈstreɪniəs/', 'イクストレイニアス',
  'The judge instructed the jury to disregard all extraneous information.',
  '裁判官は陪審員にすべての無関係な情報を無視するよう指示した。',
  'Removing extraneous details from the report made it far more readable.',
  '報告書から非本質的な詳細を取り除くことで、はるかに読みやすくなった。'),
(1086, 'enchant', '~を魅惑する、魅了する', '/ɪnˈtʃænt/', 'インチャント',
  'The storyteller enchanted the audience with tales of far-off lands.',
  '語り部は遠い国々の物語で聴衆を魅了した。',
  'Visitors are invariably enchanted by the breathtaking beauty of the alpine lake.',
  '訪問者は高山湖の息をのむような美しさに必ず魅了される。'),
(1087, 'infantile', '(人・行動などが)子どもっぽい、幼稚な;幼児(期)の', '/ˈɪnfəntaɪl/', 'インファンタイル',
  'His infantile behavior at the board meeting embarrassed his colleagues.',
  '取締役会議での彼の幼稚な振る舞いは同僚たちを当惑させた。',
  'The doctor diagnosed the child with a rare infantile neurological disorder.',
  '医師はその子どもに稀な幼児期の神経障害があると診断した。'),
(1088, 'acclimate', '(人・動植物が)(新しい環境・気候などに)慣れる、順応する;~を慣れさせる', '/ˈæklɪmeɪt/', 'アクリメイト',
  'It took several weeks for the transplanted trees to acclimate to the new soil.',
  '移植された木々が新しい土壌に順応するまでに数週間かかった。',
  'The mountaineers paused at base camp to acclimate to the high altitude.',
  '登山家たちは高地に順応するためにベースキャンプで休息を取った。'),
(1089, 'abstinence', '節制、自制', '/ˈæbstɪnəns/', 'アブスティネンス',
  'The doctor recommended total abstinence from alcohol during the treatment.',
  '医師は治療中はアルコールの完全な節制を勧めた。',
  'His years of abstinence from sugar dramatically improved his overall health.',
  '何年にもわたる砂糖の節制が彼の全体的な健康を劇的に改善した。'),
(1090, 'reverie', '空想、夢想', '/ˈrɛvəri/', 'レヴァリー',
  'She was lost in reverie when the sudden knock on the door startled her.',
  '彼女が空想にふけっていたとき、突然のドアのノックに驚かされた。',
  'The poet''s reverie was interrupted by the blaring of a car horn outside.',
  '詩人の夢想は外の車のクラクションの騒音によって中断された。'),
(1091, 'tether', '(動物)をつなぐ;(動物をつなぐ)ロープ、鎖', '/ˈtɛðər/', 'テザー',
  'The farmer tethered the goat to a post so it would not wander into the road.',
  '農夫はヤギが道路にさまよい出ないように杭につないだ。',
  'By the end of the exhausting negotiations, she was at the end of her tether.',
  '疲れ果てた交渉の終わりには、彼女は我慢の限界に達していた。'),
(1092, 'gratify', '~を喜ばせる、満足させる', '/ˈɡrætɪfaɪ/', 'グラティファイ',
  'It gratified the teacher to see her students excel in the national examination.',
  '生徒たちが全国試験で優秀な成績を収めるのを見て、教師は喜んだ。',
  'The company introduced new features to gratify the demands of its customers.',
  '会社は顧客の要望を満たすために新機能を導入した。'),
(1093, 'pompous', '(人が)もったいぶった、尊大な;(言葉・身ぶりなどが)仰々しい', '/ˈpɒmpəs/', 'ポンパス',
  'The pompous official lectured the crowd as though they were ignorant children.',
  'そのもったいぶった役人は、群衆を無知な子どもであるかのように説教した。',
  'His pompous speech, filled with grandiose claims, failed to impress the audience.',
  '大げさな主張で満ちた彼の仰々しいスピーチは、聴衆を感心させることができなかった。'),
(1094, 'scruffy', '薄汚い、みすぼらしい', '/ˈskrʌfi/', 'スクラッフィー',
  'The scruffy stray cat was taken in by a kind-hearted neighbor.',
  'その薄汚い野良猫は心優しい隣人に引き取られた。',
  'He showed up to the formal dinner in scruffy jeans, much to everyone''s dismay.',
  '彼はみすぼらしいジーンズ姿でフォーマルな夕食会に現れ、皆を落胆させた。'),
(1095, 'censure', '非難、酷評;(人)を非難する、酷評する', '/ˈsɛnʃər/', 'センシャー',
  'The parliament voted to censure the minister for his unethical conduct.',
  '議会はその大臣の非倫理的な行為に対して非難の議決を行った。',
  'Public censure of the corporation''s practices led to sweeping policy reforms.',
  '企業慣行に対する世間の非難が、広範な政策改革につながった。'),
(1096, 'flinch', '(驚き・恐怖・苦痛などで)ひるむ、たじろぐ', '/flɪntʃ/', 'フリンチ',
  'The soldier did not flinch even when the explosion erupted nearby.',
  'その兵士は近くで爆発が起きてもひるまなかった。',
  'She flinched at the harsh criticism but quickly composed herself.',
  '彼女は厳しい批判にたじろいだが、すぐに気を取り直した。'),
(1097, 'duplicity', '二枚舌、不誠実な行為', '/djuːˈplɪsəti/', 'デュープリシティ',
  'The ambassador''s duplicity was exposed when secret documents were leaked to the press.',
  '機密文書がマスコミに漏洩したとき、大使の二枚舌が暴露された。',
  'Years of duplicity had eroded all trust between the two business partners.',
  '長年の不誠実な行為が二人のビジネスパートナー間のすべての信頼を蝕んでいた。'),
(1098, 'apparition', '亡霊、幽霊', '/ˌæpəˈrɪʃən/', 'アパリション',
  'The villagers claimed to have seen an apparition wandering through the old cemetery.',
  '村人たちは古い墓地をさまよう亡霊を見たと主張した。',
  'What she initially mistook for an apparition turned out to be a reflection in the glass.',
  '彼女が最初は幽霊と見間違えたものは、ガラスに映った反射だった。'),
(1099, 'spillage', 'こぼす[こぼれる]こと、こぼれたもの', '/ˈspɪlɪdʒ/', 'スピリッジ',
  'The chemical spillage forced the evacuation of the entire industrial complex.',
  '化学物質のこぼれにより、工業団地全体の避難が余儀なくされた。',
  'Workers rushed to contain the oil spillage before it reached the river.',
  '作業員たちは石油のこぼれが川に達する前に封じ込めようと急いだ。'),
(1100, 'stampede', '(動物・人の集団が)(驚き・興奮で)一斉に逃げる;一斉に逃げる[暴走する]こと', '/stæmˈpiːd/', 'スタンピード',
  'A sudden thunderclap caused the herd of cattle to stampede across the open plain.',
  '突然の雷鳴により牛の群れが開けた平原を一斉に暴走した。',
  'The stampede at the stadium entrance resulted in dozens of injuries.',
  'スタジアム入口での暴走により数十人が負傷した。');
