-- words テーブル INSERT文 (No.1101 ~ No.1150)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1101, 'clemency', '(敵・罪人に対する)寛大な措置、温情', '/ˈklɛmənsi/', 'クレメンシー',
  'The governor granted clemency to the aging prisoner, commuting his life sentence to time served.',
  '知事は高齢の囚人に温情を示し、終身刑を既に服役した期間に減刑した。',
  'Human rights organizations worldwide appealed for clemency, arguing that the death penalty was disproportionate to the offense.',
  '世界中の人権団体が、死刑は罪に対して不均衡であると主張し、寛大な措置を求めた。'),
(1102, 'chide', '~を叱る、たしなめる', '/tʃaɪd/', 'チャイド',
  'The senior partner chided the young associate for submitting the legal brief without thoroughly proofreading it.',
  '上級パートナーは、法律文書を十分に校正せずに提出した若い弁護士を叱った。',
  'She gently chided her colleague for arriving late to the board meeting, reminding him of the importance of punctuality.',
  '彼女は取締役会に遅刻した同僚をやんわりとたしなめ、時間厳守の重要性を思い出させた。'),
(1103, 'trudge', 'とぼとぼ歩く、重い足取りで歩く', '/trʌdʒ/', 'トラッジ',
  'The exhausted hikers trudged through the knee-deep snow for hours before finally reaching the mountain refuge.',
  '疲れ果てた登山者たちは、ようやく山小屋にたどり着くまで何時間も膝まである雪の中をとぼとぼ歩いた。',
  'Every morning, the factory workers trudged along the muddy path to begin their grueling twelve-hour shifts.',
  '毎朝、工場の労働者たちは過酷な12時間のシフトを始めるために泥道を重い足取りで歩いた。'),
(1104, 'edify', '~を啓発する、教化する', '/ˈɛdɪfaɪ/', 'エディファイ',
  'The documentary was designed not merely to entertain but to edify viewers about the complexities of global migration.',
  'そのドキュメンタリーは単に娯楽を提供するだけでなく、国際移住の複雑さについて視聴者を啓発するために作られた。',
  'The professor''s lectures never failed to edify even the most disengaged students in the auditorium.',
  'その教授の講義は、講堂で最も関心の薄い学生さえも啓発せずにはいなかった。'),
(1105, 'sordid', '(内容・行為などが)下劣な、浅ましい;(場所・環境などが)不潔な、むさくるしい', '/ˈsɔːrdɪd/', 'ソーディッド',
  'The investigative journalist exposed the sordid details of the corruption scandal that had plagued the administration for years.',
  '調査報道記者は、何年も政権を悩ませてきた汚職スキャンダルの下劣な詳細を暴露した。',
  'The refugees were forced to live in sordid conditions, with no access to clean water or adequate sanitation.',
  '難民たちは清潔な水や適切な衛生設備もなく、不潔な環境での生活を余儀なくされた。'),
(1106, 'alacrity', '機敏さ;乗り気', '/əˈlækrɪti/', 'アラクリティ',
  'The volunteers responded with remarkable alacrity when the earthquake relief fund issued an urgent call for assistance.',
  '地震救援基金が緊急の支援要請を出したとき、ボランティアたちは驚くべき機敏さで応じた。',
  'She accepted the overseas assignment with alacrity, eager to broaden her professional horizons in a new cultural environment.',
  '彼女は新しい文化環境で専門的な視野を広げたいと意欲的で、海外赴任を乗り気で引き受けた。'),
(1107, 'ludicrous', '(行為・考えなどが)こっけいな、ばかげた', '/ˈluːdɪkrəs/', 'ルーディクラス',
  'The defendant''s claim that he had accidentally embezzled ten million dollars struck the jury as utterly ludicrous.',
  '1000万ドルを誤って横領したという被告の主張は、陪審員にとって全くばかげたものだった。',
  'It would be ludicrous to suggest that a single policy change could resolve centuries of deep-rooted social inequality.',
  'たった一つの政策変更で何世紀にもわたる根深い社会的不平等を解決できると主張するのはばかげている。'),
(1108, 'vehement', '(感情・主張などが)激しい、強烈な', '/ˈviːəmənt/', 'ヴィーアメント',
  'The opposition party launched a vehement attack on the proposed legislation, calling it an unprecedented assault on civil liberties.',
  '野党は提案された法案に激しい攻撃を展開し、市民の自由に対する前例のない侵害だと称した。',
  'Despite vehement protests from environmental groups, the government approved the construction of the offshore drilling platform.',
  '環境団体からの激しい抗議にもかかわらず、政府は沖合掘削プラットフォームの建設を承認した。'),
(1109, 'annulment', '無効(宣告)、取り消し', '/əˈnʌlmənt/', 'アナルメント',
  'The court issued an annulment of the contract after discovering that one party had signed under duress.',
  '一方の当事者が強迫の下で署名していたことが判明し、裁判所は契約の無効宣告を下した。',
  'She sought an annulment of her marriage on the grounds that her spouse had concealed a prior criminal conviction.',
  '彼女は配偶者が前科を隠していたことを理由に、結婚の取り消しを求めた。'),
(1110, 'docile', '(子ども・動物などが)従順な、扱いやすい', '/ˈdɒsaɪl/', 'ドサイル',
  'The once-feral cat became remarkably docile after months of patient rehabilitation at the animal shelter.',
  'かつて野生だった猫は、動物保護施設で数ヶ月の忍耐強いリハビリを経て、驚くほど従順になった。',
  'Authoritarian regimes often seek to cultivate a docile populace through censorship and systematic suppression of dissent.',
  '権威主義体制はしばしば検閲と組織的な反対意見の抑圧によって従順な国民を育成しようとする。'),
(1111, 'bombastic', '(人・言葉などが)大げさな、大言壮語する', '/bɒmˈbæstɪk/', 'ボンバスティック',
  'The senator''s bombastic rhetoric failed to conceal the lack of substance behind his proposed economic reforms.',
  'その上院議員の大げさな弁論は、彼が提案した経済改革の実質の欠如を隠すことができなかった。',
  'Critics dismissed the CEO''s bombastic claims about revolutionizing the industry as nothing more than empty posturing.',
  '批評家たちは、業界を革命的に変えるというCEOの大言壮語を単なる虚勢にすぎないと退けた。'),
(1112, 'erudite', '博識な、博学な', '/ˈɛrjʊdaɪt/', 'エルダイト',
  'The erudite historian captivated the audience with her comprehensive analysis of medieval trade routes across the Silk Road.',
  'その博識な歴史家は、シルクロードを横断する中世の交易路についての包括的な分析で聴衆を魅了した。',
  'His erudite commentary on Renaissance art demonstrated a depth of knowledge that few contemporary scholars could rival.',
  'ルネサンス美術に関する彼の博学な解説は、現代の学者ではほとんど太刀打ちできない知識の深さを示していた。'),
(1113, 'pernicious', '悪影響を及ぼす、非常に有害な', '/pərˈnɪʃəs/', 'パーニシャス',
  'The pernicious effects of misinformation on public health became alarmingly evident during the pandemic.',
  '公衆衛生に対する誤情報の有害な影響は、パンデミック中に驚くほど明白になった。',
  'Scholars have long warned about the pernicious influence of unchecked corporate lobbying on democratic governance.',
  '学者たちは、規制のない企業ロビー活動が民主主義統治に及ぼす有害な影響について長い間警告してきた。'),
(1114, 'felicity', '至福、幸運', '/fɪˈlɪsɪti/', 'フェリシティ',
  'The couple radiated an air of felicity on their golden wedding anniversary, surrounded by generations of their family.',
  '金婚式の日、何世代もの家族に囲まれたその夫婦は至福の雰囲気を漂わせていた。',
  'The author''s felicity of expression made even the most abstract philosophical concepts accessible to general readers.',
  'その著者の巧みな表現力は、最も抽象的な哲学的概念さえも一般読者に理解しやすくした。'),
(1115, 'scrounge', '(金品)をせびる、ねだる', '/skraʊndʒ/', 'スクラウンジ',
  'He was always scrounging cigarettes from his coworkers, never bothering to purchase his own pack.',
  '彼はいつも同僚からタバコをせびっていて、自分で買おうとはしなかった。',
  'During the economic downturn, many families were reduced to scrounging for basic necessities at charitable organizations.',
  '景気低迷の間、多くの家族が慈善団体で基本的な必需品をねだるまでに困窮した。'),
(1116, 'laborious', '(作業工程などが)手間のかかる、努力を要する', '/ləˈbɔːriəs/', 'ラボリアス',
  'The laborious process of manually cataloguing thousands of archaeological artifacts took the research team over two years.',
  '何千もの考古学的遺物を手作業で目録化する手間のかかる作業に、研究チームは2年以上を費やした。',
  'Translating ancient Sumerian cuneiform tablets remains a laborious endeavor that demands exceptional linguistic expertise.',
  '古代シュメールの楔形文字の粘土板を翻訳することは、卓越した言語学的専門知識を要する手間のかかる仕事である。'),
(1117, 'incinerate', '(ごみなど)を焼却する;(死体)を火葬する', '/ɪnˈsɪnəreɪt/', 'インシネレイト',
  'The municipal government decided to incinerate the contaminated medical waste rather than risk burying it in landfills.',
  '市政府は、汚染された医療廃棄物を埋立地に埋めるリスクを冒すよりも焼却することを決定した。',
  'The wildfire advanced so rapidly that it incinerated entire neighborhoods before firefighting crews could establish containment lines.',
  '山火事は非常に急速に進み、消防隊が封じ込め線を確立する前に近隣一帯を焼き尽くした。'),
(1118, 'twitch', '(体・筋肉などが)びくびく動く;けいれん', '/twɪtʃ/', 'トゥイッチ',
  'The surgeon noticed that the patient''s eyelid began to twitch involuntarily during the delicate neurological examination.',
  '外科医は、繊細な神経学的検査中に患者のまぶたが無意識にびくびく動き始めたことに気づいた。',
  'A nervous twitch in his jaw betrayed the anxiety he was desperately trying to conceal from the interrogators.',
  '顎のけいれんが、彼が取調官から必死に隠そうとしていた不安を暴露した。'),
(1119, 'strident', '(声・音が)キーキーいう、耳ざわりな', '/ˈstraɪdənt/', 'ストライデント',
  'The strident tone of the alarm pierced through the silence of the laboratory, signaling a critical chemical leak.',
  '警報の耳ざわりな音が研究室の静寂を貫き、重大な化学物質の漏洩を知らせた。',
  'Her strident criticism of the proposed merger alienated several board members who had initially supported her candidacy.',
  '提案された合併に対する彼女の激しい批判は、当初彼女の立候補を支持していた数人の取締役を遠ざけた。'),
(1120, 'inclination', '気持ち、意向;傾向', '/ˌɪnklɪˈneɪʃən/', 'インクリネイション',
  'Despite her natural inclination toward the arts, she pursued a career in biomedical engineering at her parents'' urging.',
  '芸術への自然な傾向にもかかわらず、彼女は両親の勧めで生物医学工学のキャリアを追求した。',
  'The committee showed little inclination to revisit the controversial policy that had already been ratified by a majority vote.',
  '委員会は、すでに過半数の投票で批准された物議を醸す政策を再検討する意向をほとんど示さなかった。'),
(1121, 'clobber', '(人・チーム)を決定的に打ち負かす', '/ˈklɒbər/', 'クロバー',
  'The defending champions clobbered their opponents in the semifinal, winning by an unprecedented margin of thirty points.',
  'ディフェンディングチャンピオンは準決勝で対戦相手を決定的に打ち負かし、前例のない30点差で勝利した。',
  'Small businesses were clobbered by the sudden imposition of tariffs that doubled the cost of imported raw materials.',
  '輸入原材料のコストを倍増させた突然の関税の賦課により、中小企業は大打撃を受けた。'),
(1122, 'perturb', '(人)を不安にする、動揺させる', '/pərˈtɜːrb/', 'パーターブ',
  'The unexpected fluctuations in the stock market perturbed even the most seasoned financial analysts on Wall Street.',
  '株式市場の予想外の変動は、ウォール街の最も経験豊富な金融アナリストさえも動揺させた。',
  'Nothing seemed to perturb the veteran diplomat, who maintained her composure throughout the heated negotiations.',
  'ベテラン外交官は何事にも動揺しないようで、白熱した交渉を通じて冷静さを保っていた。'),
(1123, 'billow', '(カーテン・帆などが)(風で)膨らむ;大波', '/ˈbɪloʊ/', 'ビロウ',
  'The enormous sails billowed magnificently as the restored galleon embarked on its maiden commemorative voyage.',
  '復元されたガレオン船が記念航海に出発すると、巨大な帆が見事に膨らんだ。',
  'Thick billows of smoke rose from the industrial complex, prompting authorities to issue an immediate evacuation order.',
  '工業団地から黒煙が大きく立ち上り、当局は即座に避難命令を出した。'),
(1124, 'reticent', '無口な、口が重い', '/ˈrɛtɪsənt/', 'レティセント',
  'The witness remained reticent throughout the cross-examination, offering only monosyllabic responses to the attorney''s probing questions.',
  '証人は反対尋問を通じて口が重く、弁護士の追及する質問には単音節の返答しかしなかった。',
  'Japanese corporate culture has traditionally been reticent about disclosing executive compensation to the general public.',
  '日本の企業文化は伝統的に、役員報酬を一般に開示することに消極的であった。'),
(1125, 'extrinsic', '外部(から)の、外的な;本質的でない', '/ɪkˈstrɪnsɪk/', 'エクストリンシック',
  'Researchers found that extrinsic motivators such as bonuses and promotions were less effective than intrinsic satisfaction in retaining top talent.',
  '研究者たちは、ボーナスや昇進などの外的動機づけは、優秀な人材を維持するうえで内発的満足感ほど効果的ではないことを発見した。',
  'The appraiser determined that the diamond''s value was diminished by extrinsic factors, including a poorly executed setting.',
  '鑑定士は、不出来な台座を含む外的要因によってダイヤモンドの価値が低下していると判断した。'),
(1126, 'encumber', '(人(の行動))を妨げる、~の足手まといになる', '/ɪnˈkʌmbər/', 'エンカンバー',
  'The soldiers were heavily encumbered by their equipment, making the ascent through the mountainous terrain painfully slow.',
  '兵士たちは装備で大きく行動を妨げられ、山岳地帯の登り道が苦痛なほど遅くなった。',
  'Excessive bureaucratic regulations continue to encumber small enterprises that lack the resources to navigate complex compliance requirements.',
  '過度な官僚的規制は、複雑なコンプライアンス要件に対処するリソースを持たない中小企業の妨げになり続けている。'),
(1127, 'restitution', '(所有者への)返却、返還;(損害などの)補償', '/ˌrɛstɪˈtjuːʃən/', 'レスティテューション',
  'The court ordered the convicted art dealer to make full restitution of the stolen paintings to the museum.',
  '裁判所は、有罪判決を受けた美術商に盗まれた絵画を美術館に全額返還するよう命じた。',
  'Several nations have formally demanded the restitution of cultural artifacts that were looted during the colonial era.',
  'いくつかの国が、植民地時代に略奪された文化的遺物の返還を正式に要求している。'),
(1128, 'impel', '(人)を駆り立てる、強いる', '/ɪmˈpɛl/', 'インペル',
  'A profound sense of injustice impelled the young lawyer to dedicate her career to defending the rights of the underprivileged.',
  '不正義に対する深い意識が、その若い弁護士を恵まれない人々の権利を守るキャリアに駆り立てた。',
  'Economic necessity impelled thousands of skilled workers to seek employment opportunities in neighboring countries.',
  '経済的必要性が何千人もの熟練労働者を近隣諸国での雇用機会を求めるよう駆り立てた。'),
(1129, 'rankle', '(人)の心を苦しめる', '/ˈræŋkəl/', 'ランクル',
  'The perceived injustice of the verdict continued to rankle the defendant long after his release from prison.',
  '判決の不当さに対する思いは、出所後もずっと被告の心を苦しめ続けた。',
  'It still rankles many citizens that the corporate executives responsible for the financial crisis escaped criminal prosecution.',
  '金融危機の責任を負うべき企業の幹部が刑事訴追を免れたことは、今でも多くの市民の心を苦しめている。'),
(1130, 'absurdity', 'ばかげたこと[もの];不合理、不条理', '/əbˈsɜːrdɪti/', 'アブサーディティ',
  'The sheer absurdity of the bureaucratic requirements left even experienced immigration attorneys shaking their heads in disbelief.',
  '官僚的な要件のあまりのばかげたさに、経験豊富な移民弁護士でさえ信じられないと首を振った。',
  'Existentialist philosophers such as Camus explored the fundamental absurdity of seeking meaning in an indifferent universe.',
  'カミュのような実存主義哲学者たちは、無関心な宇宙の中で意味を求めることの根本的な不条理を探求した。'),
(1131, 'onrush', '突然の発展;突進、突撃', '/ˈɒnrʌʃ/', 'オンラッシュ',
  'The onrush of technological innovation in artificial intelligence has fundamentally transformed the global labor market.',
  '人工知能における技術革新の急速な発展は、世界の労働市場を根本的に変革した。',
  'The defenders braced themselves against the onrush of enemy cavalry charging across the open plains.',
  '防衛軍は、開けた平原を突撃してくる敵の騎兵隊の突進に備えた。'),
(1132, 'cogitate', '熟考する、熟慮する', '/ˈkɒdʒɪteɪt/', 'コジテイト',
  'The philosopher spent decades cogitating on the nature of consciousness before publishing his groundbreaking treatise.',
  'その哲学者は画期的な論文を発表する前に、意識の本質について何十年も熟考した。',
  'Rather than acting impulsively, the seasoned negotiator preferred to cogitate over every possible outcome before making her counteroffer.',
  '衝動的に行動するのではなく、その熟練した交渉人は反対提案をする前にあらゆる結果を熟慮することを好んだ。'),
(1133, 'gnaw', '(人・動物が)((もの)を)かじる、かじり取る;[gnaw at ~](人・心など)を苦しめる、さいなむ', '/nɔː/', 'ノー',
  'The persistent doubt gnawed at her conscience, making it impossible to enjoy the promotion she had secured through deception.',
  '絶え間ない疑念が彼女の良心をさいなみ、欺瞞によって得た昇進を楽しむことができなかった。',
  'Archaeologists discovered fossilized bones that had been gnawed by prehistoric predators millions of years ago.',
  '考古学者たちは、数百万年前に先史時代の捕食者にかじられた化石化した骨を発見した。'),
(1134, 'ingenious', '(方法・計画・装置などが)見事な、うまくできた;(人が)創意に満ちた', '/ɪnˈdʒiːniəs/', 'インジーニアス',
  'The engineer devised an ingenious solution to the water scarcity problem using solar-powered desalination technology.',
  'そのエンジニアは太陽光発電の淡水化技術を使って、水不足の問題に対する見事な解決策を考案した。',
  'The ingenious design of the ancient Roman aqueducts continues to inspire modern hydraulic engineering projects worldwide.',
  '古代ローマの水道橋の見事な設計は、世界中の現代の水理工学プロジェクトにインスピレーションを与え続けている。'),
(1135, 'deity', '神、女神', '/ˈdiːɪti/', 'ディーイティ',
  'The ancient temple was dedicated to a water deity believed to control the monsoon rains essential for agriculture.',
  'その古代の寺院は、農業に不可欠なモンスーンの雨を支配すると信じられていた水の神に捧げられていた。',
  'In Hindu mythology, each deity embodies specific virtues and cosmic principles that govern the natural order of the universe.',
  'ヒンドゥー教の神話では、それぞれの神が宇宙の自然の秩序を司る特定の美徳と宇宙的原理を体現している。'),
(1136, 'accede', '(要求・提案などに)(譲歩して)同意する、応じる', '/ækˈsiːd/', 'アクシード',
  'After prolonged negotiations, the government reluctantly acceded to the union''s demands for improved workplace safety standards.',
  '長期にわたる交渉の末、政府は渋々ながら職場安全基準の改善を求める労働組合の要求に応じた。',
  'The monarch acceded to the throne following the unexpected abdication of his elder brother.',
  '兄の予想外の退位に伴い、その君主は王位に就いた。'),
(1137, 'entwine', '~を巻きつける、絡ませる', '/ɪnˈtwaɪn/', 'エントワイン',
  'The ancient wisteria vines had entwined themselves around the stone pillars, creating a breathtaking natural canopy.',
  '古い藤のつるが石柱に絡みつき、息をのむような自然の天蓋を作り出していた。',
  'The histories of the two neighboring nations are so deeply entwined that studying one in isolation yields an incomplete picture.',
  '二つの隣国の歴史は深く絡み合っており、一方だけを孤立して研究しても不完全な像しか得られない。'),
(1138, 'lubricate', '(機械など)に油を差す', '/ˈluːbrɪkeɪt/', 'ルーブリケイト',
  'The maintenance crew was tasked with lubricating all the heavy machinery before the factory resumed its overnight production run.',
  '整備班は、工場が夜間生産を再開する前にすべての重機に油を差す任務を課された。',
  'Diplomats often use informal social gatherings to lubricate otherwise tense and protracted treaty negotiations.',
  '外交官はしばしば非公式な社交の場を利用して、緊張した長引く条約交渉を円滑にする。'),
(1139, 'paucity', '不足、欠乏;少数、少量', '/ˈpɔːsɪti/', 'ポーシティ',
  'The paucity of empirical evidence supporting the new drug''s efficacy prompted regulators to delay its market approval.',
  '新薬の有効性を裏付ける実証的証拠の不足により、規制当局はその市場承認を延期した。',
  'Critics lamented the paucity of female representation in senior leadership positions across the technology sector.',
  '批評家たちは、テクノロジー部門全体の上級管理職における女性代表の少なさを嘆いた。'),
(1140, 'virulent', '(病気などが)悪性の、伝染力の強い、致命的な;(言葉・人などが)悪意に満ちた', '/ˈvɪrjʊlənt/', 'ヴィルレント',
  'The virulent strain of influenza spread rapidly through the densely populated region, overwhelming local healthcare facilities.',
  'その悪性のインフルエンザ株は人口密集地域で急速に広がり、地域の医療施設を圧倒した。',
  'The political commentator launched a virulent attack on the opposition leader, accusing her of systematic corruption.',
  'その政治評論家は野党党首に悪意に満ちた攻撃を仕掛け、組織的な汚職を非難した。'),
(1141, 'debonair', '(男性が)感じのよい、おしゃれな、粋な', '/ˌdɛbəˈnɛər/', 'デボネア',
  'The debonair ambassador charmed every dignitary at the state banquet with his impeccable manners and witty conversation.',
  'その粋な大使は、完璧なマナーと機知に富んだ会話で国宴のすべての要人を魅了した。',
  'He cultivated a debonair image that belied the humble origins from which he had risen to international prominence.',
  '彼は、国際的な名声を得るに至った謙虚な出自を感じさせない、おしゃれなイメージを築き上げた。'),
(1142, 'deprecate', '~を批判する;~に反対する、不賛成を唱える', '/ˈdɛprɪkeɪt/', 'デプリケイト',
  'The archbishop publicly deprecated the government''s decision to cut funding for social welfare programs serving the most vulnerable communities.',
  '大司教は、最も脆弱なコミュニティに奉仕する社会福祉プログラムへの資金を削減する政府の決定を公に批判した。',
  'Several prominent economists deprecated the central bank''s aggressive interest rate hikes as counterproductive to economic recovery.',
  '数人の著名な経済学者が、中央銀行の積極的な金利引き上げは景気回復に逆効果であると批判した。'),
(1143, 'incriminate', '(人)に罪を負わせる、(人)を有罪にする', '/ɪnˈkrɪmɪneɪt/', 'インクリミネイト',
  'The newly discovered forensic evidence was sufficient to incriminate the suspect, who had previously evaded prosecution for over a decade.',
  '新たに発見された法医学的証拠は、10年以上訴追を逃れていた容疑者を有罪にするのに十分だった。',
  'The whistleblower provided documents that incriminated several high-ranking officials in an elaborate money-laundering scheme.',
  '内部告発者は、数人の高官が精巧な資金洗浄計画に関与していることを示す書類を提供した。'),
(1144, 'pare', '(ナイフなどで)(果物など)の皮をむく;~を切り詰める、削減する', '/pɛər/', 'ペア',
  'The finance minister announced plans to pare the national budget deficit by eliminating redundant administrative expenditures.',
  '財務大臣は、冗長な行政支出を排除することで国家予算の赤字を削減する計画を発表した。',
  'She meticulously pared the apples into perfectly uniform slices for the award-winning tarte tatin she was preparing.',
  '彼女は準備中の受賞歴のあるタルトタタンのために、リンゴの皮を丁寧にむいて完璧に均一な薄切りにした。'),
(1145, 'sullen', '不機嫌な、押し黙った;(空・天気が)うっとうしい、陰うつな', '/ˈsʌlən/', 'サレン',
  'The teenager sat in sullen silence throughout the family dinner, refusing to engage in any conversation whatsoever.',
  'その10代の若者は家族の夕食の間ずっと不機嫌に押し黙り、いかなる会話にも参加しようとしなかった。',
  'Under the sullen gray sky, the fishing village appeared even more desolate than it had during the previous winter.',
  '陰うつな灰色の空の下、その漁村は前の冬よりもさらに荒涼として見えた。'),
(1146, 'delirious', '精神が錯乱した;(喜びで)非常に興奮した、有頂天の', '/dɪˈlɪriəs/', 'デリリアス',
  'The patient became delirious from the high fever and began uttering incoherent phrases that alarmed the attending physicians.',
  '患者は高熱で精神が錯乱し、担当医を驚かせる支離滅裂な言葉を発し始めた。',
  'The entire nation was delirious with joy when their underdog team clinched the World Cup title in a dramatic final.',
  '劣勢と見なされていた自国チームが劇的な決勝戦でワールドカップのタイトルを勝ち取ったとき、国中が有頂天になった。'),
(1147, 'schism', '(組織などの)分裂、分離', '/ˈskɪzəm/', 'スキズム',
  'The doctrinal schism within the church led to the formation of two rival denominations that remain divided to this day.',
  '教会内の教義上の分裂は、今日に至るまで分かれたままの二つの対立する宗派の形成につながった。',
  'A bitter schism erupted among the party leadership over whether to support the controversial trade liberalization agreement.',
  '物議を醸す貿易自由化協定を支持するかどうかをめぐって、党指導部の間に激しい分裂が生じた。'),
(1148, 'rendezvous', '待ち合わせ、(会う)約束;待ち合わせ場所;(待ち合わせして)会う', '/ˈrɒndɪvuː/', 'ランデヴー',
  'The intelligence operatives arranged a clandestine rendezvous at an inconspicuous café on the outskirts of the capital.',
  '諜報工作員たちは、首都郊外の目立たないカフェで秘密の待ち合わせを手配した。',
  'The two spacecraft successfully rendezvoused in orbit before commencing the delicate docking procedure.',
  '二つの宇宙船は、繊細なドッキング手順を開始する前に、軌道上で首尾よく会合した。'),
(1149, 'hibernate', '冬眠する', '/ˈhaɪbərneɪt/', 'ハイバーネイト',
  'Certain species of bats hibernate in caves throughout the winter, drastically reducing their metabolic rate to conserve energy.',
  '特定の種のコウモリは冬の間洞窟で冬眠し、エネルギーを節約するために代謝率を大幅に低下させる。',
  'The startup''s ambitious expansion plans were forced to hibernate during the prolonged economic recession.',
  'そのスタートアップの野心的な拡大計画は、長引く景気後退の間、休眠を余儀なくされた。'),
(1150, 'egregious', '実にひどい、目に余る', '/ɪˈɡriːdʒəs/', 'イグリージャス',
  'The auditor uncovered egregious accounting irregularities that had gone undetected for nearly five consecutive fiscal years.',
  '監査人は、ほぼ5会計年度連続で発見されなかった目に余る会計上の不正を発見した。',
  'The committee condemned the egregious violation of human rights and called for an immediate independent investigation.',
  '委員会は目に余る人権侵害を非難し、即座に独立した調査を行うよう求めた。');
