-- words テーブル INSERT文 (No.1151 ~ No.1200)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1151, 'equilibrium', '(相反する利害などの)均衡、釣り合い;(心の)平静、落ち着き', '/ˌiːkwɪˈlɪbriəm/', 'イークウィリブリアム',
  'The delicate equilibrium between economic growth and environmental preservation must be maintained.',
  '経済成長と環境保全の微妙な均衡を維持しなければならない。',
  'She struggled to regain her emotional equilibrium after receiving the devastating news.',
  '壊滅的な知らせを受けた後、彼女は心の平静を取り戻すのに苦労した。'),
(1152, 'prodigious', '驚嘆すべき、並外れた', '/prəˈdɪdʒəs/', 'プロディジャス',
  'The young pianist displayed a prodigious talent that left the audience in awe.',
  'その若いピアニストは聴衆を驚嘆させる並外れた才能を見せた。',
  'He consumed a prodigious amount of literature during his years of self-imposed exile.',
  '彼は自ら課した亡命生活の間に驚嘆すべき量の文学作品を読破した。'),
(1153, 'tinge', '色合い;[a tinge of ~]~じみたところ', '/tɪndʒ/', 'ティンジ',
  'There was a tinge of regret in her voice as she recalled the missed opportunity.',
  '逃した機会を振り返る彼女の声には後悔じみたところがあった。',
  'The autumn leaves added a golden tinge to the landscape along the river.',
  '紅葉が川沿いの風景に金色の色合いを添えていた。'),
(1154, 'drool', '(人・動物が)よだれを垂らす;たわごとを言う;よだれ', '/druːl/', 'ドルール',
  'The dog began to drool uncontrollably at the sight of the freshly cooked steak.',
  'その犬は焼きたてのステーキを見て抑えきれないほどよだれを垂らし始めた。',
  'Food critics drool over the chef''s exquisite creations at the newly opened restaurant.',
  '食評家たちは新しくオープンしたレストランのシェフの絶品料理によだれを垂らす。'),
(1155, 'dainty', '(もの・容姿などが)小さくて上品な;(動作が)優美な', '/ˈdeɪnti/', 'デインティ',
  'The porcelain teacups were so dainty that the guests handled them with extreme care.',
  '磁器のティーカップはとても上品で小さく、客たちは細心の注意を払って扱った。',
  'The ballerina took dainty steps across the stage, captivating the entire audience.',
  'バレリーナは舞台の上を優美な足取りで横切り、観客全員を魅了した。'),
(1156, 'heist', '強盗、銀行破り', '/haɪst/', 'ハイスト',
  'The daring heist at the national museum resulted in the theft of priceless artifacts.',
  '国立博物館での大胆な強盗により、かけがえのない遺物が盗まれた。',
  'Police eventually apprehended the mastermind behind the elaborate jewelry heist.',
  '警察はついに精巧な宝石強盗の首謀者を逮捕した。'),
(1157, 'facet', '(ものごとの)一面、側面', '/ˈfæsɪt/', 'ファスィット',
  'The documentary explored every facet of the immigration debate with remarkable impartiality.',
  'そのドキュメンタリーは移民論争のあらゆる側面を驚くべき公平さで探求した。',
  'Cultural adaptation involves understanding the multifarious facets of a new society.',
  '文化適応とは新しい社会の多種多様な側面を理解することである。'),
(1158, 'anoint', '(人・都市など)を選定する、指定する', '/əˈnɔɪnt/', 'アノイント',
  'The committee anointed her as the next chairperson of the international organization.',
  '委員会は彼女を国際組織の次期議長に選定した。',
  'The media had already anointed him as the frontrunner long before the election took place.',
  'メディアは選挙が行われるはるか前に彼を最有力候補に指定していた。'),
(1159, 'malevolent', '悪意のある', '/məˈlevələnt/', 'マレヴォレント',
  'The villain cast a malevolent glare at the protagonist before vanishing into the shadows.',
  '悪役は主人公に悪意のある視線を投げかけてから闇の中に消えた。',
  'His malevolent intentions were concealed behind a facade of charm and generosity.',
  '彼の悪意のある意図は魅力と寛大さという仮面の裏に隠されていた。'),
(1160, 'prowl', '(動物が)(獲物を求めて)うろつく、徘徊する;(犯罪目的で)うろつく', '/praʊl/', 'プラウル',
  'The leopard would prowl the savanna at dusk in search of unsuspecting prey.',
  'ヒョウは夕暮れ時に油断した獲物を求めてサバンナをうろついた。',
  'Detectives observed the suspect prowl around the warehouse district late at night.',
  '刑事たちは容疑者が深夜に倉庫街をうろつくのを観察した。'),
(1161, 'beguile', '~を巧みにだます;(人)を魅了する', '/bɪˈɡaɪl/', 'ビガイル',
  'The con artist beguiled his victims with promises of extraordinary investment returns.',
  'その詐欺師は並外れた投資収益を約束して被害者たちを巧みにだました。',
  'Visitors are often beguiled by the enchanting beauty of the ancient temple gardens.',
  '訪問者は古代の寺院庭園の魅惑的な美しさにしばしば魅了される。'),
(1162, 'dissonance', '(意見などの)不一致、不調和;不協和音', '/ˈdɪsənəns/', 'ディソナンス',
  'The cognitive dissonance between his beliefs and his actions caused him considerable distress.',
  '信念と行動の間の認知的不調和が彼にかなりの苦痛を与えた。',
  'The composer deliberately introduced dissonance into the symphony to evoke a sense of unease.',
  'その作曲家は不安感を呼び起こすために交響曲に意図的に不協和音を導入した。'),
(1163, 'incumbent', '現職の;現職者、在任者', '/ɪnˈkʌmbənt/', 'インカンベント',
  'The incumbent president faces a formidable challenger in the upcoming election.',
  '現職の大統領は来たる選挙で手強い挑戦者に直面している。',
  'It is incumbent upon every citizen to exercise their right to vote responsibly.',
  'すべての市民が責任を持って投票権を行使することが義務である。'),
(1164, 'maim', '(人)に重傷を負わせる', '/meɪm/', 'メイム',
  'The landmine explosion maimed several soldiers, leaving them with permanent disabilities.',
  '地雷の爆発で数人の兵士が重傷を負い、永久的な障害が残った。',
  'Reckless driving continues to maim innocent pedestrians on the city''s busy streets.',
  '無謀な運転が市内の混雑した通りで罪のない歩行者に重傷を負わせ続けている。'),
(1165, 'remnant', '名残、面影;(布の)端切れ', '/ˈremnənt/', 'レムナント',
  'The crumbling fortress is the last remnant of the medieval kingdom that once flourished here.',
  '崩れかけた要塞は、かつてここで栄えた中世王国の最後の名残である。',
  'She fashioned a beautiful quilt from remnants of fabric collected over many years.',
  '彼女は何年もかけて集めた端切れから美しいキルトを作り上げた。'),
(1166, 'topple', '~を倒す、ぐらつかせる;倒れる、ぐらつく;(政府など)を転覆させる', '/ˈtɒpl/', 'トプル',
  'The massive earthquake caused the ancient stone columns to topple onto the temple floor.',
  '大地震により古代の石柱が神殿の床に倒れた。',
  'The revolutionary movement sought to topple the authoritarian regime through peaceful protests.',
  '革命運動は平和的な抗議活動を通じて独裁政権を転覆させようとした。'),
(1167, 'impertinent', '(人・態度などが)生意気な、無礼な', '/ɪmˈpɜːrtɪnənt/', 'インパーティネント',
  'The student''s impertinent remark to the professor shocked everyone in the lecture hall.',
  '教授に対するその学生の生意気な発言は講堂の全員を驚かせた。',
  'She dismissed his impertinent questions with a cold stare and continued her presentation.',
  '彼女は冷たい視線で彼の無礼な質問を一蹴し、プレゼンを続けた。'),
(1168, 'aberration', '(常軌の)逸脱、異常', '/ˌæbəˈreɪʃn/', 'アベレイション',
  'The scientist dismissed the anomalous result as a statistical aberration rather than a breakthrough.',
  'その科学者は異常な結果を画期的発見ではなく統計的な逸脱として退けた。',
  'His violent outburst was considered an aberration from his normally calm and composed demeanor.',
  '彼の暴力的な爆発は、普段の穏やかで落ち着いた態度からの逸脱とみなされた。'),
(1169, 'chuckle', 'くすくす笑う、ほくそ笑む;含み笑い(すること)', '/ˈtʃʌkl/', 'チャクル',
  'He couldn''t help but chuckle at the absurdity of the situation he found himself in.',
  '彼は自分が置かれた状況のばかばかしさについくすくす笑ってしまった。',
  'A quiet chuckle spread through the audience when the speaker made an unintentional pun.',
  '講演者が意図せずしゃれを言ったとき、静かな含み笑いが聴衆に広がった。'),
(1170, 'presumptuous', '(人・行為などが)厚かましい、出しゃばった', '/prɪˈzʌmptʃuəs/', 'プリザンプチュアス',
  'It would be presumptuous of me to offer advice on a subject I know so little about.',
  '私がほとんど知らない話題について助言するのは厚かましいだろう。',
  'His presumptuous assumption that he would be promoted angered his more experienced colleagues.',
  '自分が昇進するだろうという彼の厚かましい思い込みは、より経験豊富な同僚たちを怒らせた。'),
(1171, 'chasten', '(人)に恥ずかしい思いをさせる', '/ˈtʃeɪsn/', 'チェイスン',
  'The humiliating defeat chastened the arrogant general, who never underestimated his opponents again.',
  '屈辱的な敗北がその傲慢な将軍に恥ずかしい思いをさせ、二度と敵を過小評価しなくなった。',
  'Chastened by the public backlash, the politician issued a sincere apology for his remarks.',
  '世論の反発に恥ずかしい思いをさせられ、その政治家は発言について心からの謝罪をした。'),
(1172, 'percolate', '(考え・情報などが)浸透する、広まる;(液体・光などが)しみ通る、漏れる;ろ過される', '/ˈpɜːrkəleɪt/', 'パーコレイト',
  'It took years for the new educational philosophy to percolate through the entire school system.',
  '新しい教育哲学が学校制度全体に浸透するのに何年もかかった。',
  'Rainwater slowly percolated through the layers of rock, eventually reaching the underground aquifer.',
  '雨水はゆっくりと岩の層をしみ通り、最終的に地下帯水層に達した。'),
(1173, 'jiggle', '小刻みに揺れ動く', '/ˈdʒɪɡl/', 'ジグル',
  'She had to jiggle the key in the rusty lock several times before the door finally opened.',
  '彼女はさびた錠前の中で鍵を何度も小刻みに揺らしてようやくドアが開いた。',
  'The toddler began to jiggle excitedly in his high chair when he saw the birthday cake.',
  'その幼児はバースデーケーキを見るとハイチェアの中で興奮して小刻みに揺れ動いた。'),
(1174, 'trepidation', '(これから起こる出来事についての)不安、恐れ', '/ˌtrepɪˈdeɪʃn/', 'トレピデイション',
  'She approached the podium with considerable trepidation, knowing that thousands were watching.',
  '何千人もが見ていると知り、彼女はかなりの不安を抱えて演壇に近づいた。',
  'The villagers waited with trepidation for the results of the environmental contamination tests.',
  '村人たちは環境汚染検査の結果を不安を抱えて待った。'),
(1175, 'capricious', '(人・態度などが)気まぐれな、移り気な;(天候などが)変わりやすい、不安定な', '/kəˈprɪʃəs/', 'カプリシャス',
  'The capricious nature of the stock market makes it a risky venture for inexperienced investors.',
  '株式市場の気まぐれな性質は、経験の浅い投資家にとってリスクの高い事業となる。',
  'The region''s capricious weather can shift from blazing sunshine to torrential rain within minutes.',
  'この地域の変わりやすい天候は、数分のうちに照りつける日差しから豪雨に変わることがある。'),
(1176, 'crumple', '(紙・布など)をしわくちゃにする;(紙・布などが)しわくちゃになる', '/ˈkrʌmpl/', 'クランプル',
  'In frustration, she crumpled the rejection letter and tossed it into the wastebasket.',
  '苛立ちのあまり、彼女は不採用通知をしわくちゃにしてゴミ箱に投げ込んだ。',
  'The car''s front bumper crumpled upon impact, but the safety features protected the passengers.',
  '車のフロントバンパーは衝撃でしわくちゃになったが、安全機能が乗客を守った。'),
(1177, 'epiphany', '突然のひらめき、悟り', '/ɪˈpɪfəni/', 'イピファニー',
  'The scientist had an epiphany while walking in the park that led to a groundbreaking discovery.',
  'その科学者は公園を散歩中に突然のひらめきを得て、画期的な発見につながった。',
  'After years of searching for meaning, she experienced an epiphany that transformed her outlook on life.',
  '何年も意味を探し続けた後、彼女は人生観を一変させる悟りを経験した。'),
(1178, 'elated', '大喜びで、有頂天で', '/ɪˈleɪtɪd/', 'イレイティッド',
  'The research team was elated when their experimental drug showed promising results in clinical trials.',
  '実験薬が臨床試験で有望な結果を示したとき、研究チームは大喜びだった。',
  'She felt absolutely elated upon learning that her novel had been shortlisted for the literary prize.',
  '自分の小説が文学賞の最終候補に残ったと知り、彼女は有頂天になった。'),
(1179, 'nominally', '名目上は、名ばかりは', '/ˈnɒmɪnəli/', 'ノミナリー',
  'The country is nominally a democracy, but in practice, power is concentrated in the hands of a few.',
  'その国は名目上は民主主義国家だが、実際には権力は少数の手に集中している。',
  'He was nominally in charge of the department, though his deputy made all the important decisions.',
  '彼は名目上は部門の責任者だったが、重要な決定はすべて副官が下していた。'),
(1180, 'abrasive', '(性格・態度などが)いらいらさせる;(音が)耳障りな', '/əˈbreɪsɪv/', 'アブレイシヴ',
  'His abrasive manner of speaking alienated many of his colleagues in the workplace.',
  '彼のいらいらさせる話し方は職場の多くの同僚を遠ざけた。',
  'The abrasive tone of the criticism discouraged the young artist from exhibiting her work again.',
  '批評の耳障りな口調が、その若い芸術家に再び作品を展示する気をなくさせた。'),
(1181, 'platitude', '陳腐な言葉、決まり文句', '/ˈplætɪtjuːd/', 'プラティテュード',
  'The politician''s speech was filled with hollow platitudes that failed to address the real issues.',
  'その政治家の演説は実際の問題に対処できない空虚な決まり文句で満ちていた。',
  'Rather than offering genuine comfort, he resorted to mouthing platitudes about time healing all wounds.',
  '心からの慰めを提供する代わりに、彼は時間がすべての傷を癒すという陳腐な言葉を口にした。'),
(1182, 'aspiration', '野心、大望、大志', '/ˌæspəˈreɪʃn/', 'アスピレイション',
  'Her aspiration to become a Supreme Court justice motivated her throughout her legal career.',
  '最高裁判事になるという大志が法律家としてのキャリアを通じて彼女を動機づけた。',
  'The scholarship program supports students from disadvantaged backgrounds in achieving their aspirations.',
  'その奨学金プログラムは恵まれない環境の学生たちが大望を達成するのを支援している。'),
(1183, 'abhorrent', '嫌悪感を抱かせて', '/əbˈhɒrənt/', 'アブホレント',
  'The international community condemned the dictator''s abhorrent treatment of political prisoners.',
  '国際社会は独裁者の政治犯に対する嫌悪感を抱かせる扱いを非難した。',
  'Such abhorrent acts of cruelty have no place in a civilized society.',
  'そのような嫌悪感を抱かせる残酷な行為は文明社会にあってはならない。'),
(1184, 'auxiliary', '補助の;予備の', '/ɔːɡˈzɪliəri/', 'オーグジリアリー',
  'The hospital deployed auxiliary medical staff to cope with the sudden influx of patients.',
  '病院は患者の急増に対処するために補助の医療スタッフを配置した。',
  'An auxiliary power generator kicked in automatically when the main electricity supply was disrupted.',
  '主電力供給が途絶えると、予備の発電機が自動的に作動した。'),
(1185, 'nibble', '(食べ物など)を少しずつかじる', '/ˈnɪbl/', 'ニブル',
  'The mouse nibbled cautiously at the piece of cheese placed near the trap.',
  'ネズミは罠の近くに置かれたチーズを慎重に少しずつかじった。',
  'She nibbled on a biscuit while reading the lengthy report at her desk.',
  '彼女はデスクで長い報告書を読みながらビスケットを少しずつかじった。'),
(1186, 'penitent', '(犯した罪を)後悔して、ざんげして', '/ˈpenɪtənt/', 'ペニテント',
  'The penitent offender wrote a heartfelt letter of apology to the victims of his crime.',
  '後悔している犯罪者は自分の犯罪の被害者たちに心からの謝罪の手紙を書いた。',
  'With a penitent expression on his face, he confessed to having spread the malicious rumor.',
  'ざんげするような表情を浮かべ、彼は悪意のある噂を広めたことを告白した。'),
(1187, 'embitter', '(人)につらい思いをさせる', '/ɪmˈbɪtər/', 'エンビター',
  'Years of unjust treatment had embittered the once optimistic activist beyond recognition.',
  '何年にもわたる不当な扱いが、かつて楽観的だった活動家に見違えるほどつらい思いをさせた。',
  'The protracted legal dispute embittered both families, destroying a friendship that had lasted decades.',
  '長引く法的紛争が両家につらい思いをさせ、何十年も続いた友情を壊した。'),
(1188, 'bungle', '(仕事など)をしくじる', '/ˈbʌŋɡl/', 'バングル',
  'The inexperienced surgeon bungled the routine operation, resulting in serious complications for the patient.',
  '経験の浅い外科医がルーティンの手術をしくじり、患者に深刻な合併症をもたらした。',
  'The government bungled the evacuation effort, leaving thousands of residents stranded in the flood zone.',
  '政府は避難活動をしくじり、何千人もの住民が洪水地帯に取り残された。'),
(1189, 'hobble', '足を引きずって歩く', '/ˈhɒbl/', 'ホブル',
  'The injured marathon runner had to hobble across the finish line with a sprained ankle.',
  '負傷したマラソンランナーは足首の捻挫を抱えてゴールラインまで足を引きずって歩かなければならなかった。',
  'After the accident, he hobbled around the house on crutches for several weeks.',
  '事故の後、彼は数週間松葉杖で家の中を足を引きずって歩いた。'),
(1190, 'satirize', '~を風刺する、皮肉る', '/ˈsætəraɪz/', 'サタライズ',
  'The playwright brilliantly satirized the hypocrisy of the aristocratic class in her latest production.',
  'その劇作家は最新作で貴族階級の偽善を見事に風刺した。',
  'The popular television show satirizes contemporary political figures with uncanny accuracy.',
  'その人気テレビ番組は現代の政治家たちを不思議なほど正確に風刺している。'),
(1191, 'spree', '度を過ごすこと、ばか騒ぎ', '/spriː/', 'スプリー',
  'The lottery winner went on an extravagant spending spree that depleted his fortune within a year.',
  '宝くじの当選者は贅沢な散財に走り、1年以内に財産を使い果たした。',
  'The crime spree terrorized the neighborhood until the perpetrators were finally apprehended.',
  '犯罪者たちがついに逮捕されるまで、連続犯罪が近隣住民を恐怖に陥れた。'),
(1192, 'improvise', '(~を)即興で作る', '/ˈɪmprəvaɪz/', 'インプロヴァイズ',
  'When the teleprompter malfunctioned, the seasoned speaker was able to improvise effortlessly.',
  'テレプロンプターが故障したとき、経験豊富な講演者は難なく即興で話すことができた。',
  'The jazz musicians decided to improvise rather than follow the original arrangement.',
  'ジャズミュージシャンたちは原曲の編曲に従うのではなく即興で演奏することにした。'),
(1193, 'irk', '(人)をうんざりさせる、いらいらさせる', '/ɜːrk/', 'アーク',
  'It irked her that her contributions to the project were consistently overlooked by management.',
  'プロジェクトへの彼女の貢献が経営陣に一貫して見過ごされることが彼女をいらいらさせた。',
  'The constant interruptions during the meeting irked the presenter, who struggled to maintain composure.',
  '会議中の絶え間ない中断が発表者をうんざりさせ、冷静さを保つのに苦労した。'),
(1194, 'jeer', '(人を)あざける、やじる;あざけり、やじ', '/dʒɪər/', 'ジアー',
  'The hostile crowd began to jeer at the visiting team as they walked onto the pitch.',
  '敵意のある群衆はビジターチームがピッチに歩み出ると、やじり始めた。',
  'Despite the jeers from the opposition, the senator delivered her speech with unwavering conviction.',
  '野党からのやじにもかかわらず、その上院議員は揺るぎない信念をもって演説を行った。'),
(1195, 'flippant', '(人・発言などが)不真面目な、ふざけた', '/ˈflɪpənt/', 'フリパント',
  'His flippant response to the serious allegations only served to further infuriate the investigators.',
  '深刻な疑惑に対する彼のふざけた返答は捜査官たちをさらに激怒させるだけだった。',
  'The judge reprimanded the witness for making flippant remarks during the solemn court proceedings.',
  '裁判官は厳粛な法廷手続き中にふざけた発言をした証人を叱責した。'),
(1196, 'predilection', '強い好み、偏愛', '/ˌpriːdɪˈlekʃn/', 'プリーディレクション',
  'The author''s predilection for Gothic themes is evident throughout her extensive body of work.',
  'ゴシックのテーマへのその作家の偏愛は彼女の膨大な作品群全体を通じて明らかである。',
  'His predilection for rare vintage wines has made him a respected connoisseur in the industry.',
  '希少なビンテージワインへの強い好みが、彼を業界で尊敬される目利きにした。'),
(1197, 'enigmatic', '(人・ものが)不思議な、謎めいた', '/ˌenɪɡˈmætɪk/', 'エニグマティック',
  'The Mona Lisa''s enigmatic smile has captivated art enthusiasts for centuries.',
  'モナリザの謎めいた微笑みは何世紀にもわたって美術愛好家を魅了してきた。',
  'The enigmatic disappearance of the researcher baffled the police for over a decade.',
  'その研究者の不思議な失踪は10年以上にわたって警察を困惑させた。'),
(1198, 'allegory', '寓話;寓意的作品', '/ˈæləɡɔːri/', 'アレゴリー',
  'George Orwell''s "Animal Farm" is a celebrated allegory of the Russian Revolution.',
  'ジョージ・オーウェルの「動物農場」はロシア革命の有名な寓話である。',
  'The professor analyzed the medieval painting as an allegory of the struggle between virtue and vice.',
  '教授はその中世の絵画を美徳と悪徳の闘いの寓意的作品として分析した。'),
(1199, 'trickle', '(液体が)少しずつ流れる、したたり落ちる;滴、したたり', '/ˈtrɪkl/', 'トリクル',
  'A thin trickle of water seeped through the crack in the aging dam wall.',
  '老朽化したダムの壁の亀裂から細い滴がしみ出していた。',
  'News of the ceasefire began to trickle in from the war-torn region late in the evening.',
  '夕方遅くに停戦のニュースが戦争で荒廃した地域から少しずつ入り始めた。'),
(1200, 'inanimate', '生命のない、無生物の', '/ɪnˈænɪmət/', 'イナニメット',
  'The sculptor had an extraordinary ability to breathe life into inanimate blocks of marble.',
  'その彫刻家は生命のない大理石の塊に命を吹き込む並外れた能力を持っていた。',
  'Children often attribute human emotions to inanimate objects such as stuffed animals and dolls.',
  '子供たちはぬいぐるみや人形などの無生物にしばしば人間の感情を帰属させる。');
