-- words テーブル INSERT文 (No.1201 ~ No.1250)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1201, 'adjudicate', '(法廷などが)(事件など)を裁く', '/əˈdʒuːdɪkeɪt/', 'アジューディケイト',
  'The international tribunal was convened to adjudicate the territorial dispute that had persisted between the two nations for decades.',
  '国際裁判所は、二国間で数十年にわたり続いていた領土紛争を裁くために召集された。',
  'An independent panel was appointed to adjudicate claims of unfair dismissal filed by former employees of the corporation.',
  '不当解雇の申し立てを裁くために、独立した委員会がその企業の元従業員の訴えを審理するよう任命された。'),
(1202, 'connive', '共謀する;(悪事などを)見逃す、黙認する', '/kəˈnaɪv/', 'コナイヴ',
  'The investigation revealed that several officials had connived with the contractors to inflate the cost of the public infrastructure project.',
  '調査により、数人の役人が公共インフラ事業の費用を水増しするために業者と共謀していたことが明らかになった。',
  'The manager was accused of conniving at the widespread tax evasion that had been occurring within the department for years.',
  'その部長は、部署内で何年も行われていた広範な脱税を黙認していたとして告発された。'),
(1203, 'condescending', '(人・態度が)相手を見下すような、尊大な', '/ˌkɒndɪˈsɛndɪŋ/', 'コンディセンディング',
  'His condescending tone during the meeting alienated many of the junior researchers who had contributed significantly to the project.',
  '会議中の彼の見下すような口調は、プロジェクトに大きく貢献した多くの若手研究者たちを疎外した。',
  'The diplomat''s condescending remarks about developing nations drew sharp criticism from delegates at the international summit.',
  '発展途上国に対するその外交官の尊大な発言は、国際サミットの代表団から厳しい批判を浴びた。'),
(1204, 'dank', '(洞穴などが)じめじめした、湿っぽくて寒い', '/dæŋk/', 'ダンク',
  'The explorers descended into the dank cavern, where the air was so humid that moisture dripped continuously from the limestone ceiling.',
  '探検家たちはじめじめした洞窟に降りていき、そこは空気がとても湿っていて石灰岩の天井から絶えず水滴が落ちていた。',
  'The prisoners were confined to dank underground cells where the perpetual dampness caused rampant mould and respiratory ailments.',
  '囚人たちはじめじめした地下の独房に閉じ込められ、絶え間ない湿気がカビの蔓延と呼吸器疾患を引き起こした。'),
(1205, 'cursory', '大まかな、急ぎの', '/ˈkɜːrsəri/', 'カーサリー',
  'A cursory examination of the financial statements failed to reveal the sophisticated accounting fraud that had been perpetrated over several years.',
  '財務諸表の大まかな検査では、数年にわたって行われていた巧妙な会計詐欺を発見できなかった。',
  'The editor gave the manuscript only a cursory review before approving it, which resulted in numerous typographical errors in the published edition.',
  '編集者は原稿を急ぎの確認だけで承認したため、出版された版には多数の誤植が生じた。'),
(1206, 'faze', '(人)を狼狽させる、ひるませる', '/feɪz/', 'フェイズ',
  'The relentless questioning from the parliamentary committee did not faze the seasoned minister, who responded calmly to every allegation.',
  '議会委員会からの執拗な質問も、あらゆる疑惑に冷静に応じたベテラン大臣をひるませることはなかった。',
  'Even the prospect of performing before an audience of ten thousand did not faze the young virtuoso in the slightest.',
  '一万人の聴衆の前で演奏するという見通しも、その若き巨匠を少しも狼狽させなかった。'),
(1207, 'suave', '(特に男性が)温厚な、人当たりのよい', '/swɑːv/', 'スワーヴ',
  'The suave ambassador charmed every dignitary at the reception with his impeccable manners and fluency in multiple languages.',
  'その温厚な大使は、完璧な礼儀作法と多言語の流暢さで、レセプションのすべての要人を魅了した。',
  'Behind his suave exterior, the businessman concealed a ruthless determination to eliminate any competitor who stood in his way.',
  '人当たりのよい外見の裏に、その実業家は自分の前に立ちはだかるあらゆる競合相手を排除する冷酷な決意を隠していた。'),
(1208, 'conducive', '(よい結果に)資する、貢献する', '/kənˈdjuːsɪv/', 'コンデューシヴ',
  'The university has invested heavily in creating an environment conducive to interdisciplinary research and scholarly collaboration.',
  '大学は学際的な研究と学術的協力に資する環境の構築に多額の投資を行ってきた。',
  'The manager argued that the open-plan office layout was not conducive to the deep concentration required for complex analytical tasks.',
  'マネージャーは、オープンプランのオフィスレイアウトは複雑な分析業務に必要な深い集中に適していないと主張した。'),
(1209, 'obfuscate', '~をわかりにくくする', '/ˈɒbfʌskeɪt/', 'オブファスケイト',
  'The corporation''s spokesperson attempted to obfuscate the true extent of the environmental damage caused by the chemical spill.',
  'その企業の広報担当者は、化学物質の流出による環境被害の本当の規模をわかりにくくしようとした。',
  'Critics accused the politician of deliberately obfuscating the issue by burying crucial data in a labyrinth of bureaucratic jargon.',
  '批評家たちは、重要なデータを官僚的な専門用語の迷宮の中に埋めることで意図的に問題をわかりにくくしていると、その政治家を非難した。'),
(1210, 'sanctity', '神聖さ、尊厳', '/ˈsæŋktɪti/', 'サンクティティ',
  'The constitution enshrines the sanctity of individual rights, prohibiting any governmental encroachment upon fundamental freedoms.',
  '憲法は個人の権利の尊厳を明記しており、基本的自由に対するいかなる政府の侵害も禁じている。',
  'The archaeologists took great care to preserve the sanctity of the ancient burial site during their meticulous excavation.',
  '考古学者たちは、入念な発掘作業の間、古代の埋葬地の神聖さを保つことに細心の注意を払った。'),
(1211, 'elocution', '演説法;発声法、明晰な話し方', '/ˌɛləˈkjuːʃən/', 'エロキューション',
  'The barrister''s impeccable elocution and commanding presence in the courtroom swayed the jury in favour of his client.',
  'その法廷弁護士の完璧な演説法と法廷での堂々とした存在感が、陪審員を依頼人に有利な方へ動かした。',
  'She enrolled in elocution classes to refine her diction, as her new role as a television presenter demanded flawless delivery.',
  'テレビ司会者としての新しい役割には完璧な話し方が求められたため、彼女は発声法の教室に通い始めた。'),
(1212, 'amenable', '(忠告・提案・求めなどに)進んで従う、従順な', '/əˈmiːnəbl/', 'アミーナブル',
  'The union representatives proved amenable to the revised terms, paving the way for a swift resolution of the labour dispute.',
  '組合の代表者たちは修正条件に進んで従う姿勢を示し、労使紛争の迅速な解決への道を開いた。',
  'The new director was amenable to implementing innovative teaching methodologies that had been proposed by the faculty members.',
  '新しい学部長は、教員たちが提案していた革新的な教授法の導入に前向きだった。'),
(1213, 'creed', '信条、主義;(宗教の)教義', '/kriːd/', 'クリード',
  'The organisation''s founding creed emphasises the equal dignity of all human beings, regardless of ethnicity or social standing.',
  'その組織の創設信条は、民族や社会的地位に関係なく、すべての人間の平等な尊厳を強調している。',
  'People of every creed and background gathered in the square to demand an end to the discriminatory policies.',
  'あらゆる信条と背景を持つ人々が広場に集まり、差別的な政策の廃止を要求した。'),
(1214, 'cranky', '気難しい、怒りっぽい;(考え方・態度などが)風変わりな、奇妙な', '/ˈkræŋki/', 'クランキー',
  'The sleep-deprived toddler grew increasingly cranky, throwing tantrums at the slightest provocation throughout the afternoon.',
  '睡眠不足の幼児はますます気難しくなり、午後を通してちょっとしたことで癇癪を起こした。',
  'The professor was known for being cranky during morning lectures, often snapping at students who arrived even a minute late.',
  'その教授は朝の講義中に気難しいことで知られており、1分でも遅刻した学生によく怒鳴っていた。'),
(1215, 'disposition', '(人の)気質、傾向', '/ˌdɪspəˈzɪʃən/', 'ディスポジション',
  'Her naturally cheerful disposition made her an ideal candidate for the role of community liaison officer.',
  '生まれつき朗らかな気質が、地域連絡担当者の役割にうってつけの候補者にした。',
  'The psychologist noted that children raised in nurturing environments tend to develop a more optimistic disposition than those subjected to chronic neglect.',
  '心理学者は、養育環境で育った子供は、慢性的なネグレクトを受けた子供よりも楽観的な気質を発達させる傾向があると指摘した。'),
(1216, 'enliven', '~を活気づける、にぎやかにする', '/ɪnˈlaɪvən/', 'エンライヴン',
  'The arrival of the jazz ensemble enlivened the otherwise subdued charity gala, drawing guests onto the dance floor.',
  'ジャズアンサンブルの登場が、それまで控えめだったチャリティーガラを活気づけ、ゲストたちをダンスフロアに引き出した。',
  'The lecturer enlivened her presentation on cellular biology with vivid animations that captivated the entire auditorium.',
  '講師は鮮やかなアニメーションで細胞生物学のプレゼンテーションを活気づけ、聴講者全員を魅了した。'),
(1217, 'insolent', '(人・態度などが)生意気な、無礼な', '/ˈɪnsələnt/', 'インソレント',
  'The judge reprimanded the defendant for his insolent behaviour, warning that further contempt would result in severe penalties.',
  '裁判官は被告の無礼な態度を叱責し、これ以上の侮辱行為には厳しい罰則を科すと警告した。',
  'The ambassador lodged a formal complaint after the foreign minister made insolent remarks about her country''s sovereignty.',
  '外務大臣が彼女の国の主権について無礼な発言をした後、大使は正式な抗議を申し入れた。'),
(1218, 'ambient', '周囲の、環境の;(音楽が)リラックスできる', '/ˈæmbiənt/', 'アンビエント',
  'The researchers measured the ambient temperature at various altitudes to assess the impact of climate change on alpine ecosystems.',
  '研究者たちは、気候変動が高山生態系に与える影響を評価するために、さまざまな高度で周囲温度を測定した。',
  'The spa employed ambient music and soft lighting to create a tranquil atmosphere that would soothe even the most stressed patrons.',
  'そのスパは、最もストレスを抱えた客でも癒されるような穏やかな雰囲気を作り出すために、アンビエント音楽と柔らかい照明を用いた。'),
(1219, 'lunge', '突進する', '/lʌndʒ/', 'ランジ',
  'The fencer lunged forward with remarkable precision, scoring the decisive point that clinched the championship title.',
  'フェンシング選手は驚くべき正確さで突進し、選手権のタイトルを決定づける決勝点を獲得した。',
  'The suspect lunged at the security guard in a desperate attempt to flee, but was swiftly restrained by two officers nearby.',
  '容疑者は逃走しようと必死で警備員に突進したが、近くにいた二人の警官にすぐに取り押さえられた。'),
(1220, 'rig', '(投票・価格など)を不正に操作する', '/rɪɡ/', 'リグ',
  'The opposition party alleged that the ruling coalition had rigged the election by manipulating voter registration databases.',
  '野党は、与党連合が有権者登録データベースを操作して選挙を不正に操作したと主張した。',
  'Financial regulators discovered that several traders had conspired to rig the benchmark interest rate for their own profit.',
  '金融規制当局は、複数のトレーダーが自らの利益のために基準金利を不正に操作する共謀をしていたことを発見した。'),
(1221, 'partisan', '(盲目的・熱狂的な)支持者', '/ˈpɑːrtɪzæn/', 'パーティザン',
  'The newspaper was criticised for its partisan coverage of the presidential campaign, consistently favouring one candidate over all others.',
  'その新聞は、大統領選挙の党派的な報道について批判され、常に一人の候補者を他のすべての候補者よりも支持していた。',
  'Historians noted that the conflict attracted partisans from across the ideological spectrum, each driven by deeply held convictions.',
  '歴史家たちは、その紛争がイデオロギー的スペクトル全体から支持者を引き付け、各々が強い信念に突き動かされていたと指摘した。'),
(1222, 'rupture', '破裂;(友好関係の)決裂、断絶', '/ˈrʌptʃər/', 'ラプチャー',
  'The rupture of the main water pipeline left thousands of residents without access to clean drinking water for several days.',
  '主要な水道管の破裂により、数千人の住民が数日間清潔な飲料水を利用できなくなった。',
  'The diplomatic rupture between the two allies was precipitated by a series of trade disputes and intelligence-sharing controversies.',
  '二つの同盟国間の外交的決裂は、一連の貿易紛争と情報共有に関する論争によって引き起こされた。'),
(1223, 'shimmer', 'かすかに光る、揺らめいて光る', '/ˈʃɪmər/', 'シマー',
  'The surface of the lake shimmered under the midsummer moonlight, casting an ethereal glow across the surrounding woodland.',
  '湖面が真夏の月明かりの下でかすかに光り、周囲の森に幻想的な輝きを投げかけた。',
  'The silk gown shimmered with every movement she made, drawing admiring glances from the assembled guests at the state banquet.',
  '彼女が動くたびにシルクのガウンが揺らめいて光り、国賓晩餐会に集まった客たちの賞賛のまなざしを集めた。'),
(1224, 'loiter', '(目的もなく)うろうろする、ぶらつく', '/ˈlɔɪtər/', 'ロイター',
  'Security personnel were instructed to approach anyone seen loitering near the embassy and verify their identification.',
  '警備員は、大使館の近くでうろうろしている人物を見かけたら声をかけ、身分証明書を確認するよう指示された。',
  'The new municipal ordinance prohibits loitering in the vicinity of schools during hours of operation to ensure student safety.',
  '新しい市条例は、生徒の安全を確保するために、授業時間中の学校付近でのぶらつきを禁止している。'),
(1225, 'magnanimous', '度量の大きい、心の広い', '/mæɡˈnænɪməs/', 'マグナニマス',
  'In a magnanimous gesture, the victorious general granted full amnesty to the surrendering soldiers and facilitated their safe return home.',
  '度量の大きい行いとして、勝利した将軍は降伏した兵士たちに完全な恩赦を与え、彼らの安全な帰還を促進した。',
  'The billionaire philanthropist was magnanimous in her support, donating an unprecedented sum to establish scholarships for underprivileged students.',
  'その億万長者の慈善家は支援において心が広く、恵まれない学生のための奨学金を設立するために前例のない額を寄付した。'),
(1226, 'scrumptious', '(食べ物が)とてもおいしい', '/ˈskrʌmpʃəs/', 'スクランプシャス',
  'The guests unanimously praised the scrumptious seven-course dinner prepared by the Michelin-starred chef for the anniversary celebration.',
  '招待客たちは、記念祝賀会のためにミシュラン星付きシェフが用意したとてもおいしい七品のディナーを満場一致で称賛した。',
  'The aroma wafting from the bakery was irresistible, and the freshly baked croissants turned out to be absolutely scrumptious.',
  'パン屋から漂ってくる香りは抗いがたく、焼きたてのクロワッサンは本当にとてもおいしかった。'),
(1227, 'scant', '不十分な、乏しい', '/skænt/', 'スカント',
  'The humanitarian organisation received scant funding from international donors, severely hampering its relief efforts in the disaster-stricken region.',
  '人道支援組織は国際的な寄付者からの資金が乏しく、被災地での救援活動が大きく妨げられた。',
  'The report paid scant attention to the environmental consequences of the proposed mining operation, drawing fierce criticism from ecologists.',
  'その報告書は提案された採掘事業の環境への影響にほとんど注意を払っておらず、生態学者たちから激しい批判を浴びた。'),
(1228, 'putrid', '腐敗した;悪臭のする', '/ˈpjuːtrɪd/', 'ピュートリッド',
  'The health inspector condemned the warehouse after discovering putrid meat that had been stored without proper refrigeration for weeks.',
  '衛生検査官は、適切な冷蔵なしに何週間も保管されていた腐敗した肉を発見した後、その倉庫を使用禁止にした。',
  'A putrid odour emanating from the abandoned factory prompted local residents to file formal complaints with the municipal authorities.',
  '廃工場から漂う悪臭のため、地元住民は市当局に正式な苦情を申し立てた。'),
(1229, 'muddle', '(思考など)を混乱させる;~をごちゃまぜにする、混同する;ごたごた、混乱', '/ˈmʌdl/', 'マドル',
  'The contradictory instructions from multiple supervisors muddled the new employee, who struggled to determine which directives to follow.',
  '複数の上司からの矛盾した指示が新入社員を混乱させ、どの指示に従うべきか判断するのに苦労した。',
  'The administrative muddle surrounding the visa application process deterred many qualified professionals from seeking employment in the country.',
  'ビザ申請手続きをめぐる事務的な混乱が、多くの有能な専門家をその国での就職活動から遠ざけた。'),
(1230, 'eclectic', '(考え方・人などが)偏らずに幅広い、折衷的な', '/ɪˈklɛktɪk/', 'エクレクティック',
  'The curator assembled an eclectic collection of artworks spanning five centuries, encompassing everything from Renaissance paintings to contemporary installations.',
  '学芸員は5世紀にまたがる折衷的な美術品のコレクションをまとめ、ルネサンス絵画から現代のインスタレーションまですべてを網羅した。',
  'Her eclectic taste in literature ranged from classical Greek tragedies to avant-garde postmodern novels, reflecting her insatiable intellectual curiosity.',
  '彼女の幅広い文学の趣味は古典ギリシャ悲劇から前衛的なポストモダン小説にまで及び、飽くなき知的好奇心を反映していた。'),
(1231, 'jovial', '陽気な、楽しげな', '/ˈdʒoʊviəl/', 'ジョウヴィアル',
  'The jovial host welcomed each guest with a warm embrace, ensuring that everyone felt at ease from the moment they arrived.',
  '陽気な主催者は一人一人の客を温かい抱擁で迎え、到着した瞬間から全員がくつろげるようにした。',
  'Despite the gravity of the economic crisis, the prime minister maintained a jovial demeanour during the press conference to reassure the public.',
  '経済危機の深刻さにもかかわらず、首相は国民を安心させるために記者会見中、楽しげな態度を保った。'),
(1232, 'proffer', '(助言・情報など)を与える、提供する', '/ˈprɒfər/', 'プロファー',
  'The seasoned diplomat proffered his expertise to the newly appointed envoy, who gratefully accepted the guidance on navigating delicate negotiations.',
  '経験豊富な外交官が新任の特使に専門知識を提供し、特使は繊細な交渉の進め方についての助言をありがたく受け入れた。',
  'The witness proffered crucial evidence that had previously been overlooked, fundamentally altering the trajectory of the investigation.',
  '証人は以前見落とされていた重要な証拠を提供し、捜査の方向性を根本的に変えた。'),
(1233, 'cogent', '説得力のある、納得のいく', '/ˈkoʊdʒənt/', 'コウジェント',
  'The barrister presented a cogent argument that systematically dismantled every aspect of the prosecution''s case against her client.',
  '弁護士は、依頼人に対する検察の主張のあらゆる側面を体系的に崩す説得力のある論証を展開した。',
  'The committee found the researcher''s proposal cogent and well-substantiated, unanimously voting to allocate additional funding for the study.',
  '委員会はその研究者の提案を説得力があり十分な根拠があると判断し、全会一致でその研究への追加資金の配分を可決した。'),
(1234, 'reel', '(人・心などが)混乱する、動揺する;(人が)よろめく', '/riːl/', 'リール',
  'The entire nation reeled from the devastating earthquake, which had reduced entire neighbourhoods to rubble in a matter of seconds.',
  '国全体が壊滅的な地震に動揺し、その地震はわずか数秒で街全体を瓦礫の山に変えた。',
  'Still reeling from the unexpected merger announcement, the employees struggled to concentrate on their daily responsibilities.',
  '予期せぬ合併発表にまだ動揺しながら、従業員たちは日々の業務に集中するのに苦労した。'),
(1235, 'scorn', '(人・考えなど)を軽蔑する、ばかにする;軽蔑、さげすみ', '/skɔːrn/', 'スコーン',
  'The literary establishment initially scorned the young author''s experimental prose, only to later hail it as a groundbreaking masterpiece.',
  '文壇は当初、その若い作家の実験的な散文を軽蔑したが、後にそれを画期的な傑作として称賛することになった。',
  'She regarded their narrow-minded prejudices with undisguised scorn, refusing to compromise her principles to gain their approval.',
  '彼女は彼らの偏狭な偏見をあからさまな軽蔑をもって見つめ、承認を得るために自分の原則を妥協することを拒んだ。'),
(1236, 'bereft', '(家族・友人との死別で)打ちひしがれた;奪われた', '/bɪˈrɛft/', 'ビレフト',
  'Bereft of her lifelong companion, the elderly woman found solace in the memories they had shared over six decades of marriage.',
  '生涯の伴侶を失い打ちひしがれたその年配の女性は、60年にわたる結婚生活で共有した思い出に慰めを見出した。',
  'The once-thriving community was left bereft of essential services after the government withdrew funding for the regional hospital.',
  '政府が地域病院への資金を打ち切った後、かつて繁栄していた地域社会は不可欠なサービスを奪われた。'),
(1237, 'blurb', '(新刊本・新製品の)宣伝文、推薦文', '/blɜːrb/', 'ブラーブ',
  'The publisher commissioned a renowned literary critic to write the blurb for the debut novel, hoping to boost initial sales.',
  '出版社は初版の売上を伸ばすことを期待して、著名な文芸評論家にその処女小説の推薦文を書くよう依頼した。',
  'The blurb on the back cover described the thriller as a masterful exploration of political corruption, instantly piquing readers'' curiosity.',
  '裏表紙の宣伝文はそのスリラーを政治腐敗の見事な探究と評しており、読者の好奇心を即座にかき立てた。'),
(1238, 'jocular', 'ひょうきんな、おどけた', '/ˈdʒɒkjʊlər/', 'ジョキュラー',
  'The professor''s jocular manner of explaining complex theories made even the most abstruse concepts accessible to undergraduate students.',
  'その教授のひょうきんな複雑な理論の説明方法は、最も難解な概念さえも学部生にわかりやすくした。',
  'His jocular remarks at the beginning of the conference lightened the mood and set a collegial tone for the ensuing deliberations.',
  '会議冒頭のおどけた発言が雰囲気を和らげ、その後の審議に対して友好的な雰囲気を作った。'),
(1239, 'saunter', 'のんびり[ぶらぶら]歩く', '/ˈsɔːntər/', 'ソーンター',
  'The detective sauntered through the bustling marketplace, discreetly observing the movements of the suspect from a safe distance.',
  '刑事は賑やかな市場をのんびり歩きながら、安全な距離から容疑者の動きをさりげなく観察した。',
  'On Sunday afternoons, the couple would saunter along the riverbank, savouring the tranquillity that the countryside afforded them.',
  '日曜日の午後、夫婦は川沿いをぶらぶら歩き、田園地帯がもたらす静けさを満喫したものだった。'),
(1240, 'binge', '過度の熱中;どんちゃん騒ぎをする', '/bɪndʒ/', 'ビンジ',
  'The psychologist warned that prolonged binge-watching of television series could have detrimental effects on both mental health and sleep patterns.',
  '心理学者は、テレビシリーズの長時間にわたる過度の視聴は精神的健康と睡眠パターンの両方に悪影響を及ぼす可能性があると警告した。',
  'After weeks of strict dieting, she went on a binge, consuming an enormous quantity of food in a single sitting.',
  '何週間もの厳しいダイエットの後、彼女はどんちゃん騒ぎをし、一度に膨大な量の食べ物を食べた。'),
(1241, 'lampoon', '~を風刺する、茶化す', '/læmˈpuːn/', 'ランプーン',
  'The satirical magazine lampooned the prime minister''s economic policies with a series of scathing cartoons that went viral on social media.',
  '風刺雑誌は首相の経済政策を一連の痛烈な漫画で風刺し、それがソーシャルメディアで拡散した。',
  'The playwright lampooned the pretensions of the aristocracy in a witty farce that delighted audiences and infuriated the nobility in equal measure.',
  'その劇作家は機知に富んだ喜劇で貴族の気取りを茶化し、観客を喜ばせると同時に貴族たちを憤慨させた。'),
(1242, 'twinge', '心の痛み;うずくような痛み', '/twɪndʒ/', 'トゥインジ',
  'She felt a twinge of guilt upon realising that her harsh words had deeply wounded her closest colleague.',
  '自分の厳しい言葉が最も親しい同僚を深く傷つけたと気づいたとき、彼女は良心の痛みを感じた。',
  'The athlete ignored the twinge in his knee during the final sprint, only to discover later that he had torn a ligament.',
  'そのアスリートは最後のスプリント中に膝のうずくような痛みを無視したが、後に靱帯を断裂していたことがわかった。'),
(1243, 'vexing', 'いら立たしい、厄介な', '/ˈvɛksɪŋ/', 'ヴェクシング',
  'The persistent software glitch proved to be a vexing problem that eluded even the most experienced engineers on the development team.',
  '持続するソフトウェアの不具合は、開発チームの最も経験豊富なエンジニアでさえも解決できない厄介な問題であることが判明した。',
  'The vexing ambiguity of the new regulation left many businesses uncertain about their compliance obligations.',
  '新しい規制の厄介な曖昧さにより、多くの企業がコンプライアンス義務について不確かなままだった。'),
(1244, 'tabulate', '(数字・情報など)を表にする、まとめる', '/ˈtæbjʊleɪt/', 'タビュレイト',
  'The research assistants meticulously tabulated the survey responses, categorising them by demographic variables for subsequent statistical analysis.',
  '研究助手たちは調査回答を丹念に表にまとめ、その後の統計分析のために人口統計変数ごとに分類した。',
  'Election officials worked through the night to tabulate the ballots, with the final results expected to be announced by dawn.',
  '選挙管理委員たちは投票用紙を表にまとめるために夜通し作業し、最終結果は夜明けまでに発表される見込みだった。'),
(1245, 'parched', '(土地などが)干からびた、からからに乾いた', '/pɑːrtʃt/', 'パーチト',
  'The prolonged drought left the once-fertile agricultural land completely parched, devastating the livelihoods of thousands of farmers.',
  '長引く干ばつにより、かつて肥沃だった農地は完全に干からび、数千人の農民の生計を壊滅させた。',
  'After hiking for hours under the scorching sun without adequate water, the explorers were utterly parched and on the verge of dehydration.',
  '十分な水もなく灼熱の太陽の下で何時間もハイキングした後、探検家たちはからからに乾いて脱水状態の寸前だった。'),
(1246, 'delectable', '非常においしい、おいしそうなにおいの', '/dɪˈlɛktəbl/', 'デレクタブル',
  'The Michelin-starred restaurant served a delectable array of courses, each one a testament to the chef''s extraordinary culinary artistry.',
  'ミシュラン星付きのレストランは非常においしい料理の数々を提供し、その一品一品がシェフの卓越した料理の技の証だった。',
  'The delectable aroma of freshly brewed coffee permeated the entire office, instantly lifting the spirits of the exhausted staff.',
  '淹れたてのコーヒーのおいしそうな香りがオフィス全体に漂い、疲れ切ったスタッフの気分を即座に高めた。'),
(1247, 'scrawny', 'やせこけた', '/ˈskrɔːni/', 'スクローニー',
  'The veterinarian nursed the scrawny stray cat back to health, providing it with proper nutrition and medical treatment over several weeks.',
  '獣医師はやせこけた野良猫を数週間にわたって適切な栄養と治療を与えて健康を回復させた。',
  'Despite his scrawny build, the young wrestler possessed remarkable agility and technique that consistently confounded larger opponents.',
  'やせこけた体格にもかかわらず、その若いレスラーは驚くべき敏捷性と技術を備えており、常に大柄な対戦相手を混乱させた。'),
(1248, 'myriad', '[a myriad of ~]無数の～', '/ˈmɪriəd/', 'ミリアド',
  'The coral reef sustains a myriad of marine species, making it one of the most biodiverse ecosystems on the planet.',
  'そのサンゴ礁は無数の海洋生物種を支えており、地球上で最も生物多様性に富む生態系の一つとなっている。',
  'Researchers face a myriad of challenges when attempting to replicate the complex biochemical processes that occur within living cells.',
  '研究者たちは生細胞内で起こる複雑な生化学的プロセスを再現しようとする際に、無数の課題に直面する。'),
(1249, 'soar', '(数値・温度・価格などが)急上昇する;(空高く)舞い上がる', '/sɔːr/', 'ソアー',
  'Property prices in the capital soared by nearly forty per cent in a single year, exacerbating the already severe housing affordability crisis.',
  '首都の不動産価格がわずか1年で約40パーセント急上昇し、すでに深刻だった住宅の手頃さの危機をさらに悪化させた。',
  'The eagle soared majestically above the mountain peaks, riding the thermal currents with effortless grace.',
  '鷲が山の頂上の上を雄大に舞い上がり、上昇気流に乗って優雅に滑空した。'),
(1250, 'backlash', '(社会的)反発', '/ˈbæklæʃ/', 'バックラッシュ',
  'The government''s decision to raise the retirement age provoked a fierce backlash from labour unions, culminating in a nationwide general strike.',
  '政府の定年引き上げの決定は労働組合からの激しい反発を招き、全国的なゼネストに発展した。',
  'The celebrity faced an intense public backlash after making dismissive comments about the struggles of low-income families during a television interview.',
  'その有名人はテレビインタビュー中に低所得家庭の苦労について軽視する発言をした後、激しい世論の反発に直面した。');
