-- words テーブル INSERT文 (No.1301 ~ No.1350)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1301, 'exterminate', '(種族・動物など)を皆殺しにする、根絶する', '/ɪkˈstɜːrmɪneɪt/', 'イクスターミネイト',
  'The government launched an aggressive campaign to exterminate the invasive species threatening local ecosystems.',
  '政府は地域の生態系を脅かす外来種を根絶するために積極的なキャンペーンを開始した。',
  'Historical records reveal the horrific attempts to exterminate entire ethnic groups during the conflict.',
  '歴史的記録は、その紛争中に民族全体を皆殺しにしようとした恐ろしい試みを明らかにしている。'),
(1302, 'upstart', '新興企業;成り上がり者、成金', '/ˈʌpstɑːrt/', 'アップスタート',
  'The upstart technology firm disrupted the entire industry with its innovative business model.',
  'その新興のテクノロジー企業は革新的なビジネスモデルで業界全体を一変させた。',
  'Established politicians dismissed him as a mere upstart with no real governing experience.',
  '既存の政治家たちは彼を実際の統治経験のない単なる成り上がり者として退けた。'),
(1303, 'mentor', 'よき指導者、助言者', '/ˈmentɔːr/', 'メンター',
  'She credits her academic mentor with inspiring her to pursue a career in neuroscience.',
  '彼女は神経科学のキャリアを追求するきっかけを与えてくれた学問上の指導者に感謝している。',
  'The program pairs experienced professionals with young graduates who need a mentor to navigate the corporate world.',
  'そのプログラムはビジネス界を歩むための助言者を必要とする若い卒業生と経験豊富な専門家を組み合わせる。'),
(1304, 'drenched', 'びしょぬれの、浸された', '/drentʃt/', 'ドレンチト',
  'The hikers arrived at the shelter completely drenched after being caught in a sudden downpour.',
  'ハイカーたちは突然の豪雨に見舞われ、完全にびしょぬれの状態でシェルターに到着した。',
  'The fields lay drenched in morning dew, glistening under the first rays of sunlight.',
  '畑は朝露に浸され、最初の日差しの下できらきらと輝いていた。'),
(1305, 'decor', '装飾、内装', '/deɪˈkɔːr/', 'デコー',
  'The restaurant''s elegant decor, featuring handcrafted wooden panels, impressed every guest.',
  '手作りの木製パネルを特徴とするそのレストランの優雅な内装はすべてのゲストを感銘させた。',
  'She spent months selecting the perfect decor for her newly renovated apartment.',
  '彼女は新しく改装したアパートの完璧な装飾を選ぶのに数か月を費やした。'),
(1306, 'swap', '~を交換する;交換', '/swɑːp/', 'スワップ',
  'The two nations agreed to swap prisoners of war as a gesture of goodwill during negotiations.',
  '両国は交渉中の善意の表れとして戦争捕虜を交換することに合意した。',
  'Currency swaps between central banks can help stabilize exchange rates during financial crises.',
  '中央銀行間の通貨交換は金融危機時に為替レートの安定化に役立つことがある。'),
(1307, 'flunk', '(試験など)に不合格になる、落第する', '/flʌŋk/', 'フランク',
  'Despite studying diligently, she was devastated to flunk the bar examination on her first attempt.',
  '熱心に勉強したにもかかわらず、彼女は初回の受験で司法試験に不合格になり打ちのめされた。',
  'Students who flunk the entrance exam are encouraged to retake it the following year.',
  '入学試験に落第した学生は翌年に再受験することを奨励されている。'),
(1308, 'sinister', '邪悪な、悪意のある;不吉な', '/ˈsɪnɪstər/', 'シニスター',
  'The detective sensed something sinister lurking behind the seemingly ordinary facade of the building.',
  '刑事はその建物の一見普通の外観の裏に何か不吉なものが潜んでいるのを感じ取った。',
  'The politician''s sinister motives were eventually exposed by investigative journalists.',
  'その政治家の邪悪な動機はやがて調査報道記者によって暴かれた。'),
(1310, 'implicate', '(悪事などへの)~の関与を示す[示唆する]', '/ˈɪmplɪkeɪt/', 'インプリケイト',
  'The leaked documents implicate several high-ranking officials in the embezzlement scheme.',
  '流出した文書は横領計画への数名の高官の関与を示唆している。',
  'Forensic evidence collected at the scene implicated the suspect in the robbery.',
  '現場で収集された法医学的証拠が容疑者の強盗への関与を示した。'),
(1311, 'pragmatic', '現実的な、実践的な', '/præɡˈmætɪk/', 'プラグマティック',
  'The committee adopted a pragmatic approach to budget allocation, prioritizing essential services.',
  '委員会は予算配分に現実的なアプローチを採用し、必要不可欠なサービスを優先した。',
  'Rather than pursuing idealistic goals, the prime minister took a pragmatic stance on foreign policy.',
  '理想主義的な目標を追求するのではなく、首相は外交政策に対して現実的な姿勢をとった。'),
(1312, 'empathize', '(人・こと・状況に)共感する、感情移入する', '/ˈempəθaɪz/', 'エンパサイズ',
  'Skilled therapists are trained to empathize with their patients without losing professional objectivity.',
  '熟練したセラピストは専門的な客観性を失うことなく患者に共感するよう訓練されている。',
  'It is difficult to empathize with the plight of refugees unless one has experienced displacement firsthand.',
  '自分自身が避難を経験していない限り、難民の苦境に共感することは難しい。'),
(1313, 'slump', '(価格・価値などが)急落する;どさっと落ちる[座り込む];低迷、不振;(急激な)下落、落ち込み', '/slʌmp/', 'スランプ',
  'Stock prices slumped dramatically after the central bank announced an unexpected interest rate hike.',
  '中央銀行が予想外の利上げを発表した後、株価は劇的に急落した。',
  'The prolonged economic slump forced numerous small businesses into bankruptcy.',
  '長期にわたる経済の低迷は多くの中小企業を倒産に追い込んだ。'),
(1314, 'posture', '(体の)姿勢;(精神的な)姿勢、態度;格好をつける、ポーズを取る', '/ˈpɑːstʃər/', 'ポスチャー',
  'Poor posture over many years can lead to chronic back pain and spinal deformities.',
  '長年にわたる悪い姿勢は慢性的な腰痛や脊椎の変形を引き起こしうる。',
  'The government''s aggressive diplomatic posture alarmed neighboring countries.',
  '政府の攻撃的な外交姿勢は近隣諸国を警戒させた。'),
(1315, 'lag', '遅れを取る;遅れること', '/læɡ/', 'ラグ',
  'Developing nations often lag behind industrialized countries in terms of technological infrastructure.',
  '発展途上国は技術的インフラの面で先進国に遅れを取ることが多い。',
  'There is typically a significant lag between the implementation of a policy and its observable effects.',
  '政策の実施とその目に見える効果の間には通常、大きな遅れがある。'),
(1316, 'lenient', '(人・判決などが)寛大な、甘い', '/ˈliːniənt/', 'リーニエント',
  'Critics argued that the judge was too lenient in sentencing the convicted fraudster.',
  '批評家たちは裁判官が有罪判決を受けた詐欺師への量刑において寛大すぎたと主張した。',
  'Some educators believe that overly lenient grading standards undermine academic rigor.',
  '一部の教育者は過度に甘い成績評価基準が学問的厳格さを損なうと考えている。'),
(1317, 'deflect', '(注意・批判など)をかわす;(進路から)(もの)をそらす', '/dɪˈflekt/', 'ディフレクト',
  'The spokesperson attempted to deflect criticism by shifting the focus to the administration''s achievements.',
  '報道官は焦点を政権の業績に移すことで批判をかわそうとした。',
  'The armor was designed to deflect incoming projectiles and protect the wearer from serious injury.',
  'その装甲は飛来する弾丸をそらし、着用者を重傷から守るように設計された。'),
(1318, 'protagonist', '(小説・映画などの)主役、主人公', '/proʊˈtæɡənɪst/', 'プロタゴニスト',
  'The novel''s protagonist undergoes a profound transformation as she confronts her traumatic past.',
  'その小説の主人公はトラウマ的な過去と向き合う中で深い変容を遂げる。',
  'Many literary critics regard Hamlet as one of the most complex protagonists in Western literature.',
  '多くの文学批評家はハムレットを西洋文学における最も複雑な主人公の一人と見なしている。'),
(1319, 'elastic', '(材質が)弾力性のある、伸縮性の', '/ɪˈlæstɪk/', 'イラスティック',
  'The elastic nature of the material allows it to stretch without tearing under moderate pressure.',
  'その素材の弾力性のある性質により、適度な圧力の下で破れることなく伸びることができる。',
  'Economists describe consumer demand for luxury goods as relatively elastic compared to necessities.',
  '経済学者は贅沢品に対する消費者の需要を必需品と比較して比較的弾力性があると説明する。'),
(1320, 'amplify', '~を拡大する、増大する;(信号など)を増幅する', '/ˈæmplɪfaɪ/', 'アンプリファイ',
  'Social media platforms can amplify misinformation, spreading it to millions within hours.',
  'ソーシャルメディアのプラットフォームは偽情報を増幅し、数時間以内に数百万人に拡散させることがある。',
  'The engineer used a specialized device to amplify the weak signal received from the satellite.',
  'エンジニアは衛星から受信した微弱な信号を増幅するために専用の装置を使用した。'),
(1322, 'breach', '(法律・協定など)を破る', '/briːtʃ/', 'ブリーチ',
  'The corporation was sued for breaching the terms of the confidentiality agreement.',
  'その企業は秘密保持契約の条件を破ったとして訴えられた。',
  'Any attempt to breach the ceasefire will be met with immediate military retaliation.',
  '停戦を破るいかなる試みも即座に軍事的報復を受けるだろう。'),
(1323, 'linger', '(人が)立ち去りかねている、ぐずぐずする;(戦争・病気などが)長引く', '/ˈlɪŋɡər/', 'リンガー',
  'The haunting melody continued to linger in her mind long after the concert had ended.',
  'そのもの悲しい旋律はコンサートが終わった後もずっと彼女の心に残り続けた。',
  'Doubts about the safety of the vaccine lingered among certain segments of the population.',
  'ワクチンの安全性に対する疑念が人口の特定の層の間で長引いた。'),
(1324, 'speculation', '推測、憶測;投機、思惑買い', '/ˌspekjəˈleɪʃən/', 'スペキュレイション',
  'Rampant speculation in the real estate market contributed to the devastating financial crash.',
  '不動産市場における横行する投機が壊滅的な金融崩壊の一因となった。',
  'There has been widespread speculation about the prime minister''s intention to resign.',
  '首相の辞任の意図についての広範な憶測がなされている。'),
(1325, 'ordeal', '辛い体験、試練', '/ɔːrˈdiːl/', 'オーディール',
  'The hostages described their ordeal as the most terrifying experience of their lives.',
  '人質たちは自分たちの試練を人生で最も恐ろしい体験だったと述べた。',
  'Recovering from the surgery proved to be a long and painful ordeal for the elderly patient.',
  '手術からの回復はその高齢の患者にとって長く辛い試練であることが判明した。'),
(1326, 'embody', '(思想・理念など)を具体的な形に表す、具現[体現]する', '/ɪmˈbɑːdi/', 'エンバディ',
  'The constitution is meant to embody the fundamental values of liberty and justice.',
  '憲法は自由と正義の根本的な価値を体現することを意図している。',
  'Her tireless dedication to humanitarian work embodies the spirit of selfless service.',
  '人道的活動への彼女のたゆまぬ献身は無私の奉仕の精神を具現している。'),
(1327, 'whim', '気まぐれ、思いつき', '/wɪm/', 'ウィム',
  'The billionaire purchased the island on a whim, without any prior planning or deliberation.',
  'その億万長者は事前の計画や熟考なしに気まぐれでその島を購入した。',
  'Government policy should not be dictated by the whims of a single individual.',
  '政府の政策は一個人の気まぐれに左右されるべきではない。'),
(1328, 'muffle', '(音・声)を消す;(防寒具などで)(体など)を包む、くるむ', '/ˈmʌfl/', 'マッフル',
  'Thick curtains were installed to muffle the noise from the busy street outside.',
  '外の賑やかな通りからの騒音を消すために厚いカーテンが設置された。',
  'She muffled her face in a scarf to protect herself from the biting winter wind.',
  '彼女は身を切るような冬の風から身を守るためにスカーフで顔をくるんだ。'),
(1329, 'adulation', '(過度の)絶賛、称賛', '/ˌædʒəˈleɪʃən/', 'アジュレイション',
  'The rock star basked in the adulation of thousands of adoring fans at the concert.',
  'そのロックスターはコンサートで何千人もの熱狂的なファンの絶賛に浸っていた。',
  'Excessive adulation from subordinates can distort a leader''s perception of reality.',
  '部下からの過度の称賛は指導者の現実認識を歪めることがある。'),
(1330, 'disavow', '(関係・責任など)を否定する', '/ˌdɪsəˈvaʊ/', 'ディサヴァウ',
  'The organization publicly disavowed any connection to the extremist faction.',
  'その組織は過激派との一切の関係を公に否定した。',
  'The senator was forced to disavow his earlier remarks after they sparked a national controversy.',
  'その上院議員は自身の先の発言が全国的な論争を引き起こした後、発言を否定せざるを得なかった。'),
(1331, 'poised', '準備ができて', '/pɔɪzd/', 'ポイズド',
  'The company is poised to launch its most ambitious product line in the coming quarter.',
  'その企業は来四半期に最も野心的な製品ラインを発売する準備ができている。',
  'With her extensive training complete, the astronaut was poised for her first mission to space.',
  '広範な訓練を終え、その宇宙飛行士は初の宇宙ミッションへの準備ができていた。'),
(1332, 'expediency', '方便、打算、ご都合主義', '/ɪkˈspiːdiənsi/', 'エクスピーディエンシー',
  'The decision was driven by political expediency rather than genuine concern for public welfare.',
  'その決定は公共の福祉に対する真の関心ではなく、政治的な打算によって動かされた。',
  'Critics accused the administration of sacrificing long-term sustainability for short-term expediency.',
  '批評家たちは政権が短期的な方便のために長期的な持続可能性を犠牲にしていると非難した。'),
(1334, 'hubris', '傲慢、思い上がり', '/ˈhjuːbrɪs/', 'ヒューブリス',
  'The CEO''s hubris led him to dismiss the warnings of his advisors, ultimately resulting in the company''s downfall.',
  'CEOの傲慢さは顧問たちの警告を退けさせ、最終的に会社の没落をもたらした。',
  'Ancient Greek tragedies often depicted the destruction wrought by hubris in the face of the gods.',
  '古代ギリシャの悲劇はしばしば神々に対する思い上がりがもたらす破滅を描いた。'),
(1335, 'gloss', '光沢、つや', '/ɡlɑːs/', 'グロス',
  'The new furniture polish restores the natural gloss of wooden surfaces without leaving residue.',
  '新しい家具用つや出し剤は残留物を残さずに木製表面の自然な光沢を回復させる。',
  'Beneath the gloss of the company''s annual report lay a troubling pattern of declining profits.',
  'その会社の年次報告書の光沢の裏には、利益減少という憂慮すべきパターンが潜んでいた。'),
(1336, 'grovel', '(強い者に)ひれ伏す、卑屈な振る舞いをする', '/ˈɡrɑːvl/', 'グロヴェル',
  'The disgraced official was forced to grovel before the committee, begging for a second chance.',
  '不名誉を被った役人は委員会の前でひれ伏し、もう一度の機会を懇願することを余儀なくされた。',
  'She refused to grovel for approval from those who had never shown her any respect.',
  '彼女は一度も敬意を示さなかった人々に対して卑屈に振る舞って承認を求めることを拒んだ。'),
(1337, 'layover', '(旅行先での)途中下車、一時的滞在', '/ˈleɪoʊvər/', 'レイオーヴァー',
  'Due to the flight cancellation, passengers faced an unexpected twelve-hour layover in Dubai.',
  '航空便のキャンセルにより、乗客はドバイでの予期しない12時間の一時的滞在に直面した。',
  'She took advantage of her layover in Singapore to explore the city''s renowned street food scene.',
  '彼女はシンガポールでの途中下車を利用して、街の有名なストリートフードを探索した。'),
(1338, 'fling', '(もの)を投げつける、さっと投げる', '/flɪŋ/', 'フリング',
  'In a fit of rage, he flung the documents across the room, scattering papers everywhere.',
  '怒りに駆られて彼は書類を部屋の向こうに投げつけ、紙をあちこちに散らした。',
  'The protesters flung stones at the barricade in a desperate attempt to break through.',
  '抗議者たちはバリケードを突破しようと必死に石を投げつけた。'),
(1339, 'wean', '(赤ん坊)を離乳させる;(人)に(~を)徐々にやめさせる', '/wiːn/', 'ウィーン',
  'The government introduced subsidies for renewable energy to wean the nation off its dependence on fossil fuels.',
  '政府は化石燃料への依存を国に徐々にやめさせるために再生可能エネルギーへの補助金を導入した。',
  'Pediatricians generally recommend beginning to wean infants from breast milk at around six months.',
  '小児科医は一般的に生後約6か月で乳児を母乳から離乳させ始めることを推奨している。'),
(1340, 'shove', '~を(力任せに)押す、押しのける', '/ʃʌv/', 'シャヴ',
  'The crowd surged forward, and panicked spectators began to shove one another toward the exits.',
  '群衆が前方に押し寄せ、パニックになった観客は出口に向かって互いを押しのけ始めた。',
  'He shoved the heavy cabinet aside to reveal a hidden door behind it.',
  '彼は重い戸棚を力任せに押しのけ、その背後に隠された扉を露わにした。'),
(1341, 'limp', '柔弱な、弱々しい', '/lɪmp/', 'リンプ',
  'After hours of exposure to the scorching sun, the flowers hung limp and wilted in the garden.',
  '灼熱の太陽に何時間もさらされた後、花は庭で弱々しくしおれて垂れ下がっていた。',
  'His limp handshake failed to inspire any confidence among the potential investors.',
  '彼の弱々しい握手は潜在的な投資家たちに何の信頼も与えなかった。'),
(1342, 'sloth', '怠惰、無精', '/slɔːθ/', 'スロース',
  'The philosopher warned that intellectual sloth is the greatest obstacle to personal enlightenment.',
  'その哲学者は知的怠惰が自己啓発に対する最大の障害であると警告した。',
  'Years of sloth had left him physically unfit and unable to cope with the demands of the new position.',
  '何年にもわたる怠惰は彼の体力を衰えさせ、新しい職位の要求に対処できなくさせていた。'),
(1343, 'interminable', '果てしなく続く、際限のない', '/ɪnˈtɜːrmɪnəbl/', 'インターミナブル',
  'The interminable bureaucratic process frustrated applicants who had been waiting for months.',
  '果てしなく続く官僚的手続きは何か月も待っていた申請者たちを苛立たせた。',
  'What seemed like an interminable silence fell over the courtroom before the verdict was announced.',
  '判決が発表される前に、際限のないように思える沈黙が法廷に降りた。'),
(1344, 'loophole', '(法律・契約などの)抜け穴', '/ˈluːphoʊl/', 'ループホール',
  'Wealthy corporations exploit tax loopholes to minimize their financial obligations to the state.',
  '裕福な企業は国に対する財政的義務を最小限にするために税の抜け穴を利用している。',
  'The new legislation was drafted specifically to close the loophole that had allowed illegal dumping.',
  '新しい法律は不法投棄を可能にしていた抜け穴を塞ぐために特別に起草された。'),
(1346, 'synthesize', '~を総合する;~を合成する', '/ˈsɪnθəsaɪz/', 'シンセサイズ',
  'The researcher was able to synthesize findings from multiple disciplines into a cohesive theoretical framework.',
  'その研究者は複数の分野からの知見を一貫した理論的枠組みに総合することができた。',
  'Pharmaceutical companies invest billions in efforts to synthesize new compounds for treating rare diseases.',
  '製薬会社は希少疾患を治療するための新しい化合物を合成する取り組みに数十億ドルを投資している。'),
(1347, 'din', '(絶え間ない)騒音', '/dɪn/', 'ディン',
  'The din of construction machinery outside the office made it nearly impossible to concentrate.',
  'オフィスの外の建設機械の騒音が集中することをほぼ不可能にした。',
  'Above the din of the crowded marketplace, the vendor''s voice could barely be heard.',
  '混雑した市場の騒音の上では、露天商の声はほとんど聞こえなかった。'),
(1348, 'bureaucrat', '官僚;官僚主義的な人', '/ˈbjʊrəkræt/', 'ビューロクラット',
  'The reform initiative was stalled by bureaucrats who resisted any changes to the existing system.',
  '改革の取り組みは既存の制度への変更に抵抗する官僚たちによって停滞させられた。',
  'Citizens often express frustration with bureaucrats who prioritize procedure over practical outcomes.',
  '市民はしばしば実際の結果よりも手続きを優先する官僚主義的な人々に対して不満を表明する。'),
(1349, 'pacify', '(怒りなど)を和らげる、静める', '/ˈpæsɪfaɪ/', 'パシファイ',
  'The government deployed additional security forces in an attempt to pacify the restive province.',
  '政府は不安定な州を静めるために追加の治安部隊を配備した。',
  'The mother struggled to pacify her crying infant during the long transatlantic flight.',
  '母親は長い大西洋横断飛行の間、泣いている乳児をなだめるのに苦労した。'),
(1350, 'pounce', '(獲物などに)飛びかかる;(機会などに)飛びつく', '/paʊns/', 'パウンス',
  'The opposition party was quick to pounce on the minister''s controversial remark during the press conference.',
  '野党は記者会見での大臣の物議を醸す発言にすぐさま飛びついた。',
  'The cat crouched silently in the grass, waiting for the perfect moment to pounce on its unsuspecting prey.',
  '猫は草むらに静かにしゃがみ、油断している獲物に飛びかかる完璧な瞬間を待っていた。');
