-- words テーブル INSERT文 (No.1351 ~ No.1400)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1351, 'malice', '悪意、敵意', '/ˈmælɪs/', 'マリス',
  'The prosecutor argued that the defendant had acted with clear malice toward the victim.',
  '検察官は被告が被害者に対して明確な悪意を持って行動したと主張した。',
  'There was no malice in her remarks; she was simply stating the facts as she understood them.',
  '彼女の発言に悪意はなかった。彼女は自分が理解している事実をただ述べていたにすぎない。'),
(1352, 'bluntly', '無遠慮に、単刀直入に', '/ˈblʌntli/', 'ブラントリー',
  'The chairman bluntly told the shareholders that the company was on the verge of bankruptcy.',
  '会長は株主に対して会社が破産寸前であると単刀直入に告げた。',
  'She bluntly refused the offer, stating that the terms were entirely unacceptable.',
  '彼女は条件がまったく受け入れられないと述べ、無遠慮にその申し出を拒否した。'),
(1353, 'squash', '(人・もの)を押しつぶす', '/skwɑːʃ/', 'スクウォッシュ',
  'The government moved swiftly to squash the rebellion before it could gain momentum.',
  '政府は反乱が勢いを増す前に鎮圧するため迅速に動いた。',
  'The heavy machinery accidentally squashed several crates of imported goods at the warehouse.',
  '重機が倉庫で輸入品の箱数個を誤って押しつぶしてしまった。'),
(1354, 'mishap', '(ちょっとした)災難、不運', '/ˈmɪshæp/', 'ミスハップ',
  'The expedition proceeded without mishap despite the treacherous mountain terrain.',
  '危険な山岳地形にもかかわらず、探検は何の災難もなく進行した。',
  'A minor mishap during the rehearsal forced the director to postpone the opening night.',
  'リハーサル中のちょっとした災難により、演出家は初日の公演を延期せざるを得なかった。'),
(1355, 'sparse', 'まばらな、希薄な', '/spɑːrs/', 'スパース',
  'The region''s sparse population made it difficult to justify building new infrastructure.',
  'その地域のまばらな人口は新たなインフラ建設を正当化することを困難にした。',
  'Information about the incident remains sparse, leaving investigators with few leads to follow.',
  'その事件に関する情報は依然として希薄であり、捜査官にはたどるべき手がかりがほとんどない。'),
(1356, 'fabricate', '(話・情報など)をでっち上げる、捏造する;~を製作する、組み立てる', '/ˈfæbrɪkeɪt/', 'ファブリケイト',
  'The journalist was dismissed for fabricating quotes attributed to a prominent politician.',
  'その記者は著名な政治家の発言を捏造したとして解雇された。',
  'The components were fabricated in a specialized facility and then assembled on site.',
  '部品は専門施設で製作され、その後現場で組み立てられた。'),
(1358, 'recalcitrant', '(人・態度などが)反抗的な、強情な', '/rɪˈkælsɪtrənt/', 'リカルシトラント',
  'The recalcitrant employee repeatedly refused to comply with the new workplace regulations.',
  'その反抗的な従業員は新しい職場規則に繰り返し従うことを拒否した。',
  'Diplomats struggled to bring the recalcitrant nation to the negotiating table.',
  '外交官たちはその強情な国を交渉の場に引き出すのに苦労した。'),
(1359, 'sabotage', '(敵の兵器・設備など)を破壊する;(故意に)(他人の計画)を妨害する;破壊工作', '/ˈsæbətɑːʒ/', 'サボタージュ',
  'Investigators concluded that the factory explosion was an act of deliberate sabotage.',
  '調査官は工場爆発が意図的な破壊工作であったと結論づけた。',
  'A disgruntled former employee attempted to sabotage the company''s product launch.',
  '不満を持つ元従業員が会社の製品発売を妨害しようとした。'),
(1360, 'contemplate', '~を熟考する', '/ˈkɑːntəmpleɪt/', 'コンテンプレイト',
  'The board of directors is contemplating a major restructuring of the organization.',
  '取締役会は組織の大規模な再編を熟考している。',
  'She sat by the window, contemplating the implications of her decision to resign.',
  '彼女は窓辺に座り、辞職するという決断の含意を熟考していた。'),
(1361, 'obstruct', '(進行・視界など)を妨げる', '/əbˈstrʌkt/', 'オブストラクト',
  'A fallen tree obstructed the main highway, causing a massive traffic jam.',
  '倒木が主要幹線道路を塞ぎ、大規模な交通渋滞を引き起こした。',
  'The senator was charged with attempting to obstruct the congressional investigation.',
  'その上院議員は議会調査を妨害しようとした罪で起訴された。'),
(1362, 'shoddy', '粗悪な、手抜きの', '/ˈʃɑːdi/', 'ショディ',
  'The contractor was sued for delivering shoddy workmanship that compromised the building''s safety.',
  'その請負業者は建物の安全性を損なう粗悪な施工を行ったとして訴えられた。',
  'Consumers have the right to demand refunds for shoddy merchandise that fails to meet standards.',
  '消費者は基準を満たさない粗悪な商品に対して返金を要求する権利がある。'),
(1363, 'leeway', '自由、裁量', '/ˈliːweɪ/', 'リーウェイ',
  'The new policy gives managers considerable leeway in determining how to allocate resources.',
  '新しい方針は管理職に資源配分の方法を決定する上でかなりの裁量を与えている。',
  'There is little leeway for error when performing delicate surgical procedures.',
  '繊細な外科手術を行う際にはミスの許容範囲はほとんどない。'),
(1364, 'leverage', '影響力、効力;てこの力', '/ˈlevərɪdʒ/', 'レヴァリッジ',
  'The union used the threat of a strike as leverage to negotiate better working conditions.',
  '労働組合はストライキの脅威をより良い労働条件を交渉するための影響力として利用した。',
  'Small nations often lack the economic leverage needed to influence international trade agreements.',
  '小国は国際貿易協定に影響を与えるために必要な経済的効力を欠いていることが多い。'),
(1365, 'whine', '泣き言を言う、不平を言う', '/waɪn/', 'ワイン',
  'Instead of whining about the unfair treatment, she took legal action against the company.',
  '不当な扱いについて泣き言を言う代わりに、彼女はその会社に対して法的措置を取った。',
  'The opposition party continued to whine about the election results without producing any evidence of fraud.',
  '野党は不正の証拠を何ら提示せずに選挙結果について不平を言い続けた。'),
(1366, 'repository', '収納庫、保管場所', '/rɪˈpɑːzɪtɔːri/', 'リポジトリー',
  'The national archives serve as a repository for historically significant government documents.',
  '国立公文書館は歴史的に重要な政府文書の保管場所として機能している。',
  'The university library has become a repository of rare manuscripts from the medieval period.',
  'その大学図書館は中世の希少な写本の収蔵庫となっている。'),
(1367, 'impoverish', '~を貧乏にする;(資源・土地など)を貧弱にする', '/ɪmˈpɑːvərɪʃ/', 'インポヴァリッシュ',
  'Decades of civil war have impoverished the nation, leaving millions without basic necessities.',
  '数十年にわたる内戦が国を貧困に陥れ、何百万もの人々が基本的な必需品を欠く状態にした。',
  'Intensive monoculture farming can impoverish the soil, depleting it of essential nutrients.',
  '集約的な単一栽培農業は土壌を貧弱にし、必須栄養素を枯渇させることがある。'),
(1368, 'outcast', '(社会から)追放された人、のけ者', '/ˈaʊtkæst/', 'アウトキャスト',
  'After the scandal, he became a social outcast, shunned by former colleagues and friends.',
  'そのスキャンダルの後、彼は社会ののけ者となり、かつての同僚や友人から避けられた。',
  'The novel portrays the struggles of outcasts who are marginalized by a rigid class system.',
  'その小説は厳格な階級制度によって疎外されたのけ者たちの苦闘を描いている。'),
(1370, 'efface', '(記憶・痕跡・文字など)を取り除く、消し去る', '/ɪˈfeɪs/', 'イフェイス',
  'Time had effaced the inscriptions on the ancient tombstone, making them nearly illegible.',
  '時の経過が古い墓石の碑文を消し去り、ほとんど判読不能にしていた。',
  'No amount of propaganda could efface the memory of the atrocities committed during the war.',
  'いかなる量のプロパガンダも戦争中に犯された残虐行為の記憶を消し去ることはできなかった。'),
(1371, 'vicarious', '(他人の経験を)自分のことのように感じる;代理の', '/vaɪˈkeriəs/', 'ヴァイケアリアス',
  'Many readers derive vicarious pleasure from the adventures described in travel literature.',
  '多くの読者は旅行文学に描かれた冒険から自分のことのような喜びを得ている。',
  'Parents often experience vicarious satisfaction through their children''s academic achievements.',
  '親はしばしば子供の学業成績を通じて代理的な満足感を経験する。'),
(1372, 'paragon', '模範、手本', '/ˈpærəɡɑːn/', 'パラゴン',
  'The philanthropist was widely regarded as a paragon of generosity and civic responsibility.',
  'その慈善家は寛大さと市民的責任の模範として広く認められていた。',
  'The institution has long been held up as a paragon of academic excellence.',
  'その機関は長い間、学問的卓越性の手本として掲げられてきた。'),
(1373, 'paternity', '父であること、父性', '/pəˈtɜːrnɪti/', 'パターニティ',
  'The court ordered a DNA test to establish the paternity of the child.',
  '裁判所はその子供の父親であることを確定するためにDNA検査を命じた。',
  'Several countries have extended paternity leave to encourage fathers to participate in childcare.',
  '父親が育児に参加することを奨励するため、いくつかの国は父親の育児休暇を延長した。'),
(1374, 'purported', '(~と)称されている', '/pərˈpɔːrtɪd/', 'パーポーティド',
  'The purported benefits of the supplement have not been substantiated by clinical research.',
  'そのサプリメントの称されている効果は臨床研究によって実証されていない。',
  'The document, purported to be a royal decree, turned out to be an elaborate forgery.',
  '王令と称されていたその文書は精巧な偽造であることが判明した。'),
(1375, 'impetus', '刺激、推進力', '/ˈɪmpɪtəs/', 'インピタス',
  'The economic crisis provided the impetus for sweeping reforms in the financial sector.',
  '経済危機は金融部門における抜本的改革の推進力となった。',
  'The discovery of a new energy source gave fresh impetus to the country''s industrialization efforts.',
  '新たなエネルギー源の発見が国の工業化の取り組みに新たな刺激を与えた。'),
(1376, 'pledge', '~(すること)を誓う;誓約、公約', '/pledʒ/', 'プレッジ',
  'The president pledged to reduce carbon emissions by fifty percent within the next decade.',
  '大統領は今後10年以内に炭素排出量を50パーセント削減することを誓った。',
  'Several wealthy donors made a pledge to contribute generously to the disaster relief fund.',
  '数人の裕福な寄付者が災害救援基金に惜しみなく貢献するという誓約をした。'),
(1377, 'lineage', '家系、系統', '/ˈlɪniɪdʒ/', 'リニエッジ',
  'The royal family traces its lineage back to the medieval era.',
  '王室はその家系を中世の時代まで遡ることができる。',
  'Genetic research has enabled scientists to trace the lineage of various species with remarkable precision.',
  '遺伝子研究により科学者はさまざまな種の系統を驚くべき精度でたどることが可能になった。'),
(1378, 'denomination', '(貨幣の)単位;宗派、教派', '/dɪˌnɑːmɪˈneɪʃən/', 'デノミネイション',
  'The central bank issued banknotes in several new denominations to facilitate daily transactions.',
  '中央銀行は日常の取引を円滑にするためにいくつかの新しい単位の紙幣を発行した。',
  'Representatives from various Christian denominations gathered for an ecumenical conference.',
  'さまざまなキリスト教の宗派の代表者がエキュメニカル会議に集まった。'),
(1379, 'crest', '頂上、尾根;波頭', '/krest/', 'クレスト',
  'The hikers paused at the crest of the hill to admire the panoramic view of the valley below.',
  'ハイカーたちは丘の頂上で立ち止まり、眼下の谷の全景を眺めた。',
  'The surfer waited patiently for the wave to reach its crest before riding it toward the shore.',
  'サーファーは波が波頭に達するのを辛抱強く待ってから岸に向かって乗った。'),
(1380, 'constrain', '(人)に制約する;(人・もの)に強いる', '/kənˈstreɪn/', 'コンストレイン',
  'Budgetary limitations constrain the government''s ability to invest in public infrastructure.',
  '予算上の制約が公共インフラに投資する政府の能力を制約している。',
  'The artist felt constrained by the traditional conventions of the genre and sought a new form of expression.',
  'その芸術家はジャンルの伝統的な慣習に制約されていると感じ、新しい表現形式を追求した。'),
(1382, 'semblance', 'うわべ、外見;類似', '/ˈsembləns/', 'センブランス',
  'Despite the turmoil, the government tried to maintain a semblance of order in the capital.',
  '混乱にもかかわらず、政府は首都で秩序のうわべを維持しようとした。',
  'The ceasefire agreement restored at least a semblance of normalcy to the war-torn region.',
  '停戦協定は戦火に見舞われた地域に少なくとも平常のうわべを回復させた。'),
(1383, 'indelible', '消すことのできない', '/ɪnˈdelɪbl/', 'インデリブル',
  'The humanitarian crisis left an indelible mark on the collective consciousness of the nation.',
  '人道的危機は国の集合的意識に消すことのできない痕跡を残した。',
  'Her courageous speech made an indelible impression on everyone who attended the conference.',
  '彼女の勇気ある演説は会議に出席した全員に消すことのできない印象を与えた。'),
(1384, 'mystique', '神秘的な雰囲気', '/mɪˈstiːk/', 'ミスティーク',
  'The ancient temple retains an air of mystique that continues to attract pilgrims from around the world.',
  'その古代寺院は世界中から巡礼者を引きつけ続ける神秘的な雰囲気を保っている。',
  'The artist cultivated a certain mystique by rarely appearing in public or granting interviews.',
  'その芸術家はめったに公の場に姿を見せずインタビューにも応じないことで、ある種の神秘的な雰囲気を醸し出していた。'),
(1385, 'clumsy', '不器用な、ぎこちない;無様な、不格好な', '/ˈklʌmzi/', 'クラムジー',
  'The diplomat''s clumsy handling of the negotiations only aggravated the existing tensions.',
  'その外交官のぎこちない交渉の進め方は既存の緊張を悪化させるだけだった。',
  'His clumsy attempt to apologize was met with skepticism by the offended party.',
  '彼の不格好な謝罪の試みは気分を害した側から懐疑的に受け止められた。'),
(1386, 'bountiful', '豊富な;(人が)物惜しみしない、気前のよい', '/ˈbaʊntɪfəl/', 'バウンティフル',
  'The region is blessed with bountiful natural resources, including oil, gas, and minerals.',
  'その地域は石油、天然ガス、鉱物を含む豊富な天然資源に恵まれている。',
  'The bountiful harvest this year alleviated concerns about a potential food shortage.',
  '今年の豊富な収穫は潜在的な食糧不足に対する懸念を和らげた。'),
(1387, 'sanctuary', '鳥獣保護区域', '/ˈsæŋktʃueri/', 'サンクチュアリ',
  'The government designated the wetland as a sanctuary for endangered migratory birds.',
  '政府はその湿地を絶滅危惧種の渡り鳥の保護区域に指定した。',
  'The wildlife sanctuary provides a safe haven for animals rescued from illegal trafficking.',
  'その野生動物保護区域は違法取引から救出された動物に安全な避難場所を提供している。'),
(1388, 'germinate', '(種が)発芽する', '/ˈdʒɜːrmɪneɪt/', 'ジャーミネイト',
  'The seeds began to germinate after several days of consistent warmth and moisture.',
  '数日間の安定した暖かさと湿気の後、種子は発芽し始めた。',
  'An innovative idea germinated in her mind during the conference and later became a groundbreaking project.',
  '会議中に革新的なアイデアが彼女の心の中で芽生え、後に画期的なプロジェクトとなった。'),
(1389, 'precipitous', '非常に険しい、急峻な', '/prɪˈsɪpɪtəs/', 'プリシピタス',
  'The precipitous cliffs along the coastline made the area inaccessible by land.',
  '海岸線に沿った急峻な崖がその地域を陸路では近づけないものにしていた。',
  'The company experienced a precipitous decline in share prices following the accounting scandal.',
  'その会社は会計スキャンダルの後、株価の急激な下落を経験した。'),
(1390, 'blurt', '~を出し抜けに言う、うっかり口にする', '/blɜːrt/', 'ブラート',
  'He accidentally blurted out the confidential information during the press conference.',
  '彼は記者会見中にうっかり機密情報を口にしてしまった。',
  'She blurted out her resignation in a moment of frustration, a decision she later regretted.',
  '彼女は苛立ちの瞬間に出し抜けに辞職を口にしたが、後にその決断を後悔した。'),
(1391, 'tumble', '転ぶ、倒れる;転倒', '/ˈtʌmbl/', 'タンブル',
  'Stock prices tumbled sharply after the central bank announced an unexpected interest rate hike.',
  '中央銀行が予想外の利上げを発表した後、株価は急落した。',
  'The child took a tumble on the playground but quickly got back up and resumed playing.',
  'その子供は遊び場で転倒したが、すぐに立ち上がって遊びを再開した。'),
(1392, 'outage', '(電力・水道などの)供給停止', '/ˈaʊtɪdʒ/', 'アウティッジ',
  'The widespread power outage left millions of residents without electricity for over 48 hours.',
  '広範な停電により何百万もの住民が48時間以上にわたって電気のない状態に置かれた。',
  'The internet outage disrupted financial markets and caused significant economic losses.',
  'インターネットの供給停止は金融市場を混乱させ、多大な経済的損失を引き起こした。'),
(1394, 'belatedly', '遅れて、遅ればせながら', '/bɪˈleɪtɪdli/', 'ビレイティドリー',
  'The government belatedly acknowledged the severity of the crisis after weeks of public outcry.',
  '政府は数週間にわたる国民の抗議の後、遅ればせながら危機の深刻さを認めた。',
  'He belatedly realized that his hasty decision had cost the company a lucrative contract.',
  '彼は自分の性急な判断が会社に有利な契約を失わせたことに遅れて気づいた。'),
(1395, 'erode', '(関係・自信など)を損なう;(価値など)を下げる;(風雨などで)浸食される;~を浸食する', '/ɪˈroʊd/', 'イロウド',
  'Years of government inaction have eroded public confidence in the political establishment.',
  '何年にもわたる政府の不作為が政治体制に対する国民の信頼を損なってきた。',
  'Coastal erosion has gradually eroded the cliffs, threatening nearby residential areas.',
  '海岸浸食が徐々に崖を浸食し、近隣の住宅地を脅かしている。'),
(1396, 'incarnation', '人の姿を取ること、肉体化;(理念などの)具体化', '/ˌɪnkɑːrˈneɪʃən/', 'インカーネイション',
  'Many devotees believe that the deity appears on earth in various incarnations throughout history.',
  '多くの信者はその神が歴史を通じてさまざまな化身として地上に現れると信じている。',
  'The new museum is seen as the incarnation of the city''s commitment to preserving cultural heritage.',
  'その新しい博物館は文化遺産の保存に対する市の決意の具体化と見なされている。'),
(1397, 'vulgar', '(言動などが)下品な、卑猥な;(人・振る舞いなどが)粗野な', '/ˈvʌlɡər/', 'ヴァルガー',
  'The comedian was criticized for resorting to vulgar humor that offended many audience members.',
  'そのコメディアンは多くの観客を不快にさせる下品なユーモアに頼ったことで批判された。',
  'His vulgar display of wealth at the charity event was widely condemned as tasteless.',
  '慈善イベントでの彼の粗野な富の誇示は趣味が悪いと広く非難された。'),
(1398, 'arrogance', '傲慢、思い上がり', '/ˈærəɡəns/', 'アロガンス',
  'The CEO''s arrogance ultimately led to his downfall when the board voted to remove him.',
  'そのCEOの傲慢さは取締役会が彼の解任に投票した際に最終的に彼の没落につながった。',
  'Intellectual arrogance prevents scholars from acknowledging the validity of opposing viewpoints.',
  '知的な思い上がりは学者が対立する見解の妥当性を認めることを妨げる。'),
(1399, 'hitch', '(一時的な)支障、障害', '/hɪtʃ/', 'ヒッチ',
  'The satellite launch went off without a hitch, marking a milestone for the space agency.',
  '人工衛星の打ち上げは何の支障もなく行われ、宇宙機関にとっての画期的な出来事となった。',
  'A last-minute technical hitch delayed the broadcast of the live ceremony by thirty minutes.',
  '直前の技術的な障害により、生放送の式典の放映が30分遅れた。'),
(1400, 'tantalizing', 'じらすような、欲望をかき立てるような', '/ˈtæntəlaɪzɪŋ/', 'タンタライジング',
  'The research team released tantalizing preliminary findings that hinted at a breakthrough in cancer treatment.',
  '研究チームはがん治療における画期的な進展を示唆するじらすような予備的発見を公表した。',
  'The tantalizing aroma of freshly baked bread wafted through the narrow streets of the old quarter.',
  '焼きたてのパンの欲望をかき立てるような香りが旧市街の狭い通りに漂っていた。');
