-- words テーブル INSERT文 (No.1401 ~ No.1450)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1401, 'eavesdrop', '(会話などを)盗み聞きする、立ち聞きする', '/ˈiːvzdrɑːp/', 'イーヴズドロップ',
  'The journalist was caught trying to eavesdrop on the confidential meeting between the diplomats.',
  'そのジャーナリストは外交官同士の機密会議を盗み聞きしようとしているところを捕まった。',
  'She couldn''t help but eavesdrop on the couple''s heated argument at the adjacent table.',
  '彼女は隣のテーブルでのカップルの激しい口論を立ち聞きせずにはいられなかった。'),
(1402, 'gimmick', '(人目を引くための)からくり、仕掛け', '/ˈɡɪmɪk/', 'ギミック',
  'Critics dismissed the new product as nothing more than a marketing gimmick designed to boost sales.',
  '批評家たちはその新製品を売上を伸ばすためのマーケティングの仕掛けにすぎないと一蹴した。',
  'The politician''s promise of tax cuts was seen by many as an electoral gimmick.',
  'その政治家の減税の約束は多くの人に選挙用のからくりと見なされた。'),
(1403, 'demean', '~の品位を落とす', '/dɪˈmiːn/', 'ディミーン',
  'He refused to demean himself by responding to the baseless accusations.',
  '彼は根拠のない非難に応じて自分の品位を落とすことを拒んだ。',
  'The supervisor''s condescending tone served only to demean the hardworking employees.',
  '上司の見下すような口調は、勤勉な従業員たちの品位を落とすだけだった。'),
(1404, 'shrewd', '頭の切れる、やり手の、鋭い', '/ʃruːd/', 'シュルード',
  'The shrewd investor anticipated the market downturn and sold her stocks well in advance.',
  'その頭の切れる投資家は市場の低迷を予見し、かなり前に株を売却した。',
  'His shrewd negotiation tactics enabled the company to secure an exceptionally favorable contract.',
  '彼の鋭い交渉戦術のおかげで、会社は極めて有利な契約を確保できた。'),
(1406, 'anonymity', '匿名(性)', '/ˌænəˈnɪməti/', 'アノニミティ',
  'The whistleblower insisted on anonymity to protect herself from potential retaliation.',
  'その内部告発者は報復の可能性から身を守るために匿名性を求めた。',
  'The internet provides a degree of anonymity that emboldens people to express controversial opinions.',
  'インターネットはある程度の匿名性を提供し、人々に物議を醸す意見を表明する勇気を与える。'),
(1407, 'fetter', '~を拘束する、束縛する;[fetters]足かせ', '/ˈfetər/', 'フェター',
  'Excessive regulations can fetter innovation and hinder economic growth.',
  '過度な規制はイノベーションを束縛し、経済成長を妨げる可能性がある。',
  'The artist refused to let commercial pressures fetter her creative expression.',
  'そのアーティストは商業的な圧力に自分の創造的表現を拘束させることを拒んだ。'),
(1408, 'lackluster', 'さえない、活気のない', '/ˈlæklʌstər/', 'ラックラスター',
  'The team''s lackluster performance in the first half nearly cost them the championship.',
  'チームの前半のさえないパフォーマンスは、危うく優勝を逃すところだった。',
  'Despite months of preparation, the product launch was met with a lackluster response from consumers.',
  '何ヶ月もの準備にもかかわらず、製品の発売は消費者から活気のない反応を受けた。'),
(1409, 'implicit', '(同意・脅迫などが)暗黙の、それとなしの', '/ɪmˈplɪsɪt/', 'インプリシット',
  'There was an implicit understanding among the board members that the CEO would step down.',
  '取締役会のメンバーの間にはCEOが辞任するという暗黙の了解があった。',
  'The implicit threat in his words made everyone in the room uncomfortable.',
  '彼の言葉に含まれるそれとなしの脅迫が、部屋にいる全員を不快にさせた。'),
(1410, 'buffer', '(衝撃などを)和らげるもの[人]', '/ˈbʌfər/', 'バッファー',
  'The dense forest acts as a buffer against the harsh winds blowing in from the coast.',
  '密生した森は海岸から吹き込む厳しい風を和らげるものとして機能している。',
  'She served as a buffer between the two feuding departments, mediating their disputes.',
  '彼女は対立する二つの部署の間で衝撃を和らげる人として、紛争を仲裁した。'),
(1411, 'demeanor', '振る舞い、態度', '/dɪˈmiːnər/', 'ディミーナー',
  'Despite the crisis, the surgeon maintained a calm demeanor throughout the operation.',
  '危機的状況にもかかわらず、外科医は手術中ずっと冷静な態度を維持した。',
  'Her professional demeanor during the interview impressed the hiring committee.',
  '面接での彼女のプロフェッショナルな振る舞いは採用委員会に感銘を与えた。'),
(1412, 'cajole', '(人)をおだてる、丸め込む', '/kəˈdʒoʊl/', 'カジョール',
  'The salesman tried to cajole the reluctant customer into purchasing the expensive warranty.',
  'セールスマンは渋る顧客をおだてて高額な保証を購入させようとした。',
  'She managed to cajole her colleagues into volunteering for the weekend project.',
  '彼女は同僚たちを丸め込んで週末のプロジェクトにボランティアさせることに成功した。'),
(1413, 'disgruntled', '不満な、不機嫌な', '/dɪsˈɡrʌntld/', 'ディスグラントルド',
  'The disgruntled employees staged a walkout to protest the sudden pay cuts.',
  '不満な従業員たちは突然の賃金カットに抗議してストライキを行った。',
  'A disgruntled customer wrote a scathing review that went viral on social media.',
  '不機嫌な顧客がソーシャルメディアで拡散された辛辣なレビューを書いた。'),
(1414, 'urbane', '洗練された、落ち着いた物腰の', '/ɜːrˈbeɪn/', 'アーベイン',
  'The ambassador''s urbane manner charmed everyone at the diplomatic reception.',
  '大使の洗練された物腰は外交レセプションの全員を魅了した。',
  'He cultivated an urbane persona that concealed his humble rural upbringing.',
  '彼は素朴な田舎育ちを隠す落ち着いた物腰の人格を築き上げた。'),
(1415, 'emblazon', '(デザインなどで)~を飾る', '/ɪmˈbleɪzən/', 'エンブレイゾン',
  'The school crest was emblazoned across the front of the new gymnasium.',
  '校章が新しい体育館の正面に飾られていた。',
  'Protesters wore T-shirts emblazoned with slogans demanding political reform.',
  '抗議者たちは政治改革を求めるスローガンで飾られたTシャツを着ていた。'),
(1416, 'equivocate', 'あいまいなことを言う、言葉を濁す', '/ɪˈkwɪvəkeɪt/', 'イクウィヴォケイト',
  'The minister continued to equivocate when pressed about the government''s stance on the issue.',
  'その大臣は政府の問題に対する立場を問い詰められても言葉を濁し続けた。',
  'Rather than equivocate, the CEO gave a straightforward answer that surprised the journalists.',
  'あいまいなことを言うのではなく、CEOはジャーナリストたちを驚かせる率直な回答をした。'),
(1418, 'exponential', '急激な、加速度的な', '/ˌekspəˈnenʃəl/', 'エクスポネンシャル',
  'The exponential growth of the city''s population has strained its infrastructure beyond capacity.',
  'その都市の人口の急激な増加はインフラの許容量を超えて圧迫している。',
  'Advances in artificial intelligence have led to an exponential increase in data processing capabilities.',
  '人工知能の進歩はデータ処理能力の加速度的な向上をもたらした。'),
(1419, 'snare', '(動物を捕らえるための)わな;(人を陥れる)誘惑、わな', '/sneər/', 'スネア',
  'The poacher set a snare in the forest to capture endangered wildlife illegally.',
  '密猟者は絶滅危惧種の野生動物を違法に捕獲するために森にわなを仕掛けた。',
  'The fraudulent investment scheme was nothing but a snare to lure unsuspecting victims.',
  'その詐欺的な投資計画は無警戒な被害者を誘い込むわなにすぎなかった。'),
(1420, 'guzzle', '~をがぶがぶ飲む、がつがつ食う', '/ˈɡʌzl/', 'ガズル',
  'The SUV guzzles fuel at an alarming rate, making it impractical for daily commuting.',
  'そのSUVは驚くほどの速さで燃料をがぶがぶ消費し、毎日の通勤には非実用的だ。',
  'After the marathon, the exhausted runners guzzled water to replenish their dehydrated bodies.',
  'マラソンの後、疲れ果ったランナーたちは脱水した体を回復させるために水をがぶがぶ飲んだ。'),
(1421, 'translucent', '半透明の、透き通るような', '/trænzˈluːsnt/', 'トランスルーセント',
  'The translucent curtains allowed soft light to filter into the room while maintaining privacy.',
  '半透明のカーテンはプライバシーを保ちながら柔らかな光を部屋に取り込んだ。',
  'The jellyfish''s translucent body shimmered beautifully under the aquarium lights.',
  'クラゲの透き通るような体が水族館の照明の下で美しく輝いた。'),
(1422, 'jaded', 'うんざりした、飽き飽きした', '/ˈdʒeɪdɪd/', 'ジェイディド',
  'After decades in the industry, the jaded critic found it difficult to be impressed by new films.',
  '何十年もその業界にいた飽き飽きした批評家は、新しい映画に感動することが難しくなっていた。',
  'The jaded travelers sought out increasingly exotic destinations to rekindle their sense of adventure.',
  'うんざりした旅行者たちは冒険心を再燃させるために、ますます異国的な目的地を求めた。'),
(1423, 'obsequious', 'へつらう、卑屈な', '/əbˈsiːkwiəs/', 'オブシークウィアス',
  'The obsequious assistant agreed with every word the director said, never offering an independent opinion.',
  'へつらう助手は監督の言うことすべてに同意し、独自の意見を述べることはなかった。',
  'His obsequious behavior toward the wealthy patron was transparent and off-putting.',
  '裕福なパトロンに対する彼の卑屈な振る舞いは見え透いており、不快だった。'),
(1424, 'tedium', '退屈なこと', '/ˈtiːdiəm/', 'ティーディアム',
  'The sheer tedium of the repetitive assembly-line work drove many employees to resign.',
  '繰り返しの組立ラインの仕事のあまりの退屈さに、多くの従業員が辞職に追い込まれた。',
  'She relieved the tedium of the long flight by immersing herself in a captivating novel.',
  '彼女は魅力的な小説に没頭することで長時間のフライトの退屈さを紛らわせた。'),
(1425, 'impound', '(裁判所などが)(商品・文書など)を押収する、没収する', '/ɪmˈpaʊnd/', 'インパウンド',
  'The customs officers impounded the shipment after discovering undeclared contraband.',
  '税関職員は未申告の密輸品を発見した後、積荷を押収した。',
  'The city authorities impounded dozens of illegally parked vehicles during the crackdown.',
  '市当局は取り締まり中に何十台もの違法駐車車両を没収した。'),
(1426, 'genial', '(人・態度などが)愛想のよい、陽気な;(気候などが)温暖な', '/ˈdʒiːniəl/', 'ジーニアル',
  'The genial host made every guest feel welcome at the annual charity gala.',
  '愛想のよいホストは年次チャリティーガラですべてのゲストを歓迎されていると感じさせた。',
  'The region''s genial climate attracts retirees from all over the country.',
  'その地域の温暖な気候は全国から退職者を引きつけている。'),
(1427, 'embolden', '(人)を勇気づける、大胆にする', '/ɪmˈboʊldən/', 'エンボールデン',
  'The court''s favorable ruling emboldened other activists to file similar lawsuits.',
  '裁判所の好意的な判決は他の活動家たちに同様の訴訟を起こす勇気を与えた。',
  'Her success in the competition emboldened her to pursue a professional career in athletics.',
  '大会での成功が彼女に陸上競技のプロとしてのキャリアを追求する勇気を与えた。'),
(1428, 'efficacious', '(治療・方法などが)効き目のある、有効な', '/ˌefɪˈkeɪʃəs/', 'エフィケイシャス',
  'Clinical trials confirmed that the new vaccine is highly efficacious against the virus.',
  '臨床試験により、新しいワクチンがウイルスに対して非常に有効であることが確認された。',
  'The therapist recommended a more efficacious treatment plan after the initial approach failed.',
  '最初のアプローチが失敗した後、セラピストはより効き目のある治療計画を勧めた。'),
(1430, 'conceit', 'うぬぼれ、虚栄心', '/kənˈsiːt/', 'コンシート',
  'His insufferable conceit alienated even his closest allies within the organization.',
  '彼の我慢ならないうぬぼれは組織内の最も親しい味方さえも遠ざけた。',
  'The author''s conceit led her to dismiss all constructive criticism of her manuscript.',
  'その著者の虚栄心は原稿に対するすべての建設的な批判を退けさせた。'),
(1431, 'effigy', '(嫌われる人物の)像、人形', '/ˈefɪdʒi/', 'エフィジー',
  'Angry demonstrators burned an effigy of the dictator in the central square.',
  '怒ったデモ参加者たちは中央広場で独裁者の人形を燃やした。',
  'The museum displayed a wax effigy of the infamous historical figure.',
  '博物館はその悪名高い歴史上の人物の蝋人形を展示した。'),
(1432, 'throb', '(体の一部が)ずきずき痛む;(心臓が)どきどきする', '/θrɑːb/', 'スロブ',
  'His injured ankle continued to throb painfully despite the medication.',
  '薬を飲んだにもかかわらず、彼の負傷した足首はずきずきと痛み続けた。',
  'Her heart began to throb with excitement as the announcement of the winners drew near.',
  '受賞者の発表が近づくにつれ、彼女の心臓は興奮でどきどきし始めた。'),
(1433, 'progeny', '[集合的に](人・動物の)子孫', '/ˈprɑːdʒəni/', 'プロジェニー',
  'The wealthy industrialist left his vast fortune to his progeny in a meticulously drafted will.',
  'その裕福な実業家は綿密に作成された遺言書で膨大な財産を子孫に残した。',
  'Scientists studied the progeny of the genetically modified organisms to assess long-term effects.',
  '科学者たちは長期的な影響を評価するために遺伝子組み換え生物の子孫を研究した。'),
(1434, 'grind', '退屈な仕事;(穀物・コーヒー豆など)をひく', '/ɡraɪnd/', 'グラインド',
  'The daily grind of commuting two hours each way was taking a toll on her health.',
  '片道2時間の通勤という毎日の退屈な仕事が彼女の健康をむしばんでいた。',
  'The artisan would grind the coffee beans by hand to achieve the perfect consistency.',
  'その職人は完璧な粒度を得るためにコーヒー豆を手でひいていた。'),
(1435, 'deface', '(落書きなどで)~の外観を損なう', '/dɪˈfeɪs/', 'ディフェイス',
  'Vandals defaced the historic monument with spray paint, outraging the local community.',
  '破壊者たちがスプレー塗料で歴史的建造物の外観を損ない、地域社会を激怒させた。',
  'The library took measures to prevent anyone from defacing its rare book collection.',
  '図書館は貴重な蔵書の外観を損なわれないよう対策を講じた。'),
(1436, 'dissemble', '(本心などを)隠す、偽る', '/dɪˈsembl/', 'ディセンブル',
  'The spy had learned to dissemble his true intentions behind a facade of friendliness.',
  'そのスパイは友好的な外見の裏に本当の意図を隠すことを学んでいた。',
  'She could no longer dissemble her frustration with the committee''s indecisiveness.',
  '彼女は委員会の優柔不断さに対する不満をもはや偽ることができなかった。'),
(1437, 'append', '(書物などに)(注釈・補遺など)を追加する', '/əˈpend/', 'アペンド',
  'The editor asked the author to append a glossary of technical terms at the end of the book.',
  '編集者は著者に本の最後に専門用語の用語集を追加するよう求めた。',
  'Please append your signature to the document before submitting it to the registrar.',
  '登記官に提出する前に書類に署名を追加してください。'),
(1438, 'consummate', '非常に有能な、熟練した;~を完全なものにする', '/ˈkɑːnsəmət/', 'コンサメット',
  'As a consummate professional, she handled the crisis with remarkable composure.',
  '非常に有能なプロフェッショナルとして、彼女は危機を見事な冷静さで対処した。',
  'The treaty was finally consummated after years of painstaking negotiations.',
  'その条約は何年にもわたる苦心の交渉の末、ようやく完全なものとなった。'),
(1439, 'fervor', '熱情、熱烈', '/ˈfɜːrvər/', 'ファーヴァー',
  'The revolutionary leader spoke with such fervor that the crowd was instantly galvanized.',
  'その革命的指導者は非常な熱情をもって語り、群衆は瞬時に奮い立った。',
  'Religious fervor swept through the community, leading to a dramatic increase in church attendance.',
  '宗教的な熱烈さが地域社会に広がり、教会の出席者が劇的に増加した。'),
(1440, 'enamored', '興味を持って、魅惑されて', '/ɪˈnæmərd/', 'イナマード',
  'The critics were enamored of the young pianist''s extraordinary talent and stage presence.',
  '批評家たちは若いピアニストの並外れた才能と舞台での存在感に魅惑されていた。',
  'He became so enamored with the ancient culture that he decided to dedicate his career to its study.',
  '彼はその古代文化に非常に興味を持ち、キャリアをその研究に捧げることを決めた。'),
(1442, 'emancipate', '(社会・法律的な束縛から)(人)を解放する', '/ɪˈmænsɪpeɪt/', 'イマンシペイト',
  'The landmark legislation sought to emancipate millions of workers from exploitative labor practices.',
  'その画期的な法律は何百万人もの労働者を搾取的な労働慣行から解放することを目指した。',
  'Education has the power to emancipate individuals from the cycle of poverty.',
  '教育は個人を貧困の連鎖から解放する力を持っている。'),
(1443, 'sidestep', '(問題など)を回避する、はぐらかす', '/ˈsaɪdstep/', 'サイドステップ',
  'The politician skillfully sidestepped the reporter''s question about the corruption allegations.',
  'その政治家は汚職疑惑に関する記者の質問を巧みに回避した。',
  'The company attempted to sidestep environmental regulations by relocating its factory overseas.',
  'その会社は工場を海外に移転することで環境規制を回避しようとした。'),
(1444, 'deform', '~を変形させる、ゆがめる', '/dɪˈfɔːrm/', 'ディフォーム',
  'The intense heat deformed the metal framework of the building during the fire.',
  '火災中の激しい熱が建物の金属フレームを変形させた。',
  'Years of heavy use had deformed the wooden floorboards beyond repair.',
  '何年もの酷使が木製の床板を修復不可能なほどにゆがめていた。'),
(1445, 'rustic', '田舎(風)の、素朴な', '/ˈrʌstɪk/', 'ラスティック',
  'The couple chose a rustic farmhouse as their wedding venue for its charming simplicity.',
  'そのカップルは魅力的な素朴さからウェディング会場に田舎風の農家を選んだ。',
  'The restaurant''s rustic decor, with exposed wooden beams, appealed to tourists seeking authenticity.',
  'むき出しの木の梁がある素朴な装飾のレストランは、本物を求める観光客に人気があった。'),
(1446, 'woe', '[woes]問題、トラブル;苦痛、悲痛', '/woʊ/', 'ウォー',
  'The company''s financial woes deepened as consumer demand continued to decline.',
  '消費者需要が低下し続ける中、会社の財政上の問題は深刻化した。',
  'The flood victims shared tales of woe that moved the entire nation to action.',
  '洪水の被災者たちは国全体を行動に駆り立てる苦痛の物語を語った。'),
(1447, 'usher', '(人)を案内する、誘導する;(座席)案内人', '/ˈʌʃər/', 'アッシャー',
  'The discovery of penicillin helped usher in a new era of modern medicine.',
  'ペニシリンの発見は近代医学の新時代を導くのに貢献した。',
  'The usher politely guided the latecomers to their seats without disturbing the performance.',
  '案内人は公演を妨げることなく、遅れてきた人々を丁寧に席へ誘導した。'),
(1448, 'nuisance', '迷惑な人[もの]、厄介なこと', '/ˈnuːsns/', 'ニューサンス',
  'The persistent noise from the construction site became a serious nuisance to nearby residents.',
  '建設現場からの絶え間ない騒音は近隣住民にとって深刻な迷惑となった。',
  'Stray animals in the neighborhood were considered a nuisance by the local council.',
  '近隣の野良動物は地方議会から厄介なものと見なされていた。'),
(1449, 'avarice', '(金銭・利益に対する)貪欲、強欲', '/ˈævərɪs/', 'アヴァリス',
  'The CEO''s avarice led to a corporate scandal when his embezzlement was uncovered.',
  'CEOの貪欲さは横領が発覚した際に企業スキャンダルにつながった。',
  'Unbridled avarice among the ruling elite contributed to the downfall of the ancient empire.',
  '支配層の際限のない強欲が古代帝国の崩壊に寄与した。'),
(1450, 'pushover', 'だまされやすい人、かも;簡単なこと、朝飯前', '/ˈpʊʃoʊvər/', 'プッシュオーバー',
  'The opposing team underestimated us, assuming we would be a pushover in the finals.',
  '相手チームは決勝戦で我々が簡単に倒せるかもだと思い込み、過小評価した。',
  'Despite her gentle demeanor, the negotiator was no pushover when it came to closing deals.',
  '穏やかな態度にもかかわらず、その交渉者は取引をまとめる際にはだまされやすい人では決してなかった。');
