-- words テーブル INSERT文 (No.1451 ~ No.1500)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1451, 'dart', '(矢のように)動く、進む;(ダーツの)矢;突進', '/dɑːrt/', 'ダート',
  'The lizard darted across the sun-scorched pavement before disappearing into a crack in the wall.',
  'トカゲは日に焼けた舗道を矢のように横切り、壁の隙間に消えた。',
  'She darted a glance at her watch, anxious not to miss the departure of the last train.',
  '彼女は終電に乗り遅れまいと腕時計にさっと目をやった。'),
(1452, 'droop', '(だらりと)垂れる、下向きになる', '/druːp/', 'ドゥループ',
  'The flowers began to droop after being left without water for several days in the sweltering heat.',
  '花は猛暑の中、数日間水を与えられなかった後、だらりと垂れ始めた。',
  'His shoulders drooped visibly when he learned that his application had been rejected.',
  '応募が却下されたと知ったとき、彼の肩は目に見えて下向きになった。'),
(1454, 'blanch', '(人・顔などが)青ざめる;~を熱湯に通す、湯がく', '/blæntʃ/', 'ブランチ',
  'She blanched at the sight of the enormous medical bill that arrived in the mail.',
  '郵便で届いた莫大な医療費の請求書を見て彼女は青ざめた。',
  'The chef instructed his apprentice to blanch the vegetables briefly before adding them to the stir-fry.',
  'シェフは弟子に野菜を炒め物に加える前に軽く湯がくよう指示した。'),
(1455, 'sectarian', '宗派(間)の、分派(間)の', '/sekˈteəriən/', 'セクテリアン',
  'The peace accord was designed to put an end to decades of sectarian violence in the region.',
  'その和平協定はその地域における数十年にわたる宗派間の暴力に終止符を打つために策定された。',
  'Sectarian divisions within the political party threatened to undermine its electoral prospects.',
  '政党内の分派間の対立が選挙の見通しを損なう恐れがあった。'),
(1456, 'levitate', '(魔術などの力で)空中に浮く', '/ˈlevɪteɪt/', 'レヴィテイト',
  'The magician appeared to levitate above the stage, leaving the audience in stunned silence.',
  'その魔術師はステージの上空に浮いているように見え、観客を驚愕の沈黙に陥れた。',
  'In the dream, she felt herself levitate effortlessly toward the clouds.',
  '夢の中で、彼女は力を入れずに雲に向かって空中に浮く感覚を味わった。'),
(1457, 'rapture', '歓喜、有頂天', '/ˈræptʃər/', 'ラプチャー',
  'The audience listened in rapture as the virtuoso performed the final movement of the concerto.',
  '巨匠が協奏曲の最終楽章を演奏する間、聴衆は歓喜のうちに聞き入った。',
  'The children gazed at the fireworks display with expressions of pure rapture.',
  '子どもたちは純粋な有頂天の表情で花火大会を見つめた。'),
(1458, 'impermeable', '不浸透性の', '/ɪmˈpɜːrmiəbl/', 'インパーミアブル',
  'The geologists discovered an impermeable layer of rock that prevented groundwater from seeping further.',
  '地質学者たちは地下水がさらに浸透するのを防ぐ不浸透性の岩盤層を発見した。',
  'Workers wore impermeable suits to protect themselves from hazardous chemical spills.',
  '作業員たちは危険な化学物質の漏出から身を守るために不浸透性のスーツを着用した。'),
(1459, 'ascension', '上昇、上がること、昇進', '/əˈsenʃən/', 'アセンション',
  'Her rapid ascension to the position of CEO was attributed to her exceptional leadership skills.',
  '彼女のCEOへの急速な昇進は、卓越したリーダーシップ能力のおかげとされた。',
  'The mountaineers documented every stage of their ascension to the summit of the peak.',
  '登山家たちは山頂への上昇のすべての段階を記録した。'),
(1460, 'fumigate', '(部屋など)を薫蒸消毒する', '/ˈfjuːmɪɡeɪt/', 'フューミゲイト',
  'The health authorities ordered the building to be fumigated after a severe termite infestation was detected.',
  '深刻なシロアリの侵入が検出された後、保健当局はその建物を薫蒸消毒するよう命じた。',
  'Farmers fumigate their grain storage facilities annually to prevent pest contamination.',
  '農家は害虫汚染を防ぐために穀物貯蔵施設を毎年薫蒸消毒する。'),
(1461, 'lassitude', '無気力、倦怠', '/ˈlæsɪtjuːd/', 'ラシテュード',
  'A profound lassitude overcame the workforce after months of relentless overtime.',
  '何ヶ月にもわたる容赦ない残業の後、深い倦怠が労働者たちを襲った。',
  'The tropical heat induced a pervasive lassitude that made even simple tasks feel burdensome.',
  '熱帯の暑さは広範な無気力を引き起こし、単純な作業さえも重荷に感じさせた。'),
(1462, 'instantaneous', '(反応・行動などが)即座の、瞬間的な', '/ˌɪnstənˈteɪniəs/', 'インスタンテイニアス',
  'The chemical reaction was virtually instantaneous, producing a brilliant flash of light.',
  'その化学反応は事実上即座で、まばゆい閃光を生み出した。',
  'Modern communication technology enables the instantaneous transmission of information across the globe.',
  '現代の通信技術は世界中への情報の瞬間的な伝達を可能にしている。'),
(1463, 'escapade', 'とっぴな[羽目を外した]行動、悪ふざけ', '/ˈeskəpeɪd/', 'エスカペイド',
  'The tabloids were filled with stories of the celebrity''s latest escapade at a nightclub.',
  'タブロイド紙はその有名人のナイトクラブでの最新のとっぴな行動の話であふれていた。',
  'His youthful escapades were often recounted with laughter at family gatherings.',
  '彼の若い頃の悪ふざけは家族の集まりでよく笑い話として語られた。'),
(1464, 'entourage', '[集合的に]側近、取り巻き', '/ˈɑːntʊrɑːʒ/', 'アントゥラージ',
  'The president arrived at the summit accompanied by a large entourage of advisors and security personnel.',
  '大統領は顧問やセキュリティ担当者の大勢の側近を伴ってサミットに到着した。',
  'The rock star''s entourage occupied an entire floor of the luxury hotel.',
  'そのロックスターの取り巻きは高級ホテルのフロア全体を占拠した。'),
(1466, 'profane', '不敬な、冒涜的な;世俗的な', '/prəˈfeɪn/', 'プロフェイン',
  'The artist''s profane depiction of religious icons sparked outrage among conservative groups.',
  'そのアーティストの宗教的なイコンに対する冒涜的な描写は保守派の間で怒りを引き起こした。',
  'He was reprimanded for using profane language during the formal parliamentary session.',
  '彼は正式な議会の会期中に不敬な言葉遣いをしたことで叱責された。'),
(1467, 'malign', '(人)を中傷する、けなす;有害な、悪意のある', '/məˈlaɪn/', 'マライン',
  'The opposition party sought to malign the candidate''s reputation through a series of unfounded allegations.',
  '野党は一連の根拠のない主張を通じて候補者の評判を中傷しようとした。',
  'The malign influence of the corrupt official extended far beyond his own department.',
  'その腐敗した役人の有害な影響は彼自身の部署をはるかに超えて広がっていた。'),
(1468, 'personable', '(人が)感じのよい、魅力的な', '/ˈpɜːrsənəbl/', 'パーソナブル',
  'The personable receptionist made visitors feel instantly at ease upon entering the office.',
  '感じのよい受付係はオフィスに入った訪問者を即座にくつろがせた。',
  'His personable demeanor and sharp intellect made him an ideal candidate for the diplomatic post.',
  '彼の魅力的な態度と鋭い知性が外交官のポストの理想的な候補者にした。'),
(1469, 'makeshift', '間に合わせの、一時しのぎの', '/ˈmeɪkʃɪft/', 'メイクシフト',
  'The refugees constructed makeshift shelters from tarpaulins and wooden pallets.',
  '難民たちは防水シートと木製パレットで間に合わせの避難所を建てた。',
  'After the bridge collapsed, engineers erected a makeshift crossing to restore access to the village.',
  '橋が崩壊した後、技術者たちは村へのアクセスを回復するために一時しのぎの渡り場を設置した。'),
(1470, 'nauseate', '(人)に吐き気を催させる;(人)に嫌悪感を抱かせる', '/ˈnɔːzieɪt/', 'ノージエイト',
  'The putrid smell emanating from the abandoned factory nauseated everyone in the vicinity.',
  '廃工場から発せられる腐敗臭が近隣のすべての人に吐き気を催させた。',
  'The graphic footage of the environmental destruction nauseated viewers around the world.',
  '環境破壊の生々しい映像は世界中の視聴者に嫌悪感を抱かせた。'),
(1471, 'seditious', '反政府的な、扇動的な', '/sɪˈdɪʃəs/', 'セディシャス',
  'The government accused the journalist of publishing seditious material intended to incite public unrest.',
  '政府はそのジャーナリストを公衆の不安を煽ることを意図した反政府的な資料を出版したと非難した。',
  'Possession of seditious literature was grounds for immediate arrest under the authoritarian regime.',
  '扇動的な文書の所持は独裁政権下では即時逮捕の根拠となった。'),
(1472, 'desultory', 'とりとめのない、漫然とした', '/ˈdesəltɔːri/', 'デサルトリー',
  'The meeting devolved into a desultory discussion with no clear agenda or objectives.',
  '会議は明確な議題も目標もないとりとめのない議論に陥った。',
  'He made only desultory attempts to study for the exam, spending most of his time on social media.',
  '彼は試験勉強に漫然とした努力しかせず、ほとんどの時間をソーシャルメディアに費やした。'),
(1473, 'swab', '(薬などを)(傷口など)に綿棒で塗る、~を消毒する;綿棒、綿球', '/swɑːb/', 'スワブ',
  'The nurse carefully swabbed the wound with antiseptic before applying the bandage.',
  '看護師は包帯を巻く前に慎重に傷口を消毒液で拭いた。',
  'The forensic team used a swab to collect DNA evidence from the crime scene.',
  '鑑識チームは犯罪現場からDNA証拠を採取するために綿棒を使用した。'),
(1474, 'decadence', '(人・道徳などの)堕落、退廃', '/ˈdekədəns/', 'デカダンス',
  'Historians often cite moral decadence as one of the contributing factors to the fall of the Roman Empire.',
  '歴史家たちはしばしば道徳的な退廃をローマ帝国の滅亡の一因として挙げる。',
  'The film portrayed the decadence of the aristocracy in vivid and unflinching detail.',
  'その映画は貴族階級の堕落を鮮明かつ容赦のない描写で描いた。'),
(1475, 'luster', '輝かしい名声、栄光;光沢、つや', '/ˈlʌstər/', 'ラスター',
  'The scandal tarnished the luster of the institution that had once been held in the highest regard.',
  'そのスキャンダルは、かつて最も高く評価されていた機関の輝かしい名声を傷つけた。',
  'The jeweler polished the gemstone until it regained its original luster.',
  '宝石商はその宝石が元の光沢を取り戻すまで磨き上げた。'),
(1476, 'strenuous', '(運動などが)激しい;大変な努力を要する', '/ˈstrenjuəs/', 'ストレニュアス',
  'The doctor advised him to avoid strenuous physical activity until his knee had fully healed.',
  '医師は膝が完全に治るまで激しい運動を避けるよう彼に助言した。',
  'Despite strenuous opposition from local residents, the council approved the construction project.',
  '地元住民からの大変な反対にもかかわらず、議会は建設プロジェクトを承認した。'),
(1478, 'indiscriminate', '(行動などが)無差別の、見境なしの', '/ˌɪndɪˈskrɪmɪnət/', 'インディスクリミネット',
  'The indiscriminate bombing of civilian areas drew widespread international condemnation.',
  '民間地域への無差別爆撃は広範な国際的非難を招いた。',
  'The indiscriminate use of pesticides has caused irreparable damage to the local ecosystem.',
  '農薬の見境なしの使用は地域の生態系に取り返しのつかない損害を与えた。'),
(1479, 'clairvoyant', '透視力のある、千里眼の', '/kleərˈvɔɪənt/', 'クレアヴォイアント',
  'She claimed to possess clairvoyant abilities that allowed her to foresee catastrophic events.',
  '彼女は壊滅的な出来事を予見できる透視力があると主張した。',
  'The novel''s protagonist consults a clairvoyant figure who reveals a shocking truth about her ancestry.',
  '小説の主人公は彼女の祖先についての衝撃的な真実を明かす千里眼の人物に相談する。'),
(1480, 'reap', '(利益・報酬など)を享受する;(作物)を刈り取る', '/riːp/', 'リープ',
  'After years of dedicated research, the scientist finally reaped the rewards of her perseverance.',
  '長年の献身的な研究の後、その科学者はついに忍耐の報酬を享受した。',
  'Farmers in the region reap their wheat harvest in late summer when the fields turn golden.',
  'その地域の農家は畑が黄金色に変わる夏の終わりに小麦を刈り取る。'),
(1481, 'fortitude', '(精神的な)強さ、不屈の精神', '/ˈfɔːrtɪtjuːd/', 'フォーティテュード',
  'The survivors displayed remarkable fortitude in the face of the devastating natural disaster.',
  '壊滅的な自然災害に直面して、生存者たちは驚くべき不屈の精神を示した。',
  'It takes considerable fortitude to speak out against injustice when doing so puts one''s career at risk.',
  'そうすることでキャリアが危険にさらされるとき、不正に対して声を上げるにはかなりの精神的な強さが必要だ。'),
(1482, 'dubious', '不審な、怪しげな;疑わしく思う', '/ˈdjuːbiəs/', 'デュービアス',
  'The investors grew dubious when the company failed to provide transparent financial statements.',
  '会社が透明な財務諸表を提供できなかったとき、投資家たちは疑わしく思うようになった。',
  'The product''s dubious claims of miraculous health benefits attracted scrutiny from regulatory authorities.',
  'その製品の奇跡的な健康効果という怪しげな主張は規制当局からの精査を招いた。'),
(1483, 'romp', '(試合での)楽勝;跳ね回ること;跳ね回る', '/rɑːmp/', 'ロンプ',
  'The defending champions romped to victory with a commanding ten-point lead.',
  'ディフェンディングチャンピオンは10ポイントの大差で楽勝した。',
  'The children romped joyfully through the meadow, chasing butterflies and picking wildflowers.',
  '子どもたちは蝶を追いかけ野の花を摘みながら、牧草地を楽しそうに跳ね回った。'),
(1484, 'grouch', '不平屋、不機嫌な人;不平を言う', '/ɡraʊtʃ/', 'グラウチ',
  'The office grouch complained about everything, from the temperature to the quality of the coffee.',
  '職場の不平屋は気温からコーヒーの質まで、あらゆることに文句を言った。',
  'He tends to grouch about the state of modern politics whenever the topic arises at dinner.',
  '彼は夕食の場でその話題が出るたびに現代の政治の状況について不平を言う傾向がある。'),
(1485, 'abyss', 'どん底、危機的状況;(底なしの)深淵、深み', '/əˈbɪs/', 'アビス',
  'The country teetered on the abyss of economic collapse before international aid intervened.',
  'その国は国際援助が介入する前に経済崩壊のどん底に瀕していた。',
  'The philosopher gazed into the abyss of existential uncertainty and emerged with a profound new theory.',
  'その哲学者は実存的不確実性の深淵を見つめ、深遠な新理論を携えて戻ってきた。'),
(1486, 'jilt', '(恋人)を(突然)捨てる', '/dʒɪlt/', 'ジルト',
  'She was devastated when her fiancé jilted her just weeks before the wedding.',
  '婚約者が結婚式のわずか数週間前に突然彼女を捨てたとき、彼女は打ちのめされた。',
  'The novel tells the story of a jilted lover who seeks redemption through a cross-country journey.',
  'その小説は捨てられた恋人が国を横断する旅を通じて救済を求める物語を語る。'),
(1487, 'transpose', '~を入れ換える、置き換える', '/trænˈspoʊz/', 'トランスポーズ',
  'The typist accidentally transposed two digits in the account number, causing a significant payment error.',
  'タイピストが誤って口座番号の2桁を入れ換え、重大な支払いミスを引き起こした。',
  'The composer transposed the melody into a different key to better suit the soprano''s vocal range.',
  '作曲家はソプラノの声域により適するようにメロディーを別の調に置き換えた。'),
(1488, 'conundrum', '難題、難問', '/kəˈnʌndrəm/', 'コナンドラム',
  'The ethical conundrum of balancing privacy rights with national security continues to challenge lawmakers.',
  'プライバシーの権利と国家安全保障のバランスをとるという倫理的な難題は、立法者たちを悩ませ続けている。',
  'Scientists face the conundrum of how to dispose of nuclear waste safely for thousands of years.',
  '科学者たちは数千年にわたって核廃棄物を安全に処分する方法という難問に直面している。'),
(1490, 'snitch', '密告者;密告する', '/snɪtʃ/', 'スニッチ',
  'The gang threatened severe retaliation against anyone who dared to snitch to the authorities.',
  'そのギャングは当局に密告する者には厳しい報復をすると脅した。',
  'The informant was labeled a snitch by his former associates and forced into witness protection.',
  'その情報提供者は元仲間から密告者のレッテルを貼られ、証人保護プログラムに入ることを余儀なくされた。'),
(1491, 'emphatic', '(反応・意見などが)強調された;(人が)強く主張して', '/ɪmˈfætɪk/', 'エンファティック',
  'The prime minister was emphatic in her denial of any involvement in the corruption scandal.',
  '首相は汚職スキャンダルへのいかなる関与も強く否定した。',
  'The jury delivered an emphatic guilty verdict after only two hours of deliberation.',
  '陪審団はわずか2時間の審議の後、強調された有罪評決を下した。'),
(1492, 'snide', '(発言が)嫌みな、とげのある', '/snaɪd/', 'スナイド',
  'Her snide remarks about his presentation undermined his confidence in front of the entire team.',
  '彼のプレゼンテーションに対する彼女の嫌みな発言がチーム全員の前で彼の自信を損なわせた。',
  'The critic''s snide review of the exhibition was widely condemned as unprofessional.',
  'その批評家の展覧会に対するとげのあるレビューはプロフェッショナルらしくないと広く非難された。'),
(1493, 'widget', '小さな装置、機器', '/ˈwɪdʒɪt/', 'ウィジェット',
  'The engineer designed an innovative widget that significantly improved the machine''s energy efficiency.',
  'そのエンジニアは機械のエネルギー効率を大幅に向上させる革新的な小さな装置を設計した。',
  'The company''s latest widget integrates seamlessly with existing smart home systems.',
  'その会社の最新の機器は既存のスマートホームシステムとシームレスに統合される。'),
(1494, 'credulity', '信じやすい性質', '/krɪˈdjuːləti/', 'クレデュリティ',
  'The con artist exploited the elderly woman''s credulity to swindle her out of her life savings.',
  '詐欺師は高齢女性の信じやすい性質を利用して彼女の全財産をだまし取った。',
  'The outlandish conspiracy theory strained the credulity of even the most gullible listeners.',
  'その突飛な陰謀論は最も騙されやすい聞き手の信じやすい性質さえも試すものだった。'),
(1495, 'ephemeral', '一時的な、つかの間の;(動植物が)1日しか生きられない', '/ɪˈfemərəl/', 'イフェメラル',
  'The beauty of cherry blossoms is often celebrated precisely because it is so ephemeral.',
  '桜の美しさはまさにそれがつかの間であるがゆえに称えられることが多い。',
  'Social media fame is notoriously ephemeral, with trends disappearing as quickly as they emerge.',
  'ソーシャルメディアでの名声は一時的なことで有名であり、トレンドは現れるのと同じ速さで消えていく。'),
(1496, 'insubstantial', '非現実的な、架空の;(数量・金額などが)わずかな、不十分な', '/ˌɪnsəbˈstænʃəl/', 'インサブスタンシャル',
  'The prosecution''s case was built on insubstantial evidence that failed to convince the jury.',
  '検察の主張は陪審員を納得させることができない不十分な証拠に基づいていた。',
  'The ghostly figure appeared insubstantial, as though it might vanish at any moment.',
  'その幽霊のような姿は非現実的に見え、今にも消えてしまいそうだった。'),
(1497, 'beckon', '(人)に手招きする、合図する', '/ˈbekən/', 'ベコン',
  'The mysterious stranger beckoned to her from across the dimly lit corridor.',
  '見知らぬ人物が薄暗い廊下の向こうから彼女に手招きした。',
  'New opportunities beckoned as the company expanded its operations into emerging markets.',
  '会社が新興市場に事業を拡大するにつれ、新たな機会が手招きした。'),
(1498, 'sneer', '冷笑、あざけり;あざ笑う、冷笑する', '/snɪr/', 'スニア',
  'The aristocrat sneered at the commoner''s attempt to gain admission to the exclusive club.',
  'その貴族は庶民が名門クラブへの入会を試みるのをあざ笑った。',
  'His sneer of contempt was unmistakable as he dismissed the junior colleague''s proposal.',
  '後輩の提案を退ける際の彼の軽蔑の冷笑は紛れもないものだった。'),
(1499, 'tenuous', '(根拠などが)弱い;(関係などが)希薄な', '/ˈtenjuəs/', 'テニュアス',
  'The detective''s theory rested on a tenuous connection between two seemingly unrelated incidents.',
  '刑事の理論は一見無関係に見える二つの事件の間の弱いつながりに基づいていた。',
  'The ceasefire maintained only a tenuous peace, with both sides poised to resume hostilities.',
  '停戦は希薄な平和を維持しているにすぎず、双方が敵対行為の再開に備えていた。'),
(1500, 'scuff', '(ものの表面)にこすった跡をつける;こすれた跡、傷', '/skʌf/', 'スカフ',
  'He scuffed his brand-new leather shoes on the rough pavement during his morning commute.',
  '彼は朝の通勤中に粗い舗道で真新しい革靴にこすった跡をつけてしまった。',
  'The scuff marks on the gymnasium floor bore witness to years of vigorous athletic activity.',
  '体育館の床のこすれた跡は何年にもわたる活発な運動の証だった。');
