-- words テーブル INSERT文 (No.1501 ~ No.1550)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1502, 'dredge', '(川・湾など)を浚渫する、さらう', '/drɛdʒ/', 'ドレッジ',
  'The government allocated substantial funds to dredge the harbor and restore its navigability for commercial vessels.',
  '政府は港を浚渫し商業船舶の航行性を回復させるために多額の資金を割り当てた。',
  'Archaeologists dredged the riverbed in hopes of uncovering artifacts from the medieval settlement.',
  '考古学者たちは中世の集落の遺物を発掘することを期待して川底を浚渫した。'),
(1503, 'niggle', '(ささいなことに)くよくよする;(人)をいらいらさせる', '/ˈnɪɡl/', 'ニグル',
  'A nagging doubt continued to niggle at her long after the decision had been made.',
  '決定がなされた後もずっと、しつこい疑念が彼女をくよくよさせ続けた。',
  'Minor discrepancies in the financial report niggled the auditor throughout the review process.',
  '財務報告書の些細な矛盾が監査プロセスの間中、監査人をいらいらさせた。'),
(1504, 'bulge', '膨れる、膨らむ;膨らみ、出っ張り', '/bʌldʒ/', 'バルジ',
  'His pockets bulged with documents he had hastily gathered before fleeing the office.',
  '彼のポケットはオフィスから逃げる前に急いで集めた書類で膨らんでいた。',
  'The unusual bulge in the wall indicated structural damage caused by years of water seepage.',
  '壁の異常な出っ張りは長年の水の浸透による構造的損傷を示していた。'),
(1505, 'perverse', '(人・行い・喜びなどが)ひねくれた、屈折した', '/pərˈvɜːrs/', 'パーヴァース',
  'There is a perverse irony in the fact that the safety regulation itself led to more accidents.',
  '安全規制そのものがより多くの事故を引き起こしたという事実にはひねくれた皮肉がある。',
  'He took a perverse pleasure in pointing out the flaws in his colleagues'' proposals.',
  '彼は同僚の提案の欠点を指摘することに屈折した喜びを感じていた。'),
(1506, 'heretic', '異端者、異教徒', '/ˈhɛrətɪk/', 'ヘレティック',
  'During the Inquisition, anyone who questioned the established doctrine was branded a heretic.',
  '異端審問の時代、確立された教義に疑問を呈する者は誰でも異端者の烙印を押された。',
  'The scientist was treated as a heretic by the academic establishment for challenging prevailing theories.',
  'その科学者は通説に異議を唱えたことで学界から異端者として扱われた。'),
(1507, 'imperious', '傲慢な、横柄な', '/ɪmˈpɪriəs/', 'インピアリアス',
  'The imperious manager issued commands without ever soliciting input from the team members.',
  '横柄なマネージャーはチームメンバーから意見を求めることなく命令を出した。',
  'Her imperious tone alienated potential allies who might otherwise have supported her candidacy.',
  '彼女の傲慢な口調は、さもなければ彼女の立候補を支持していたかもしれない潜在的な味方を遠ざけた。'),
(1508, 'levy', '税、税金;(税など)を課する、徴収する', '/ˈlɛvi/', 'レヴィ',
  'The government decided to levy a new tax on carbon emissions to combat climate change.',
  '政府は気候変動に対抗するために炭素排出に新たな税を課すことを決定した。',
  'The unexpected levy imposed on imported goods sparked outrage among international trade partners.',
  '輸入品に課された予想外の税金は国際貿易パートナーの間に激しい怒りを引き起こした。'),
(1509, 'conflate', '(複数の情報・考えなど)をまとめる、合成する', '/kənˈfleɪt/', 'コンフレイト',
  'The media tends to conflate correlation with causation, misleading the public on scientific findings.',
  'メディアは相関関係と因果関係をまとめて扱いがちであり、科学的知見について一般市民を誤解させている。',
  'Critics accused the historian of conflating two distinct events into a single misleading narrative.',
  '批評家たちはその歴史家が二つの異なる出来事を一つの誤解を招く物語に合成したと非難した。'),
(1510, 'prerogative', '(役職上の)特権', '/prɪˈrɑːɡətɪv/', 'プリロガティヴ',
  'It is the chairperson''s prerogative to cast the deciding vote in the event of a tie.',
  '同数の場合に決定票を投じるのは議長の特権である。',
  'The prime minister exercised her prerogative to dissolve parliament and call for new elections.',
  '首相は議会を解散し新たな選挙を求める特権を行使した。'),
(1511, 'collation', '照合、対照', '/kəˈleɪʃən/', 'コレイション',
  'The meticulous collation of data from multiple sources ensured the accuracy of the final report.',
  '複数の情報源からのデータの綿密な照合が最終報告書の正確性を保証した。',
  'After the collation of the ballots, the election committee announced the preliminary results.',
  '投票用紙の照合の後、選挙委員会は暫定結果を発表した。'),
(1512, 'truancy', 'ずる休み、無断欠席', '/ˈtruːənsi/', 'トゥルーアンシー',
  'The school implemented a strict policy to combat the rising rates of truancy among students.',
  '学校は生徒の無断欠席の増加率に対処するため厳格な方針を実施した。',
  'Persistent truancy is often symptomatic of deeper issues such as bullying or family instability.',
  '常習的なずる休みは、いじめや家庭の不安定さなどのより深い問題の兆候であることが多い。'),
(1514, 'haggard', '(病気・心労・寝不足などで)やつれた', '/ˈhæɡərd/', 'ハガード',
  'After weeks of sleepless nights caring for her ailing mother, she looked visibly haggard.',
  '病気の母親を看病して何週間も眠れない夜を過ごした後、彼女は目に見えてやつれていた。',
  'The haggard faces of the refugees bore witness to the unimaginable hardships they had endured.',
  '難民たちのやつれた顔は、彼らが耐え忍んだ想像を絶する苦難を物語っていた。'),
(1515, 'malady', '病気;(組織・社会などの)病弊', '/ˈmælədi/', 'マラディ',
  'Corruption is a deep-rooted malady that continues to plague many developing nations.',
  '汚職は多くの発展途上国を悩ませ続ける根深い病弊である。',
  'The physician struggled to diagnose the mysterious malady that had afflicted the entire village.',
  '医師は村全体を苦しめた謎の病気の診断に苦労した。'),
(1516, 'indictment', '起訴、告訴;(制度・社会などの)欠陥を示すもの', '/ɪnˈdaɪtmənt/', 'インダイトメント',
  'The grand jury returned an indictment against the former executive on charges of fraud and embezzlement.',
  '大陪審は詐欺と横領の容疑で元幹部に対する起訴を決定した。',
  'The documentary served as a damning indictment of the nation''s crumbling healthcare system.',
  'そのドキュメンタリーは国の崩壊しつつある医療制度の欠陥を示すものとして機能した。'),
(1517, 'vociferous', '(人が)やかましい、(文句・要求などが)声高な', '/voʊˈsɪfərəs/', 'ヴォシフェラス',
  'Vociferous protests erupted outside the parliament building when the controversial bill was introduced.',
  '物議を醸す法案が提出された際、議会の建物の外でやかましい抗議が勃発した。',
  'The vociferous demands of the labor unions eventually compelled the corporation to renegotiate wages.',
  '労働組合の声高な要求はついに企業に賃金の再交渉を強いた。'),
(1518, 'infirmity', '虚弱、病弱', '/ɪnˈfɜːrməti/', 'インファーミティ',
  'Despite the infirmities of old age, the retired professor continued to publish groundbreaking research.',
  '老齢による虚弱にもかかわらず、その退職した教授は画期的な研究を発表し続けた。',
  'The charitable organization provides assistance to those suffering from physical infirmity.',
  'その慈善団体は身体的な病弱に苦しむ人々に支援を提供している。'),
(1519, 'mutinous', '反抗的な;反乱[暴動]に加わった', '/ˈmjuːtɪnəs/', 'ミューティナス',
  'The mutinous crew seized control of the vessel and imprisoned the captain in his quarters.',
  '反乱に加わった乗組員たちは船を掌握し、船長を船室に監禁した。',
  'A mutinous atmosphere pervaded the workforce after the abrupt announcement of mass layoffs.',
  '大量解雇の突然の発表の後、反抗的な雰囲気が従業員の間に広がった。'),
(1520, 'celibate', '(特に宗教上の理由により)独身主義の;禁欲主義の;独身[禁欲]主義者', '/ˈsɛlɪbət/', 'セリベット',
  'The monks in the monastery have chosen to remain celibate as part of their spiritual devotion.',
  '修道院の修道士たちは精神的な献身の一環として独身主義を貫くことを選んだ。',
  'The debate over whether clergy should be required to remain celibate continues to divide the church.',
  '聖職者が独身主義であることを求められるべきかどうかの議論は教会を分裂させ続けている。'),
(1521, 'taint', '(人・名声など)を傷つける;(水・空気など)を汚す、汚染する;汚点、不名誉', '/teɪnt/', 'テイント',
  'The scandal threatened to taint the reputation of the entire institution beyond repair.',
  'そのスキャンダルは機関全体の評判を修復不可能なほど傷つける恐れがあった。',
  'Industrial runoff had begun to taint the groundwater supply, prompting an urgent government inquiry.',
  '工業排水が地下水の供給を汚染し始め、政府の緊急調査を促した。'),
(1522, 'insignia', '(地位・所属などを示す)記章', '/ɪnˈsɪɡniə/', 'インシグニア',
  'The officer''s insignia on his uniform indicated that he held the rank of colonel.',
  '制服の記章は彼が大佐の階級であることを示していた。',
  'The royal insignia was embroidered on the curtains that adorned the throne room.',
  '王室の記章は玉座の間を飾るカーテンに刺繍されていた。'),
(1523, 'probationary', '試用の、見習い中の;保護観察中の', '/proʊˈbeɪʃənɛri/', 'プロベイショナリー',
  'During the probationary period, new employees are closely monitored to assess their suitability for the role.',
  '試用期間中、新入社員はその役割への適性を評価するために注意深く観察される。',
  'The probationary officer was required to report to his supervisor on a weekly basis.',
  '保護観察中の人物は毎週監督者に報告することを求められた。'),
(1524, 'denunciation', '(公然の)非難、弾劾;(罪の)摘発、告発', '/dɪˌnʌnsiˈeɪʃən/', 'デナンシエイション',
  'The senator''s public denunciation of the policy drew widespread media attention.',
  'その上院議員の政策に対する公然の非難は広くメディアの注目を集めた。',
  'Her denunciation of the corrupt officials led to a sweeping investigation by the authorities.',
  '彼女の腐敗した役人の告発は当局による徹底的な調査につながった。'),
(1526, 'lax', '(規律などが)ゆるい、甘い', '/læks/', 'ラックス',
  'The company''s lax enforcement of safety protocols was cited as a contributing factor in the accident.',
  '会社の安全規定の甘い執行が事故の一因として挙げられた。',
  'Critics argued that lax border controls facilitated the smuggling of contraband into the country.',
  '批評家たちは国境管理のゆるさが密輸品の国内への流入を容易にしたと主張した。'),
(1527, 'obnoxious', '非常に不快な、気に障る', '/əbˈnɑːkʃəs/', 'オブノクシャス',
  'The obnoxious behavior of the rowdy passengers disrupted the entire flight.',
  '騒がしい乗客の非常に不快な振る舞いがフライト全体を混乱させた。',
  'An obnoxious odor emanating from the factory prompted residents to file formal complaints.',
  '工場から発する気に障る悪臭が住民に正式な苦情を提出させた。'),
(1528, 'harbinger', '(変化の)前兆、前触れ', '/ˈhɑːrbɪndʒər/', 'ハービンジャー',
  'Many economists view the recent decline in consumer spending as a harbinger of an impending recession.',
  '多くの経済学者は最近の消費者支出の減少を差し迫った不況の前兆と見ている。',
  'The first robin of spring is traditionally regarded as a harbinger of warmer days to come.',
  '春の最初のコマドリは伝統的に暖かい日々の前触れと見なされている。'),
(1529, 'logistically', '業務遂行上', '/loʊˈdʒɪstɪkli/', 'ロジスティクリー',
  'Coordinating relief efforts across multiple disaster zones proved logistically challenging.',
  '複数の災害地域にわたる救援活動の調整は業務遂行上困難であることが判明した。',
  'The merger was financially advantageous but logistically complex to implement.',
  'その合併は財務的には有利だったが、業務遂行上実施するのは複雑だった。'),
(1530, 'exhilaration', '高揚感、興奮', '/ɪɡˌzɪləˈreɪʃən/', 'イグジラレイション',
  'The exhilaration of completing her first marathon was an experience she would never forget.',
  '初めてのマラソンを完走した高揚感は彼女が決して忘れない経験だった。',
  'A wave of exhilaration swept through the stadium as the home team scored the winning goal.',
  'ホームチームが決勝ゴールを決めると、興奮の波がスタジアムを駆け巡った。'),
(1531, 'rancid', '(油・油脂を含む食品が)悪臭のする', '/ˈrænsɪd/', 'ランシッド',
  'The butter had turned rancid after being left out of the refrigerator for several days.',
  'バターは冷蔵庫の外に数日間放置された後、悪臭のする状態になっていた。',
  'A rancid smell permeated the kitchen, indicating that the cooking oil had gone bad.',
  '悪臭のするにおいが台所に充満し、食用油が傷んだことを示していた。'),
(1532, 'contemptuous', '軽蔑した、ばかにした', '/kənˈtɛmptʃuəs/', 'コンテンプチュアス',
  'The defendant cast a contemptuous glance at the prosecutor during the cross-examination.',
  '被告は反対尋問中に検察官に軽蔑した視線を投げかけた。',
  'Her contemptuous dismissal of the proposal offended the colleagues who had worked tirelessly on it.',
  '彼女の提案に対するばかにした却下は、それに精力的に取り組んだ同僚たちを怒らせた。'),
(1533, 'peddle', '(商品)を売り歩く、行商する', '/ˈpɛdl/', 'ペドル',
  'Street vendors peddled their wares along the bustling market square from dawn until dusk.',
  '露天商たちは夜明けから日暮れまで賑やかな市場広場で商品を売り歩いた。',
  'The organization accused the tabloid of peddling misinformation to boost circulation.',
  'その組織はタブロイド紙が発行部数を伸ばすために誤情報を売り歩いていると非難した。'),
(1534, 'rueful', '悔やむような、申し訳なさそうな', '/ˈruːfəl/', 'ルーフル',
  'He gave a rueful smile as he recounted the foolish mistakes he had made in his youth.',
  '彼は若い頃に犯した愚かな過ちを語りながら、悔やむような微笑みを浮かべた。',
  'With a rueful expression, she admitted that she should have heeded her mentor''s advice.',
  '申し訳なさそうな表情で、彼女は師のアドバイスに耳を傾けるべきだったと認めた。'),
(1535, 'inoculate', '~に(予防)接種する', '/ɪˈnɑːkjəleɪt/', 'イノキュレイト',
  'The health authorities launched a campaign to inoculate the entire population against the emerging virus.',
  '保健当局は新興ウイルスに対して全国民に予防接種を行うキャンペーンを開始した。',
  'Children in rural areas were inoculated by mobile medical teams dispatched by the government.',
  '農村部の子どもたちは政府が派遣した移動医療チームによって予防接種を受けた。'),
(1536, 'gratuity', '心づけ、チップ', '/ɡrəˈtuːəti/', 'グラチュイティ',
  'In many countries, it is customary to leave a gratuity of fifteen to twenty percent at restaurants.',
  '多くの国では、レストランで15パーセントから20パーセントのチップを残すのが慣例である。',
  'The hotel concierge graciously accepted the gratuity for arranging last-minute theater tickets.',
  'ホテルのコンシェルジュは急な劇場のチケットの手配に対する心づけを丁重に受け取った。'),
(1538, 'tantrum', '(特に幼児の)かんしゃく、立腹', '/ˈtæntrəm/', 'タントラム',
  'The toddler threw a tantrum in the middle of the supermarket when denied a bag of sweets.',
  'その幼児はお菓子の袋を拒否されるとスーパーの真ん中でかんしゃくを起こした。',
  'The executive''s frequent tantrums during meetings created a toxic work environment.',
  'その幹部の会議中の頻繁な立腹が有害な職場環境を生み出した。'),
(1539, 'hallucinate', '(人が)幻覚を起こす', '/həˈluːsɪneɪt/', 'ハルーシネイト',
  'The patient began to hallucinate after being administered an excessive dose of the medication.',
  '患者は薬を過剰投与された後、幻覚を起こし始めた。',
  'Severe sleep deprivation can cause individuals to hallucinate and experience distorted perceptions of reality.',
  '深刻な睡眠不足は人に幻覚を起こさせ、現実の歪んだ認識を経験させることがある。'),
(1540, 'indemnity', '賠償(金)、補償(金)', '/ɪnˈdɛmnəti/', 'インデムニティ',
  'The insurance company agreed to pay full indemnity for the damages caused by the natural disaster.',
  '保険会社は自然災害によって引き起こされた損害に対して全額の補償金を支払うことに同意した。',
  'The defeated nation was forced to pay a crippling war indemnity under the terms of the treaty.',
  '敗戦国は条約の条件の下、壊滅的な戦争賠償金を支払うことを強いられた。'),
(1541, 'indolence', '怠惰、無精', '/ˈɪndələns/', 'インドレンス',
  'His chronic indolence prevented him from fulfilling his considerable academic potential.',
  '彼の慢性的な怠惰は相当な学問的潜在能力を発揮することを妨げた。',
  'The tropical climate was often blamed for fostering a culture of indolence among the colonists.',
  '熱帯の気候は植民者たちの間に怠惰の文化を育んだと非難されることが多かった。'),
(1542, 'underwrite', '(活動・事業など)の融資を引き受ける', '/ˌʌndərˈraɪt/', 'アンダーライト',
  'Several major banks agreed to underwrite the construction of the new international airport.',
  'いくつかの大手銀行が新しい国際空港の建設の融資を引き受けることに同意した。',
  'The philanthropic foundation underwrote the research initiative aimed at developing renewable energy sources.',
  'その慈善財団は再生可能エネルギー源の開発を目指す研究イニシアチブの融資を引き受けた。'),
(1543, 'virtuous', '徳の高い、有徳の;高潔な', '/ˈvɜːrtʃuəs/', 'ヴァーチュアス',
  'The community regarded the elderly volunteer as a virtuous individual who dedicated her life to serving others.',
  '地域社会はその高齢のボランティアを他者への奉仕に人生を捧げた徳の高い人物と見なしていた。',
  'Leading a virtuous life requires the discipline to resist temptation and uphold one''s principles.',
  '高潔な生活を送るには誘惑に抵抗し自分の信念を守る規律が必要である。'),
(1544, 'exult', '大喜びする、狂喜する', '/ɪɡˈzʌlt/', 'イグザルト',
  'The entire nation exulted when the team clinched the gold medal at the Olympic Games.',
  'チームがオリンピックで金メダルを獲得したとき、国全体が大喜びした。',
  'She could not help but exult upon receiving the news of her promotion to senior partner.',
  '彼女はシニアパートナーへの昇進の知らせを受けて狂喜せずにはいられなかった。'),
(1545, 'tumult', '(群衆などの)騒動、大騒ぎ', '/ˈtuːmʌlt/', 'テューマルト',
  'The announcement of the verdict caused a tumult in the courtroom that the judge struggled to contain.',
  '判決の発表は法廷で騒動を引き起こし、裁判官はそれを収めるのに苦労した。',
  'Amid the tumult of the political upheaval, ordinary citizens struggled to maintain their daily routines.',
  '政治的動乱の大騒ぎの中、一般市民は日常生活を維持するのに苦労した。'),
(1546, 'redeem', '(失敗・弱点など)を補う;(引換券など)を現金に換える', '/rɪˈdiːm/', 'リディーム',
  'The actor''s stellar performance in the final act redeemed an otherwise mediocre production.',
  'その俳優の最終幕での素晴らしい演技が、それ以外は平凡な作品を補った。',
  'Customers can redeem their accumulated loyalty points for discounts on future purchases.',
  '顧客は蓄積したポイントを今後の購入の割引に換えることができる。'),
(1547, 'consort', '(悪い人間と)付き合う;一致する、調和する', '/kənˈsɔːrt/', 'コンソート',
  'The prince was criticized by the press for consorting with individuals of dubious reputation.',
  'その王子は怪しげな評判の人物と付き合っているとマスコミに批判された。',
  'His extravagant lifestyle did not consort with the image of austerity he projected to the public.',
  '彼の贅沢な生活様式は一般に示していた質素なイメージと一致しなかった。'),
(1548, 'defer', '(決定・支払いなど)を延期する', '/dɪˈfɜːr/', 'ディファー',
  'The board voted to defer the decision on the merger until a more thorough analysis could be conducted.',
  '取締役会はより徹底的な分析が行われるまで合併に関する決定を延期することを決議した。',
  'Students may defer their enrollment for up to one academic year under exceptional circumstances.',
  '学生は例外的な状況の下、入学を最長1学年延期することができる。'),
(1550, 'condiment', '調味料、香辛料', '/ˈkɑːndɪmənt/', 'コンディメント',
  'The chef meticulously selected each condiment to complement the delicate flavors of the dish.',
  'シェフは料理の繊細な風味を引き立てるために各調味料を入念に選んだ。',
  'Mustard remains one of the most widely consumed condiments across European cuisine.',
  'マスタードはヨーロッパ料理で最も広く消費されている調味料の一つである。');
