-- words テーブル INSERT文 (No.1551 ~ No.1600)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1551, 'crux', '(問題・議論などの)核心、最重要点', '/krʌks/', 'クラックス',
  'The crux of the matter is whether the government can justify such a drastic policy shift.',
  'その問題の核心は、政府がそれほど大幅な政策転換を正当化できるかどうかだ。',
  'After hours of deliberation, the committee finally addressed the crux of the dispute.',
  '何時間もの審議の後、委員会はついに紛争の核心に取り組んだ。'),
(1552, 'foist', '(相手の望まないもの・不要なものなど)を押し付ける', '/fɔɪst/', 'フォイスト',
  'The manager tried to foist the tedious paperwork onto the newest member of the team.',
  'マネージャーは退屈な事務作業をチームの最も新しいメンバーに押し付けようとした。',
  'Consumers resented the company''s attempt to foist unwanted subscription services upon them.',
  '消費者は不要なサブスクリプションサービスを押し付けようとする会社の試みに憤慨した。'),
(1553, 'dispensation', '(権力者などからの)特別な許し;分配(品)', '/ˌdɪspenˈseɪʃən/', 'ディスペンセイション',
  'The bishop granted a special dispensation allowing the ceremony to be held outside the cathedral.',
  '司教は式典を大聖堂の外で行うことを認める特別な許しを与えた。',
  'Under the new dispensation, citizens were permitted to travel freely across provincial borders.',
  '新しい制度の下で、市民は州境を越えて自由に旅行することが許された。'),
(1554, 'arrears', '滞納、未払い金', '/əˈrɪrz/', 'アリアーズ',
  'The tenant fell into arrears on his rent payments after losing his job unexpectedly.',
  '借主は予期せず失業した後、家賃の支払いが滞納となった。',
  'The company was taken to court for being several months in arrears on its supplier invoices.',
  'その会社は仕入先への請求書が数ヶ月滞納していたため、裁判に訴えられた。'),
(1555, 'egalitarian', '平等主義の', '/ɪˌɡælɪˈtɛriən/', 'イギャリテリアン',
  'The constitution enshrines egalitarian principles that guarantee equal rights for all citizens.',
  'その憲法は全市民に平等な権利を保障する平等主義の原則を明記している。',
  'Critics argue that despite its egalitarian rhetoric, the policy disproportionately benefits the wealthy.',
  '批評家たちは、平等主義の修辞にもかかわらず、その政策は富裕層に不均衡に恩恵を与えていると主張している。'),
(1556, 'belittle', '~を軽んじる、見くびる', '/bɪˈlɪtl/', 'ビリトル',
  'The professor''s tendency to belittle students'' questions discouraged open discussion in the classroom.',
  '教授が学生の質問を軽んじる傾向は、教室での開かれた議論を妨げた。',
  'She refused to let anyone belittle her achievements, regardless of their seniority.',
  '彼女は相手の地位に関係なく、自分の功績を見くびらせることを拒んだ。'),
(1557, 'snarl', '(犬などが)(歯をむいて)うなる', '/snɑːrl/', 'スナール',
  'The guard dog began to snarl menacingly at the intruder who scaled the perimeter fence.',
  '番犬は外周のフェンスを乗り越えた侵入者に対して威嚇するようにうなり始めた。',
  'The wolf snarled at the approaching hikers, baring its teeth in a show of aggression.',
  'オオカミは近づいてくるハイカーたちに歯をむき出しにして攻撃の姿勢でうなった。'),
(1558, 'annihilate', '~を全滅させる、絶滅させる', '/əˈnaɪəleɪt/', 'アナイアレイト',
  'The volcanic eruption threatened to annihilate the entire ecosystem of the island.',
  '火山の噴火は島の生態系全体を絶滅させる恐れがあった。',
  'The invading army sought to annihilate all resistance in the occupied territory.',
  '侵略軍は占領地域のすべての抵抗勢力を全滅させようとした。'),
(1559, 'crabby', '不機嫌な、気難しい', '/ˈkræbi/', 'クラビー',
  'The crabby librarian scolded anyone who so much as whispered in the reading room.',
  '気難しい図書館員は閲覧室で少しでもささやいた人を叱りつけた。',
  'Lack of sleep made him increasingly crabby, and his colleagues learned to avoid him in the mornings.',
  '睡眠不足で彼はますます不機嫌になり、同僚たちは朝は彼を避けるようになった。'),
(1560, 'glib', '(人・発言・態度などが)口先だけの、軽薄な', '/ɡlɪb/', 'グリブ',
  'The politician''s glib assurances failed to convince the public that meaningful reform was forthcoming.',
  'その政治家の口先だけの保証は、意味のある改革が近いと国民を納得させることができなかった。',
  'His glib response to the serious allegations only deepened the suspicion surrounding him.',
  '深刻な疑惑に対する彼の軽薄な返答は、彼を取り巻く疑念をさらに深めただけだった。'),
(1562, 'entreaty', '懇願、嘆願', '/ɪnˈtriːti/', 'エントリーティ',
  'Despite her heartfelt entreaty, the judge refused to reduce the sentence.',
  '彼女の心からの懇願にもかかわらず、裁判官は刑の軽減を拒んだ。',
  'The refugees'' entreaty for asylum was met with bureaucratic indifference.',
  '難民たちの亡命の嘆願は官僚的な無関心で迎えられた。'),
(1563, 'luminary', '著名人、大御所、大家', '/ˈluːmɪneri/', 'ルーミナリー',
  'The conference attracted luminaries from the fields of science, literature, and the arts.',
  'その会議は科学、文学、芸術の分野から著名人たちを集めた。',
  'As a luminary in the world of architecture, her designs have influenced an entire generation.',
  '建築界の大御所として、彼女のデザインは一世代全体に影響を与えてきた。'),
(1564, 'ebullience', '(あふれんばかりの)情熱、エネルギー', '/ɪˈbʌliəns/', 'イバリエンス',
  'The candidate''s ebullience on the campaign trail energized voters across the nation.',
  '選挙活動中のその候補者のあふれんばかりの情熱は全国の有権者を活気づけた。',
  'Her natural ebullience made her the perfect choice to lead the team through the challenging project.',
  '彼女の生来のエネルギーは、困難なプロジェクトを通じてチームを率いるのに最適な選択肢とした。'),
(1565, 'senile', '老齢による、もうろくした', '/ˈsiːnaɪl/', 'シーナイル',
  'The family struggled to cope with the grandfather''s increasingly senile behavior.',
  '家族は祖父のますますもうろくした行動に対処するのに苦労した。',
  'The opposition cruelly suggested that the aging president was becoming senile and unfit for office.',
  '野党は高齢の大統領がもうろくして職務に不適格になりつつあると残酷に示唆した。'),
(1566, 'incredulous', '(人が)信じようとしない;(顔つきなどが)疑うような', '/ɪnˈkredʒələs/', 'インクレジュラス',
  'The jury exchanged incredulous glances when the defendant retracted his earlier confession.',
  '被告が以前の自白を撤回したとき、陪審員たちは信じられないという視線を交わした。',
  'She gave him an incredulous look when he claimed to have finished the entire report overnight.',
  '彼が一晩で報告書全体を仕上げたと主張したとき、彼女は疑うような目で彼を見た。'),
(1567, 'waylay', '(どこかに行こうとする人)を呼び止める', '/weɪˈleɪ/', 'ウェイレイ',
  'Reporters waylaid the minister outside the parliament building, demanding answers about the scandal.',
  '記者たちは国会議事堂の外で大臣を呼び止め、スキャンダルについての回答を要求した。',
  'She was waylaid by a colleague in the corridor who insisted on discussing the budget proposal.',
  '彼女は廊下で予算案について議論することを主張する同僚に呼び止められた。'),
(1568, 'tubby', 'ずんぐりした、太った', '/ˈtʌbi/', 'タビー',
  'The tubby cat waddled across the kitchen floor in search of its food bowl.',
  'ずんぐりした猫は餌皿を探して台所の床をよちよち歩いた。',
  'As a child he was rather tubby, but he slimmed down considerably after taking up long-distance running.',
  '子供の頃は太っていたが、長距離走を始めてからかなり痩せた。'),
(1569, 'acquiesce', '黙認する、(黙って・反論せずに)受け入れる', '/ˌækwiˈes/', 'アクウィエス',
  'The board reluctantly acquiesced to the shareholders'' demands for greater transparency.',
  '取締役会は渋々ながら、より大きな透明性を求める株主の要求を受け入れた。',
  'Rather than protest, the employees chose to acquiesce in the new working arrangements.',
  '抗議するのではなく、従業員たちは新しい勤務体制を黙認することを選んだ。'),
(1570, 'conscription', '徴兵(制度)', '/kənˈskrɪpʃən/', 'コンスクリプション',
  'The government introduced conscription as the threat of invasion grew increasingly imminent.',
  '侵略の脅威がますます差し迫る中、政府は徴兵制度を導入した。',
  'Many young men fled the country to avoid conscription during the prolonged conflict.',
  '長引く紛争中、多くの若者が徴兵を逃れるために国外に逃亡した。'),
(1571, 'contravene', '(法律・規則など)に違反する', '/ˌkɑːntrəˈviːn/', 'コントラヴィーン',
  'The factory was fined heavily for contravening environmental regulations on waste disposal.',
  'その工場は廃棄物処理に関する環境規制に違反したとして多額の罰金を科された。',
  'Any clause that contravenes international human rights law will be deemed null and void.',
  '国際人権法に違反する条項はすべて無効とみなされる。'),
(1572, 'inter', '~を埋葬する', '/ɪnˈtɜːr/', 'インター',
  'The remains of the fallen soldiers were interred with full military honors at the national cemetery.',
  '戦没兵士の遺骨は国立墓地で軍の完全な栄誉礼をもって埋葬された。',
  'The ancient king was interred in an elaborate tomb filled with precious artifacts.',
  '古代の王は貴重な遺物で満たされた精巧な墓に埋葬された。'),
(1574, 'dribble', '(液体・よだれ)を垂らす;垂れる;(サッカーなどで)ドリブルする;したたり', '/ˈdrɪbl/', 'ドリブル',
  'The baby dribbled milk down the front of her bib during the feeding.',
  '赤ちゃんは授乳中によだれかけの前面にミルクを垂らした。',
  'The midfielder dribbled past three defenders before delivering a perfect cross into the box.',
  'そのミッドフィールダーは3人のディフェンダーをドリブルでかわし、ボックス内に完璧なクロスを送った。'),
(1575, 'rumple', '(髪・服など)をくしゃくしゃにする;くしゃくしゃになる;しわ', '/ˈrʌmpl/', 'ランプル',
  'The child rumpled his school uniform within minutes of putting it on.',
  '子供は制服を着てから数分でくしゃくしゃにしてしまった。',
  'She smoothed out the rumples in the tablecloth before the dinner guests arrived.',
  '夕食の客が到着する前に、彼女はテーブルクロスのしわを伸ばした。'),
(1576, 'kindred', '同類の、よく似た;血縁の、親類の', '/ˈkɪndrɪd/', 'キンドレッド',
  'The two researchers discovered they were kindred spirits who shared a passion for marine biology.',
  '二人の研究者は、海洋生物学に対する情熱を共有する同類の魂であることを発見した。',
  'She felt an instant connection with kindred souls at the literary festival.',
  '彼女は文学祭で同類の人々と瞬時につながりを感じた。'),
(1577, 'cardinal', '非常に重要な、基本的な', '/ˈkɑːrdɪnl/', 'カーディナル',
  'Honesty is a cardinal virtue that underpins all meaningful human relationships.',
  '誠実さはすべての意義ある人間関係の基盤となる非常に重要な美徳である。',
  'The report identified several cardinal errors in the company''s risk management strategy.',
  'その報告書は会社のリスク管理戦略における基本的な誤りをいくつか特定した。'),
(1578, 'matriculate', '(大学などに)入学する', '/məˈtrɪkjəleɪt/', 'マトリキュレイト',
  'She matriculated at one of the country''s most prestigious universities on a full scholarship.',
  '彼女は全額奨学金で国内最も名門の大学の一つに入学した。',
  'Students who matriculate in the autumn semester must complete orientation by the end of September.',
  '秋学期に入学する学生は9月末までにオリエンテーションを修了しなければならない。'),
(1579, 'treason', '反逆(罪)', '/ˈtriːzn/', 'トリーズン',
  'The general was tried for treason after conspiring to overthrow the democratically elected government.',
  'その将軍は民主的に選ばれた政府を転覆する陰謀を企てた後、反逆罪で裁判にかけられた。',
  'Leaking classified military intelligence to a foreign power constitutes an act of treason.',
  '機密の軍事情報を外国勢力に漏洩することは反逆行為に該当する。'),
(1580, 'bereaved', '最近家族[親友]を亡くした、あとに残された', '/bɪˈriːvd/', 'ビリーヴド',
  'The charity provides counseling services to bereaved families struggling with grief.',
  'その慈善団体は悲しみに苦しむ遺族にカウンセリングサービスを提供している。',
  'The bereaved widow delivered a moving eulogy at her husband''s memorial service.',
  'あとに残された未亡人は夫の追悼式で感動的な弔辞を述べた。'),
(1581, 'tier', '段階、階層;(段状の)座席', '/tɪr/', 'ティアー',
  'The new pricing structure introduces three tiers of membership, each offering different benefits.',
  '新しい料金体系は、それぞれ異なる特典を提供する3段階の会員制度を導入する。',
  'Spectators in the upper tier of the stadium had a panoramic view of the entire pitch.',
  'スタジアムの上段の座席の観客はピッチ全体のパノラマビューを楽しめた。'),
(1582, 'garrulous', 'おしゃべりな', '/ˈɡærələs/', 'ギャルラス',
  'The garrulous taxi driver regaled his passengers with stories throughout the entire journey.',
  'おしゃべりなタクシー運転手は旅の間中、乗客に話を聞かせ続けた。',
  'Her garrulous nature, while endearing at social gatherings, proved distracting in the workplace.',
  '彼女のおしゃべりな性格は社交の場では愛嬌があったが、職場では気が散る原因となった。'),
(1583, 'digression', '(話などの)脱線、逸脱', '/daɪˈɡreʃən/', 'ダイグレッション',
  'The professor''s frequent digressions, though entertaining, left little time for the core material.',
  '教授の頻繁な脱線は面白かったが、核心的な教材のための時間をほとんど残さなかった。',
  'After a lengthy digression about his childhood, the speaker finally returned to the main topic.',
  '子供時代についての長い脱線の後、講演者はようやく本題に戻った。'),
(1584, 'stymie', '~を妨害する、邪魔する', '/ˈstaɪmi/', 'スタイミー',
  'Bureaucratic red tape continued to stymie efforts to deliver humanitarian aid to the region.',
  '官僚的な手続きがその地域への人道支援の取り組みを妨害し続けた。',
  'The lack of funding stymied the research team''s attempt to develop a breakthrough treatment.',
  '資金不足が画期的な治療法を開発しようとする研究チームの試みを妨害した。'),
(1586, 'dismay', '~をうろたえさせる、失望させる;狼狽、失望', '/dɪsˈmeɪ/', 'ディスメイ',
  'The sudden cancellation of the project dismayed the researchers who had invested years of effort.',
  'プロジェクトの突然の中止は、何年もの努力を投じてきた研究者たちを失望させた。',
  'To the dismay of environmentalists, the government approved the construction of the controversial dam.',
  '環境保護主義者たちの失望をよそに、政府は物議を醸すダムの建設を承認した。'),
(1587, 'volition', '意志の働き、決断', '/voʊˈlɪʃən/', 'ヴォリション',
  'She left the company of her own volition, contrary to rumors that she had been forced out.',
  '彼女は追い出されたという噂に反して、自分の意志で会社を辞めた。',
  'The philosopher argued that true volition requires not merely desire but conscious deliberation.',
  'その哲学者は、真の意志の働きには単なる願望だけでなく意識的な熟慮が必要であると論じた。'),
(1588, 'arbitrate', '~を仲裁する、調停する', '/ˈɑːrbɪtreɪt/', 'アービトレイト',
  'An independent panel was appointed to arbitrate the dispute between the two corporations.',
  '二つの企業間の紛争を仲裁するために独立した委員会が任命された。',
  'The labor union requested that a neutral third party arbitrate the contract negotiations.',
  '労働組合は中立的な第三者が契約交渉を調停するよう要請した。'),
(1589, 'agape', '(驚いて)口を開けた、非常に驚いた', '/əˈɡeɪp/', 'アゲイプ',
  'The audience sat agape as the magician performed an illusion that defied all explanation.',
  '観客はあらゆる説明を覆す手品をマジシャンが披露する中、口を開けて座っていた。',
  'She stood agape at the breathtaking panorama that unfolded from the mountain summit.',
  '彼女は山頂から広がる息をのむようなパノラマに口を開けて立ち尽くした。'),
(1590, 'gradient', '(道・鉄道などの)勾配、傾斜', '/ˈɡreɪdiənt/', 'グレイディエント',
  'The steep gradient of the mountain pass made it treacherous for vehicles during winter.',
  '山道の急な勾配は冬季に車両にとって危険なものとなった。',
  'Engineers had to account for the natural gradient of the terrain when designing the drainage system.',
  '技術者たちは排水システムを設計する際に地形の自然な傾斜を考慮しなければならなかった。'),
(1591, 'repulsive', '嫌悪感を催させる、不快な', '/rɪˈpʌlsɪv/', 'リパルシヴ',
  'The documentary exposed the repulsive conditions in which factory workers were forced to live.',
  'そのドキュメンタリーは工場労働者が強いられていた不快な生活環境を暴露した。',
  'Many found the defendant''s lack of remorse for his crimes utterly repulsive.',
  '多くの人が被告の犯罪に対する反省のなさをまったく嫌悪感を催させるものだと感じた。'),
(1592, 'abduct', '(人)を誘拐する、拉致する', '/æbˈdʌkt/', 'アブダクト',
  'The criminal gang attempted to abduct the businessman''s daughter and hold her for ransom.',
  '犯罪集団は実業家の娘を誘拐し、身代金目的で拘束しようとした。',
  'International authorities cooperated to rescue the diplomat who had been abducted in broad daylight.',
  '白昼に拉致された外交官を救出するために国際当局が協力した。'),
(1593, 'linkage', 'つながり、関連', '/ˈlɪŋkɪdʒ/', 'リンケージ',
  'Researchers established a clear linkage between prolonged exposure to pollution and respiratory disease.',
  '研究者たちは汚染への長期的な曝露と呼吸器疾患との明確なつながりを立証した。',
  'The political linkage between trade agreements and human rights remains a contentious issue.',
  '貿易協定と人権の政治的な関連は依然として論争の的となっている。'),
(1594, 'contraption', '変わった機械[器具]', '/kənˈtræpʃən/', 'コントラプション',
  'The inventor proudly demonstrated his bizarre contraption designed to automate household chores.',
  'その発明家は家事を自動化するために設計された奇妙な機械を誇らしげに実演した。',
  'The Rube Goldberg contraption delighted the children with its elaborate chain of mechanical reactions.',
  'そのルーブ・ゴールドバーグの変わった器具は精巧な連鎖機械反応で子供たちを喜ばせた。'),
(1595, 'garble', '~を誤って伝える', '/ˈɡɑːrbl/', 'ガーブル',
  'The message was so badly garbled during transmission that its original meaning was lost entirely.',
  '伝達中にそのメッセージがひどく誤って伝えられたため、元の意味は完全に失われた。',
  'Witnesses garbled the suspect''s description, leading the police to pursue the wrong individual.',
  '目撃者たちが容疑者の特徴を誤って伝えたため、警察は間違った人物を追跡することになった。'),
(1596, 'demur', '(穏やかに)異議を唱える', '/dɪˈmɜːr/', 'ディマー',
  'When asked to accept the unfavorable terms, the lawyer demurred and requested further negotiations.',
  '不利な条件を受け入れるよう求められたとき、弁護士は異議を唱え、さらなる交渉を要請した。',
  'She demurred at the suggestion that she should retire, insisting she still had much to contribute.',
  '彼女は引退すべきだという提案に穏やかに異議を唱え、まだ多くの貢献ができると主張した。'),
(1598, 'stolid', '感情を表に出さない;無感動な', '/ˈstɑːlɪd/', 'ストリッド',
  'The stolid guard remained expressionless even as chaos erupted around him.',
  '感情を表に出さない警備員は周囲が混乱に陥っても無表情のままだった。',
  'Behind his stolid exterior, he harbored a deep sensitivity that few people ever glimpsed.',
  '無感動な外見の裏に、彼はほとんど誰にも見せない深い感受性を秘めていた。'),
(1599, 'sedate', '(人・場所などが)落ち着いた、物静かな', '/sɪˈdeɪt/', 'セデイト',
  'The sedate atmosphere of the old library provided the perfect environment for scholarly research.',
  'その古い図書館の落ち着いた雰囲気は学術研究に最適な環境を提供した。',
  'Compared to the bustling capital, the sedate provincial town offered a welcome respite from noise and stress.',
  '賑やかな首都に比べて、物静かな地方の町は騒音とストレスからの歓迎される休息を提供した。'),
(1600, 'gaudy', '派手な、けばけばしい', '/ˈɡɔːdi/', 'ゴーディ',
  'The gaudy decorations at the event clashed with the venue''s otherwise elegant interior.',
  'イベントの派手な装飾は、それ以外は上品な会場の内装と調和しなかった。',
  'She dismissed the gaudy jewelry as tasteless and opted for a simple pearl necklace instead.',
  '彼女はけばけばしい宝石を趣味が悪いと退け、代わりにシンプルな真珠のネックレスを選んだ。');
