-- words テーブル INSERT文 (No.1601 ~ No.1650)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1601, 'provident', '将来に備えた、将来のために倹約する', '/ˈprɒvɪdənt/', 'プロヴィデント',
  'A provident investor always diversifies assets to mitigate the risks of market volatility.',
  '将来に備えた投資家は常に資産を分散させて市場変動のリスクを軽減する。',
  'Her provident nature led her to accumulate substantial savings well before retirement.',
  '彼女の将来のために倹約する性格のおかげで、退職のかなり前に相当な貯蓄を蓄えた。'),
(1602, 'fortuitously', '偶然に、思いがけず', '/fɔːrˈtjuːɪtəsli/', 'フォートゥイタスリー',
  'The manuscript was fortuitously discovered in the attic of an abandoned estate.',
  'その原稿は廃墟となった邸宅の屋根裏部屋で偶然に発見された。',
  'Fortuitously, the surgeon who specialized in that rare condition happened to be visiting the hospital that day.',
  '思いがけず、その稀な疾患を専門とする外科医がその日たまたまその病院を訪れていた。'),
(1603, 'rebate', '払い戻し(金)', '/ˈriːbeɪt/', 'リーベイト',
  'Customers who purchase energy-efficient appliances may be eligible for a government rebate.',
  '省エネ家電を購入する顧客は政府の払い戻し金の対象となる場合がある。',
  'The company offered a generous rebate to retain dissatisfied subscribers.',
  'その会社は不満を持つ加入者を引き留めるために寛大な払い戻しを提供した。'),
(1604, 'burnish', '(金属など)を磨く、~につやを出す', '/ˈbɜːrnɪʃ/', 'バーニッシュ',
  'The craftsman spent hours burnishing the brass fixtures until they gleamed like gold.',
  '職人は真鍮の金具が金のように輝くまで何時間もかけて磨いた。',
  'The politician sought to burnish his reputation by championing popular environmental causes.',
  'その政治家は人気のある環境問題を擁護することで自分の評判につやを出そうとした。'),
(1605, 'overhaul', '~を分解修理する、オーバーホールする;分解修理、オーバーホール', '/ˌoʊvərˈhɔːl/', 'オーヴァーホール',
  'The airline was forced to overhaul its entire fleet after inspectors discovered structural defects.',
  '検査官が構造的欠陥を発見した後、その航空会社は全機体を分解修理することを余儀なくされた。',
  'A comprehensive overhaul of the education system is long overdue in this country.',
  'この国では教育制度の包括的なオーバーホールがとうに必要とされている。'),
(1606, 'ponderous', '(重々しくて)退屈な、つまらない;(動きなどが)のっそりした、鈍重な', '/ˈpɒndərəs/', 'ポンダラス',
  'The professor''s ponderous lectures drove many students to the brink of sleep.',
  '教授の退屈な講義は多くの学生を眠りの淵に追いやった。',
  'The ponderous elephant lumbered through the dense undergrowth with surprising grace.',
  'のっそりした象は驚くほど優雅に密生した下草の中を進んだ。'),
(1607, 'eponymous', '(小説・劇などの主人公が)作品名と同名の', '/ɪˈpɒnɪməs/', 'エポニマス',
  'The eponymous heroine of Charlotte Brontë''s novel endures great hardship before finding happiness.',
  'シャーロット・ブロンテの小説の作品名と同名のヒロインは幸福を見つけるまで大きな苦難に耐える。',
  'The band released their eponymous debut album to widespread critical acclaim.',
  'そのバンドはバンド名と同名のデビューアルバムを発売し、幅広い批評家の称賛を受けた。'),
(1608, 'incisive', '(言葉・批評などが)鋭い、的確な', '/ɪnˈsaɪsɪv/', 'インサイシヴ',
  'The journalist''s incisive questioning exposed the contradictions in the minister''s official statement.',
  'そのジャーナリストの鋭い質問が大臣の公式声明の矛盾を暴いた。',
  'Her incisive analysis of the economic data persuaded the board to revise its strategy.',
  '彼女の的確な経済データ分析が取締役会に戦略を見直すよう説得した。'),
(1610, 'cavernous', '(洞窟のように)だだっ広い', '/ˈkævərnəs/', 'キャヴァナス',
  'The cavernous warehouse stood empty, its vast interior echoing with every footstep.',
  'だだっ広い倉庫は空っぽで、その広大な内部は足音ごとに反響した。',
  'They dined in a cavernous banquet hall that could easily accommodate five hundred guests.',
  '彼らは500人の客を容易に収容できるだだっ広い宴会場で食事をした。'),
(1611, 'jubilant', '歓喜に満ちた', '/ˈdʒuːbɪlənt/', 'ジュービラント',
  'The jubilant crowd erupted into cheers as the national team scored the winning goal.',
  '代表チームが決勝ゴールを決めると、歓喜に満ちた群衆は歓声を上げた。',
  'Jubilant supporters flooded the streets to celebrate their candidate''s landslide victory.',
  '歓喜に満ちた支持者たちは候補者の圧勝を祝って通りにあふれ出た。'),
(1612, 'aperture', 'すき間、割れ目', '/ˈæpərtʃər/', 'アパチャー',
  'Light streamed through a narrow aperture in the ancient stone wall.',
  '古い石壁の狭いすき間から光が差し込んだ。',
  'The photographer adjusted the aperture of the lens to capture the perfect depth of field.',
  '写真家は完璧な被写界深度を捉えるためにレンズの絞りを調整した。'),
(1613, 'devout', '信心深い、敬虔な', '/dɪˈvaʊt/', 'ディヴァウト',
  'The devout congregation gathered at dawn for the Easter sunrise service.',
  '信心深い会衆は復活祭の日の出の礼拝のために夜明けに集まった。',
  'A devout adherent of nonviolence, she refused to retaliate even when provoked.',
  '非暴力の敬虔な信奉者である彼女は、挑発されても報復することを拒んだ。'),
(1614, 'promulgate', '〈考えなど〉を広める、宣伝する;〈法律など〉を公布する', '/ˈprɒməlɡeɪt/', 'プロマルゲイト',
  'The government promulgated new regulations aimed at curbing carbon emissions from heavy industry.',
  '政府は重工業からの炭素排出を抑制することを目的とした新しい規制を公布した。',
  'The organization actively promulgates the principles of sustainable development across the region.',
  'その組織は地域全体で持続可能な開発の原則を積極的に広めている。'),
(1615, 'pliable', '曲がりやすい、柔軟な', '/ˈplaɪəbl/', 'プライアブル',
  'The artisan selected pliable willow branches to weave an intricate basket.',
  '職人は精巧な籠を編むために曲がりやすい柳の枝を選んだ。',
  'Young children''s minds are remarkably pliable, making early education crucial for their development.',
  '幼い子供の心は非常に柔軟であり、早期教育が発達にとって極めて重要である。'),
(1616, 'chunky', '〈服などが〉厚手の;〈人・動物が〉どっしりした、ずんぐりした', '/ˈtʃʌŋki/', 'チャンキー',
  'She wrapped herself in a chunky knit sweater to ward off the bitter winter chill.',
  '彼女は厳しい冬の寒さを防ぐために厚手のニットセーターに身を包んだ。',
  'The chunky bulldog waddled across the park, drawing affectionate laughter from onlookers.',
  'ずんぐりしたブルドッグが公園をよちよち歩き、見物人から愛情のこもった笑いを誘った。'),
(1617, 'specter', '不安、恐怖;幽霊、亡霊', '/ˈspektər/', 'スペクター',
  'The specter of mass unemployment loomed over the nation as factories continued to close.',
  '工場が閉鎖され続ける中、大量失業の不安が国全体に立ちこめた。',
  'The old mansion was rumored to be haunted by the specter of its former owner.',
  'その古い邸宅は元の所有者の亡霊に取り憑かれているという噂があった。'),
(1618, 'undulate', '〈土地などが〉起伏に富む、〈水面などが〉波打つ', '/ˈʌndjəleɪt/', 'アンジュレイト',
  'The golden wheat fields undulated gently in the warm summer breeze.',
  '金色の小麦畑が暖かい夏のそよ風に穏やかに波打った。',
  'The terrain undulated dramatically, presenting a formidable challenge for the marathon runners.',
  '地形は激しく起伏に富み、マラソンランナーたちに手ごわい挑戦を突きつけた。'),
(1619, 'spoof', 'パロディー、もじり', '/spuːf/', 'スプーフ',
  'The comedian''s spoof of the prime minister''s mannerisms had the audience in stitches.',
  'そのコメディアンの首相の癖のパロディーは観客を爆笑させた。',
  'The film is a clever spoof of classic horror movies that pays homage while poking fun.',
  'その映画は古典的ホラー映画の巧みなもじりで、敬意を表しながらからかっている。'),
(1620, 'extort', '〈金銭など〉を巻き上げる、強要する', '/ɪkˈstɔːrt/', 'エクストート',
  'The corrupt official attempted to extort bribes from businesses seeking government contracts.',
  '腐敗した役人は政府の契約を求める企業から賄賂を巻き上げようとした。',
  'The gang extorted protection money from shopkeepers in the neighborhood under threat of violence.',
  'そのギャングは暴力をちらつかせて近隣の商店主からみかじめ料を強要した。'),
(1622, 'inimical', '有害で、不利で', '/ɪˈnɪmɪkəl/', 'イニミカル',
  'The committee concluded that the proposed development was inimical to the preservation of wildlife habitats.',
  '委員会はその開発計画が野生生物の生息地の保全に有害であると結論づけた。',
  'A corporate culture that is inimical to innovation will inevitably stifle long-term growth.',
  '革新に不利な企業文化は必然的に長期的な成長を抑制する。'),
(1623, 'ameliorate', '~を改善する', '/əˈmiːliəreɪt/', 'アミーリオレイト',
  'The new legislation was designed to ameliorate the living conditions of migrant workers.',
  'その新しい法律は移民労働者の生活条件を改善するために設計された。',
  'Charitable organizations have worked tirelessly to ameliorate the suffering caused by the famine.',
  '慈善団体は飢饉によって引き起こされた苦しみを改善するために精力的に活動してきた。'),
(1624, 'waver', '動揺する、迷う', '/ˈweɪvər/', 'ウェイヴァー',
  'Despite intense pressure from her peers, she never wavered in her commitment to ethical journalism.',
  '同僚からの激しい圧力にもかかわらず、彼女は倫理的なジャーナリズムへの信念に動揺することはなかった。',
  'The jury wavered for days before finally reaching a unanimous verdict.',
  '陪審員団は何日も迷った末にようやく全員一致の評決に達した。'),
(1625, 'ferocious', '〈人・動物が〉凶暴な、どう猛な;〈風雨・感情などが〉激しい', '/fəˈroʊʃəs/', 'フェロウシャス',
  'The ferocious storm battered the coastline, uprooting trees and demolishing fragile structures.',
  '激しい嵐が海岸線を打ちつけ、木を根こそぎにし脆い建造物を破壊した。',
  'The debate grew increasingly ferocious as both candidates traded personal accusations.',
  '両候補が個人攻撃を交わす中、議論はますます激しくなった。'),
(1626, 'irresolute', '優柔不断な、決断力のない', '/ɪˈrezəluːt/', 'イレゾルート',
  'The irresolute leader''s inability to make timely decisions cost the company dearly.',
  '優柔不断な指導者の適時に決断を下せない能力不足は会社に大きな損失をもたらした。',
  'Voters grew weary of the irresolute government that seemed incapable of addressing the economic crisis.',
  '有権者たちは経済危機に対処する能力がないように見える決断力のない政府にうんざりした。'),
(1627, 'hilarious', 'とても面白い、こっけいな', '/hɪˈlɛriəs/', 'ヒレリアス',
  'The comedian''s hilarious impersonation of world leaders brought the audience to tears of laughter.',
  'そのコメディアンの世界の指導者たちのとても面白い物まねは観客を涙が出るほど笑わせた。',
  'What was intended as a serious speech turned into a hilarious spectacle when the microphone malfunctioned.',
  '真剣なスピーチのつもりだったものが、マイクが故障してこっけいな見世物になった。'),
(1628, 'banish', '〈人〉を追放する;〈考えなど〉を追い払う', '/ˈbænɪʃ/', 'バニッシュ',
  'The dissident was banished from the country for publicly criticizing the authoritarian regime.',
  'その反体制派は独裁政権を公然と批判したとして国外に追放された。',
  'She tried to banish all negative thoughts from her mind before the crucial examination.',
  '彼女は重要な試験の前にすべての否定的な考えを頭から追い払おうとした。'),
(1629, 'conformist', '(伝統・慣習などに)従う人、順応主義者', '/kənˈfɔːrmɪst/', 'コンフォーミスト',
  'The artist rebelled against the conformists who insisted that art must adhere to classical traditions.',
  'その芸術家は芸術が古典的な伝統に従わなければならないと主張する順応主義者たちに反抗した。',
  'In a society dominated by conformists, those who dare to think differently are often marginalized.',
  '順応主義者が支配する社会では、あえて異なる考え方をする人々はしばしば疎外される。'),
(1630, 'angst', '(将来などに対する)不安、苦悩', '/æŋst/', 'アングスト',
  'The novel captures the existential angst of a generation disillusioned by economic stagnation.',
  'その小説は経済停滞に幻滅した世代の実存的不安を捉えている。',
  'Teenage angst is a recurring theme in contemporary coming-of-age literature.',
  '十代の苦悩は現代の成長物語文学における繰り返し現れるテーマである。'),
(1631, 'remit', '〈金銭など〉を送る;〈刑・税金など〉を免じる', '/rɪˈmɪt/', 'リミット',
  'Migrant workers often remit a significant portion of their earnings to their families abroad.',
  '移民労働者はしばしば収入のかなりの部分を海外の家族に送金する。',
  'The governor exercised his authority to remit the remainder of the prisoner''s sentence.',
  '知事は囚人の残りの刑期を免じる権限を行使した。'),
(1632, 'redolence', '芳香', '/ˈredələns/', 'レドレンス',
  'The redolence of freshly baked bread wafted through the narrow streets of the village.',
  '焼きたてのパンの芳香が村の狭い通りに漂った。',
  'The garden was renowned for the exquisite redolence of its rare orchid collection.',
  'その庭園は珍しい蘭のコレクションの絶妙な芳香で知られていた。'),
(1634, 'predominate', '(数・力などの点で)優位を占める', '/prɪˈdɒmɪneɪt/', 'プリドミネイト',
  'In this region, agriculture continues to predominate as the primary source of livelihood.',
  'この地域では農業が主要な生計手段として優位を占め続けている。',
  'Although several genres were represented, classical compositions predominated at the festival.',
  'いくつかのジャンルが出品されていたが、フェスティバルではクラシック作品が優位を占めた。'),
(1635, 'apex', '(山の)頂上;(成功の)絶頂', '/ˈeɪpeks/', 'エイペックス',
  'After decades of dedication, she finally reached the apex of her career as a Supreme Court justice.',
  '数十年の献身の後、彼女はついに最高裁判事としてのキャリアの絶頂に達した。',
  'The climbers paused to rest just below the apex of the treacherous mountain peak.',
  '登山者たちは危険な山の頂上のすぐ下で休憩した。'),
(1636, 'accreditation', '(公式の)認可、認定', '/əˌkredɪˈteɪʃən/', 'アクレディテイション',
  'The university risked losing its accreditation after failing to meet the prescribed academic standards.',
  'その大学は所定の学術基準を満たせなかったため、認定を失う危険にさらされた。',
  'International accreditation has become indispensable for institutions seeking to attract overseas students.',
  '国際的な認可は海外の学生を惹きつけようとする教育機関にとって不可欠となっている。'),
(1637, 'courier', '(書類・小包などの)配達人、配達業者', '/ˈkʊriər/', 'クーリエ',
  'The confidential documents were dispatched by a trusted courier rather than through the postal service.',
  '機密文書は郵便ではなく信頼できる配達人によって発送された。',
  'The courier navigated through heavy traffic to ensure the package arrived before the deadline.',
  '配達業者は締め切り前に荷物が届くよう激しい交通渋滞を縫って進んだ。'),
(1638, 'elongate', '~を長くする、伸ばす', '/ɪˈlɔːŋɡeɪt/', 'イロンゲイト',
  'The designer elongated the silhouette of the dress to create a more elegant and statuesque appearance.',
  'デザイナーはより優雅で堂々とした外観を生み出すためにドレスのシルエットを長くした。',
  'Yoga practitioners often perform stretches that elongate the spine and improve posture.',
  'ヨガの実践者は脊椎を伸ばし姿勢を改善するストレッチをよく行う。'),
(1639, 'servitude', '隷属(状態)、服従', '/ˈsɜːrvɪtjuːd/', 'サーヴィチュード',
  'The abolition of servitude marked a pivotal turning point in the nation''s history.',
  '隷属状態の廃止はその国の歴史における極めて重要な転換点となった。',
  'Generations of families endured decades of servitude before the emancipation decree was issued.',
  '解放令が発布されるまで何世代もの家族が数十年にわたる服従に耐えた。'),
(1640, 'inertia', 'ものぐさ、怠惰;慣性、惰性', '/ɪˈnɜːrʃə/', 'イナーシャ',
  'Bureaucratic inertia prevented the swift implementation of the emergency relief program.',
  '官僚的な怠惰が緊急救援プログラムの迅速な実施を妨げた。',
  'The physicist demonstrated how the principle of inertia governs the motion of celestial bodies.',
  'その物理学者は慣性の法則がいかに天体の運動を支配するかを実演した。'),
(1641, 'impregnable', '〈考え・地位などが〉揺るがない、動じない;〈要塞などが〉難攻不落の', '/ɪmˈpreɡnəbl/', 'インプレグナブル',
  'The fortress was considered impregnable until the enemy discovered a hidden passage beneath its walls.',
  'その要塞は敵が城壁の下に隠された通路を発見するまで難攻不落と考えられていた。',
  'Her impregnable confidence in the face of relentless criticism earned her the respect of her colleagues.',
  '容赦ない批判に直面しても揺るがない彼女の自信は同僚たちの尊敬を勝ち取った。'),
(1642, 'stalwart', '(組織・政党などの)熱心な支持者', '/ˈstɔːlwərt/', 'ストールワート',
  'The party stalwarts rallied behind the new leader despite widespread skepticism from the public.',
  '国民の間に広がる懐疑にもかかわらず、党の熱心な支持者たちは新しいリーダーの下に結集した。',
  'As a stalwart of the civil rights movement, she dedicated her entire life to the pursuit of equality.',
  '公民権運動の熱心な支持者として、彼女は平等の追求に全生涯を捧げた。'),
(1643, 'blasphemy', '(神などに対する)不敬、冒涜', '/ˈblæsfəmi/', 'ブラスフェミー',
  'In certain theocratic states, blasphemy remains a criminal offense punishable by imprisonment.',
  '一部の神権国家では、冒涜は依然として投獄に処せられる犯罪行為である。',
  'The author''s controversial novel was denounced by religious leaders as an act of blasphemy.',
  'その作家の物議を醸す小説は宗教指導者たちによって不敬行為であると非難された。'),
(1644, 'haughty', '〈人・態度などが〉高慢な、横柄な', '/ˈhɔːti/', 'ホーティ',
  'The haughty aristocrat refused to acknowledge the presence of those he deemed beneath his station.',
  'その高慢な貴族は自分の地位にふさわしくないとみなす者たちの存在を認めようとしなかった。',
  'Her haughty demeanor alienated potential allies who might otherwise have supported her candidacy.',
  '彼女の横柄な態度は、そうでなければ彼女の立候補を支持したかもしれない潜在的な味方を遠ざけた。'),
(1646, 'attuned', '順応して、慣れて', '/əˈtjuːnd/', 'アチューンド',
  'A skilled diplomat must be keenly attuned to the cultural sensitivities of the host nation.',
  '熟練した外交官は受入国の文化的な敏感さに鋭く順応していなければならない。',
  'After years of living abroad, she became fully attuned to the rhythms of her adopted country.',
  '何年も海外で暮らした後、彼女は養子縁組先の国のリズムに完全に慣れた。'),
(1647, 'ascetic', '苦行の、禁欲主義の', '/əˈsetɪk/', 'アセティック',
  'The monk embraced an ascetic lifestyle, renouncing all material possessions and worldly pleasures.',
  'その僧侶はすべての物質的な所有物と世俗的な快楽を放棄し、苦行の生活様式を受け入れた。',
  'Her ascetic discipline in training was widely credited for her extraordinary athletic achievements.',
  '彼女のトレーニングにおける禁欲主義的な規律が、彼女の並外れた運動成績の功績として広く認められた。'),
(1648, 'reciprocate', '(同じ行為)を相手に返す', '/rɪˈsɪprəkeɪt/', 'リシプロケイト',
  'When a neighboring country offered disaster relief, the government was eager to reciprocate the goodwill.',
  '隣国が災害救援を申し出たとき、政府はその好意を返すことに熱心だった。',
  'She reciprocated his kindness by volunteering to assist with his charitable foundation.',
  '彼女は彼の慈善財団の手伝いをボランティアで申し出ることで彼の親切に報いた。'),
(1649, 'prophetic', '予言者の、予言的な', '/prəˈfetɪk/', 'プロフェティック',
  'The scientist''s prophetic warnings about climate change, once dismissed, have now proven alarmingly accurate.',
  'かつて退けられたその科学者の気候変動に関する予言的な警告は、今や驚くほど正確であることが証明された。',
  'In retrospect, the economist''s prophetic analysis of the housing market foreshadowed the financial crisis.',
  '振り返ってみれば、その経済学者の住宅市場に関する予言的な分析は金融危機を予兆していた。'),
(1650, 'inclement', '〈天候が〉荒れ模様の、厳寒の', '/ɪnˈklemənt/', 'インクレメント',
  'The outdoor ceremony was postponed indefinitely due to the inclement weather that swept across the region.',
  '地域一帯を襲った荒れ模様の天候のため、屋外の式典は無期限に延期された。',
  'Despite the inclement conditions, the rescue team pressed on through the blizzard to reach the stranded hikers.',
  '厳寒の状況にもかかわらず、救助チームは立ち往生したハイカーたちに到達するために吹雪の中を前進し続けた。');
