-- words テーブル INSERT文 (No.1651 ~ No.1700)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1651, 'lure', '~を誘い出す、誘い込む', '/lʊr/', 'ルアー',
  'The promise of lucrative salaries lured many talented engineers away from academia.',
  '高い報酬の約束が多くの優秀なエンジニアを学界から誘い出した。',
  'Fraudsters used fake investment opportunities to lure unsuspecting victims into parting with their savings.',
  '詐欺師たちは偽の投資機会を使って無防備な被害者を誘い込み、貯蓄を手放させた。'),
(1652, 'warden', '監視員、管理人', '/ˈwɔːrdən/', 'ウォーデン',
  'The park warden issued a stern warning to hikers who strayed from the designated trails.',
  '公園の監視員は指定された遊歩道から外れたハイカーたちに厳しい警告を発した。',
  'The warden of the historic estate ensured that the grounds were meticulously maintained throughout the year.',
  '歴史的な邸宅の管理人は敷地が年間を通じて細心の注意を払って維持されるよう努めた。'),
(1653, 'statutory', '法定の、法令の', '/ˈstætʃətɔːri/', 'スタチュトリー',
  'Employers are legally obligated to provide statutory maternity leave to eligible employees.',
  '雇用主は資格のある従業員に法定の産休を提供する法的義務がある。',
  'The statutory framework governing data protection was overhauled to address emerging cybersecurity threats.',
  'データ保護を規定する法令の枠組みは、新たなサイバーセキュリティの脅威に対処するために全面的に見直された。'),
(1654, 'bicker', '(ささいなことで)口論する', '/ˈbɪkər/', 'ビカー',
  'The siblings bickered incessantly over trivial matters, much to the exasperation of their parents.',
  '兄弟はささいなことで絶え間なく口論し、両親をひどくいらだたせた。',
  'Rather than bickering over minor procedural details, the committee should focus on substantive policy reforms.',
  '些末な手続き上の詳細について口論するのではなく、委員会は実質的な政策改革に集中すべきだ。'),
(1655, 'torrid', '〈恋愛感情などが〉情熱的な、熱烈な;〈地域・気候が〉灼熱の、からからに乾いた', '/ˈtɔːrɪd/', 'トリッド',
  'The novel chronicles the torrid love affair between a renowned painter and his enigmatic muse.',
  'その小説は著名な画家と彼の謎めいたミューズとの情熱的な恋愛を年代順に描いている。',
  'Crops withered under the torrid sun as the region endured its worst drought in decades.',
  'この地域が数十年で最悪の干ばつに耐える中、灼熱の太陽の下で作物は枯れた。'),
(1656, 'swill', '~をがぶがぶ飲む;~を洗い流す', '/swɪl/', 'スウィル',
  'The rowdy patrons swilled cheap beer throughout the evening, growing louder with each passing hour.',
  '騒々しい常連客は一晩中安いビールをがぶがぶ飲み、時間が経つにつれてますます騒がしくなった。',
  'She swilled out the bucket with clean water before using it to collect rainwater for the garden.',
  '彼女は庭の雨水を集めるためにバケツを使う前に、きれいな水でそれを洗い流した。'),
(1658, 'dilate', '〈体の器官〉を広げる、拡張する;〈体の器官が〉広がる、拡張する', '/daɪˈleɪt/', 'ダイレイト',
  'The ophthalmologist used special drops to dilate the patient''s pupils before conducting the examination.',
  '眼科医は検査を行う前に特別な点眼薬を使って患者の瞳孔を拡張した。',
  'Blood vessels dilate in response to heat, which is why the skin appears flushed during vigorous exercise.',
  '血管は熱に反応して拡張するため、激しい運動中に肌が紅潮して見える。'),
(1659, 'expiate', '〈罪など〉を償う', '/ˈekspiˌeɪt/', 'エクスピエイト',
  'The convict devoted the remainder of his life to charitable work in an attempt to expiate his crimes.',
  'その受刑者は自分の罪を償おうとして、残りの人生を慈善活動に捧げた。',
  'No amount of public apology could fully expiate the damage inflicted upon the victims and their families.',
  'いかなる公式謝罪も、被害者とその家族に与えた損害を完全に償うことはできなかった。'),
(1660, 'inane', 'ばかげた、無意味な', '/ɪˈneɪn/', 'イネイン',
  'The critic dismissed the film as inane, noting its utter lack of substance or originality.',
  '批評家はその映画をばかげたものとして退け、内容や独創性の完全な欠如を指摘した。',
  'His inane remarks during the board meeting undermined his credibility among senior executives.',
  '取締役会での彼の無意味な発言は上級幹部の間での彼の信頼性を損なった。'),
(1661, 'acolyte', '部下、助手、取り巻き', '/ˈækəlaɪt/', 'アコライト',
  'The senator was invariably surrounded by a retinue of loyal acolytes who echoed his every opinion.',
  'その上院議員は常に彼のあらゆる意見に同調する忠実な取り巻きの一団に囲まれていた。',
  'As a young acolyte of the renowned architect, she absorbed invaluable lessons in design and craftsmanship.',
  '著名な建築家の若い助手として、彼女はデザインと職人技における貴重な教訓を吸収した。'),
(1662, 'chivalrous', '〈男性が〉勇敢な、〈女性に〉親切な;騎士道の', '/ˈʃɪvəlrəs/', 'シヴァルラス',
  'His chivalrous gesture of offering his coat to the shivering stranger earned him admiration from onlookers.',
  '震えている見知らぬ人に上着を差し出す彼の勇敢な行為は、見物人から賞賛を得た。',
  'The novel romanticizes a bygone era in which chivalrous knights defended the honor of the realm.',
  'その小説は騎士道の騎士たちが王国の名誉を守った過ぎ去った時代をロマンチックに描いている。'),
(1663, 'diffuse', '〈光・熱・においなど〉を拡散する、放散する;〈知識・情報など〉を普及させる', '/dɪˈfjuːz/', 'ディフューズ',
  'The organization sought to diffuse knowledge of sustainable agricultural practices across developing nations.',
  'その組織は持続可能な農業慣行の知識を発展途上国全体に普及させようとした。',
  'Frosted glass panels were installed to diffuse the harsh sunlight entering the office space.',
  '事務所に差し込む強い日差しを拡散するために、すりガラスのパネルが設置された。'),
(1664, 'intractable', '〈問題などが〉解決困難な、手に負えない;〈病気が〉治りにくい', '/ɪnˈtræktəbl/', 'イントラクタブル',
  'The refugee crisis has proven to be one of the most intractable challenges facing the international community.',
  '難民危機は国際社会が直面する最も解決困難な課題の一つであることが証明された。',
  'The patient suffered from intractable migraines that failed to respond to conventional treatments.',
  'その患者は従来の治療法に反応しない治りにくい偏頭痛に苦しんでいた。'),
(1665, 'fathom', '〈不可解なことなど〉を理解する、推測する', '/ˈfæðəm/', 'ファゾム',
  'Analysts struggled to fathom the rationale behind the central bank''s unexpected decision to raise interest rates.',
  'アナリストたちは中央銀行の予想外の利上げ決定の背後にある理論的根拠を理解するのに苦労した。',
  'She could not fathom why her application had been rejected despite meeting all the stated criteria.',
  '彼女はすべての記載された基準を満たしているにもかかわらず、なぜ申請が却下されたのか理解できなかった。'),
(1666, 'squint', '目を凝らす、目を細めて見る', '/skwɪnt/', 'スクウィント',
  'He squinted at the faded inscription on the ancient tombstone, trying to decipher the weathered letters.',
  '彼は古い墓石のかすれた碑文に目を凝らし、風化した文字を解読しようとした。',
  'The bright stage lights forced the speaker to squint as she addressed the vast audience.',
  '明るい舞台照明のせいで講演者は大勢の聴衆に話しかけながら目を細めなければならなかった。'),
(1667, 'confluence', '(複数の出来事の)同時発生;(川などの)合流点', '/ˈkɑːnfluəns/', 'コンフルエンス',
  'The economic crisis was precipitated by a confluence of factors including rising inflation and declining exports.',
  '経済危機はインフレの上昇と輸出の減少を含む複数の要因の同時発生によって引き起こされた。',
  'The city was founded at the confluence of two major rivers, making it a natural hub for trade.',
  'その都市は二つの主要な川の合流点に建設され、貿易の自然な拠点となった。'),
(1668, 'craze', '(一時的な)熱狂、大流行', '/kreɪz/', 'クレイズ',
  'The fitness craze that swept the nation in the 1980s fundamentally transformed attitudes toward personal health.',
  '1980年代に国を席巻したフィットネスの大流行は個人の健康に対する態度を根本的に変えた。',
  'What began as a niche hobby soon became a global craze, attracting millions of enthusiasts worldwide.',
  'ニッチな趣味として始まったものはすぐに世界的な熱狂となり、世界中で数百万人の愛好家を惹きつけた。'),
(1670, 'gripe', '不平、愚痴;(だらだらと)文句を言う', '/ɡraɪp/', 'グライプ',
  'The employees'' principal gripe was the company''s persistent failure to address workplace safety concerns.',
  '従業員の主な不平は、職場の安全上の懸念に対処しないという会社の根強い怠慢だった。',
  'Rather than merely griping about the inadequacies of the system, she proposed a comprehensive reform plan.',
  '制度の不備について単に文句を言うのではなく、彼女は包括的な改革案を提案した。'),
(1671, 'cleave', '(人・思想などに)執着する、忠実である', '/kliːv/', 'クリーヴ',
  'Despite the political upheaval, the community continued to cleave to its traditional values and customs.',
  '政治的動乱にもかかわらず、その共同体は伝統的な価値観と慣習に執着し続けた。',
  'The dissidents cleaved to their principles even under intense pressure from the authoritarian regime.',
  '反体制派は権威主義政権からの激しい圧力の下でも自らの信条に忠実であり続けた。'),
(1672, 'luscious', '〈味・香りが〉とてもよい、甘い', '/ˈlʌʃəs/', 'ラシャス',
  'The luscious aroma of freshly baked pastries wafted through the narrow streets of the old quarter.',
  '焼きたてのペストリーのとてもよい香りが旧市街の狭い通りに漂った。',
  'The chef garnished the dessert with luscious tropical fruits that delighted every guest at the banquet.',
  'シェフはデザートを甘いトロピカルフルーツで飾り、宴会のすべての客を喜ばせた。'),
(1673, 'mirth', 'はしゃぐこと、浮かれ騒ぐこと', '/mɜːrθ/', 'マース',
  'The comedian''s irreverent humor provoked uncontrollable mirth among the audience members.',
  'そのコメディアンの不遜なユーモアは観客の間に抑えられないはしゃぎを引き起こした。',
  'The atmosphere of mirth and celebration pervaded the town square during the annual harvest festival.',
  '毎年恒例の収穫祭の間、浮かれ騒ぎと祝賀の雰囲気が町の広場に満ちていた。'),
(1674, 'caveat', '警告、忠告', '/ˈkæviˌæt/', 'キャヴィアット',
  'The report endorsed the new medication but added the caveat that long-term side effects remained unknown.',
  'その報告書は新薬を支持したが、長期的な副作用は依然として不明であるという警告を付け加えた。',
  'Investors should heed the caveat that past performance does not guarantee future returns.',
  '投資家は過去の実績が将来のリターンを保証するものではないという忠告に留意すべきだ。'),
(1675, 'atonement', '償い、罪滅ぼし', '/əˈtoʊnmənt/', 'アトーンメント',
  'The novel explores the protagonist''s lifelong quest for atonement after a devastating act of betrayal.',
  'その小説は壊滅的な裏切り行為の後の主人公の生涯にわたる償いの探求を描いている。',
  'The government issued a formal apology as an act of atonement for the injustices suffered by indigenous communities.',
  '政府は先住民コミュニティが被った不正義に対する罪滅ぼしの行為として正式な謝罪を発表した。'),
(1676, 'embroider', '〈話など〉を潤色する、脚色する;〈布地など〉に刺繍する', '/ɪmˈbrɔɪdər/', 'エンブロイダー',
  'The witness was accused of embroidering his testimony to make his role in the events seem more heroic.',
  '証人は出来事における自分の役割をより英雄的に見せるために証言を脚色したと非難された。',
  'She spent months embroidering an intricate tapestry depicting scenes from her family''s ancestral history.',
  '彼女は家族の祖先の歴史の場面を描いた精巧なタペストリーを刺繍するのに数ヶ月を費やした。'),
(1677, 'strife', '衝突、紛争', '/straɪf/', 'ストライフ',
  'Decades of civil strife had left the nation''s infrastructure in a state of utter devastation.',
  '数十年にわたる内戦は国のインフラを完全な荒廃状態に置いた。',
  'The mediator''s tireless efforts helped bring an end to the bitter strife between the rival factions.',
  '調停者のたゆまぬ努力は、対立する派閥間の激しい紛争を終わらせるのに役立った。'),
(1678, 'partake', '(活動などに)参加する', '/pɑːrˈteɪk/', 'パーテイク',
  'All delegates were invited to partake in a ceremonial dinner hosted by the ambassador.',
  'すべての代表者は大使が主催する儀式的な夕食会に参加するよう招待された。',
  'Visitors to the cultural festival were encouraged to partake in traditional craft workshops.',
  '文化祭の来場者は伝統的な工芸のワークショップに参加するよう奨励された。'),
(1679, 'juxtapose', '(比較対照のために)~を並べる、並置する', '/ˌdʒʌkstəˈpoʊz/', 'ジャクスタポウズ',
  'The exhibition juxtaposed contemporary artwork with classical masterpieces to highlight evolving aesthetic sensibilities.',
  'その展覧会は現代美術と古典的傑作を並置し、進化する美的感覚を際立たせた。',
  'The documentary juxtaposes scenes of opulent wealth with images of abject poverty to underscore social inequality.',
  'そのドキュメンタリーは豪華な富の場面と悲惨な貧困の映像を並べ、社会的不平等を強調している。'),
(1680, 'fortress', '(大規模な)要塞、城塞', '/ˈfɔːrtrəs/', 'フォートレス',
  'The medieval fortress perched atop the cliff had withstood countless sieges over the centuries.',
  '崖の上にそびえる中世の要塞は何世紀にもわたって無数の包囲戦に耐えてきた。',
  'The regime transformed the island into an impregnable fortress bristling with advanced defense systems.',
  'その政権は島を最先端の防衛システムを備えた難攻不落の城塞に変えた。'),
(1682, 'manipulate', '〈人・世論・価格など〉を操作する、巧みに仕向ける', '/məˈnɪpjəleɪt/', 'マニピュレイト',
  'The corporation was fined for attempting to manipulate commodity prices through coordinated trading strategies.',
  'その企業は協調的な取引戦略を通じて商品価格を操作しようとしたとして罰金を科された。',
  'Propagandists skillfully manipulate public opinion by exploiting fears and amplifying misinformation.',
  'プロパガンダの専門家は恐怖を利用し誤情報を増幅することで巧みに世論を操作する。'),
(1683, 'regime', '政権、政府;政治制度', '/reɪˈʒiːm/', 'レジーム',
  'The oppressive regime suppressed all forms of dissent through censorship and political persecution.',
  '抑圧的な政権は検閲と政治的迫害を通じてあらゆる形態の反対意見を抑圧した。',
  'International sanctions were imposed to pressure the regime into restoring democratic governance.',
  '民主的な統治を回復するよう政権に圧力をかけるために国際制裁が課された。'),
(1684, 'subsequent', 'その後の、それに続く', '/ˈsʌbsɪkwənt/', 'サブシクウェント',
  'The initial findings were corroborated by subsequent research conducted at multiple institutions.',
  '最初の調査結果は複数の機関で実施されたその後の研究によって裏付けられた。',
  'The earthquake and the subsequent tsunami caused unprecedented devastation along the entire coastline.',
  '地震とそれに続く津波は海岸線全体に前例のない壊滅的被害をもたらした。'),
(1685, 'vulnerable', '〈人・感情などが〉傷つきやすい、〈病気などに〉かかりやすい', '/ˈvʌlnərəbl/', 'ヴァルナラブル',
  'Elderly residents living alone are particularly vulnerable to fraudulent schemes targeting their savings.',
  '一人暮らしの高齢者は貯蓄を狙った詐欺的な手口に対して特に傷つきやすい。',
  'The ecosystem is vulnerable to irreversible damage if deforestation continues at the current rate.',
  '現在の速度で森林伐採が続けば、生態系は不可逆的な損害を受けやすい状態にある。'),
(1686, 'indigenous', '(ある土地に)固有の、先住の', '/ɪnˈdɪdʒənəs/', 'インディジェナス',
  'The conservation program aims to protect indigenous species threatened by the introduction of invasive predators.',
  'その保全プログラムは侵略的な捕食者の導入によって脅かされている固有種を保護することを目的としている。',
  'Indigenous communities have long advocated for the recognition of their ancestral land rights.',
  '先住民コミュニティは長い間、祖先の土地の権利の認知を主張してきた。'),
(1687, 'trait', '(性格・身体上の)特徴', '/treɪt/', 'トレイト',
  'Resilience is a character trait that enables individuals to recover swiftly from adversity.',
  '回復力は個人が逆境から迅速に立ち直ることを可能にする性格の特徴である。',
  'Geneticists have identified several hereditary traits that predispose certain populations to specific diseases.',
  '遺伝学者は特定の集団を特定の疾患にかかりやすくするいくつかの遺伝的特徴を特定した。'),
(1688, 'predator', '捕食動物、捕食者', '/ˈpredətər/', 'プレデター',
  'The reintroduction of apex predators into the national park restored balance to the fragile ecosystem.',
  '国立公園への頂点捕食者の再導入は脆弱な生態系のバランスを回復させた。',
  'Smaller fish have evolved elaborate camouflage mechanisms to evade detection by marine predators.',
  '小型の魚は海洋捕食者による検出を逃れるために精巧な擬態のメカニズムを進化させた。'),
(1689, 'ultimately', '結局、最終的に', '/ˈʌltɪmətli/', 'アルティメトリー',
  'Although the negotiations were arduous, the two parties ultimately reached a mutually acceptable compromise.',
  '交渉は困難であったが、両者は最終的に相互に受け入れ可能な妥協に達した。',
  'The success of any educational reform ultimately depends on the dedication and competence of its teachers.',
  'いかなる教育改革の成功も結局はその教師の献身と能力にかかっている。'),
(1690, 'diagnose', '~を診断する;〈故障・異常など〉を突き止める', '/ˌdaɪəɡˈnoʊs/', 'ダイアグノウス',
  'The physician diagnosed the patient with a rare autoimmune disorder after months of inconclusive testing.',
  '医師は数ヶ月にわたる結論の出ない検査の後、患者を稀な自己免疫疾患と診断した。',
  'Technicians were called in to diagnose the persistent malfunction in the factory''s automated assembly line.',
  '工場の自動組立ラインの持続的な故障を突き止めるために技術者が呼ばれた。'),
(1691, 'legitimate', '理にかなった、正当な;合法的な', '/lɪˈdʒɪtɪmət/', 'レジティメト',
  'The court ruled that the employee had a legitimate grievance against the company for wrongful termination.',
  '裁判所はその従業員が不当解雇について会社に対して正当な不満を持っていると判断した。',
  'Critics questioned whether the surveillance program served a legitimate purpose or merely infringed upon civil liberties.',
  '批評家たちは監視プログラムが正当な目的に資するのか、それとも単に市民の自由を侵害しているだけなのかを疑問視した。'),
(1692, 'enhance', '〈質・価値・力など〉を高める、向上させる', '/ɪnˈhæns/', 'エンハンス',
  'The renovation was designed to enhance the building''s energy efficiency while preserving its architectural heritage.',
  'その改修は建築遺産を保存しながら建物のエネルギー効率を高めるよう設計された。',
  'Strategic partnerships with leading universities have significantly enhanced the institute''s research capabilities.',
  '主要大学との戦略的パートナーシップは研究所の研究能力を大幅に向上させた。'),
(1694, 'validity', '妥当性、正当性;(法的な)効力、有効性', '/vəˈlɪdəti/', 'ヴァリディティ',
  'The defense attorney challenged the validity of the forensic evidence presented by the prosecution.',
  '弁護人は検察が提出した法医学的証拠の妥当性に異議を唱えた。',
  'The validity of the contract was called into question after irregularities were discovered in the signing process.',
  '署名手続きに不正が発見された後、契約の有効性が疑問視された。'),
(1695, 'proponent', '(主義・方針などの)擁護者、支持者', '/prəˈpoʊnənt/', 'プロポーネント',
  'Proponents of renewable energy argue that transitioning away from fossil fuels is both economically and environmentally imperative.',
  '再生可能エネルギーの支持者は、化石燃料からの移行は経済的にも環境的にも不可欠であると主張している。',
  'As a staunch proponent of universal healthcare, the senator has consistently voted in favor of expanding coverage.',
  '国民皆保険の確固たる擁護者として、その上院議員は一貫して保険適用の拡大に賛成票を投じてきた。'),
(1696, 'cognitive', '認識の、認識に関する', '/ˈkɑːɡnɪtɪv/', 'コグニティヴ',
  'Recent studies suggest that regular physical exercise can significantly improve cognitive function in older adults.',
  '最近の研究は定期的な運動が高齢者の認知機能を著しく改善できることを示唆している。',
  'The psychologist specializes in cognitive behavioral therapy for patients suffering from chronic anxiety disorders.',
  'その心理学者は慢性的な不安障害に苦しむ患者のための認知行動療法を専門としている。'),
(1697, 'outright', '完全に、全面的に;ずばりと、公然と;即座に', '/ˈaʊtraɪt/', 'アウトライト',
  'The proposal was rejected outright by the committee, which deemed it financially unviable.',
  'その提案は財政的に実行不可能と判断した委員会によって完全に拒否された。',
  'Rather than resorting to outright confrontation, the diplomat pursued a strategy of gradual persuasion.',
  '全面的な対立に訴えるのではなく、その外交官は段階的な説得の戦略を追求した。'),
(1698, 'facilitate', '~を容易にする、促進する', '/fəˈsɪlɪteɪt/', 'ファシリテイト',
  'The new digital platform was developed to facilitate seamless communication between remote teams.',
  '新しいデジタルプラットフォームはリモートチーム間のシームレスなコミュニケーションを促進するために開発された。',
  'International organizations played a crucial role in facilitating the peace negotiations between the warring nations.',
  '国際機関は交戦国間の和平交渉を促進する上で重要な役割を果たした。'),
(1699, 'correlation', '相関関係', '/ˌkɔːrəˈleɪʃən/', 'コレレイション',
  'The study revealed a strong correlation between socioeconomic deprivation and lower educational attainment.',
  'その研究は社会経済的な困窮と低い学業達成度との間の強い相関関係を明らかにした。',
  'Scientists caution that correlation does not imply causation, urging more rigorous experimental investigation.',
  '科学者は相関関係は因果関係を意味しないと警告し、より厳密な実験的調査を促している。'),
(1700, 'underestimate', '(~を)過小評価する、見くびる', '/ˌʌndərˈestɪmeɪt/', 'アンダーエスティメイト',
  'The incumbent party fatally underestimated the opposition''s ability to mobilize disaffected voters.',
  '与党は不満を抱く有権者を動員する野党の能力を致命的に過小評価した。',
  'It would be unwise to underestimate the complexity of implementing such sweeping institutional reforms.',
  'そのような大規模な制度改革を実施する複雑さを見くびるのは賢明ではないだろう。');
