-- words テーブル INSERT文 (No.1701 ~ No.1750)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1701, 'drawback', '(状況・考えなどの)欠点', '/ˈdrɔːbæk/', 'ドローバック',
  'The main drawback of the proposed legislation is that it places an undue burden on small businesses.',
  'その法案の主な欠点は、中小企業に過度な負担を課すことである。',
  'Despite its numerous advantages, the technology has one significant drawback: its prohibitive cost.',
  '数多くの利点にもかかわらず、その技術には一つの重大な欠点がある。それは法外な費用である。'),
(1702, 'skeptical', '懐疑的な、疑っている', '/ˈskeptɪkəl/', 'スケプティカル',
  'Many scientists remain skeptical about the validity of the study''s conclusions due to its small sample size.',
  '多くの科学者はサンプル数が少ないことから、その研究の結論の妥当性について懐疑的なままである。',
  'The public grew increasingly skeptical of the government''s assurances that the economy was recovering.',
  '国民は経済が回復しているという政府の保証に対してますます懐疑的になった。'),
(1703, 'embrace', '〈考え・提案など〉を受け入れる、採用する;(~を)抱擁する', '/ɪmˈbreɪs/', 'エンブレイス',
  'The company decided to embrace a more sustainable business model in response to mounting environmental concerns.',
  '環境への懸念の高まりに応えて、その会社はより持続可能なビジネスモデルを採用することを決定した。',
  'Rather than resist technological change, the veteran journalist chose to embrace digital media wholeheartedly.',
  'ベテランジャーナリストは技術的変化に抵抗するのではなく、デジタルメディアを全面的に受け入れることを選んだ。'),
(1704, 'controversial', '論争を引き起こす、物議をかもす;論争好きな', '/ˌkɑːntrəˈvɜːrʃəl/', 'コントロヴァーシャル',
  'The minister''s controversial remarks about immigration policy ignited a fierce debate in parliament.',
  '移民政策に関する大臣の物議をかもす発言は議会で激しい議論を引き起こした。',
  'The decision to demolish the historic building proved highly controversial among local residents.',
  'その歴史的建造物を取り壊す決定は、地元住民の間で非常に物議をかもすものとなった。'),
(1706, 'extract', '(別の物質から)(物質)を抽出する、採取する;(もの)を取り除く、引き抜く;(情報など)を聞き出す', '/ɪkˈstrækt/', 'エクストラクト',
  'Scientists have developed a novel method to extract rare minerals from seawater with minimal environmental impact.',
  '科学者たちは環境への影響を最小限に抑えながら海水から希少鉱物を抽出する新しい方法を開発した。',
  'The detective managed to extract a crucial confession from the reluctant witness after hours of questioning.',
  '刑事は何時間もの尋問の後、渋る証人から重要な自白を聞き出すことに成功した。'),
(1707, 'implement', '〈計画・政策など〉を実行する、履行する;道具、用具', '/ˈɪmplɪment/', 'インプリメント',
  'The government pledged to implement sweeping reforms to the healthcare system within the next fiscal year.',
  '政府は次の会計年度中に医療制度の抜本的な改革を実行することを約束した。',
  'Without adequate funding, it will be virtually impossible to implement the committee''s ambitious recommendations.',
  '十分な資金がなければ、委員会の野心的な勧告を履行することは事実上不可能であろう。'),
(1708, 'influx', '(人・金・ものなどの)到来、殺到、流入', '/ˈɪnflʌks/', 'インフラックス',
  'The sudden influx of refugees placed enormous pressure on the country''s already strained public services.',
  '難民の突然の流入は、すでに逼迫している公共サービスに多大な圧力をかけた。',
  'The coastal resort experienced an unprecedented influx of tourists following the release of the blockbuster film.',
  'その海岸リゾートは大ヒット映画の公開後、かつてない観光客の殺到を経験した。'),
(1709, 'outweigh', '~より重要である、~に勝る', '/ˌaʊtˈweɪ/', 'アウトウェイ',
  'The committee concluded that the potential benefits of the new drug outweigh the associated risks.',
  '委員会は新薬の潜在的な利益が関連するリスクに勝ると結論づけた。',
  'For many employees, the flexibility of remote work far outweighs the social advantages of being in the office.',
  '多くの従業員にとって、リモートワークの柔軟性はオフィスにいることの社会的利点をはるかに上回る。'),
(1710, 'envision', '〈将来など〉を想像する', '/ɪnˈvɪʒən/', 'エンヴィジョン',
  'The architect envisioned a futuristic cityscape in which green spaces and skyscrapers coexist harmoniously.',
  'その建築家は緑地と超高層ビルが調和して共存する未来的な都市景観を想像した。',
  'Few could have envisioned the rapid transformation that artificial intelligence would bring to the labor market.',
  '人工知能が労働市場にもたらす急速な変革を想像できた人はほとんどいなかっただろう。'),
(1711, 'contend', '① …であると強く主張する ② 競う、争う', '/kənˈtend/', 'コンテンド',
  'The defense attorney contended that the evidence presented by the prosecution was entirely circumstantial.',
  '弁護人は検察が提出した証拠は完全に状況証拠であると強く主張した。',
  'Several multinational corporations are contending for the lucrative government contract.',
  'いくつかの多国籍企業がその有利な政府契約をめぐって競い合っている。'),
(1712, 'pharmaceutical', '製薬の、薬剤の', '/ˌfɑːrməˈsuːtɪkəl/', 'ファーマスーティカル',
  'The pharmaceutical industry has come under scrutiny for its aggressive pricing strategies on life-saving medications.',
  '製薬業界は救命薬に対する強引な価格戦略について厳しい監視を受けている。',
  'A major pharmaceutical company announced a breakthrough in the development of a vaccine for the tropical disease.',
  '大手製薬会社が熱帯病のワクチン開発における画期的な進歩を発表した。'),
(1713, 'migration', '(人・動物などの)移動、移住', '/maɪˈɡreɪʃən/', 'マイグレイション',
  'The annual migration of monarch butterflies across North America is one of nature''s most spectacular phenomena.',
  'オオカバマダラの北米を横断する年に一度の移動は、自然界で最も壮観な現象の一つである。',
  'Mass migration from rural areas to urban centers has accelerated dramatically in developing nations.',
  '農村部から都市部への大規模な移住は発展途上国で劇的に加速している。'),
(1714, 'warfare', '戦争;戦闘', '/ˈwɔːrfer/', 'ウォーフェア',
  'The advent of drone technology has fundamentally altered the nature of modern warfare.',
  'ドローン技術の出現は現代の戦争の本質を根本的に変えた。',
  'Cyber warfare poses an increasingly serious threat to national security and critical infrastructure.',
  'サイバー戦闘は国家安全保障と重要なインフラに対してますます深刻な脅威をもたらしている。'),
(1715, 'livestock', '家畜', '/ˈlaɪvstɑːk/', 'ライヴストック',
  'The prolonged drought devastated the region''s livestock, leaving thousands of farmers without a livelihood.',
  '長引く干ばつはその地域の家畜に壊滅的な被害を与え、何千人もの農民が生計を失った。',
  'Sustainable management of livestock is essential to reducing greenhouse gas emissions from the agricultural sector.',
  '家畜の持続可能な管理は、農業部門からの温室効果ガス排出を削減するために不可欠である。'),
(1716, 'perish', '〈人・動物が〉(突然)死ぬ;滅びる、消滅する', '/ˈperɪʃ/', 'ペリッシュ',
  'Hundreds of villagers perished in the catastrophic earthquake that struck the mountainous province.',
  '山岳地帯の州を襲った壊滅的な地震で何百人もの村民が亡くなった。',
  'Without immediate intervention, the ancient language spoken by this community will perish within a generation.',
  '即座に介入しなければ、この共同体が話す古代の言語は一世代のうちに消滅するだろう。'),
(1718, 'implant', '〈臓器など〉を移植する;(もの)を埋め込む;〈思想など〉を植えつける;移植(片)', '/ɪmˈplænt/', 'インプラント',
  'Surgeons successfully implanted an artificial heart in the patient, granting him several more years of life.',
  '外科医は患者に人工心臓を移植することに成功し、さらに数年の命を与えた。',
  'The propaganda campaign sought to implant a deep distrust of foreign institutions in the public consciousness.',
  'そのプロパガンダ運動は外国の制度に対する深い不信を国民の意識に植えつけようとした。'),
(1719, 'hypothesis', '仮説', '/haɪˈpɑːθəsɪs/', 'ハイポセシス',
  'The researcher''s hypothesis that sleep deprivation impairs cognitive function was supported by the experimental data.',
  '睡眠不足が認知機能を損なうという研究者の仮説は実験データによって裏付けられた。',
  'Before conducting the experiment, the team formulated a clear hypothesis to guide their investigation.',
  '実験を行う前に、チームは調査を導くための明確な仮説を立てた。'),
(1720, 'breakthrough', '飛躍的な進歩、現状突破', '/ˈbreɪkθruː/', 'ブレイクスルー',
  'The discovery of a new catalyst represents a major breakthrough in the quest for clean energy.',
  '新しい触媒の発見はクリーンエネルギーの追求における大きな飛躍的進歩を表している。',
  'After years of stalled negotiations, the diplomatic breakthrough came as a surprise to political analysts.',
  '何年にもわたる交渉の行き詰まりの後、その外交上の現状突破は政治アナリストにとって驚きであった。'),
(1721, 'overly', '過度に、あまりにも', '/ˈoʊvərli/', 'オウヴァリー',
  'Critics warned that the government was being overly optimistic in its economic growth projections.',
  '批評家たちは政府が経済成長の予測において過度に楽観的であると警告した。',
  'An overly cautious approach to investment can result in missed opportunities for substantial returns.',
  '投資に対する過度に慎重なアプローチは、大きなリターンの機会を逃す結果となりうる。'),
(1722, 'inherent', '本来備わっている、生まれつきの', '/ɪnˈhɪrənt/', 'インヒアレント',
  'There is an inherent tension between the pursuit of economic growth and the preservation of the environment.',
  '経済成長の追求と環境保全の間には本来備わっている緊張関係がある。',
  'The judge acknowledged the inherent difficulty of balancing national security with individual civil liberties.',
  '裁判官は国家安全保障と個人の市民的自由のバランスを取ることの本質的な難しさを認めた。'),
(1723, 'roam', '(~を)歩き回る、放浪する', '/roʊm/', 'ロウム',
  'Herds of wild elephants still roam freely across the vast savannas of sub-Saharan Africa.',
  '野生の象の群れは今もサハラ以南のアフリカの広大なサバンナを自由に歩き回っている。',
  'After retiring from his corporate career, he spent two years roaming through Southeast Asia.',
  '企業でのキャリアを引退した後、彼は2年間東南アジアを放浪して過ごした。'),
(1724, 'mandatory', '義務的な、強制的な', '/ˈmændətɔːri/', 'マンダトリー',
  'The new legislation makes it mandatory for all commercial buildings to undergo annual fire safety inspections.',
  '新しい法律はすべての商業ビルに対して年に一度の防火安全点検を受けることを義務的にしている。',
  'Attendance at the ethics training seminar is mandatory for all employees, regardless of seniority.',
  '倫理研修セミナーへの出席は、役職に関係なく全従業員に対して強制的である。'),
(1725, 'accusation', '告発、非難', '/ˌækjuˈzeɪʃən/', 'アキュゼイション',
  'The politician vehemently denied the accusations of corruption leveled against him by the opposition party.',
  'その政治家は野党から向けられた汚職の告発を激しく否定した。',
  'Unfounded accusations can irreparably damage a person''s reputation, even if they are later proven innocent.',
  '根拠のない非難は、たとえ後に無実が証明されても、人の評判を取り返しのつかないほど傷つけることがある。'),
(1726, 'contaminate', '~を汚染する', '/kənˈtæmɪneɪt/', 'コンタミネイト',
  'Industrial waste discharged into the river contaminated the drinking water supply for several downstream communities.',
  '川に排出された産業廃棄物が下流のいくつかの地域の飲料水供給を汚染した。',
  'The laboratory specimens were inadvertently contaminated, rendering the entire experiment invalid.',
  '研究所の試料が不注意により汚染され、実験全体が無効になった。'),
(1727, 'inmate', '(刑務所の)囚人;(精神病棟の)収容者', '/ˈɪnmeɪt/', 'インメイト',
  'The prison reform initiative aims to provide inmates with vocational training to reduce recidivism rates.',
  'その刑務所改革の取り組みは、再犯率を下げるために囚人に職業訓練を提供することを目指している。',
  'Several inmates filed a lawsuit alleging that the facility had violated their constitutional rights.',
  '数人の囚人が、施設が彼らの憲法上の権利を侵害したと主張する訴訟を起こした。'),
(1728, 'dub', '① ~を(…と)呼ぶ ②〈映画などの言語〉を吹き替える', '/dʌb/', 'ダブ',
  'The media dubbed the young prodigy the "Mozart of the twenty-first century" after her debut recital.',
  'メディアはその若い天才をデビューリサイタルの後「21世紀のモーツァルト」と呼んだ。',
  'The foreign film was dubbed into English for its theatrical release in North America.',
  'その外国映画は北米での劇場公開のために英語に吹き替えられた。'),
(1730, 'credibility', '信用、信頼性', '/ˌkredɪˈbɪləti/', 'クレディビリティ',
  'The journalist''s credibility was severely undermined when it emerged that she had fabricated key sources.',
  'その記者が主要な情報源を捏造していたことが発覚し、彼女の信頼性は著しく損なわれた。',
  'Establishing credibility with international investors is paramount for any emerging economy seeking foreign capital.',
  '外国資本を求める新興経済国にとって、国際的な投資家との信用を確立することが最も重要である。'),
(1731, 'toxic', '毒性のある、有毒な', '/ˈtɑːksɪk/', 'トクシック',
  'Prolonged exposure to toxic chemicals in the workplace has been linked to a range of chronic illnesses.',
  '職場での有毒な化学物質への長期的な曝露は、さまざまな慢性疾患と関連づけられている。',
  'The psychologist warned that a toxic work environment can have devastating effects on employees'' mental health.',
  '心理学者は毒性のある職場環境が従業員の精神的健康に壊滅的な影響を及ぼしうると警告した。'),
(1732, 'relevance', '関連(性);(社会的)意味', '/ˈreləvəns/', 'レレヴァンス',
  'The professor questioned the relevance of the student''s argument to the central thesis of the dissertation.',
  '教授はその学生の議論が論文の中心的テーゼとの関連性について疑問を呈した。',
  'In an era of rapid technological change, maintaining the relevance of traditional educational curricula is a challenge.',
  '急速な技術変化の時代において、従来の教育カリキュラムの意味を維持することは課題である。'),
(1733, 'thrive', '〈動植物が〉育つ;繁栄する、成功する', '/θraɪv/', 'スライヴ',
  'Coral reefs thrive in warm, shallow waters where sunlight can penetrate to sustain photosynthetic organisms.',
  'サンゴ礁は太陽光が光合成生物を維持できるほど浸透する温かく浅い海域で育つ。',
  'Small businesses tend to thrive in communities where local consumers actively support independent enterprises.',
  '地元の消費者が独立系企業を積極的に支援する地域では、中小企業が繁栄する傾向がある。'),
(1734, 'underlie', '〈思想・行動など〉の基礎となる、根拠をなす', '/ˌʌndərˈlaɪ/', 'アンダーライ',
  'A deep commitment to social justice underlies all of the organization''s advocacy campaigns.',
  '社会正義への深い献身がその組織のすべての擁護運動の基礎となっている。',
  'The report sought to identify the structural factors that underlie persistent economic inequality.',
  'その報告書は根強い経済的不平等の根拠をなす構造的要因を特定しようとした。'),
(1735, 'sway', '~に影響を与える、〈考え〉を左右する;揺れる、揺れ動く;影響(力)', '/sweɪ/', 'スウェイ',
  'The eloquent barrister managed to sway the jury with a compelling closing argument.',
  '雄弁な法廷弁護士は説得力のある最終弁論で陪審員に影響を与えることに成功した。',
  'Public opinion can be easily swayed by sensationalist media coverage of complex political issues.',
  '世論は複雑な政治問題のセンセーショナルなメディア報道によって容易に左右されうる。'),
(1736, 'delegate', '~を任せる、委託する;〈人〉を(公式の場に)派遣する;代表者', '/ˈdelɪɡeɪt/', 'デレゲイト',
  'Effective leaders understand the importance of learning to delegate responsibilities to trusted subordinates.',
  '有能なリーダーは信頼できる部下に責任を委託することを学ぶ重要性を理解している。',
  'Each member state was invited to send a delegate to the international summit on climate change.',
  '各加盟国は気候変動に関する国際サミットに代表者を派遣するよう招かれた。'),
(1737, 'foresee', '〈問題・事故など〉を予知する;~を予見する', '/fɔːrˈsiː/', 'フォーシー',
  'Few analysts could have foreseen the dramatic collapse of the global financial markets in such a short span.',
  'これほど短期間での世界金融市場の劇的な崩壊を予見できたアナリストはほとんどいなかっただろう。',
  'The engineers failed to foresee the structural vulnerabilities that ultimately led to the bridge''s collapse.',
  '技術者たちは最終的に橋の崩壊につながった構造的脆弱性を予知することができなかった。'),
(1738, 'reinforce', '~を強化する、強固にする', '/ˌriːɪnˈfɔːrs/', 'リインフォース',
  'The government deployed additional troops to reinforce the border defenses amid escalating tensions.',
  '政府は緊張の高まりの中、国境防衛を強化するために追加部隊を配備した。',
  'The findings of the latest study reinforce the widely held view that exercise is beneficial for mental health.',
  '最新の研究結果は、運動が精神的健康に有益であるという広く支持されている見解を強固にするものである。'),
(1739, 'assault', '〈人〉を襲う、〈人〉に暴行する;暴行', '/əˈsɔːlt/', 'アソールト',
  'The defendant was charged with assault after attacking a security guard outside the nightclub.',
  '被告はナイトクラブの外で警備員を襲った後、暴行罪で起訴された。',
  'The humanitarian organization condemned the assault on the refugee camp as a flagrant violation of international law.',
  '人道支援団体は難民キャンプへの暴行を国際法の明白な違反として非難した。'),
(1740, 'inject', '〈薬など〉を注射する、注入する', '/ɪnˈdʒekt/', 'インジェクト',
  'The central bank decided to inject billions of dollars into the economy to stave off a looming recession.',
  '中央銀行は迫りくる景気後退を食い止めるために数十億ドルを経済に注入することを決定した。',
  'The nurse carefully injected the vaccine into the patient''s upper arm.',
  '看護師は患者の上腕にワクチンを慎重に注射した。'),
(1742, 'disrupt', '〈会合・制度・交通など〉を混乱させる、中断させる', '/dɪsˈrʌpt/', 'ディスラプト',
  'The unprecedented snowstorm disrupted air travel across the entire northeastern corridor for three consecutive days.',
  '前例のない暴風雪が北東回廊全体の航空交通を3日間連続で混乱させた。',
  'Protesters attempted to disrupt the parliamentary session by chanting slogans from the public gallery.',
  '抗議者たちは傍聴席からスローガンを叫んで議会を中断させようとした。'),
(1743, 'quota', '(生産・販売などの)分担、ノルマ', '/ˈkwoʊtə/', 'クォウタ',
  'The fishing industry is subject to strict quotas designed to prevent the depletion of marine stocks.',
  '漁業は海洋資源の枯渇を防ぐために設けられた厳格なノルマの対象となっている。',
  'Several countries have introduced gender quotas for corporate boards to promote greater workplace diversity.',
  'いくつかの国は職場の多様性を促進するために企業の取締役会に性別の分担を導入している。'),
(1744, 'forefront', '(活動などの)最前線', '/ˈfɔːrfrʌnt/', 'フォーフラント',
  'Japan has long been at the forefront of robotics research and development.',
  '日本は長年にわたりロボット工学の研究開発の最前線にいる。',
  'The issue of data privacy has moved to the forefront of public discourse in the digital age.',
  'データプライバシーの問題はデジタル時代において公の議論の最前線に移っている。'),
(1745, 'uprising', '反乱、暴動', '/ˈʌpraɪzɪŋ/', 'アップライジング',
  'The popular uprising against the authoritarian regime was brutally suppressed by the military.',
  '権威主義体制に対する民衆の反乱は軍によって残忍に鎮圧された。',
  'Historians regard the peasant uprising of 1381 as a pivotal moment in the struggle for social equality.',
  '歴史家たちは1381年の農民反乱を社会的平等のための闘争における重要な転換点とみなしている。'),
(1746, 'constitutional', '憲法の、合憲の', '/ˌkɑːnstɪˈtuːʃənəl/', 'コンスティテューショナル',
  'The supreme court ruled that the surveillance program was not constitutional and ordered its immediate suspension.',
  '最高裁判所はその監視プログラムが合憲ではないと判決を下し、即座の中止を命じた。',
  'A constitutional amendment requires the approval of two-thirds of both houses of parliament.',
  '憲法改正には両院の3分の2の承認が必要である。'),
(1747, 'specimen', '標本、サンプル', '/ˈspesɪmən/', 'スペシメン',
  'The museum''s collection includes rare botanical specimens gathered from expeditions spanning three centuries.',
  'その博物館のコレクションには3世紀にわたる探検で収集された珍しい植物標本が含まれている。',
  'Laboratory technicians analyzed the blood specimen to determine whether the patient had been exposed to the pathogen.',
  '検査技師は患者がその病原体に曝露されたかどうかを判定するために血液サンプルを分析した。'),
(1748, 'displace', '〈人・動物など〉を立ち退かせる、追い出す', '/dɪsˈpleɪs/', 'ディスプレイス',
  'The construction of the massive dam displaced thousands of families from their ancestral homelands.',
  '巨大なダムの建設は何千もの家族を先祖代々の故郷から立ち退かせた。',
  'Automation threatens to displace workers in industries that have traditionally relied on manual labor.',
  '自動化は従来手作業に依存してきた産業の労働者を追い出す恐れがある。'),
(1749, 'mortgage', '① 住宅ローン ② 抵当、担保', '/ˈmɔːrɡɪdʒ/', 'モーゲージ',
  'Rising interest rates have made it increasingly difficult for young couples to secure an affordable mortgage.',
  '金利の上昇により、若い夫婦が手頃な住宅ローンを確保することがますます困難になっている。',
  'The bank refused to approve the mortgage application because the applicant''s credit score was too low.',
  '申請者の信用スコアが低すぎたため、銀行は住宅ローンの申請を承認することを拒否した。'),
(1750, 'socioeconomic', '社会経済的な', '/ˌsoʊsioʊˌiːkəˈnɑːmɪk/', 'ソウシオウエコノミック',
  'The study revealed a strong correlation between socioeconomic status and access to quality healthcare.',
  'その研究は社会経済的地位と質の高い医療へのアクセスとの間に強い相関関係があることを明らかにした。',
  'Addressing the socioeconomic disparities that persist in urban areas requires a comprehensive policy framework.',
  '都市部に根強く残る社会経済的格差に対処するには、包括的な政策の枠組みが必要である。');
