-- words テーブル INSERT文 (No.1751 ~ No.1800)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1751, 'livelihood', '生計、生活手段', '/ˈlaɪvlihʊd/', 'ライヴリフッド',
  'The prolonged drought threatened the livelihood of thousands of farmers in the region.',
  '長引く干ばつはその地域の何千人もの農家の生計を脅かした。',
  'Many artisans have seen their traditional livelihood eroded by the rise of mass production.',
  '多くの職人が大量生産の台頭によって伝統的な生活手段が侵食されるのを目の当たりにしてきた。'),
(1752, 'intensify', '~を強める、激しくする', '/ɪnˈtensɪfaɪ/', 'インテンシファイ',
  'The government decided to intensify its efforts to combat cybercrime in the financial sector.',
  '政府は金融部門におけるサイバー犯罪と闘う取り組みを強めることを決定した。',
  'As the hurricane approached the coast, the winds intensified to a dangerous degree.',
  'ハリケーンが海岸に近づくにつれて、風は危険な程度まで激しくなった。'),
(1754, 'induce', '~を引き起こす、誘発する;〈人〉に勧めて~させる', '/ɪnˈdjuːs/', 'インデュース',
  'The new tax policy was designed to induce companies to invest in renewable energy sources.',
  '新しい税制政策は企業に再生可能エネルギー源への投資を促すよう設計された。',
  'Prolonged exposure to extreme stress can induce a range of serious psychological disorders.',
  '極度のストレスへの長期間の曝露はさまざまな深刻な心理的障害を引き起こしうる。'),
(1755, 'surpass', '~に勝る、~を超える', '/sərˈpæs/', 'サーパス',
  'The young pianist''s virtuosity was said to surpass that of many established professionals.',
  'その若いピアニストの妙技は多くの著名な専門家のそれを超えると言われた。',
  'Annual exports surpassed the one-trillion-dollar mark for the first time in the nation''s history.',
  '年間輸出額が国の歴史上初めて1兆ドルの大台を超えた。'),
(1756, 'irrational', '不合理な、ばかげた', '/ɪˈræʃənl/', 'イラショナル',
  'The committee dismissed the proposal as irrational, citing its complete lack of empirical evidence.',
  '委員会はその提案を経験的根拠の完全な欠如を理由に不合理であると退けた。',
  'His irrational fear of flying prevented him from attending the international conference in person.',
  '飛行機に対する彼の不合理な恐怖が、国際会議に直接出席することを妨げた。'),
(1757, 'infamous', '悪名高い', '/ˈɪnfəməs/', 'インファマス',
  'The dictator became infamous for his brutal suppression of political dissent.',
  'その独裁者は政治的反対意見の残忍な弾圧で悪名高くなった。',
  'The infamous scandal brought down the entire cabinet and led to early elections.',
  'その悪名高いスキャンダルは内閣全体を崩壊させ、早期選挙につながった。'),
(1758, 'outrage', '激怒;〈人〉を激怒させる', '/ˈaʊtreɪdʒ/', 'アウトレイジ',
  'The court''s controversial verdict sparked outrage among civil rights advocates across the country.',
  '裁判所の物議を醸す判決は全国の公民権擁護者の間で激怒を引き起こした。',
  'Citizens were outraged by the revelation that public funds had been embezzled by senior officials.',
  '公的資金が高官によって横領されていたという暴露に市民は激怒した。'),
(1759, 'overthrow', '〈政府など〉を転覆させる', '/ˌoʊvərˈθroʊ/', 'オウヴァースロウ',
  'The revolutionaries plotted to overthrow the authoritarian regime and establish a democratic government.',
  '革命家たちは権威主義体制を転覆させ、民主的な政府を樹立することを企てた。',
  'The military coup that overthrew the elected president plunged the country into prolonged instability.',
  '選挙で選ばれた大統領を転覆させた軍事クーデターはその国を長期的な不安定状態に陥れた。'),
(1760, 'spur', '~を促進する、刺激する;~に拍車をかける;動機づけるもの、拍車', '/spɜːr/', 'スパー',
  'The discovery of vast oil reserves spurred unprecedented economic development in the region.',
  '広大な石油埋蔵量の発見はその地域に前例のない経済発展を促進した。',
  'Competition from overseas manufacturers acted as a spur for domestic companies to innovate.',
  '海外メーカーからの競争は国内企業が革新するための刺激として作用した。'),
(1761, 'overstate', '~を大げさに話す、誇張する', '/ˌoʊvərˈsteɪt/', 'オウヴァーステイト',
  'Critics accused the pharmaceutical company of overstating the efficacy of its new drug.',
  '批評家たちは製薬会社が新薬の有効性を誇張していると非難した。',
  'It would be difficult to overstate the significance of this archaeological discovery.',
  'この考古学的発見の重要性をいくら強調しても足りないだろう。'),
(1762, 'dilemma', 'ジレンマ、板ばさみ', '/dɪˈlemə/', 'ディレマ',
  'The physician faced an ethical dilemma when the patient''s family requested that treatment be withdrawn.',
  '患者の家族が治療の中止を要請したとき、医師は倫理的なジレンマに直面した。',
  'Many developing nations confront the dilemma of balancing economic growth with environmental conservation.',
  '多くの発展途上国が経済成長と環境保全のバランスというジレンマに直面している。'),
(1763, 'ravage', '〈国家・経済など〉を破壊する、荒廃させる;荒廃、惨害', '/ˈrævɪdʒ/', 'ラヴィジ',
  'The prolonged civil war ravaged the nation''s infrastructure and displaced millions of civilians.',
  '長引く内戦はその国のインフラを破壊し、何百万人もの民間人を避難させた。',
  'Historians documented the ravages of the plague that swept across medieval Europe.',
  '歴史家たちは中世ヨーロッパを席巻した疫病の惨害を記録した。'),
(1764, 'viable', '実行可能な、成功の見込める', '/ˈvaɪəbl/', 'ヴァイアブル',
  'After extensive market research, the team concluded that the venture was commercially viable.',
  '広範な市場調査の後、チームはその事業が商業的に実行可能であると結論づけた。',
  'Solar energy has emerged as a viable alternative to fossil fuels in many parts of the world.',
  '太陽エネルギーは世界の多くの地域で化石燃料に代わる実行可能な選択肢として台頭してきた。'),
(1766, 'uphold', '〈法・制度・主義など〉を守る', '/ʌpˈhoʊld/', 'アップホウルド',
  'The Supreme Court voted to uphold the constitutionality of the newly enacted legislation.',
  '最高裁判所は新たに制定された法律の合憲性を守る判決を下した。',
  'It is the duty of every citizen to uphold the democratic values upon which the nation was founded.',
  '国家が建国された民主主義的価値観を守ることはすべての市民の義務である。'),
(1767, 'simplistic', '単純すぎる', '/sɪmˈplɪstɪk/', 'シンプリスティック',
  'The minister''s simplistic explanation of the economic crisis failed to address its structural causes.',
  '大臣の経済危機に対する単純すぎる説明はその構造的原因に対処できなかった。',
  'Reducing the conflict to a simplistic narrative of good versus evil ignores the complex historical context.',
  '紛争を善対悪という単純すぎる物語に還元することは複雑な歴史的文脈を無視している。'),
(1768, 'intake', '(食べ物などの)摂取(量)', '/ˈɪnteɪk/', 'インテイク',
  'Nutritionists recommend reducing one''s daily sodium intake to lower the risk of hypertension.',
  '栄養士は高血圧のリスクを下げるために一日のナトリウム摂取量を減らすことを推奨している。',
  'The university announced plans to increase its annual intake of international students by twenty percent.',
  'その大学は留学生の年間受け入れ数を20パーセント増やす計画を発表した。'),
(1769, 'tremendous', '(数量・程度などが)非常に大きい;素晴らしい', '/trɪˈmendəs/', 'トゥリメンダス',
  'The charitable organization has made a tremendous impact on reducing child poverty in the region.',
  'その慈善団体はその地域の子供の貧困削減に非常に大きな影響を与えてきた。',
  'The team put in a tremendous effort to meet the deadline despite numerous setbacks.',
  'チームは数々の障害にもかかわらず、締め切りに間に合わせるために素晴らしい努力を注いだ。'),
(1770, 'indispensable', '不可欠な、欠くことのできない', '/ˌɪndɪˈspensəbl/', 'インディスペンサブル',
  'Clean water and sanitation are indispensable to maintaining public health in any community.',
  '清潔な水と衛生設備はどの地域社会においても公衆衛生を維持するために不可欠である。',
  'Her expertise in international law proved indispensable during the treaty negotiations.',
  '国際法における彼女の専門知識は条約交渉中に欠くことのできないものであると証明された。'),
(1771, 'divert', '~の方向[進路]を変える;(資金・資源など)を転用する;(注意など)をそらす', '/daɪˈvɜːrt/', 'ダイヴァート',
  'Authorities decided to divert traffic away from the city center during the state visit.',
  '当局は国賓訪問中に交通を都心から迂回させることを決定した。',
  'The government was criticized for diverting funds originally allocated for education to military expenditure.',
  '政府は元々教育に割り当てられていた資金を軍事費に転用したことで批判された。'),
(1772, 'projection', '(既存の情報に基づく)予測、見積もり;投射、映写', '/prəˈdʒekʃən/', 'プロジェクション',
  'Financial analysts revised their projections for the company''s annual revenue upward by fifteen percent.',
  '金融アナリストはその会社の年間収益の予測を15パーセント上方修正した。',
  'The projection of demographic trends suggests an aging population will pose significant fiscal challenges.',
  '人口動態のトレンドの予測は、高齢化する人口が重大な財政的課題をもたらすことを示唆している。'),
(1773, 'subordinate', '下位の人、部下;下位の、位が低い', '/səˈbɔːrdɪnət/', 'サボーディネット',
  'An effective leader delegates responsibility to subordinates while maintaining overall accountability.',
  '有能なリーダーは全体的な責任を維持しながら部下に責任を委譲する。',
  'The court ruled that individual privacy rights should not be subordinate to commercial interests.',
  '裁判所は個人のプライバシー権が商業的利益に対して下位に置かれるべきではないと判決した。'),
(1774, 'necessitate', '~を必要とする、余儀なくさせる', '/nəˈsesɪteɪt/', 'ネセシテイト',
  'The rapid spread of the epidemic necessitated the immediate closure of all public schools.',
  '疫病の急速な拡大はすべての公立学校の即時閉鎖を余儀なくさせた。',
  'Structural damage to the bridge necessitated a complete reconstruction rather than mere repairs.',
  '橋の構造的損傷は単なる修理ではなく全面的な再建を必要とした。'),
(1775, 'revolt', '(体制・政府などに対する)反乱、暴動;反乱を起こす;〈人〉を不快にする', '/rɪˈvoʊlt/', 'リヴォルト',
  'The peasants'' revolt against oppressive taxation eventually led to sweeping legislative reforms.',
  '抑圧的な課税に対する農民の反乱はやがて広範な立法改革につながった。',
  'Citizens revolted against the authoritarian decree that curtailed their fundamental freedoms.',
  '市民は基本的自由を制限する権威主義的な法令に対して反乱を起こした。'),
(1776, 'infectious', '〈病気が〉伝染性の、(空気)感染する;〈感情などが〉うつりやすい、すぐに伝わる', '/ɪnˈfekʃəs/', 'インフェクシャス',
  'The hospital implemented strict quarantine protocols to contain the outbreak of the infectious disease.',
  '病院は伝染性の病気の流行を封じ込めるために厳格な隔離手順を実施した。',
  'Her infectious enthusiasm for the project inspired even the most skeptical members of the team.',
  'プロジェクトに対する彼女のうつりやすい熱意はチームの最も懐疑的なメンバーさえも奮い立たせた。'),
(1778, 'oppress', '〈人・集団〉を虐げる、圧迫する', '/əˈpres/', 'オプレス',
  'The regime continued to oppress ethnic minorities through discriminatory legislation and forced displacement.',
  'その政権は差別的な法律と強制的な移住を通じて少数民族を虐げ続けた。',
  'Throughout history, those who have sought to oppress others have ultimately faced resistance and downfall.',
  '歴史を通じて、他者を圧迫しようとした者は最終的に抵抗と没落に直面してきた。'),
(1779, 'disposal', '処分、処理', '/dɪˈspoʊzl/', 'ディスポウザル',
  'The improper disposal of hazardous waste poses a grave threat to both public health and the environment.',
  '有害廃棄物の不適切な処理は公衆衛生と環境の両方に重大な脅威をもたらす。',
  'The city council allocated additional funds for the safe disposal of electronic waste.',
  '市議会は電子廃棄物の安全な処分のために追加資金を割り当てた。'),
(1780, 'overrun', '(場所)を制圧する、侵略する;[be overrun](望ましくないもので)いっぱいになる;〈予算など〉を超過する', '/ˌoʊvərˈrʌn/', 'オウヴァーラン',
  'The abandoned estate was completely overrun with invasive plant species within a few years.',
  'その放棄された屋敷は数年のうちに侵略的な植物種で完全にいっぱいになった。',
  'Construction costs overran the original budget by nearly forty percent, prompting a government inquiry.',
  '建設費は当初の予算をほぼ40パーセント超過し、政府の調査を促した。'),
(1781, 'recipient', '受け手、受益者', '/rɪˈsɪpiənt/', 'リシピエント',
  'The recipient of the prestigious literary award delivered a powerful speech on the role of fiction in society.',
  'その名誉ある文学賞の受賞者は社会における小説の役割について力強い演説を行った。',
  'Aid organizations must ensure that recipients of humanitarian assistance are treated with dignity.',
  '援助機関は人道支援の受益者が尊厳をもって扱われることを保証しなければならない。'),
(1782, 'societal', '社会の、社会に関する', '/səˈsaɪətl/', 'ソサイエトル',
  'The rapid advancement of artificial intelligence has raised profound societal questions about employment.',
  '人工知能の急速な進歩は雇用に関する深遠な社会的問題を提起してきた。',
  'Addressing societal inequality requires a multifaceted approach encompassing education, healthcare, and housing.',
  '社会的不平等に対処するには、教育、医療、住宅を包括する多面的なアプローチが必要である。'),
(1783, 'rebellious', '〈人・態度が〉言うことを聞かない、反抗的な;反乱を起こした', '/rɪˈbeljəs/', 'リベリアス',
  'The rebellious teenager refused to comply with the school''s strict dress code.',
  '反抗的なティーンエイジャーは学校の厳しい服装規定に従うことを拒否した。',
  'The government dispatched troops to quell the rebellious factions in the northern provinces.',
  '政府は北部の州で反乱を起こした派閥を鎮圧するために軍隊を派遣した。'),
(1784, 'niche', '(市場の)すき間、ニッチ', '/niːʃ/', 'ニーシュ',
  'The startup carved out a profitable niche in the market by catering to environmentally conscious consumers.',
  'そのスタートアップは環境意識の高い消費者に対応することで市場に収益性の高いニッチを開拓した。',
  'Rare orchid species often occupy a very narrow ecological niche, making them vulnerable to habitat loss.',
  '希少なラン種はしばしば非常に狭い生態学的ニッチを占めており、生息地の喪失に対して脆弱である。'),
(1785, 'devastate', '〈国・地域など〉を荒廃させる、壊滅させる', '/ˈdevəsteɪt/', 'デヴァステイト',
  'The unprecedented earthquake devastated the coastal city, leaving tens of thousands homeless.',
  '前例のない地震が沿岸都市を壊滅させ、数万人を家を失わせた。',
  'The closure of the factory devastated the local economy, which had depended on it for decades.',
  '工場の閉鎖は何十年もそれに依存してきた地域経済を荒廃させた。'),
(1786, 'prestige', '名声、威信', '/preˈstiːʒ/', 'プレスティージュ',
  'The university has maintained its prestige through centuries of academic excellence and groundbreaking research.',
  'その大学は何世紀にもわたる学問的卓越性と画期的な研究を通じて名声を維持してきた。',
  'Winning the international competition considerably enhanced the orchestra''s prestige on the global stage.',
  '国際コンクールでの優勝は世界の舞台におけるそのオーケストラの威信を大いに高めた。'),
(1787, 'brutality', '残忍さ、野蛮;残虐行為、蛮行', '/bruːˈtæləti/', 'ブルータリティ',
  'The documentary exposed the brutality inflicted upon prisoners of war during the conflict.',
  'そのドキュメンタリーは紛争中に捕虜に加えられた残虐行為を暴露した。',
  'International organizations condemned the brutality of the crackdown on peaceful demonstrators.',
  '国際機関は平和的なデモ参加者に対する弾圧の残忍さを非難した。'),
(1788, 'casualty', '(事故・戦闘などの)死傷者;被害者、犠牲者', '/ˈkæʒuəlti/', 'キャジュアルティ',
  'The earthquake resulted in over a thousand casualties and left critical infrastructure in ruins.',
  'その地震は1000人以上の死傷者を出し、重要なインフラを廃墟と化した。',
  'Small independent bookshops have become casualties of the shift toward online retail.',
  '小規模な独立系書店はオンライン小売への移行の犠牲者となってきた。'),
(1790, 'coalition', '(国・政党などの)連立、連合、(団体の)連携', '/ˌkoʊəˈlɪʃən/', 'コウアリション',
  'The two parties formed a coalition government after neither secured an outright majority in the election.',
  'どちらの党も選挙で過半数を獲得できなかったため、二党は連立政府を樹立した。',
  'A broad coalition of environmental groups launched a campaign to preserve the endangered wetlands.',
  '環境保護団体の広範な連携が絶滅の危機に瀕する湿地を保全するキャンペーンを開始した。'),
(1791, 'confinement', '監禁(状態)', '/kənˈfaɪnmənt/', 'コンファインメント',
  'The prisoner endured years of solitary confinement before his case was finally reviewed by a higher court.',
  'その囚人は上級裁判所が彼の事件を再審するまで何年もの独房監禁に耐えた。',
  'The prolonged confinement during the pandemic had a detrimental effect on many people''s mental health.',
  'パンデミック中の長期にわたる閉じ込め状態は多くの人々の精神的健康に有害な影響を及ぼした。'),
(1792, 'microscopic', '微小な、微細な;顕微鏡による', '/ˌmaɪkrəˈskɒpɪk/', 'マイクロスコピック',
  'The forensic team discovered microscopic traces of the substance that proved crucial to the investigation.',
  '法医学チームは調査に決定的に重要であることが証明された物質の微小な痕跡を発見した。',
  'Microscopic analysis of the tissue sample revealed the presence of previously undetected pathogens.',
  '組織サンプルの顕微鏡による分析は、以前検出されなかった病原体の存在を明らかにした。'),
(1793, 'neutrality', '中立、中立的立場', '/njuːˈtræləti/', 'ニュートラリティ',
  'The small nation declared its neutrality at the outbreak of the war, refusing to align with either side.',
  'その小国は戦争の勃発時に中立を宣言し、どちらの側にもつくことを拒否した。',
  'The mediator''s strict neutrality was essential to gaining the trust of both disputing parties.',
  '調停者の厳格な中立的立場は紛争当事者双方の信頼を得るために不可欠だった。'),
(1794, 'evacuate', '(〈場所〉から)避難する、立ち退く;〈人〉を避難させる', '/ɪˈvækjueɪt/', 'イヴァキュエイト',
  'Authorities ordered residents to evacuate the coastal areas immediately as the typhoon approached.',
  '台風の接近に伴い、当局は沿岸地域の住民に直ちに避難するよう命じた。',
  'Rescue teams worked around the clock to evacuate survivors from the flood-stricken villages.',
  '救助チームは洪水に見舞われた村々から生存者を避難させるために24時間体制で作業した。'),
(1795, 'hygiene', '衛生(状態)', '/ˈhaɪdʒiːn/', 'ハイジーン',
  'Maintaining rigorous hygiene standards in hospitals is paramount to preventing the spread of infection.',
  '病院で厳格な衛生基準を維持することは感染の拡大を防ぐために最も重要である。',
  'The charity launched a campaign to improve hygiene practices in underserved rural communities.',
  'その慈善団体は十分なサービスを受けていない農村地域での衛生慣行を改善するキャンペーンを開始した。'),
(1796, 'integral', 'なくてはならない、不可欠な', '/ˈɪntɪɡrəl/', 'インテグラル',
  'Public transportation is an integral component of any sustainable urban development strategy.',
  '公共交通機関はあらゆる持続可能な都市開発戦略のなくてはならない要素である。',
  'The mentor played an integral role in shaping the young scientist''s career trajectory.',
  'そのメンターは若い科学者のキャリアの軌道を形作る上で不可欠な役割を果たした。'),
(1797, 'outnumber', '~を数で上回る、~より数が多い', '/ˌaʊtˈnʌmbər/', 'アウトナンバー',
  'Female graduates now outnumber their male counterparts in many academic disciplines.',
  '現在、多くの学問分野で女性の卒業生が男性の卒業生を数で上回っている。',
  'The invading forces were heavily outnumbered, yet they managed to hold their position until reinforcements arrived.',
  '侵攻部隊は数で大きく劣っていたが、援軍が到着するまで陣地を守り抜いた。'),
(1798, 'albeit', '~ではあるが', '/ɔːlˈbiːɪt/', 'オールビーイット',
  'The reform produced tangible results, albeit at a considerably higher cost than originally anticipated.',
  'その改革は目に見える成果を生んだが、当初の予想よりもかなり高い費用を要した。',
  'She accepted the offer, albeit reluctantly, recognizing that no better alternative was available.',
  '彼女はより良い代替案がないことを認識し、不本意ながらもその申し出を受け入れた。'),
(1799, 'disproportionate', '不釣り合いな、不均衡な', '/ˌdɪsprəˈpɔːrʃənət/', 'ディスプロポーショネット',
  'The report revealed that marginalized communities bear a disproportionate burden of environmental pollution.',
  'その報告書は、社会的に疎外されたコミュニティが環境汚染の不均衡な負担を負っていることを明らかにした。',
  'Critics argued that the penalty imposed was disproportionate to the severity of the offense.',
  '批評家たちは課された罰則が犯罪の重大さに対して不釣り合いであると主張した。'),
(1800, 'restoration', '修復;(制度などの)回復、復旧', '/ˌrestəˈreɪʃən/', 'レストレイション',
  'The restoration of the medieval cathedral took over a decade and required the expertise of master craftsmen.',
  '中世の大聖堂の修復は10年以上かかり、名匠の専門知識を必要とした。',
  'Environmentalists called for the restoration of the degraded wetlands to their original ecological state.',
  '環境保護主義者たちは劣化した湿地を元の生態学的状態に回復させることを求めた。');
