-- words テーブル INSERT文 (No.1801 ~ No.1850)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1802, 'allocate', '~を割り当てる、配分する', '/ˈæləkeɪt/', 'アロケイト',
  'The government decided to allocate a substantial portion of the budget to renewable energy research.',
  '政府は予算のかなりの部分を再生可能エネルギーの研究に割り当てることを決定した。',
  'The committee must allocate resources equitably among all departments to avoid internal disputes.',
  '委員会は内部紛争を避けるために全部門に公平に資源を配分しなければならない。'),
(1803, 'hostile', '敵意を持った、非友好的な;敵の;〈環境などが〉厳しい', '/ˈhɑːstl/', 'ハスタル',
  'The delegation encountered a hostile reception from local residents who opposed the proposed development.',
  '代表団は提案された開発に反対する地元住民から敵意を持った対応を受けた。',
  'The arctic expedition faced hostile weather conditions that forced the team to abandon their original route.',
  '北極探検隊は厳しい気象条件に直面し、チームは当初のルートを断念せざるを得なかった。'),
(1804, 'buildup', '増加、増強;売り込み', '/ˈbɪldʌp/', 'ビルドアップ',
  'The military buildup along the border has raised concerns among neighboring countries.',
  '国境沿いの軍事増強は近隣諸国の間で懸念を引き起こしている。',
  'The media buildup surrounding the product launch generated unprecedented consumer anticipation.',
  '製品発売を巡るメディアの売り込みは前例のない消費者の期待を生み出した。'),
(1805, 'penalize', '〈人〉を罰する', '/ˈpiːnəlaɪz/', 'ピーナライズ',
  'Companies that fail to comply with the new emissions standards will be heavily penalized.',
  '新しい排出基準を遵守しない企業は厳しく罰せられる。',
  'The revised tax code penalizes corporations that attempt to shift profits to offshore jurisdictions.',
  '改正された税法は利益をオフショア管轄地域に移転しようとする企業を罰する。'),
(1806, 'convict', '〈人〉に有罪判決を下す;囚人', '/kənˈvɪkt/', 'コンヴィクト',
  'The jury convicted the former executive of embezzling millions from the company''s pension fund.',
  '陪審は元幹部に会社の年金基金から数百万を横領した罪で有罪判決を下した。',
  'The convict spent fifteen years behind bars before new DNA evidence led to his exoneration.',
  'その囚人は新しいDNA証拠が無罪放免につながるまで15年間収監された。'),
(1807, 'aftermath', '(災害・戦争などの)直後の時期、余波、後遺症', '/ˈæftərmæθ/', 'アフターマス',
  'In the aftermath of the earthquake, thousands of displaced residents sought refuge in temporary shelters.',
  '地震の直後の時期に、何千人もの被災住民が仮設避難所に避難した。',
  'The economic aftermath of the pandemic continued to reverberate through global markets for years.',
  'パンデミックの経済的余波は何年にもわたって世界市場に波及し続けた。'),
(1808, 'hail', '[hail A as B] AをBとして迎える;〈人〉を歓呼して迎える', '/heɪl/', 'ヘイル',
  'Critics hailed the young novelist as the most promising literary talent of her generation.',
  '批評家たちはその若い小説家を彼女の世代で最も有望な文学的才能として迎えた。',
  'The returning astronauts were hailed as national heroes upon their safe arrival at the space center.',
  '帰還した宇宙飛行士たちは宇宙センターに無事到着すると国民的英雄として歓呼して迎えられた。'),
(1809, 'merge', '(~を)統合する、合併する;~を融合させる', '/mɜːrdʒ/', 'マージ',
  'The two pharmaceutical giants announced plans to merge, creating the largest drug manufacturer in the world.',
  '二つの製薬大手は合併計画を発表し、世界最大の医薬品メーカーを設立することになった。',
  'The artist skillfully merged traditional techniques with contemporary aesthetics in her latest exhibition.',
  'そのアーティストは最新の展覧会で伝統的な技法と現代的な美学を巧みに融合させた。'),
(1810, 'captive', '捕らえられた、捕虜になった;とりこになった', '/ˈkæptɪv/', 'キャプティヴ',
  'The captive soldiers endured months of harsh treatment before an international delegation negotiated their release.',
  '捕虜になった兵士たちは国際代表団が釈放を交渉するまで数ヶ月の過酷な待遇に耐えた。',
  'The speaker held the audience captive with her compelling narrative of survival against impossible odds.',
  '講演者は不可能な逆境に立ち向かう生存の説得力ある物語で聴衆をとりこにした。'),
(1811, 'complimentary', '無料で提供される、ただの', '/ˌkɑːmplɪˈmentəri/', 'コンプリメンタリー',
  'Hotel guests were offered complimentary access to the spa and fitness facilities during their stay.',
  'ホテルの宿泊客には滞在中、スパとフィットネス施設への無料アクセスが提供された。',
  'The airline provides complimentary meals and beverages on all long-haul international flights.',
  'その航空会社はすべての長距離国際便で無料の食事と飲み物を提供している。'),
(1812, 'downfall', '没落、破滅', '/ˈdaʊnfɔːl/', 'ダウンフォール',
  'Historians attribute the empire''s downfall to a combination of military overreach and internal corruption.',
  '歴史家たちはその帝国の没落を軍事的な過剰拡大と内部腐敗の組み合わせに帰している。',
  'His arrogance and refusal to heed expert advice ultimately proved to be his downfall.',
  '彼の傲慢さと専門家の助言に耳を傾けることへの拒否が最終的に彼の破滅となった。'),
(1814, 'upheaval', '大変動、激変', '/ʌpˈhiːvəl/', 'アップヒーヴァル',
  'The political upheaval following the contested election plunged the nation into months of uncertainty.',
  '争われた選挙後の政治的激変は国を数ヶ月の不安定な状態に陥れた。',
  'Technological upheaval in the manufacturing sector has rendered many traditional skills obsolete.',
  '製造業における技術的大変動は多くの伝統的技能を時代遅れにしてしまった。'),
(1815, 'eradicate', '〈病気・社会問題・害虫など〉を根絶する、撲滅する', '/ɪˈrædɪkeɪt/', 'イラディケイト',
  'The global health initiative aims to eradicate malaria in sub-Saharan Africa within the next decade.',
  'その世界的な保健イニシアチブはサハラ以南のアフリカで今後10年以内にマラリアを根絶することを目指している。',
  'Despite decades of effort, authorities have failed to eradicate corruption from the public sector.',
  '数十年の努力にもかかわらず、当局は公共部門から汚職を撲滅することに失敗している。'),
(1816, 'verge', '間際、瀬戸際;へり、境界', '/vɜːrdʒ/', 'ヴァージ',
  'The endangered species is on the verge of extinction due to rampant deforestation and poaching.',
  'その絶滅危惧種は横行する森林伐採と密猟のために絶滅の瀬戸際にある。',
  'The company was on the verge of bankruptcy before a last-minute investor agreed to inject capital.',
  'その会社は土壇場で投資家が資本注入に同意するまで破産の間際にあった。'),
(1817, 'pretense', 'ふり、見せかけ;口実', '/prɪˈtens/', 'プリテンス',
  'He maintained the pretense of loyalty to the organization while secretly negotiating with its rivals.',
  '彼は組織への忠誠の見せかけを維持しながら、密かにライバルと交渉していた。',
  'Under the pretense of conducting a routine inspection, the agents searched for classified documents.',
  '定期検査を行うという口実の下、捜査官たちは機密文書を捜索した。'),
(1818, 'privileged', '特権的な、特権を持つ', '/ˈprɪvəlɪdʒd/', 'プリヴィレッジド',
  'Critics argue that the tax reform disproportionately benefits the privileged few at the expense of ordinary citizens.',
  '批評家たちは税制改革が一般市民を犠牲にして特権的な少数者に不均衡に恩恵を与えていると主張する。',
  'She acknowledged her privileged upbringing and pledged to use her influence to advocate for the marginalized.',
  '彼女は自分の特権的な育ちを認め、影響力を使って社会的に疎外された人々のために擁護することを誓った。'),
(1819, 'tolerance', '寛容さ、許容', '/ˈtɑːlərəns/', 'トレランス',
  'A democratic society thrives on tolerance for diverse opinions, even those that challenge prevailing norms.',
  '民主主義社会は、既存の規範に異議を唱えるものであっても、多様な意見に対する寛容さの上に繁栄する。',
  'The engineer tested the bridge''s tolerance for extreme wind loads before approving its design.',
  '技術者は設計を承認する前に、極端な風荷重に対する橋の許容度を試験した。'),
(1820, 'render', '〈人・もの〉を(ある状態に)する', '/ˈrendər/', 'レンダー',
  'The unprecedented flooding rendered the main highway impassable for several weeks.',
  '前例のない洪水により幹線道路は数週間にわたって通行不能になった。',
  'Advances in artificial intelligence may render certain administrative positions redundant within a decade.',
  '人工知能の進歩は10年以内に特定の管理職を不要にする可能性がある。'),
(1821, 'outlaw', '~を違法とする、禁止する;無法者、ならず者', '/ˈaʊtlɔː/', 'アウトロー',
  'Several nations have moved to outlaw the use of single-use plastics in an effort to protect marine ecosystems.',
  'いくつかの国が海洋生態系を保護するために使い捨てプラスチックの使用を違法とする措置を講じた。',
  'The legendary outlaw evaded capture for years by hiding in the dense forests along the border.',
  'その伝説的な無法者は国境沿いの鬱蒼とした森に隠れて何年も捕獲を逃れた。'),
(1822, 'reassure', '〈人〉を安心させる、元気づける', '/ˌriːəˈʃʊr/', 'リアシュア',
  'The doctor reassured the patient that the procedure carried minimal risk and a high success rate.',
  '医師はその処置がリスクが最小限で成功率が高いと患者を安心させた。',
  'The government issued a statement to reassure the public that the water supply was safe for consumption.',
  '政府は水道水が飲用に安全であると国民を安心させるための声明を発表した。'),
(1823, 'gigantic', '巨大な;(数量などが)膨大な', '/dʒaɪˈɡæntɪk/', 'ジャイガンティック',
  'The construction of the gigantic dam displaced thousands of villagers from their ancestral homes.',
  '巨大なダムの建設は何千人もの村人を先祖代々の家から立ち退かせた。',
  'The corporation reported a gigantic loss in the fourth quarter, sending its share price plummeting.',
  'その企業は第4四半期に膨大な損失を報告し、株価の急落を招いた。'),
(1824, 'forcible', '力ずくの、強制的な', '/ˈfɔːrsəbl/', 'フォーシブル',
  'Human rights organizations condemned the forcible eviction of refugees from the temporary settlement.',
  '人権団体は仮設居住地からの難民の強制的な立ち退きを非難した。',
  'The forcible suppression of peaceful protests drew widespread international condemnation.',
  '平和的な抗議活動の力ずくの弾圧は広範な国際的非難を招いた。'),
(1826, 'disguise', '(事実・外見・感情など)を偽る;~を偽装する、変装する;偽装、変装', '/dɪsˈɡaɪz/', 'ディスガイズ',
  'The spy adopted an elaborate disguise to infiltrate the heavily guarded diplomatic reception.',
  'そのスパイは厳重に警備された外交レセプションに潜入するために精巧な変装をした。',
  'There is no disguising the fact that the economy has entered a prolonged period of stagnation.',
  '経済が長期の停滞期に入ったという事実を偽ることはできない。'),
(1827, 'confidential', '〈情報が〉機密の、マル秘の', '/ˌkɑːnfɪˈdenʃəl/', 'コンフィデンシャル',
  'All employees are required to sign a non-disclosure agreement to protect confidential company information.',
  '全従業員は会社の機密情報を保護するために秘密保持契約に署名することが求められる。',
  'The leaked confidential documents revealed the extent of government surveillance on ordinary citizens.',
  '流出した機密文書は一般市民に対する政府の監視の範囲を明らかにした。'),
(1828, 'dismiss', '〈提案・考えなど〉を退ける、否定する;〈人〉を解雇する、罷免する', '/dɪsˈmɪs/', 'ディスミス',
  'The board of directors voted unanimously to dismiss the CEO following the accounting scandal.',
  '取締役会は会計スキャンダルを受けてCEOを解雇することを全会一致で可決した。',
  'It would be unwise to dismiss the concerns raised by the opposition without careful consideration.',
  '野党が提起した懸念を慎重な検討なしに退けるのは賢明ではないだろう。'),
(1829, 'irrigation', '水を引くこと、灌漑', '/ˌɪrɪˈɡeɪʃən/', 'イリゲイション',
  'The construction of an advanced irrigation system transformed the arid region into productive farmland.',
  '高度な灌漑システムの建設はその乾燥地帯を生産性の高い農地に変えた。',
  'Without adequate irrigation, the crops would wither during the prolonged dry season.',
  '十分な灌漑がなければ、長引く乾季の間に作物は枯れてしまうだろう。'),
(1830, 'confrontational', '対決的な、挑戦的な', '/ˌkɑːnfrʌnˈteɪʃənl/', 'コンフロンテイショナル',
  'The ambassador''s confrontational tone during negotiations only served to deepen the diplomatic rift.',
  '交渉中の大使の対決的な口調は外交上の亀裂を深めるだけだった。',
  'Adopting a confrontational approach to labor disputes often prolongs the conflict rather than resolving it.',
  '労働争議に対決的なアプローチを取ることは、紛争を解決するよりもむしろ長引かせることが多い。'),
(1831, 'hinder', '〈発展・動きなど〉を妨げる、妨害する', '/ˈhɪndər/', 'ヒンダー',
  'Excessive bureaucracy continues to hinder economic growth in many developing nations.',
  '過度な官僚主義が多くの発展途上国で経済成長を妨げ続けている。',
  'The severe weather hindered rescue operations, delaying the delivery of essential supplies to the affected area.',
  '悪天候が救助活動を妨害し、被災地への必需品の配達を遅延させた。'),
(1832, 'oversight', '監視、監督;ミス、見落とし', '/ˈoʊvərsaɪt/', 'オーヴァーサイト',
  'The parliamentary committee was established to provide independent oversight of intelligence agencies.',
  '議会委員会は情報機関の独立した監督を提供するために設立された。',
  'Due to an administrative oversight, the applicant''s visa renewal was not processed before the deadline.',
  '事務的な見落としにより、申請者のビザ更新は期限前に処理されなかった。'),
(1833, 'skyrocket', '〈価格などが〉急騰する', '/ˈskaɪrɑːkɪt/', 'スカイロケット',
  'Housing prices in the metropolitan area have skyrocketed over the past decade, pricing out many first-time buyers.',
  '首都圏の住宅価格は過去10年間で急騰し、多くの初めての購入者を締め出している。',
  'Demand for electric vehicles skyrocketed after the government introduced generous tax incentives.',
  '政府が手厚い税制優遇措置を導入した後、電気自動車の需要が急騰した。'),
(1834, 'evaporate', '~を蒸発させる;蒸発する;〈感情・希望などが〉(蒸気のように)徐々に消える', '/ɪˈvæpəreɪt/', 'イヴァポレイト',
  'As temperatures rose, the shallow lake began to evaporate, leaving behind a vast expanse of cracked earth.',
  '気温が上昇するにつれて浅い湖は蒸発し始め、広大なひび割れた大地を残した。',
  'Public enthusiasm for the reform evaporated once the true cost of implementation became apparent.',
  '実施の真のコストが明らかになると、改革に対する国民の熱意は徐々に消えた。'),
(1835, 'staggering', '驚くべき、途方もない', '/ˈstæɡərɪŋ/', 'スタガリング',
  'The investigation revealed a staggering amount of public funds had been misappropriated over the years.',
  '調査は何年にもわたって驚くべき額の公的資金が不正流用されていたことを明らかにした。',
  'The staggering complexity of the human genome continues to challenge even the most advanced research teams.',
  'ヒトゲノムの途方もない複雑さは最も先進的な研究チームでさえも挑戦し続けている。'),
(1836, 'status quo', '現状(維持)', '/ˌsteɪtəs ˈkwoʊ/', 'ステイタス クオウ',
  'Powerful vested interests are determined to maintain the status quo and resist any meaningful reform.',
  '強力な既得権益層は現状を維持し、意味のある改革に抵抗することを決意している。',
  'The activist argued that accepting the status quo was tantamount to condoning systemic injustice.',
  'その活動家は現状を受け入れることは制度的不正を容認するに等しいと主張した。'),
(1838, 'exert', '〈権力・影響力など〉を使う、行使する;[exert oneself] 努力する、奮闘する', '/ɪɡˈzɜːrt/', 'イグザート',
  'Multinational corporations can exert considerable influence over the domestic policies of smaller nations.',
  '多国籍企業は小国の国内政策に対してかなりの影響力を行使することができる。',
  'She exerted herself tirelessly to ensure the charity gala was an unqualified success.',
  '彼女はチャリティーガラが完全な成功を収めるよう疲れを知らずに奮闘した。'),
(1839, 'ballot', '投票用紙;(無記名)投票', '/ˈbælət/', 'バロット',
  'Citizens cast their ballots in record numbers during the historic presidential election.',
  '市民は歴史的な大統領選挙で記録的な数の投票用紙を投じた。',
  'The union conducted a secret ballot to determine whether its members supported the proposed strike action.',
  '労働組合は組合員が提案されたストライキ行動を支持するかどうかを判断するために無記名投票を実施した。'),
(1840, 'disciplinary', '懲戒の、規律上の;訓練の', '/ˈdɪsəplɪneri/', 'ディシプリナリー',
  'The officer faced disciplinary proceedings after allegations of misconduct surfaced in the media.',
  'その職員はメディアで不正行為の疑惑が浮上した後、懲戒処分の手続きに直面した。',
  'The school''s disciplinary committee recommended suspension for students found guilty of plagiarism.',
  '学校の懲戒委員会は剽窃で有罪と認められた生徒に停学を勧告した。'),
(1841, 'solidify', '〈液体が〉凝固する;(液体)を凝固させる;(関係などが)強固になる;(関係など)を強固にする', '/səˈlɪdɪfaɪ/', 'ソリディファイ',
  'The trade agreement served to solidify the diplomatic relationship between the two nations.',
  'その貿易協定は二国間の外交関係を強固にする役割を果たした。',
  'As the molten lava cooled, it began to solidify into rugged basalt formations along the coastline.',
  '溶岩が冷えるにつれ、海岸線沿いにごつごつした玄武岩の岩層へと凝固し始めた。'),
(1842, 'bribery', '贈収賄', '/ˈbraɪbəri/', 'ブライバリー',
  'The former governor was indicted on charges of bribery and abuse of public office.',
  '元知事は贈収賄と公職の乱用の容疑で起訴された。',
  'Stringent anti-bribery legislation was enacted to restore public confidence in the integrity of government officials.',
  '政府職員の誠実さに対する国民の信頼を回復するために厳格な贈収賄防止法が制定された。'),
(1843, 'curb', '~を抑制する、制限する;抑制、制限', '/kɜːrb/', 'カーブ',
  'The central bank raised interest rates in an effort to curb runaway inflation.',
  '中央銀行は暴走するインフレを抑制するために金利を引き上げた。',
  'New regulations were introduced to curb the spread of misinformation on social media platforms.',
  'ソーシャルメディアプラットフォーム上の偽情報の拡散を制限するために新しい規制が導入された。'),
(1844, 'rash', '〈言動などが〉性急な、軽率な', '/ræʃ/', 'ラッシュ',
  'The minister''s rash decision to impose tariffs without consultation provoked a diplomatic crisis.',
  '大臣が協議なしに関税を課すという性急な決定は外交危機を引き起こした。',
  'In hindsight, it was rash of the company to invest so heavily in a volatile market without due diligence.',
  '振り返ってみれば、十分な調査なしに不安定な市場に多額の投資をしたのは会社にとって軽率だった。'),
(1845, 'irrelevant', '関連のない', '/ɪˈreləvənt/', 'イレレヴァント',
  'The defense attorney argued that the prosecution''s evidence was irrelevant to the charges in question.',
  '弁護人は検察側の証拠が問題となっている容疑に関連がないと主張した。',
  'Critics fear that traditional print media may become irrelevant in an era dominated by digital platforms.',
  '批評家たちは伝統的な印刷メディアがデジタルプラットフォームに支配される時代に関連のないものになるかもしれないと懸念している。'),
(1846, 'demographic', '(一群の人々から成る)層;人口統計の、人口の', '/ˌdeməˈɡræfɪk/', 'デモグラフィック',
  'The aging demographic in many industrialized nations poses serious challenges for pension systems.',
  '多くの先進国における高齢化する人口層は年金制度に深刻な課題を突きつけている。',
  'Marketers must understand the demographic profile of their target audience to craft effective campaigns.',
  'マーケターは効果的なキャンペーンを作成するためにターゲット層の人口統計的プロファイルを理解しなければならない。'),
(1847, 'communal', '共同の、共有の;自治体の、共同体の', '/kəˈmjuːnl/', 'コミューナル',
  'The residents of the housing complex share a communal garden where they grow vegetables and herbs.',
  '住宅団地の住民たちは野菜やハーブを育てる共同の庭を共有している。',
  'Communal tensions between ethnic groups escalated following the disputed local election results.',
  '争われた地方選挙の結果を受けて民族間の共同体の緊張が高まった。'),
(1848, 'norm', '規範、基準', '/nɔːrm/', 'ノーム',
  'Remote work has become the norm in many industries since the global health crisis reshaped workplace culture.',
  '世界的な健康危機が職場文化を変えて以来、多くの産業でリモートワークが規範となった。',
  'Behavior that deviates significantly from social norms often invites scrutiny and censure from the community.',
  '社会規範から大きく逸脱する行動はしばしば地域社会からの精査と非難を招く。'),
(1850, 'shatter', '〈希望・信念など〉を打ち砕く;〈ガラスなど〉を粉々に割る', '/ˈʃætər/', 'シャター',
  'The revelation of widespread fraud shattered public trust in the financial institution.',
  '広範な不正の発覚はその金融機関に対する国民の信頼を打ち砕いた。',
  'The explosion shattered every window in the building, sending shards of glass cascading onto the street below.',
  '爆発はビルのすべての窓を粉々に割り、ガラスの破片が下の通りに降り注いだ。');
