-- words テーブル INSERT文 (No.1851 ~ No.1900)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1851, 'chaotic', '混沌とした、無秩序な', '/keɪˈɑːtɪk/', 'ケイアティック',
  'The evacuation became chaotic when conflicting instructions were issued by different emergency agencies.',
  '異なる緊急機関から矛盾する指示が出されたため、避難は混沌としたものになった。',
  'Without effective leadership, the once orderly organization descended into a chaotic state of dysfunction.',
  '効果的なリーダーシップがなければ、かつて秩序あった組織は無秩序な機能不全の状態に陥った。'),
(1852, 'integrity', '正直さ、誠実さ;完全性', '/ɪnˈteɡrəti/', 'インテグリティ',
  'The journalist''s unwavering integrity earned her the respect of both colleagues and the public.',
  'そのジャーナリストの揺るぎない誠実さは同僚と国民の両方から尊敬を得た。',
  'Engineers conducted extensive tests to verify the structural integrity of the aging bridge before reopening it.',
  '技術者たちは老朽化した橋を再開する前にその構造的完全性を検証するために広範な試験を実施した。'),
(1853, 'agrarian', '農業の', '/əˈɡreriən/', 'アグレリアン',
  'The country''s transition from an agrarian economy to an industrial one displaced millions of rural workers.',
  'その国の農業経済から工業経済への転換は数百万の農村労働者を移動させた。',
  'Agrarian reform was at the heart of the revolutionary movement that swept through the region in the 1960s.',
  '農業改革は1960年代にその地域を席巻した革命運動の中心にあった。'),
(1854, 'uproar', '大騒ぎ、騒動', '/ˈʌprɔːr/', 'アップロアー',
  'The government''s proposal to raise the retirement age caused an uproar among the working population.',
  '政府の定年引き上げ案は労働人口の間で大騒ぎを引き起こした。',
  'The sudden dismissal of the popular university president created an uproar among students and faculty alike.',
  '人気のある大学学長の突然の解任は学生と教職員の間で同様に騒動を引き起こした。'),
(1855, 'commence', '~を始める;始まる', '/kəˈmens/', 'コメンス',
  'Construction of the new international terminal is scheduled to commence early next year.',
  '新しい国際ターミナルの建設は来年初めに開始される予定である。',
  'The peace negotiations commenced after months of preliminary diplomatic exchanges between the two parties.',
  '和平交渉は両当事者間の数ヶ月にわたる予備的な外交交渉の後に始まった。'),
(1856, 'coin', '〈新語など〉を作る', '/kɔɪn/', 'コイン',
  'The sociologist coined the term to describe the phenomenon of voluntary social withdrawal among young adults.',
  'その社会学者は若年成人の間での自発的な社会的引きこもり現象を表すためにその用語を作った。',
  'Shakespeare is widely credited with having coined numerous words and phrases that remain in common use today.',
  'シェイクスピアは今日でも一般的に使われている多くの単語や表現を作ったことで広く評価されている。'),
(1857, 'deplete', '〈資源・蓄えなど〉を激減させる、枯渇させる', '/dɪˈpliːt/', 'ディプリート',
  'Decades of overexploitation have severely depleted the region''s once-abundant fishery resources.',
  '数十年にわたる過剰開発はその地域のかつて豊富だった水産資源を深刻に枯渇させた。',
  'The prolonged military campaign depleted the nation''s treasury, leaving insufficient funds for domestic programs.',
  '長期にわたる軍事作戦は国庫を激減させ、国内プログラムのための資金が不足した。'),
(1858, 'exempt', '~を免除する;免除された', '/ɪɡˈzempt/', 'イグゼンプト',
  'Non-profit organizations are typically exempt from paying corporate income tax under current legislation.',
  '非営利団体は通常、現行法の下で法人所得税の支払いを免除されている。',
  'The government decided to exempt essential goods from the newly imposed sales tax to protect low-income households.',
  '政府は低所得世帯を保護するために新たに課された消費税から必需品を免除することを決定した。'),
(1859, 'incite', '〈感情など〉を引き起こす;〈人〉を刺激する、扇動する', '/ɪnˈsaɪt/', 'インサイト',
  'The inflammatory speech was widely condemned for its potential to incite violence among rival factions.',
  'その扇動的な演説は対立する派閥間で暴力を引き起こす可能性があるとして広く非難された。',
  'Authorities charged the activist with attempting to incite a rebellion against the newly established government.',
  '当局はその活動家を新たに樹立された政府に対する反乱を扇動しようとした罪で起訴した。'),
(1860, 'unprecedented', '前例のない、空前の', '/ʌnˈpresɪdentɪd/', 'アンプレシデンティド',
  'The pandemic triggered an unprecedented global economic downturn that affected virtually every sector.',
  'パンデミックは事実上すべてのセクターに影響を与える前例のない世界的な景気後退を引き起こした。',
  'The scientist''s discovery represented an unprecedented breakthrough in the field of quantum computing.',
  'その科学者の発見は量子コンピューティングの分野における空前の画期的進歩を示した。'),
(1862, 'intervene', '(調停・和平などのために)介入する', '/ˌɪntərˈviːn/', 'インターヴィーン',
  'The United Nations decided to intervene in the conflict after diplomatic efforts failed to produce a ceasefire.',
  '外交努力が停戦をもたらすことに失敗した後、国連はその紛争に介入することを決定した。',
  'The central bank was forced to intervene in the currency market to prevent a catastrophic devaluation.',
  '中央銀行は壊滅的な通貨切り下げを防ぐために為替市場に介入せざるを得なかった。'),
(1863, 'attic', '屋根裏(部屋)', '/ˈætɪk/', 'アティック',
  'While renovating the attic, the family discovered a collection of rare manuscripts dating back to the 18th century.',
  '屋根裏部屋を改装中に、その家族は18世紀にさかのぼる珍しい写本のコレクションを発見した。',
  'The architect proposed converting the unused attic into a spacious home office with skylights for natural illumination.',
  '建築家は使われていない屋根裏部屋を自然光のための天窓付きの広々としたホームオフィスに改装することを提案した。'),
(1864, 'presumption', '想定、推定', '/prɪˈzʌmpʃən/', 'プリザンプション',
  'The legal system operates on the presumption of innocence until guilt is proven beyond reasonable doubt.',
  '法制度は合理的な疑いを超えて有罪が証明されるまで無罪の推定に基づいて運営される。',
  'The presumption that economic growth automatically leads to social progress has been challenged by many scholars.',
  '経済成長が自動的に社会的進歩につながるという想定は多くの学者によって異議を唱えられてきた。'),
(1865, 'assertive', 'はっきり意見を述べる、自信に満ちた', '/əˈsɜːrtɪv/', 'アサーティヴ',
  'The new chairperson adopted an assertive leadership style that quickly transformed the committee''s dynamics.',
  '新しい議長は委員会の力学を急速に変えた自信に満ちたリーダーシップスタイルを採用した。',
  'Negotiators must be assertive yet diplomatic to secure favorable terms without alienating the opposing party.',
  '交渉者は相手方を疎外することなく有利な条件を確保するために、はっきり意見を述べつつも外交的でなければならない。'),
(1866, 'liken', '~をなぞらえる', '/ˈlaɪkən/', 'ライケン',
  'Critics likened the president''s authoritarian tendencies to those of infamous dictators of the past century.',
  '批評家たちは大統領の権威主義的傾向を前世紀の悪名高い独裁者たちのそれになぞらえた。',
  'The poet likened the fleeting nature of youth to a blossom that withers before the onset of autumn.',
  'その詩人は青春のはかない性質を秋の訪れの前に萎れる花になぞらえた。'),
(1867, 'fragility', 'もろさ、脆弱性', '/frəˈdʒɪləti/', 'フラジリティ',
  'The financial crisis exposed the fragility of the global banking system and its susceptibility to speculative bubbles.',
  '金融危機は世界的な銀行システムの脆弱性と投機的バブルへの感受性を露呈した。',
  'The fragility of the ceasefire agreement became apparent when sporadic fighting resumed along the border.',
  '国境沿いで散発的な戦闘が再開した時、停戦合意のもろさが明らかになった。'),
(1868, 'hefty', '高額な;がっしりした、大きくて重い', '/ˈhefti/', 'ヘフティ',
  'The corporation was hit with a hefty fine for violating environmental regulations at its manufacturing plant.',
  'その企業は製造工場で環境規制に違反したとして高額な罰金を科された。',
  'The hefty volume of legal documents required weeks of careful review by the entire legal team.',
  '大きくて重い法律文書の量は法務チーム全体による数週間の慎重な検討を必要とした。'),
(1869, 'foe', '敵、(競技などの)相手', '/foʊ/', 'フォウ',
  'The two nations, once bitter foes, have forged a strategic alliance based on mutual economic interests.',
  'かつて激しい敵同士であった二国は相互の経済的利益に基づく戦略的同盟を結んだ。',
  'The chess grandmaster faced a formidable foe in the tournament final, pushing the match to a grueling five-hour battle.',
  'そのチェスのグランドマスターはトーナメントの決勝で手ごわい相手に直面し、試合は過酷な5時間の戦いに持ち込まれた。'),
(1870, 'incidence', '発生(率)', '/ˈɪnsɪdəns/', 'インシデンス',
  'Epidemiologists have noted a troubling increase in the incidence of antibiotic-resistant infections worldwide.',
  '疫学者たちは世界中で抗生物質耐性感染症の発生率の憂慮すべき増加に注目している。',
  'The incidence of workplace injuries declined significantly after the implementation of stricter safety protocols.',
  'より厳格な安全基準の実施後、職場での負傷の発生率は大幅に低下した。'),
(1871, 'catastrophe', '破局、大失敗', '/kəˈtæstrəfi/', 'カタストロフィ',
  'The oil spill was an environmental catastrophe that devastated marine ecosystems along hundreds of kilometers of coastline.',
  'その石油流出は数百キロメートルの海岸線に沿って海洋生態系を壊滅させた環境の破局だった。',
  'Failure to address climate change could lead to a catastrophe of unprecedented proportions for future generations.',
  '気候変動に対処しないことは将来の世代にとって前例のない規模の破局につながりかねない。'),
(1872, 'outstrip', '〈需要・量が〉~を上回る、超える', '/ˌaʊtˈstrɪp/', 'アウトストリップ',
  'Demand for affordable housing continues to outstrip supply in most major metropolitan areas.',
  '手頃な住宅の需要はほとんどの主要大都市圏で供給を上回り続けている。',
  'The pace of technological innovation has outstripped the ability of regulatory frameworks to keep pace.',
  '技術革新のペースは規制の枠組みが追いつく能力を超えてしまった。'),
(1874, 'overdue', '(支払い・返却の)期限が過ぎて;(予定より)遅れて;もっと早くすべきで', '/ˌoʊvərˈduː/', 'オーヴァーデュー',
  'The reform of the country''s antiquated pension system is long overdue and can no longer be postponed.',
  'その国の旧態依然とした年金制度の改革はもっと早くすべきであり、もはや先延ばしにはできない。',
  'The library notified patrons that overdue books would incur a daily fine until returned.',
  '図書館は利用者に期限を過ぎた本は返却されるまで日割りの罰金が科されると通知した。'),
(1875, 'seamless', '継ぎ目のない、一体となった', '/ˈsiːmləs/', 'シームレス',
  'The company invested heavily in technology to ensure a seamless transition from physical to digital services.',
  'その企業は物理的なサービスからデジタルサービスへの継ぎ目のない移行を確実にするために技術に多額の投資をした。',
  'The seamless integration of renewable energy sources into the existing grid remains a significant engineering challenge.',
  '再生可能エネルギー源の既存の電力網への一体となった統合は依然として重要な工学的課題である。'),
(1876, 'evoke', '〈感情・記憶など〉を喚起する', '/ɪˈvoʊk/', 'イヴォウク',
  'The haunting melody of the symphony evoked a profound sense of nostalgia among the audience.',
  '交響曲の忘れがたい旋律は聴衆の間に深い郷愁の感覚を喚起した。',
  'The photographer''s exhibition evoked powerful emotions by depicting the stark reality of life in conflict zones.',
  'その写真家の展覧会は紛争地帯の厳しい現実を描くことで強烈な感情を喚起した。'),
(1877, 'brag', '自慢する', '/bræɡ/', 'ブラグ',
  'He could not help but brag about his daughter''s acceptance into one of the most prestigious universities in the country.',
  '彼は娘が国内で最も名門の大学の一つに合格したことを自慢せずにはいられなかった。',
  'The CEO frequently bragged about the company''s record profits, yet failed to acknowledge the employees'' contributions.',
  'そのCEOは会社の記録的な利益について頻繁に自慢したが、従業員の貢献を認めなかった。'),
(1878, 'upscale', '高所得者(向け)の、高級な', '/ˈʌpskeɪl/', 'アップスケイル',
  'The once-neglected neighborhood has been transformed into an upscale residential district with luxury apartments.',
  'かつて放置されていた地区は高級マンションのある高級住宅街に変貌した。',
  'The restaurant repositioned itself as an upscale dining establishment to attract a more affluent clientele.',
  'そのレストランはより裕福な顧客層を引き付けるために高級ダイニング施設として再位置づけした。'),
(1879, 'renowned', '名高い、名声のある', '/rɪˈnaʊnd/', 'リナウンド',
  'The university is renowned for its cutting-edge research in biotechnology and molecular genetics.',
  'その大学はバイオテクノロジーと分子遺伝学の最先端研究で名高い。',
  'The renowned architect was commissioned to design the new national museum of contemporary art.',
  'その名声のある建築家は新しい国立現代美術館の設計を依頼された。'),
(1880, 'freight', '運送貨物;貨物輸送', '/freɪt/', 'フレイト',
  'The disruption to global freight networks caused severe shortages of essential goods across multiple continents.',
  '世界的な貨物輸送ネットワークの混乱は複数の大陸で必需品の深刻な不足を引き起こした。',
  'The government announced plans to invest in modernizing the freight rail system to reduce dependence on road transport.',
  '政府は道路輸送への依存を減らすために貨物鉄道システムの近代化に投資する計画を発表した。'),
(1881, 'outcry', '(世間の強い)抗議、憤激', '/ˈaʊtkraɪ/', 'アウトクライ',
  'The proposed demolition of the historic landmark triggered a public outcry that forced the council to reconsider.',
  '歴史的建造物の取り壊し案は議会に再考を強いる世間の抗議を引き起こした。',
  'There was an international outcry when the government imposed severe restrictions on press freedom.',
  '政府が報道の自由に厳しい制限を課した時、国際的な憤激があった。'),
(1882, 'unearth', '~を掘り出す、発掘する;(偶然)~を見つける、発見する', '/ʌnˈɜːrθ/', 'アンアース',
  'Archaeologists unearthed a remarkably well-preserved Roman villa buried beneath the farmland for centuries.',
  '考古学者たちは何世紀も農地の下に埋もれていた非常に保存状態の良いローマ時代の別荘を発掘した。',
  'An investigative journalist unearthed evidence of systematic corruption within the highest echelons of government.',
  '調査報道記者が政府の最高幹部における組織的な汚職の証拠を発見した。'),
(1883, 'municipality', '地方自治体', '/mjuːˌnɪsɪˈpæləti/', 'ミューニシパリティ',
  'The municipality allocated additional funding to expand public transportation services in underserved districts.',
  'その地方自治体はサービスが行き届いていない地区で公共交通サービスを拡大するために追加の資金を配分した。',
  'Residents petitioned the municipality to implement stricter zoning regulations to preserve green spaces.',
  '住民は緑地を保全するためにより厳格な区画規制を実施するよう地方自治体に請願した。'),
(1884, 'recede', '後退する、遠ざかる;〈感情・痛みなどが〉弱まる、和らぐ', '/rɪˈsiːd/', 'リシード',
  'As the floodwaters gradually receded, the full extent of the devastation became painfully apparent.',
  '洪水の水が徐々に後退するにつれ、壊滅的な被害の全容が痛いほど明らかになった。',
  'The initial panic receded once the authorities confirmed that the threat had been neutralized.',
  '当局が脅威が無力化されたと確認すると、当初のパニックは弱まった。'),
(1886, 'watershed', '(歴史・人生などの)転機、分岐点;分水嶺', '/ˈwɔːtərʃed/', 'ウォーターシェッド',
  'The landmark Supreme Court ruling proved to be a watershed moment in the struggle for civil rights.',
  'その画期的な最高裁判決は公民権闘争における転機となった。',
  'Historians regard the invention of the printing press as a watershed event that democratized access to knowledge.',
  '歴史家たちは印刷機の発明を知識へのアクセスを民主化した分岐点となる出来事とみなしている。'),
(1887, 'instability', '不安定さ', '/ˌɪnstəˈbɪləti/', 'インスタビリティ',
  'Political instability in the region has deterred foreign investors and hampered economic development.',
  'その地域の政治的不安定さは外国投資家を遠ざけ、経済発展を妨げている。',
  'The structural instability of the aging dam raised fears of a catastrophic failure during the rainy season.',
  '老朽化したダムの構造的不安定さは雨季における壊滅的な決壊の懸念を引き起こした。'),
(1888, 'suppress', '〈感情など〉を抑える;〈反乱など〉を鎮圧する', '/səˈpres/', 'サプレス',
  'The authoritarian regime employed military force to suppress the pro-democracy movement.',
  'その権威主義体制は民主化運動を鎮圧するために軍事力を行使した。',
  'She struggled to suppress her frustration during the lengthy and unproductive committee meeting.',
  '彼女は長く非生産的な委員会の会議中にフラストレーションを抑えるのに苦労した。'),
(1889, 'misinterpret', '~を誤って解釈[説明]する', '/ˌmɪsɪnˈtɜːrprɪt/', 'ミスインタープリト',
  'The ambassador''s remarks were widely misinterpreted by the foreign press, sparking an unnecessary diplomatic row.',
  '大使の発言は外国メディアに広く誤って解釈され、不必要な外交的論争を引き起こした。',
  'Students frequently misinterpret the author''s use of irony, taking literally what was intended as satire.',
  '学生はしばしば著者の皮肉の使用を誤って解釈し、風刺として意図されたものを文字通りに受け取る。'),
(1890, 'decent', '満足できる、まずまずの;〈人・振る舞いなどが〉上品な、礼儀正しい', '/ˈdiːsnt/', 'ディーセント',
  'Every citizen deserves a decent standard of living, including access to healthcare, education, and housing.',
  'すべての市民は医療、教育、住居へのアクセスを含む満足できる生活水準に値する。',
  'Despite the challenging circumstances, the refugees were treated with decent respect by the host community.',
  '困難な状況にもかかわらず、難民たちはホストコミュニティから礼儀正しい敬意をもって扱われた。'),
(1891, 'retrieve', '~を救出する、取り戻す;〈情報〉を検索する', '/rɪˈtriːv/', 'リトリーヴ',
  'The deep-sea expedition was launched to retrieve the black box from the wreckage of the sunken aircraft.',
  '深海探検は沈没した航空機の残骸からブラックボックスを救出するために開始された。',
  'The new database system enables researchers to retrieve vast amounts of archived data within seconds.',
  '新しいデータベースシステムにより研究者は膨大な量のアーカイブデータを数秒以内に検索できる。'),
(1892, 'wary', '警戒している、慎重な', '/ˈweri/', 'ウェアリー',
  'Investors remain wary of committing capital to the volatile emerging markets amid geopolitical uncertainty.',
  '投資家たちは地政学的不確実性の中、不安定な新興市場への資本投入に警戒している。',
  'The public has grown increasingly wary of claims made by pharmaceutical companies regarding new treatments.',
  '国民は製薬会社が新しい治療法について行う主張にますます慎重になっている。'),
(1893, 'criminality', '犯罪性;犯罪行為', '/ˌkrɪmɪˈnæləti/', 'クリミナリティ',
  'The report highlighted the link between urban poverty and rising criminality in marginalized neighborhoods.',
  'その報告書は都市の貧困と社会的に疎外された地域での犯罪行為の増加との関連を浮き彫りにした。',
  'Experts argue that addressing the root causes of criminality is far more effective than merely increasing prison sentences.',
  '専門家は犯罪性の根本原因に対処することは単に刑期を延ばすよりもはるかに効果的であると主張する。'),
(1894, 'vandalism', '(文化・芸術などの)破壊行為', '/ˈvændəlɪzəm/', 'ヴァンダリズム',
  'The museum installed state-of-the-art surveillance systems to protect priceless exhibits from vandalism.',
  'その美術館は貴重な展示品を破壊行為から守るために最先端の監視システムを設置した。',
  'Acts of vandalism against public monuments sparked a heated debate about historical memory and cultural heritage.',
  '公共の記念碑に対する破壊行為は歴史的記憶と文化遺産についての激しい議論を引き起こした。'),
(1895, 'sanitation', '(公衆)衛生', '/ˌsænɪˈteɪʃən/', 'サニテイション',
  'Improving sanitation infrastructure in developing nations is critical to reducing the spread of waterborne diseases.',
  '発展途上国の衛生インフラの改善は水系感染症の拡大を減らすために不可欠である。',
  'The humanitarian organization deployed teams to restore sanitation facilities in communities devastated by the earthquake.',
  'その人道支援組織は地震で壊滅した地域社会に衛生施設を復旧するためにチームを派遣した。'),
(1896, 'setback', '(進歩・発展の)障害、妨げ', '/ˈsetbæk/', 'セットバック',
  'The failure of the clinical trial was a major setback for the pharmaceutical company''s drug development program.',
  '臨床試験の失敗はその製薬会社の新薬開発プログラムにとって大きな障害だった。',
  'Despite numerous setbacks, the engineering team persevered and eventually completed the bridge ahead of schedule.',
  '数多くの妨げにもかかわらず、エンジニアリングチームは粘り強く取り組み、最終的に予定より早く橋を完成させた。'),
(1898, 'affluent', '裕福な、(経済的に)豊かな', '/ˈæfluənt/', 'アフルエント',
  'The tax reform disproportionately benefits affluent households while placing a heavier burden on the middle class.',
  'その税制改革は裕福な世帯に不均衡に恩恵を与える一方で、中間層により重い負担を課している。',
  'Affluent nations have a moral obligation to contribute more generously to global humanitarian relief efforts.',
  '裕福な国々は世界的な人道支援活動により寛大に貢献する道義的義務がある。'),
(1899, 'rundown', '概要、(手短な)報告', '/ˈrʌndaʊn/', 'ランダウン',
  'The manager provided a quick rundown of the quarterly performance figures before the board meeting commenced.',
  'マネージャーは取締役会が開始する前に四半期の業績数値の概要を手短に説明した。',
  'Could you give me a rundown of the key findings from the environmental impact assessment?',
  '環境影響評価の主要な調査結果の概要を教えていただけますか。'),
(1900, 'formidable', '〈敵・問題などが〉手ごわい', '/ˈfɔːrmɪdəbl/', 'フォーミダブル',
  'The candidate faces a formidable challenge in winning over voters who have long been loyal to the opposition.',
  'その候補者は長年野党に忠実だった有権者を取り込むという手ごわい課題に直面している。',
  'The sheer scale of the infrastructure project presents formidable logistical and financial obstacles.',
  'そのインフラプロジェクトの規模の大きさは手ごわい物流的・財政的障害を提示している。');
