-- words テーブル INSERT文 (No.1901 ~ No.1950)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1901, 'deregulate', '〈商取引など〉の規制を解く', '/diːˈreɡjəleɪt/', 'ディレギュレイト',
  'The government''s decision to deregulate the telecommunications industry led to increased competition and lower prices.',
  '政府が通信産業の規制を解くという決定は競争の激化と価格の低下をもたらした。',
  'Economists remain divided on whether deregulating the financial sector would stimulate growth or invite reckless speculation.',
  '金融部門の規制を解くことが成長を促進するのか無謀な投機を招くのか、経済学者の間で意見が分かれている。'),
(1902, 'erupt', '〈暴動などが〉勃発する;噴火する;(感情を)爆発させる', '/ɪˈrʌpt/', 'イラプト',
  'Violence erupted in the capital after the government announced sweeping austerity measures.',
  '政府が大規模な緊縮財政措置を発表した後、首都で暴動が勃発した。',
  'The long-dormant volcano erupted without warning, forcing the immediate evacuation of nearby communities.',
  '長い間休眠していた火山が警告なしに噴火し、近隣のコミュニティの即時避難を余儀なくさせた。'),
(1903, 'diminutive', '非常に小さい、小型の', '/dɪˈmɪnjətɪv/', 'ディミニュティヴ',
  'Despite her diminutive stature, the attorney commanded the courtroom with her formidable presence and sharp intellect.',
  '小柄な体格にもかかわらず、その弁護士は圧倒的な存在感と鋭い知性で法廷を支配した。',
  'The diminutive device, no larger than a thumbnail, is capable of storing an astonishing volume of data.',
  '親指の爪ほどの大きさしかないその小型の装置は、驚くべき量のデータを保存することができる。'),
(1904, 'benchmark', '基準、尺度', '/ˈbentʃmɑːrk/', 'ベンチマーク',
  'The country''s universal healthcare system is often cited as a benchmark for other nations to emulate.',
  'その国の国民皆保険制度は他の国が見習うべき基準としてしばしば引用される。',
  'The committee established rigorous benchmarks against which the success of the educational reform would be measured.',
  '委員会は教育改革の成功を測定するための厳格な尺度を確立した。'),
(1905, 'indicative', '示して、暗示して', '/ɪnˈdɪkətɪv/', 'インディカティヴ',
  'The sharp decline in consumer spending is indicative of a broader loss of confidence in the economy.',
  '消費支出の急激な減少は経済に対するより広範な信頼の喪失を示している。',
  'Her reluctance to disclose the terms of the agreement was indicative of deeper tensions within the coalition.',
  '合意の条件を開示することへの彼女の消極的な姿勢は連合内のより深い緊張を暗示していた。'),
(1906, 'reliant', '依存している', '/rɪˈlaɪənt/', 'リライアント',
  'Many developing nations remain heavily reliant on foreign aid to sustain their healthcare infrastructure.',
  '多くの発展途上国は医療インフラを維持するために外国の援助に大きく依存している。',
  'The region''s economy is dangerously reliant on a single commodity, leaving it vulnerable to market fluctuations.',
  'その地域の経済は単一の商品に危険なほど依存しており、市場の変動に対して脆弱な状態にある。'),
(1907, 'prosecute', '〈人〉を起訴する', '/ˈprɑːsɪkjuːt/', 'プロシキュート',
  'The district attorney vowed to prosecute all individuals involved in the elaborate money-laundering scheme.',
  '地方検事はその精巧な資金洗浄計画に関与したすべての個人を起訴すると誓った。',
  'Authorities warned that anyone caught illegally dumping hazardous waste would be prosecuted to the fullest extent of the law.',
  '当局は有害廃棄物を不法投棄した者は法の及ぶ最大限の範囲で起訴すると警告した。'),
(1908, 'stunning', 'とても美しい、魅力的な;驚くべき、衝撃的な', '/ˈstʌnɪŋ/', 'スタニング',
  'The gallery unveiled a stunning collection of impressionist paintings that had been in private hands for decades.',
  'そのギャラリーは何十年も個人所有だった印象派絵画のとても美しいコレクションを公開した。',
  'The underdog candidate''s stunning victory in the election sent shockwaves through the political establishment.',
  '劣勢だった候補者の衝撃的な選挙勝利は政治体制に衝撃を与えた。'),
(1910, 'addictive', '中毒性の、依存性の;病みつきになる', '/əˈdɪktɪv/', 'アディクティヴ',
  'Health experts have called for stricter regulation of addictive substances that are freely available to minors.',
  '健康専門家は未成年者が自由に入手できる中毒性のある物質に対するより厳しい規制を求めている。',
  'The game''s addictive design, which exploits psychological reward mechanisms, has drawn criticism from child welfare advocates.',
  '心理的報酬メカニズムを利用したそのゲームの病みつきになるデザインは児童福祉の擁護者から批判を受けている。'),
(1911, 'plead', '(有罪・無罪)を認める、主張する;嘆願する', '/pliːd/', 'プリード',
  'The defendant chose to plead not guilty, insisting that the evidence against him was entirely circumstantial.',
  '被告は自分に対する証拠は完全に状況証拠であると主張し、無罪を認めることを選んだ。',
  'Environmental groups pleaded with the government to halt construction of the dam before irreversible damage was done.',
  '環境団体は取り返しのつかない被害が生じる前にダム建設を中止するよう政府に嘆願した。'),
(1912, 'traumatic', '心的外傷を残す', '/trɔːˈmætɪk/', 'トロマティック',
  'Survivors of the disaster received counseling to help them cope with the traumatic experience.',
  '災害の生存者たちは心的外傷を残す経験に対処するためのカウンセリングを受けた。',
  'Research suggests that traumatic childhood events can have lasting effects on an individual''s mental health.',
  '研究は心的外傷を残す幼少期の出来事が個人の精神的健康に永続的な影響を及ぼしうることを示唆している。'),
(1913, 'contradictory', '〈話・考えなどが〉矛盾している', '/ˌkɑːntrəˈdɪktəri/', 'コントラディクトリー',
  'The witnesses provided contradictory accounts of the incident, making it difficult for the jury to establish the facts.',
  '証人たちは事件について矛盾した証言をし、陪審が事実を確定することを困難にした。',
  'The minister issued contradictory statements about the policy, undermining public confidence in the government''s competence.',
  '大臣はその政策について矛盾した声明を発表し、政府の能力に対する国民の信頼を損なった。'),
(1914, 'hierarchical', '〈社会・組織などが〉階層的な、階級制の', '/ˌhaɪəˈrɑːrkɪkəl/', 'ハイアラーキカル',
  'The traditional hierarchical structure of the corporation stifled innovation and discouraged employees from voicing dissent.',
  'その企業の伝統的な階層的構造はイノベーションを抑制し、従業員が異議を唱えることを妨げた。',
  'Many modern organizations are abandoning hierarchical management models in favor of more collaborative frameworks.',
  '多くの現代の組織は階級制の管理モデルを捨て、より協力的な枠組みを採用している。'),
(1915, 'populous', '人口の多い、人口密度の高い', '/ˈpɑːpjələs/', 'ポピュラス',
  'Providing adequate public transportation in the most populous cities remains a formidable challenge for urban planners.',
  '最も人口の多い都市で十分な公共交通機関を提供することは都市計画者にとって依然として困難な課題である。',
  'The populous coastal regions are particularly vulnerable to the devastating effects of rising sea levels.',
  '人口密度の高い沿岸地域は海面上昇の壊滅的な影響に対して特に脆弱である。'),
(1916, 'raid', '襲撃、急襲;(警察による)踏み込み、手入れ;〈人・場所〉を急襲する', '/reɪd/', 'レイド',
  'The police conducted a dawn raid on several properties suspected of being used for illegal drug manufacturing.',
  '警察は違法薬物の製造に使用されている疑いのある複数の物件に早朝の踏み込みを行った。',
  'The daring raid on the enemy''s supply depot severely disrupted their logistical operations for weeks.',
  '敵の補給基地への大胆な急襲は数週間にわたって彼らの兵站活動を深刻に混乱させた。'),
(1917, 'humanitarian', '人道的な、博愛主義の', '/hjuːˌmænɪˈteriən/', 'ヒューマニテリアン',
  'International organizations mobilized a massive humanitarian effort to deliver food and medicine to the war-torn region.',
  '国際機関は戦争で荒廃した地域に食料と医薬品を届けるために大規模な人道的活動を動員した。',
  'The philanthropist was awarded the Nobel Peace Prize for her lifelong humanitarian contributions to refugee welfare.',
  'その慈善家は難民の福祉に対する生涯にわたる人道的貢献でノーベル平和賞を授与された。'),
(1918, 'workload', '(一定期間に行うべき)仕事量、ノルマ', '/ˈwɜːrkloʊd/', 'ワークロウド',
  'The relentless workload placed on junior doctors has been linked to increased rates of burnout and medical errors.',
  '若手医師に課せられた絶え間ない仕事量は燃え尽き症候群と医療ミスの増加に関連している。',
  'Automating routine administrative tasks could significantly reduce the workload of overstretched teaching staff.',
  '日常的な事務作業を自動化すれば、過重な負担を抱える教職員の仕事量を大幅に削減できるだろう。'),
(1919, 'monopoly', '(事業などの)独占(権)、専売', '/məˈnɑːpəli/', 'モノポリー',
  'The government moved to break up the tech giant''s monopoly over the online advertising market.',
  '政府はそのテック大手のオンライン広告市場に対する独占を解体する措置を講じた。',
  'Critics argue that granting any single entity a monopoly on essential services inevitably leads to consumer exploitation.',
  '批評家たちは、いかなる単一の主体にも不可欠なサービスの独占権を与えることは必然的に消費者の搾取につながると主張する。'),
(1920, 'finalize', '〈計画・契約など〉を最終的に決定する', '/ˈfaɪnəlaɪz/', 'ファイナライズ',
  'The two governments are expected to finalize the bilateral trade agreement by the end of the fiscal year.',
  '両政府は会計年度末までに二国間貿易協定を最終的に決定する見通しである。',
  'After months of negotiation, the board finally finalized the terms of the merger with its competitor.',
  '数ヶ月の交渉の末、取締役会はついに競合他社との合併条件を最終的に決定した。'),
(1922, 'standstill', '行き詰まり、立ち止まること', '/ˈstændstɪl/', 'スタンドスティル',
  'The nationwide strike brought public transportation to a complete standstill, stranding millions of commuters.',
  '全国的なストライキが公共交通機関を完全な行き詰まりに追い込み、何百万人もの通勤者を立ち往生させた。',
  'Peace negotiations reached a standstill when neither side was willing to make concessions on territorial disputes.',
  '領土紛争に関してどちらの側も譲歩する意思がなく、和平交渉は行き詰まりに達した。'),
(1923, 'extraterrestrial', '地球外の;地球外生物', '/ˌekstrətəˈrestriəl/', 'エクストラテレストリアル',
  'The discovery of microbial fossils on Mars would constitute the first definitive evidence of extraterrestrial life.',
  '火星上の微生物化石の発見は地球外生命の最初の決定的な証拠となるだろう。',
  'Scientists have deployed sophisticated radio telescopes in the hope of detecting signals from extraterrestrial civilizations.',
  '科学者たちは地球外文明からの信号を検出することを期待して高度な電波望遠鏡を配備した。'),
(1924, 'consolidate', '~をまとめる、統合する;〈地位・権力など〉を強固にする', '/kənˈsɑːlɪdeɪt/', 'コンソリデイト',
  'The newly appointed CEO sought to consolidate the company''s fragmented operations under a single management structure.',
  '新しく任命されたCEOは会社の分散した事業を単一の管理体制の下に統合しようとした。',
  'After winning the election by a narrow margin, the president moved swiftly to consolidate her political power.',
  '僅差で選挙に勝利した後、大統領は迅速に政治的権力を強固にする行動を取った。'),
(1925, 'invariably', 'いつも、決まって', '/ɪnˈveriəbli/', 'インヴェリアブリー',
  'Attempts to implement sweeping reforms without stakeholder consultation invariably encounter fierce resistance.',
  '利害関係者との協議なしに大規模な改革を実施しようとする試みはいつも激しい抵抗に遭う。',
  'The professor invariably arrived ten minutes early to class, meticulously arranging his notes before the lecture began.',
  'その教授は決まって授業の10分前に到着し、講義が始まる前に几帳面にノートを整理していた。'),
(1926, 'prevalence', '普及、普及率', '/ˈprevələns/', 'プレヴァレンス',
  'The alarming prevalence of antibiotic-resistant bacteria has prompted calls for a fundamental overhaul of prescribing practices.',
  '抗生物質耐性菌の憂慮すべき普及率は処方慣行の根本的な見直しの要求を促している。',
  'A recent study documented the growing prevalence of mental health disorders among university students worldwide.',
  '最近の研究は世界中の大学生の間で精神的健康障害の普及率が高まっていることを記録した。'),
(1927, 'populace', '(ある国の)人民、一般大衆;人々', '/ˈpɑːpjələs/', 'ポピュレス',
  'The government''s failure to address rising food prices fueled widespread discontent among the populace.',
  '政府が食料価格の上昇に対処できなかったことが一般大衆の間で広範な不満を煽った。',
  'The ruler maintained control over the populace through a combination of propaganda and surveillance.',
  'その支配者はプロパガンダと監視の組み合わせによって人民の支配を維持した。'),
(1928, 'glamorous', '魅力的な、魅惑的な', '/ˈɡlæmərəs/', 'グラマラス',
  'Behind the glamorous facade of the fashion industry lies a world of grueling schedules and intense competition.',
  'ファッション業界の魅力的な外観の裏には過酷なスケジュールと激しい競争の世界がある。',
  'The documentary revealed that the seemingly glamorous life of a diplomat is fraught with stress and personal sacrifice.',
  'そのドキュメンタリーは外交官の一見魅惑的な生活がストレスと個人的な犠牲に満ちていることを明らかにした。'),
(1929, 'stoke', '〈感情など〉をあおる、かき立てる;~に(まきなどを)くべる', '/stoʊk/', 'ストウク',
  'Inflammatory rhetoric from political leaders only served to stoke tensions between the rival communities.',
  '政治指導者による扇動的な発言は対立するコミュニティ間の緊張をあおるだけだった。',
  'The editorial accused the media of stoking public fear with sensationalist coverage of the outbreak.',
  'その社説はメディアが感染症の流行をセンセーショナルに報道して国民の恐怖をかき立てていると非難した。'),
(1930, 'ration', '[rations] 食料;(食料・物資などの)配給;~を配給する;~を(一定量に)制限する', '/ˈræʃən/', 'ラション',
  'During the siege, authorities were forced to ration drinking water to ensure equitable distribution among the population.',
  '包囲中、当局は住民への公平な分配を確保するために飲料水を配給せざるを得なかった。',
  'The soldiers survived on meager rations for weeks while awaiting the arrival of supply convoys.',
  '兵士たちは補給車列の到着を待つ間、何週間も乏しい食料で生き延びた。'),
(1931, 'deceptive', '〈見かけなどが〉当てにならない、誤解を招く;人を迷わす[だます]', '/dɪˈseptɪv/', 'ディセプティヴ',
  'The calm surface of the lake was deceptive; beneath it lay treacherous undercurrents that had claimed several lives.',
  '湖の穏やかな水面は当てにならなかった。その下には何人もの命を奪った危険な底流が潜んでいた。',
  'Consumer advocacy groups have demanded stricter penalties for companies that engage in deceptive advertising practices.',
  '消費者擁護団体は人を欺く広告慣行に従事する企業に対するより厳しい罰則を要求している。'),
(1932, 'reminisce', '懐かしむ、思い出にふける', '/ˌremɪˈnɪs/', 'レミニス',
  'The retired diplomat often reminisced about the pivotal negotiations that had shaped the post-war peace accord.',
  '引退した外交官は戦後の平和協定を形作った重要な交渉についてよく懐かしんでいた。',
  'At the reunion, former classmates reminisced fondly about their university days and the friendships they had forged.',
  '同窓会で、かつてのクラスメートたちは大学時代と築いた友情について懐かしく思い出にふけった。'),
(1934, 'agitate', '世論に訴える、運動する;〈人〉を動揺させる、〈気持ちなど〉をかき乱す', '/ˈædʒɪteɪt/', 'アジテイト',
  'Workers'' unions agitated for better conditions, staging a series of demonstrations outside the parliament building.',
  '労働組合はより良い条件を求めて運動し、議会の建物の前で一連のデモを行った。',
  'The distressing news visibly agitated the elderly woman, and her family rushed to comfort her.',
  'その悲痛なニュースは明らかにその高齢の女性を動揺させ、家族は彼女を慰めるために駆け寄った。'),
(1935, 'entail', '(必然的に)~を伴う', '/ɪnˈteɪl/', 'インテイル',
  'Transitioning to a carbon-neutral economy will entail significant investment in renewable energy infrastructure.',
  '炭素中立経済への移行は再生可能エネルギーインフラへの多大な投資を伴うだろう。',
  'The position entails frequent international travel and the ability to negotiate with stakeholders from diverse cultural backgrounds.',
  'そのポジションは頻繁な海外出張と多様な文化的背景を持つ利害関係者と交渉する能力を伴う。'),
(1936, 'detour', '回り道、迂回路', '/ˈdiːtʊr/', 'ディートゥア',
  'A landslide blocked the main highway, forcing motorists to take a lengthy detour through the mountain pass.',
  '地滑りが幹線道路を塞ぎ、運転者たちは山道を通る長い迂回路を取ることを余儀なくされた。',
  'What began as a brief detour from her academic career eventually became a lifelong commitment to humanitarian work.',
  '学問的キャリアからのほんの少しの回り道として始まったものが、最終的に人道的活動への生涯にわたる献身となった。'),
(1937, 'milestone', '画期的な事件、出来事', '/ˈmaɪlstoʊn/', 'マイルストウン',
  'The successful launch of the reusable rocket marked a historic milestone in commercial space exploration.',
  '再利用可能なロケットの打ち上げ成功は商業宇宙探査における画期的な出来事となった。',
  'Reaching the milestone of one million subscribers was a testament to the platform''s growing influence.',
  '100万人の登録者というマイルストーンに到達したことはそのプラットフォームの影響力の増大の証だった。'),
(1938, 'reclaim', '~を奪還する、取り戻す;〈土地など〉を造成する、開拓する', '/rɪˈkleɪm/', 'リクレイム',
  'The indigenous community launched a legal campaign to reclaim ancestral lands that had been seized during colonization.',
  '先住民コミュニティは植民地化の際に奪われた先祖伝来の土地を奪還するための法的キャンペーンを開始した。',
  'The city reclaimed a vast stretch of marshland to build affordable housing for its rapidly expanding population.',
  'その市は急速に拡大する人口のための手頃な住宅を建設するために広大な湿地帯を造成した。'),
(1939, 'transparent', '〈組織・活動などが〉透明性の高い;透明な、透き通った', '/trænsˈpærənt/', 'トランスペアレント',
  'Citizens demanded a more transparent decision-making process to hold government officials accountable for public expenditure.',
  '市民は政府職員に公共支出の責任を負わせるためにより透明性の高い意思決定プロセスを要求した。',
  'The biologist observed the transparent jellyfish drifting through the sunlit waters, its internal organs clearly visible.',
  '生物学者は日光の差す海中を漂う透明なクラゲを観察し、その内臓がはっきりと見えた。'),
(1940, 'dissolution', '(組織・団体などの)解体、分解、崩壊;(契約などの)解消', '/ˌdɪsəˈluːʃən/', 'ディソリューション',
  'The dissolution of the Soviet Union in 1991 fundamentally altered the geopolitical landscape of the twentieth century.',
  '1991年のソビエト連邦の解体は20世紀の地政学的景観を根本的に変えた。',
  'The court ordered the dissolution of the business partnership following irreconcilable disputes between the founding members.',
  '裁判所は創設メンバー間の和解不可能な紛争を受けて事業提携の解消を命じた。'),
(1941, 'barren', '〈土地が〉不毛の、やせた', '/ˈbærən/', 'バレン',
  'Decades of unsustainable farming practices had left the once-fertile plains barren and incapable of supporting crops.',
  '数十年にわたる持続不可能な農業慣行がかつて肥沃だった平野を不毛にし、作物を支えられない状態にした。',
  'The expedition traversed miles of barren desert before finally reaching the oasis that would serve as their base camp.',
  '探検隊は何マイルもの不毛の砂漠を横断し、ついにベースキャンプとなるオアシスにたどり着いた。'),
(1942, 'occupant', '(建物・部屋などの)占有者、居住者', '/ˈɑːkjəpənt/', 'オキュパント',
  'The building''s occupants were evacuated immediately after structural engineers declared it unsafe for habitation.',
  '構造技術者が居住に安全でないと宣言した直後に、建物の居住者たちは直ちに避難させられた。',
  'The previous occupant of the apartment had failed to pay several months'' rent, leaving the landlord with substantial losses.',
  'そのアパートの前の占有者は数ヶ月分の家賃を支払っておらず、大家に多大な損失を残した。'),
(1943, 'land', '〈職など〉を手に入れる', '/lænd/', 'ランド',
  'After years of perseverance, the aspiring actress finally landed a leading role in a critically acclaimed production.',
  '何年もの忍耐の末、その志望の女優はついに批評家に絶賛された作品で主役を手に入れた。',
  'The young engineer landed a prestigious position at a top aerospace firm, fulfilling a childhood dream.',
  'その若い技術者はトップの航空宇宙企業で名誉ある職を手に入れ、子供の頃の夢を叶えた。'),
(1944, 'onlooker', '傍観者、野次馬', '/ˈɑːnlʊkər/', 'オンルッカー',
  'A crowd of onlookers gathered at the scene of the accident, impeding the efforts of emergency responders.',
  '事故現場に野次馬の群衆が集まり、救急隊員の活動を妨げた。',
  'Horrified onlookers watched as the historic cathedral was engulfed in flames, helpless to intervene.',
  '恐怖におののく傍観者たちは歴史的な大聖堂が炎に包まれるのを介入できずに見守った。'),
(1946, 'racket', '大騒ぎ、(不快な)騒音', '/ˈrækɪt/', 'ラケット',
  'The construction crew made such a racket that residents in the neighboring apartments could not concentrate on their work.',
  '建設作業員があまりにも大騒ぎしたので、隣接するアパートの住民は仕事に集中できなかった。',
  'The children''s racket in the hallway drew a stern reprimand from the librarian, who insisted on absolute silence.',
  '廊下での子供たちの騒音は絶対的な静寂を求める司書からの厳しい叱責を招いた。'),
(1947, 'humane', '人道的な、残酷でない', '/hjuːˈmeɪn/', 'ヒューメイン',
  'Animal rights activists have long campaigned for more humane conditions in industrial livestock farming.',
  '動物の権利活動家は工業的畜産におけるより人道的な条件を求めて長い間運動してきた。',
  'The judge advocated for a more humane approach to criminal sentencing, emphasizing rehabilitation over punishment.',
  'その裁判官は刑事判決に対するより人道的なアプローチを提唱し、罰よりも更生を重視した。'),
(1948, 'withhold', '~を与えずにおく、保留する', '/wɪðˈhoʊld/', 'ウィズホウルド',
  'The government decided to withhold funding from institutions that failed to meet the newly established compliance standards.',
  '政府は新たに設定されたコンプライアンス基準を満たさない機関への資金を保留することを決定した。',
  'The witness was accused of deliberately withholding critical information that could have altered the outcome of the trial.',
  'その証人は裁判の結果を変えた可能性のある重要な情報を意図的に与えずにおいたとして非難された。'),
(1949, 'obsessive', '頭から離れない、強迫観念の', '/əbˈsesɪv/', 'オブセシヴ',
  'His obsessive attention to detail, while producing flawless results, often delayed projects beyond their deadlines.',
  '彼の頭から離れないほどの細部へのこだわりは完璧な結果を生み出す一方で、しばしばプロジェクトを期限を超えて遅延させた。',
  'Psychologists warn that obsessive use of social media can erode self-esteem and exacerbate feelings of isolation.',
  '心理学者はソーシャルメディアの強迫観念的な使用が自尊心を蝕み、孤立感を悪化させる可能性があると警告している。'),
(1950, 'proposition', '(取引などにおける)提案、申し出;(対処すべき)事柄、主張', '/ˌprɑːpəˈzɪʃən/', 'プロポジション',
  'The venture capitalist dismissed the startup''s proposition as financially unviable given the current market conditions.',
  'そのベンチャーキャピタリストは現在の市場状況を考えるとそのスタートアップの提案は財政的に実行不可能だとして退けた。',
  'Reforming the entire electoral system is a daunting proposition that would require broad bipartisan support.',
  '選挙制度全体を改革することは広範な超党派の支持を必要とする困難な事柄である。');
