-- words テーブル INSERT文 (No.1951 ~ No.2000)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1951, 'scrutinize', '~を綿密に調べる', '/ˈskruːtənaɪz/', 'スクルーティナイズ',
  'The auditors were brought in to scrutinize the company''s financial records for any irregularities.',
  '監査人が会社の財務記録に不正がないか綿密に調べるために招かれた。',
  'Legislators must scrutinize every clause of the proposed bill before casting their votes.',
  '立法者は投票する前に提案された法案のすべての条項を綿密に調べなければならない。'),
(1952, 'containment', '(好ましくないものの)制御、封じ込め', '/kənˈteɪnmənt/', 'コンテインメント',
  'The government''s containment strategy proved effective in limiting the spread of the infectious disease.',
  '政府の封じ込め戦略は感染症の拡大を制限するのに効果的であった。',
  'International cooperation is essential for the containment of nuclear proliferation threats.',
  '核拡散の脅威の制御には国際協力が不可欠である。'),
(1953, 'distressing', '悲惨な、痛ましい、つらい', '/dɪˈstresɪŋ/', 'ディストレシング',
  'The documentary presented distressing footage of civilians caught in the crossfire of the armed conflict.',
  'そのドキュメンタリーは武力紛争の銃撃戦に巻き込まれた民間人の痛ましい映像を提示した。',
  'It is deeply distressing to witness the erosion of democratic institutions in once-stable nations.',
  'かつて安定していた国々で民主的制度が侵食されるのを目撃するのは非常につらいことである。'),
(1954, 'impair', '〈能力など〉を弱める、損なう', '/ɪmˈper/', 'インペア',
  'Prolonged exposure to excessive noise levels can permanently impair one''s hearing.',
  '過度な騒音レベルに長期間さらされると、聴力が永久に損なわれる可能性がある。',
  'Sleep deprivation has been shown to significantly impair cognitive function and decision-making abilities.',
  '睡眠不足は認知機能と意思決定能力を著しく弱めることが示されている。'),
(1955, 'resurrect', '〈失われたもの・忘れられたものなど〉を復活させる', '/ˈrezərekt/', 'レザレクト',
  'The new director sought to resurrect the abandoned urban renewal project that had stalled for years.',
  '新しい局長は何年も停滞していた放棄された都市再生プロジェクトを復活させようとした。',
  'Scholars have made efforts to resurrect endangered languages before they vanish entirely from human memory.',
  '学者たちは絶滅危惧言語が人類の記憶から完全に消える前に復活させる努力をしてきた。'),
(1956, 'discontent', '不満、不平', '/ˌdɪskənˈtent/', 'ディスコンテント',
  'Rising unemployment and stagnant wages have fueled widespread discontent among the working class.',
  '失業率の上昇と賃金の停滞が労働者階級の間で広範な不満を煽っている。',
  'The government''s failure to address public discontent eventually led to mass protests in the capital.',
  '国民の不平に対処しなかった政府の失態は最終的に首都での大規模な抗議活動につながった。'),
(1958, 'conspiracy', '陰謀、共謀', '/kənˈspɪrəsi/', 'コンスピラシー',
  'The executives were charged with conspiracy to defraud investors through the manipulation of stock prices.',
  '幹部たちは株価の操作を通じて投資家を欺く陰謀の容疑で起訴された。',
  'Historians have long debated whether the assassination was the act of a lone gunman or part of a larger conspiracy.',
  '歴史家たちはその暗殺が単独犯の行為であったか、より大きな共謀の一部であったかを長い間議論してきた。'),
(1959, 'lousy', 'お粗末な、ひどい', '/ˈlaʊzi/', 'ラウジー',
  'The restaurant received scathing reviews due to its lousy service and overpriced menu.',
  'そのレストランはお粗末なサービスと割高なメニューのために酷評を受けた。',
  'Despite investing millions in the campaign, the candidate''s lousy debate performance cost him the election.',
  '選挙運動に数百万を投資したにもかかわらず、候補者のひどい討論のパフォーマンスが選挙の敗因となった。'),
(1960, 'legislature', '議会、立法府', '/ˈledʒɪsleɪtʃər/', 'レジスレイチャー',
  'The state legislature passed a landmark bill aimed at reducing carbon emissions by fifty percent.',
  '州議会は炭素排出量を50パーセント削減することを目指す画期的な法案を可決した。',
  'Members of the legislature engaged in heated debate over the proposed amendments to the immigration law.',
  '立法府の議員たちは移民法の改正案について激しい議論を交わした。'),
(1961, 'interrogation', '尋問、取り調べ', '/ɪnˌterəˈɡeɪʃən/', 'インテロゲイション',
  'The suspect endured hours of relentless interrogation before finally confessing to the crime.',
  '容疑者は犯行を自白するまで何時間もの容赦ない尋問に耐えた。',
  'Human rights advocates have called for stricter oversight of interrogation techniques used by intelligence agencies.',
  '人権擁護者たちは情報機関が使用する取り調べ手法のより厳格な監視を求めている。'),
(1962, 'itchy', 'かゆい、むずむずする', '/ˈɪtʃi/', 'イッチー',
  'The allergic reaction left her with an unbearably itchy rash that persisted for several days.',
  'アレルギー反応により、彼女は数日間続く耐えられないほどかゆい発疹に悩まされた。',
  'After weeks of confinement, the restless explorer grew itchy to embark on another expedition.',
  '何週間も閉じ込められた後、落ち着きのない探検家は別の探検に出発したくてむずむずしていた。'),
(1963, 'scheme', '事業計画;陰謀;〈陰謀など〉を企てる', '/skiːm/', 'スキーム',
  'The government unveiled an ambitious scheme to revitalize declining rural communities through infrastructure investment.',
  '政府はインフラ投資を通じて衰退する農村地域を活性化する野心的な事業計画を発表した。',
  'The fraudulent scheme bilked thousands of unsuspecting investors out of their life savings.',
  'その不正な陰謀は何千人もの疑いを持たない投資家から生涯の貯蓄をだまし取った。'),
(1964, 'vocalization', '発声;発生された音[声]', '/ˌvoʊkələˈzeɪʃən/', 'ヴォーカリゼイション',
  'Researchers have discovered that certain species of whales possess remarkably complex vocalizations.',
  '研究者たちは特定の種のクジラが非常に複雑な発声を持つことを発見した。',
  'The infant''s early vocalizations are a crucial precursor to the development of language acquisition.',
  '乳児の初期の発声は言語習得の発達における重要な前兆である。'),
(1965, 'obsolescence', '廃れること、旧式化', '/ˌɑːbsəˈlesəns/', 'アブソレセンス',
  'Planned obsolescence is a controversial strategy in which manufacturers design products with a limited lifespan.',
  '計画的旧式化とは、メーカーが製品を限られた寿命で設計する物議を醸す戦略である。',
  'The rapid obsolescence of electronic devices contributes significantly to the growing problem of e-waste.',
  '電子機器の急速な旧式化は増大する電子廃棄物の問題に大きく寄与している。'),
(1966, 'preferential', '優先的な、優遇の', '/ˌprefəˈrenʃəl/', 'プレファレンシャル',
  'Developing nations often negotiate preferential trade agreements to gain better access to foreign markets.',
  '発展途上国は外国市場へのより良いアクセスを得るために優先的な貿易協定を交渉することが多い。',
  'Critics accused the administration of granting preferential treatment to politically connected corporations.',
  '批評家たちは政権が政治的コネのある企業に優遇措置を与えていると非難した。'),
(1967, 'pesky', 'うるさい、やっかいな', '/ˈpeski/', 'ペスキー',
  'The pesky mosquitoes made it nearly impossible for the researchers to conduct fieldwork in the tropical wetlands.',
  'うるさい蚊のせいで研究者たちは熱帯湿地帯でのフィールドワークをほとんど実施できなかった。',
  'A few pesky technical glitches delayed the launch of the much-anticipated software update.',
  'いくつかのやっかいな技術的不具合が待望のソフトウェアアップデートの公開を遅らせた。'),
(1968, 'janitor', '(ビル・学校などの)管理人、用務員、清掃作業員', '/ˈdʒænɪtər/', 'ジャニター',
  'The diligent janitor noticed a gas leak in the basement and immediately alerted the building''s occupants.',
  '勤勉な管理人が地下室のガス漏れに気づき、直ちにビルの居住者に警告した。',
  'After years of working as a janitor, he earned a scholarship and went on to become a renowned engineer.',
  '何年も用務員として働いた後、彼は奨学金を得て著名なエンジニアになった。'),
(1970, 'perimeter', '周囲[周辺](の長さ);境界線、防御線', '/pəˈrɪmɪtər/', 'ペリミター',
  'Security forces established a strict perimeter around the embassy following the bomb threat.',
  '爆破予告を受けて治安部隊は大使館の周囲に厳重な防御線を敷いた。',
  'The architect calculated the perimeter of the proposed building site to determine the extent of fencing required.',
  '建築家は必要なフェンスの範囲を決定するために予定建設用地の周囲の長さを計算した。'),
(1971, 'loom', '〈困難・危険・脅威などが〉迫ってくる', '/luːm/', 'ルーム',
  'The specter of a global recession looms large as inflation continues to erode consumer purchasing power.',
  'インフレが消費者の購買力を侵食し続ける中、世界的な不況の影が大きく迫っている。',
  'With the deadline looming, the negotiators worked through the night to finalize the terms of the agreement.',
  '締め切りが迫る中、交渉者たちは協定の条件を確定するために徹夜で作業した。'),
(1972, 'respiratory', '呼吸(器)の', '/ˈrespərətɔːri/', 'レスピラトリー',
  'Chronic exposure to air pollution is a leading cause of respiratory diseases in densely populated urban areas.',
  '大気汚染への慢性的な曝露は人口密集都市部における呼吸器疾患の主な原因である。',
  'The patient was placed on a respiratory ventilator after experiencing severe difficulty breathing.',
  '患者は重度の呼吸困難を経験した後、人工呼吸器に接続された。'),
(1973, 'state-of-the-art', '最新式の、最先端の', '/ˌsteɪt əv ðə ˈɑːrt/', 'ステイトオブジアート',
  'The hospital invested in state-of-the-art diagnostic equipment to improve the accuracy of early disease detection.',
  'その病院は早期疾患発見の精度を向上させるために最先端の診断機器に投資した。',
  'The research facility boasts a state-of-the-art laboratory capable of conducting experiments at the molecular level.',
  'その研究施設は分子レベルでの実験が可能な最新式の研究室を誇っている。'),
(1974, 'assimilate', '(〈民族・文化など〉を)同化する、融合する;〈考え・情報など〉を自分のものにする', '/əˈsɪməleɪt/', 'アシミレイト',
  'Immigrants often face the challenge of trying to assimilate into a new culture while preserving their own heritage.',
  '移民はしばしば自らの遺産を守りながら新しい文化に同化しようとする課題に直面する。',
  'The analyst needed time to assimilate the vast amount of data before presenting her conclusions to the board.',
  'アナリストは取締役会に結論を提示する前に膨大なデータを自分のものにするための時間が必要だった。'),
(1975, 'refurbish', '〈建物など〉を改装する、改修する', '/ˌriːˈfɜːrbɪʃ/', 'リファービッシュ',
  'The city council approved a plan to refurbish the dilapidated waterfront district into a vibrant commercial hub.',
  '市議会は荒廃した臨海地区を活気ある商業拠点に改装する計画を承認した。',
  'The museum was closed for two years while specialists refurbished its galleries and updated the exhibition spaces.',
  '専門家がギャラリーを改修し展示スペースを刷新する間、博物館は2年間閉館していた。'),
(1976, 'conglomerate', 'コングロマリット、複合企業;寄せ集め、集合(体)', '/kənˈɡlɑːmərət/', 'コングロマリット',
  'The media conglomerate owns dozens of television networks, newspapers, and digital platforms across the globe.',
  'そのメディア複合企業は世界中で数十のテレビネットワーク、新聞、デジタルプラットフォームを所有している。',
  'Antitrust regulators scrutinized the merger, fearing the resulting conglomerate would stifle market competition.',
  '独占禁止規制当局は、合併により生まれるコングロマリットが市場競争を抑圧することを懸念して合併を精査した。'),
(1977, 'simulate', '~の模擬実験をする、~をシミュレーションする', '/ˈsɪmjəleɪt/', 'シミュレイト',
  'Engineers used advanced software to simulate the structural integrity of the bridge under extreme seismic conditions.',
  '技術者たちは極端な地震条件下での橋の構造的完全性をシミュレーションするために先進的なソフトウェアを使用した。',
  'The flight academy employs sophisticated devices that simulate real-world turbulence to train aspiring pilots.',
  'その航空学校はパイロット志望者を訓練するために実際の乱気流を模擬実験する精巧な装置を使用している。'),
(1978, 'doom', '~を(悪い方向に)運命づける;運命', '/duːm/', 'ドゥーム',
  'The prolonged drought doomed the harvest, leaving thousands of farming families facing starvation.',
  '長期化した干ばつが収穫を台無しにし、何千もの農家が飢餓に直面することになった。',
  'Many analysts predicted that the company''s refusal to innovate would doom it to irrelevance.',
  '多くのアナリストはその企業の革新への拒否が無用の存在へと運命づけるだろうと予測した。'),
(1979, 'stockpile', '(食料・兵器などの)備蓄;~を備蓄する', '/ˈstɑːkpaɪl/', 'ストックパイル',
  'Nations began to stockpile essential medical supplies in anticipation of a second wave of the pandemic.',
  '各国はパンデミックの第二波を見越して必要な医療物資を備蓄し始めた。',
  'The discovery of a massive weapons stockpile in the rebel-held territory alarmed international observers.',
  '反政府勢力が支配する地域での大量の兵器備蓄の発見は国際的な監視者たちを警戒させた。'),
(1980, 'inconsequential', '取るに足りない、重要でない', '/ɪnˌkɑːnsəˈkwenʃəl/', 'インコンシクエンシャル',
  'What may appear to be an inconsequential policy change could have far-reaching implications for the economy.',
  '取るに足りない政策変更に見えるものが経済に広範な影響を及ぼす可能性がある。',
  'The diplomat dismissed the territorial dispute as inconsequential, a stance that later proved dangerously naive.',
  '外交官はその領土紛争を重要でないとして退けたが、その姿勢は後に危険なほど甘かったことが判明した。'),
(1982, 'eyewitness', '目撃者', '/ˈaɪwɪtnəs/', 'アイウィットネス',
  'The prosecution''s case hinged on the testimony of a single eyewitness who claimed to have seen the defendant at the scene.',
  '検察側の訴訟は被告を現場で見たと主張するたった一人の目撃者の証言にかかっていた。',
  'Eyewitness accounts of the disaster painted a harrowing picture of chaos and destruction.',
  '災害の目撃者の証言は混乱と破壊の悲惨な光景を描き出した。'),
(1983, 'commodity', '商品、売買品;有用なもの', '/kəˈmɑːdəti/', 'コモディティ',
  'Clean water has become a precious commodity in regions devastated by prolonged conflict and infrastructure collapse.',
  '長期にわたる紛争とインフラの崩壊で荒廃した地域では清潔な水が貴重な商品となっている。',
  'The volatile fluctuation in commodity prices has destabilized the economies of resource-dependent nations.',
  '商品価格の不安定な変動が資源依存型国家の経済を不安定にしている。'),
(1984, 'notorious', '悪名高い、(よくないことで)よく知られた', '/noʊˈtɔːriəs/', 'ノトーリアス',
  'The region is notorious for its treacherous mountain passes that have claimed numerous lives over the centuries.',
  'その地域は何世紀にもわたって多くの命を奪ってきた危険な山道で悪名高い。',
  'The notorious hacker was finally apprehended after a multinational investigation spanning three continents.',
  'その悪名高いハッカーは三大陸にまたがる多国間捜査の末にようやく逮捕された。'),
(1985, 'shot', '(賭けなどの)勝ち目、可能性;試み、挑戦', '/ʃɑːt/', 'ショット',
  'Despite the overwhelming odds, the underdog team still has a shot at winning the championship.',
  '圧倒的に不利であるにもかかわらず、劣勢のチームにはまだ優勝の可能性がある。',
  'She decided to take a shot at starting her own business after years of working in corporate finance.',
  '彼女は企業金融で何年も働いた後、自分の事業を始めることに挑戦することに決めた。'),
(1986, 'emigrate', '(自国から他国に)移住する', '/ˈemɪɡreɪt/', 'エミグレイト',
  'Thousands of skilled professionals emigrate from developing countries each year in search of better opportunities.',
  '毎年何千人もの熟練した専門家がより良い機会を求めて発展途上国から移住する。',
  'Her grandparents emigrated from Eastern Europe in the aftermath of the Second World War.',
  '彼女の祖父母は第二次世界大戦後に東欧から移住した。'),
(1987, 'cede', '〈土地・権利など〉を譲渡する、割譲する', '/siːd/', 'シード',
  'Under the terms of the treaty, the defeated nation was forced to cede vast tracts of territory to the victor.',
  '条約の条件に基づき、敗戦国は広大な領土を戦勝国に割譲することを強いられた。',
  'The company refused to cede control of its intellectual property despite mounting pressure from its partners.',
  'その企業はパートナーからの圧力が高まっているにもかかわらず知的財産の管理を譲渡することを拒否した。'),
(1988, 'degrade', '~を分解する、劣化させる;〈価値・品位など〉を低下させる;〈人〉を降格させる', '/dɪˈɡreɪd/', 'ディグレイド',
  'Industrial pollutants continue to degrade the quality of soil and groundwater in the surrounding area.',
  '産業汚染物質が周辺地域の土壌と地下水の質を劣化させ続けている。',
  'The relentless media scrutiny served only to degrade the reputation of an otherwise distinguished public servant.',
  '容赦ないメディアの精査はそれ以外は優れた公務員の品位を低下させるだけだった。'),
(1989, 'extremist', '過激派、過激主義者', '/ɪkˈstriːmɪst/', 'イクストリーミスト',
  'Intelligence agencies warned that extremist groups were exploiting social media to radicalize vulnerable individuals.',
  '情報機関は過激派グループがソーシャルメディアを利用して脆弱な個人を過激化させていると警告した。',
  'The government introduced sweeping legislation to combat the growing threat posed by domestic extremists.',
  '政府は国内の過激主義者がもたらす増大する脅威に対抗するために包括的な法律を導入した。'),
(1990, 'execute', '〈計画・義務など〉を実行する;~を処刑する', '/ˈeksɪkjuːt/', 'エクセキュート',
  'The military commander was tasked with executing a highly sensitive operation behind enemy lines.',
  'その軍司令官は敵前線の背後で非常に機密性の高い作戦を実行する任務を課された。',
  'The regime was condemned internationally for executing political prisoners without due process.',
  'その政権は適正な法的手続きなしに政治犯を処刑したことで国際的に非難された。'),
(1991, 'long-lasting', '長続きする、持続的な', '/ˌlɔːŋˈlæstɪŋ/', 'ロングラスティング',
  'The peace accord established a framework for long-lasting stability in a region plagued by decades of conflict.',
  'その和平協定は数十年にわたる紛争に悩まされてきた地域の持続的な安定のための枠組みを確立した。',
  'Childhood trauma can have long-lasting psychological effects that persist well into adulthood.',
  '幼少期のトラウマは成人期まで十分に持続する長続きする心理的影響を及ぼす可能性がある。'),
(1992, 'reside', '〈事物・性質などが〉存在する、備わっている', '/rɪˈzaɪd/', 'リザイド',
  'True authority does not reside in titles or positions but in the capacity to inspire trust and confidence.',
  '真の権威は肩書きや地位にではなく、信頼と確信を鼓舞する能力に存在する。',
  'The power to amend the constitution resides exclusively with the national legislature.',
  '憲法を改正する権限は国の立法府にのみ備わっている。'),
(1994, 'hallmark', '(顕著な)特徴、特質', '/ˈhɔːlmɑːrk/', 'ホールマーク',
  'Precision and attention to detail have long been the hallmark of this renowned watchmaker.',
  '精密さと細部への注意はこの著名な時計職人の長年の特徴である。',
  'Transparency in governance is widely regarded as the hallmark of a functioning democracy.',
  '統治における透明性は機能する民主主義の特質として広く認められている。'),
(1995, 'squarely', '真っ向から、直接に', '/ˈskwerli/', 'スクエアリー',
  'The report placed the blame squarely on the regulatory authorities for failing to prevent the financial crisis.',
  '報告書は金融危機を防げなかったことの責任を規制当局に真っ向から負わせた。',
  'The candidate addressed the corruption allegations squarely, refusing to deflect or evade the questions.',
  '候補者は汚職疑惑に直接向き合い、質問をそらしたり回避したりすることを拒否した。'),
(1996, 'parameter', '限界、指針', '/pəˈræmɪtər/', 'パラミター',
  'The researchers defined strict parameters for the clinical trial to ensure the validity of the results.',
  '研究者たちは結果の妥当性を確保するために臨床試験の厳格な指針を定めた。',
  'The negotiations must operate within the parameters established by international humanitarian law.',
  '交渉は国際人道法によって定められた限界の範囲内で行われなければならない。'),
(1997, 'wield', '〈権力・影響など〉を行使する', '/wiːld/', 'ウィールド',
  'The multinational corporation wields enormous influence over trade policy in the developing world.',
  'その多国籍企業は発展途上国の貿易政策に対して莫大な影響力を行使している。',
  'Critics warned that allowing a single entity to wield such unchecked power would inevitably lead to abuse.',
  '批評家たちは単一の組織にそのような抑制のない権力を行使させることは必然的に濫用につながると警告した。'),
(1998, 'epidemic', '流行、伝染(病)', '/ˌepɪˈdemɪk/', 'エピデミック',
  'Health officials declared an epidemic after the number of confirmed cases surged beyond initial projections.',
  '確認された症例数が当初の予測を超えて急増した後、保健当局は伝染病の流行を宣言した。',
  'The opioid epidemic has devastated communities across the nation, claiming tens of thousands of lives annually.',
  'オピオイドの流行は国中の地域社会を荒廃させ、年間数万人の命を奪っている。'),
(1999, 'perilous', '危険な', '/ˈperələs/', 'ペリラス',
  'Refugees undertook the perilous journey across the open sea in overcrowded and unseaworthy vessels.',
  '難民たちは過密で航行に耐えない船で外洋を渡る危険な旅に出た。',
  'Investing heavily in a single volatile market is a perilous strategy that could result in catastrophic losses.',
  '単一の不安定な市場に多額の投資をすることは壊滅的な損失をもたらしかねない危険な戦略である。'),
(2000, 'predisposed', '(~の)傾向にある;(病気などに)なりやすい', '/ˌpriːdɪˈspoʊzd/', 'プリディスポウズド',
  'Genetic research suggests that certain individuals may be predisposed to developing cardiovascular disease.',
  '遺伝子研究は特定の個人が心血管疾患を発症しやすい傾向にある可能性を示唆している。',
  'Children raised in authoritarian households may be predisposed to accept hierarchical structures without question.',
  '権威主義的な家庭で育った子供は階層的構造を疑問なく受け入れる傾向にあるかもしれない。');
