-- words テーブル INSERT文 (No.251 ~ No.300)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(251, 'disband', '解散する、解体する', '/dɪsˈbænd/', 'ディスバンド',
  'The committee voted unanimously to disband after fulfilling its mandate.',
  '委員会はその任務を果たした後、全会一致で解散することを決議した。',
  'The guerrilla forces were persuaded to disband as part of the peace agreement.',
  'ゲリラ部隊は和平合意の一環として解体するよう説得された。'),
(252, 'somber', '(雰囲気・色などが)陰気な、暗い', '/ˈsɑːmbər/', 'サンバー',
  'A somber atmosphere pervaded the memorial service for the fallen soldiers.',
  '戦没者の追悼式典には陰気な雰囲気が漂っていた。',
  'The artist''s later works are characterized by somber tones and melancholic themes.',
  'その画家の後期の作品は暗い色調と憂鬱な主題を特徴としている。'),
(253, 'annotation', '注釈、注記', '/ˌænəˈteɪʃən/', 'アノテイション',
  'The professor''s annotations in the margins of the manuscript proved invaluable to scholars.',
  '教授が原稿の余白に書いた注釈は学者たちにとって非常に貴重なものとなった。',
  'The digital edition includes hyperlinked annotations for each obscure reference.',
  'デジタル版には各難解な引用にハイパーリンク付きの注記が含まれている。'),
(254, 'untenable', '(主張・立場などが)支持できない、擁護できない', '/ʌnˈtenəbəl/', 'アンテナブル',
  'The discovery of new evidence rendered the defendant''s alibi completely untenable.',
  '新たな証拠の発見により、被告のアリバイは完全に支持できないものとなった。',
  'Critics argued that the government''s fiscal policy was economically untenable.',
  '批評家たちは政府の財政政策が経済的に擁護できないものだと主張した。'),
(255, 'assuage', '(苦痛・不安など)を和らげる、鎮める', '/əˈsweɪdʒ/', 'アスウェイジ',
  'The minister''s reassuring speech did little to assuage public anxiety over the crisis.',
  '大臣の安心させるような演説も、危機に対する国民の不安を和らげるにはほとんど役立たなかった。',
  'She tried to assuage her guilt by donating generously to the charity.',
  '彼女は慈善団体に惜しみなく寄付することで罪悪感を鎮めようとした。'),
(256, 'flounder', 'もがく、四苦八苦する', '/ˈflaʊndər/', 'フラウンダー',
  'Without adequate funding, the startup began to flounder within its first year.',
  '十分な資金がなく、そのスタートアップ企業は最初の年で四苦八苦し始めた。',
  'The inexperienced speaker floundered when confronted with hostile questions from the audience.',
  '経験の浅いその講演者は聴衆からの敵意ある質問に直面してもがいた。'),
(257, 'pander', '(人の弱みなどに)つけ込む、迎合する', '/ˈpændər/', 'パンダー',
  'The tabloid press was accused of pandering to the public''s appetite for sensationalism.',
  'タブロイド紙は大衆のセンセーショナリズムへの欲求に迎合していると非難された。',
  'A responsible leader should never pander to extremist factions for political gain.',
  '責任ある指導者は政治的利益のために過激派に迎合すべきではない。'),
(258, 'overt', '公然の、あからさまな', '/oʊˈvɜːrt/', 'オウヴァート',
  'The nation condemned the overt military aggression against its sovereign territory.',
  'その国は主権領土に対する公然の軍事的侵略を非難した。',
  'His overt hostility toward the new policy made collaboration with colleagues difficult.',
  '新しい方針に対する彼のあからさまな敵意は同僚との協力を困難にした。'),
(259, 'antagonistic', '敵対的な、反感を持った', '/ænˌtæɡəˈnɪstɪk/', 'アンタゴニスティック',
  'The two factions remained deeply antagonistic despite repeated attempts at reconciliation.',
  '和解の試みが繰り返されたにもかかわらず、両派閥は深く敵対的なままだった。',
  'Her antagonistic attitude during negotiations undermined any prospect of a settlement.',
  '交渉中の彼女の敵対的な態度は和解の見通しを台無しにした。'),
(260, 'budge', '(かたくなな態度を)変える;少し動く', '/bʌdʒ/', 'バッジ',
  'Despite hours of persuasion, the union representatives refused to budge on their demands.',
  '何時間にもわたる説得にもかかわらず、組合の代表者たちは要求について態度を変えなかった。',
  'The heavy oak door would not budge no matter how hard he pushed.',
  'どんなに強く押しても、重いオーク材のドアは少しも動かなかった。'),
(261, 'sedentary', '座ってばかりの、体を動かさない', '/ˈsedənteri/', 'セデンテリー',
  'Medical researchers have linked sedentary lifestyles to an increased risk of cardiovascular disease.',
  '医学研究者たちは座ってばかりの生活様式と心血管疾患のリスク増加を関連づけている。',
  'Office workers are encouraged to take regular breaks to counteract the effects of sedentary work.',
  'オフィスワーカーは体を動かさない仕事の影響に対抗するために定期的に休憩を取ることが推奨されている。'),
(262, 'accentuate', '~を際立たせる、強調する', '/əkˈsentʃueɪt/', 'アクセンチュエイト',
  'The dramatic lighting was designed to accentuate the sculpture''s intricate details.',
  'その劇的な照明は彫刻の精緻な細部を際立たせるよう設計されていた。',
  'The economic downturn only served to accentuate the disparity between rich and poor.',
  '景気後退は貧富の格差を際立たせる結果となっただけだった。'),
(263, 'ember', '(消えかけている火の)残り火、燃えさし', '/ˈembər/', 'エンバー',
  'The glowing embers of the campfire cast a warm light across the clearing.',
  'キャンプファイヤーの赤く光る残り火が広場に暖かい光を投げかけていた。',
  'A single ember carried by the wind was enough to ignite the neighboring barn.',
  '風に運ばれたたった一つの燃えさしが隣の納屋に火をつけるのに十分だった。'),
(264, 'engender', '(感情・状況など)を生じさせる、引き起こす', '/ɪnˈdʒendər/', 'インジェンダー',
  'The controversial policy engendered widespread resentment among the working class.',
  'その物議を醸した政策は労働者階級の間に広範な憤りを生じさせた。',
  'Transparent governance can engender trust between citizens and their elected officials.',
  '透明性のある統治は市民と選出された公職者の間に信頼を生じさせることができる。'),
(265, 'inundate', '~に押し寄せる、殺到する;(場所)を水浸しにする', '/ˈɪnʌndeɪt/', 'イナンデイト',
  'The customer service department was inundated with complaints after the product recall.',
  '製品リコールの後、カスタマーサービス部門には苦情が殺到した。',
  'Torrential rains inundated the low-lying villages, displacing thousands of residents.',
  '豪雨が低地の村々を水浸しにし、数千人の住民が避難を余儀なくされた。'),
(266, 'rampage', '大暴れ、暴動;暴れ回る', '/ˈræmpeɪdʒ/', 'ランペイジ',
  'The escaped bull went on a rampage through the town square, overturning market stalls.',
  '逃げ出した雄牛が町の広場で大暴れし、市場の屋台をひっくり返した。',
  'Rioters rampaged through the commercial district, causing millions of dollars in damage.',
  '暴徒たちが商業地区を暴れ回り、数百万ドルの損害を引き起こした。'),
(267, 'echelon', '(組織の)階層、地位', '/ˈeʃəlɑːn/', 'エシャロン',
  'Only those in the upper echelons of management had access to the confidential report.',
  '経営の上層部にいる者だけがその機密報告書にアクセスできた。',
  'She rose through the echelons of the diplomatic corps with remarkable speed.',
  '彼女は驚くべき速さで外交団の階層を上り詰めた。'),
(268, 'disdain', '軽蔑、さげすみ', '/dɪsˈdeɪn/', 'ディスデイン',
  'The aristocrat regarded the nouveau riche with unconcealed disdain.',
  'その貴族は成金たちを隠しきれない軽蔑の目で見ていた。',
  'Her disdain for bureaucratic inefficiency motivated her to pursue administrative reform.',
  '官僚的な非効率に対する彼女のさげすみが行政改革の追求へと彼女を駆り立てた。'),
(269, 'eschew', '(好ましくないもの)を避ける、控える', '/ɪsˈtʃuː/', 'イスチュー',
  'The health-conscious entrepreneur eschewed processed food in favor of organic produce.',
  '健康志向のその起業家は加工食品を避け、有機農産物を好んだ。',
  'The monastery''s residents eschew all forms of modern technology.',
  'その修道院の住人たちは現代技術のあらゆる形態を控えている。'),
(270, 'palatable', '(食べ物が)口に合う、おいしい;(考えなどが)受け入れられる', '/ˈpælətəbəl/', 'パラタブル',
  'The chef transformed humble ingredients into a surprisingly palatable dish.',
  'そのシェフは質素な材料を驚くほどおいしい料理に変えた。',
  'The committee sought to present the austerity measures in a more palatable form.',
  '委員会は緊縮措置をより受け入れられやすい形で提示しようとした。'),
(271, 'referendum', '国民投票、住民投票', '/ˌrefəˈrendəm/', 'レファレンダム',
  'The government announced a nationwide referendum on the proposed constitutional amendment.',
  '政府は提案された憲法改正に関する全国的な国民投票を発表した。',
  'The referendum results revealed a deeply divided electorate on the issue of sovereignty.',
  '住民投票の結果は主権問題に関して有権者が深く分裂していることを明らかにした。'),
(272, 'fickle', '(人・天気などが)変わりやすい、気まぐれな', '/ˈfɪkəl/', 'フィクル',
  'The fashion industry thrives on the fickle tastes of consumers.',
  'ファッション産業は消費者の気まぐれな嗜好を糧にして繁栄している。',
  'Mountain weather is notoriously fickle, shifting from sunshine to blizzard within minutes.',
  '山の天気は変わりやすいことで有名で、数分で晴天から吹雪に変わる。'),
(273, 'tantamount', '[be tantamount to]~に等しい、~同然の', '/ˈtæntəmaʊnt/', 'タンタマウント',
  'Refusing to act in the face of such injustice is tantamount to complicity.',
  'そのような不正義を前にして行動を拒むことは共謀に等しい。',
  'The diplomat warned that the embargo would be tantamount to a declaration of war.',
  'その外交官は禁輸措置は宣戦布告同然だと警告した。'),
(274, 'placid', '穏やかな、のどかな', '/ˈplæsɪd/', 'プラシッド',
  'The placid surface of the lake mirrored the surrounding mountains perfectly.',
  '穏やかな湖面が周囲の山々を完璧に映し出していた。',
  'Despite the chaos around her, she maintained a remarkably placid demeanor.',
  '周囲の混乱にもかかわらず、彼女は驚くほど穏やかな態度を保っていた。'),
(275, 'heave', '~を(力を込めて)持ち上げる、引っ張る', '/hiːv/', 'ヒーヴ',
  'The sailors heaved the heavy anchor out of the murky water.',
  '水夫たちは濁った水から重い錨を力を込めて引き上げた。',
  'With a collective effort, the volunteers heaved the fallen tree off the roadway.',
  '全員の力を合わせて、ボランティアたちは倒木を道路から持ち上げて移動させた。'),
(276, 'scrawl', '~を走り書きする;走り書き', '/skrɔːl/', 'スクロール',
  'The physician scrawled an illegible prescription on his notepad.',
  'その医師は処方箋をメモ帳に判読不能な走り書きで書いた。',
  'A hastily written scrawl on the door warned visitors that the building was condemned.',
  'ドアに走り書きされた急ぎの文字がその建物が取り壊し予定であることを訪問者に警告していた。'),
(277, 'implore', '(人)に懇願する', '/ɪmˈplɔːr/', 'インプロア',
  'The refugees implored the border officials to grant them asylum.',
  '難民たちは国境の職員に亡命を認めてくれるよう懇願した。',
  'Environmental activists implored the corporation to cease its harmful drilling operations.',
  '環境活動家たちはその企業に有害な掘削作業を中止するよう懇願した。'),
(278, 'accost', '(見知らぬ人に)声をかける、近づく', '/əˈkɔːst/', 'アコースト',
  'A stranger accosted me on the street and demanded directions to the station.',
  '見知らぬ人が通りで私に声をかけ、駅への道順を尋ねた。',
  'Journalists accosted the politician as she emerged from the courthouse.',
  '記者たちは裁判所から出てきた政治家に近づいた。'),
(279, 'erratic', '(行動・動きなどが)不規則な、予測できない', '/ɪˈrætɪk/', 'イラティック',
  'The patient''s erratic heartbeat prompted the physician to order further tests.',
  '患者の不規則な心拍が医師にさらなる検査を指示させた。',
  'His erratic behavior at work raised concerns among his colleagues and supervisors.',
  '職場での彼の予測できない行動は同僚や上司の間に懸念を引き起こした。'),
(280, 'absolve', '(人)の罪を許す、(責任など)を免除する', '/əbˈzɑːlv/', 'アブゾルヴ',
  'The jury''s verdict absolved the defendant of all criminal charges.',
  '陪審員の評決により被告はすべての刑事告訴を免除された。',
  'No amount of charitable work can absolve a person of deliberate wrongdoing.',
  'どれだけ慈善活動をしても、意図的な不正行為の罪を許すことはできない。'),
(281, 'hoard', '(食料・金など)を蓄える、ため込む', '/hɔːrd/', 'ホード',
  'During the wartime shortages, many families hoarded essential supplies in their cellars.',
  '戦時中の物資不足の間、多くの家族が地下室に必需品をため込んだ。',
  'The investigation revealed that the executive had hoarded company funds in offshore accounts.',
  '調査により、その幹部が会社の資金をオフショア口座にため込んでいたことが明らかになった。'),
(282, 'euphoric', '多幸感に満ちた、有頂天の', '/juːˈfɔːrɪk/', 'ユーフォリック',
  'The team was euphoric after clinching the championship title in the final seconds.',
  '最後の数秒で優勝を決めた後、チームは有頂天だった。',
  'The euphoric atmosphere at the concert was infectious, spreading joy through the entire venue.',
  'コンサートの多幸感に満ちた雰囲気は伝染性があり、会場全体に喜びが広がった。'),
(283, 'incarcerate', '(人)を投獄する、監禁する', '/ɪnˈkɑːrsəreɪt/', 'インカーサレイト',
  'The regime incarcerated political dissidents without trial for years on end.',
  'その政権は政治的反体制派を裁判なしで何年も投獄した。',
  'Advocates argue that incarcerating nonviolent offenders is both costly and counterproductive.',
  '擁護者たちは非暴力犯罪者を投獄することは費用がかかる上に逆効果だと主張している。'),
(284, 'brevity', '簡潔さ;短さ', '/ˈbrevəti/', 'ブレヴィティ',
  'The diplomat was known for the brevity and precision of her public statements.',
  'その外交官は公式声明の簡潔さと正確さで知られていた。',
  'Given the brevity of our meeting, I will confine my remarks to the most pressing issues.',
  '会議の短さを考慮し、最も差し迫った問題に発言を限定します。'),
(285, 'pamper', '(人)を甘やかす', '/ˈpæmpər/', 'パンパー',
  'The luxury resort pampers its guests with personalized spa treatments and gourmet cuisine.',
  'その高級リゾートはパーソナライズされたスパトリートメントとグルメ料理で宿泊客を甘やかす。',
  'Critics warned that pampered children often struggle to cope with adversity later in life.',
  '批評家たちは甘やかされた子供は後の人生で逆境に対処するのに苦労することが多いと警告した。'),
(286, 'culpable', '(行為・怠慢などが)責められるべき、有罪の', '/ˈkʌlpəbəl/', 'カルパブル',
  'The inquiry concluded that negligent officials were culpable for the safety violations.',
  '調査は怠慢な職員が安全違反について責められるべきだと結論づけた。',
  'Whether the company is legally culpable depends on the outcome of the pending litigation.',
  'その会社が法的に有罪かどうかは係争中の訴訟の結果次第である。'),
(287, 'impervious', '(批判・影響などを)受けつけない;(水などを)通さない', '/ɪmˈpɜːrviəs/', 'インパーヴィアス',
  'The seasoned politician appeared impervious to the barrage of criticism from the opposition.',
  'その熟練した政治家は野党からの批判の集中砲火を受けつけないように見えた。',
  'The new material is impervious to water, making it ideal for outdoor construction.',
  'その新素材は水を通さないため、屋外建設に最適である。'),
(288, 'prowess', '優れた能力、腕前', '/ˈpraʊəs/', 'プラウエス',
  'The young attorney quickly gained recognition for her prowess in constitutional law.',
  'その若い弁護士は憲法学における優れた能力で早くから評価を得た。',
  'The nation''s military prowess served as a deterrent against potential aggressors.',
  'その国の軍事的な腕前が潜在的な侵略者に対する抑止力として機能した。'),
(289, 'nonchalant', '(様子・態度が)平然とした、無頓着な', '/ˌnɑːnʃəˈlɑːnt/', 'ノンシャラント',
  'Despite the gravity of the situation, she maintained a nonchalant expression throughout.',
  '事態の深刻さにもかかわらず、彼女は終始平然とした表情を保っていた。',
  'His nonchalant attitude toward the deadline infuriated his project manager.',
  '締め切りに対する彼の無頓着な態度はプロジェクトマネージャーを激怒させた。'),
(290, 'dawdle', 'ぐずぐずする、のろのろ歩く', '/ˈdɔːdəl/', 'ドードル',
  'We cannot afford to dawdle when lives are at stake in the disaster zone.',
  '災害地域で命がかかっているときにぐずぐずしている余裕はない。',
  'The children dawdled along the path, stopping to examine every wildflower they encountered.',
  '子供たちは小道をのろのろ歩き、見つけた野の花をすべて観察するために立ち止まった。'),
(291, 'capitulate', '降伏する、屈服する', '/kəˈpɪtʃuleɪt/', 'キャピチュレイト',
  'After a prolonged siege, the garrison had no choice but to capitulate to the enemy forces.',
  '長期にわたる包囲戦の後、守備隊は敵軍に降伏する以外に選択肢がなかった。',
  'The board of directors ultimately capitulated to shareholder pressure and replaced the CEO.',
  '取締役会は最終的に株主の圧力に屈服し、CEOを交代させた。'),
(292, 'rebuff', '(申し出・好意など)をはねつける;拒絶', '/rɪˈbʌf/', 'リバフ',
  'The diplomat''s peace overture was rebuffed by the hostile neighboring state.',
  'その外交官の和平の申し入れは敵対的な隣国にはねつけられた。',
  'Undeterred by the initial rebuff, the entrepreneur revised her proposal and resubmitted it.',
  '最初の拒絶にもひるまず、その起業家は提案を修正して再提出した。'),
(293, 'pedantic', '学者ぶった、知識をひけらかす', '/pɪˈdæntɪk/', 'ペダンティック',
  'His pedantic insistence on obscure grammatical rules alienated many of his students.',
  '難解な文法規則に対する彼の学者ぶったこだわりは多くの学生を遠ざけた。',
  'The reviewer''s pedantic critique focused more on minor stylistic issues than substantive content.',
  'その評論家の知識をひけらかす批評は実質的な内容よりも些細な文体上の問題に焦点を当てていた。'),
(294, 'squeamish', '(血・暴力などに)気分が悪くなりやすい', '/ˈskwiːmɪʃ/', 'スクウィーミッシュ',
  'Those who are squeamish may wish to look away during the surgical footage.',
  '気分が悪くなりやすい方は手術の映像の間は目をそらした方がよいかもしれない。',
  'The detective could not afford to be squeamish when examining the gruesome crime scene.',
  'その刑事は凄惨な犯行現場を調べる際に気分が悪くなっている場合ではなかった。'),
(295, 'diatribe', '痛烈な非難、酷評', '/ˈdaɪətraɪb/', 'ダイアトライブ',
  'The senator launched into a lengthy diatribe against the proposed immigration bill.',
  'その上院議員は提案された移民法案に対する長い痛烈な非難を展開した。',
  'What began as constructive feedback soon devolved into an unrestrained diatribe.',
  '建設的なフィードバックとして始まったものがすぐに歯止めのない酷評へと変質した。'),
(296, 'reprehensible', '(行為などが)非難に値する', '/ˌreprɪˈhensəbəl/', 'レプリヘンシブル',
  'The court described the defendant''s exploitation of vulnerable individuals as reprehensible.',
  '裁判所は被告の弱者搾取を非難に値すると述べた。',
  'It is reprehensible that such discriminatory practices persist in a modern society.',
  'このような差別的慣行が現代社会に存続していることは非難に値する。'),
(297, 'cryptic', '謎めいた、意味のわかりにくい', '/ˈkrɪptɪk/', 'クリプティック',
  'The informant left a cryptic message that only a trained analyst could decipher.',
  '情報提供者は訓練されたアナリストだけが解読できる謎めいたメッセージを残した。',
  'Her cryptic response to the journalist''s question fueled further speculation.',
  '記者の質問に対する彼女の意味のわかりにくい回答がさらなる憶測をあおった。'),
(298, 'exuberant', '(人が)元気いっぱいの、活気あふれる', '/ɪɡˈzuːbərənt/', 'イグズーバラント',
  'The exuberant crowd erupted in cheers when the hometown team scored the winning goal.',
  '地元チームが決勝ゴールを決めると、元気いっぱいの群衆は歓声を上げた。',
  'Her exuberant personality made her the natural choice to lead the welcoming committee.',
  '彼女の活気あふれる性格は彼女を歓迎委員会を率いる当然の人選とした。'),
(299, 'pallid', '(顔色が)青白い、血の気のない', '/ˈpælɪd/', 'パリッド',
  'The patient''s pallid complexion alarmed the nurse, who immediately summoned the doctor.',
  '患者の青白い顔色に看護師は驚き、すぐに医師を呼んだ。',
  'After weeks of confinement indoors, his pallid appearance betrayed his lack of sunlight.',
  '何週間も屋内に閉じこもった後、彼の血の気のない外見は日光不足を物語っていた。'),
(300, 'acrid', '(におい・味が)鼻をつく、刺激性の', '/ˈækrɪd/', 'アクリッド',
  'An acrid smell of burning rubber permeated the factory floor after the machinery malfunctioned.',
  '機械が故障した後、焼けたゴムの鼻をつくにおいが工場のフロアに充満した。',
  'The acrid fumes from the chemical spill forced the evacuation of the entire neighborhood.',
  '化学物質流出による刺激性の煙が近隣全体の避難を余儀なくさせた。');
