-- words テーブル INSERT文 (No.351 ~ No.400)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(351, 'delve', '(問題などを)掘り下げる、深く調べる', '/dɛlv/', 'デルヴ',
  'The investigative journalist decided to delve into the corporation''s financial records to uncover potential fraud.',
  'その調査報道記者は、不正の可能性を暴くためにその企業の財務記録を深く調べることにした。',
  'Before writing her dissertation, she spent months delving into the archives of 18th-century colonial correspondence.',
  '論文を書く前に、彼女は18世紀の植民地時代の書簡のアーカイブを何か月もかけて掘り下げた。'),
(352, 'embed', '~を埋め込む、はめ込む', '/ɪmˈbɛd/', 'インベッド',
  'The artisan carefully embedded precious gemstones into the surface of the ornate silver bracelet.',
  'その職人は精巧な銀のブレスレットの表面に貴重な宝石を丁寧に埋め込んだ。',
  'The values of integrity and perseverance were deeply embedded in the culture of the organization.',
  '誠実さと忍耐の価値観がその組織の文化に深く根付いていた。'),
(353, 'bestow', '(名誉・称号など)を授ける', '/bɪˈstoʊ/', 'ビストウ',
  'The university decided to bestow an honorary doctorate upon the renowned physicist for her groundbreaking contributions.',
  'その大学は画期的な貢献をした著名な物理学者に名誉博士号を授けることを決定した。',
  'The monarch bestowed the title of knight upon the soldier who had demonstrated exceptional valor in battle.',
  '君主は戦闘で並外れた勇気を示した兵士にナイトの称号を授けた。'),
(354, 'stringent', '(規則・条件などが)厳格な、厳しい', '/ˈstrɪndʒənt/', 'ストリンジェント',
  'The pharmaceutical company must comply with stringent regulations before any new drug can be approved for public use.',
  '製薬会社は新薬が一般使用の認可を受ける前に厳格な規制を遵守しなければならない。',
  'Stringent security measures were implemented at the airport following the recent series of threats.',
  '最近の一連の脅威を受けて、空港では厳しい安全対策が実施された。'),
(355, 'dissipate', '(雲・恐れなどが)消え去る;(金・時間など)を浪費する', '/ˈdɪsɪpeɪt/', 'ディシペイト',
  'The morning fog gradually dissipated as the sun rose higher and warmed the valley below.',
  '朝霧は太陽が高く昇り下の谷を温めるにつれて徐々に消え去った。',
  'He dissipated his family''s fortune on reckless investments and extravagant living within a decade.',
  '彼は10年以内に無謀な投資と贅沢な生活で一族の財産を浪費してしまった。'),
(356, 'hoax', 'でっち上げ、いたずら', '/hoʊks/', 'ホウクス',
  'The elaborate hoax involving a fabricated archaeological discovery deceived even seasoned experts in the field.',
  '捏造された考古学的発見を含む手の込んだでっち上げは、その分野のベテラン専門家さえも欺いた。',
  'Authorities eventually confirmed that the bomb threat was nothing more than a malicious hoax.',
  '当局は最終的に、爆弾脅迫は悪意あるいたずらに過ぎないと確認した。'),
(357, 'astound', '~をびっくり仰天させる', '/əˈstaʊnd/', 'アスタウンド',
  'The magician''s ability to perform seemingly impossible feats never failed to astound the audience.',
  'その手品師の一見不可能に見える技を披露する能力は、いつも観客をびっくり仰天させた。',
  'The sheer scale of the ancient ruins astounded the archaeologists who had been excavating the site for years.',
  '古代遺跡の圧倒的な規模は、何年もその場所を発掘してきた考古学者たちを驚愕させた。'),
(358, 'reinstate', '(人)を(地位・職に)復帰させる;(制度など)を復活させる', '/ˌriːɪnˈsteɪt/', 'リーインステイト',
  'After a thorough internal investigation cleared him of all allegations, the board voted to reinstate the director.',
  '徹底した内部調査で全ての疑惑が晴れた後、取締役会はその役員を復職させることを決議した。',
  'The government announced plans to reinstate the scholarship program that had been discontinued due to budget cuts.',
  '政府は予算削減で廃止されていた奨学金制度を復活させる計画を発表した。'),
(359, 'momentous', '(出来事・決定などが)極めて重大な', '/moʊˈmɛntəs/', 'モウメンタス',
  'The signing of the peace accord was a momentous occasion that brought an end to decades of conflict.',
  '和平協定の調印は、数十年にわたる紛争に終止符を打つ極めて重大な出来事だった。',
  'The scientist''s momentous discovery of a new element reshaped the entire field of chemistry.',
  'その科学者による新元素の極めて重大な発見は、化学の全分野を一変させた。'),
(360, 'adjunct', '付属物、補助的なもの', '/ˈædʒʌŋkt/', 'アジャンクト',
  'Meditation is often recommended as a useful adjunct to conventional therapy for patients suffering from anxiety.',
  '瞑想は不安に苦しむ患者にとって、従来の治療法の有用な補助手段としてしばしば推奨される。',
  'The new research center will serve as an adjunct to the existing university hospital.',
  '新しい研究センターは、既存の大学病院の付属施設として機能する予定だ。'),
(361, 'evade', '(義務・責任など)を逃れる;(質問・話題など)を避ける', '/ɪˈveɪd/', 'イヴェイド',
  'The suspect managed to evade capture for several months by constantly changing his appearance and location.',
  '容疑者は外見と居場所を絶えず変えることで、数か月間逮捕を逃れることに成功した。',
  'The politician skillfully evaded the reporter''s probing questions about the controversial policy.',
  'その政治家は物議を醸す政策についての記者の鋭い質問を巧みにかわした。'),
(362, 'benign', '(人・気候などが)穏やかな;(腫瘍が)良性の', '/bɪˈnaɪn/', 'ビナイン',
  'Much to the patient''s relief, the biopsy results confirmed that the tumor was entirely benign.',
  '患者の安堵の中、生検の結果は腫瘍が完全に良性であることを確認した。',
  'Despite his intimidating appearance, the professor had a benign demeanor that put students at ease.',
  '威圧的な外見にもかかわらず、その教授は学生を安心させる穏やかな態度を持っていた。'),
(363, 'concession', '譲歩、妥協', '/kənˈsɛʃən/', 'コンセション',
  'After prolonged negotiations, both parties agreed to make significant concessions to reach a compromise.',
  '長引く交渉の末、双方は妥協に至るために大幅な譲歩をすることに同意した。',
  'The union''s major concession on working hours paved the way for a new collective bargaining agreement.',
  '労働時間に関する組合の大きな譲歩が、新たな労働協約への道を開いた。'),
(364, 'enlighten', '(人)を啓発する、教える', '/ɪnˈlaɪtn/', 'インライトゥン',
  'The documentary aimed to enlighten the public about the devastating effects of plastic pollution on marine ecosystems.',
  'そのドキュメンタリーはプラスチック汚染が海洋生態系に及ぼす壊滅的な影響について大衆を啓発することを目的としていた。',
  'Could you enlighten me as to why the committee decided to reject our proposal without any prior discussion?',
  '委員会がなぜ事前の議論もなく私たちの提案を却下したのか教えていただけますか？'),
(365, 'preclude', '~を不可能にする、妨げる', '/prɪˈkluːd/', 'プリクルード',
  'The severe weather conditions precluded any possibility of launching the rescue helicopter that evening.',
  '悪天候のため、その晩に救助ヘリコプターを飛ばすことは一切不可能になった。',
  'His criminal record effectively precluded him from obtaining a license to practice law.',
  '彼の前科は事実上、弁護士資格を取得することを妨げた。'),
(366, 'treacherous', '裏切りの、不誠実な;(状況などが)危険な', '/ˈtrɛtʃərəs/', 'トレチャラス',
  'The treacherous mountain pass claimed the lives of several inexperienced climbers every year.',
  'その危険な山道は毎年、経験の浅い登山者の命を奪った。',
  'His treacherous act of leaking classified documents to a foreign government led to his immediate arrest.',
  '機密文書を外国政府に漏洩するという彼の裏切り行為は、即座の逮捕につながった。'),
(367, 'besiege', '~を包囲する、攻囲する;~に殺到する', '/bɪˈsiːdʒ/', 'ビスィージ',
  'The medieval army besieged the fortified castle for nearly six months before the defenders finally surrendered.',
  '中世の軍隊は要塞化された城を約6か月間包囲し、ついに防衛側が降伏した。',
  'Following the celebrity''s unexpected announcement, reporters besieged her residence demanding an interview.',
  'そのセレブの予期せぬ発表の後、記者たちがインタビューを求めて彼女の住居に殺到した。'),
(368, 'impeccable', '非の打ちどころのない、完璧な', '/ɪmˈpɛkəbl/', 'インペカブル',
  'The ambassador was widely admired for her impeccable manners and her command of five languages.',
  'その大使は非の打ちどころのないマナーと5か国語の運用能力で広く敬服されていた。',
  'The restaurant earned its reputation through impeccable service and an exquisite seasonal menu.',
  'そのレストランは完璧なサービスと絶妙な季節のメニューで評判を得た。'),
(369, 'flaunt', '(富・能力など)を見せびらかす、誇示する', '/flɔːnt/', 'フローント',
  'He had a tendency to flaunt his wealth by arriving at events in a fleet of luxury vehicles.',
  '彼は高級車を何台も連ねてイベントに到着することで富を見せびらかす癖があった。',
  'Critics accused the socialite of flaunting her privileged lifestyle on social media while others struggled financially.',
  '批評家たちは、他の人々が経済的に苦しむ中、その社交界の名士がSNSで恵まれた生活を誇示していると非難した。'),
(370, 'revamp', '~を改修する、刷新する', '/riːˈvæmp/', 'リーヴァンプ',
  'The city council approved a plan to revamp the aging public transportation system with modern electric buses.',
  '市議会は老朽化した公共交通機関を最新の電気バスで刷新する計画を承認した。',
  'The company decided to revamp its entire marketing strategy after experiencing a sharp decline in sales.',
  '売上の急激な落ち込みを経験した後、その会社はマーケティング戦略全体を刷新することを決めた。'),
(371, 'stake', '利害関係、出資;くい', '/steɪk/', 'ステイク',
  'Several major investors hold a significant stake in the newly established biotechnology firm.',
  '複数の大手投資家がその新設のバイオテクノロジー企業に大きな利害関係を持っている。',
  'With so much at stake, the negotiators worked tirelessly to reach an agreement before the deadline.',
  '多くのものがかかっていたため、交渉担当者たちは期限前に合意に達しようと精力的に取り組んだ。'),
(372, 'opulent', '豪華な、ぜいたくな', '/ˈɒpjʊlənt/', 'オピュレント',
  'The opulent ballroom, adorned with crystal chandeliers and gilded ceilings, took everyone''s breath away.',
  'クリスタルのシャンデリアと金箔の天井で飾られた豪華な舞踏室は、全員の息を呑ませた。',
  'The oligarch''s opulent lifestyle stood in stark contrast to the poverty that plagued the surrounding communities.',
  'その新興財閥の贅沢な生活様式は、周辺地域を苦しめる貧困とは際立った対照をなしていた。'),
(373, 'frigid', '極寒の、厳寒の;無感動な、冷淡な', '/ˈfrɪdʒɪd/', 'フリジッド',
  'The explorers endured frigid temperatures of minus forty degrees during their expedition across the Antarctic plateau.',
  '探検家たちは南極高原を横断する遠征中にマイナス40度の極寒の気温に耐えた。',
  'Her frigid response to the heartfelt apology made it clear that reconciliation was unlikely.',
  '心のこもった謝罪に対する彼女の冷淡な反応は、和解はありそうにないことを明らかにした。'),
(374, 'embargo', '通商停止、貿易禁止;~の貿易を停止する', '/ɪmˈbɑːrɡoʊ/', 'インバーゴウ',
  'The United Nations imposed a comprehensive trade embargo on the country in response to its nuclear weapons program.',
  '国連はその国の核兵器計画への対応として、包括的な貿易禁止を課した。',
  'The oil embargo of the 1970s had profound and lasting effects on the global economy.',
  '1970年代の石油禁輸は世界経済に深くかつ持続的な影響を及ぼした。'),
(375, 'blur', '見えにくくなる、ぼやける;~を見えにくくする;はっきり見えないもの、にじみ', '/blɜːr/', 'ブラー',
  'The rapid advancement of technology has blurred the line between professional and personal life for many workers.',
  '急速な技術の進歩は、多くの労働者にとって仕事と私生活の境界をぼやけさせた。',
  'Tears blurred her vision as she read the poignant letter from her late grandmother.',
  '亡き祖母からの胸を打つ手紙を読むうちに、涙で視界がにじんだ。'),
(376, 'bemoan', '~について不満に思う、不平を言う;(運命・出来事など)について嘆く、悲しむ', '/bɪˈmoʊn/', 'ビモウン',
  'Teachers frequently bemoan the lack of adequate funding for essential educational resources in public schools.',
  '教師たちは公立学校における必要不可欠な教育資源への十分な資金の不足をしばしば嘆いている。',
  'Rather than bemoaning his misfortune, he chose to channel his energy into finding a constructive solution.',
  '不運を嘆くのではなく、彼は建設的な解決策を見つけることにエネルギーを注ぐことを選んだ。'),
(377, 'impasse', '行き詰まり、難局', '/ˈɪmpæs/', 'インパス',
  'The peace talks reached an impasse when neither side was willing to compromise on territorial disputes.',
  '領土紛争についてどちらの側も妥協する意思がなく、和平交渉は行き詰まりに達した。',
  'A skilled mediator was brought in to break the impasse between the labor union and management.',
  '労働組合と経営陣の間の行き詰まりを打開するために、熟練した調停者が招かれた。'),
(378, 'inconspicuous', '目立たない、地味な', '/ˌɪnkənˈspɪkjuəs/', 'インコンスピキュアス',
  'The undercover agent wore inconspicuous clothing to blend in with the crowd at the busy market.',
  '潜入捜査官は混雑した市場の群衆に溶け込むために目立たない服装をしていた。',
  'She preferred an inconspicuous corner table at the café where she could observe people without being noticed.',
  '彼女は気づかれずに人々を観察できるカフェの目立たない隅のテーブルを好んだ。'),
(379, 'derelict', '(建物などが)(長期にわたり)遺棄された、放置された;見捨てられた人、放置されたもの', '/ˈdɛrəlɪkt/', 'デレリクト',
  'The derelict warehouse on the outskirts of town was finally demolished to make way for a new community center.',
  '町の郊外にある放置された倉庫は、新しいコミュニティセンターのためについに取り壊された。',
  'Volunteers organized an initiative to convert derelict buildings into affordable housing for the homeless.',
  'ボランティアたちは放置された建物をホームレスのための手頃な住宅に転換する取り組みを組織した。'),
(380, 'meager', '(数量・質が)不十分な、乏しい', '/ˈmiːɡər/', 'ミーガー',
  'Despite her meager salary, she managed to save enough money to fund her children''s education.',
  '乏しい給料にもかかわらず、彼女は子どもたちの教育費を賄うのに十分なお金を貯めることができた。',
  'The refugees survived on meager rations of rice and water while awaiting relocation to a safer area.',
  '難民たちはより安全な地域への移転を待つ間、わずかな米と水の配給で生き延びた。'),
(381, 'decry', '(人・考え・行動)を(公然と)非難する', '/dɪˈkraɪ/', 'ディクライ',
  'Environmental activists decried the government''s decision to approve the construction of a new coal-fired power plant.',
  '環境活動家たちは、新たな石炭火力発電所の建設を承認した政府の決定を公然と非難した。',
  'Several prominent academics decried the proposed cuts to research funding as short-sighted and detrimental.',
  '何人かの著名な学者が、研究費の削減案を近視眼的で有害であると非難した。'),
(382, 'botch', '(不注意・未熟で)~をしくじる、やり損なう', '/bɒtʃ/', 'ボッチ',
  'The inexperienced contractor botched the renovation so badly that the entire kitchen had to be redone.',
  '経験の浅い業者がリフォームをひどくしくじったので、キッチン全体をやり直さなければならなかった。',
  'The surgeon was sued for malpractice after botching a routine procedure that left the patient with permanent damage.',
  'その外科医は日常的な手術をやり損ない、患者に永久的な損傷を残したとして医療過誤で訴えられた。'),
(383, 'bout', '(病気・活動が続く)期間;(病気の)発作;(ボクシングなどの)試合', '/baʊt/', 'バウト',
  'After a prolonged bout of illness, the author finally resumed work on her long-awaited novel.',
  '長期にわたる病気の期間を経て、その作家はついに待望の小説の執筆を再開した。',
  'The championship bout between the two undefeated boxers attracted millions of viewers worldwide.',
  '二人の無敗のボクサーによるチャンピオンシップの試合は世界中で数百万人の視聴者を集めた。'),
(384, 'collateral', '担保(物件);付随する、二次的な', '/kəˈlætərəl/', 'コラテラル',
  'The bank required the borrower to provide real estate as collateral before approving the substantial loan.',
  '銀行は多額の融資を承認する前に、借り手に不動産を担保として提供するよう求めた。',
  'The military operation was halted due to concerns about excessive collateral damage to civilian infrastructure.',
  '民間インフラへの過度の付随的被害が懸念されたため、軍事作戦は中止された。'),
(385, 'impediment', '障害、支障', '/ɪmˈpɛdɪmənt/', 'インペディメント',
  'The lack of reliable internet access remains a significant impediment to economic development in rural areas.',
  '信頼できるインターネットアクセスの欠如は、農村地域の経済発展にとって大きな障害のままである。',
  'His speech impediment did not prevent him from becoming one of the most compelling orators of his generation.',
  '言語障害があったにもかかわらず、彼は世代で最も説得力のある弁士の一人となった。'),
(386, 'precocious', '(子どもが)早熟な;大人びた、ませた', '/prɪˈkoʊʃəs/', 'プリコウシャス',
  'The precocious child astonished her teachers by reading complex novels at the age of five.',
  'その早熟な子どもは5歳で難解な小説を読み、教師たちを驚嘆させた。',
  'His precocious talent for mathematics earned him a place at a prestigious university at just sixteen.',
  '数学における彼の早熟な才能は、わずか16歳で名門大学への入学を勝ち取った。'),
(387, 'mediocre', 'よくも悪くもない、平凡な', '/ˌmiːdiˈoʊkər/', 'ミーディオウカー',
  'The film received mediocre reviews from critics who found the plot predictable and the acting uninspired.',
  'その映画は、筋書きが予想通りで演技に覇気がないと感じた批評家から平凡な評価を受けた。',
  'Refusing to accept mediocre results, the coach pushed the team to train harder for the upcoming championship.',
  '平凡な結果を受け入れることを拒否し、コーチは来たる選手権に向けてチームにより厳しい練習を課した。'),
(388, 'negligent', '怠慢な、不注意な', '/ˈnɛɡlɪdʒənt/', 'ネグリジェント',
  'The hospital was found negligent for failing to properly sterilize surgical instruments before the operation.',
  'その病院は手術前に手術器具を適切に滅菌しなかったとして怠慢と認定された。',
  'The negligent driver who caused the multi-vehicle accident was held fully liable for the resulting damages.',
  '多重衝突事故を引き起こした不注意な運転手は、その結果生じた損害に対して全面的に責任を負うとされた。'),
(389, 'kickback', 'リベート、払い戻し', '/ˈkɪkbæk/', 'キックバック',
  'The investigation revealed that several officials had received substantial kickbacks from the construction company.',
  '調査により、数人の役人が建設会社から多額のリベートを受け取っていたことが明らかになった。',
  'Accepting kickbacks in exchange for favorable contract terms is a serious criminal offense in most jurisdictions.',
  '有利な契約条件と引き換えにリベートを受け取ることは、ほとんどの法域で重大な犯罪行為である。'),
(390, 'requisite', '必要(不可欠)な', '/ˈrɛkwɪzɪt/', 'レクウィジット',
  'Applicants must possess the requisite qualifications and a minimum of five years of relevant experience.',
  '応募者は必要な資格と最低5年の関連する経験を有していなければならない。',
  'The committee determined that the proposal lacked the requisite evidence to justify such a large expenditure.',
  '委員会は、その提案にはそのような多額の支出を正当化するのに必要な根拠が欠けていると判断した。'),
(391, 'exemplary', '模範的な、りっぱな', '/ɪɡˈzɛmpləri/', 'イグゼンプラリー',
  'The firefighter was commended for her exemplary courage in rescuing three children from the burning building.',
  'その消防士は燃えるビルから3人の子どもを救出した模範的な勇気を称えられた。',
  'His exemplary conduct throughout his career made him the ideal candidate for the leadership position.',
  'キャリアを通じた彼の模範的な行動が、リーダー職の理想的な候補者にした。'),
(392, 'defiance', '(権威などに対する)反抗的態度', '/dɪˈfaɪəns/', 'ディファイアンス',
  'The activist''s open defiance of the unjust law inspired thousands of citizens to join the protest movement.',
  'その活動家による不当な法律への公然たる反抗は、何千もの市民を抗議運動に参加させるきっかけとなった。',
  'In defiance of the court order, the company continued to dump industrial waste into the river.',
  '裁判所の命令に反抗して、その会社は産業廃棄物を川に投棄し続けた。'),
(393, 'concerted', '協力して行われる、協調的な', '/kənˈsɜːrtɪd/', 'コンサーティッド',
  'A concerted effort by international organizations helped eradicate the disease from the entire region.',
  '国際機関による協調的な取り組みが、その地域全体から病気を根絶するのに役立った。',
  'The teachers made a concerted attempt to improve literacy rates among students from disadvantaged backgrounds.',
  '教師たちは恵まれない環境の生徒の識字率を向上させるために協力して取り組んだ。'),
(394, 'banter', '軽口、冗談の言い合い', '/ˈbæntər/', 'バンター',
  'The lighthearted banter between the two colleagues made the tedious office work far more bearable.',
  '二人の同僚の間の軽い冗談の言い合いが、退屈なオフィスの仕事をはるかに耐えやすくした。',
  'What began as harmless banter gradually escalated into a heated argument about company policy.',
  '無害な軽口として始まったものが、会社の方針をめぐる激しい議論に次第にエスカレートした。'),
(395, 'antiseptic', '消毒薬[剤]、防腐剤;消毒用の、殺菌の', '/ˌæntɪˈsɛptɪk/', 'アンティセプティック',
  'The nurse applied an antiseptic solution to the wound to prevent any potential bacterial infection.',
  '看護師は細菌感染の可能性を防ぐために傷口に消毒液を塗布した。',
  'The discovery of effective antiseptic techniques in the 19th century revolutionized surgical practices worldwide.',
  '19世紀における効果的な消毒技術の発見は、世界中の外科手術の実践に革命をもたらした。'),
(396, 'incessant', '絶え間のない、ひっきりなしの', '/ɪnˈsɛsənt/', 'インセサント',
  'The incessant noise from the construction site made it impossible for the residents to sleep at night.',
  '建設現場からの絶え間ない騒音のせいで、住民は夜眠ることが不可能だった。',
  'Her incessant complaints about trivial matters eventually alienated all of her colleagues.',
  '些細なことについての彼女のひっきりなしの不平は、最終的にすべての同僚を遠ざけた。'),
(397, 'allegiance', '(国家・主義などに対する)忠誠、忠実', '/əˈliːdʒəns/', 'アリージャンス',
  'The soldiers swore their allegiance to the newly established republic and vowed to defend its constitution.',
  '兵士たちは新設された共和国への忠誠を誓い、その憲法を守ることを誓約した。',
  'His allegiance to the principles of justice and equality never wavered despite immense political pressure.',
  '莫大な政治的圧力にもかかわらず、正義と平等の原則に対する彼の忠誠は決して揺らがなかった。'),
(398, 'delinquent', '(人が)滞納した;(債務などが)支払期日を過ぎた;義務を怠った;非行の、罪を犯した', '/dɪˈlɪŋkwənt/', 'ディリンクウェント',
  'The bank sent a final notice to the delinquent borrower warning of imminent foreclosure proceedings.',
  '銀行は滞納している借り手に差し押さえ手続きが差し迫っていることを警告する最終通知を送った。',
  'The social worker developed a rehabilitation program specifically designed for delinquent youths in the community.',
  'そのソーシャルワーカーは、地域の非行少年のために特別に設計された更生プログラムを策定した。'),
(399, 'prod', '(人など)に促す、思い出させる;~をつつく', '/prɒd/', 'プロッド',
  'The manager had to prod the team repeatedly to meet the rapidly approaching project deadline.',
  'マネージャーは急速に迫るプロジェクトの期限に間に合わせるために、チームに繰り返し催促しなければならなかった。',
  'She gently prodded her colleague to submit the overdue report before the end of the week.',
  '彼女は同僚に、週末までに期限を過ぎた報告書を提出するよう穏やかに促した。'),
(400, 'coerce', '(人)に強要する', '/koʊˈɜːrs/', 'コウアース',
  'The whistleblower alleged that senior executives had coerced employees into falsifying financial statements.',
  '内部告発者は、上級幹部が従業員に財務諸表の改ざんを強要したと主張した。',
  'No individual should ever be coerced into signing a contract without fully understanding its terms and conditions.',
  'いかなる個人も、契約条件を十分に理解せずに契約書に署名するよう強要されるべきではない。');
