-- words テーブル INSERT文 (No.401 ~ No.450)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(401, 'pertinent', '関係のある;適切な、妥当な', '/ˈpɜːrtɪnənt/', 'パーティナント',
  'The lawyer asked the witness to provide only pertinent details that were directly related to the case.',
  '弁護士は証人に、事件に直接関係のある適切な詳細のみを提供するよう求めた。',
  'Her pertinent observations during the board meeting helped steer the discussion toward a viable solution.',
  '取締役会での彼女の的確な意見が、議論を実行可能な解決策へと導いた。'),
(402, 'arbitrary', '任意の、恣意的な', '/ˈɑːrbɪtreri/', 'アービトレリ',
  'The dictator''s arbitrary decisions were made without consulting any of his advisors or considering public opinion.',
  '独裁者の恣意的な決定は、顧問に相談することも世論を考慮することもなく下された。',
  'Critics argued that the new regulations were arbitrary and lacked any scientific basis whatsoever.',
  '批評家たちは、新しい規制は恣意的であり、科学的根拠がまったくないと主張した。'),
(403, 'stagnant', '(水・空気などが)流れの悪い、よどんだ;(経済・活動などが)停滞した、不振な', '/ˈstæɡnənt/', 'スタグナント',
  'The stagnant economy forced many small businesses to close their doors permanently.',
  '停滞した経済により、多くの中小企業が永久に閉店を余儀なくされた。',
  'The pond had become stagnant over the summer, breeding mosquitoes and emitting a foul odor.',
  'その池は夏の間によどみ、蚊が繁殖し、悪臭を放つようになった。'),
(404, 'bane', '破滅のもと、悩みの種', '/beɪn/', 'ベイン',
  'Procrastination has long been the bane of students who struggle to meet assignment deadlines.',
  '先延ばしは、課題の締め切りに間に合わせるのに苦労する学生にとって、長年の悩みの種である。',
  'Invasive species have become the bane of native ecosystems, displacing indigenous flora and fauna.',
  '外来種は在来の生態系の破滅のもととなり、固有の動植物を追いやっている。'),
(405, 'morbid', '(考え・性向などが)病的な、不健全な', '/ˈmɔːrbɪd/', 'モービッド',
  'His morbid fascination with crime documentaries concerned his family, who urged him to seek healthier interests.',
  '犯罪ドキュメンタリーへの彼の病的な関心は家族を心配させ、もっと健全な趣味を持つよう促された。',
  'The novelist was known for her morbid imagination, which produced some of the most chilling horror stories ever written.',
  'その小説家は病的な想像力で知られ、これまでに書かれた中で最も背筋の凍るホラー小説を生み出した。'),
(406, 'purge', '(政党・組織など)から追放する;(人)を追放する', '/pɜːrdʒ/', 'パージ',
  'The new regime purged all dissenters from the political party in an effort to consolidate its power.',
  '新政権は権力を強化するため、政党からすべての反対者を追放した。',
  'The company decided to purge outdated files from its servers to free up valuable storage space.',
  '会社は貴重な記憶容量を空けるため、サーバーから古いファイルを一掃することにした。'),
(407, 'pervasive', '行き渡った、まん延した', '/pərˈveɪsɪv/', 'パーヴェイスィヴ',
  'The pervasive influence of social media on modern culture has fundamentally altered how people communicate.',
  'ソーシャルメディアの現代文化への広範な影響は、人々のコミュニケーション方法を根本的に変えた。',
  'A pervasive sense of anxiety gripped the nation in the aftermath of the unprecedented natural disaster.',
  '前例のない自然災害の後、国中に広がる不安感が人々を支配した。'),
(408, 'appraise', '(土地・財産など)を評価する、鑑定する', '/əˈpreɪz/', 'アプレイズ',
  'The antique dealer was called in to appraise the collection of rare paintings discovered in the abandoned mansion.',
  '古美術商が、廃墟の邸宅で発見された希少な絵画のコレクションを鑑定するために呼ばれた。',
  'Before selling the property, they hired a certified professional to appraise its current market value.',
  '不動産を売却する前に、彼らは現在の市場価値を鑑定するために公認の専門家を雇った。'),
(409, 'nullify', '~を無効にする;(契約など)を破棄する', '/ˈnʌlɪfaɪ/', 'ナリファイ',
  'The Supreme Court ruled to nullify the controversial legislation that had been passed without proper parliamentary procedure.',
  '最高裁判所は、適切な議会手続きを経ずに可決された問題の法律を無効にする判決を下した。',
  'The discovery of fraudulent signatures was enough to nullify the entire contract between the two corporations.',
  '不正な署名の発見は、2つの企業間の契約全体を無効にするのに十分であった。'),
(410, 'tacit', '(承認・同意・知識などが)暗黙の、無言の', '/ˈtæsɪt/', 'タスィット',
  'There was a tacit understanding among the colleagues that no one would mention the CEO''s embarrassing mistake.',
  'CEOの恥ずかしい失敗については誰も口にしないという暗黙の了解が同僚間にあった。',
  'Her tacit approval of the plan was evident from the fact that she raised no objections during the meeting.',
  '会議中に異議を唱えなかったことから、彼女がその計画を暗黙のうちに承認していることは明らかだった。'),
(411, 'swerve', '(急に)向きを変える、ハンドルを切る;(車などが)方向を変えること', '/swɜːrv/', 'スワーヴ',
  'The driver had to swerve sharply to avoid hitting the deer that had suddenly appeared on the highway.',
  '高速道路に突然現れた鹿を避けるため、運転手は急にハンドルを切らなければならなかった。',
  'The sudden swerve of the bus caused several standing passengers to lose their balance and fall.',
  'バスの急な方向転換により、立っていた数人の乗客がバランスを崩して転倒した。'),
(412, 'perpetrate', '(犯罪など)を犯す、(悪事)を働く', '/ˈpɜːrpɪtreɪt/', 'パーピトレイト',
  'The fraud was perpetrated by a group of executives who had been siphoning funds from the company for years.',
  'その詐欺は、何年にもわたって会社から資金を横領していた幹部グループによって犯された。',
  'Authorities are investigating who perpetrated the cyberattack that compromised millions of customer records.',
  '当局は、数百万件の顧客記録を漏洩させたサイバー攻撃を誰が犯したのかを調査している。'),
(413, 'reclusive', '隠遁した、引きこもりがちな', '/rɪˈkluːsɪv/', 'リクルースィヴ',
  'The reclusive author had not granted a single interview in over two decades despite her immense popularity.',
  'その隠遁した作家は、絶大な人気にもかかわらず、20年以上一度もインタビューに応じなかった。',
  'After retiring from public life, the billionaire became increasingly reclusive, rarely leaving his estate.',
  '公的生活から引退した後、その億万長者はますます引きこもりがちになり、邸宅を出ることはほとんどなかった。'),
(414, 'onus', '責任、義務', '/ˈoʊnəs/', 'オウナス',
  'The onus is on the prosecution to prove beyond a reasonable doubt that the defendant committed the crime.',
  '被告が犯罪を犯したことを合理的な疑いを超えて証明する責任は検察側にある。',
  'The onus of maintaining workplace safety falls squarely on the shoulders of the employer.',
  '職場の安全を維持する責任は、雇用者の双肩にかかっている。'),
(415, 'cinch', 'たやすいこと、朝飯前のこと;間違いないこと、本命', '/sɪntʃ/', 'スィンチ',
  'With her extensive experience in negotiations, closing the deal was a cinch for the seasoned diplomat.',
  '交渉での豊富な経験を持つその熟練外交官にとって、取引を成立させるのは朝飯前だった。',
  'The veteran chef assured his apprentice that making a perfect soufflé would be a cinch once she mastered the basics.',
  'ベテランシェフは弟子に、基本をマスターすれば完璧なスフレを作るのはたやすいことだと保証した。'),
(416, 'mesmerize', '(演技・声などで)(人)をすっかり魅惑する、くぎ付けにする', '/ˈmezməraɪz/', 'メズマライズ',
  'The virtuoso pianist mesmerized the audience with a breathtaking performance of Rachmaninoff''s Third Concerto.',
  'その名ピアニストは、ラフマニノフのピアノ協奏曲第3番の息をのむような演奏で観客をくぎ付けにした。',
  'Children were mesmerized by the magician''s elaborate illusions, their eyes wide with wonder and disbelief.',
  '子供たちは手品師の精巧なイリュージョンに魅了され、驚きと信じられないという思いで目を見開いた。'),
(417, 'lurid', '(話などが)恐ろしい、残忍な;(色などが)どぎつい、けばけばしい', '/ˈlʊrɪd/', 'ルーリッド',
  'The tabloid published lurid details about the celebrity scandal, sparing no effort to sensationalize every aspect.',
  'そのタブロイド紙は有名人のスキャンダルについて恐ろしい詳細を掲載し、あらゆる面をセンセーショナルに報じた。',
  'The lurid neon signs along the strip cast an eerie glow over the deserted streets at midnight.',
  '通り沿いのどぎつい色のネオンサインが、真夜中の人気のない通りに不気味な光を投げかけた。'),
(418, 'exhort', '(人)に強く勧める、説得する', '/ɪɡˈzɔːrt/', 'イグゾート',
  'The coach exhorted his players to give their utmost effort in the championship final.',
  '監督は選手たちに、決勝戦で全力を尽くすよう強く勧めた。',
  'Environmental activists exhorted the government to take immediate action against deforestation in the Amazon.',
  '環境活動家たちは政府に、アマゾンの森林破壊に対して直ちに行動を起こすよう強く訴えた。'),
(419, 'throng', '群衆、人だかり;(場所)に群がる、殺到する', '/θrɔːŋ/', 'スローング',
  'A throng of enthusiastic fans gathered outside the stadium hours before the concert was scheduled to begin.',
  '熱狂的なファンの群衆が、コンサートの開始予定時刻の数時間前にスタジアムの外に集まった。',
  'Tourists thronged the narrow streets of the ancient city, marveling at its well-preserved medieval architecture.',
  '観光客たちが古代都市の狭い通りに群がり、保存状態の良い中世の建築に感嘆した。'),
(420, 'thwart', '(計画など)を阻止する;(人)を妨げる', '/θwɔːrt/', 'スウォート',
  'The intelligence agency managed to thwart the terrorist plot just hours before it was to be carried out.',
  '情報機関は、テロ計画が実行されるわずか数時間前に阻止することに成功した。',
  'Despite numerous attempts to thwart her ambitions, she persevered and eventually became the youngest CEO in the industry.',
  '彼女の野心を妨げようとする数々の試みにもかかわらず、彼女は粘り強く努力し、最終的に業界最年少のCEOとなった。'),
(421, 'insinuate', '(悪口など)を遠回しに言う;…と遠回しに言う', '/ɪnˈsɪnjueɪt/', 'インスィニュエイト',
  'The journalist seemed to insinuate that the politician had accepted bribes, though she never made the accusation directly.',
  'そのジャーナリストは政治家が賄賂を受け取ったと遠回しにほのめかしたようだが、直接的に非難することはなかった。',
  'He resented the way his colleague would insinuate that his promotion was due to favoritism rather than merit.',
  '彼は、同僚が昇進は実力ではなくえこひいきによるものだと遠回しに言うやり方に憤慨した。'),
(422, 'canvass', '(寄付・投票などを求めて)訪ねて回る', '/ˈkænvəs/', 'キャンヴァス',
  'Volunteers spent the entire weekend canvassing the neighborhood to gather support for the local candidate.',
  'ボランティアたちは週末をすべて費やして、地元候補者への支持を集めるために近隣を訪ねて回った。',
  'The charity organization canvassed businesses throughout the city, seeking donations for the flood relief fund.',
  '慈善団体は洪水救援基金への寄付を求めて、市内の企業を訪ねて回った。'),
(423, 'complacent', '自己満足の、悦に入った', '/kəmˈpleɪsənt/', 'コンプレイスント',
  'The team became complacent after winning three consecutive championships and failed to prepare adequately for the next season.',
  'チームは3連覇の後に自己満足に陥り、次のシーズンへの準備が不十分だった。',
  'Experts warned that citizens should not become complacent about cybersecurity despite recent improvements in protective measures.',
  '専門家は、最近の防護策の改善にもかかわらず、市民がサイバーセキュリティについて油断してはならないと警告した。'),
(424, 'innuendo', '(性的な・不快な)ほのめかし、当てこすり', '/ˌɪnjuˈendoʊ/', 'イニュエンドウ',
  'The political debate devolved into a series of innuendos rather than substantive policy discussions.',
  '政治討論は実質的な政策議論ではなく、一連の当てこすりに堕落した。',
  'She filed a complaint against her supervisor, citing persistent innuendo that created a hostile work environment.',
  '彼女は、敵対的な職場環境を生み出す絶え間ないほのめかしを理由に、上司に対して苦情を申し立てた。'),
(425, 'clench', '(歯)を食いしばる、(手)を握りしめる', '/klentʃ/', 'クレンチ',
  'She clenched her fists in frustration as the judge announced the verdict that she considered profoundly unjust.',
  '彼女が著しく不公正だと考える判決を裁判官が言い渡した際、彼女は悔しさで拳を握りしめた。',
  'The athlete clenched his teeth and pushed through the final meters of the grueling marathon despite the searing pain.',
  'その選手は、焼けるような痛みにもかかわらず歯を食いしばり、過酷なマラソンの最後の数メートルを走り抜いた。'),
(426, 'astute', '(人・行動などが)鋭い、鋭敏な', '/əˈstuːt/', 'アストゥート',
  'The astute investor recognized the potential of the startup long before it became a household name.',
  'その鋭い投資家は、そのスタートアップが有名になるずっと前にその可能性を見抜いていた。',
  'Her astute observation about the flaw in the research methodology saved the team months of wasted effort.',
  '研究方法論の欠陥に関する彼女の鋭い指摘が、チームの何か月もの無駄な努力を救った。'),
(427, 'levity', '軽率さ、場違いな陽気さ', '/ˈlevɪti/', 'レヴィティ',
  'The chairman''s attempt at levity during the solemn memorial service was met with disapproving glances from the attendees.',
  '厳粛な追悼式での議長の軽率な冗談は、出席者から非難の視線を浴びた。',
  'A moment of levity helped ease the tension in the courtroom after hours of intense cross-examination.',
  '何時間にもわたる激しい反対尋問の後、一瞬の軽妙さが法廷の緊張を和らげた。'),
(428, 'falter', '(人が)(自信を失い)口ごもる、(声が)震える;(ことが)調子が悪くなる、勢いがなくなる', '/ˈfɔːltər/', 'フォールター',
  'Her voice faltered as she recounted the harrowing experience of surviving the earthquake that devastated her hometown.',
  '故郷を壊滅させた地震を生き延びた悲惨な経験を語る彼女の声は震えた。',
  'The economy began to falter after the central bank raised interest rates for the fifth consecutive quarter.',
  '中央銀行が5四半期連続で金利を引き上げた後、経済は失速し始めた。'),
(429, 'copious', '(数量などが)多くの', '/ˈkoʊpiəs/', 'コウピアス',
  'The researcher took copious notes during the three-hour lecture, filling an entire notebook with detailed observations.',
  'その研究者は3時間の講義中に大量のメモを取り、ノート1冊を詳細な記録で埋めた。',
  'Copious rainfall throughout the monsoon season replenished the reservoirs that had been critically low for months.',
  'モンスーンの季節を通じての大量の降雨が、何か月も危機的に低い水位だった貯水池を満たした。'),
(430, 'retort', '(人が)(すぐに)…と言い返す、切り返す', '/rɪˈtɔːrt/', 'リトート',
  'When accused of being overly cautious, she retorted that prudence had saved the company from bankruptcy on multiple occasions.',
  '慎重すぎると非難された際、彼女は慎重さが何度も会社を倒産から救ったと言い返した。',
  'The senator''s sharp retort silenced his critics and earned him a round of applause from his supporters.',
  'その上院議員の鋭い切り返しは批判者を黙らせ、支持者から拍手を受けた。'),
(431, 'wilt', '(草花が)しおれる、(野菜が)しんなりする;(人が)ぐったりする', '/wɪlt/', 'ウィルト',
  'The flowers in the garden began to wilt under the relentless summer heat, despite being watered twice daily.',
  '庭の花は1日2回水やりをしたにもかかわらず、容赦ない夏の暑さでしおれ始めた。',
  'The marathon runners started to wilt in the final kilometers as temperatures soared above thirty-five degrees.',
  'マラソンランナーたちは気温が35度を超えるなか、最後の数キロでぐったりし始めた。'),
(432, 'accrue', '(利子・資本などが)(徐々に)たまる', '/əˈkruː/', 'アクルー',
  'Interest will accrue on the outstanding balance if the payment is not made by the end of the billing cycle.',
  '請求期間の終わりまでに支払いがなされなければ、未払い残高に利息がたまる。',
  'Over the years, she accrued substantial benefits from her long-term investment in diversified portfolios.',
  '長年にわたり、彼女は分散ポートフォリオへの長期投資からかなりの利益を蓄積した。'),
(433, 'reprieve', '(危険などからの)一時的な猶予;(特に死刑の)執行延期[中止]', '/rɪˈpriːv/', 'リプリーヴ',
  'The governor granted a last-minute reprieve, sparing the condemned prisoner from execution pending further review.',
  '知事は土壇場で執行猶予を与え、さらなる審理を待つ間、死刑囚を刑の執行から救った。',
  'The unexpected funding provided a temporary reprieve for the struggling hospital that had been on the verge of closure.',
  '予期せぬ資金提供が、閉鎖寸前だった経営難の病院に一時的な猶予を与えた。'),
(434, 'rehash', '焼き直し(たもの)、改作;(古い考え・著作など)を焼き直す', '/ˈriːhæʃ/', 'リーハッシュ',
  'Critics dismissed the film as a mere rehash of the original, offering nothing new in terms of plot or character development.',
  '批評家たちはその映画をオリジナルの単なる焼き直しにすぎず、筋立てや人物描写に新しさがないと酷評した。',
  'Rather than rehashing old arguments, the committee proposed an entirely fresh approach to solving the housing crisis.',
  '委員会は古い議論を焼き直すのではなく、住宅危機を解決するためのまったく新しいアプローチを提案した。'),
(435, 'congregate', '集まる、集合する', '/ˈkɒŋɡrɪɡeɪt/', 'コングリゲイト',
  'Thousands of protesters congregated in the central square to demand sweeping reforms to the electoral system.',
  '何千人もの抗議者が選挙制度の抜本的な改革を求めて中央広場に集まった。',
  'Every evening, local residents congregate at the park to socialize and enjoy the cool breeze from the river.',
  '毎晩、地元の住民が交流し、川からの涼しい風を楽しむために公園に集まる。'),
(436, 'demure', '(女性・衣服などが)おとなしい、控えめな', '/dɪˈmjʊr/', 'ディミュア',
  'Despite her demure appearance, she was a fiercely competitive attorney who rarely lost a case in court.',
  '控えめな外見にもかかわらず、彼女は法廷でめったに負けない非常に闘争心の強い弁護士だった。',
  'The actress adopted a demure persona for the role, speaking softly and avoiding direct eye contact with other characters.',
  'その女優はその役のために控えめな人物像を演じ、穏やかに話し、他の登場人物との直接的なアイコンタクトを避けた。'),
(437, 'mock', '模擬の、まがいものの;~をばかにする、からかう', '/mɒk/', 'モック',
  'The students participated in a mock trial to gain practical experience before entering the legal profession.',
  '学生たちは法曹界に入る前に実践的な経験を積むために模擬裁判に参加した。',
  'It is unconscionable to mock someone for their accent or the way they speak a second language.',
  '誰かのアクセントや第二言語の話し方をばかにするのは良心に反することである。'),
(438, 'abscond', '(場所から)逃亡する、行方をくらます', '/æbˈskɒnd/', 'アブスコンド',
  'The embezzler absconded with millions of dollars and fled to a country with no extradition treaty.',
  'その横領犯は数百万ドルを持って逃亡し、犯罪人引渡し条約のない国へ逃げた。',
  'The suspect absconded from custody during a routine hospital visit, prompting a nationwide manhunt.',
  '容疑者は通常の病院への訪問中に拘留から逃亡し、全国的な捜索が始まった。'),
(439, 'ebb', '(人気・感情などが)(潮が引くように)衰退する;(潮が)引く', '/eb/', 'エブ',
  'Public enthusiasm for the ambitious space program began to ebb as costs escalated beyond initial projections.',
  '費用が当初の予想を超えて膨らむにつれ、野心的な宇宙計画への国民の熱意は衰退し始めた。',
  'As the tide ebbed, it revealed a vast expanse of pristine sand and scattered rock pools teeming with marine life.',
  '潮が引くと、手つかずの砂浜の広大な広がりと、海洋生物があふれる点在する潮だまりが現れた。'),
(440, 'dissuade', '(人)を説得して(~を)思いとどまらせる', '/dɪˈsweɪd/', 'ディスウェイド',
  'Her parents tried to dissuade her from dropping out of university, but she was determined to pursue her entrepreneurial dreams.',
  '両親は大学を中退しないよう説得しようとしたが、彼女は起業家としての夢を追求する決意を固めていた。',
  'The harsh penalties were designed to dissuade potential offenders from committing acts of corporate fraud.',
  '厳しい罰則は、潜在的な違反者が企業不正を犯すのを思いとどまらせるために設けられた。'),
(441, 'repudiate', '~を否認する;~を拒絶する', '/rɪˈpjuːdieɪt/', 'リピューディエイト',
  'The president publicly repudiated the allegations of corruption, calling them fabricated and politically motivated.',
  '大統領は汚職疑惑を公に否認し、それらはでっち上げで政治的動機によるものだと述べた。',
  'Several member states threatened to repudiate the treaty if the proposed amendments were not incorporated.',
  '提案された修正が盛り込まれなければ、いくつかの加盟国がその条約を拒否すると脅した。'),
(442, 'deposition', '宣誓証言(すること)、供述調書;堆積、沈殿;(高官などの)免職、罷免', '/ˌdepəˈzɪʃən/', 'デポズィション',
  'During her deposition, the witness provided crucial testimony that contradicted the defendant''s version of events.',
  '宣誓証言の中で、その証人は被告の事件の説明と矛盾する重要な証言を行った。',
  'The gradual deposition of sediment over millennia formed the fertile delta that now sustains millions of farmers.',
  '何千年にもわたる堆積物の徐々の堆積が、今何百万人もの農民を支える肥沃なデルタを形成した。'),
(443, 'retention', '記憶、記憶力;保有、保持', '/rɪˈtenʃən/', 'リテンション',
  'The company implemented flexible working arrangements to improve employee retention and reduce costly turnover.',
  '会社は従業員の保持率を向上させ、コストのかかる離職を減らすために柔軟な勤務形態を導入した。',
  'Studies suggest that active learning techniques significantly enhance the retention of complex information.',
  '研究によると、能動的学習テクニックは複雑な情報の記憶保持を大幅に向上させるという。'),
(444, 'propagation', '(思想・情報などの)伝播、普及;(動植物の)繁殖、増殖', '/ˌprɒpəˈɡeɪʃən/', 'プロパゲイション',
  'The propagation of misinformation through social media has become one of the most pressing challenges of our time.',
  'ソーシャルメディアを通じた誤情報の伝播は、現代の最も差し迫った課題の一つとなっている。',
  'The botanist specialized in the propagation of endangered orchid species through innovative tissue culture methods.',
  'その植物学者は、革新的な組織培養法による絶滅危惧蘭種の増殖を専門としていた。'),
(445, 'cringe', '(恐怖などで)すくむ、後ずさりする;(恥などで)身が縮む', '/krɪndʒ/', 'クリンジ',
  'She cringed at the memory of her disastrous speech, during which she had forgotten every word she had rehearsed.',
  '練習したすべての言葉を忘れてしまった悲惨なスピーチの記憶に、彼女は身が縮む思いだった。',
  'The audience collectively cringed when the presenter accidentally displayed confidential data on the main screen.',
  '発表者が誤って機密データをメインスクリーンに表示した時、聴衆は一斉に身をすくめた。'),
(446, 'unruly', '言うことを聞かない、手に負えない', '/ʌnˈruːli/', 'アンルーリー',
  'The substitute teacher struggled to maintain order in the classroom full of unruly students who ignored every instruction.',
  '代理の教師は、すべての指示を無視する手に負えない生徒でいっぱいの教室で秩序を保つのに苦労した。',
  'The unruly crowd was eventually dispersed by police after they began blocking traffic on the main thoroughfare.',
  '手に負えない群衆が幹線道路の交通を妨害し始めた後、最終的に警察によって解散させられた。'),
(447, 'dislodge', '(もの・人)を(特定の場所から)取り除く、移動させる', '/dɪsˈlɒdʒ/', 'ディスロッジ',
  'The rescue team worked tirelessly to dislodge the massive boulder that had blocked the only road to the village.',
  '救助チームは、村への唯一の道を塞いだ巨大な岩を取り除くために休むことなく作業した。',
  'Despite fierce resistance, the allied forces managed to dislodge the enemy from their fortified positions along the ridge.',
  '激しい抵抗にもかかわらず、連合軍は尾根に沿った敵の要塞化された陣地から敵を排除することに成功した。'),
(448, 'tactful', '機転の利く、そつのない', '/ˈtæktfəl/', 'タクトフル',
  'The diplomat gave a tactful response that acknowledged both sides'' concerns without offending either party.',
  'その外交官は、どちらの当事者も怒らせることなく双方の懸念を認める機転の利いた回答をした。',
  'A tactful manager knows how to deliver constructive criticism in a way that motivates rather than demoralizes employees.',
  '機転の利く管理者は、従業員を落胆させるのではなく動機づける方法で建設的な批判を行う方法を知っている。'),
(449, 'derisive', '嘲笑的な、あざけりの', '/dɪˈraɪsɪv/', 'ディライスィヴ',
  'The crowd erupted in derisive laughter when the politician made yet another promise that nobody believed he would keep.',
  '政治家が誰も守られるとは思わない約束をまたもやした時、群衆は嘲笑を爆発させた。',
  'His derisive tone during the interview alienated potential allies who might otherwise have supported his candidacy.',
  'インタビュー中の彼の嘲笑的な口調は、そうでなければ彼の立候補を支持したかもしれない潜在的な味方を遠ざけた。'),
(450, 'blunder', 'へま、どじ、不手際', '/ˈblʌndər/', 'ブランダー',
  'The diplomatic blunder nearly derailed the peace negotiations that had taken years of painstaking effort to arrange.',
  'その外交上の不手際は、何年もの苦労を重ねて手配した和平交渉をほぼ頓挫させるところだった。',
  'Admitting his blunder publicly, the executive took full responsibility and outlined steps to prevent similar mistakes in the future.',
  '自らの不手際を公に認め、その幹部は全責任を負い、将来同様のミスを防ぐための措置を概説した。');
