-- words テーブル INSERT文 (No.601 ~ No.650)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(601, 'explicit', '露骨な、あからさまな;明白な、あいまいさのない', '/ɪkˈsplɪsɪt/', 'イクスプリシト',
  'The contract contained explicit instructions regarding the responsibilities of each party involved in the merger.',
  'その契約書には、合併に関わる各当事者の責任について明白な指示が含まれていた。',
  'The government issued explicit warnings about the health risks associated with prolonged exposure to the chemical.',
  '政府はその化学物質への長期的な曝露に伴う健康リスクについてあからさまな警告を発した。'),
(602, 'insulate', '(熱・音など)を遮断する;(人)を隔離する、孤立させる', '/ˈɪnsjuleɪt/', 'インシュレイト',
  'The thick walls of the medieval fortress were designed to insulate the interior from the harsh winter cold.',
  '中世の要塞の厚い壁は、厳しい冬の寒さから内部を遮断するように設計されていた。',
  'Growing up in a wealthy family had insulated her from the economic hardships that most citizens endured.',
  '裕福な家庭で育ったことが、ほとんどの市民が耐えていた経済的困難から彼女を隔離していた。'),
(603, 'pivotal', '重要な、決定的な', '/ˈpɪvətl/', 'ピヴァトル',
  'The discovery of penicillin proved to be a pivotal moment in the history of modern medicine.',
  'ペニシリンの発見は、近代医学の歴史における決定的な瞬間であった。',
  'Her pivotal role in negotiating the peace treaty earned her international recognition and a Nobel Prize nomination.',
  '和平条約の交渉における彼女の重要な役割が、国際的な評価とノーベル賞候補への推薦をもたらした。'),
(604, 'expedite', '~を促進する、急がせる', '/ˈekspɪdaɪt/', 'エクスピダイト',
  'The minister promised to expedite the approval process for the construction of new affordable housing units.',
  '大臣は新しい低価格住宅の建設に対する承認プロセスを促進すると約束した。',
  'To expedite the delivery of humanitarian aid, the military deployed additional cargo aircraft to the disaster zone.',
  '人道支援物資の配送を急がせるため、軍は被災地に追加の輸送機を配備した。'),
(605, 'subdued', '(いつになく)元気のない、おとなしい;(光・色・音などが)控えめの', '/səbˈdjuːd/', 'サブデュード',
  'The usually cheerful office atmosphere became subdued after the announcement of the company''s impending layoffs.',
  '会社の差し迫ったレイオフの発表後、普段は陽気なオフィスの雰囲気が元気のないものになった。',
  'The artist deliberately chose subdued colours to evoke a sense of melancholy in the landscape painting.',
  'その画家は風景画に哀愁を漂わせるため、意図的に控えめの色彩を選んだ。'),
(606, 'destitute', '困窮した、極貧の', '/ˈdestɪtjuːt/', 'デスティテュート',
  'After the catastrophic earthquake, thousands of families were left destitute, with no shelter or means of livelihood.',
  '壊滅的な地震の後、何千もの家族が住む場所も生活手段もなく困窮した状態に置かれた。',
  'The charity organisation has been providing essential supplies to destitute communities in the war-torn region.',
  'その慈善団体は、戦争で荒廃した地域の極貧のコミュニティに必需品を提供し続けている。'),
(607, 'grievance', '苦情、不満', '/ˈɡriːvəns/', 'グリーヴァンス',
  'The labour union filed a formal grievance against the management over the sudden reduction in employee benefits.',
  '労働組合は従業員福利の突然の削減について経営陣に対して正式な苦情を申し立てた。',
  'Unless the company addresses the workers'' grievances promptly, a prolonged strike seems inevitable.',
  '会社が労働者の不満に迅速に対処しなければ、長期的なストライキは避けられないだろう。'),
(608, 'arduous', '骨の折れる、きつい', '/ˈɑːrdjuəs/', 'アージュアス',
  'The arduous climb to the summit of the mountain tested even the most experienced mountaineers in the expedition.',
  '山頂への骨の折れる登山は、遠征隊の中で最も経験豊富な登山家たちをも試すものだった。',
  'Completing a doctoral dissertation is an arduous undertaking that requires years of dedicated research and writing.',
  '博士論文の完成は、何年もの専念した研究と執筆を必要とする骨の折れる仕事である。'),
(609, 'oblivious', '気づかないで、無頓着で;忘れて', '/əˈblɪviəs/', 'オブリヴィアス',
  'The tourists wandered through the narrow streets, seemingly oblivious to the mounting political tensions in the city.',
  '観光客たちは街の高まる政治的緊張に気づかないまま、狭い通りをさまよっていた。',
  'Engrossed in her research, the scientist was completely oblivious to the passage of time until dawn broke.',
  '研究に没頭していたその科学者は、夜が明けるまで時間の経過にまったく無頓着だった。'),
(610, 'recoup', '(損失・支出など)を取り戻す', '/rɪˈkuːp/', 'リクープ',
  'The company expects to recoup its initial investment within three years through aggressive overseas expansion.',
  'その会社は積極的な海外展開を通じて3年以内に初期投資を取り戻すことを見込んでいる。',
  'It took the airline nearly a decade to recoup the losses incurred during the global financial crisis.',
  'その航空会社が世界的な金融危機の間に被った損失を取り戻すのに10年近くかかった。'),
(611, 'demoralize', '(人)の士気をくじく、(人)を意気消沈させる', '/dɪˈmɒrəlaɪz/', 'ディモラライズ',
  'The series of unexpected defeats demoralized the troops, causing many to question the viability of their campaign.',
  '相次ぐ予期せぬ敗北が兵士たちの士気をくじき、多くの者が作戦の実現可能性に疑問を抱くようになった。',
  'Constant criticism from the supervisor had demoralized the entire department, leading to a sharp decline in productivity.',
  '上司からの絶え間ない批判が部署全体を意気消沈させ、生産性の急激な低下を招いた。'),
(612, 'fraudulent', '(行為・誘示などが)詐欺の、不正な', '/ˈfrɔːdjulənt/', 'フロージュラント',
  'The investigation revealed a fraudulent scheme in which investors were deceived into purchasing worthless securities.',
  '調査により、投資家が無価値の証券を購入するよう欺かれた詐欺の手口が明らかになった。',
  'The bank implemented stricter verification procedures to prevent fraudulent transactions on its online platform.',
  'その銀行はオンラインプラットフォームでの不正な取引を防ぐため、より厳格な認証手続きを導入した。'),
(613, 'frantic', '(心配・恐怖などで)取り乱した;大慌ての、慌てふためいた', '/ˈfræntɪk/', 'フランティック',
  'The frantic mother searched every room in the house after realising her toddler had wandered off unattended.',
  '幼い子どもが目を離した隙にいなくなったことに気づき、取り乱した母親は家中の部屋を捜した。',
  'In the frantic rush to evacuate before the hurricane, many residents left behind irreplaceable personal belongings.',
  'ハリケーンの前に避難する大慌ての中で、多くの住民がかけがえのない私物を置き去りにした。'),
(614, 'incremental', '(量・金額などが)少しずつ増加する', '/ˌɪnkrəˈmentl/', 'インクリメンタル',
  'The government adopted an incremental approach to tax reform, raising rates by a small percentage each fiscal year.',
  '政府は税制改革に段階的なアプローチを採用し、各会計年度にわずかな割合ずつ税率を引き上げた。',
  'Rather than pursuing radical innovation, the company focused on incremental improvements to its existing product line.',
  '急進的な革新を追求するのではなく、その会社は既存の製品ラインの少しずつの改善に注力した。'),
(615, 'afflict', '(病気・災害など)(人・国など)を苦しめる、悩ませる', '/əˈflɪkt/', 'アフリクト',
  'The region has long been afflicted by severe droughts that devastate crops and threaten food security.',
  'その地域は長い間、農作物を壊滅させ食料安全保障を脅かす深刻な干ばつに苦しめられてきた。',
  'A mysterious neurological disorder began to afflict residents of the coastal town, baffling medical experts.',
  '原因不明の神経障害がその沿岸の町の住民を苦しめ始め、医療専門家たちを困惑させた。'),
(616, 'plummet', '(価格などが)急落する;真っ逆さまに落ちる', '/ˈplʌmɪt/', 'プラミト',
  'Share prices plummeted by over thirty percent following the unexpected announcement of the CEO''s resignation.',
  'CEOの辞任という予期せぬ発表を受けて、株価は30パーセント以上急落した。',
  'Tourism revenues plummeted during the pandemic, forcing many hotels and restaurants to close permanently.',
  'パンデミックの間に観光収入が急落し、多くのホテルやレストランが恒久的な閉鎖を余儀なくされた。'),
(617, 'stunt', '(人目を引くための)派手な行為;曲芸、スタント', '/stʌnt/', 'スタント',
  'The daring publicity stunt attracted worldwide media coverage and boosted the brand''s recognition overnight.',
  'その大胆な宣伝目的の派手な行為は世界中のメディアの報道を集め、一夜にしてブランドの認知度を高めた。',
  'The politician''s opponents dismissed his dramatic speech as nothing more than an electoral stunt designed to win votes.',
  'その政治家の対立候補たちは、彼の劇的な演説を票を獲得するための選挙目的の派手な行為にすぎないと一蹴した。'),
(618, 'liable', '(法的に)責任がある、義務がある;~しがちだ', '/ˈlaɪəbl/', 'ライアブル',
  'The manufacturer was held liable for the defective product that caused serious injuries to several consumers.',
  'その製造業者は数人の消費者に重傷を負わせた欠陥製品について責任があるとされた。',
  'Without proper maintenance, the ageing infrastructure is liable to collapse during extreme weather events.',
  '適切なメンテナンスがなければ、老朽化したインフラは極端な気象現象の際に崩壊しがちだ。'),
(619, 'premise', '前提、根拠;[premises](建物の)敷地、構内', '/ˈpremɪs/', 'プレミス',
  'The entire argument was built on the premise that economic growth inevitably leads to improved living standards.',
  'その議論全体は、経済成長が必然的に生活水準の向上につながるという前提の上に構築されていた。',
  'Unauthorised individuals found on the premises after business hours will be subject to legal prosecution.',
  '営業時間後に敷地内で発見された無許可の個人は法的訴追の対象となる。'),
(620, 'demolition', '(古い建物などの)破壊、取り壊し', '/ˌdeməˈlɪʃn/', 'デモリション',
  'The demolition of the historic theatre sparked fierce protests from local heritage preservation groups.',
  'その歴史的な劇場の取り壊しは、地元の文化遺産保存団体からの激しい抗議を引き起こした。',
  'Following the earthquake, the demolition of structurally compromised buildings became an urgent public safety priority.',
  '地震の後、構造的に損傷した建物の取り壊しが緊急の公共安全上の優先事項となった。'),
(621, 'turbulent', '(世の中・時代などが)動乱の、混乱した;(天候などが)荒れ狂う', '/ˈtɜːrbjulənt/', 'タービュラント',
  'The nation endured a turbulent period of political upheaval that lasted for nearly two decades.',
  'その国は約20年にわたる動乱の政治的激変の時代を耐え忍んだ。',
  'The aircraft encountered turbulent conditions over the Atlantic, causing passengers considerable alarm.',
  'その航空機は大西洋上空で荒れ狂う気象条件に遭遇し、乗客にかなりの不安を与えた。'),
(622, 'allot', '(仕事・時間・予算など)を割り当てる、割り振る', '/əˈlɒt/', 'アロット',
  'The committee decided to allot a larger portion of the annual budget to renewable energy research.',
  '委員会は年間予算のより大きな部分を再生可能エネルギーの研究に割り当てることを決定した。',
  'Each participant was allotted precisely fifteen minutes to present their proposal to the panel of judges.',
  '各参加者には、審査員団に提案を発表するために正確に15分が割り振られた。'),
(623, 'dissect', '(動物の死体・植物)を解剖する;(理論・状況など)を分析する', '/dɪˈsekt/', 'ディセクト',
  'The biology students were required to dissect a frog as part of their anatomy coursework.',
  '生物学の学生たちは解剖学の授業の一環としてカエルを解剖することを求められた。',
  'The panel of experts proceeded to dissect the government''s economic policy, exposing several fundamental flaws.',
  '専門家のパネルは政府の経済政策を分析し、いくつかの根本的な欠陥を暴露した。'),
(624, 'provision', '(契約・法律などの)条項、規定;(必需品の)供給、支給', '/prəˈvɪʒn/', 'プロヴィジョン',
  'A provision in the new legislation requires all corporations to disclose their carbon emissions annually.',
  '新しい法律の条項は、すべての企業に年間の炭素排出量を開示することを義務づけている。',
  'The emergency provision of food and medical supplies to the flood victims was coordinated by international agencies.',
  '洪水被災者への食料と医療物資の緊急供給は国際機関によって調整された。'),
(625, 'hone', '(技術など)に磨きをかける', '/hoʊn/', 'ホウン',
  'She spent years abroad honing her linguistic skills before returning to work as a professional interpreter.',
  '彼女はプロの通訳として働くために帰国する前に、何年も海外で語学力に磨きをかけた。',
  'The apprentice chef honed his culinary techniques under the guidance of a world-renowned master.',
  'その見習いシェフは世界的に有名な巨匠の指導の下、料理の技術に磨きをかけた。'),
(626, 'jeopardy', '(損失・失敗などの)危険、危機', '/ˈdʒepərdi/', 'ジェパディ',
  'The entire project was placed in jeopardy when the primary funding source unexpectedly withdrew its support.',
  '主要な資金源が予期せず支援を撤回したとき、プロジェクト全体が危機に陥った。',
  'Failure to comply with the new environmental regulations could put the company''s operating licence in jeopardy.',
  '新しい環境規制に従わなければ、会社の営業許可が危険にさらされる可能性がある。'),
(627, 'disintegration', '崩壊、分解', '/dɪsˌɪntɪˈɡreɪʃn/', 'ディスインティグレイション',
  'The disintegration of the Soviet Union in 1991 fundamentally reshaped the geopolitical landscape of Europe.',
  '1991年のソビエト連邦の崩壊はヨーロッパの地政学的状況を根本的に変えた。',
  'Scientists observed the gradual disintegration of the glacier, accelerated by rising global temperatures.',
  '科学者たちは地球温暖化によって加速された氷河の徐々の分解を観察した。'),
(628, 'misnomer', 'ふさわしくない名前[呼び名];誤称', '/mɪsˈnoʊmər/', 'ミスノーマー',
  'Calling the substance a "safe alternative" is a misnomer, as recent studies have revealed significant health risks.',
  'その物質を「安全な代替品」と呼ぶのはふさわしくない名前であり、最近の研究で重大な健康リスクが明らかになっている。',
  'The term "rush hour" is something of a misnomer, given that traffic congestion often persists for several hours.',
  '「ラッシュアワー」という用語は、交通渋滞がしばしば数時間続くことを考えると、一種の誤称である。'),
(629, 'pitfall', '隠れた危険、落とし穴', '/ˈpɪtfɔːl/', 'ピットフォール',
  'The guidebook outlines common pitfalls that inexperienced investors should be aware of before entering the market.',
  'そのガイドブックは、経験の浅い投資家が市場に参入する前に知っておくべき一般的な落とし穴を概説している。',
  'One major pitfall of relying solely on artificial intelligence is the potential for algorithmic bias in decision-making.',
  '人工知能にのみ依存することの大きな落とし穴の一つは、意思決定におけるアルゴリズムバイアスの可能性である。'),
(630, 'meekly', 'おとなしく、従順に', '/ˈmiːkli/', 'ミークリー',
  'The defendant meekly accepted the court''s verdict without making any attempt to appeal the harsh sentence.',
  '被告は厳しい判決に対して控訴しようともせず、おとなしく裁判所の評決を受け入れた。',
  'Rather than challenging the unfair policy, the employees meekly complied with the new regulations imposed by management.',
  '不公平な方針に異議を唱えるのではなく、従業員たちは経営陣が課した新しい規制に従順に従った。'),
(631, 'terrain', '地形、地勢、土地', '/təˈreɪn/', 'テレイン',
  'The rugged terrain of the mountain range made it virtually impossible to construct a conventional railway line.',
  'その山脈の険しい地形は、従来の鉄道路線の建設をほぼ不可能にした。',
  'Military strategists carefully analysed the terrain before deploying troops to the contested border region.',
  '軍の戦略家たちは、紛争中の国境地域に部隊を展開する前に地形を慎重に分析した。'),
(632, 'brew', '(茶・コーヒーなど)をいれる、煎じる;(ビールなど)を醸造する', '/bruː/', 'ブルー',
  'The monastery has been brewing its own distinctive ale using a centuries-old recipe passed down by the monks.',
  'その修道院は修道士たちが何世紀にもわたって受け継いできたレシピを使い、独自のエールビールを醸造してきた。',
  'Political discontent had been brewing for years before it finally erupted into a full-scale revolution.',
  '政治的不満は何年も醸成されてきた末に、ついに本格的な革命へと爆発した。'),
(633, 'pseudonym', '(作家などの)ペンネーム、筆名', '/ˈsuːdənɪm/', 'スードニム',
  'The renowned author published her most controversial novel under a pseudonym to avoid public backlash.',
  'その著名な作家は世間からの反発を避けるため、最も物議を醸す小説をペンネームで出版した。',
  'The hacker operated under a pseudonym for years before investigators finally uncovered his true identity.',
  'そのハッカーは何年もの間ペンネームで活動していたが、捜査官がついに彼の本当の身元を明らかにした。'),
(634, 'stealth', '密かな行動', '/stelθ/', 'ステルス',
  'The operative infiltrated the enemy compound with remarkable stealth, avoiding detection by armed sentries.',
  '工作員は驚くべき密かな行動で敵の施設に潜入し、武装した歩哨に発見されなかった。',
  'The corporation acquired its competitors through stealth, secretly purchasing shares over a period of months.',
  'その企業は数か月にわたって密かに株式を購入し、密かな行動で競合他社を買収した。'),
(635, 'mosaic', 'モザイク風のもの、寄せ集め', '/moʊˈzeɪɪk/', 'モゼイイク',
  'The city is a vibrant mosaic of cultures, languages, and traditions that coexist in remarkable harmony.',
  'その都市は驚くほど調和して共存する文化、言語、伝統の鮮やかな寄せ集めである。',
  'The archaeologists unearthed an exquisite Roman mosaic that had been buried beneath the ruins for two millennia.',
  '考古学者たちは2千年もの間遺跡の下に埋もれていた精巧なローマのモザイクを発掘した。'),
(636, 'ponder', '(問題)について熟考する', '/ˈpɒndər/', 'ポンダー',
  'The philosopher spent decades pondering the fundamental nature of consciousness and human existence.',
  'その哲学者は意識と人間の存在の根本的な本質について何十年も熟考した。',
  'Before making such a momentous decision, I urge you to ponder the long-term consequences carefully.',
  'そのような重大な決定を下す前に、長期的な結果について慎重に熟考することを強く勧める。'),
(637, 'flex', '(筋肉)を動かす;(手足など)を曲げる', '/fleks/', 'フレックス',
  'The athlete flexed his injured shoulder cautiously to determine whether he could compete in the final event.',
  'その選手は最終種目に出場できるかを確認するため、負傷した肩を慎重に動かした。',
  'The new trade agreement allows smaller nations to flex their economic influence on the global stage.',
  '新しい貿易協定により、小国が世界の舞台で経済的影響力を発揮することが可能になった。'),
(638, 'testament', 'あかし、証拠', '/ˈtestəmənt/', 'テスタメント',
  'The longevity of the ancient aqueduct stands as a testament to the remarkable engineering skills of the Romans.',
  '古代の水路橋の長寿命は、ローマ人の卓越した工学技術のあかしとして立っている。',
  'Her rapid recovery from the devastating injury was a testament to her extraordinary determination and resilience.',
  '壊滅的な怪我からの彼女の急速な回復は、彼女の並外れた決意と回復力の証拠だった。'),
(639, 'prudence', '思慮、分別、用心深さ', '/ˈpruːdns/', 'プルーデンス',
  'Financial prudence dictates that one should maintain an emergency fund equivalent to at least six months'' expenses.',
  '財務上の分別は、少なくとも6か月分の支出に相当する緊急資金を維持すべきだと定めている。',
  'The diplomat exercised great prudence in her public statements to avoid escalating the fragile ceasefire negotiations.',
  'その外交官は脆弱な停戦交渉を悪化させないよう、公式声明において大いなる思慮を働かせた。'),
(640, 'adjacent', '隣の、隣接した', '/əˈdʒeɪsnt/', 'アジェイスント',
  'The fire quickly spread to adjacent buildings due to the strong winds and the density of the urban area.',
  '強風と都市部の密集により、火災は隣接した建物に急速に燃え広がった。',
  'The proposed development plan includes a new park adjacent to the residential complex for community use.',
  '提案された開発計画には、コミュニティの利用のための住宅団地に隣接した新しい公園が含まれている。'),
(641, 'confederation', '同盟、連合', '/kənˌfedəˈreɪʃn/', 'コンフェデレイション',
  'The confederation of independent states agreed to establish a unified military command for collective defence.',
  '独立国家の連合は集団防衛のための統一軍事指揮の設立に合意した。',
  'Several trade unions formed a confederation to strengthen their bargaining power against major corporations.',
  'いくつかの労働組合が大企業に対する交渉力を強化するために同盟を結成した。'),
(642, 'chant', '(スローガンなど)を一斉に唱える、繰り返す', '/tʃænt/', 'チャント',
  'Thousands of demonstrators marched through the capital, chanting slogans demanding political reform and accountability.',
  '何千人もの抗議者が政治改革と説明責任を求めるスローガンを一斉に唱えながら首都を行進した。',
  'The monks gathered in the ancient temple at dawn to chant sacred verses in solemn unison.',
  '僧侶たちは夜明けに古い寺院に集まり、厳粛に声を合わせて聖なる詩句を唱えた。'),
(643, 'endemic', '(深刻な状況・問題などが)(地域・集団に)よく見られる;(病気・動植物が)(地域に)特有の、固有の', '/enˈdemɪk/', 'エンデミック',
  'Corruption has become so endemic in the bureaucracy that meaningful reform will require a complete overhaul of the system.',
  '汚職が官僚機構にあまりにもよく見られるようになり、意味のある改革にはシステムの完全な見直しが必要だろう。',
  'The island is home to several endemic species of birds that cannot be found anywhere else on earth.',
  'その島には地球上の他のどこにも見られない固有の鳥類の種がいくつか生息している。'),
(644, 'unravel', '(難問など)を解決する、(謎など)を解く;(より糸・編んだものなど)をほどく', '/ʌnˈrævl/', 'アンラヴル',
  'The detective painstakingly unravelled the complex web of lies that had concealed the perpetrator''s identity for years.',
  '刑事は何年もの間犯人の身元を隠していた複雑な嘘の網を苦労して解き明かした。',
  'The fragile peace accord began to unravel as both sides accused each other of violating the ceasefire agreement.',
  '双方が互いに停戦協定の違反を非難し合い、脆弱な和平協定が崩れ始めた。'),
(645, 'curfew', '(夜間)外出禁止令;(子どもの)門限', '/ˈkɜːrfjuː/', 'カーフュー',
  'The military authorities imposed a strict curfew across the city in response to the escalating civil unrest.',
  '軍当局は激化する市民の不安に対応して、市全域に厳しい外出禁止令を課した。',
  'Teenagers who violate the midnight curfew will be escorted home by police and their parents will be notified.',
  '深夜の門限に違反した10代の若者は警察に自宅まで送られ、親に通知される。'),
(646, 'spate', '多発、続発', '/speɪt/', 'スペイト',
  'A spate of cyberattacks targeting financial institutions prompted the government to strengthen its digital security laws.',
  '金融機関を標的としたサイバー攻撃の多発が、政府にデジタルセキュリティ法の強化を促した。',
  'The recent spate of resignations among senior executives has raised concerns about the company''s internal stability.',
  '上級幹部の最近の相次ぐ辞任が、会社の内部安定性に対する懸念を引き起こしている。'),
(647, 'infringe', '(権利・自由などを)侵害する、制限する', '/ɪnˈfrɪndʒ/', 'インフリンジ',
  'The court ruled that the new surveillance programme would infringe upon the constitutional rights of ordinary citizens.',
  '裁判所は新しい監視プログラムが一般市民の憲法上の権利を侵害するだろうと判決を下した。',
  'The company was sued for manufacturing products that allegedly infringe several internationally held patents.',
  'その会社は国際的に保有されているいくつかの特許を侵害しているとされる製品の製造で訴えられた。'),
(648, 'crackdown', '(犯罪・悪事に対する)厳重な取り締まり', '/ˈkrækdaʊn/', 'クラックダウン',
  'The government announced a nationwide crackdown on tax evasion, deploying additional auditors to investigate suspicious accounts.',
  '政府は脱税に対する全国的な厳重な取り締まりを発表し、疑わしい口座を調査するため追加の監査人を配備した。',
  'The police crackdown on illegal street racing resulted in dozens of arrests and the confiscation of numerous vehicles.',
  '違法なストリートレースに対する警察の厳重な取り締まりにより、数十人が逮捕され多数の車両が没収された。'),
(649, 'reminiscent', '連想させる、思い出させる', '/ˌremɪˈnɪsnt/', 'レミニスント',
  'The architectural style of the new museum is reminiscent of the grand European galleries of the nineteenth century.',
  'その新しい博物館の建築様式は19世紀のヨーロッパの壮大な美術館を連想させる。',
  'Her haunting vocal performance was reminiscent of the legendary jazz singers of a bygone era.',
  '彼女の忘れがたいボーカルパフォーマンスは過ぎ去った時代の伝説的なジャズ歌手を思い出させるものだった。'),
(650, 'aptitude', '才能、素質、適性', '/ˈæptɪtjuːd/', 'アプティテュード',
  'From an early age, the prodigy displayed an extraordinary aptitude for mathematics that astounded her teachers.',
  '幼い頃から、その神童は教師たちを驚かせる数学に対する並外れた才能を発揮した。',
  'The aptitude test administered during the recruitment process revealed several promising candidates for the engineering role.',
  '採用過程で実施された適性テストにより、エンジニア職の有望な候補者が数人明らかになった。');
