-- words テーブル INSERT文 (No.651 ~ No.700)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(651, 'regenerate', '(地域・社会など)を再生させる、再建する', '/rɪˈdʒɛnəreɪt/', 'リジェナレイト',
  'The government launched an ambitious initiative to regenerate the economically deprived areas of the industrial north.',
  '政府は工業地帯である北部の経済的に困窮した地域を再生させるための野心的な計画を立ち上げた。',
  'Urban planners believe that investing in green spaces can regenerate neglected neighborhoods and boost community morale.',
  '都市計画者は、緑地への投資が荒廃した地域を再建し、地域の士気を高めることができると考えている。'),
(652, 'fixture', '欠かせない人[もの]、定番;(建物・家屋の)備えつけの設備、備品', '/ˈfɪkstʃər/', 'フィクスチャー',
  'Professor Tanaka has been a fixture at the university for over three decades, mentoring countless doctoral students.',
  '田中教授は30年以上にわたり大学に欠かせない存在であり、数え切れないほどの博士課程の学生を指導してきた。',
  'The antique chandelier is considered a permanent fixture of the historic mansion and cannot be removed during renovation.',
  'そのアンティークのシャンデリアは歴史的な邸宅の備えつけの設備とみなされており、改修中に取り外すことはできない。'),
(653, 'perplexed', '当惑した、まごついた', '/pərˈplɛkst/', 'パープレクスト',
  'The detective was utterly perplexed by the contradictory evidence that seemed to exonerate and implicate the suspect simultaneously.',
  '刑事は、容疑者の無罪と有罪を同時に示すかのような矛盾する証拠に完全に当惑した。',
  'Residents were left perplexed when the city council reversed its decision on the housing development without any explanation.',
  '市議会が何の説明もなく住宅開発に関する決定を撤回したため、住民たちは当惑した。'),
(654, 'dissident', '反体制派の人;反体制派の', '/ˈdɪsɪdənt/', 'ディシデント',
  'The imprisoned dissident became a symbol of resistance against the authoritarian regime that had silenced all opposition.',
  '投獄された反体制派の人物は、すべての反対意見を封じ込めた権威主義体制に対する抵抗の象徴となった。',
  'Dissident voices within the ruling party were quickly suppressed before the controversial legislation was passed.',
  '物議を醸す法案が可決される前に、与党内の反体制派の声は素早く抑え込まれた。'),
(655, 'rapport', '信頼関係、協調', '/ræˈpɔːr/', 'ラポール',
  'Establishing a strong rapport with patients is considered essential for effective psychotherapy and long-term recovery.',
  '患者との強い信頼関係を築くことは、効果的な心理療法と長期的な回復に不可欠であると考えられている。',
  'The new ambassador quickly built a rapport with foreign diplomats, facilitating smoother trade negotiations between the two nations.',
  '新しい大使はすぐに外国の外交官との信頼関係を築き、両国間の貿易交渉を円滑にした。'),
(656, 'typify', '~の典型となる、特徴を示す', '/ˈtɪpɪfaɪ/', 'ティピファイ',
  'The architect''s minimalist designs typify the aesthetic sensibilities that dominated Japanese postwar construction.',
  'その建築家のミニマリストなデザインは、日本の戦後建築を支配した美的感覚の典型となっている。',
  'Her bold decision to challenge the board of directors typifies the fearless leadership style for which she is renowned.',
  '取締役会に異議を唱えるという彼女の大胆な決断は、彼女が名高い恐れを知らないリーダーシップスタイルの特徴を示している。'),
(657, 'impunity', '処罰を受けないこと、免責', '/ɪmˈpjuːnəti/', 'インピューニティ',
  'Corrupt officials acted with impunity for years until a newly appointed prosecutor launched a comprehensive investigation.',
  '腐敗した役人たちは、新しく任命された検察官が包括的な捜査を開始するまで、何年も処罰を受けることなく行動していた。',
  'The report condemned the fact that perpetrators of war crimes continued to enjoy impunity despite overwhelming evidence.',
  '報告書は、圧倒的な証拠があるにもかかわらず、戦争犯罪の加害者が免責を享受し続けている事実を非難した。'),
(658, 'novice', '(ある分野の)初心者、未熟者', '/ˈnɒvɪs/', 'ノヴィス',
  'Even a novice in the field of astrophysics could appreciate the groundbreaking significance of the discovery.',
  '天体物理学の分野の初心者でさえ、その発見の画期的な重要性を理解することができた。',
  'The training program is specifically designed to transform novices into competent professionals within six months.',
  'その研修プログラムは、初心者を6か月以内に有能な専門家に育てることを目的として特別に設計されている。'),
(659, 'amnesty', '(政治犯などに対する)恩赦、特赦', '/ˈæmnəsti/', 'アムネスティ',
  'The newly elected president declared a general amnesty for all political prisoners as a gesture of national reconciliation.',
  '新しく選出された大統領は、国民和解の姿勢としてすべての政治犯に対する恩赦を宣言した。',
  'Critics argued that granting amnesty to tax evaders would undermine public trust in the fairness of the legal system.',
  '批評家たちは、脱税者に恩赦を与えることは法制度の公正さに対する国民の信頼を損なうと主張した。'),
(660, 'ablaze', '(激しく)燃えて;(明るく)輝いて', '/əˈbleɪz/', 'アブレイズ',
  'Within minutes of the explosion, the entire warehouse was ablaze, and firefighters struggled to contain the inferno.',
  '爆発から数分以内に倉庫全体が激しく燃え、消防士たちは猛火の封じ込めに苦戦した。',
  'The autumn hillside was ablaze with brilliant shades of crimson and gold, attracting photographers from across the region.',
  '秋の丘陵は深紅と金色の鮮やかな色合いで輝いており、各地から写真家を引きつけた。'),
(661, 'stipulation', '(法律・契約などの)規定、条項', '/ˌstɪpjʊˈleɪʃən/', 'スティピュレイション',
  'The contract contained a stipulation that all disputes must be resolved through international arbitration rather than litigation.',
  'その契約には、すべての紛争は訴訟ではなく国際仲裁によって解決しなければならないという規定が含まれていた。',
  'One key stipulation of the peace agreement was the immediate withdrawal of all military forces from the occupied territory.',
  '和平協定の重要な条項の一つは、占領地域からのすべての軍事力の即時撤退であった。'),
(662, 'commune', '(宗教・信条などを共有する)共同社会、共同体', '/ˈkɒmjuːn/', 'コミューン',
  'In the 1960s, many young idealists established communes in rural areas to pursue a self-sufficient, egalitarian lifestyle.',
  '1960年代には、多くの若い理想主義者が自給自足で平等主義的な生活を追求するため、農村地域に共同体を設立した。',
  'The artist commune on the outskirts of the city became a renowned hub for avant-garde creativity and cultural exchange.',
  '市の郊外にあるその芸術家の共同社会は、前衛的な創造性と文化交流の著名な拠点となった。'),
(663, 'chronic', '(病気が)慢性の', '/ˈkrɒnɪk/', 'クロニック',
  'Chronic sleep deprivation has been linked to a significantly elevated risk of cardiovascular disease and cognitive decline.',
  '慢性的な睡眠不足は、心血管疾患や認知機能低下のリスクの著しい上昇と関連づけられている。',
  'The region suffers from chronic water shortages that have persisted for decades despite numerous infrastructure projects.',
  'その地域は、多くのインフラ事業にもかかわらず数十年にわたって続いている慢性的な水不足に苦しんでいる。'),
(664, 'protocol', '儀礼、礼儀作法;手順、手続き;条約議定書', '/ˈproʊtəkɒl/', 'プロトコル',
  'Diplomatic protocol dictates that visiting heads of state be received with a formal ceremony at the national airport.',
  '外交儀礼は、訪問する国家元首を国立空港で公式な式典をもって迎えることを定めている。',
  'The hospital revised its emergency protocol after an internal review revealed critical delays in patient triage procedures.',
  '内部調査により患者のトリアージ手続きに重大な遅延が明らかになった後、病院は緊急時の手順を改訂した。'),
(665, 'temper', '~を加減する、抑制する', '/ˈtɛmpər/', 'テンパー',
  'The judge urged the prosecution to temper its demands with a degree of compassion, given the defendant''s circumstances.',
  '裁判官は、被告人の事情を考慮し、検察側にある程度の思いやりをもって要求を抑制するよう促した。',
  'Investors must temper their optimism with caution, as the economic recovery remains fragile and unpredictable.',
  '経済回復は依然として脆弱で予測不可能であるため、投資家は楽観主義を慎重さで抑制しなければならない。'),
(666, 'retrospect', '回顧、回想', '/ˈrɛtrəspɛkt/', 'レトロスペクト',
  'In retrospect, the decision to merge the two departments proved to be a catastrophic miscalculation by the management.',
  '回顧してみると、二つの部門を統合するという決定は、経営陣による壊滅的な判断ミスであったことが分かった。',
  'The author''s memoir offers a candid retrospect on the turbulent political events that shaped her generation.',
  'その著者の回想録は、彼女の世代を形作った激動の政治的出来事について率直な回想を提供している。'),
(667, 'interim', '仮の、暫定的な;(結果・配当などが)中間の', '/ˈɪntərɪm/', 'インテリム',
  'An interim government was established to maintain order until democratic elections could be held the following year.',
  '翌年に民主的な選挙が実施されるまでの秩序を維持するために暫定的な政府が樹立された。',
  'The company released an encouraging interim report showing a significant increase in quarterly revenue and market share.',
  'その企業は四半期収益と市場シェアの大幅な増加を示す心強い中間報告を発表した。'),
(668, 'capitalize', '利用する、活用する;~を資本化する', '/ˈkæpɪtəlaɪz/', 'キャピタライズ',
  'The startup sought to capitalize on the growing demand for renewable energy solutions in emerging markets.',
  'そのスタートアップは、新興市場における再生可能エネルギーソリューションへの需要の高まりを活用しようとした。',
  'Savvy investors capitalized on the temporary dip in stock prices to acquire undervalued shares at a significant discount.',
  '抜け目のない投資家たちは、株価の一時的な下落を利用して、割安な株式を大幅な割引で取得した。'),
(669, 'antithesis', '正反対、対照', '/ænˈtɪθəsɪs/', 'アンティシシス',
  'The candidate''s authoritarian policies were the antithesis of the democratic values the party had traditionally championed.',
  'その候補者の権威主義的な政策は、党が伝統的に擁護してきた民主主義的価値観の正反対であった。',
  'Critics described the bland, formulaic sequel as the antithesis of the original film''s bold artistic vision.',
  '批評家たちは、その味気なく型にはまった続編を、原作映画の大胆な芸術的ビジョンの正反対であると評した。'),
(670, 'ordinance', '(地方自治体の)条例', '/ˈɔːrdɪnəns/', 'オーディナンス',
  'The city council passed a new ordinance prohibiting the use of single-use plastics in all municipal buildings and parks.',
  '市議会は、すべての市の建物と公園での使い捨てプラスチックの使用を禁止する新しい条例を可決した。',
  'Local residents challenged the zoning ordinance in court, arguing that it unfairly restricted small business development.',
  '地元住民は、その区画条例が中小企業の発展を不当に制限していると主張し、法廷で異議を申し立てた。'),
(671, 'align', '~を一直線[1列]に並べる', '/əˈlaɪn/', 'アライン',
  'The company restructured its departments to align its operational strategy with the newly articulated long-term objectives.',
  'その企業は、新たに明示された長期目標に運営戦略を一致させるために部門を再編した。',
  'Engineers meticulously aligned the satellite dish to ensure optimal signal reception from the orbiting communications relay.',
  'エンジニアたちは、周回する通信中継衛星からの最適な信号受信を確保するために、衛星アンテナを入念に一直線に並べた。'),
(672, 'repeal', '(法律など)を廃止する、撤廃する', '/rɪˈpiːl/', 'リピール',
  'Activists campaigned tirelessly for decades to repeal the discriminatory legislation that had marginalized minority communities.',
  '活動家たちは、少数派コミュニティを疎外してきた差別的な法律を撤廃するために何十年にもわたって精力的に運動した。',
  'The parliament voted overwhelmingly to repeal the outdated trade regulations that had stifled economic growth for years.',
  '議会は、長年にわたり経済成長を抑制してきた時代遅れの貿易規制を廃止することを圧倒的多数で可決した。'),
(673, 'underscore', '~を強調する、明確にする;~に下線を引く', '/ˌʌndərˈskɔːr/', 'アンダースコア',
  'The devastating earthquake underscored the urgent need for stricter building codes in seismically vulnerable regions.',
  '壊滅的な地震は、地震に脆弱な地域においてより厳格な建築基準の緊急の必要性を強調した。',
  'The audit findings underscore the importance of maintaining transparent financial records throughout the fiscal year.',
  '監査結果は、会計年度を通じて透明性のある財務記録を維持することの重要性を明確にしている。'),
(674, 'ardent', '熱心な、熱狂的な', '/ˈɑːrdənt/', 'アーデント',
  'She was an ardent advocate for environmental conservation, dedicating her entire career to protecting endangered ecosystems.',
  '彼女は環境保全の熱心な提唱者であり、絶滅の危機に瀕した生態系の保護にキャリア全体を捧げた。',
  'The ardent supporters of the reform bill organized rallies across the country to demonstrate widespread public backing.',
  '改革法案の熱狂的な支持者たちは、広範な国民の支持を示すために全国各地で集会を組織した。'),
(675, 'depreciate', '(価値・価格などが)下がる;~の価値[価格]を下げる', '/dɪˈpriːʃieɪt/', 'ディプリーシエイト',
  'The national currency depreciated sharply against the dollar following the central bank''s unexpected decision to cut interest rates.',
  '中央銀行の予想外の利下げ決定を受けて、自国通貨はドルに対して急激に下落した。',
  'Commercial vehicles depreciate rapidly within the first three years, making used models an attractive option for small businesses.',
  '商用車は最初の3年間で急速に価値が下がるため、中古モデルは中小企業にとって魅力的な選択肢となっている。'),
(676, 'hype', '誇大広告', '/haɪp/', 'ハイプ',
  'Despite all the media hype surrounding the product launch, consumer reviews revealed significant performance shortcomings.',
  '製品発売をめぐるメディアの誇大広告にもかかわらず、消費者レビューでは重大な性能の欠陥が明らかになった。',
  'Industry analysts warned investors not to be swayed by the hype and to evaluate the company''s fundamentals objectively.',
  '業界アナリストは投資家に、誇大広告に惑わされず、企業のファンダメンタルズを客観的に評価するよう警告した。'),
(677, 'adversary', '敵;(競技・試合などの)相手、対戦者', '/ˈædvərsɛri/', 'アドヴァーサリー',
  'The chess grandmaster studied his adversary''s previous matches meticulously to devise an effective counter-strategy.',
  'そのチェスのグランドマスターは、効果的な対抗戦略を考案するために対戦者の過去の試合を入念に研究した。',
  'In international diplomacy, it is often more productive to engage one''s adversary in dialogue than to resort to sanctions.',
  '国際外交において、制裁に訴えるよりも敵と対話に臨む方がしばしばより生産的である。'),
(678, 'moratorium', '(製造・使用などの)一時的停止[禁止];支払い猶予', '/ˌmɒrəˈtɔːriəm/', 'モラトリアム',
  'The government imposed a moratorium on deep-sea drilling until the environmental impact assessment was completed.',
  '政府は環境影響評価が完了するまで、深海掘削の一時的停止を課した。',
  'Several nations called for an immediate moratorium on nuclear weapons testing to facilitate disarmament negotiations.',
  'いくつかの国が軍縮交渉を促進するために核兵器実験の即時禁止を求めた。'),
(679, 'ailing', '(慢性的に)病気の、病弱な;不況の、不振の', '/ˈeɪlɪŋ/', 'エイリング',
  'The ailing steel industry required a massive injection of government subsidies to prevent widespread factory closures.',
  '不振の鉄鋼産業は、広範な工場閉鎖を防ぐために政府補助金の大規模な投入を必要とした。',
  'She devoted the final years of her life to caring for her ailing mother, who suffered from a degenerative neurological condition.',
  '彼女は、変性神経疾患を患っていた病弱な母親の介護に人生の最後の数年間を捧げた。'),
(680, 'relentless', '(不快なことが)容赦なく続く;情け容赦のない、厳しい', '/rɪˈlɛntləs/', 'リレントレス',
  'The relentless bombardment of the besieged city continued for weeks, reducing entire neighborhoods to rubble.',
  '包囲された都市への容赦ない砲撃は何週間も続き、近隣地域全体を瓦礫の山と化した。',
  'Her relentless pursuit of academic excellence earned her a prestigious fellowship at one of the world''s leading research institutions.',
  '学問的卓越性への彼女の容赦なき追求により、世界有数の研究機関の一つで名誉あるフェローシップを獲得した。'),
(681, 'transient', '一時的な、束の間の', '/ˈtrænziənt/', 'トランジエント',
  'The economic boom proved to be transient, as a severe recession struck the region within just two years.',
  'その経済ブームは一時的なものであったことが判明し、わずか2年以内にその地域は深刻な不況に見舞われた。',
  'Philosophers have long contemplated the transient nature of human existence and its implications for how we find meaning.',
  '哲学者たちは長い間、人間の存在の束の間の本質と、それが私たちの意味の見出し方に対して持つ意味について考察してきた。'),
(682, 'orchestrate', '(複雑な計画など)を企てる、周到に準備する', '/ˈɔːrkɪstreɪt/', 'オーケストレイト',
  'Intelligence agencies revealed that a foreign government had orchestrated the cyberattack on critical national infrastructure.',
  '諜報機関は、外国政府が重要な国家インフラへのサイバー攻撃を企てたことを明らかにした。',
  'The event coordinator brilliantly orchestrated the international summit, ensuring every logistical detail was flawlessly executed.',
  'イベントコーディネーターは国際サミットを見事に周到に準備し、あらゆるロジスティクスの細部が完璧に実行されるようにした。'),
(683, 'sprout', '発芽する;急成長する', '/spraʊt/', 'スプラウト',
  'New technology startups have sprouted across the region, transforming the once-declining industrial town into a thriving innovation hub.',
  '新しいテクノロジー系のスタートアップがその地域全体で急成長し、かつて衰退していた工業都市を繁栄するイノベーションの拠点へと変貌させた。',
  'After weeks of careful cultivation, the first seedlings finally sprouted, bringing hope to the community''s urban farming initiative.',
  '何週間もの丁寧な栽培の後、最初の苗がついに発芽し、地域の都市農業計画に希望をもたらした。'),
(684, 'assail', '(身体的に・言葉で)(人・もの)を攻撃する', '/əˈseɪl/', 'アセイル',
  'Opposition lawmakers assailed the prime minister''s economic policy, calling it reckless and detrimental to working families.',
  '野党議員たちは首相の経済政策を攻撃し、無謀で勤労世帯に有害であると批判した。',
  'The whistleblower was assailed from all sides by corporate executives seeking to discredit her testimony before the committee.',
  '内部告発者は、委員会での彼女の証言の信用を失墜させようとする企業幹部たちからあらゆる方面から攻撃された。'),
(685, 'affable', '愛想のよい、気さくな', '/ˈæfəbəl/', 'アファブル',
  'The CEO''s affable demeanor during public appearances belied the ruthless efficiency with which she managed the corporation.',
  '公の場でのCEOの愛想のよい態度は、彼女が企業を管理する際の容赦ない効率性とは対照的であった。',
  'Diplomats praised the ambassador for his affable nature, which helped ease tensions during the protracted border negotiations.',
  '外交官たちは、長引く国境交渉中の緊張を和らげるのに役立った大使の気さくな性格を称賛した。'),
(686, 'disheveled', '(髪が)乱れた;(服装が)だらしない', '/dɪˈʃɛvəld/', 'ディシェヴェルド',
  'The exhausted researcher emerged from the laboratory looking disheveled after working through the night on the critical experiment.',
  '疲れ果てた研究者は、重要な実験に徹夜で取り組んだ後、髪が乱れた様子で研究室から出てきた。',
  'His disheveled appearance at the board meeting raised concerns among colleagues about his ability to cope with the mounting pressure.',
  '取締役会でのだらしない服装は、増大するプレッシャーに対処する彼の能力について同僚たちの間で懸念を引き起こした。'),
(687, 'insatiable', '(欲求・好奇心などが)飽くことを知らない、貪欲な', '/ɪnˈseɪʃəbəl/', 'インセイシャブル',
  'Her insatiable curiosity about ancient civilizations drove her to pursue archaeological excavations on three different continents.',
  '古代文明に対する彼女の飽くことを知らない好奇心が、三つの異なる大陸での考古学的発掘を追求する原動力となった。',
  'The corporation''s insatiable appetite for expansion led to a series of aggressive acquisitions that eventually destabilized its finances.',
  'その企業の貪欲な拡大欲は、一連の積極的な買収をもたらし、最終的に財務を不安定にした。'),
(688, 'defraud', '(人)から(金・権利などを)だまし取る、詐取する', '/dɪˈfrɔːd/', 'ディフロード',
  'The elaborate Ponzi scheme defrauded thousands of unsuspecting investors of their life savings over a period of fifteen years.',
  'その精巧なねずみ講は、15年にわたって何千人もの無防備な投資家から生涯の貯蓄をだまし取った。',
  'The former executive was convicted of conspiring to defraud the government by submitting falsified tax returns for multiple years.',
  'その元幹部は、複数年にわたり虚偽の確定申告を提出して政府から詐取する共謀の罪で有罪となった。'),
(689, 'arcane', '(普通の人には)難解な、少数の人だけが理解している', '/ɑːrˈkeɪn/', 'アーケイン',
  'The arcane regulations governing international maritime law are comprehensible only to a handful of specialized legal scholars.',
  '国際海事法を規定する難解な規則は、少数の専門的な法学者にしか理解できない。',
  'He possessed an encyclopedic knowledge of the arcane rituals and traditions that had been preserved by the indigenous community for centuries.',
  '彼は、先住民コミュニティによって何世紀にもわたって保存されてきた難解な儀式と伝統に関する百科事典的な知識を持っていた。'),
(690, 'autonomously', '自律的に、自発的に', '/ɔːˈtɒnəməsli/', 'オートノマスリー',
  'The unmanned spacecraft is designed to navigate autonomously through deep space without any real-time input from ground control.',
  'その無人宇宙船は、地上管制からのリアルタイムの入力なしに深宇宙を自律的に航行するように設計されている。',
  'The regional office operates autonomously, making its own strategic decisions without seeking prior approval from headquarters.',
  'その地方事務所は自律的に運営されており、本社の事前承認を求めることなく独自の戦略的決定を下している。'),
(691, 'distraught', '(心配などで)取り乱した、動転した', '/dɪˈstrɔːt/', 'ディストロート',
  'The distraught families of the missing passengers demanded a thorough investigation into the cause of the maritime disaster.',
  '行方不明の乗客の取り乱した家族たちは、海難事故の原因の徹底的な調査を要求した。',
  'She was visibly distraught upon learning that the scholarship she had worked so hard to obtain had been rescinded.',
  '一生懸命に獲得しようとしていた奨学金が取り消されたことを知り、彼女は目に見えて動転した。'),
(692, 'affix', '(もの)を貼る、添付する', '/əˈfɪks/', 'アフィクス',
  'Delegates were required to affix their official seals to the treaty document before it could be ratified by the assembly.',
  '代表者たちは、条約文書が議会で批准される前に公式の印章を貼ることを求められた。',
  'The customs officer instructed the importer to affix the appropriate certification labels to every container before clearance.',
  '税関職員は、通関前にすべてのコンテナに適切な認証ラベルを添付するよう輸入業者に指示した。'),
(693, 'wayward', '(人が)わがままな、手に負えない', '/ˈweɪwərd/', 'ウェイワード',
  'The novel chronicles the turbulent life of a wayward aristocrat who defied every social convention of his era.',
  'その小説は、自分の時代のあらゆる社会的慣習に背いたわがままな貴族の波乱に満ちた生涯を描いている。',
  'The rehabilitation program was specifically designed to help wayward youths reintegrate into society through vocational training.',
  'そのリハビリプログラムは、手に負えない若者たちが職業訓練を通じて社会に再統合できるよう特別に設計された。'),
(694, 'allude', 'ほのめかす、遠回しに言う', '/əˈluːd/', 'アルード',
  'The ambassador carefully alluded to the possibility of imposing economic sanctions without making any explicit threat.',
  '大使は明確な脅迫をすることなく、経済制裁を課す可能性を慎重にほのめかした。',
  'In her resignation speech, the minister alluded to internal corruption within the party but declined to name specific individuals.',
  '辞任演説の中で、大臣は党内の内部腐敗を遠回しに言及したが、具体的な個人名を挙げることは拒否した。'),
(695, 'cordon', '(警察などによる)非常線、包囲網', '/ˈkɔːrdən/', 'コードン',
  'Police immediately established a cordon around the building after receiving a credible bomb threat from an anonymous caller.',
  '匿名の通報者から信頼性のある爆弾の脅迫を受けた後、警察は直ちにその建物の周囲に非常線を張った。',
  'Security forces maintained a tight cordon around the embassy throughout the duration of the political crisis.',
  '治安部隊は政治危機の間中、大使館の周囲に厳重な包囲網を維持した。'),
(696, 'tatter', 'ぼろ、ぼろ切れ', '/ˈtætər/', 'タター',
  'The war refugees arrived at the border wearing clothes in tatters, having walked for days through treacherous mountain terrain.',
  '戦争難民たちは、険しい山岳地帯を何日も歩いた末に、ぼろをまとって国境に到着した。',
  'The once-magnificent flag of the fallen empire now hung in tatters above the ruins of the abandoned fortress.',
  '崩壊した帝国のかつて壮麗な旗は、今では廃墟となった要塞の上にぼろ切れとなってぶら下がっていた。'),
(697, 'careen', '(人・車などが)大きく揺れながら疾走する', '/kəˈriːn/', 'カリーン',
  'The out-of-control bus careened down the steep mountain road, narrowly avoiding a catastrophic collision with oncoming traffic.',
  '制御不能のバスが急な山道を大きく揺れながら疾走し、対向車との壊滅的な衝突をかろうじて回避した。',
  'Witnesses described how the stolen vehicle careened through the crowded marketplace before crashing into a concrete barrier.',
  '目撃者たちは、盗難車両が混雑した市場を大きく揺れながら疾走し、コンクリートの障壁に衝突した様子を語った。'),
(698, 'haggle', '値切る、(値段などについて)交渉する', '/ˈhæɡəl/', 'ハグル',
  'Tourists unfamiliar with the local customs were surprised to find that vendors expected them to haggle over every purchase.',
  '地元の慣習に不慣れな観光客は、露天商がすべての購入について値切ることを期待していることに驚いた。',
  'The two corporations haggled over the terms of the merger for months before finally reaching a mutually acceptable agreement.',
  '二つの企業は合併条件について何か月も交渉した末、最終的に双方が受け入れ可能な合意に達した。'),
(699, 'contrition', '(犯した罪・悪行などについての)悔恨', '/kənˈtrɪʃən/', 'コントリション',
  'The defendant''s apparent lack of contrition during the sentencing hearing prompted the judge to impose the maximum penalty.',
  '量刑審理における被告人の明らかな悔恨の欠如は、裁判官に最高刑を科すよう促した。',
  'Public contrition alone is insufficient; the corporation must take concrete steps to compensate the communities it has harmed.',
  '公の場での悔恨だけでは不十分であり、その企業は被害を受けたコミュニティに補償するための具体的な措置を講じなければならない。'),
(700, 'woo', '(人)の支持を得ようと努める', '/wuː/', 'ウー',
  'Both political parties are aggressively trying to woo undecided voters in the swing states ahead of the general election.',
  '両政党は総選挙を前に、激戦州の未決定の有権者の支持を得ようと積極的に努めている。',
  'The city launched a comprehensive campaign to woo foreign investors by offering generous tax incentives and streamlined regulations.',
  '市は寛大な税制優遇措置と合理化された規制を提供することで、外国人投資家の支持を得ようと包括的なキャンペーンを開始した。');
