-- words テーブル INSERT文 (No.751 ~ No.800)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(751, 'irrepressible', '(人が)快活な、自信にあふれた;(感情・行為などが)抑えられない', '/ˌɪrɪˈprɛsəbl/', 'イリプレサブル',
  'The irrepressible optimism of the young entrepreneur inspired her colleagues to persevere despite mounting obstacles.',
  'その若い起業家の抑えきれない楽観主義が、障害が増す中でも同僚たちに頑張り続ける気持ちを与えた。',
  'Even after receiving harsh criticism, his irrepressible spirit drove him to refine his proposal and submit it again.',
  '厳しい批判を受けた後でも、彼の抑えがたい精神力が提案を練り直して再提出する原動力となった。'),
(752, 'debrief', '(軍人・外交官・パイロットなど)に報告を求める', '/diːˈbriːf/', 'ディブリーフ',
  'The intelligence officers were debriefed immediately upon returning from the covert operation in hostile territory.',
  '諜報員たちは敵地での秘密作戦から帰還後、直ちに報告を求められた。',
  'After the diplomatic summit concluded, senior officials debriefed the ambassador on every detail of the negotiations.',
  '外交サミット終了後、高官たちは大使に交渉のあらゆる詳細について報告を求めた。'),
(753, 'expropriate', '(政府などが)(土地・財産など)を没収する、収用する', '/ɛksˈproʊpriˌeɪt/', 'エクスプロウプリエイト',
  'The government expropriated vast tracts of farmland to construct a new highway connecting the two major cities.',
  '政府は二つの大都市を結ぶ新しい高速道路を建設するために広大な農地を収用した。',
  'Residents protested vigorously when the municipality announced plans to expropriate their properties for urban redevelopment.',
  '市が都市再開発のために住民の所有地を収用する計画を発表すると、住民たちは激しく抗議した。'),
(754, 'relish', '(思いつき・可能性)を楽しむ', '/ˈrɛlɪʃ/', 'レリッシュ',
  'She relished the opportunity to present her groundbreaking research at the international symposium on biomedical engineering.',
  '彼女は生体工学に関する国際シンポジウムで画期的な研究を発表する機会を楽しんだ。',
  'The seasoned diplomat relished the challenge of brokering peace between the two nations that had been at odds for decades.',
  'その熟練した外交官は、何十年も対立してきた二国間の平和を仲介するという挑戦を楽しんだ。'),
(755, 'atrocious', '(品質などが)悪い、ひどい;残虐な', '/əˈtroʊʃəs/', 'アトロウシャス',
  'The atrocious working conditions in the factory prompted a nationwide investigation by the labor regulatory authority.',
  '工場のひどい労働条件が、労働規制当局による全国的な調査を促した。',
  'Critics condemned the film for its atrocious screenplay, calling it the worst production of the decade.',
  '批評家たちはその映画のひどい脚本を非難し、この10年で最悪の作品だと評した。'),
(756, 'infuse', '(思想・活力など)を吹き込む', '/ɪnˈfjuːz/', 'インフューズ',
  'The newly appointed director infused the struggling organization with a renewed sense of purpose and direction.',
  '新任のディレクターは、苦境にある組織に新たな目的意識と方向性を吹き込んだ。',
  'The government infused substantial capital into the ailing industry to prevent a catastrophic economic collapse.',
  '政府は壊滅的な経済崩壊を防ぐために、低迷する産業に多額の資本を注入した。'),
(757, 'assiduous', '根気強い、勤勉な;入念な', '/əˈsɪdʒuəs/', 'アシジュアス',
  'Through assiduous research spanning over a decade, the scientist finally identified the gene responsible for the rare disorder.',
  '10年以上にわたる根気強い研究を通じて、その科学者はついに稀な疾患の原因遺伝子を特定した。',
  'The assiduous attention to detail displayed by the restoration team preserved the cathedral''s original splendor.',
  '修復チームが見せた入念な細部へのこだわりが、大聖堂の本来の壮麗さを保った。'),
(758, 'detonate', '(爆弾など)を爆発させる', '/ˈdɛtəˌneɪt/', 'デトネイト',
  'The bomb disposal unit successfully detonated the unexploded ordnance discovered at the construction site without any casualties.',
  '爆弾処理班は建設現場で発見された不発弾を死傷者なく無事に爆発させた。',
  'Investigators determined that the device had been remotely detonated using a sophisticated electronic trigger mechanism.',
  '捜査官は、その装置が高度な電子トリガー機構を用いて遠隔爆発させられたと断定した。'),
(759, 'sumptuous', '豪華な、ぜいたくな', '/ˈsʌmptʃuəs/', 'サンプチュアス',
  'The ambassador hosted a sumptuous banquet featuring dishes prepared by three Michelin-starred chefs from across Europe.',
  '大使はヨーロッパ各地の三つ星シェフが調理した料理を揃えた豪華な宴会を催した。',
  'The palace''s sumptuous interior, adorned with gold leaf and priceless tapestries, left the visiting dignitaries speechless.',
  '金箔と貴重なタペストリーで飾られた宮殿の豪華な内装に、訪問した要人たちは言葉を失った。'),
(760, 'hurtle', '(車などが)猛スピードで進む、突進する', '/ˈhɜːrtl/', 'ハートル',
  'The out-of-control freight train hurtled through the station, narrowly missing the passengers standing on the platform.',
  '制御不能の貨物列車が駅を猛スピードで突き抜け、ホームに立っていた乗客をかろうじて避けた。',
  'Debris from the collapsed building hurtled toward the street below, forcing emergency crews to evacuate the surrounding area.',
  '崩壊した建物の瓦礫が下の通りに向かって突進し、緊急隊員は周辺地域を避難させざるを得なかった。'),
(761, 'profusion', '多数、多種多様', '/prəˈfjuːʒən/', 'プロフュージョン',
  'A profusion of wildflowers blanketed the alpine meadow, creating a breathtaking spectacle that attracted photographers from around the world.',
  '多種多様な野花が高山の草原を覆い、世界中から写真家を引きつける息をのむような光景を生み出した。',
  'The marketplace offered a profusion of handcrafted goods, ranging from intricate pottery to elaborately woven textiles.',
  'その市場には精巧な陶器から手の込んだ織物まで、多種多様な手工芸品が並んでいた。'),
(762, 'perspire', '汗をかく、発汗する', '/pərˈspaɪər/', 'パースパイア',
  'The candidates perspired visibly under the intense studio lights during the nationally televised presidential debate.',
  '全国放送された大統領討論会の間、候補者たちは強烈なスタジオ照明の下で目に見えて汗をかいていた。',
  'Despite the sweltering heat, the soldiers continued to march without rest, perspiring profusely beneath their heavy gear.',
  '酷暑にもかかわらず、兵士たちは休むことなく行軍を続け、重い装備の下で大量に汗をかいた。'),
(763, 'impromptu', '即席の、即興の、準備なしの', '/ɪmˈprɑːmptuː/', 'インプロンプトゥー',
  'The prime minister delivered an impromptu speech at the press conference that captivated journalists with its eloquence and candor.',
  '首相が記者会見で行った即席のスピーチは、その雄弁さと率直さでジャーナリストたちを魅了した。',
  'What began as an impromptu gathering of neighbors evolved into a large-scale community event that raised thousands for charity.',
  '近所の人々の即席の集まりとして始まったものが、慈善のために数千ドルを集める大規模な地域イベントへと発展した。'),
(764, 'indiscretion', '軽率な言動;軽率、無分別', '/ˌɪndɪˈskrɛʃən/', 'インディスクレション',
  'The senator''s youthful indiscretions resurfaced during the campaign, threatening to derail his bid for reelection.',
  'その上院議員の若い頃の軽率な言動が選挙戦中に再浮上し、再選を目指す活動を頓挫させかねなかった。',
  'A single indiscretion by the CEO, leaked to the press, resulted in a dramatic plunge in the company''s stock price.',
  'CEOのたった一つの軽率な行動がマスコミに漏れ、同社の株価の劇的な暴落を招いた。'),
(765, 'catapult', '(人)を一躍(有名・スターなどに)押し上げる', '/ˈkætəˌpʌlt/', 'キャタパルト',
  'The viral documentary catapulted the obscure environmental activist to international fame virtually overnight.',
  'そのバイラルなドキュメンタリーが、無名の環境活動家をほぼ一夜にして国際的な名声へと押し上げた。',
  'A single bestselling novel catapulted the young author from anonymity into the ranks of the world''s most celebrated writers.',
  '一冊のベストセラー小説が、若い作家を無名から世界で最も著名な作家の仲間入りへと一躍押し上げた。'),
(766, 'jest', '冗談、しゃれ', '/dʒɛst/', 'ジェスト',
  'What was intended as an innocent jest during the board meeting was misconstrued as a serious policy recommendation.',
  '取締役会で無邪気な冗談のつもりだったものが、真剣な政策提案と誤解された。',
  'The diplomat''s jest about international trade tensions, though lighthearted, underscored the gravity of the ongoing negotiations.',
  '国際貿易摩擦に関するその外交官の冗談は、軽い調子ではあったものの、進行中の交渉の深刻さを浮き彫りにした。'),
(767, 'teeter', 'ぐらつく、よろめく', '/ˈtiːtər/', 'ティーター',
  'The economy teetered on the brink of recession as consumer confidence plummeted and unemployment rates soared.',
  '消費者信頼感が急落し失業率が急上昇する中、経済は不況の瀬戸際でぐらついていた。',
  'The aging infrastructure of the bridge teetered dangerously under the weight of modern traffic, prompting calls for immediate renovation.',
  '橋の老朽化したインフラが現代の交通量の重みで危険にぐらつき、即座の改修を求める声が上がった。'),
(768, 'footage', '映像、(テレビ・映画などの)場面', '/ˈfʊtɪdʒ/', 'フッテージ',
  'Surveillance footage from the warehouse revealed that the theft had been orchestrated by a former employee with insider knowledge.',
  '倉庫の監視映像により、窃盗は内部情報を持つ元従業員が企てたものであることが判明した。',
  'The documentary relied heavily on archival footage from the 1960s to reconstruct the pivotal moments of the civil rights movement.',
  'そのドキュメンタリーは公民権運動の重要な瞬間を再現するために1960年代のアーカイブ映像に大きく依存していた。'),
(769, 'amiable', '人当たりのよい、愛想のよい', '/ˈeɪmiəbl/', 'エイミアブル',
  'The professor''s amiable demeanor made even the most apprehensive students feel comfortable asking questions in her lectures.',
  'その教授の人当たりのよい態度は、最も不安を感じている学生でさえ講義中に気楽に質問できるようにした。',
  'Despite his formidable reputation in the courtroom, the barrister was known among colleagues for his amiable and approachable nature.',
  '法廷での手ごわい評判にもかかわらず、その法廷弁護士は同僚の間で愛想がよく親しみやすい人柄で知られていた。'),
(770, 'idly', '怠けて、何もしないで', '/ˈaɪdli/', 'アイドリー',
  'The committee could not stand idly by while the environmental degradation continued to ravage the coastal ecosystems.',
  '沿岸の生態系が環境破壊によって荒廃し続ける中、委員会は何もしないで傍観するわけにはいかなかった。',
  'Rather than sitting idly during the economic downturn, the corporation invested heavily in research and development for future growth.',
  '景気低迷期に何もせず座っているのではなく、その企業は将来の成長のために研究開発に多額の投資をした。'),
(771, 'balk', '躊躇する、ためらう', '/bɔːk/', 'ボーク',
  'Several investors balked at the proposed merger, citing concerns over the target company''s mounting debt obligations.',
  '数人の投資家が、対象企業の増大する債務を懸念して、提案された合併を躊躇した。',
  'The union balked at accepting the revised contract, arguing that the wage increase was insufficient to offset rising living costs.',
  '労働組合は改訂された契約の受け入れをためらい、賃上げ額が生活費上昇を補うには不十分だと主張した。'),
(772, 'degenerate', '悪化する、堕落する', '/dɪˈdʒɛnəˌreɪt/', 'ディジェネレイト',
  'What began as a civil parliamentary debate quickly degenerated into a chaotic exchange of personal insults and accusations.',
  '礼節ある議会の議論として始まったものが、すぐに個人的な侮辱と非難の混乱したやり取りへと悪化した。',
  'Without proper maintenance, the historic district degenerated into a neglected area plagued by vandalism and structural decay.',
  '適切な維持管理がなければ、その歴史的地区は破壊行為と構造的劣化に悩まされる放置された地域へと堕落した。'),
(773, 'secrete', '(臓器が)~を分泌する', '/sɪˈkriːt/', 'シクリート',
  'The pancreas secretes insulin to regulate blood sugar levels, a process that is impaired in patients with type 1 diabetes.',
  '膵臓は血糖値を調節するためにインスリンを分泌するが、この過程は1型糖尿病患者では障害されている。',
  'Researchers discovered that the newly identified gland secretes a hormone that plays a crucial role in regulating sleep cycles.',
  '研究者たちは、新たに特定された腺が睡眠周期の調節に重要な役割を果たすホルモンを分泌することを発見した。'),
(774, 'quizzical', '(表情が)いぶかしげな、不思議そうな', '/ˈkwɪzɪkəl/', 'クウィジカル',
  'The professor gave a quizzical look when the student proposed a theory that contradicted decades of established research.',
  '学生が何十年にもわたる確立された研究と矛盾する理論を提案したとき、教授はいぶかしげな表情を見せた。',
  'Her quizzical expression suggested that she was far from convinced by the consultant''s optimistic financial projections.',
  '彼女のいぶかしげな表情は、コンサルタントの楽観的な財務予測に到底納得していないことを示していた。'),
(775, 'dazzle', '(美しさ・能力などで)(人)を驚嘆させる;(強い光が)~の目をくらませる', '/ˈdæzl/', 'ダズル',
  'The virtuoso pianist dazzled the audience with a flawless rendition of Rachmaninoff''s notoriously difficult Third Concerto.',
  'その名手のピアニストは、ラフマニノフの難曲として名高い第3協奏曲の完璧な演奏で聴衆を驚嘆させた。',
  'The sheer scale and architectural ingenuity of the newly unveiled museum dazzled visitors from the moment they entered.',
  '新たに公開された美術館の圧倒的な規模と建築的な創意工夫が、入場した瞬間から来場者を驚嘆させた。'),
(776, 'upshot', '結末、結論', '/ˈʌpˌʃɑːt/', 'アップショット',
  'The upshot of the lengthy arbitration was that both parties were required to make significant concessions to reach a settlement.',
  '長期にわたる仲裁の結末は、和解に至るために両当事者が大幅な譲歩を求められるというものだった。',
  'After months of deliberation, the upshot of the committee''s review was a complete overhaul of the existing regulatory framework.',
  '数か月の審議の後、委員会の検討の結論は既存の規制枠組みの全面的な見直しであった。'),
(777, 'dupe', '(人)をだます、かつぐ', '/duːp/', 'デュープ',
  'The fraudulent investment scheme duped thousands of retirees into surrendering their life savings with promises of exorbitant returns.',
  '詐欺的な投資スキームは、法外なリターンの約束で数千人の退職者をだまして老後の蓄えを差し出させた。',
  'Consumers were duped by the company''s misleading advertising, which grossly exaggerated the efficacy of its weight-loss supplement.',
  '消費者はその企業の誤解を招く広告にだまされたが、その広告は減量サプリメントの効能を大幅に誇張していた。'),
(778, 'insurgency', '反乱、暴動', '/ɪnˈsɜːrdʒənsi/', 'インサージェンシー',
  'The protracted insurgency in the northern provinces destabilized the entire region and displaced millions of civilians.',
  '北部州での長期化する反乱が地域全体を不安定にし、数百万人の民間人を避難させた。',
  'International forces struggled to quell the insurgency, which had gained momentum through sophisticated guerrilla tactics.',
  '国際部隊は、巧妙なゲリラ戦術で勢いを増した反乱を鎮圧するのに苦労した。'),
(779, 'proscribe', '(危険・有害だとして法的に)~を禁止する', '/proʊˈskraɪb/', 'プロスクライブ',
  'The legislation proscribed the use of certain hazardous chemicals in consumer products, imposing heavy fines on violators.',
  'その法律は消費者製品における特定の有害化学物質の使用を禁止し、違反者に重い罰金を課した。',
  'The international treaty proscribed the development and stockpiling of biological weapons by all signatory nations.',
  'その国際条約は、すべての署名国による生物兵器の開発と備蓄を禁止した。'),
(780, 'slam', '~を酷評する、こき下ろす;(ドア・窓など)をバタンと閉める', '/slæm/', 'スラム',
  'The opposition leader slammed the government''s handling of the pandemic, calling it a catastrophic failure of leadership.',
  '野党党首は政府のパンデミック対応を酷評し、指導力の壊滅的な失敗と呼んだ。',
  'Film critics universally slammed the sequel for its incoherent plot and wooden performances by the lead actors.',
  '映画批評家たちはその続編を、一貫性のないプロットと主演俳優たちの棒読みの演技で一様に酷評した。'),
(781, 'glitch', '(計画の)狂い;(機械などの)故障、不調', '/ɡlɪtʃ/', 'グリッチ',
  'A software glitch in the trading platform triggered a series of erroneous transactions worth millions of dollars.',
  '取引プラットフォームのソフトウェアの不調が、数百万ドル相当の一連の誤った取引を引き起こした。',
  'The satellite launch was postponed indefinitely after engineers detected a critical glitch in the navigation system.',
  'エンジニアが航行システムに重大な故障を発見した後、衛星の打ち上げは無期限に延期された。'),
(782, 'arable', '(土地が)耕作に適した', '/ˈærəbl/', 'アラブル',
  'The expansion of urban development has significantly reduced the amount of arable land available for agricultural production.',
  '都市開発の拡大により、農業生産に利用できる耕作適地の面積が大幅に減少した。',
  'Climate change is projected to render vast swathes of currently arable land unsuitable for cultivation within the next few decades.',
  '気候変動により、今後数十年以内に現在耕作に適した広大な土地が栽培に不適になると予測されている。'),
(783, 'rant', '(興奮した声で)わめき散らす、声を張り上げる', '/rænt/', 'ラント',
  'The disgruntled shareholder ranted about the board''s incompetence for nearly twenty minutes before being asked to yield the floor.',
  '不満を持つ株主は取締役会の無能さについて約20分間わめき散らした後、発言を譲るよう求められた。',
  'The talk show host''s unscripted rant about government corruption went viral, sparking a nationwide debate on political accountability.',
  'トーク番組の司会者が台本なしで政府の汚職についてわめいた場面がバイラルとなり、政治的説明責任に関する全国的な議論を巻き起こした。'),
(784, 'recurrent', '繰り返し起こる、再発する', '/rɪˈkɜːrənt/', 'リカレント',
  'The recurrent flooding in the low-lying region prompted the government to invest in a comprehensive flood prevention infrastructure.',
  '低地での繰り返し起こる洪水が、政府に包括的な洪水防止インフラへの投資を促した。',
  'Patients suffering from recurrent migraines were enrolled in a clinical trial to evaluate the efficacy of a novel treatment.',
  '再発する偏頭痛に苦しむ患者たちが、新しい治療法の有効性を評価する臨床試験に登録された。'),
(785, 'orator', '雄弁家、達弁家', '/ˈɔːrətər/', 'オレイター',
  'Regarded as one of the finest orators of his generation, the statesman could sway public opinion with a single address.',
  '同世代で最も優れた雄弁家の一人と見なされ、その政治家は一度の演説で世論を動かすことができた。',
  'The competition sought to identify the most gifted young orators who could articulate complex ideas with clarity and conviction.',
  'そのコンテストは、複雑な考えを明瞭さと確信をもって述べることができる最も才能ある若き雄弁家を見出すことを目的としていた。'),
(786, 'bail', '保釈金;保釈', '/beɪl/', 'ベイル',
  'The judge set bail at an unprecedented amount, reflecting the severity of the charges and the defendant''s perceived flight risk.',
  '裁判官は容疑の重大さと被告の逃亡リスクを考慮し、保釈金を前例のない額に設定した。',
  'The suspect was denied bail after prosecutors argued that releasing him would pose an imminent threat to public safety.',
  '検察官が被告を釈放すれば公共の安全に差し迫った脅威をもたらすと主張し、容疑者の保釈は認められなかった。'),
(787, 'bogus', '偽の、偽造の', '/ˈboʊɡəs/', 'ボウガス',
  'Customs officials intercepted a shipment of bogus pharmaceuticals that could have posed a serious risk to unsuspecting consumers.',
  '税関職員は、何も知らない消費者に深刻なリスクをもたらしかねない偽造医薬品の積荷を差し押さえた。',
  'The investigation revealed that the company had been issuing bogus safety certifications to expedite the approval of its products.',
  '調査により、その企業が製品の承認を迅速化するために偽の安全認証を発行していたことが判明した。'),
(788, 'query', '(組織・専門家への)質問、問い合わせ', '/ˈkwɪri/', 'クウィリー',
  'The technical support team received an overwhelming number of queries after the software update introduced several unexpected bugs.',
  'ソフトウェアのアップデートが予期せぬバグをいくつか引き起こした後、技術サポートチームは圧倒的な数の問い合わせを受けた。',
  'The researcher submitted a detailed query to the archives requesting access to declassified government documents from the Cold War era.',
  '研究者は冷戦時代の機密解除された政府文書へのアクセスを求め、アーカイブに詳細な問い合わせを提出した。'),
(789, 'frisk', '(人)のボディチェックをする', '/frɪsk/', 'フリスク',
  'Security personnel frisked every attendee at the entrance to the high-profile summit to ensure no prohibited items were brought inside.',
  '警備員は注目度の高いサミットの入り口ですべての参加者のボディチェックをし、禁止品の持ち込みがないことを確認した。',
  'The court ruled that officers had no reasonable grounds to frisk the suspect, rendering the evidence obtained inadmissible.',
  '裁判所は警察官が容疑者のボディチェックをする合理的な根拠がなかったと判断し、得られた証拠を不採用とした。'),
(790, 'secluded', '(場所が)人目につかない、人里離れた', '/sɪˈkluːdɪd/', 'シクルーデッド',
  'The author retreated to a secluded cabin in the mountains to complete her manuscript without the distractions of urban life.',
  'その作家は都会生活の雑念から離れて原稿を完成させるため、山中の人里離れた小屋にこもった。',
  'The secluded monastery, accessible only by a narrow mountain path, had served as a sanctuary for monks for over five centuries.',
  '狭い山道でしか行けない人里離れたその修道院は、500年以上にわたって修道士たちの聖域として機能してきた。'),
(791, 'infallible', '(人・判断などが)常に正しい、間違いのない', '/ɪnˈfæləbl/', 'インファラブル',
  'No diagnostic system is infallible, and physicians must exercise clinical judgment when interpreting automated test results.',
  'どんな診断システムも間違いのないものではなく、医師は自動化された検査結果を解釈する際に臨床的判断を行わなければならない。',
  'The CEO''s reputation as an infallible strategist was shattered when the company''s ambitious expansion plan ended in financial ruin.',
  '会社の野心的な拡大計画が財政破綻に終わったとき、間違いのない戦略家としてのCEOの評判は崩壊した。'),
(792, 'expletive', 'ののしり言葉', '/ˈɛksplətɪv/', 'エクスプレティヴ',
  'The live broadcast was abruptly cut when the interviewee let out a string of expletives in response to a provocative question.',
  'インタビュー対象者が挑発的な質問に対して一連のののしり言葉を発したとき、生放送は突然中断された。',
  'The leaked recording contained numerous expletives that severely damaged the politician''s carefully cultivated public image.',
  '流出した録音には多数のののしり言葉が含まれており、その政治家が慎重に築いてきた公的なイメージを深刻に傷つけた。'),
(793, 'clinch', '(不確定な状況・問題など)を確定的にする;~を獲得する、勝ち取る', '/klɪntʃ/', 'クリンチ',
  'The decisive victory in the final match clinched the championship title for the underdog team for the first time in their history.',
  '最終戦での決定的な勝利が、弱小チームに歴史上初の優勝タイトルをもたらした。',
  'After months of negotiations, the company clinched a multibillion-dollar defense contract that would secure thousands of jobs.',
  '数か月の交渉の末、同社は数十億ドルの防衛契約を獲得し、数千人の雇用を確保することになった。'),
(794, 'congenial', '(職場・場所・雰囲気などが)快適な、好みに合った', '/kənˈdʒiːniəl/', 'コンジーニアル',
  'The research institute fostered a congenial atmosphere that encouraged collaboration among scholars from diverse academic disciplines.',
  'その研究所は多様な学問分野の学者間の協力を促す快適な雰囲気を育んだ。',
  'She found the coastal town remarkably congenial and decided to relocate there permanently after just a brief visit.',
  '彼女はその海辺の町が非常に好みに合うと感じ、ほんの短い訪問の後に永住することを決めた。'),
(795, 'headway', '(仕事の)進捗、進展', '/ˈhɛdˌweɪ/', 'ヘッドウェイ',
  'Despite years of diplomatic efforts, negotiators have made little headway in resolving the territorial dispute between the two nations.',
  '何年にもわたる外交努力にもかかわらず、交渉者たちは二国間の領土紛争の解決にほとんど進展を見せていない。',
  'The research team finally made significant headway in developing a vaccine after identifying the virus''s unique protein structure.',
  'ウイルスの独特なタンパク質構造を特定した後、研究チームはついにワクチン開発に大きな進展を遂げた。'),
(796, 'complicity', '(犯罪などの)共謀、共犯', '/kəmˈplɪsəti/', 'コンプリシティ',
  'The executive was charged with complicity in the massive accounting fraud that had deceived shareholders for over a decade.',
  'その幹部は10年以上にわたって株主を欺いてきた大規模な会計詐欺の共謀で起訴された。',
  'Evidence of the government''s complicity in the cover-up emerged when classified documents were leaked to investigative journalists.',
  '機密文書が調査報道記者に漏洩したとき、政府の隠蔽工作への共謀の証拠が浮上した。'),
(797, 'memento', '記念品、思い出の品', '/məˈmɛntoʊ/', 'メメントウ',
  'The veteran kept a faded photograph as a memento of the comrades he had served with during the conflict.',
  'その退役軍人は紛争中に共に従軍した戦友の思い出の品として、色あせた写真を大切にしていた。',
  'Visitors to the historic site often purchase handcrafted mementos to commemorate their experience at the ancient ruins.',
  '史跡の訪問者はしばしば古代遺跡での体験を記念するために手作りの記念品を購入する。'),
(798, 'commensurate', '(報酬・責任などが)見合った、相応の', '/kəˈmɛnsərət/', 'コメンサレット',
  'The board argued that the CEO''s compensation package was commensurate with the extraordinary growth the company had achieved.',
  '取締役会は、CEOの報酬パッケージは会社が達成した非凡な成長に見合ったものだと主張した。',
  'Employees demanded salaries commensurate with their qualifications and the escalating cost of living in the metropolitan area.',
  '従業員たちは自分たちの資格と大都市圏での上昇する生活費に相応の給与を要求した。'),
(799, 'dormant', '活動停止中の、休止状態の', '/ˈdɔːrmənt/', 'ドーマント',
  'The volcano, which had been dormant for over three centuries, showed alarming signs of seismic activity that rattled nearby communities.',
  '3世紀以上休止状態にあった火山が、周辺のコミュニティを動揺させる不穏な地震活動の兆候を見せた。',
  'The legislation had remained dormant for decades before a landmark court ruling brought it back into the spotlight.',
  'その法律は画期的な裁判所の判決によって再び脚光を浴びるまで、何十年も休止状態にあった。'),
(800, 'haven', '避難所、安全な場所', '/ˈheɪvən/', 'ヘイヴン',
  'The coastal nation has long been regarded as a tax haven, attracting multinational corporations seeking to minimize their fiscal obligations.',
  'その沿岸国は長い間タックスヘイブンと見なされ、税負担を最小限に抑えようとする多国籍企業を引きつけてきた。',
  'The community center served as a haven for displaced families, providing shelter, food, and counseling in the aftermath of the disaster.',
  'そのコミュニティセンターは、災害の後、避難した家族に住居、食料、カウンセリングを提供する避難所として機能した。');
