-- words テーブル INSERT文 (No.801 ~ No.850)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(801, 'forgo', '(楽しみなど)を控える、我慢する', '/fɔːrˈɡoʊ/', 'フォーゴウ',
  'The executive decided to forgo his annual bonus in a gesture of solidarity with employees who had faced salary cuts.',
  'その幹部は、給与削減に直面した社員たちとの連帯の意志を示すため、年間賞与を控えることにした。',
  'Many patients forgo necessary medical treatment because they cannot afford the exorbitant costs of prescription drugs.',
  '多くの患者が処方薬の法外な費用を負担できないため、必要な治療を我慢している。'),
(802, 'rife', '(病気・うわさなどが)広まって;(よくないものが)あふれて', '/raɪf/', 'ライフ',
  'Corruption was rife throughout the government, with officials at every level implicated in the embezzlement scandal.',
  '汚職が政府全体に広まっており、あらゆる階層の役人が横領事件に関与していた。',
  'Speculation was rife that the company would announce a major restructuring following its disappointing quarterly earnings.',
  '期待外れの四半期決算を受け、同社が大規模なリストラを発表するという憶測が広まっていた。'),
(803, 'restraint', '自制、慎み;抑制、制約、制限', '/rɪˈstreɪnt/', 'リストレイント',
  'The diplomat exercised remarkable restraint despite the provocative remarks made by his counterpart during the negotiations.',
  'その外交官は、交渉中に相手方が挑発的な発言をしたにもかかわらず、見事な自制心を発揮した。',
  'Critics argue that insufficient regulatory restraint on the financial sector was a primary cause of the economic crisis.',
  '批評家たちは、金融部門に対する規制上の抑制が不十分だったことが経済危機の主な原因だと主張している。'),
(804, 'tentative', '(予定などが)仮の、暫定的な;自信なさげな、ためらいがちな', '/ˈtɛntətɪv/', 'テンタティヴ',
  'The two nations reached a tentative agreement on trade tariffs, though several contentious issues remained unresolved.',
  '両国は貿易関税に関する暫定的な合意に達したが、いくつかの争点は未解決のままだった。',
  'The new employee made a tentative suggestion during the meeting, clearly unsure of how her ideas would be received.',
  '新入社員は会議でためらいがちに提案をしたが、自分の考えがどう受け止められるか明らかに不安そうだった。'),
(805, 'stammer', '(人が)口ごもる、どもる;どもること', '/ˈstæmər/', 'スタマー',
  'The witness began to stammer under the relentless cross-examination, raising doubts about the veracity of his testimony.',
  '証人は容赦ない反対尋問の下で口ごもり始め、その証言の真実性に疑念が生じた。',
  'Despite his tendency to stammer when nervous, the young advocate delivered a compelling closing argument that swayed the jury.',
  '緊張するとどもる癖があるにもかかわらず、その若い弁護士は陪審員を動かす説得力のある最終弁論を行った。'),
(806, 'yardstick', '(判断・比較などの)基準、尺度', '/ˈjɑːrdstɪk/', 'ヤードスティック',
  'GDP has long been the primary yardstick for measuring a nation''s economic prosperity, but many economists now question its adequacy.',
  'GDPは長い間、国の経済的繁栄を測る主要な尺度であったが、多くの経済学者がその妥当性を疑問視している。',
  'Academic performance should not be the sole yardstick by which we evaluate the potential of young students.',
  '学業成績は、若い学生の可能性を評価する唯一の基準であるべきではない。'),
(807, 'rudimentary', '未発達の、初期段階の;基本的な', '/ˌruːdɪˈmɛntəri/', 'ルーディメンタリ',
  'The refugees were housed in rudimentary shelters that offered little protection from the harsh winter conditions.',
  '難民たちは厳しい冬の気候からほとんど身を守れない初歩的な避難所に収容された。',
  'Even a rudimentary understanding of genetics is sufficient to appreciate the enormity of recent breakthroughs in gene therapy.',
  '遺伝学の基本的な理解があるだけでも、遺伝子治療における最近の飛躍的進歩の重大さを認識するのに十分である。'),
(808, 'clichéd', '言い古された、陳腐な', '/klɪˈʃeɪd/', 'クリシェイド',
  'The film''s plot was so clichéd that critics unanimously panned it as an uninspired rehash of tired Hollywood formulas.',
  'その映画の筋書きはあまりに陳腐で、批評家たちは使い古されたハリウッドの公式の安易な焼き直しだと酷評した。',
  'While it may sound clichéd, perseverance truly is the single most important factor in achieving long-term professional success.',
  '言い古されたように聞こえるかもしれないが、忍耐力こそが長期的な職業上の成功を達成する上で最も重要な要素である。'),
(809, 'gust', '突風、一陣の風', '/ɡʌst/', 'ガスト',
  'A powerful gust of wind tore the scaffolding from the side of the building, sending debris crashing onto the street below.',
  '強い突風が建物の側面から足場を引きはがし、がれきが下の通りに落下した。',
  'The meteorological agency warned that gusts exceeding one hundred kilometers per hour were expected along the coastal regions.',
  '気象庁は、沿岸地域で時速100キロメートルを超える突風が予想されると警告した。'),
(810, 'redress', '(損害に対する)補償、賠償(金);(こと)を正す、償わせる', '/rɪˈdrɛs/', 'リドレス',
  'The indigenous community sought legal redress for the decades of environmental damage caused by industrial mining operations on their ancestral land.',
  '先住民コミュニティは、祖先の土地での産業採掘事業によって何十年にもわたって引き起こされた環境被害に対する法的な補償を求めた。',
  'The new legislation was introduced specifically to redress the systemic inequalities that had persisted in the education system for generations.',
  'その新しい法律は、教育制度に何世代にもわたって存続してきた構造的な不平等を正すために特別に導入された。'),
(811, 'curt', '(人・言葉・態度などが)素っ気ない、ぶっきらぼうな', '/kɜːrt/', 'カート',
  'The manager''s curt dismissal of the proposal offended the team members who had spent weeks preparing the presentation.',
  'マネージャーの素っ気ない提案の却下は、何週間もかけてプレゼンテーションを準備したチームメンバーの感情を害した。',
  'Her curt reply to the journalist''s question sparked a public relations controversy that dominated the news cycle for days.',
  '記者の質問に対する彼女のぶっきらぼうな返答は、何日も報道を席巻する広報上の論争を引き起こした。'),
(812, 'ensconce', '身を落ち着ける', '/ɪnˈskɒns/', 'インスコンス',
  'After a long and arduous journey, the traveler ensconced herself in the corner of the cozy inn, reluctant to venture out again.',
  '長く困難な旅の後、旅行者は居心地の良い宿の隅に身を落ち着け、再び外に出るのを渋った。',
  'The dictator had ensconced himself in a fortified compound, surrounded by loyal guards who would brook no dissent.',
  '独裁者は要塞化された施設に身を落ち着け、反対意見を一切許さない忠実な護衛に囲まれていた。'),
(813, 'revel', '大いに楽しむ、喜ぶ', '/ˈrɛvəl/', 'レヴェル',
  'The students reveled in their newfound freedom after the grueling examination period finally came to an end.',
  '学生たちは過酷な試験期間がついに終わり、新たに得た自由を大いに楽しんだ。',
  'The artist reveled in the critical acclaim that followed the unveiling of her controversial installation at the national gallery.',
  'その芸術家は、国立美術館での物議を醸すインスタレーションの公開後に続いた批評家の称賛を大いに喜んだ。'),
(814, 'premeditated', '前もって考えた、計画的な', '/prɪˈmɛdɪteɪtɪd/', 'プリメディテイティド',
  'The prosecution argued that the crime was premeditated, presenting evidence that the defendant had purchased the weapon weeks in advance.',
  '検察側は犯行が計画的であると主張し、被告が数週間前に凶器を購入していた証拠を提示した。',
  'The tribunal concluded that the atrocities were not spontaneous acts of violence but premeditated campaigns of systematic persecution.',
  '法廷は、その残虐行為が自然発生的な暴力行為ではなく、組織的迫害の計画的な活動であったと結論づけた。'),
(815, 'intermittently', '断続的に、途切れ途切れに', '/ˌɪntərˈmɪtəntli/', 'インターミテントリ',
  'The satellite signal was received only intermittently due to severe atmospheric interference caused by the solar storm.',
  '太陽嵐による深刻な大気干渉のため、衛星信号は断続的にしか受信できなかった。',
  'The factory has been operating only intermittently since the supply chain disruptions began earlier this year.',
  '今年初めにサプライチェーンの混乱が始まって以来、その工場は断続的にしか稼働していない。'),
(816, 'transitory', '一時的な、つかの間の', '/ˈtrænzɪtɔːri/', 'トランジトリ',
  'The economic boom proved to be transitory, as the market collapsed just eighteen months after reaching its peak.',
  '経済的好況は一時的なものであることが判明し、市場はピークに達してからわずか18か月で崩壊した。',
  'Philosophers have long contemplated the transitory nature of human existence and its implications for how we ought to live.',
  '哲学者たちは長い間、人間の存在のはかなさとそれが私たちの生き方にもたらす意味について思索してきた。'),
(817, 'imprudent', '軽率な、無分別な', '/ɪmˈpruːdənt/', 'インプルーデント',
  'The auditor concluded that the company''s imprudent investment strategy had exposed shareholders to unnecessary financial risk.',
  '監査人は、同社の軽率な投資戦略が株主を不必要な財務リスクにさらしたと結論づけた。',
  'It would be imprudent to proceed with the merger without first conducting a thorough due diligence investigation.',
  '徹底的なデューディリジェンス調査を先に行わずに合併を進めるのは無分別であろう。'),
(818, 'avail', '[avail oneself of ~]~を利用する', '/əˈveɪl/', 'アヴェイル',
  'Residents were encouraged to avail themselves of the free legal consultation services provided by the municipal government.',
  '住民は、市政府が提供する無料の法律相談サービスを利用するよう奨励された。',
  'Despite numerous attempts to negotiate a settlement, all diplomatic efforts were to no avail, and hostilities soon resumed.',
  '和解交渉の試みが幾度となくなされたにもかかわらず、すべての外交努力は無駄に終わり、まもなく敵対行為が再開された。'),
(819, 'wrest', '(支配権・主導権など)を力ずくで奪う;~をもぎ取る', '/rɛst/', 'レスト',
  'The opposition party managed to wrest control of the legislature from the ruling coalition in a landmark electoral victory.',
  '野党は画期的な選挙での勝利によって、与党連合から議会の支配権を力ずくで奪い取ることに成功した。',
  'After years of litigation, the family finally wrested the patent rights from the corporation that had unlawfully claimed ownership.',
  '何年にもわたる訴訟の末、その家族は不法に所有権を主張していた企業から特許権をもぎ取った。'),
(820, 'abet', '(人)をそそのかす、(犯罪)をほう助[教唆]する', '/əˈbɛt/', 'アベット',
  'The court found that the financial advisor had aided and abetted the fraudulent scheme by concealing illicit transactions.',
  '裁判所は、その財務顧問が不正な取引を隠蔽することで詐欺計画をほう助したと認定した。',
  'Anyone who knowingly abets the smuggling of contraband across international borders faces severe criminal penalties.',
  '国境を越えた密輸品の密輸を故意にほう助する者は、厳しい刑事罰に直面する。'),
(821, 'confound', '(人)を困惑[混乱]させる;(人など)の誤りを証明する', '/kənˈfaʊnd/', 'コンファウンド',
  'The experimental results confounded the researchers, as they contradicted every prediction made by the prevailing theoretical model.',
  '実験結果は、主流の理論モデルによるすべての予測に矛盾しており、研究者たちを困惑させた。',
  'The underdog team confounded the critics by defeating the reigning champions in a stunning upset at the world tournament.',
  '弱小チームは世界大会で衝撃的な番狂わせにより前年度チャンピオンを破り、批評家たちの誤りを証明した。'),
(822, 'intrinsic', '(価値・性質などが)固有の、本来備わっている', '/ɪnˈtrɪnzɪk/', 'イントリンジック',
  'The intrinsic value of a liberal arts education lies not in immediate employability but in the cultivation of critical thinking.',
  'リベラルアーツ教育の固有の価値は、すぐに就職できることではなく、批判的思考力の育成にある。',
  'Scientists have discovered that the intrinsic properties of this newly synthesized material make it ideal for superconductor applications.',
  '科学者たちは、この新たに合成された材料の本来備わっている特性が超伝導体への応用に理想的であることを発見した。'),
(823, 'oust', '(人)を追放する、失脚させる', '/aʊst/', 'アウスト',
  'The board of directors voted unanimously to oust the chief executive after a series of financial scandals came to light.',
  '一連の金融スキャンダルが明るみに出た後、取締役会は最高経営責任者を全会一致で解任した。',
  'The military coup ousted the democratically elected president, plunging the nation into a protracted period of political instability.',
  '軍事クーデターが民主的に選ばれた大統領を失脚させ、国を長期にわたる政治的不安定に陥れた。'),
(824, 'disparage', '(人・ものなど)を批判する、けなす', '/dɪˈspærɪdʒ/', 'ディスパリッジ',
  'The senator was widely condemned for publicly disparaging the contributions of frontline healthcare workers during the pandemic.',
  'その上院議員は、パンデミック中に最前線の医療従事者の貢献を公然とけなしたとして広く非難された。',
  'It is unprofessional to disparage a colleague''s work in front of clients, regardless of any personal disagreements you may have.',
  '個人的な意見の相違に関係なく、クライアントの前で同僚の仕事をけなすのは非専門的である。'),
(825, 'brandish', '(威嚇して)(武器など)を振り回す', '/ˈbrændɪʃ/', 'ブランディッシュ',
  'The assailant brandished a knife at the security guard before fleeing the premises through the emergency exit.',
  '襲撃者は非常口から施設を逃走する前に、警備員にナイフを振り回して見せた。',
  'Protesters brandished placards and banners as they marched through the capital demanding immediate governmental reform.',
  '抗議者たちは即座の政府改革を要求して首都を行進しながら、プラカードや横断幕を振りかざした。'),
(826, 'relapse', '(人が)病気を再発する;(悪事などに)再び陥る', '/rɪˈlæps/', 'リラプス',
  'The patient suffered a devastating relapse just weeks after being declared free of the aggressive form of leukemia.',
  '患者は、進行性白血病から解放されたと宣告されたわずか数週間後に壊滅的な再発に見舞われた。',
  'Without a robust support network, recovering addicts are significantly more likely to relapse into substance abuse.',
  '強固な支援ネットワークがなければ、回復中の依存症患者が薬物乱用に再び陥る可能性は大幅に高くなる。'),
(827, 'morsel', '(食べ物の)一口分、一切れ;少量、ほんの一かけら', '/ˈmɔːrsəl/', 'モーセル',
  'The starving refugees devoured every last morsel of food that the humanitarian aid workers distributed at the camp.',
  '飢えた難民たちは、人道支援活動家がキャンプで配布した食料の最後の一切れまですべて平らげた。',
  'The detective seized upon every morsel of evidence, no matter how insignificant it appeared, to build the prosecution''s case.',
  '刑事はどんなに些細に見えても、あらゆるわずかな証拠を捉えて検察側の立証を組み立てた。'),
(828, 'excavate', '(場所)を発掘する;(埋もれたもの)を掘り出す', '/ˈɛkskəveɪt/', 'エクスカヴェイト',
  'Archaeologists excavated the ancient burial site and unearthed artifacts dating back more than three thousand years.',
  '考古学者たちは古代の埋葬地を発掘し、3000年以上前にさかのぼる遺物を掘り出した。',
  'The construction crew was forced to halt operations when they began to excavate what appeared to be a medieval foundation.',
  '建設作業員は、中世の基礎と思われるものを掘り出し始めたとき、作業を中断せざるを得なかった。'),
(829, 'volatile', '(状況・気分などが)変わりやすい、不安定な', '/ˈvɒlətaɪl/', 'ヴォラタイル',
  'The volatile political situation in the region has deterred foreign investors from committing capital to major infrastructure projects.',
  'その地域の不安定な政治情勢は、外国の投資家が大規模なインフラプロジェクトに資本を投入することを躊躇させている。',
  'Cryptocurrency markets are notoriously volatile, with prices capable of fluctuating dramatically within a matter of hours.',
  '暗号通貨市場は変わりやすいことで悪名高く、価格は数時間のうちに劇的に変動する可能性がある。'),
(830, 'devious', '(人・行為などが)悪質な、狡猾な', '/ˈdiːviəs/', 'ディーヴィアス',
  'The investigation revealed a devious scheme to siphon public funds through a labyrinth of offshore shell companies.',
  '調査により、海外のペーパーカンパニーの迷路を通じて公的資金を吸い上げる狡猾な計略が明らかになった。',
  'The antagonist in the novel was portrayed as a devious manipulator who exploited the trust of everyone around him.',
  '小説の敵役は、周囲のあらゆる人の信頼を悪用する狡猾な操作者として描かれていた。'),
(831, 'tenet', '(集団・思想などの)主義、教義', '/ˈtɛnɪt/', 'テニット',
  'Freedom of expression is a fundamental tenet of democratic societies, enshrined in constitutions around the world.',
  '表現の自由は民主主義社会の基本的な主義であり、世界中の憲法に明記されている。',
  'The organization''s core tenets emphasize environmental stewardship and the sustainable utilization of natural resources.',
  'その組織の中核的な教義は、環境保全と天然資源の持続可能な利用を強調している。'),
(832, 'appease', '(人)をなだめる;(反発など)を鎮める', '/əˈpiːz/', 'アピーズ',
  'The government offered substantial economic concessions in an attempt to appease the disgruntled labor unions threatening a general strike.',
  '政府はゼネストを脅かす不満を抱いた労働組合をなだめるため、大幅な経済的譲歩を提示した。',
  'Historians often cite the policy of appeasement as a cautionary tale of how attempts to appease aggressors can embolden them further.',
  '歴史家たちは、侵略者をなだめようとする試みがかえって彼らを増長させる教訓として宥和政策をしばしば引用する。'),
(833, 'instigate', '(扇動して)(反乱・暴動など)を起こさせる', '/ˈɪnstɪɡeɪt/', 'インスティゲイト',
  'The deposed leader was accused of instigating a violent insurrection in a desperate bid to reclaim political power.',
  '追放された指導者は、政治的権力を取り戻すための必死の試みとして暴力的な反乱を起こさせたとして告発された。',
  'An internal inquiry found that the manager had instigated a campaign of harassment against employees who reported safety violations.',
  '内部調査により、そのマネージャーが安全違反を報告した従業員に対する嫌がらせ活動を扇動していたことが判明した。'),
(834, 'resonate', '(音が)鳴り響く、響きわたる;(作品などが)感銘を与える、響く', '/ˈrɛzəneɪt/', 'レゾネイト',
  'The keynote speaker''s impassioned plea for social justice resonated deeply with the audience of young activists and reformers.',
  '基調講演者の社会正義への情熱的な訴えは、若い活動家や改革者たちの聴衆に深く響いた。',
  'The haunting melody of the symphony resonated through the grand concert hall, leaving the audience in a state of profound contemplation.',
  '交響曲の忘れがたい旋律が壮大なコンサートホールに響き渡り、聴衆を深い瞑想の状態にさせた。'),
(835, 'obliterate', '~を跡形もなく破壊する', '/əˈblɪtəreɪt/', 'オブリテレイト',
  'The catastrophic tsunami obliterated entire coastal villages, leaving nothing but devastation in its wake.',
  '壊滅的な津波が沿岸の村々を跡形もなく破壊し、その後には荒廃だけが残った。',
  'The relentless bombing campaign obliterated the city''s historic district, erasing centuries of irreplaceable cultural heritage.',
  '容赦ない爆撃作戦が街の歴史地区を跡形もなく破壊し、何世紀にもわたるかけがえのない文化遺産を消し去った。'),
(836, 'jostle', '(人)を突き飛ばす、押しのける;争う、競う', '/ˈdʒɒsəl/', 'ジョスル',
  'Commuters jostled one another on the overcrowded platform as they attempted to board the already packed train.',
  '通勤客たちは、すでに満員の列車に乗り込もうとして混雑したホームで互いを押しのけた。',
  'Several multinational corporations are jostling for dominance in the rapidly expanding renewable energy market.',
  '複数の多国籍企業が急速に拡大する再生可能エネルギー市場での優位を争っている。'),
(837, 'hunch', '直感、予感、虫の知らせ', '/hʌntʃ/', 'ハンチ',
  'Acting on a hunch, the detective revisited the crime scene and discovered a crucial piece of evidence that had been overlooked.',
  '直感に従い、刑事は犯行現場を再訪し、見落とされていた重要な証拠を発見した。',
  'The venture capitalist had a hunch that the fledgling startup would revolutionize the industry, and her instinct proved remarkably prescient.',
  'そのベンチャーキャピタリストは、その新興スタートアップが業界に革命を起こすだろうという予感を持っており、彼女の直感は驚くほど先見の明があった。'),
(838, 'lament', '~を嘆く、悲しむ', '/ləˈmɛnt/', 'ラメント',
  'Environmentalists lament the irreversible destruction of pristine rainforests caused by unchecked commercial logging operations.',
  '環境保護活動家たちは、歯止めのない商業伐採によって引き起こされた手つかずの熱帯雨林の不可逆的な破壊を嘆いている。',
  'The renowned author lamented the decline of reading culture in an era increasingly dominated by digital entertainment.',
  '著名な作家は、デジタルエンターテインメントにますます支配される時代における読書文化の衰退を嘆いた。'),
(839, 'trample', '((希望・権利など)を)踏みにじる;~を踏みつける、踏みつぶす', '/ˈtræmpəl/', 'トランプル',
  'The authoritarian regime systematically trampled the civil liberties of its citizens under the guise of maintaining national security.',
  '権威主義体制は国家安全保障の維持を装って、市民の自由を組織的に踏みにじった。',
  'Several spectators were trampled in the ensuing panic when a false alarm triggered a mass evacuation of the stadium.',
  '誤報がスタジアムの大規模避難を引き起こした際、その後のパニックで数名の観客が踏みつけられた。'),
(840, 'squabble', '(つまらないことで)言い争う', '/ˈskwɒbəl/', 'スクウォブル',
  'The coalition partners squabbled incessantly over minor policy differences, ultimately undermining their ability to govern effectively.',
  '連立パートナーは些細な政策の違いをめぐって絶え間なく言い争い、最終的に効果的な統治能力を損なった。',
  'Rather than squabbling over the allocation of blame, the committee should focus on devising a constructive solution to the crisis.',
  '責任の所在をめぐって言い争うよりも、委員会は危機に対する建設的な解決策の考案に集中すべきである。'),
(841, 'resilient', '回復力がある、立ち直りが早い;弾力性のある', '/rɪˈzɪliənt/', 'リジリエント',
  'The nation''s economy proved remarkably resilient, recovering from the devastating financial crisis far more rapidly than analysts had predicted.',
  'その国の経済は驚くほど回復力があることが証明され、壊滅的な金融危機からアナリストの予測よりもはるかに早く回復した。',
  'Children raised in supportive environments tend to be more resilient when confronted with adversity later in life.',
  '支援的な環境で育った子供たちは、後の人生で逆境に直面した際、より立ち直りが早い傾向がある。'),
(842, 'void', '空虚、喪失感;真空;(契約などが)無効の', '/vɔɪd/', 'ヴォイド',
  'The sudden departure of the founding director left an enormous void in the organization that proved exceedingly difficult to fill.',
  '創設ディレクターの突然の退任は、組織に埋めるのが極めて困難な大きな空虚を残した。',
  'The court declared the contract null and void on the grounds that it had been signed under duress.',
  '裁判所は、その契約が強迫の下で署名されたことを理由に無効であると宣言した。'),
(843, 'innocuous', '(言動が)当たり障りのない、無難な', '/ɪˈnɒkjuəs/', 'イノキュアス',
  'What appeared to be an innocuous remark by the diplomat was later interpreted as a veiled threat by the opposing delegation.',
  '外交官による当たり障りのない発言に見えたものが、後に相手側の代表団によって暗黙の脅威として解釈された。',
  'The seemingly innocuous chemical compound was later found to have severe long-term carcinogenic effects on laboratory subjects.',
  '一見無害に見えたその化合物は、後に実験対象に深刻な長期的発がん作用があることが判明した。'),
(844, 'taunt', '(人)をあざける、嘲笑する', '/tɔːnt/', 'トーント',
  'The opposition taunted the prime minister relentlessly during the parliamentary debate, questioning his competence and credibility.',
  '野党は議会の討論中に首相を容赦なくあざけり、その能力と信頼性を疑問視した。',
  'The school implemented a strict anti-bullying policy after several students reported being taunted and ostracized by their peers.',
  '数名の生徒が仲間にあざけられ仲間外れにされていると報告した後、学校は厳格ないじめ防止方針を実施した。'),
(845, 'reverberate', '(音などが)反響する、鳴り響く;(出来事などが)影響する', '/rɪˈvɜːrbəreɪt/', 'リヴァーバレイト',
  'The thunderous applause reverberated through the auditorium as the acclaimed pianist concluded her magnificent performance.',
  '著名なピアニストが壮大な演奏を終えると、雷鳴のような拍手が講堂中に反響した。',
  'The economic repercussions of the trade embargo continue to reverberate throughout the region, affecting millions of livelihoods.',
  '貿易禁輸措置の経済的影響は地域全体に影響し続け、何百万人もの生活に影響を及ぼしている。'),
(846, 'illustrious', '(功績により)(人が)著名な、有名な;(業績などが)輝かしい', '/ɪˈlʌstriəs/', 'イラストリアス',
  'The university boasts an illustrious alumni network that includes Nobel laureates, heads of state, and pioneering scientists.',
  'その大学はノーベル賞受賞者、国家元首、先駆的な科学者を含む著名な卒業生ネットワークを誇っている。',
  'The general''s illustrious military career spanned four decades and encompassed some of the most consequential conflicts of the modern era.',
  'その将軍の輝かしい軍歴は40年にわたり、現代の最も重大な紛争のいくつかを含んでいた。'),
(847, 'verbose', '言葉数が多い、冗長な', '/vɜːrˈboʊs/', 'ヴァーボウス',
  'The professor''s verbose lectures often exceeded the allotted time, leaving students with little opportunity to ask questions.',
  'その教授の冗長な講義はしばしば割り当てられた時間を超過し、学生に質問する機会をほとんど与えなかった。',
  'Legal documents are notoriously verbose, often requiring specialized knowledge to decipher their dense and convoluted language.',
  '法的文書は冗長なことで悪名高く、その密で複雑な言語を解読するには専門知識がしばしば必要である。'),
(848, 'gallant', '勇敢な、堂々とした', '/ˈɡælənt/', 'ギャラント',
  'The gallant firefighters risked their own lives to rescue the family trapped on the upper floors of the burning building.',
  '勇敢な消防士たちは、燃え盛る建物の上階に閉じ込められた家族を救出するために自らの命を危険にさらした。',
  'Despite a gallant defensive effort, the outnumbered garrison was ultimately forced to surrender to the besieging army.',
  '勇敢な防御努力にもかかわらず、数で劣る守備隊は最終的に包囲軍に降伏せざるを得なかった。'),
(849, 'pulverize', '~を粉状にする、粉々にする', '/ˈpʌlvəraɪz/', 'パルヴァライズ',
  'The industrial machinery is capable of pulverizing enormous boulders into fine gravel suitable for road construction.',
  'その産業機械は巨大な岩石を道路建設に適した細かい砂利に粉砕することができる。',
  'The earthquake pulverized the concrete foundations of the high-rise buildings, rendering them structurally unsound and uninhabitable.',
  '地震が高層ビルのコンクリート基礎を粉々にし、構造的に不健全で居住不可能にした。'),
(850, 'forlorn', '(人が)孤独な、みじめな;(場所が)さびれた', '/fərˈlɔːrn/', 'フォーローン',
  'The forlorn child sat alone on the park bench, clutching a tattered stuffed animal and waiting for someone who would never come.',
  'その孤独な子供はぼろぼろのぬいぐるみを抱きしめて公園のベンチに一人で座り、決して来ない誰かを待っていた。',
  'The once-thriving mining town had become a forlorn ghost town, its abandoned buildings slowly succumbing to the ravages of time.',
  'かつて繁栄していたその鉱山町はさびれたゴーストタウンとなり、放棄された建物は時の荒廃にゆっくりと屈していた。');
