-- words テーブル INSERT文 (No.901 ~ No.950)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(901, 'irascible', '短気な、怒りっぽい', '/ɪˈræsəbl/', 'イラサブル',
  'The irascible professor was notorious for berating students who dared to ask questions he deemed trivial.',
  'その短気な教授は、くだらないと見なした質問をする学生を叱りつけることで悪名高かった。',
  'Despite his irascible temperament, the surgeon was widely regarded as the most skilled in the entire hospital.',
  '怒りっぽい気性にもかかわらず、その外科医は病院全体で最も腕の立つ医師として広く認められていた。'),
(902, 'rejuvenate', '(人)を若返らせる、~の元気を回復させる', '/rɪˈdʒuːvəneɪt/', 'リジューヴェネイト',
  'The government launched an ambitious initiative to rejuvenate the economically depressed region through infrastructure investment.',
  '政府はインフラ投資を通じて経済的に疲弊した地域を再活性化させる野心的な計画を開始した。',
  'A week-long retreat in the countryside rejuvenated the exhausted executives, who returned to work with renewed vigor.',
  '田舎での一週間の保養が疲弊した経営幹部たちを元気づけ、彼らは新たな活力を持って仕事に復帰した。'),
(903, 'glean', '(情報・知識など)を少しずつ収集する', '/ɡliːn/', 'グリーン',
  'The journalist managed to glean crucial information from confidential sources within the government.',
  'そのジャーナリストは政府内部の機密情報源から重要な情報を少しずつ収集することに成功した。',
  'Researchers gleaned valuable insights from the data collected over two decades of longitudinal studies.',
  '研究者たちは20年間にわたる縦断的研究で集められたデータから貴重な知見を収集した。'),
(904, 'emanate', '(光・におい・感情など)を発する、発散する;(光・音・におい・考え・うわさなどが)生じる、広まる', '/ˈɛməneɪt/', 'エマネイト',
  'A pungent odor emanated from the abandoned factory, prompting residents to file complaints with the local authorities.',
  '放置された工場から刺激臭が発せられ、住民たちは地元の当局に苦情を申し立てた。',
  'The confidence that emanated from the young diplomat impressed even the most seasoned negotiators at the summit.',
  '若い外交官から発せられる自信は、サミットの最も経験豊かな交渉者たちさえも感嘆させた。'),
(905, 'rectify', '(問題・状況・誤りなど)を正す、修正する', '/ˈrɛktɪfaɪ/', 'レクティファイ',
  'The company pledged to rectify the accounting errors that had led to the misstatement of quarterly profits.',
  'その会社は四半期利益の誤表示につながった会計上の誤りを修正することを約束した。',
  'Unless the government acts swiftly to rectify the systemic flaws in the healthcare system, the crisis will only deepen.',
  '政府が医療制度の構造的欠陥を迅速に正さない限り、危機はさらに深刻化するだろう。'),
(906, 'garnish', '(料理)に付け合わせを添える;(料理の)付け合わせ', '/ˈɡɑːrnɪʃ/', 'ガーニッシュ',
  'The chef garnished the exquisite dish with edible flowers and a drizzle of truffle oil before serving it to the guests.',
  'シェフは客に提供する前に、食用花とトリュフオイルを少量かけてその絶品料理に付け合わせを添えた。',
  'A simple garnish of fresh herbs can elevate an otherwise mundane meal into something truly memorable.',
  '新鮮なハーブのシンプルな付け合わせが、平凡な食事を本当に印象的なものに変えることがある。'),
(907, 'insular', '偏狭な、島国根性の;島の、島国の', '/ˈɪnsələr/', 'インシュラー',
  'The committee''s insular approach to policymaking ignored the perspectives of international stakeholders entirely.',
  '委員会の偏狭な政策立案は、国際的な利害関係者の視点を完全に無視していた。',
  'Growing up in an insular community left him ill-prepared for the cultural diversity he encountered at university.',
  '偏狭な地域社会で育ったことで、彼は大学で遭遇する文化的多様性に対する準備が不十分であった。'),
(908, 'extricate', '~を(難局・身動きできない場所から)救い出す、脱出させる', '/ˈɛkstrɪkeɪt/', 'エクストリケイト',
  'The firefighters worked tirelessly to extricate the survivors trapped beneath the rubble of the collapsed building.',
  '消防士たちは倒壊した建物の瓦礫の下に閉じ込められた生存者を救い出すために懸命に作業した。',
  'The diplomat struggled to extricate his country from the complex web of alliances that threatened to drag it into war.',
  'その外交官は、自国を戦争に引きずり込みかねない複雑な同盟関係の網から脱出させるのに苦心した。'),
(909, 'recant', '(自説・前言など)を(正式に)撤回する', '/rɪˈkænt/', 'リカント',
  'Under immense political pressure, the scientist was forced to recant his controversial findings on climate change.',
  '多大な政治的圧力のもと、その科学者は気候変動に関する物議を醸した研究結果を撤回せざるを得なかった。',
  'The witness recanted her earlier testimony, claiming that she had been coerced into making false statements.',
  '証人は以前の証言を撤回し、虚偽の陳述を強要されたと主張した。'),
(910, 'dreary', '陰うつな、物寂しい;つまらない、退屈な', '/ˈdrɪri/', 'ドリアリー',
  'The dreary winter landscape, devoid of color and life, mirrored the protagonist''s sense of desolation in the novel.',
  '色も生命もない陰うつな冬の風景は、小説の主人公の荒涼とした心情を映し出していた。',
  'Workers endured dreary conditions in the factory, performing monotonous tasks for twelve hours a day.',
  '労働者たちは工場の陰うつな環境に耐え、一日12時間単調な作業を行っていた。'),
(911, 'morose', '不機嫌な、むっつりした', '/məˈroʊs/', 'モロウス',
  'After losing the election by a narrow margin, the candidate became increasingly morose and withdrew from public life.',
  '僅差で選挙に敗れた後、その候補者はますます不機嫌になり、公の場から身を引いた。',
  'The morose expression on the prisoner''s face revealed the depth of his despair after years of solitary confinement.',
  '囚人のむっつりとした表情は、長年の独房生活の後の絶望の深さを物語っていた。'),
(912, 'trite', '(表現・考えなどが)古くさい、陳腐な', '/traɪt/', 'トライト',
  'The literary critic dismissed the novel as trite, arguing that its themes had been explored far more effectively by earlier authors.',
  '文芸評論家はその小説を陳腐だと切り捨て、そのテーマは以前の作家たちによってはるかに効果的に探究されていると主張した。',
  'His speech was filled with trite platitudes that failed to inspire the audience or address the pressing issues at hand.',
  '彼の演説は陳腐な決まり文句で満ちており、聴衆を鼓舞することも目前の差し迫った問題に対処することもできなかった。'),
(913, 'ornate', '(派手に)飾り立てた;凝りすぎた', '/ɔːrˈneɪt/', 'オーネイト',
  'The ornate ceiling of the cathedral, adorned with intricate frescoes, left visitors gazing upward in silent admiration.',
  '精巧なフレスコ画で飾られた大聖堂の装飾的な天井は、訪問者たちを静かな感嘆のうちに見上げさせた。',
  'Critics argued that the author''s ornate prose style, while impressive, ultimately detracted from the clarity of the narrative.',
  '批評家たちは、その作家の凝りすぎた散文体は印象的ではあるが、結局は物語の明瞭さを損なっていると主張した。'),
(914, 'decrepit', '老衰した、老朽化した', '/dɪˈkrɛpɪt/', 'ディクレピット',
  'The decrepit infrastructure of the aging city posed a serious threat to public safety and demanded immediate renovation.',
  'その老朽化した都市のインフラは公共の安全に深刻な脅威をもたらし、早急な改修を必要としていた。',
  'The once-grand mansion had become so decrepit that the cost of restoration far exceeded the property''s market value.',
  'かつて壮麗だった邸宅はあまりにも老朽化し、修復費用が不動産の市場価値をはるかに上回っていた。'),
(915, 'impalpable', '感知できない、触っても感じられない;容易に理解できない', '/ɪmˈpælpəbl/', 'インパルパブル',
  'The impalpable tension in the negotiation room was evident only in the delegates'' carefully measured words and rigid postures.',
  '交渉室の感知しにくい緊張感は、代表団の慎重に計算された言葉と硬い姿勢にのみ表れていた。',
  'The philosopher grappled with the impalpable nature of consciousness, a subject that has eluded definitive explanation for centuries.',
  'その哲学者は意識の感知できない性質と格闘した。それは何世紀にもわたって決定的な説明を逃れてきた主題である。'),
(916, 'sham', '偽物、見せかけ、いんちき', '/ʃæm/', 'シャム',
  'The investigation revealed that the charity was nothing more than a sham designed to funnel donations into the founder''s personal accounts.',
  '調査により、その慈善団体は寄付金を創設者の個人口座に流し込むために作られた見せかけに過ぎないことが判明した。',
  'The opposition denounced the election as a sham, citing widespread irregularities and voter intimidation throughout the country.',
  '野党は全国的な不正や有権者への脅迫を挙げ、その選挙をいんちきだと非難した。'),
(917, 'prevaricate', '言葉を濁す、はぐらかす', '/prɪˈværɪkeɪt/', 'プリヴァリケイト',
  'The CEO continued to prevaricate when questioned about the company''s involvement in the environmental scandal.',
  '環境スキャンダルへの会社の関与について質問された際、CEOは言葉を濁し続けた。',
  'Politicians who prevaricate on critical issues inevitably lose the trust of the electorate.',
  '重要な問題ではぐらかす政治家は、必然的に有権者の信頼を失う。'),
(918, 'renunciation', '(信念・権利などの)放棄、断念', '/rɪˌnʌnsiˈeɪʃən/', 'リナンシエイション',
  'The prince''s renunciation of his claim to the throne sent shockwaves through the royal court and the nation.',
  '王子の王位継承権の放棄は、宮廷と国全体に衝撃を与えた。',
  'The treaty required the complete renunciation of nuclear weapons by all signatory nations within a decade.',
  'その条約は、すべての署名国に10年以内の核兵器の完全放棄を求めた。'),
(919, 'sluggish', '(動きが)鈍い、緩慢な;(経済などが)停滞した', '/ˈslʌɡɪʃ/', 'スラギッシュ',
  'The sluggish pace of economic recovery has prompted the central bank to consider further monetary easing measures.',
  '経済回復の鈍いペースにより、中央銀行はさらなる金融緩和策の検討を迫られている。',
  'After the heavy meal, the participants felt sluggish and struggled to maintain their concentration during the afternoon session.',
  '重い食事の後、参加者たちは鈍い感じがし、午後のセッション中に集中力を維持するのに苦労した。'),
(920, 'regress', '(以前の悪い状態に)後退する、逆戻りする', '/rɪˈɡrɛs/', 'リグレス',
  'Without sustained international support, the war-torn nation risks regressing into the chaos and instability of previous decades.',
  '持続的な国際支援がなければ、その戦争で荒廃した国は過去数十年の混乱と不安定な状態に逆戻りする危険がある。',
  'The patient''s condition regressed sharply after the experimental treatment was discontinued.',
  '実験的な治療が中止された後、患者の状態は急激に後退した。'),
(921, 'superfluous', '余分な、過剰な', '/suːˈpɜːrfluəs/', 'スーパーフルアス',
  'The editor removed several superfluous paragraphs that added nothing of substance to the already lengthy manuscript.',
  '編集者は、すでに長い原稿に実質的な内容を何も加えていないいくつかの余分な段落を削除した。',
  'In an era of automation, many workers fear that their skills will become superfluous as machines take over their roles.',
  '自動化の時代において、多くの労働者は機械が自分たちの役割を引き継ぐにつれて自分の技能が余分になることを恐れている。'),
(922, 'enthrall', '(人)を魅了する、夢中にさせる', '/ɪnˈθrɔːl/', 'インスロール',
  'The virtuoso pianist enthralled the audience with a breathtaking rendition of Rachmaninoff''s Third Concerto.',
  'その名ピアニストはラフマニノフの第3協奏曲の息を呑むような演奏で聴衆を魅了した。',
  'The documentary enthralled viewers worldwide, shedding light on the previously unknown customs of the remote indigenous tribe.',
  'そのドキュメンタリーは世界中の視聴者を魅了し、遠隔地の先住民族のこれまで知られていなかった慣習に光を当てた。'),
(923, 'perforation', '切り取り線、ミシン目', '/ˌpɜːrfəˈreɪʃən/', 'パーフォレイション',
  'The perforations along the edge of the stamps allowed them to be separated easily without the need for scissors.',
  '切手の縁に沿ったミシン目により、はさみを使わなくても簡単に切り離すことができた。',
  'The surgeon discovered a perforation in the patient''s intestinal wall, necessitating an emergency operation.',
  '外科医は患者の腸壁に穿孔を発見し、緊急手術が必要となった。'),
(924, 'debase', '~の価値[品質]を落とす', '/dɪˈbeɪs/', 'ディベイス',
  'Critics accused the network of debasing journalistic standards by prioritizing sensationalism over factual reporting.',
  '批評家たちは、事実報道よりもセンセーショナリズムを優先することでジャーナリズムの基準を低下させていると放送局を非難した。',
  'The prolonged period of quantitative easing has effectively debased the currency, eroding the purchasing power of ordinary citizens.',
  '長期にわたる量的緩和は事実上通貨の価値を下げ、一般市民の購買力を侵食した。'),
(925, 'vestige', '痕跡、名残り', '/ˈvɛstɪdʒ/', 'ヴェスティジ',
  'The ruins are the last vestige of a once-flourishing civilization that dominated the region for centuries.',
  'その遺跡は、何世紀にもわたってこの地域を支配したかつて繁栄した文明の最後の痕跡である。',
  'Not a vestige of the original forest remains after decades of relentless logging and urban expansion.',
  '数十年にわたる容赦ない伐採と都市拡大の後、元の森林の痕跡は一切残っていない。'),
(926, 'proviso', '(条約・契約などの)ただし書き、条件', '/prəˈvaɪzoʊ/', 'プロヴァイゾウ',
  'The agreement was signed with the proviso that both parties would submit to independent arbitration in the event of a dispute.',
  'その協定は、紛争が生じた場合に両当事者が独立した仲裁に従うという条件付きで署名された。',
  'She accepted the job offer with the proviso that she could work remotely at least three days a week.',
  '彼女は週に少なくとも3日はリモートワークができるという条件でその採用通知を受け入れた。'),
(927, 'remission', '(病気・症状などの)一時的軽減、緩和;(負債などの)免除', '/rɪˈmɪʃən/', 'リミッション',
  'After months of aggressive chemotherapy, the oncologist confirmed that the patient''s cancer was in complete remission.',
  '数か月にわたる強力な化学療法の後、腫瘍専門医は患者のがんが完全に緩解していることを確認した。',
  'The government announced a remission of tax penalties for small businesses that had been adversely affected by the pandemic.',
  '政府はパンデミックによって悪影響を受けた中小企業に対する税の罰則の免除を発表した。'),
(928, 'foment', '(混乱・暴動など)を助長する、扇動する', '/foʊˈmɛnt/', 'フォメント',
  'The propaganda broadcast was specifically designed to foment unrest among the already discontented populace.',
  'そのプロパガンダ放送は、すでに不満を抱いている大衆の間に混乱を扇動するために特別に企画されたものだった。',
  'Authorities accused foreign agents of attempting to foment a rebellion by distributing inflammatory pamphlets in border towns.',
  '当局は外国のエージェントが国境の町で扇動的なパンフレットを配布し、反乱を助長しようとしていると非難した。'),
(929, 'travesty', 'まがいもの、茶番', '/ˈtrævəsti/', 'トラヴェスティ',
  'Human rights organizations condemned the trial as a travesty of justice, noting the absence of legal representation for the accused.',
  '人権団体は、被告人に弁護人がいないことを指摘し、その裁判を正義の茶番だと非難した。',
  'The biopic was widely regarded as a travesty, distorting the historical figure''s legacy beyond recognition.',
  'その伝記映画は広くまがいものと見なされ、歴史上の人物の功績を認識できないほどに歪曲していた。'),
(930, 'procrastinate', '(やるべきことを)先延ばしにする', '/proʊˈkræstɪneɪt/', 'プロクラスティネイト',
  'Students who habitually procrastinate often find themselves overwhelmed by the sheer volume of work as deadlines approach.',
  '習慣的に先延ばしにする学生は、締め切りが近づくにつれて膨大な量の課題に圧倒されることが多い。',
  'The administration''s tendency to procrastinate on infrastructure repairs ultimately resulted in a catastrophic bridge collapse.',
  'インフラ修繕を先延ばしにする行政の傾向が、最終的に壊滅的な橋の崩落を引き起こした。'),
(931, 'nebulous', '漠然とした、あいまいな', '/ˈnɛbjələs/', 'ネビュラス',
  'The company''s nebulous mission statement failed to provide employees with a clear sense of direction or purpose.',
  'その会社の漠然とした使命宣言は、従業員に明確な方向性や目的意識を提供できなかった。',
  'The boundary between artistic expression and political dissent remains nebulous in many authoritarian regimes.',
  '芸術的表現と政治的異議申し立ての境界は、多くの権威主義体制において依然として曖昧である。'),
(932, 'clump', '群れ、塊;群れをなす、かたまる;どしんどしん歩く', '/klʌmp/', 'クランプ',
  'A clump of ancient oak trees at the edge of the property provided a natural windbreak for the farmhouse.',
  '敷地の端にある古いオークの木の群れが、農家の家に自然の防風林を提供していた。',
  'The children clumped together in the hallway, whispering excitedly about the surprise announcement from the headmaster.',
  '子供たちは廊下に群がり、校長からのサプライズ発表について興奮してひそひそ話をしていた。'),
(933, 'tally', '(支出などの)記録、勘定;(競技の)得点;~を計算する、集計する', '/ˈtæli/', 'タリー',
  'The final tally of votes confirmed that the incumbent had lost the election by an unexpectedly large margin.',
  '最終的な得票の集計により、現職が予想外の大差で選挙に敗れたことが確認された。',
  'Auditors were brought in to tally the company''s expenditures after discrepancies were found in the quarterly financial report.',
  '四半期財務報告書に不一致が見つかった後、会社の支出を集計するために監査人が招集された。'),
(934, 'saturate', '~を濡らす、浸す', '/ˈsætʃəreɪt/', 'サチュレイト',
  'The unprecedented rainfall saturated the soil to such an extent that landslides became an imminent threat across the region.',
  '前例のない降雨量が土壌を極度に浸し、地滑りがその地域全体で差し迫った脅威となった。',
  'The market has become so saturated with competing products that new entrants struggle to gain a foothold.',
  '市場は競合製品で飽和状態になり、新規参入者は足場を築くのに苦労している。'),
(935, 'rendition', '(絵画・音楽などによる)表現、描写、演奏', '/rɛnˈdɪʃən/', 'レンディション',
  'Her haunting rendition of the national anthem at the memorial ceremony moved the entire audience to tears.',
  '追悼式典での彼女の心に残る国歌の演奏は、聴衆全体を涙させた。',
  'The artist''s modern rendition of the classical masterpiece sparked a heated debate among art critics.',
  'その芸術家による古典的名作の現代的な表現は、美術評論家の間で白熱した議論を巻き起こした。'),
(936, 'pensive', '(人・表情などが)もの思いに沈んだ', '/ˈpɛnsɪv/', 'ペンシヴ',
  'The pensive expression on the diplomat''s face suggested that the negotiations had taken an unexpectedly difficult turn.',
  '外交官のもの思いに沈んだ表情は、交渉が予想外に困難な展開を迎えたことを示唆していた。',
  'She sat by the window in a pensive mood, contemplating the implications of the life-altering decision she was about to make.',
  '彼女はもの思いに沈んだ気分で窓辺に座り、これからしようとしている人生を変える決断の意味を熟考していた。'),
(937, 'charade', '見せかけ、(見え透いた)うその芝居', '/ʃəˈreɪd/', 'シャレイド',
  'The peace talks were nothing but a charade, as neither side had any genuine intention of reaching a compromise.',
  'その和平交渉はまったくの見せかけに過ぎず、どちらの側も妥協に達する真の意図はなかった。',
  'The employees saw through the charade of the so-called restructuring plan, which was merely a pretext for mass layoffs.',
  '従業員たちは、いわゆるリストラ計画の見せかけを見抜いた。それは大量解雇の口実に過ぎなかった。'),
(938, 'caricature', '風刺画;~を風刺的に描く', '/ˈkærɪkətʃʊr/', 'キャリカチュア',
  'The editorial caricature depicting the prime minister as a puppet provoked outrage among government supporters.',
  '首相を操り人形として描いた社説の風刺画は、政府支持者の間に怒りを引き起こした。',
  'The novelist was accused of caricaturing an entire ethnic group through the use of crude and offensive stereotypes.',
  'その小説家は、粗野で不快な固定観念を用いて民族全体を風刺的に描いたとして非難された。'),
(939, 'entangle', '~をもつれさせる、絡ませる', '/ɪnˈtæŋɡl/', 'インタングル',
  'The corporation became entangled in a web of lawsuits after whistleblowers exposed its fraudulent accounting practices.',
  '内部告発者が不正な会計慣行を暴露した後、その企業は訴訟の網に絡め取られた。',
  'Marine biologists warned that discarded fishing nets continue to entangle and endanger countless species of sea life.',
  '海洋生物学者は、廃棄された漁網が引き続き無数の海洋生物種を絡め取り、危険にさらしていると警告した。'),
(940, 'piety', '敬虔さ、信仰(心)', '/ˈpaɪəti/', 'パイエティ',
  'The monarch''s conspicuous piety was regarded by some historians as a calculated political strategy rather than genuine devotion.',
  'その君主の際立った敬虔さは、一部の歴史家によって真の献身ではなく計算された政治的戦略と見なされた。',
  'In medieval Europe, acts of piety such as pilgrimages and charitable donations were believed to secure divine favor.',
  '中世ヨーロッパでは、巡礼や慈善寄付といった敬虔な行為が神の恩寵を確保すると信じられていた。'),
(941, 'babble', 'まくしたてる', '/ˈbæbl/', 'バブル',
  'The nervous witness began to babble incoherently under the relentless cross-examination by the defense attorney.',
  '緊張した証人は、弁護士の容赦ない反対尋問のもとで支離滅裂にまくしたて始めた。',
  'The toddler babbled happily in her crib, producing sounds that her parents eagerly interpreted as first words.',
  '幼児はベビーベッドの中で楽しそうにまくしたて、両親はその音を最初の言葉だと熱心に解釈した。'),
(942, 'propel', '~を推進する、前進させる;(人)を駆り立てる', '/prəˈpɛl/', 'プロペル',
  'The breakthrough in renewable energy technology could propel the nation to the forefront of the global green economy.',
  '再生可能エネルギー技術の画期的な進歩は、その国を世界的なグリーン経済の最前線に推進する可能性がある。',
  'A deep sense of injustice propelled the young activist to devote her life to championing human rights.',
  '深い不正義の感覚が若い活動家を駆り立て、人権擁護に人生を捧げさせた。'),
(943, 'vanquish', '(敵・相手)を破る、負かす', '/ˈvæŋkwɪʃ/', 'ヴァンクウィッシュ',
  'The underdog team vanquished the reigning champions in a stunning upset that captivated sports fans around the world.',
  '劣勢と見られていたチームが、世界中のスポーツファンを魅了する驚きの番狂わせで王者を破った。',
  'It took decades of sustained diplomatic effort to vanquish the deep-seated mistrust between the two neighboring nations.',
  '二つの隣国間の根深い不信感を克服するには、数十年にわたる持続的な外交努力を要した。'),
(944, 'revoke', '(免許・法律など)を無効にする、廃止する', '/rɪˈvoʊk/', 'リヴォウク',
  'The regulatory authority threatened to revoke the pharmaceutical company''s license after repeated violations of safety protocols.',
  '規制当局は、安全手順の度重なる違反の後、その製薬会社の免許を取り消すと警告した。',
  'The Supreme Court''s decision to revoke the longstanding precedent sent ripples of uncertainty through the legal community.',
  '最高裁判所の長年の判例を無効にする決定は、法曹界に不確実性の波紋を広げた。'),
(945, 'precinct', '行政区、選挙区', '/ˈpriːsɪŋkt/', 'プリーシンクト',
  'Voter turnout in the urban precincts far exceeded expectations, ultimately tipping the balance in favor of the challenger.',
  '都市部の選挙区での投票率は予想をはるかに上回り、最終的に挑戦者に有利な方向に均衡を傾けた。',
  'The newly established pedestrian precinct in the city center has revitalized local businesses and attracted tourists.',
  '市中心部に新設された歩行者専用区域は地元の商業を活性化させ、観光客を引き付けた。'),
(946, 'inaugurate', '(人)を就任させる;(新事業など)を発足させる;~の落成式を行う', '/ɪˈnɔːɡjəreɪt/', 'イノーギュレイト',
  'The president-elect will be inaugurated in a ceremony attended by dignitaries from over fifty nations.',
  '次期大統領は50か国以上の要人が出席する式典で就任する。',
  'The mayor inaugurated the state-of-the-art research facility, hailing it as a milestone in the city''s commitment to innovation.',
  '市長は最新鋭の研究施設の落成式を行い、それをイノベーションへの市の取り組みにおける画期的な出来事として称えた。'),
(947, 'insipid', '無味乾燥な、面白くない;(食品が)味のない、おいしくない', '/ɪnˈsɪpɪd/', 'インシピッド',
  'The film received scathing reviews, with critics describing the dialogue as insipid and the plot as utterly predictable.',
  'その映画は酷評を受け、批評家たちはセリフを無味乾燥で、プロットを完全に予測可能だと評した。',
  'The once-celebrated restaurant now serves insipid dishes that bear no resemblance to the culinary masterpieces of its heyday.',
  'かつて名声を博したそのレストランは今や味気ない料理を出しており、全盛期の料理の傑作とは似ても似つかない。'),
(948, 'indignant', '(人・表情などが)憤慨した、怒った', '/ɪnˈdɪɡnənt/', 'インディグナント',
  'The indignant residents staged a massive protest after the council approved the construction of a waste incinerator in their neighborhood.',
  '市議会が近隣にごみ焼却施設の建設を承認した後、憤慨した住民たちは大規模な抗議活動を行った。',
  'She wrote an indignant letter to the editor, denouncing the newspaper''s biased coverage of the labor dispute.',
  '彼女は編集者に憤慨した手紙を書き、労働争議に関する新聞の偏った報道を非難した。'),
(949, 'premonition', '(悪い)予感、虫の知らせ', '/ˌprɛməˈnɪʃən/', 'プレモニション',
  'She had an inexplicable premonition that something terrible was about to happen, which compelled her to cancel the trip.',
  '彼女は何か恐ろしいことが起こりそうだという説明しがたい予感があり、旅行をキャンセルせざるを得なかった。',
  'The captain''s premonition of an impending storm proved accurate, as violent gales struck the vessel mere hours later.',
  '嵐が差し迫っているという船長の予感は的中し、わずか数時間後に激しい暴風が船を襲った。'),
(950, 'dexterity', '(手先の)器用さ;利口さ、抜け目なさ', '/dɛkˈstɛrəti/', 'デクステリティ',
  'The surgeon''s remarkable dexterity allowed her to perform the intricate microsurgery with a precision that astonished her colleagues.',
  'その外科医の卓越した手先の器用さにより、同僚を驚嘆させるほどの精度で精密な顕微鏡手術を行うことができた。',
  'The diplomat''s political dexterity enabled him to navigate the complex negotiations without alienating any of the participating nations.',
  'その外交官の政治的な抜け目なさにより、参加国のいずれも疎外することなく複雑な交渉を乗り切ることができた。');
