INSERT INTO passages (id, title, topic, word_range, content, content_ja) VALUES (73, 'Invasive Species and the Unraveling of Native Ecosystems', '生物', '1~700',
'When the brown tree snake was inadvertently introduced to Guam in the late 1940s, likely as a stowaway in military cargo, few could have apprehended the ecological catastrophe that would ensue. Within decades, this relentless nocturnal predator had driven ten of the island''s twelve native forest bird species to extinction, decimated populations of native lizards and small mammals, and triggered a cascade of secondary effects—including an explosion in spider populations, freed from avian predation—that fundamentally transformed the island''s ecosystem. The Guam disaster, far from being an isolated fiasco, typifies a global pattern: the introduction of non-native species into ecosystems where they face no natural adversaries has become one of the most destructive and least tractable environmental crises of the modern era, inflicting damages estimated at over 400 billion dollars annually worldwide.

The pathways through which invasive species infiltrate new habitats are as varied as they are difficult to cordon off. International shipping remains the predominant vector: ballast water discharged by cargo vessels transports an estimated 7,000 species across oceanic boundaries every day, while organisms attach themselves to hull surfaces and scamper ashore when ships dock. The global pet trade constitutes another major conduit; the Burmese python, now endemic to the Florida Everglades, was almost certainly released or escaped from private collections. Agricultural imports, too, carry stowaways—insects, fungi, and plant pathogens that evade quarantine inspections and establish themselves in hospitable new terrain. Once an invasive species gains a foothold, eradication becomes exponentially more arduous, as reproductive rates typically outpace any realistic containment effort. The Asian carp, introduced to the United States in the 1970s to control algae in aquaculture ponds, subsequently escaped into the Mississippi River system and has been on a rampage ever since, outcompeting native fish for food and threatening to breach the electric barriers that constitute the last line of defense for the Great Lakes ecosystem.

The ecological mechanisms by which invasive species wreak havoc are multiple and often synergistic. Direct predation—as exemplified by the brown tree snake—is the most conspicuous, but competition for resources can be equally devastating. In the Great Lakes, the zebra mussel, which arrived in ballast water from the Caspian Sea in the late 1980s, has created a glut of filtered water so clear that sunlight now penetrates to depths previously shrouded in turbidity, fundamentally altering the aquatic food web and enabling toxic algal blooms that afflict municipal water supplies. Invasive plants, meanwhile, can transform entire landscapes: kudzu, the "vine that ate the South," smothers native vegetation by growing at rates exceeding thirty centimeters per day during peak season, while in Australia, the prickly pear cactus once infested over 25 million hectares before a biological control agent—the Cactoblastis moth—was introduced to [BLANK]. Perhaps most insidious is the role invasive species play in disease transmission: the Asian tiger mosquito, now established on every continent except Antarctica, serves as a vector for dengue, chikungunya, and Zika viruses, imposing a public health burden that extends far beyond the ecological sphere.

Efforts to combat invasive species have historically oscillated between two broad strategies: prevention and control. Prevention—intercepting organisms before they establish themselves—is by far the more cost-effective approach, yet it demands a level of international coordination and protocol enforcement that has proven difficult to sustain. New Zealand, widely regarded as the global leader in biosecurity, operates one of the most stringent border inspection regimes in the world; arriving passengers are routinely accosted by biosecurity officers and sniffer dogs, and undeclared biological material is promptly confiscated. Even so, new incursions occur with dispiriting regularity. Once prevention fails, control measures range from chemical treatments and physical removal to the deployment of biological control agents—natural predators or pathogens imported to suppress the invader. Such interventions, however, carry their own risks: the cane toad, introduced to Australia in 1935 to control beetle infestations in sugarcane fields, itself became one of the continent''s most destructive invasive species, a cautionary tale that has made authorities squeamish about sanctioning further biological introductions without exhaustive risk assessment.

The frontier of invasive species management now lies in genetic technologies that were arcane only a decade ago. Gene drives—engineered genetic elements that spread through populations at rates exceeding normal inheritance—offer the tantalizing prospect of suppressing or even eliminating invasive species without the collateral damage associated with chemical or biological methods. Researchers at institutions including the Commonwealth Scientific and Industrial Research Organisation in Australia are actively exploring gene drives as a tool for controlling invasive rodents on islands, where conventional eradication methods have often botched the job or proved prohibitively expensive. The ethical and ecological implications of releasing gene-drive organisms into the wild, however, have provoked turbulent debate. Critics warn that engineered genes could jump to non-target species with unforeseeable consequences, while adherents argue that the alternative—watching helplessly as invasive species liquidate native biodiversity—is morally untenable. Navigating this juncture will require not only scientific rigor but also an unprecedented degree of public engagement and regulatory prudence, for the decisions made in the coming decade may well determine whether humanity can recoup what has already been lost or whether the unraveling of native ecosystems will continue unabated.',

'1940年代後半に褐色イグアナヘビが軍事貨物の密航者としてグアムに不注意に導入されたとき、その後に起こる生態学的大惨事を予見できた者はほとんどいなかった。数十年以内に、この容赦ない夜行性の捕食者は島の12種の在来森林鳥類のうち10種を絶滅に追い込み、在来のトカゲや小型哺乳類の個体数を激減させ、鳥類の捕食から解放されたクモの個体数の爆発を含む二次的効果の連鎖を引き起こし、島の生態系を根本的に変容させた。グアムの災害は孤立した大失態からほど遠く、世界的なパターンを典型化している：天然の敵がいない生態系への非在来種の導入は、現代の最も破壊的で最も扱いにくい環境危機の一つとなり、世界中で年間4000億ドル以上と推定される損害をもたらしている。

侵入種が新たな生息地に浸透する経路は、遮断が困難であるのと同様に多様である。国際海運が主要なベクターであり続けている：貨物船が放出するバラスト水は毎日推定7000種を海洋の境界を越えて輸送し、一方で生物は船体表面に付着し、船が停泊すると岸に駆け上がる。世界的なペット取引はもう一つの主要な経路を構成している。現在フロリダのエバーグレーズに土着しているビルマニシキヘビは、ほぼ確実に個人のコレクションから放出または逃走したものである。農業輸入品もまた密航者——検疫検査を逃れて好適な新しい地形に定着する昆虫、真菌、植物病原体——を運ぶ。侵入種がいったん足場を得ると、繁殖率が現実的なあらゆる封じ込め努力を通常上回るため、根絶は指数関数的に困難になる。1970年代に養殖池の藻類を制御するために米国に導入されたアジア鯉は、その後ミシシッピ川水系に逃げ出し、それ以来暴れ回り、在来魚と食料を巡って競争し、五大湖の生態系の最後の防衛線である電気バリアを突破する脅威となっている。

侵入種が大混乱を引き起こす生態学的メカニズムは複数であり、しばしば相乗的である。褐色イグアナヘビに例示される直接的な捕食は最も目立つが、資源をめぐる競争も同様に壊滅的であり得る。五大湖では、1980年代後半にカスピ海からバラスト水で到着したゼブラ貝が、太陽光が以前は濁りに覆われていた深さまで浸透するほど澄んだ濾過水の過剰を生み出し、水中食物網を根本的に変え、都市の水道供給を苦しめる有毒藻類ブルームを可能にした。一方、侵入植物は景観全体を変容させ得る：「南部を食べ尽くした蔓」であるクズは、ピークシーズン中に1日30センチメートルを超える速度で成長して在来植生を窒息させ、オーストラリアではウチワサボテンがかつて2500万ヘクタール以上に蔓延した後、生物的防除剤——カクトブラスティス蛾——がそれを抑制するために導入された。おそらく最も陰険なのは、侵入種が病気の伝播において果たす役割である：現在南極大陸を除くすべての大陸に定着しているアジアヤブカは、デング熱、チクングニア、ジカウイルスのベクターとして機能し、生態学的領域をはるかに超えた公衆衛生上の負担を課している。

侵入種と戦う取り組みは歴史的に2つの大きな戦略——予防と制御——の間で揺れ動いてきた。予防——生物が定着する前に阻止すること——ははるかに費用対効果の高いアプローチであるが、持続することが困難であることが証明されている国際的な調整とプロトコル執行のレベルを要求する。生物安全保障の世界的リーダーと広く見なされているニュージーランドは、世界で最も厳格な国境検査体制の一つを運用している：到着した乗客は生物安全保障担当官と探知犬に日常的に声をかけられ、未申告の生物材料は速やかに没収される。それでも新たな侵入は意気消沈するほどの規則性で発生する。予防が失敗すると、制御措置は化学処理や物理的除去から生物的防除剤——侵入者を抑制するために輸入された天然の捕食者や病原体——の展開にまで及ぶ。しかしそのような介入には独自のリスクが伴う：サトウキビ畑の甲虫の蔓延を制御するために1935年にオーストラリアに導入されたオオヒキガエル自体が大陸の最も破壊的な侵入種の一つとなり、徹底的なリスク評価なしにさらなる生物導入を認可することに当局を慎重にさせた警告的な物語である。

侵入種管理のフロンティアは、わずか10年前には難解であった遺伝子技術に今やある。遺伝子ドライブ——通常の遺伝を超える速度で集団を通じて広がる工学的遺伝要素——は、化学的または生物学的方法に伴う付随的損害なしに侵入種を抑制または排除さえする魅力的な見通しを提供する。オーストラリアの連邦科学産業研究機構を含む機関の研究者たちは、従来の根絶方法がしばしば仕事を台無しにしたり法外に高価であることが証明された島嶼での侵入齧歯類を制御するツールとして遺伝子ドライブを積極的に探求している。しかし、遺伝子ドライブ生物を野生に放出することの倫理的および生態学的含意は激しい議論を引き起こしている。批判者は工学的遺伝子が予見不可能な結果をもたらして非標的種に飛び移る可能性があると警告し、一方で支持者は代替案——侵入種が在来の生物多様性を壊滅させるのを無力に見守ること——は道徳的に擁護できないと主張する。この岐路を乗り切るには科学的厳密さだけでなく、前例のない程度の市民参加と規制上の慎重さも必要であろう。なぜなら、来る10年間に下される決定が、人類がすでに失われたものを取り戻せるかどうか、それとも在来生態系の解体が衰えることなく続くかどうかを決定する可能性が十分にあるからだ。');

INSERT INTO passage_questions (id, passage_id, question_number, question_type, question_text, explanation, correct_choice) VALUES
(217, 73, 1, 'comprehension',
 'What does the passage indicate about the challenges of eradicating invasive species once they have become established?',
 '第2段落で、侵入種がいったん足場を得ると繁殖率が封じ込め努力を上回るため根絶が指数関数的に困難になると述べられ、アジア鯉の例が挙げられている。第4段落ではオオヒキガエルの例で生物的防除の失敗も示されている。選択肢2が正解。',
 2),
(218, 73, 2, 'comprehension',
 'According to the passage, why has gene drive technology for invasive species management generated controversy?',
 '第5段落で、遺伝子ドライブ生物を野生に放出することについて、批判者は工学的遺伝子が非標的種に飛び移り予見不可能な結果をもたらす可能性を警告している一方、支持者は侵入種が在来の生物多様性を壊滅させるのを見守る代替案は道徳的に擁護できないと主張していると述べられている。選択肢4が正解。',
 4),
(219, 73, 3, 'fill_in_blank',
 'Choose the best option to fill in the blank [BLANK] in the passage.',
 '空所は第3段落にあり、オーストラリアでウチワサボテンが2500万ヘクタール以上に蔓延した後、カクトブラスティス蛾が導入された目的を述べる部分。文脈から、蛾は侵入植物であるサボテンを抑制するために導入されたことが読み取れる。選択肢1が正解。',
 1);

INSERT INTO question_choices (question_id, choice_number, choice_text) VALUES
(217, 1, 'Invasive species can be reliably eliminated through coordinated international hunting programs, provided sufficient funding is allocated within the first five years of detection.'),
(217, 2, 'Once established, invasive species reproduce at rates that typically outpace containment efforts, making eradication exponentially more difficult and often impractical.'),
(217, 3, 'The primary obstacle to eradication is the lack of scientific knowledge about invasive species'' reproductive biology, which prevents researchers from developing targeted countermeasures.'),
(217, 4, 'Eradication is straightforward in island ecosystems but virtually impossible on continental landmasses due to the larger geographical areas involved.'),
(218, 1, 'Gene drives have been shown to cause widespread mutations in target species that render them more aggressive and dangerous to humans.'),
(218, 2, 'The technology is prohibitively expensive, costing billions of dollars per application, which makes it inaccessible to the developing nations where invasive species cause the greatest damage.'),
(218, 3, 'Religious organizations have condemned gene drives as a violation of natural law, creating political opposition that has blocked all research funding.'),
(218, 4, 'There are concerns that engineered genes could spread to unintended species with unpredictable consequences, though proponents argue that inaction against invasive species is itself morally indefensible.'),
(219, 1, 'curb the cactus''s spread and reclaim the land for agricultural use'),
(219, 2, 'pollinate native plant species that had been displaced by the invasive cactus across the Australian outback'),
(219, 3, 'serve as a food source for endangered bird species whose populations had declined due to habitat loss caused by the cactus'),
(219, 4, 'decompose the dead cactus material into nutrient-rich soil that could support the regeneration of native grasslands');

INSERT INTO passage_words (passage_id, word_id) SELECT 73, id FROM words WHERE word_number IN (210, 680, 73, 656, 677, 695, 495, 643, 361, 631, 608, 266, 593, 220, 615, 278, 238, 294, 689, 382, 621, 598, 173, 525, 610, 639, 644);
