INSERT INTO passages (id, title, topic, word_range, content, content_ja) VALUES (82, 'Learned Helplessness and the Erosion of Agency', '心理', '1~1000',
'In the late 1960s, a young psychologist named Martin Seligman stumbled upon a finding that would reshape the landscape of clinical psychology. While conducting experiments on classical conditioning in dogs, Seligman observed that animals subjected to inescapable electric shocks eventually ceased all attempts to flee, even when an escape route was subsequently made available. The dogs simply lay down and whimpered, having apparently concluded that their actions were futile. Seligman termed this phenomenon "learned helplessness" and postulated that it might serve as an explanatory model for human depression—a conjecture that, over the ensuing decades, has been corroborated by a vast body of research and has profoundly influenced therapeutic practice worldwide.

The core mechanism of learned helplessness is deceptively straightforward: when organisms repeatedly experience outcomes that appear independent of their actions, they develop a pervasive expectation that future efforts will likewise prove ineffectual. This expectation, once entrenched, produces a triad of deficits—motivational, cognitive, and emotional. Motivationally, the individual becomes apathetic, eschewing opportunities that might actually yield positive results. Cognitively, a peculiar distortion takes hold: even when successes do occur, the helpless person attributes them to external factors—luck, the benevolence of others, or sheer coincidence—rather than to their own competence. Emotionally, the cumulative weight of perceived powerlessness engenders a somber resignation that can, in its most acute form, culminate in clinical depression. What makes learned helplessness particularly insidious is its self-reinforcing nature: the fewer actions a person takes, the fewer opportunities arise for disconfirming the belief that action is pointless, thereby perpetuating a vicious cycle that proves exceedingly arduous to break.

Seligman''s original formulation, however, was not without its detractors. Critics pointed out that not all individuals exposed to uncontrollable situations develop helplessness; some, paradoxically, emerge more resilient. This observation prompted the psychologist to collaborate with his colleagues Lyn Abramson and John Teasdale on a reformulated theory, published in 1978, that introduced the concept of "attributional style" as a mediating variable. According to this revised framework, what matters is not merely the experience of uncontrollability but how individuals construe that experience. People who habitually attribute negative events to causes that are internal ("It''s my fault"), stable ("It will always be this way"), and global ("This affects everything in my life") are far more susceptible to learned helplessness than those who favor external, transient, and specific explanations. This attributional model has since become a cornerstone of cognitive behavioral therapy, furnishing clinicians with a tangible target for intervention: by helping patients identify and challenge their pessimistic explanatory patterns, therapists can gradually dismantle the cognitive architecture that sustains helplessness.

The ramifications of learned helplessness extend well beyond the therapist''s office. Educational researchers have documented its corrosive effects in classroom settings, where students who repeatedly flounder on tasks calibrated beyond their current abilities may internalize a belief that academic achievement is beyond their reach. Once this conviction takes root, even well-intentioned pedagogical interventions can [BLANK], as the student''s default response to challenge becomes passive withdrawal rather than renewed effort. Workplace studies have revealed analogous patterns: employees subjected to chronic micromanagement or arbitrary evaluative criteria often exhibit diminished initiative, reduced creativity, and a reluctance to broach new ideas—symptoms that managers frequently misdiagnose as laziness or incompetence rather than as predictable consequences of an environment that has systematically curtailed their sense of autonomy.

More recently, scholars have begun to explore learned helplessness at the societal level, examining how prolonged exposure to systemic inequities can foster collective passivity. Communities plagued by persistent poverty, discriminatory policing, or institutional neglect may develop a shared expectation that civic engagement is futile—a phenomenon that some political scientists have termed "political helplessness." This collective resignation does not reflect an innate deficiency in affected populations but rather a rational, if ultimately detrimental, adaptation to environments in which individual agency has been repeatedly nullified. Addressing this form of helplessness demands more than motivational rhetoric or incremental policy adjustments; it requires substantive structural reforms that restore tangible connections between citizens'' actions and observable outcomes, thereby rekindling the belief—fragile yet indispensable—that effort can, in fact, make a difference.',

'1960年代後半、マーティン・セリグマンという若い心理学者が、臨床心理学の風景を一変させる発見に偶然出会った。犬の古典的条件づけに関する実験を行っていた際、セリグマンは逃れられない電気ショックを受けた動物が、たとえその後逃走経路が利用可能になっても、やがてすべての逃走の試みをやめることを観察した。犬は単に横たわって泣き声を上げるだけで、自分の行動が無駄であると結論づけたようだった。セリグマンはこの現象を「学習性無力感」と名付け、それが人間のうつ病の説明モデルとして機能するかもしれないと仮定した——この推測は、その後の数十年にわたって膨大な研究によって裏付けられ、世界中の治療実践に深い影響を与えてきた。

学習性無力感の中核メカニズムは一見したところ単純明快である：有機体が自分の行動とは無関係に見える結果を繰り返し経験すると、将来の努力も同様に無効であるという広範な期待を発達させる。この期待はひとたび定着すると、動機づけ、認知、感情という三つの欠陥を生み出す。動機づけの面では、個人は無気力になり、実際には肯定的な結果をもたらすかもしれない機会を避けるようになる。認知の面では、独特の歪みが生じる：成功が実際に起こったときでさえ、無力感を抱いた人はそれを自分の能力ではなく、運、他者の好意、または単なる偶然といった外的要因に帰属させる。感情の面では、認知された無力感の累積的な重みが陰鬱な諦めを生み出し、最も重症の場合には臨床的うつ病に至ることがある。学習性無力感を特に陰険にしているのはその自己強化的な性質である：人が行動を起こさなければ起こさないほど、行動は無意味だという信念を覆す機会が少なくなり、それによって打破が極めて困難な悪循環が永続する。

しかし、セリグマンの当初の定式化には批判者がいなかったわけではない。批判者は、統制不能な状況にさらされたすべての個人が無力感を発達させるわけではないことを指摘した。逆説的に、より回復力を増して現れる者もいる。この観察は、セリグマンに同僚のリン・エイブラムソンとジョン・ティーズデイルと協力して、媒介変数として「帰属スタイル」の概念を導入した改訂理論（1978年発表）に取り組むよう促した。この修正された枠組みによれば、重要なのは統制不能性の経験そのものだけでなく、個人がその経験をどのように解釈するかである。否定的な出来事を内的（「私のせいだ」）、安定的（「いつもこうなる」）、全般的（「これは人生のすべてに影響する」）な原因に習慣的に帰属させる人は、外的、一時的、特定的な説明を好む人よりも学習性無力感にはるかに影響されやすい。この帰属モデルは以来、認知行動療法の礎石となり、臨床家に介入の具体的な対象を提供している：患者が悲観的な説明パターンを特定し挑戦するのを助けることで、治療者は無力感を維持する認知的構造を段階的に解体することができる。

学習性無力感の影響は治療室をはるかに超えて広がっている。教育研究者は教室環境でのその腐食的な影響を記録しており、現在の能力を超えるように調整された課題で繰り返し失敗する生徒は、学業成績が手の届かないものだという信念を内面化する可能性がある。この確信がひとたび根づくと、たとえ善意の教育的介入であっても失敗に終わることがある。なぜなら、挑戦に対する生徒の既定の反応が、新たな努力ではなく受動的な撤退になるからだ。職場の研究でも類似のパターンが明らかになっている：慢性的なマイクロマネジメントや恣意的な評価基準にさらされた従業員は、しばしばイニシアチブの低下、創造性の減少、新しいアイデアを切り出すことへの消極性を示す——これらの症状を管理者は、自律性の感覚を体系的に削減してきた環境の予測可能な帰結としてではなく、怠慢や無能力とよく誤診する。

より最近では、学者たちは社会レベルでの学習性無力感を探求し始めており、体系的な不平等への長期的な曝露がいかに集団的な受動性を育みうるかを検討している。根強い貧困、差別的な警察活動、または制度的な無関心に悩まされるコミュニティは、市民参加は無駄であるという共有された期待を発達させる可能性がある——一部の政治学者が「政治的無力感」と呼ぶ現象である。この集団的な諦めは、影響を受けた集団の生まれつきの欠陥を反映するものではなく、個人の主体性が繰り返し無効化されてきた環境への合理的な、しかし究極的には有害な適応である。この形態の無力感に対処するには、動機づけの修辞や漸進的な政策調整以上のものが必要であり、市民の行動と観察可能な結果との間の具体的なつながりを回復する実質的な構造改革を必要とする。それによって、努力が実際に違いを生むことができるという、脆いが不可欠な信念を再び灯すのである。');

INSERT INTO passage_questions (id, passage_id, question_number, question_type, question_text, explanation, correct_choice) VALUES
(244, 82, 1, 'comprehension',
 'According to the passage, how did the reformulated theory of learned helplessness improve upon Seligman''s original model?',
 '第3段落で、エイブラムソンとティーズデイルとの共同研究により、「帰属スタイル」が媒介変数として導入されたことが説明されている。重要なのは統制不能性の経験そのものではなく、個人がその経験をどう解釈するか（内的・安定的・全般的 vs 外的・一時的・特定的）であるとされた。選択肢1が正解。',
 1),
(245, 82, 2, 'comprehension',
 'What does the passage suggest about the manifestation of learned helplessness in workplace environments?',
 '第4段落後半で、慢性的なマイクロマネジメントや恣意的な評価基準にさらされた従業員がイニシアチブの低下や創造性の減少を示し、管理者がこれらを怠慢や無能力と誤診することが述べられている。これらは自律性を体系的に削減してきた環境の予測可能な帰結であるとされている。選択肢4が正解。',
 4),
(246, 82, 3, 'fill_in_blank',
 'Choose the best option to fill in the blank [BLANK] in the passage.',
 '空所は第4段落にあり、学業成績が手の届かないものだと内面化した生徒に対する教育的介入の結果を述べる部分。文脈から、生徒の既定の反応が受動的な撤退であるため善意の介入も効果が出ないという内容が適切。選択肢3が正解。',
 3);

INSERT INTO question_choices (question_id, choice_number, choice_text) VALUES
(244, 1, 'It introduced attributional style as a mediating factor, explaining why some individuals develop helplessness while others remain resilient when facing the same uncontrollable situations.'),
(244, 2, 'It demonstrated that learned helplessness is an exclusively biological phenomenon caused by neurochemical imbalances rather than by psychological interpretations of experience.'),
(244, 3, 'It proved that learned helplessness affects only individuals with pre-existing mental health conditions and has no relevance to the general population.'),
(244, 4, 'It replaced the concept of learned helplessness entirely with a new theory based on evolutionary psychology and genetic predisposition.'),
(245, 1, 'Employees who experience learned helplessness invariably resign from their positions, leading to high turnover rates that alert management to systemic problems.'),
(245, 2, 'Workplace learned helplessness manifests exclusively as interpersonal conflict among colleagues rather than as reduced individual initiative or creativity.'),
(245, 3, 'Learned helplessness in the workplace can be entirely prevented through regular performance reviews and clear communication of expectations.'),
(245, 4, 'Employees subjected to excessive control and arbitrary evaluation criteria display diminished initiative and creativity, symptoms that managers often misattribute to personal failings rather than environmental factors.'),
(246, 1, 'succeed dramatically, as the student''s underlying desire for academic recognition overrides the accumulated sense of futility'),
(246, 2, 'produce anxiety and hostility, as the student perceives additional support as an implicit criticism of their intellectual capacity'),
(246, 3, 'fall short of their intended impact, as the student''s ingrained expectation of failure leads them to disengage rather than respond constructively'),
(246, 4, 'trigger an immediate reversal of the learned helplessness pattern, since external encouragement is the primary catalyst for restoring self-efficacy');

INSERT INTO passage_words (passage_id, word_id) SELECT 82, id FROM words WHERE word_number IN (115, 69, 560, 52, 269, 264, 252, 608, 841, 154, 981, 256, 225, 239, 402, 409, 137, 614, 231, 335, 136, 407, 969, 534, 681);
