INSERT INTO passages (id, title, topic, word_range, content, content_ja) VALUES (70, 'Permafrost Thaw and the Methane Time Bomb', '環境', '1~700',
'Beneath the vast, arid expanses of Siberia, Alaska, and northern Canada lies a geological reservoir that climate scientists have long regarded with a mixture of fascination and dread. Permafrost—ground that has remained frozen for at least two consecutive years, though much of it has been locked in ice for millennia—stores an estimated 1,500 billion metric tons of organic carbon, roughly twice the amount currently present in the Earth''s atmosphere. As global temperatures continue their relentless upward trajectory, this frozen terrain is beginning to thaw at rates that have left researchers perplexed and alarmed. The incremental warming observed over past decades has now given way to abrupt destabilization in certain regions, and the consequences threaten to unravel the carefully calibrated models on which international climate policy rests.

The mechanism by which permafrost thaw accelerates climate change is deceptively straightforward. When frozen soil warms, microbial communities that have lain dormant for thousands of years regenerate and begin to dissect the ancient organic matter entombed within. This decomposition produces two potent greenhouse gases: carbon dioxide under aerobic conditions and methane where oxygen is absent. Methane is of particular concern because, molecule for molecule, its warming potential over a twenty-year horizon is approximately eighty times that of carbon dioxide. Scientists monitoring the Arctic have documented a spate of methane emissions from thermokarst lakes—bodies of water formed when ice-rich permafrost collapses—that were not adequately accounted for in previous climate projections. The pivotal question is no longer whether these emissions will materialize but how rapidly they will escalate and whether any realistic intervention can temper their impact.

Field research in the Siberian tundra has underscored the urgency of the situation. Sergey Zimov, a Russian ecologist who has devoted his career to studying permafrost dynamics, established the Pleistocene Park project in northeastern Siberia, an ambitious attempt to restore grassland ecosystems that could insulate the permafrost and slow its degradation. The premise is rooted in paleontological evidence: during the Pleistocene epoch, large herbivores such as mammoths, bison, and wild horses maintained grasslands by trampling snow, which reduced its insulating effect and kept the ground colder. By reintroducing modern analogues—bison, horses, and musk oxen—Zimov aims to replicate this process. Critics, however, have been brusquely dismissive, arguing that the scale required to make a meaningful difference is so enormous as to render the project a quixotic endeavor rather than a viable climate strategy. Whether such skepticism is warranted or whether it merely reflects a penchant for defeatism in the face of unprecedented challenges remains a subject of ardent debate.

Beyond localized experiments, the broader policy landscape offers little cause for levity. The provisions of the Paris Agreement do not explicitly address permafrost emissions, a glaring omission that many scientists regard as a pitfall in the international climate framework. Current nationally determined contributions assume a relatively subdued rate of carbon release from thawing permafrost, yet emerging data suggest that these projections may depreciate the true scale of the threat by a significant margin. A 2022 study published in Nature Climate Change estimated that even under an optimistic emissions scenario, permafrost thaw could release between 50 and 100 billion additional tons of carbon by 2100—an amount sufficient to negate the gains achieved through [BLANK]. Meanwhile, infrastructure built on permafrost is already beginning to buckle: in Russia, roads careen into sinkholes, pipelines rupture, and buildings that once stood on stable foundations now slouch at precarious angles. The economic toll, already running into billions of dollars, is projected to plummet further into catastrophic territory as warming intensifies.

The challenge of permafrost thaw is, at its core, a testament to the interconnectedness of Earth''s climate system. What transpires in the remote Arctic does not remain confined there; the methane and carbon dioxide released from thawing ground enter the global atmosphere, compounding the warming that caused the thaw in the first place—a feedback loop that, once fully engaged, may prove invincible to human intervention. Prudence demands that policymakers treat permafrost not as a peripheral concern but as a chronic, escalating threat that must be integrated into every climate model, every emissions target, and every adaptation strategy. The alternative—continuing to treat the Arctic as a distant abstraction while its frozen carbon reserves brew into atmospheric poison—would constitute a dereliction of responsibility whose consequences future generations will neither forgive nor forget.',

'シベリア、アラスカ、カナダ北部の広大で乾燥した地域の地下には、気候科学者が長い間魅了と恐怖の入り混じった目で見てきた地質学的貯蔵庫がある。永久凍土——少なくとも2年連続で凍結したままの地面であるが、その多くは数千年にわたって氷の中に閉じ込められてきた——は推定1兆5000億トンの有機炭素を貯蔵しており、これは現在地球の大気中に存在する量のおよそ2倍である。地球の気温が容赦なく上昇し続ける中、この凍った地形は研究者を困惑させ警戒させるほどの速度で融解し始めている。過去数十年にわたって観測された漸進的な温暖化は、特定の地域では突然の不安定化に取って代わられ、その結果は国際的な気候政策が依拠する慎重に較正されたモデルを解きほぐす恐れがある。

永久凍土の融解が気候変動を加速するメカニズムは、欺瞞的なほど単純である。凍った土壌が温まると、数千年にわたって休眠していた微生物群集が再生し、内部に埋葬された古代の有機物を分解し始める。この分解は2つの強力な温室効果ガスを生み出す：好気条件下での二酸化炭素と酸素がない場所でのメタンである。メタンは分子単位で比較すると、20年間の温暖化ポテンシャルが二酸化炭素の約80倍であるため特に懸念される。北極を監視している科学者たちは、サーモカルスト湖——氷を豊富に含む永久凍土が崩壊して形成された水域——からの一連のメタン排出を記録しており、これらは以前の気候予測では適切に考慮されていなかった。極めて重要な問題は、これらの排出が実現するかどうかではなく、どれほど急速にエスカレートするか、そして現実的な介入がその影響を和らげることができるかである。

シベリアのツンドラにおける現地調査は状況の緊急性を浮き彫りにしている。永久凍土の動態研究に生涯を捧げてきたロシアの生態学者セルゲイ・ジモフは、シベリア北東部に更新世公園プロジェクトを設立した。これは草地の生態系を復元し、永久凍土を断熱してその劣化を遅らせようとする野心的な試みである。その前提は古生物学的証拠に根ざしている：更新世の時代、マンモスやバイソン、野生馬などの大型草食動物が雪を踏み固めることで草地を維持し、それが雪の断熱効果を低下させて地面をより冷たく保っていた。現代の類似種——バイソン、馬、ジャコウウシ——を再導入することで、ジモフはこのプロセスを再現することを目指している。しかし批判者たちはぶっきらぼうに否定的で、意味のある違いを生むために必要な規模が非常に巨大であるため、このプロジェクトは実行可能な気候戦略というよりもドン・キホーテ的な試みに過ぎないと主張している。そのような懐疑が正当であるのか、それとも前例のない課題に直面した際の敗北主義への嗜好を反映しているに過ぎないのかは、熱い議論の的であり続けている。

局所的な実験を超えて、より広い政策の風景は気軽に構えていられる余地をほとんど提供しない。パリ協定の条項は永久凍土の排出を明示的に取り上げておらず、多くの科学者はこれを国際的な気候枠組みの落とし穴と見なしている。現在の各国の決定貢献は融解する永久凍土からの比較的抑えられた炭素放出速度を想定しているが、新たなデータはこれらの予測が脅威の真の規模を大幅に過小評価している可能性を示唆している。2022年にNature Climate Change誌に発表された研究は、楽観的な排出シナリオの下でも、永久凍土の融解が2100年までに500億から1000億トンの追加炭素を放出する可能性があると推定した——これは各国が実施する積極的な脱炭素化政策によって達成される利益を帳消しにするのに十分な量である。一方、永久凍土の上に建設されたインフラはすでに崩壊し始めている：ロシアでは道路が陥没穴に突っ込み、パイプラインが破裂し、かつて安定した基礎の上に立っていた建物が危険な角度で傾いている。すでに数十億ドルに達している経済的被害は、温暖化が激化するにつれてさらに壊滅的な領域に落ち込むと予測されている。

永久凍土の融解という課題は、本質的に地球の気候システムの相互接続性の証である。遠隔地の北極で起こることはそこに留まらない：融解する地面から放出されるメタンと二酸化炭素は地球の大気に入り、そもそも融解を引き起こした温暖化を増幅する——一度完全に作動すれば人間の介入では克服不可能かもしれないフィードバックループである。慎重さは、政策立案者が永久凍土を周辺的な懸念としてではなく、すべての気候モデル、すべての排出目標、すべての適応戦略に統合されるべき慢性的でエスカレートする脅威として扱うことを求めている。代替案——北極をその凍った炭素埋蔵量が大気の毒に醸成される間、遠い抽象概念として扱い続けること——は、将来の世代が許しも忘れもしない責任放棄を構成するだろう。');

INSERT INTO passage_questions (id, passage_id, question_number, question_type, question_text, explanation, correct_choice) VALUES
(208, 70, 1, 'comprehension',
 'What does the passage suggest about Sergey Zimov''s Pleistocene Park project?',
 '第3段落で、ジモフのプロジェクトは更新世の大型草食動物が雪を踏み固めて地面を冷たく保っていたという古生物学的証拠に基づき、現代の類似種を再導入して永久凍土を保護しようとするものだと説明されている。批判者はその規模の問題から実現不可能と否定しているが、著者はこの懐疑が敗北主義を反映している可能性も示唆している。選択肢3が正解。',
 3),
(209, 70, 2, 'comprehension',
 'According to the passage, what is a significant shortcoming of the Paris Agreement with respect to permafrost?',
 '第4段落で、パリ協定の条項が永久凍土の排出を明示的に取り上げていないことが国際的な気候枠組みの「落とし穴」であると述べられている。現在の各国の決定貢献は融解する永久凍土からの炭素放出速度を過小評価している可能性がある。選択肢1が正解。',
 1),
(210, 70, 3, 'fill_in_blank',
 'Choose the best option to fill in the blank [BLANK] in the passage.',
 '空所は第4段落にあり、永久凍土の融解による追加炭素放出が「何によって達成される利益を帳消しにするのに十分な量」かを示す文脈。前後の議論から、各国の積極的な脱炭素化政策による利益を帳消しにするという趣旨が最も適切。選択肢2が正解。',
 2);

INSERT INTO question_choices (question_id, choice_number, choice_text) VALUES
(208, 1, 'It has already demonstrated measurable success in lowering permafrost temperatures across a wide area of northeastern Siberia.'),
(208, 2, 'It relies on genetic engineering to recreate extinct Pleistocene megafauna capable of restoring ancient grassland ecosystems.'),
(208, 3, 'It seeks to reintroduce large herbivores to replicate Pleistocene-era conditions that kept permafrost colder, though critics question whether it can operate at a meaningful scale.'),
(208, 4, 'It has been endorsed by the Russian government as the country''s primary strategy for mitigating methane emissions from Arctic permafrost regions.'),
(209, 1, 'The agreement does not explicitly address permafrost emissions, and current national pledges likely underestimate the rate of carbon release from thawing permafrost.'),
(209, 2, 'The agreement requires member states to reduce methane emissions but exempts natural sources such as permafrost thaw from its regulatory framework.'),
(209, 3, 'The agreement allocates insufficient funding for Arctic research, preventing scientists from accurately measuring the volume of methane released by thermokarst lakes.'),
(209, 4, 'The agreement prohibits geoengineering solutions that could slow permafrost degradation, limiting available mitigation strategies to emissions reduction alone.'),
(210, 1, 'international reforestation initiatives and marine carbon-capture technologies deployed since the signing of the Kyoto Protocol'),
(210, 2, 'aggressive decarbonization policies implemented by nations worldwide'),
(210, 3, 'the voluntary carbon offset programs established by multinational corporations under the Paris Agreement''s market mechanism'),
(210, 4, 'the natural reabsorption of atmospheric carbon by regenerating boreal forests across the Northern Hemisphere');

INSERT INTO passage_words (passage_id, word_id) SELECT 70, id FROM words WHERE word_number IN (578, 680, 631, 653, 614, 644, 651, 623, 646, 603, 665, 509, 301, 674, 427, 624, 605, 675, 548, 697, 469, 616, 522, 639, 663, 632, 476, 619);
