INSERT INTO passages (id, title, topic, word_range, content, content_ja) VALUES (69, 'The International Criminal Court: Justice Without Borders?', '政治', '1~700',
'When the Rome Statute entered into force in 2002, establishing the International Criminal Court (ICC) as a permanent tribunal for prosecuting genocide, crimes against humanity, and war crimes, its architects envisioned an institution that would serve as the antithesis of impunity—a court of last resort capable of holding even the most powerful leaders accountable. More than two decades later, the ICC stands at a critical juncture, its legitimacy assailed by critics from virtually every ideological quarter. Some regard it as an instrument of Western neo-imperialism that disproportionately targets African leaders while turning a blind eye to atrocities committed by the great powers. Others dismiss it as a toothless body whose verdicts carry no enforcement mechanism, leaving its judgments reminiscent of diplomatic communiques rather than binding legal decisions. Understanding whether the ICC can fulfill its founding promise requires a candid assessment of both its achievements and its structural limitations.

The court''s record is, by any honest accounting, a mosaic of modest successes and conspicuous failures. On the positive side, the ICC secured the conviction of Thomas Lubanga Dyilo, a Congolese militia leader, in 2012 for the recruitment of child soldiers—the first verdict delivered by the court and a pivotal moment in the development of international criminal law. The tribunal has also issued arrest warrants for sitting heads of state, most notably for Omar al-Bashir, the former president of Sudan, on charges of orchestrating a conflagration of violence in Darfur that constituted genocide. Yet al-Bashir traveled freely to ICC member states for years without being apprehended, a fiasco that underscored the court''s fundamental weakness: it possesses no police force, no army, and no independent capacity to compel compliance. It must rely on the cooperation of sovereign states, whose willingness to assist is often tempered by political calculation rather than legal obligation.

The question of selective prosecution has proven especially corrosive to the ICC''s credibility. Of the court''s completed cases, the overwhelming majority have involved defendants from African nations—a pattern that has provoked ardent criticism from the African Union and led several member states to threaten to secede from the Rome Statute. Critics allege that the court has been reluctant to pursue investigations into alleged war crimes committed by nationals of powerful Western countries or their allies, pointing to the long-delayed and ultimately abandoned preliminary examination of certain incidents during the conflict in Afghanistan. The court''s defenders counter that Africa has been disproportionately represented not because of institutional bias but because of the continent''s acute vulnerability to the kinds of mass atrocity that fall within the ICC''s jurisdiction. This rebuttal, while not without merit, has failed to mollify those who perceive a double standard at work.

The ICC''s relationship with the United States exemplifies many of these tensions. Although the Clinton administration signed the Rome Statute in 2000, the Bush administration unsigned it two years later, and Congress passed the American Service-Members'' Protection Act, which authorized the president to use "all means necessary" to liberate any American detained by the court—a provision that critics have termed "The Hague Invasion Act." Successive administrations have oscillated between cautious engagement and outright hostility. The Trump administration went so far as to impose sanctions on ICC officials who pursued investigations into American military conduct, a measure that the Biden administration subsequently waived. This turbulent history has emboldened other nations to question why they should submit to a jurisdiction that the world''s most powerful country refuses to recognize, thereby [BLANK].

Parallel to these political challenges, the ICC confronts procedural and institutional obstacles that impede its effectiveness. Investigations are arduous, often spanning a decade or more, and the evidentiary standards required for conviction are rightly exacting. Witnesses face intimidation, evidence is destroyed or confiscated by state actors, and the depositions of key informants are frequently compromised. The court''s budget—approximately 170 million euros annually—is modest relative to the scope of its mandate, and chronic underfunding has forced prosecutors to prioritize cases with the strongest evidentiary foundations rather than those involving the gravest atrocities. The interim chief prosecutor has acknowledged that the office must adopt more expeditious methods, but whether greater efficiency is achievable without compromising due process remains an open question.

Despite these formidable challenges, the ICC retains a significance that transcends its conviction rate. Its mere existence alters the calculus of political leaders contemplating mass violence: the knowledge that indictments can follow them across borders and across decades introduces a measure of deterrence that did not exist before 2002. The court has also served as a catalyst for domestic prosecution, prompting nations to strengthen their own judicial systems rather than risk the reputational cost of an ICC investigation. Whether these indirect effects constitute a sufficient testament to the court''s value is a question that will occupy scholars of international law for generations. What is certain is that the aspiration encoded in the Rome Statute—that no atrocity should go unpunished, regardless of the perpetrator''s power or the victim''s obscurity—remains as urgent as it was at the court''s founding, even if the institution charged with realizing it continues to fall short of its own ideals.',

'2002年にローマ規程が発効し、国際刑事裁判所（ICC）がジェノサイド、人道に対する罪、戦争犯罪を訴追する常設裁判所として設立されたとき、その設計者たちは不処罰の対極となる機関――最も強力な指導者さえも責任を問うことができる最後の頼みの裁判所――を構想していた。20年以上が経った現在、ICCは重大な岐路に立っており、その正統性は事実上あらゆるイデオロギー的立場の批判者から攻撃されている。アフリカの指導者を不均衡に標的にしながら大国が犯した残虐行為に目をつぶる西洋の新帝国主義の道具と見なす者もいる。執行メカニズムを持たない骨抜きの組織であり、その判決は拘束力のある法的決定というよりも外交的コミュニケを彷彿とさせると退ける者もいる。ICCが設立の約束を果たせるかどうかを理解するには、その成果と構造的限界の双方についての率直な評価が必要である。

裁判所の記録は、正直に評価すれば、控えめな成功と目立つ失敗のモザイクである。肯定的な面では、ICCは2012年にコンゴの民兵指導者トマス・ルバンガ・ディロを少年兵の徴募で有罪とした――裁判所が下した最初の評決であり、国際刑法の発展における極めて重要な瞬間であった。裁判所はまた、現職の国家元首に対する逮捕状を発行しており、最も注目すべきはスーダンの元大統領オマル・アル＝バシルに対するもので、ダルフールにおけるジェノサイドを構成する暴力の大火を画策した容疑であった。しかしアル＝バシルはICC加盟国を何年も自由に訪問し逮捕されなかった。これは裁判所の根本的弱点――警察力も軍隊も遵守を強制する独立した能力も持たないこと――を浮き彫りにする大失態であった。裁判所は主権国家の協力に頼らなければならず、その支援意思は法的義務よりも政治的計算によって左右されることが多い。

選択的訴追の問題はICCの信頼性にとって特に腐食的であることが証明されている。裁判所の完了した事件の圧倒的多数はアフリカ諸国の被告に関わるものであり――これはアフリカ連合からの熱烈な批判を招き、複数の加盟国がローマ規程からの脱退を脅かすに至ったパターンである。批判者たちは、裁判所が強力な西側諸国やその同盟国の国民が犯したとされる戦争犯罪の調査を追求することに消極的であったと主張し、アフガニスタン紛争中の特定の事件に関する長期間遅延し最終的に放棄された予備審査を指摘する。裁判所の擁護者は、アフリカが不均衡に代表されているのは制度的偏向のためではなく、ICCの管轄権に該当する種類の大量残虐行為に対する大陸の深刻な脆弱性のためであると反論する。この反論は、メリットがないわけではないが、二重基準が働いていると認識する人々をなだめることには失敗している。

ICCと米国の関係はこれらの緊張の多くを例示している。クリントン政権は2000年にローマ規程に署名したが、ブッシュ政権は2年後にそれを撤回し、議会は米国軍人保護法を可決した。これは大統領が裁判所に拘留されたいかなる米国人も解放するために「あらゆる必要な手段」を使用することを認可するもので、批判者はこれを「ハーグ侵攻法」と呼んでいる。歴代政権は慎重な関与と全面的な敵意の間で揺れ動いてきた。トランプ政権は米軍の行為を調査するICC当局者に制裁を課すところまで踏み込んだが、バイデン政権はその後この措置を免除した。この激動の歴史は他の国々に、世界最強の国が認めることを拒否する管轄権になぜ服すべきかを問わせることを助長し、それによって裁判所が拠り所とする普遍性の主張そのものを損なっている。

これらの政治的課題と並行して、ICCはその有効性を妨げる手続的・制度的障害に直面している。調査は困難で、しばしば10年以上に及び、有罪判決に必要な証拠基準は当然ながら厳格である。証人は脅迫に直面し、証拠は国家主体によって破壊または没収され、重要な情報提供者の証言は頻繁に危殆化する。裁判所の予算――年間約1億7000万ユーロ――はその権限の範囲に比して控えめであり、慢性的な資金不足は検察官に最も重大な残虐行為ではなく最も強力な証拠基盤を持つ事件を優先させることを強いてきた。暫定主任検察官は、事務所がより迅速な方法を採用しなければならないことを認めているが、適正手続きを損なうことなくより高い効率が達成可能かどうかは未解決の問題である。

これらの手強い課題にもかかわらず、ICCはその有罪率を超越する重要性を保持している。その存在自体が大量暴力を企図する政治指導者の計算を変える：起訴が国境と数十年を超えて追跡し得るという認識は、2002年以前には存在しなかった抑止力の尺度をもたらす。裁判所はまた国内訴追の触媒として機能し、ICC調査の評判コストを冒すよりも自国の司法制度を強化するよう国家を促してきた。これらの間接的効果が裁判所の価値の十分な証しを構成するかどうかは、国際法の学者が世代にわたって取り組む問題である。確かなのは、ローマ規程に符号化された願望――加害者の権力や被害者の無名さにかかわらず、いかなる残虐行為も処罰されずにはいかないということ――は、それを実現する任を負う機関がその自らの理想に及ばないままであっても、裁判所の設立時と同様に緊急であるということだ。');

INSERT INTO passage_questions (id, passage_id, question_number, question_type, question_text, explanation, correct_choice) VALUES
(205, 69, 1, 'comprehension',
 'What does the passage identify as the ICC''s fundamental structural weakness?',
 '第2段落で、アル＝バシルがICC加盟国を自由に訪問し逮捕されなかったことが裁判所の根本的弱点を浮き彫りにしたと述べられている。ICCは警察力も軍隊も遵守を強制する独立した能力も持たず、主権国家の協力に依存しなければならないが、その協力は政治的計算に左右される。選択肢2が正解。',
 2),
(206, 69, 2, 'comprehension',
 'According to the passage, how does the ICC contribute to justice even beyond its direct conviction record?',
 '最終段落で、ICCの存在自体が大量暴力を企図する指導者の計算を変え抑止力をもたらすこと、また国内訴追の触媒として機能し各国が自国の司法制度を強化するよう促していると述べられている。選択肢4が正解。',
 4),
(207, 69, 3, 'fill_in_blank',
 'Choose the best option to fill in the blank [BLANK] in the passage.',
 '空所は第4段落末尾にあり、米国がICCの管轄権を拒否することが他国にどのような影響を与えたかの帰結が入る。文脈から「裁判所が拠り所とする普遍性の主張そのものを損なう」という趣旨が最も適切。選択肢1が正解。',
 1);

INSERT INTO question_choices (question_id, choice_number, choice_text) VALUES
(205, 1, 'The court lacks jurisdiction over crimes committed during internal armed conflicts, limiting its authority to international wars between sovereign states.'),
(205, 2, 'The court has no independent enforcement capability—no police force or army—and must depend on the cooperation of sovereign states, which is often governed by political interests rather than legal duty.'),
(205, 3, 'The court''s judges are appointed by the UN Security Council, giving veto-holding nations disproportionate influence over case selection and sentencing decisions.'),
(205, 4, 'The court is prohibited from issuing arrest warrants for sitting heads of state under the principle of sovereign immunity codified in the Rome Statute.'),
(206, 1, 'The ICC publishes annual reports that rank nations by their human rights records, creating reputational pressure that discourages state-sponsored violence.'),
(206, 2, 'The ICC provides financial reparations directly to victims of atrocities, ensuring that justice is achieved through material compensation regardless of whether perpetrators are convicted.'),
(206, 3, 'The ICC trains domestic prosecutors and judges in member states, building local judicial capacity that reduces the need for international intervention over time.'),
(206, 4, 'Its mere existence deters leaders from committing atrocities by introducing the possibility of cross-border prosecution, and it catalyzes nations to strengthen their own domestic judicial systems.'),
(207, 1, 'undermining the very claim to universality on which the court''s authority rests'),
(207, 2, 'prompting the ICC to relocate its headquarters from The Hague to a neutral country in the Global South'),
(207, 3, 'encouraging private international law firms to establish parallel tribunals that compete with the ICC for jurisdiction over war crimes cases'),
(207, 4, 'forcing the United Nations to revoke the Rome Statute and replace the ICC with a new institution governed exclusively by General Assembly resolutions');

INSERT INTO passage_words (passage_id, word_id) SELECT 69, id FROM words WHERE word_number IN (669, 657, 525, 684, 562, 649, 603, 191, 210, 73, 673, 665, 57, 559, 674, 125, 621, 553, 608, 238, 442, 663, 667, 604, 638, 635);
