INSERT INTO passages (id, title, topic, word_range, content, content_ja) VALUES (72, 'The Microbiome Revolution: How Gut Bacteria Shape Human Health', '生物', '1~700',
'For much of the twentieth century, mainstream medicine regarded the trillions of microorganisms inhabiting the human gut as, at best, benign passengers and, at worst, potential pathogens to be purged at the first sign of illness. This view has undergone a dramatic transformation. Advances in genomic sequencing have allowed scientists to dissect the staggering complexity of the human microbiome—the constellation of bacteria, viruses, fungi, and archaea that colonize virtually every surface of the body—and the emerging picture suggests that these microscopic residents are not mere freeloaders but pivotal architects of human health. The implications are so far-reaching that some researchers have begun to describe the gut microbiome as a previously unrecognized organ, one whose dysfunction may underlie conditions as diverse as obesity, depression, autoimmune disorders, and even certain cancers.

The sheer scale of the microbial ecosystem within us is humbling. An adult human harbors roughly 38 trillion bacterial cells—a figure that slightly exceeds the number of human cells in the body—and these organisms collectively encode approximately 150 times more genes than the human genome. This genetic bounty enables the microbiome to perform metabolic functions that human cells cannot execute autonomously: synthesizing essential vitamins, fermenting dietary fibers into short-chain fatty acids that nourish the intestinal lining, and calibrating the immune system so that it remains vigilant against genuine threats without veering into the self-destructive overreaction that characterizes autoimmune disease. When this finely tuned ecosystem is disrupted—a state known as dysbiosis—the consequences can be profound. Studies have documented that individuals with a depleted or unruly microbiome exhibit elevated rates of inflammatory bowel disease, type 2 diabetes, and cardiovascular illness, suggesting that microbial imbalance is not merely a symptom but a culprit in the pathogenesis of chronic disease.

The relationship between the gut microbiome and mental health has proven to be one of the most provocative frontiers in contemporary biology. The so-called gut-brain axis—a bidirectional communication network linking the enteric nervous system of the gastrointestinal tract to the central nervous system—provides the anatomical substrate through which intestinal bacteria can influence mood, cognition, and behavior. Landmark research conducted at University College Cork demonstrated that germ-free mice, raised in antiseptic environments devoid of microbial colonization, displayed markedly elevated anxiety-like behavior and an exaggerated stress response compared with conventionally raised counterparts. When these mice were subsequently colonized with specific bacterial strains, their behavioral profiles normalized. In humans, clinical trials have shown that certain probiotics—colloquially termed "psychobiotics"—can produce subdued cortisol responses and modest improvements in self-reported mood, though the magnitude of these effects remains a subject of [BLANK]. Critics admonish against premature extrapolation, cautioning that the leap from rodent studies to clinical therapeutics is arduous and fraught with pitfalls.

The therapeutic potential of microbiome science extends well beyond probiotics. Fecal microbiota transplantation (FMT)—the transfer of stool from a healthy donor to the gastrointestinal tract of a patient—has achieved remarkable success in treating recurrent Clostridioides difficile infections, which infest the gut when antibiotic therapy eliminates competing bacteria. FMT boasts cure rates exceeding ninety percent for this condition, a figure that has emboldened researchers to explore its application to other diseases. Preliminary trials investigating FMT for ulcerative colitis, metabolic syndrome, and even autism spectrum disorder have yielded mixed but tantalizing results. Yet the procedure is not without hazard: in 2019, two patients enrolled in a clinical trial contracted antibiotic-resistant infections from transplanted material, prompting the U.S. Food and Drug Administration to impose stringent screening protocols. The episode served as a sobering reminder that manipulating the microbiome is not a cinch—the ecosystem''s complexity means that interventions intended to remedy one imbalance can inadvertently create another.

Looking ahead, the field of microbiome research is poised to capitalize on advances in artificial intelligence and synthetic biology to develop precision therapies tailored to individual patients. Rather than administering generic probiotics whose efficacy is often banal, scientists envision engineering bespoke microbial consortia—custom-designed communities of bacteria optimized for a specific patient''s genetic profile, dietary habits, and disease state. Companies such as Seres Therapeutics and Vedanta Biosciences are already conducting late-stage clinical trials of defined microbial compositions for conditions ranging from inflammatory bowel disease to graft-versus-host disease. The prudence required to navigate the regulatory, ethical, and scientific complexities of this nascent field cannot be overstated. Yet the premise that animates the entire enterprise—that the key to conquering many of humanity''s most stubborn ailments may reside not in our own cells but in the teeming microbial world within us—represents a paradigm shift whose ramifications will reverberate through medicine for generations to come.',

'20世紀の大部分において、主流医学は人間の腸に生息する数兆の微生物を、良くて良性の乗客、悪ければ病気の最初の兆候で排除すべき潜在的病原体と見なしていた。この見方は劇的な変容を遂げた。ゲノムシーケンシングの進歩により、科学者たちは人間のマイクロバイオーム——体のほぼすべての表面に定着する細菌、ウイルス、真菌、古細菌の星座のような集合体——の驚くべき複雑さを解剖することが可能になり、浮かび上がってきた像は、これらの微視的な住人が単なるただ乗りではなく、人間の健康の極めて重要な設計者であることを示唆している。その意味するところはあまりにも広範であるため、一部の研究者は腸内マイクロバイオームをこれまで認識されていなかった臓器——その機能不全が肥満、うつ病、自己免疫疾患、さらには特定のがんに至るまで多様な状態の根底にある可能性がある臓器——として記述し始めている。

私たちの中の微生物生態系の規模は圧倒的である。成人の人体はおよそ38兆の細菌細胞を宿している——これは体内のヒト細胞の数をわずかに上回る数字である——そしてこれらの生物は集合的にヒトゲノムの約150倍の遺伝子をコードしている。この遺伝的豊かさにより、マイクロバイオームはヒトの細胞が自律的に実行できない代謝機能を遂行できる：必須ビタミンの合成、食物繊維の腸壁を養う短鎖脂肪酸への発酵、そして自己免疫疾患を特徴づける自己破壊的な過剰反応に逸れることなく真の脅威に対して警戒を維持するよう免疫系を調整すること。この精密に調整された生態系が乱れると——ディスバイオシスとして知られる状態——その結果は深刻になり得る。研究により、枯渇したまたは制御不能なマイクロバイオームを持つ個人は炎症性腸疾患、2型糖尿病、心血管疾患の発症率が上昇していることが記録されており、微生物の不均衡が単なる症状ではなく慢性疾患の病因における原因であることを示唆している。

腸内マイクロバイオームと精神的健康の関係は、現代生物学で最も挑発的なフロンティアの一つであることが証明されている。いわゆる腸脳軸——消化管の腸管神経系と中枢神経系を結ぶ双方向コミュニケーションネットワーク——は、腸内細菌が気分、認知、行動に影響を与えることができる解剖学的基盤を提供する。コーク大学で行われた画期的な研究は、微生物の定着がない無菌環境で育てられた無菌マウスが、従来通りに育てられた対照群と比較して、著しく高い不安様行動と誇張されたストレス反応を示すことを実証した。これらのマウスにその後特定の細菌株を定着させると、行動プロフィールは正常化した。ヒトでは、臨床試験により特定のプロバイオティクス——口語で「サイコバイオティクス」と呼ばれる——がコルチゾール反応の抑制と自己報告された気分の穏やかな改善をもたらしうることが示されているが、これらの効果の大きさは依然として議論の的である。批判者は性急な外挿に対して警告し、齧歯類の研究から臨床治療への飛躍は困難で落とし穴に満ちていると注意を促している。

マイクロバイオーム科学の治療的可能性はプロバイオティクスをはるかに超えて広がっている。糞便微生物叢移植（FMT）——健康なドナーの便を患者の消化管に移植すること——は、抗生物質療法が競合する細菌を排除した際に腸に蔓延する再発性クロストリディオイデス・ディフィシル感染症の治療で顕著な成功を収めている。FMTはこの疾患に対して90パーセントを超える治癒率を誇り、この数字は研究者を他の疾患への応用を探求するよう勇気づけた。潰瘍性大腸炎、メタボリックシンドローム、さらには自閉症スペクトラム障害に対するFMTを調査する予備的試験は、結果がまちまちだが魅力的な結果をもたらした。しかし、この処置は危険がないわけではない：2019年、臨床試験に登録された2人の患者が移植材料から抗生物質耐性感染症に感染し、米国食品医薬品局は厳格なスクリーニングプロトコルを課した。このエピソードは、マイクロバイオームの操作が容易ではないことの冷静な注意喚起となった——生態系の複雑さは、一つの不均衡を修正しようとする介入が不注意に別の不均衡を生み出しうることを意味する。

将来を見据えると、マイクロバイオーム研究の分野は人工知能と合成生物学の進歩を活用して個々の患者に合わせた精密治療を開発する態勢にある。有効性がしばしば平凡である汎用プロバイオティクスを投与するのではなく、科学者は特定の患者の遺伝的プロフィール、食習慣、疾患状態に最適化されたカスタム設計の細菌コミュニティであるオーダーメイドの微生物コンソーシアムを設計することを構想している。セレス・セラピューティクスやヴェダンタ・バイオサイエンシズなどの企業は、炎症性腸疾患から移植片対宿主病に至る疾患に対する定義された微生物組成の後期段階の臨床試験をすでに実施している。この生まれたばかりの分野の規制的、倫理的、科学的複雑さを乗り切るために必要な慎重さはいくら強調してもしすぎることはない。しかし、事業全体を活気づける前提——人類の最も頑固な疾患の多くを征服する鍵が私たち自身の細胞ではなく、私たちの中の溢れる微生物世界に存在するかもしれないということ——は、今後何世代にもわたって医学に響き渡るパラダイムシフトを表している。');

INSERT INTO passage_questions (id, passage_id, question_number, question_type, question_text, explanation, correct_choice) VALUES
(214, 72, 1, 'comprehension',
 'What does the passage suggest about the role of the gut microbiome in chronic disease?',
 '第2段落で、ディスバイオシス（微生物の不均衡）の状態にある個人は炎症性腸疾患、2型糖尿病、心血管疾患の発症率が上昇しており、微生物の不均衡は単なる症状ではなく慢性疾患の病因における原因であることが示唆されていると述べられている。選択肢1が正解。',
 1),
(215, 72, 2, 'comprehension',
 'According to the passage, what lesson did the 2019 FMT safety incident provide?',
 '第4段落で、2019年の事件について、マイクロバイオームの操作は容易ではなく、生態系の複雑さゆえに一つの不均衡を修正しようとする介入が別の不均衡を生み出しうるという冷静な注意喚起であったと述べられている。選択肢3が正解。',
 3),
(216, 72, 3, 'fill_in_blank',
 'Choose the best option to fill in the blank [BLANK] in the passage.',
 '空所は第3段落末尾にあり、サイコバイオティクスの効果の大きさが依然として何であるかを述べている。前文で効果が「modest」であることが述べられ、後文で批判者が性急な外挿に警告していることから、「活発な科学的議論」が最も適切。選択肢4が正解。',
 4);

INSERT INTO question_choices (question_id, choice_number, choice_text) VALUES
(214, 1, 'Microbial imbalance in the gut appears to function not merely as a symptom but as an active contributing factor in the development of various chronic illnesses.'),
(214, 2, 'Chronic diseases are caused exclusively by genetic predisposition, with the microbiome playing only a minor modulatory role in symptom severity.'),
(214, 3, 'The microbiome protects against chronic disease primarily by producing antibiotics that eliminate harmful pathogens before they can cause systemic inflammation.'),
(214, 4, 'Scientists have conclusively proven that restoring a healthy microbiome can reverse chronic conditions such as type 2 diabetes and cardiovascular disease.'),
(215, 1, 'Fecal transplantation should be permanently banned until synthetic alternatives that eliminate all risk of infection become commercially available.'),
(215, 2, 'The FDA''s existing screening protocols were already sufficient and required only minor administrative adjustments following the incident.'),
(215, 3, 'Manipulating the microbiome is inherently complex, and interventions designed to correct one problem can unintentionally introduce new risks.'),
(215, 4, 'Clinical trials involving human subjects should be replaced entirely by computational simulations that model microbiome interactions without physical risk.'),
(216, 1, 'commercial exploitation by pharmaceutical companies seeking to patent naturally occurring bacterial strains'),
(216, 2, 'regulatory scrutiny from government agencies that classify psychobiotics as unapproved psychiatric medications'),
(216, 3, 'ethical controversy surrounding the use of germ-free animal models in behavioral neuroscience research'),
(216, 4, 'vigorous scientific debate, with many experts urging caution about generalizing preliminary findings');

INSERT INTO passage_words (passage_id, word_id) SELECT 72, id FROM words WHERE word_number IN (406, 623, 503, 603, 690, 215, 446, 565, 395, 605, 249, 608, 629, 212, 415, 664, 639, 619, 580, 668, 663, 679);
