INSERT INTO passages (id, title, topic, word_range, content, content_ja) VALUES (85, 'The Cultural Politics of Architectural Preservation', '文化', '1~1000',
'When the Parisian authorities announced plans in the 1960s to demolish the cast-iron pavilions of Les Halles—the sprawling central market that had nourished the city for over eight centuries—the ensuing public outcry was as fervent as it was futile. Despite a barrage of petitions, impassioned editorials, and protests led by some of France''s most eminent intellectuals, the pavilions were razed between 1971 and 1973, replaced by a subterranean shopping complex widely lambasted as an architectural travesty. The destruction of Les Halles has since become a cautionary parable about the perils of cavalier attitudes toward architectural heritage, yet the questions it raised—What should be preserved? Who decides? And at what cost?—remain as contentious today as they were half a century ago.

The rationale for architectural preservation appears, on its surface, straightforward: historic buildings constitute tangible links to the past, embodying the craftsmanship, aesthetic sensibilities, and social values of the eras that produced them. A medieval cathedral, an Ottoman bathhouse, a Meiji-era railway station—each serves as a testament to a particular moment in human civilization. Yet the decision to preserve a building is never purely aesthetic or historical; it is invariably freighted with political significance. Colonial-era structures in formerly subjugated nations present an especially vexing quandary. In India, the fate of British Raj edifices—courthouses, railway terminals, administrative buildings that once epitomized imperial dominion—has provoked recurrent debate. Staunch nationalists advocate demolition, arguing that these structures perpetuate the stigma of colonial subjugation; others contend that preservation is imperative precisely because these buildings bear witness to a painful but incontrovertible chapter of national history. To obliterate them would be tantamount to expunging collective memory.

The economic dimensions of preservation further complicate an already murky landscape. Historic districts—from the quaint cobblestone lanes of Prague''s Old Town to the ornate merchant houses of Hội An in Vietnam—have proven extraordinarily adept at generating tourism revenue. Yet this very success can engender a paradox that preservation advocates have termed "heritage gentrification": as property values in historic areas escalate, longtime residents find themselves priced out, replaced by boutique hotels, artisanal cafés, and souvenir shops that cater exclusively to visitors. The neighborhood retains its architectural shell but forfeits the living community that once animated it. Venice offers perhaps the starkest illustration of this phenomenon: the city''s resident population has plummeted from roughly 175,000 in the 1950s to fewer than 50,000 today, even as annual tourist arrivals have surged past 30 million. Critics lament that Venice has been reduced to a lavish stage set—resplendent in its physical beauty but devoid of the quotidian human activity that constitutes the essence of a city.

Efforts to reconcile preservation with the needs of contemporary urban life have yielded a spectrum of approaches. At one end lies the fastidious restoration philosophy championed by organizations such as the Society for the Protection of Ancient Buildings, founded by William Morris in 1877, which insists that historic structures should be maintained in their original state with minimal intervention. At the opposite pole stands adaptive reuse—the practice of repurposing historic buildings for entirely new functions while preserving their exterior character. London''s Tate Modern, housed in a former power station, and Tokyo''s [BLANK] exemplify this approach, demonstrating that architectural heritage and contemporary utility need not be mutually exclusive. Between these poles, a growing number of practitioners advocate for what might be called "living preservation"—an approach that prioritizes the continuity of human habitation and community function over the meticulous conservation of physical fabric.

The future of architectural preservation will likely be shaped by two converging pressures. Climate change poses an existential threat to heritage sites worldwide: rising sea levels imperil Venice and countless coastal monuments, while increasingly sporadic but severe weather events batter structures that were never engineered to withstand such forces. Simultaneously, rapid urbanization in the developing world—where the imperative to house burgeoning populations often overrides heritage considerations—threatens to obliterate swaths of architectural history before they can even be catalogued, let alone protected. Navigating these challenges will require not only robust funding mechanisms and stringent legal frameworks but also a fundamental reappraisal of what preservation means in an era of perpetual change. The most resilient heritage, this emerging consensus suggests, will not be that which is hermetically sealed against the present but that which finds ways to remain pertinent to the communities it serves—adapting, evolving, and accruing new layers of meaning even as it honors the old.',

'1960年代にパリ当局がレ・アール——8世紀以上にわたって市を養ってきた広大な中央市場——の鋳鉄製パビリオンの取り壊し計画を発表したとき、それに続く世論の抗議は熱烈であると同時に無益であった。フランスの最も著名な知識人の一部が率いる嘆願書、情熱的な社説、抗議運動の集中攻撃にもかかわらず、パビリオンは1971年から1973年にかけて取り壊され、建築上の茶番として広く酷評された地下ショッピングコンプレックスに置き換えられた。レ・アールの破壊はその後、建築遺産に対するぞんざいな態度の危険性についての警告的な寓話となったが、それが提起した問い——何を保存すべきか？誰が決めるのか？そしてどのような代償で？——は半世紀前と同様に今日でも論争を呼んでいる。

建築保存の根拠は、表面上は明白に見える：歴史的建造物は過去への具体的なつながりを構成し、それらを生み出した時代の職人技、美的感覚、社会的価値を体現している。中世の大聖堂、オスマン帝国の浴場、明治時代の鉄道駅——それぞれが人類文明の特定の瞬間への証言として機能している。しかし建物を保存する決定は純粋に美学的または歴史的であることはなく、不可避的に政治的重要性を帯びている。かつて支配された国々の植民地時代の建造物は、特に悩ましい困惑を呈する。インドでは、英国統治時代の建造物——かつて帝国の支配を典型的に表した裁判所、鉄道ターミナル、行政建築物——の運命が繰り返し議論を引き起こしてきた。頑固な国家主義者たちは取り壊しを主張し、これらの構造物が植民地支配の烙印を永続させると論じる。他の者たちは、これらの建物が国史の苦痛に満ちたしかし議論の余地のない章を証言しているからこそ保存が不可欠であると主張する。それらを抹消することは集合的記憶を消し去ることに等しいだろう。

保存の経済的側面は、すでに不透明な状況をさらに複雑にしている。歴史地区——プラハ旧市街の趣のある石畳の小路からベトナムのホイアンの装飾的な商家まで——は観光収入を生み出すことに驚くほど熟練していることが証明されている。しかしまさにこの成功が、保存の支持者たちが「遺産のジェントリフィケーション」と呼ぶパラドックスを生み出しうる：歴史的地域の不動産価値が上昇するにつれ、長年の住民は追い出され、訪問者専用のブティックホテル、職人カフェ、土産物店に置き換えられる。地区はその建築的外殻を保持するが、かつてそれに命を吹き込んだ生きたコミュニティを失う。ベネチアはおそらくこの現象の最も鮮明な例示を提供する：市の居住者人口は1950年代の約17万5千人から今日では5万人未満に急落しているが、年間の観光客到着数は3千万人を超えて急増している。批評家たちはベネチアが豪華な舞台装置——物理的な美しさにおいてはきらびやかだが、都市の本質を構成する日常の人間活動が欠如している——に矮小化されたと嘆いている。

保存と現代の都市生活のニーズとの調和を図る取り組みは、様々なアプローチを生み出してきた。一方の端には、1877年にウィリアム・モリスが設立した古建築保護協会などの組織が擁護する、最小限の介入で歴史的構造物を元の状態に維持すべきだと主張する細心の注意を払った修復哲学がある。対極には、歴史的建物の外観の特徴を保存しながら全く新しい機能に転用する実践であるアダプティブ・リユースがある。元の発電所に収容されたロンドンのテート・モダンや東京の同様の事例はこのアプローチを例証しており、建築遺産と現代の実用性が相互に排他的である必要はないことを実証している。これらの両極の間で、増加する実践者たちは「生きた保存」と呼びうるもの——物理的構造の細心の保存よりも人間の居住とコミュニティ機能の継続性を優先するアプローチ——を提唱している。

建築保存の将来はおそらく2つの収束する圧力によって形作られるだろう。気候変動は世界中の遺産サイトに存続的脅威をもたらしている：海面上昇はベネチアと無数の沿岸記念碑を危険にさらし、一方でますます散発的だが深刻な気象イベントがそのような力に耐えるよう設計されなかった構造物を打ちつけている。同時に、発展途上国における急速な都市化——急増する人口を収容する要請がしばしば遺産の考慮事項に優先する——は、建築史の広大な部分が目録化される前に、ましてや保護される前に抹消される脅威をもたらしている。これらの課題を乗り越えるには、強固な資金メカニズムと厳格な法的枠組みだけでなく、永久的な変化の時代における保存の意味の根本的な再評価も必要となるだろう。最も回復力のある遺産は、この新たな合意が示唆するように、現在から密封されたものではなく、古いものを敬いながら適応し、進化し、新たな意味の層を蓄積しながら、それが奉仕するコミュニティに関連性を保ち続ける方法を見出すものであろう。');

INSERT INTO passage_questions (id, passage_id, question_number, question_type, question_text, explanation, correct_choice) VALUES
(253, 85, 1, 'comprehension',
 'What does the passage suggest about the preservation of colonial-era buildings in formerly colonized nations?',
 '第2段落で、インドにおける英国統治時代の建造物をめぐる議論が述べられている。国家主義者は植民地支配の烙印を永続させるとして取り壊しを主張し、他方は苦痛だが否定できない歴史の証人として保存が不可欠だと主張する。選択肢1が正解。',
 1),
(254, 85, 2, 'comprehension',
 'According to the passage, what is the central problem with the economic success of historic district preservation, as illustrated by Venice?',
 '第3段落で、歴史地区の不動産価値上昇により長年の住民が追い出され、建築的外殻は残るが生きたコミュニティが失われる「遺産のジェントリフィケーション」の問題が述べられ、ベネチアの人口急減が例示されている。選択肢3が正解。',
 3),
(255, 85, 3, 'fill_in_blank',
 'Choose the best option to fill in the blank [BLANK] in the passage.',
 '空所は第4段落にあり、ロンドンのテート・モダンと並列して、東京における歴史的建物のアダプティブ・リユースの事例を述べる部分。歴史的建造物を現代的な文化施設に転用した例が文脈に合う。選択肢4が正解。',
 4);

INSERT INTO question_choices (question_id, choice_number, choice_text) VALUES
(253, 1, 'The issue is deeply divisive, with some arguing that such buildings perpetuate the stigma of subjugation while others maintain that their preservation is essential for acknowledging an undeniable chapter of history.'),
(253, 2, 'International law requires formerly colonized nations to preserve all colonial-era structures as part of their obligations under UNESCO World Heritage conventions.'),
(253, 3, 'Most formerly colonized nations have reached a consensus that colonial buildings should be repurposed as museums documenting the abuses of imperial rule.'),
(253, 4, 'Colonial-era buildings are universally regarded as architectural masterpieces whose aesthetic value transcends their political associations.'),
(254, 1, 'The cost of maintaining historic buildings has risen so dramatically that municipal governments can no longer afford basic maintenance without imposing steep entrance fees on tourists.'),
(254, 2, 'Tourism revenue has been monopolized by international hotel chains, leaving local governments without the funds needed to enforce preservation regulations.'),
(254, 3, 'Rising property values driven by tourism displace longtime residents, leaving historic neighborhoods physically intact but stripped of the living communities that once gave them vitality.'),
(254, 4, 'The sheer volume of tourists has caused irreversible physical damage to historic structures, with foot traffic eroding stone facades and wooden floors beyond repair.'),
(255, 1, 'meticulous reconstruction of Edo-period wooden townhouses using traditional joinery techniques passed down through generations of master carpenters'),
(255, 2, 'controversial decision to relocate a historic Shinto shrine to make way for a commercial development project in the city center'),
(255, 3, 'ambitious program to digitally scan and archive every pre-war building in the metropolitan area before permitting any renovation or demolition'),
(255, 4, 'conversion of a historic warehouse district into contemporary cultural and commercial spaces while retaining the original brick facades');

INSERT INTO passage_words (passage_id, word_id) SELECT 85, id FROM words WHERE word_number IN (51, 180, 478, 88, 929, 199, 147, 168, 638, 76, 62, 96, 202, 273, 835, 869, 118, 131, 913, 13, 264, 117, 838, 462, 130, 724, 110, 103, 354, 432, 616, 841, 784, 401, 343);
