INSERT INTO passages (id, title, topic, word_range, content, content_ja) VALUES (62, 'Deepfakes, Disinformation, and the Erosion of Public Trust', 'メディア', '1~700',
'In January 2023, a video surfaced on social media that appeared to show a prominent European head of state announcing an immediate withdrawal from a major defense alliance. Within hours, the clip had been shared millions of times, provoking frantic responses from diplomatic channels and prompting financial markets to swerve sharply downward. The footage was, in fact, a deepfake—a synthetic media artifact generated by artificial intelligence—and although fact-checkers managed to apprehend the deception within a day, the episode underscored a disquieting reality: the technology to fabricate convincing audiovisual falsehoods has outpaced society''s capacity to detect and contain them, placing the very premise of evidentiary truth in jeopardy.

Deepfake technology relies on generative adversarial networks, or GANs, a class of machine-learning architecture in which two neural networks engage in a kind of adversarial duel. One network generates counterfeit images or audio, while the other attempts to distinguish the fabrications from authentic material; through iterative refinement, the generator''s output becomes increasingly indistinguishable from reality. The pivotal breakthrough came in 2014, when the computer scientist Ian Goodfellow introduced the GAN framework at the University of Montreal. What began as an arcane research curiosity has since proliferated into consumer-grade applications that allow even a novice user to produce deepfake videos with minimal technical expertise. The democratization of this capability, while yielding legitimate applications in entertainment and education, has simultaneously created an insatiable supply of tools for those with ulterior motives.

The implications for democratic governance are particularly alarming. Political operatives can now deploy deepfakes to demoralize opponents, fabricate scandalous confessions, or orchestrate disinformation campaigns timed to coincide with elections—a period when the electorate is most vulnerable to manipulation. In 2019, a deepfake audio clip of Gabonese President Ali Bongo, circulated during a period of political instability, was widely believed to have goaded elements within the military toward an attempted coup. Researchers at the Oxford Internet Institute have documented how state-sponsored actors in at least seventy countries have honed their disinformation capabilities, and deepfakes represent the latest and most potent weapon in this arsenal. The arduous task of distinguishing genuine footage from synthetic fabrications falls disproportionately on journalists and fact-checkers, who often lack the resources to keep pace with the relentless output of AI-generated content.

Beyond politics, deepfakes have begun to infest the domains of personal reputation and financial fraud. Criminals have used the technology to impersonate corporate executives on video calls, coaxing subordinates into authorizing large wire transfers—a scam that, in one widely reported case in Hong Kong in 2024, netted approximately twenty-five million dollars. Victims of non-consensual deepfake pornography, overwhelmingly women, find their likenesses weaponized in ways that are profoundly mortifying and psychologically devastating, yet legal frameworks in most jurisdictions remain slack in addressing such abuses. The lurid nature of these violations has prompted advocacy groups to canvass legislators for more robust protections, but progress has been incremental at best, [BLANK].

Several countermeasures are under development. Technology companies have invested in digital provenance systems, such as the Coalition for Content Provenance and Authenticity (C2PA), which affix cryptographic metadata to media files at the point of creation, enabling viewers to verify a file''s origin and detect subsequent tampering. Meanwhile, academic researchers are honing detection algorithms that analyze subtle artifacts—inconsistencies in blinking patterns, lighting anomalies, or incoherent audio-visual synchronization—that betray synthetic manipulation. Legislative bodies have also begun to act: the European Union''s AI Act, finalized in 2024, includes explicit provisions requiring the labeling of AI-generated content, while several U.S. states have enacted statutes criminalizing the malicious use of deepfakes.

Yet technology and legislation alone cannot quench the threat. The ultimate antidote may lie in cultivating a more discerning public—one that approaches viral content with prudence rather than credulity, and that regards media literacy not as a peripheral educational amenity but as a prerequisite for informed citizenship in the digital age. Until such a culture of critical engagement takes root, the deepfake menace will continue to brew, testing the resilience of democratic institutions and the fabric of shared reality itself.',

'2023年1月、ある著名な欧州の国家元首が主要な防衛同盟からの即時離脱を発表しているように見える動画がソーシャルメディアに浮上した。数時間以内にこのクリップは何百万回も共有され、外交チャンネルから必死の反応を引き起こし、金融市場を急落させた。その映像は実際にはディープフェイク——人工知能によって生成された合成メディアの産物——であり、ファクトチェッカーたちが一日以内にこの欺瞞を見抜くことに成功したものの、このエピソードは不安にさせる現実を浮き彫りにした。説得力のある視聴覚的虚偽を捏造する技術が、それを検知し封じ込める社会の能力を上回っており、証拠的真実の前提そのものを危機に晒しているのである。

ディープフェイク技術は敵対的生成ネットワーク（GAN）に依存している。これは二つのニューラルネットワークが一種の敵対的決闘を行う機械学習アーキテクチャの一種である。一方のネットワークが偽造の画像や音声を生成し、もう一方がその捏造物を本物の素材から見分けようとする。反復的な改良を通じて、生成器の出力は現実とますます区別がつかなくなる。画期的な突破口は2014年、コンピュータ科学者のイアン・グッドフェローがモントリオール大学でGANフレームワークを発表した時に訪れた。難解な研究上の好奇心として始まったものは、その後、初心者のユーザーでも最小限の技術的専門知識でディープフェイク動画を制作できる消費者向けアプリケーションへと増殖した。この能力の民主化は、エンターテインメントや教育における正当な応用を生み出す一方で、裏の動機を持つ者たちのためのツールの飽くなき供給をも同時に生み出した。

民主的統治への影響は特に憂慮すべきものである。政治工作員はディープフェイクを展開して対立候補の士気を挫き、スキャンダラスな告白を捏造し、選挙——有権者が操作に最も脆弱な時期——に合わせた偽情報キャンペーンを画策することができる。2019年、政治的不安定の時期に流布されたガボンのアリ・ボンゴ大統領のディープフェイク音声クリップは、軍内の一部の勢力をクーデター未遂に駆り立てたと広く信じられた。オックスフォード・インターネット研究所の研究者たちは、少なくとも70カ国で国家が後援する行為者がいかに偽情報能力を磨いてきたかを記録しており、ディープフェイクはこの兵器庫の最新かつ最も強力な武器を代表する。本物の映像と合成の捏造物を区別するという骨の折れる仕事は、AI生成コンテンツの容赦ない出力に追いつくためのリソースをしばしば欠くジャーナリストやファクトチェッカーに不釣り合いに降りかかっている。

政治を超えて、ディープフェイクは個人の評判や金融詐欺の領域にも蔓延し始めている。犯罪者はこの技術を使ってビデオ通話で企業幹部になりすまし、部下を巧みに説得して大規模な電信送金を承認させてきた——2024年に香港で広く報道された事例では、約2500万ドルを騙し取った。非同意のディープフェイクポルノの被害者（圧倒的に女性）は、深く屈辱的で心理的に壊滅的な方法で自分の肖像が武器化されていることに気づくが、ほとんどの管轄区域の法的枠組みはそのような濫用への対処において緩いままである。これらの侵害の扇情的な性質は、擁護団体が議員に対してより堅固な保護を求めて働きかけることを促してきたが、進展はせいぜい漸進的であり、技術の急速な進歩が立法上の対応を絶えず追い越している。

いくつかの対抗策が開発中である。テクノロジー企業はデジタル来歴システムに投資しており、例えばコンテンツ来歴・真正性連合（C2PA）は、作成時点でメディアファイルに暗号メタデータを添付し、視聴者がファイルの出所を確認し、その後の改ざんを検出できるようにする。一方、学術研究者たちは、合成操作を暴露する微妙な痕跡——まばたきパターンの不整合、照明の異常、音声・映像の非整合性——を分析する検出アルゴリズムを磨いている。立法機関も行動を起こし始めている。2024年に最終決定された欧州連合のAI法には、AI生成コンテンツのラベリングを義務付ける明示的な規定が含まれており、米国のいくつかの州はディープフェイクの悪意ある使用を犯罪化する法令を制定した。

しかし、技術と法律だけではこの脅威を消し去ることはできない。究極的な解毒剤は、より目の利く公衆——バイラルコンテンツに対して軽信ではなく慎重さをもって臨み、メディアリテラシーを周辺的な教育上の便宜としてではなくデジタル時代における情報に基づく市民性の前提条件とみなす公衆——を育むことにあるかもしれない。そのような批判的関与の文化が根付くまで、ディープフェイクの脅威は醸成を続け、民主的制度の回復力と共有された現実そのものの構造を試し続けるだろう。');

INSERT INTO passage_questions (id, passage_id, question_number, question_type, question_text, explanation, correct_choice) VALUES
(184, 62, 1, 'comprehension',
 'According to the passage, what has been a significant consequence of the democratization of deepfake technology?',
 '第2段落で、GAN技術がイアン・グッドフェローによって2014年に発表され、当初は難解な研究上の好奇心だったものが消費者向けアプリケーションに増殖し、初心者でもディープフェイク動画を制作できるようになったと述べられている。これにより、正当な応用と同時に裏の動機を持つ者のためのツールの供給も生まれた。選択肢3がこの内容に合致する。',
 3),
(185, 62, 2, 'comprehension',
 'What does the passage suggest about the legal response to non-consensual deepfake pornography?',
 '第4段落で、非同意のディープフェイクポルノの被害者は深く屈辱的な方法で肖像が武器化されているが、ほとんどの管轄区域の法的枠組みはそのような濫用への対処において緩いままであり、擁護団体が議員に働きかけているものの進展はせいぜい漸進的であると述べられている。選択肢1がこの内容に合致する。',
 1),
(186, 62, 3, 'fill_in_blank',
 'Choose the best option to fill in the blank [BLANK] in the passage.',
 '空所は第4段落の末尾にあり、法的保護の進展が漸進的であるという文脈の後に続く。技術の急速な進歩が立法上の対応を絶えず追い越しているという内容が最も自然に接続する。選択肢2が正解。',
 2);

INSERT INTO question_choices (question_id, choice_number, choice_text) VALUES
(184, 1, 'It has enabled governments to develop more effective surveillance systems capable of monitoring potential threats in real time.'),
(184, 2, 'It has encouraged traditional media outlets to abandon video journalism in favor of text-based reporting to avoid credibility issues.'),
(184, 3, 'It has made sophisticated fabrication tools accessible to ordinary users, creating both legitimate applications and an abundant supply of instruments for malicious actors.'),
(184, 4, 'It has prompted all major social media platforms to implement mandatory identity verification for every uploaded video.'),
(185, 1, 'Legal frameworks in most jurisdictions remain inadequate to address such abuses, and despite advocacy efforts, legislative progress has been slow and insufficient.'),
(185, 2, 'Comprehensive international legislation has already been enacted, but enforcement remains inconsistent across different jurisdictions.'),
(185, 3, 'Courts have consistently ruled that deepfake pornography falls under existing defamation statutes, making new legislation unnecessary.'),
(185, 4, 'Victims have found effective recourse through civil litigation, which has compensated them fully for the psychological damage suffered.'),
(186, 1, 'largely because the general public has shown little interest in supporting such measures'),
(186, 2, 'as the rapid pace of technological advancement continually outstrips legislative responses'),
(186, 3, 'primarily because technology companies have lobbied aggressively against any form of regulation'),
(186, 4, 'since most democratic governments have chosen to prioritize economic growth over digital safety concerns');

INSERT INTO passage_words (passage_id, word_id) SELECT 62, id FROM words WHERE word_number IN (613, 411, 210, 619, 626, 545, 689, 658, 687, 87, 611, 682, 513, 608, 680, 212, 453, 328, 555, 417, 422, 614, 692, 229, 625, 639, 566, 632, 601, 624);
