INSERT INTO passages (id, title, topic, word_range, content, content_ja) VALUES (64, 'The Berlin Conference and the Partition of Africa', '歴史', '1~700',
'In November 1884, representatives of fourteen nations convened in Berlin at the invitation of German Chancellor Otto von Bismarck to settle competing European claims to African territory. The conference, which adjourned in late February 1885, produced a document known as the General Act of the Berlin Conference—a set of provisions that would, in retrospect, serve as the blueprint for one of history''s most consequential acts of territorial appropriation. No African leaders were invited, no African voices were consulted, and the borders that emerged bore no relation to the ethnic, linguistic, or cultural configurations that had governed the continent for millennia. The proceedings typified a form of imperial arrogance so brazen that even contemporaries with a penchant for colonial expansion found certain aspects disquieting, yet the great powers pressed forward, each faction maneuvering to secure the largest possible share of a continent whose riches they regarded as theirs to claim.

The immediate catalyst for the conference was the scramble that had erupted along the Congo River basin. King Leopold II of Belgium, operating through the nominally philanthropic International Association of the Congo, had begun to annex vast tracts of territory in Central Africa, provoking alarm among rival colonial powers—particularly France and Portugal—who feared that their own ambitions would be negated. Bismarck, whose ulterior motive was to divert French attention from the loss of Alsace-Lorraine in the Franco-Prussian War and to foster antagonistic rivalries among other European powers, seized the juncture to position Germany as an ostensibly neutral arbiter. The conference established the principle of "effective occupation," stipulating that a European power could claim African territory only if it maintained a sufficient administrative and military presence there. Far from curbing the scramble, this provision goaded the imperial powers into an even more frantic race to establish outposts, and within two decades virtually the entire African continent had been carved into European colonies or spheres of influence.

The human cost of partition was staggering and remains a source of enduring grievance across the continent. In the Congo Free State, which Leopold administered as his personal fiefdom, the relentless extraction of rubber and ivory was enforced through a regime of terror that included the confiscation of harvests, the imposition of punitive labor quotas, and the amputation of hands as punishment for failing to meet production targets. Historians estimate that the population of the Congo basin declined by approximately ten million people between 1885 and 1908—a conflagration of suffering that the journalist E. D. Morel and the diplomat Roger Casement brought to international attention through their ardent campaigning, ultimately compelling the Belgian parliament to strip Leopold of his personal control in 1908. Elsewhere, the arbitrary borders drawn at Berlin [BLANK]. The Maasai were divided between British Kenya and German Tanganyika; the Somali people were parceled among British, French, Italian, and Ethiopian jurisdictions. These divisions sowed the seeds of conflicts that would erupt with devastating force in the postcolonial era.

The economic legacy of the Berlin Conference is no less profound. Colonial administrations restructured African economies to serve metropolitan interests, establishing monoculture plantations and extractive industries that rendered local populations destitute and dependent on volatile global commodity markets. Infrastructure—railways, ports, roads—was built not to facilitate internal trade or the regeneration of local economies but to expedite the movement of raw materials from the interior to coastal ports for export. This pattern of economic subordination proved remarkably resistant to the formal end of colonial rule; even after the spate of independence movements that swept the continent in the 1950s and 1960s, many newly sovereign nations found themselves locked into trade relationships that perpetuated the exploitative dynamics of the colonial era. The reparations debate, which has gained renewed momentum in the twenty-first century, draws explicitly on this history, with adherents arguing that the wealth extracted from Africa during the colonial period constitutes an unpaid debt that former colonial powers are morally and legally liable to settle.

The Berlin Conference also bequeathed a cartographic legacy whose consequences continue to reverberate. Approximately forty-four percent of African borders follow lines of latitude or longitude—straight lines drawn with rulers on European maps, oblivious to the human realities on the ground. Scholars such as the economist Alberto Alesina have demonstrated a statistically significant correlation between the artificiality of national borders and the incidence of ethnic conflict in postcolonial states, a finding that underscores the enduring damage inflicted by decisions made in a Berlin conference hall more than a century ago. The turbulent history of states such as Nigeria, Sudan, and the Democratic Republic of the Congo cannot be understood without reference to the arbitrary partitions that fractured preexisting polities and forced disparate communities into uneasy coexistence.

In the final analysis, the Berlin Conference stands as a stark testament to the destructive potential of imperial hubris exercised without accountability. Its legacy is not merely historical but urgently contemporary, shaping patterns of poverty, conflict, and political instability that afflict the African continent to this day.',

'1884年11月、ドイツ首相オットー・フォン・ビスマルクの招きにより、14カ国の代表がベルリンに集まり、アフリカ領土に対する競合するヨーロッパの権利主張を解決しようとした。1885年2月下旬に閉会したこの会議は、ベルリン会議一般議定書として知られる文書を生み出した——振り返ってみれば、歴史上最も重大な領土占有行為の一つの青写真として機能することになる一連の規定である。アフリカの指導者は一人も招かれず、アフリカの声は一切聴取されず、出現した国境は数千年にわたって大陸を統治してきた民族的、言語的、文化的構成とは何の関係もなかった。この議事は、植民地拡大への好みを持つ同時代人でさえ特定の側面を不安に感じるほど厚かましい帝国的傲慢さの一形態を象徴していたが、列強は前進し続け、各派閥はその富を自分たちのものとして主張する権利があると見なす大陸の可能な限り最大の取り分を確保しようと策謀した。

会議の直接的な触媒は、コンゴ川流域で勃発していた争奪戦であった。ベルギーのレオポルド2世は、名目上は慈善的なコンゴ国際協会を通じて中央アフリカの広大な領土を併合し始めており、ライバルの植民地大国——特にフランスとポルトガル——の間に自国の野心が否定されるのではないかという警戒を引き起こした。普仏戦争でのアルザス＝ロレーヌ喪失からフランスの注意をそらし、他のヨーロッパ列強間の敵対的な対立を助長するという裏の動機を持つビスマルクは、この重大な時点を捉えてドイツを表面上は中立な仲裁者として位置づけた。会議は「実効支配」の原則を確立し、ヨーロッパの列強がアフリカの領土を主張できるのは、そこに十分な行政的・軍事的存在を維持している場合に限ると規定した。この規定は争奪戦を抑制するどころか、帝国列強をさらに必死のレースへと駆り立て、20年以内にアフリカ大陸のほぼ全体がヨーロッパの植民地または勢力圏に分割された。

分割の人的コストは驚異的であり、大陸全体にわたって今なお続く不満の源となっている。レオポルドが個人的な封土として統治したコンゴ自由国では、ゴムと象牙の容赦ない搾取が、収穫物の没収、懲罰的な労働割当の賦課、生産目標を達成できなかった場合の罰としての手の切断を含む恐怖政治によって施行された。歴史家たちは、コンゴ盆地の人口が1885年から1908年の間に約1000万人減少したと推定している——ジャーナリストのE・D・モレルと外交官のロジャー・ケースメントが熱心な運動を通じて国際的な注目を集め、最終的にベルギー議会にレオポルドの個人的支配を剥奪させた苦難の大火である。他の地域では、ベルリンで引かれた恣意的な国境が既存の民族的・文化的つながりを分断し、何世紀にもわたって交流を維持してきたコミュニティを切り離した。マサイ族はイギリス領ケニアとドイツ領タンガニーカに分割され、ソマリ人はイギリス、フランス、イタリア、エチオピアの管轄区域に分配された。これらの分割は、ポスト植民地時代に壊滅的な力で噴出する紛争の種をまいた。

ベルリン会議の経済的遺産はそれに劣らず深い。植民地行政はアフリカの経済を本国の利益に奉仕するよう再構築し、単一栽培プランテーションと採取産業を設立して、地元住民を困窮させ、不安定な世界商品市場に依存させた。インフラ——鉄道、港湾、道路——は内部貿易や地域経済の再生を促進するためではなく、原材料を内陸から輸出用の沿岸港へ迅速に移動させるために建設された。この経済的従属のパターンは、植民地支配の公式な終了に対して驚くほど強靱であった。1950年代と1960年代に大陸を席巻した一連の独立運動の後でさえ、多くの新たに主権を得た国家は植民地時代の搾取的力学を永続させる貿易関係に固定されていた。21世紀に新たな勢いを得ている賠償問題は、この歴史に明示的に依拠しており、支持者たちは植民地時代にアフリカから搾取された富が旧宗主国が道義的・法的に清算する義務を負う未払いの債務を構成すると主張している。

ベルリン会議はまた、その結果が今なお反響し続ける地図上の遺産を遺した。アフリカの国境のおよそ44パーセントは緯度線または経度線に沿っている——ヨーロッパの地図上で定規を使って引かれた直線であり、現場の人間的現実に無頓着であった。経済学者のアルベルト・アレシーナなどの学者は、国境の人工性とポスト植民地国家における民族紛争の発生率との間に統計的に有意な相関があることを実証しており、この発見は1世紀以上前のベルリンの会議場でなされた決定が与えた永続的な損害を浮き彫りにしている。ナイジェリア、スーダン、コンゴ民主共和国などの国家の激動の歴史は、既存の政体を分裂させ、異なるコミュニティを不安な共存へと強制した恣意的な分割に言及することなしには理解できない。

最終的な分析において、ベルリン会議は説明責任なしに行使された帝国的傲慢の破壊的な潜在力に対する鮮烈な証として立っている。その遺産は単に歴史的なものではなく緊急に現代的であり、今日に至るまでアフリカ大陸を苦しめている貧困、紛争、政治的不安定のパターンを形成している。');

INSERT INTO passage_questions (id, passage_id, question_number, question_type, question_text, explanation, correct_choice) VALUES
(190, 64, 1, 'comprehension',
 'What was Bismarck''s strategic purpose in convening the Berlin Conference, according to the passage?',
 '第2段落で、ビスマルクの裏の動機は普仏戦争でのアルザス＝ロレーヌ喪失からフランスの注意をそらし、他のヨーロッパ列強間の敵対的な対立を助長することであり、ドイツを表面上は中立な仲裁者として位置づけたと述べられている。選択肢1がこの内容に合致する。',
 1),
(191, 64, 2, 'comprehension',
 'How does the passage characterize the economic legacy of colonial rule in Africa?',
 '第4段落で、植民地行政がアフリカの経済を本国の利益のために再構築し、インフラは内部貿易ではなく原材料の輸出のために建設され、独立後も搾取的な貿易関係が継続したと述べられている。選択肢3がこの内容に合致する。',
 3),
(192, 64, 3, 'fill_in_blank',
 'Choose the best option to fill in the blank [BLANK] in the passage.',
 '空所は第3段落にあり、ベルリンで引かれた恣意的な国境の影響を説明する文脈に入る。その後にマサイ族やソマリ人の具体例が続くことから、既存の民族的・文化的つながりを分断したという内容が最も適切。選択肢4が正解。',
 4);

INSERT INTO question_choices (question_id, choice_number, choice_text) VALUES
(190, 1, 'He sought to divert French attention from its territorial losses in the Franco-Prussian War and to encourage rivalries among other European powers, positioning Germany as a seemingly impartial mediator.'),
(190, 2, 'He aimed to establish Germany as the dominant colonial power in Africa by securing exclusive trading rights throughout the Congo basin.'),
(190, 3, 'He intended to forge a pan-European alliance against Ottoman expansion into North Africa, using the conference as a platform for military coordination.'),
(190, 4, 'He wanted to demonstrate Germany''s commitment to African self-governance by proposing the establishment of autonomous administrative zones across the continent.'),
(191, 1, 'Colonial powers invested heavily in education and healthcare infrastructure, creating a foundation for economic growth that unfortunately collapsed during decolonization.'),
(191, 2, 'The economic structures established during colonialism were quickly dismantled after independence, allowing African nations to develop self-sustaining economies within a generation.'),
(191, 3, 'Colonial administrations restructured economies for metropolitan benefit, building export-oriented infrastructure, and this pattern of subordination persisted well beyond formal independence.'),
(191, 4, 'European colonial powers deliberately industrialized African territories to create new consumer markets, but these industries became obsolete after independence.'),
(192, 1, 'created opportunities for previously isolated communities to form new political alliances based on shared economic interests'),
(192, 2, 'were largely corrected during the period of decolonization as new African leaders redrew boundaries along ethnic lines'),
(192, 3, 'prompted immediate resistance movements that succeeded in preserving most preexisting territorial arrangements'),
(192, 4, 'severed preexisting ethnic and cultural bonds, separating communities that had maintained ties for centuries');

INSERT INTO passage_words (passage_id, word_id) SELECT 64, id FROM words WHERE word_number IN (533, 656, 301, 542, 113, 548, 87, 259, 525, 661, 513, 613, 238, 191, 674, 607, 680, 606, 651, 604, 646, 243, 598, 618, 198, 609, 621, 638, 615);
