-- words テーブル INSERT文 (No.1001 ~ No.1050)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1001, 'multitude', '多数の;(力を持たない)大衆、群衆', '/ˈmʌltɪtjuːd/', 'マルティテュード',
  'A multitude of factors contributed to the economic downturn.',
  '多数の要因が景気後退の一因となった。',
  'The politician addressed the assembled multitude in the town square.',
  'その政治家は広場に集まった大衆に向かって演説した。'),
(1002, 'supplant', '(古いもの・人)に取って代わる', '/səˈplænt/', 'サプラント',
  'Digital technology has largely supplanted traditional film photography.',
  'デジタル技術は従来のフィルム写真にほぼ取って代わった。',
  'The new CEO supplanted his predecessor after a dramatic boardroom coup.',
  '新しいCEOは劇的な役員会クーデターの後、前任者に取って代わった。'),
(1003, 'imminent', '(悪いことが)差し迫った、切迫した', '/ˈɪmɪnənt/', 'イミネント',
  'With dark clouds gathering, a violent storm seemed imminent.',
  '暗雲が立ち込め、激しい嵐が差し迫っているようだった。',
  'The government warned that an imminent threat to national security had been detected.',
  '政府は国家安全保障に対する差し迫った脅威が検知されたと警告した。'),
(1004, 'wrangle', '言い争う、口げんかをする', '/ˈræŋɡl/', 'ラングル',
  'The two parties continued to wrangle over the terms of the agreement.',
  '両者は合意の条件をめぐって言い争い続けた。',
  'Lawmakers wrangled for hours before reaching a compromise on the budget.',
  '議員たちは予算の妥協案に達するまで何時間も口げんかをした。'),
(1005, 'scour', '(場所・書類など)をくまなく調べる、探し回る', '/ˈskaʊər/', 'スカウアー',
  'Detectives scoured the crime scene for any trace of evidence.',
  '刑事たちは犯行現場をくまなく調べ、証拠の痕跡を探した。',
  'She scoured countless documents to find proof of the financial fraud.',
  '彼女は金融詐欺の証拠を見つけるため、無数の書類をくまなく調べた。'),
(1006, 'threshold', '(新しいものの)出発点、発端;戸口、敷居;(何かが起きる・変化する)限界点;閾', '/ˈθreʃhoʊld/', 'スレッショウルド',
  'The country stands on the threshold of a new era in renewable energy.',
  'その国は再生可能エネルギーの新時代の出発点に立っている。',
  'Once pollution levels exceed a certain threshold, irreversible damage occurs.',
  '汚染レベルがある限界点を超えると、不可逆的な損害が生じる。'),
(1007, 'dividend', '(株式の)配当', '/ˈdɪvɪdend/', 'ディヴィデンド',
  'The company announced a generous dividend for its shareholders.',
  'その会社は株主に対する手厚い配当を発表した。',
  'Investors were disappointed when the firm decided to slash its annual dividend.',
  '企業が年間配当の大幅削減を決定し、投資家たちは失望した。'),
(1008, 'pundit', '(ある分野の)評論家、専門家、有識者', '/ˈpʌndɪt/', 'パンディット',
  'Political pundits predicted a landslide victory for the ruling party.',
  '政治評論家たちは与党の地滑り的勝利を予測した。',
  'Many economic pundits failed to foresee the severity of the recession.',
  '多くの経済専門家がその不況の深刻さを予見できなかった。'),
(1009, 'incubate', '(卵)を抱く、ふ化させる', '/ˈɪŋkjubeɪt/', 'インキュベイト',
  'The hen incubated her eggs for twenty-one days before they hatched.',
  'めんどりは卵がかえるまで21日間抱いた。',
  'The university established a program to incubate promising start-up ventures.',
  'その大学は有望なスタートアップ事業をふ化させるプログラムを設立した。'),
(1010, 'attrition', '(人員などの)自然減;消耗、損耗', '/əˈtrɪʃən/', 'アトリション',
  'The company reduced its workforce through attrition rather than layoffs.',
  'その会社は解雇ではなく自然減によって従業員数を削減した。',
  'The prolonged war of attrition exhausted both armies beyond recovery.',
  '長引く消耗戦は両軍を回復不能なまでに疲弊させた。'),
(1011, 'incense', '(人)を激怒させる', '/ɪnˈsens/', 'インセンス',
  'The politician''s callous remarks incensed the victims'' families.',
  'その政治家の冷淡な発言は被害者の遺族を激怒させた。',
  'Residents were incensed by the proposal to build a waste facility in their neighborhood.',
  '住民たちは近隣に廃棄物処理施設を建設する提案に激怒した。'),
(1012, 'poach', '(~を)密猟する、密漁する', '/poʊtʃ/', 'ポウチ',
  'Rangers patrol the reserve around the clock to prevent criminals from poaching elephants.',
  'レンジャーたちは犯罪者による象の密猟を防ぐため、保護区を24時間巡回している。',
  'The fisherman was arrested for poaching salmon from a protected river.',
  'その漁師は保護された川でサケを密漁した罪で逮捕された。'),
(1013, 'intercept', '(人・もの)を途中で捕らえる;(通信)を傍受する', '/ˌɪntərˈsept/', 'インターセプト',
  'Intelligence agencies intercepted a series of encrypted communications.',
  '諜報機関は一連の暗号化された通信を傍受した。',
  'Border guards intercepted a shipment of contraband at the checkpoint.',
  '国境警備隊は検問所で密輸品の積荷を途中で捕らえた。'),
(1014, 'deceased', '死去した;[the deceased]故人', '/dɪˈsiːst/', 'ディシースト',
  'The estate of the deceased was divided equally among the heirs.',
  '故人の遺産は相続人の間で均等に分配された。',
  'A memorial service was held in honor of the deceased professor.',
  '亡くなった教授を偲んで追悼式が行われた。'),
(1015, 'straddle', '(馬・いすなど)にまたがる;(複数のもの・境界)にまたがる', '/ˈstrædl/', 'ストラドル',
  'The ancient city straddles the border between two countries.',
  'その古代都市は二国間の国境にまたがっている。',
  'Her research straddles the disciplines of neuroscience and philosophy.',
  '彼女の研究は神経科学と哲学の分野にまたがっている。'),
(1016, 'corrode', '(金属など)を腐食させる;(金属などが)腐食する', '/kəˈroʊd/', 'コロウド',
  'Saltwater rapidly corrodes metal structures near the coast.',
  '海水は沿岸の金属構造物を急速に腐食させる。',
  'Years of neglect had allowed the pipes to corrode beyond repair.',
  '何年もの放置によってパイプは修復不能なまでに腐食していた。'),
(1017, 'nurture', '(子ども・植物など)を育てる、養育する;(思想・感情など)を育む、助長する;養育、教育', '/ˈnɜːrtʃər/', 'ナーチャー',
  'The mentoring program was designed to nurture young talent in the arts.',
  'その指導プログラムは芸術分野の若い才能を育てるために設計された。',
  'Parents play a crucial role in nurturing a child''s intellectual curiosity.',
  '親は子どもの知的好奇心を育む上で重要な役割を果たす。'),
(1018, 'connotation', '(言葉の)言外の意味、含意', '/ˌkɑːnəˈteɪʃən/', 'コノテイション',
  'The word "regime" often carries a negative connotation in political discourse.',
  '「体制」という語は政治的言説においてしばしば否定的な含意を持つ。',
  'Advertisers carefully select words with positive connotations to appeal to consumers.',
  '広告主は消費者に訴えかけるため、肯定的な含意を持つ言葉を慎重に選ぶ。'),
(1019, 'anecdotal', '(話などが)個人の話に基づく、裏づけに乏しい;逸話的な', '/ˌænɪkˈdoʊtl/', 'アネクドウトル',
  'The evidence supporting the treatment is largely anecdotal and lacks scientific rigor.',
  'その治療法を裏付ける証拠は大部分が裏づけに乏しく、科学的厳密さを欠いている。',
  'While anecdotal reports suggest the drug is effective, clinical trials are still needed.',
  '個人の話に基づく報告はその薬が有効だと示唆しているが、臨床試験はまだ必要である。'),
(1020, 'smother', '(感情・反対など)を抑制する、抑える;~を覆い尽くす;(人)を窒息(死)させる', '/ˈsmʌðər/', 'スマザー',
  'The dictator attempted to smother all political dissent within the country.',
  'その独裁者は国内のあらゆる政治的反対意見を抑制しようとした。',
  'Heavy snowfall smothered the entire landscape in a thick white blanket.',
  '大雪が厚い白い毛布で全景を覆い尽くした。'),
(1021, 'tilt', '(人・ものが)傾く;(もの)を傾ける;傾く[傾ける]こと', '/tɪlt/', 'ティルト',
  'The earthquake caused the building to tilt dangerously to one side.',
  '地震でその建物は危険なほど一方に傾いた。',
  'Recent polling suggests the electoral balance has tilted in favor of the opposition.',
  '最近の世論調査は、選挙の均衡が野党有利に傾いたことを示唆している。'),
(1022, 'embroil', '~を(争い・議論などに)巻き込む', '/ɪmˈbrɔɪl/', 'エンブロイル',
  'The scandal embroiled several high-ranking officials in a bitter controversy.',
  'そのスキャンダルは複数の高官を激しい論争に巻き込んだ。',
  'The nation found itself embroiled in a diplomatic dispute with its neighbor.',
  'その国は隣国との外交紛争に巻き込まれた。'),
(1023, 'exponent', '(理論・主義などの)主唱者、主導者', '/ɪkˈspoʊnənt/', 'エクスポウネント',
  'She is regarded as the foremost exponent of progressive education reform.',
  '彼女は進歩的な教育改革の第一の主唱者と見なされている。',
  'The philosopher was a leading exponent of existentialist thought in the twentieth century.',
  'その哲学者は20世紀における実存主義思想の主導者であった。'),
(1024, 'impeach', '(政治家・官僚など)を弾劾する、告発する', '/ɪmˈpiːtʃ/', 'インピーチ',
  'The House of Representatives voted to impeach the president for abuse of power.',
  '下院は権力乱用で大統領を弾劾する採決を行った。',
  'Opposition lawmakers threatened to impeach the minister over the corruption allegations.',
  '野党議員たちは汚職疑惑をめぐりその大臣を弾劾すると脅した。'),
(1025, 'residual', '残留している、残りの', '/rɪˈzɪdʒuəl/', 'リジジュアル',
  'Residual chemicals in the soil posed a long-term threat to local wildlife.',
  '土壌に残留している化学物質が地元の野生生物に長期的な脅威をもたらした。',
  'Even after treatment, the patient experienced residual pain in her lower back.',
  '治療後も患者は腰に残りの痛みを感じていた。'),
(1026, 'boon', '恩恵、ありがたいもの', '/buːn/', 'ブーン',
  'The new railway line has been a tremendous boon for the rural community.',
  '新しい鉄道路線はその農村地域にとって大きな恩恵となった。',
  'Advances in telemedicine have proved a boon to patients in remote areas.',
  '遠隔医療の進歩は遠隔地の患者にとってありがたいものであると証明された。'),
(1027, 'retract', '(前言)を撤回する、取り消す;~を引っ込める', '/rɪˈtrækt/', 'リトラクト',
  'The newspaper was forced to retract its defamatory article after a lawsuit was filed.',
  'その新聞社は訴訟が起こされた後、名誉毀損記事を撤回せざるを得なかった。',
  'The witness retracted her testimony under intense cross-examination.',
  '証人は厳しい反対尋問の下で証言を取り消した。'),
(1028, 'insurrection', '暴動、反乱', '/ˌɪnsəˈrekʃən/', 'インサレクション',
  'The government deployed troops to quell the armed insurrection in the capital.',
  '政府は首都での武装反乱を鎮圧するため軍隊を派遣した。',
  'Historians regard the uprising as an insurrection against colonial oppression.',
  '歴史家はその蜂起を植民地支配に対する反乱と見なしている。'),
(1029, 'dispassionate', '(人・態度が)感情に左右されない、冷静な', '/dɪsˈpæʃənət/', 'ディスパッショネト',
  'The judge maintained a dispassionate demeanor throughout the emotionally charged trial.',
  '裁判官は感情的な裁判を通じて冷静な態度を保った。',
  'A dispassionate analysis of the data revealed no significant correlation.',
  'データの冷静な分析により、有意な相関は認められなかった。'),
(1030, 'wanton', '理不尽な、むちゃな;抑えられない、抑制できない', '/ˈwɑːntən/', 'ワントン',
  'The invading army was condemned for its wanton destruction of cultural heritage sites.',
  '侵略軍は文化遺産の理不尽な破壊で非難された。',
  'The report documented wanton disregard for environmental regulations by the factory.',
  'その報告書はその工場による環境規制の理不尽な無視を記録していた。'),
(1031, 'fray', '争い、いさかい', '/freɪ/', 'フレイ',
  'Several major corporations entered the fray over the lucrative government contract.',
  '複数の大企業がその利益の大きい政府契約をめぐる争いに参入した。',
  'The veteran diplomat was called upon once more to join the political fray.',
  'その熟練の外交官は再び政治的争いに加わるよう求められた。'),
(1032, 'defame', '~を中傷する、~の名誉を傷つける', '/dɪˈfeɪm/', 'ディフェイム',
  'The actress filed a lawsuit against the tabloid for attempting to defame her.',
  'その女優はタブロイド紙が自分を中傷しようとしたとして訴訟を起こした。',
  'Publishing false accusations to defame a political rival is a serious offense.',
  '政治的ライバルの名誉を傷つけるために虚偽の告発を公表することは重大な犯罪である。'),
(1033, 'veto', '(大統領・知事などが行使する)拒否権;(法案など)を拒否する', '/ˈviːtoʊ/', 'ヴィートウ',
  'The president exercised his veto to block the controversial legislation.',
  '大統領は物議を醸す法案を阻止するために拒否権を行使した。',
  'The proposal was vetoed by the security council amid heated debate.',
  'その提案は激しい議論の中で安全保障理事会によって拒否された。'),
(1034, 'buoyant', '(価格・景気などが)上向きの;うきうきした、楽天的な;浮力がある', '/ˈbɔɪənt/', 'ボイアント',
  'The stock market remained buoyant despite growing geopolitical tensions.',
  '地政学的緊張の高まりにもかかわらず、株式市場は上向きのままだった。',
  'Her buoyant personality lifted the spirits of everyone around her.',
  '彼女の楽天的な性格は周囲の皆の気持ちを明るくした。'),
(1035, 'invert', '~を逆にする、ひっくり返す', '/ɪnˈvɜːrt/', 'インヴァート',
  'The chef inverted the mold to release the perfectly shaped dessert.',
  'シェフは完璧な形のデザートを取り出すために型をひっくり返した。',
  'Inverting the traditional hierarchy proved to be an effective management strategy.',
  '従来の階層構造を逆にすることは、効果的な経営戦略であることが証明された。'),
(1036, 'invigorate', '(人)を元気づける、~の心身をさわやかにする;~を活性化する', '/ɪnˈvɪɡəreɪt/', 'インヴィゴレイト',
  'The brisk morning walk invigorated her before the long day of meetings.',
  '長い会議の一日の前に、さわやかな朝の散歩が彼女を元気づけた。',
  'The government introduced bold reforms to invigorate the stagnant economy.',
  '政府は停滞した経済を活性化するために大胆な改革を導入した。'),
(1037, 'tyranny', '専制政治、暴政', '/ˈtɪrəni/', 'ティラニー',
  'The people rose up against decades of tyranny and demanded democratic reform.',
  '国民は数十年にわたる暴政に対して立ち上がり、民主的改革を要求した。',
  'The philosopher warned that the tyranny of the majority could be just as oppressive.',
  'その哲学者は多数派の専制政治も同様に抑圧的になり得ると警告した。'),
(1038, 'stitch', '(布・傷口など)を縫う、縫い合わせる;縫い目、編み目', '/stɪtʃ/', 'スティッチ',
  'The surgeon carefully stitched the wound to minimize scarring.',
  '外科医は瘢痕を最小限にするために傷口を慎重に縫い合わせた。',
  'Each stitch in the tapestry was meticulously crafted by hand over many months.',
  'そのタペストリーの縫い目の一つ一つが何ヶ月もかけて手作業で丹念に作られた。'),
(1039, 'nimble', '(人・動作が)素早い、敏しょうな;(頭が)回転の速い', '/ˈnɪmbl/', 'ニンブル',
  'The nimble gymnast executed a flawless routine on the balance beam.',
  'その敏しょうな体操選手は平均台で完璧な演技を披露した。',
  'A nimble mind is essential for success in the rapidly changing tech industry.',
  '回転の速い頭脳は急速に変化するテクノロジー産業での成功に不可欠である。'),
(1040, 'infiltrate', '(スパイなどが)(組織など)に潜入する;(スパイなど)を潜入させる', '/ˈɪnfɪltreɪt/', 'インフィルトレイト',
  'Undercover agents managed to infiltrate the criminal syndicate.',
  '潜入捜査官は犯罪組織に潜入することに成功した。',
  'Hackers infiltrated the company''s network and stole confidential data.',
  'ハッカーたちは会社のネットワークに潜入し、機密データを盗んだ。'),
(1041, 'persecute', '(宗教・人種・政治的信条などの理由で)~を迫害する、弾圧する', '/ˈpɜːrsɪkjuːt/', 'パーシキュート',
  'The regime ruthlessly persecuted ethnic minorities for decades.',
  'その政権は数十年にわたって少数民族を容赦なく迫害した。',
  'Many refugees fled their homeland after being persecuted for their religious beliefs.',
  '多くの難民が宗教的信条を理由に迫害された後、祖国から逃れた。'),
(1042, 'colloquial', '(語・文章などが)口語の、日常会話の', '/kəˈloʊkwiəl/', 'コロウクウィアル',
  'The author deliberately used colloquial expressions to make the dialogue feel authentic.',
  '著者は対話を本物らしく感じさせるために口語表現を意図的に使った。',
  'Learners should be familiar with both formal and colloquial registers of the language.',
  '学習者は言語のフォーマルな語域と口語の語域の両方に精通しているべきである。'),
(1043, 'trajectory', '(弾丸・ミサイルなどの)弾道、軌道;(出来事の)軌跡、進展', '/trəˈdʒektəri/', 'トラジェクトリー',
  'The missile''s trajectory was tracked by radar from the moment of launch.',
  'そのミサイルの弾道は発射の瞬間からレーダーで追跡された。',
  'The trajectory of the nation''s economic growth has been remarkably steady.',
  'その国の経済成長の軌跡は驚くほど安定している。'),
(1044, 'spurn', '(申し出など)を拒絶する;(恋人)を振る', '/spɜːrn/', 'スパーン',
  'The board spurned the generous takeover bid, insisting the company was worth more.',
  '取締役会は会社の価値はもっと高いと主張し、寛大な買収提案を拒絶した。',
  'Spurned by the electorate, the former leader withdrew from public life entirely.',
  '有権者に拒絶され、その元指導者は公的生活から完全に退いた。'),
(1045, 'upend', '~を逆さまにする、ひっくり返す', '/ʌpˈend/', 'アペンド',
  'The unexpected ruling upended decades of established legal precedent.',
  '予想外の判決が数十年にわたる確立された法的先例をひっくり返した。',
  'The pandemic upended the global economy and transformed the way people work.',
  'パンデミックが世界経済をひっくり返し、人々の働き方を変えた。'),
(1046, 'conscientious', '慎重な、念入りの', '/ˌkɑːnʃiˈenʃəs/', 'コンシエンシャス',
  'The conscientious researcher double-checked every data point before publishing.',
  'その念入りな研究者は発表前にすべてのデータポイントを二重に確認した。',
  'She is known as a conscientious employee who never overlooks the smallest detail.',
  '彼女はどんな小さな詳細も見落とさない慎重な従業員として知られている。'),
(1047, 'onerous', '(仕事・任務が)骨の折れる、うんざりする', '/ˈɑːnərəs/', 'オナラス',
  'The onerous regulations imposed on small businesses stifled entrepreneurial growth.',
  '中小企業に課された骨の折れる規制が起業家の成長を抑制した。',
  'Completing the onerous paperwork for the visa application took several weeks.',
  'ビザ申請のうんざりする書類手続きを完了するのに数週間かかった。'),
(1048, 'tycoon', '(実業界などの)巨頭、大立て者', '/taɪˈkuːn/', 'タイクーン',
  'The media tycoon expanded his empire by acquiring several television networks.',
  'そのメディア界の巨頭はいくつかのテレビ局を買収して帝国を拡大した。',
  'The real estate tycoon donated a fortune to charitable causes.',
  'その不動産の大立て者は慈善事業に巨額を寄付した。'),
(1049, 'precept', '(行動・判断などの)原理、原則、指針;(宗教的・道徳的)教え、教義', '/ˈpriːsept/', 'プリーセプト',
  'The organization operates according to the precept that transparency fosters trust.',
  'その組織は透明性が信頼を育むという原則に従って運営されている。',
  'Ancient philosophical precepts continue to influence modern ethical thought.',
  '古代の哲学的教えは現代の倫理思想に影響を与え続けている。'),
(1050, 'modulate', '~を調節する、加減する;(声・音など)の調子を変える', '/ˈmɑːdʒəleɪt/', 'モジュレイト',
  'The skilled orator learned to modulate her voice to captivate the audience.',
  'その熟練した演説者は聴衆を魅了するために声の調子を変えることを学んだ',
  'The central bank modulated interest rates to stabilize the volatile market.',
  '中央銀行は不安定な市場を安定させるために金利を調節した。');
