-- words テーブル INSERT文 (No.1251 ~ No.1300)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(1251, 'articulate', '(人が)考えをはっきり述べることができる;(言葉・発音などが)明瞭な;(見解など)をはっきり述べる', '/ɑːrˈtɪkjələt/', 'アーティキュレット',
  'The candidate was articulate enough to convey her policy proposals in a compelling manner.',
  'その候補者は自分の政策提案を説得力のある形で伝えられるほど明瞭に話すことができた。',
  'He struggled to articulate his feelings about the sudden loss of his colleague.',
  '彼は同僚の突然の喪失に対する気持ちをはっきり述べることができなかった。'),
(1252, 'paramount', '最高の、最重要の', '/ˈpærəmaʊnt/', 'パラマウント',
  'Ensuring public safety is of paramount importance during a natural disaster.',
  '自然災害時に公共の安全を確保することは最重要である。',
  'The paramount concern for the committee was maintaining the integrity of the election process.',
  '委員会にとって最重要の懸念は選挙過程の公正性を維持することだった。'),
(1253, 'surge', '急に高まること、急騰;(感情の)高まり、高揚;(人が)殺到する、押し寄せる', '/sɜːrdʒ/', 'サージ',
  'A surge of protesters flooded the streets demanding governmental reform.',
  '抗議者の波が政府改革を求めて街路に殺到した。',
  'The company experienced a surge in demand after the product went viral on social media.',
  'その製品がSNSで拡散された後、会社は需要の急騰を経験した。'),
(1254, 'clot', '凝固する;(血などの)塊', '/klɑːt/', 'クロット',
  'The doctor warned that if blood were to clot in the artery, it could lead to a stroke.',
  '動脈内で血液が凝固すると脳卒中を引き起こす可能性があると医師は警告した。',
  'A clot formed at the site of the wound, effectively stopping the bleeding.',
  '傷口に血の塊が形成され、効果的に出血を止めた。'),
(1255, 'flourish', '栄える、繁栄する;(動植物が)よく育つ', '/ˈflɜːrɪʃ/', 'フラーリッシュ',
  'Small businesses tend to flourish in an economy with low interest rates and stable policies.',
  '低金利で安定した政策のある経済では中小企業は繁栄する傾向がある。',
  'Tropical orchids flourish in warm, humid environments with indirect sunlight.',
  '熱帯の蘭は暖かく湿度が高く間接的な日光のある環境でよく育つ。'),
(1256, 'ignite', '引火する、火がつく;~に点火する;(感情・論争など)に火をつける', '/ɪɡˈnaɪt/', 'イグナイト',
  'A single careless remark can ignite a fierce political controversy.',
  'たった一つの不用意な発言が激しい政治的論争に火をつけることがある。',
  'The leaked documents ignited widespread public outrage over the corruption scandal.',
  '流出した文書が汚職スキャンダルに対する広範な国民の怒りに火をつけた。'),
(1257, 'intimidate', '(人)を脅迫する、脅す', '/ɪnˈtɪmɪdeɪt/', 'インティミデイト',
  'The gang attempted to intimidate witnesses into retracting their testimonies.',
  'そのギャングは証人を脅迫して証言を撤回させようとした。',
  'She refused to be intimidated by the hostile atmosphere in the boardroom.',
  '彼女は取締役会の敵意に満ちた雰囲気に脅されることを拒否した。'),
(1258, 'intricate', '(模様・形などが)入り組んだ、複雑な;(話・構造などが)難解な', '/ˈɪntrɪkət/', 'イントリケット',
  'The intricate design of the cathedral ceiling took artisans over a decade to complete.',
  '大聖堂の天井の複雑なデザインを完成させるのに職人たちは10年以上を要した。',
  'Understanding the intricate mechanisms of the human immune system requires years of study.',
  '人間の免疫システムの複雑な仕組みを理解するには何年もの研究が必要である。'),
(1259, 'perpetuate', '(悪い状況・考えなど)を永続させる', '/pərˈpetʃueɪt/', 'パーペチュエイト',
  'The biased media coverage served to perpetuate harmful stereotypes about minorities.',
  '偏向した報道は少数者に対する有害な固定観念を永続させる役割を果たした。',
  'Failing to address income inequality will only perpetuate the cycle of poverty.',
  '所得格差に対処しないことは貧困の連鎖を永続させるだけである。'),
(1260, 'discard', '(不用品など)を捨てる、処分する', '/dɪsˈkɑːrd/', 'ディスカード',
  'The factory was fined for illegally discarding toxic waste into the river.',
  'その工場は有毒廃棄物を違法に川に捨てたとして罰金を科された。',
  'She decided to discard her old notes and start the research paper from scratch.',
  '彼女は古いノートを処分し、研究論文をゼロから始めることにした。'),
(1261, 'slaughter', '(動物)を屠殺する;(多くの人)を虐殺する;屠殺;(大量)虐殺、殺りく', '/ˈslɔːtər/', 'スローター',
  'The documentary exposed the inhumane methods used to slaughter livestock in certain facilities.',
  'そのドキュメンタリーは特定の施設で家畜を屠殺するために用いられる非人道的な方法を暴露した。',
  'The international community condemned the slaughter of innocent civilians during the conflict.',
  '国際社会は紛争中の無辜の市民の虐殺を非難した。'),
(1262, 'provoke', '~を引き起こす、誘発する;(故意に)(人など)を怒らせる', '/prəˈvoʊk/', 'プロヴォーク',
  'The controversial policy provoked a wave of protests across the nation.',
  'その物議を醸す政策は全国的な抗議の波を引き起こした。',
  'He deliberately provoked his opponent into making a rash decision during the debate.',
  '彼は討論中に相手を故意に怒らせて軽率な判断をさせた。'),
(1263, 'repress', '(感情・欲求など)を抑える、抑制する', '/rɪˈpres/', 'リプレス',
  'The authoritarian regime sought to repress any form of political dissent.',
  'その権威主義的な政権はあらゆる形の政治的反対意見を抑制しようとした。',
  'She could no longer repress her frustration and finally voiced her complaints.',
  '彼女はもはや不満を抑えることができず、ついに不平を口にした。'),
(1264, 'encompass', '(さまざまな考え・ものなど)を含む;(場所など)を取り囲む', '/ɪnˈkʌmpəs/', 'エンカンパス',
  'The new curriculum encompasses a wide range of subjects, from science to the arts.',
  '新しいカリキュラムは科学から芸術まで幅広い科目を含んでいる。',
  'The national park encompasses over two million acres of pristine wilderness.',
  'その国立公園は200万エーカー以上の手つかずの原野を含んでいる。'),
(1265, 'ensue', '続いて起こる', '/ɪnˈsuː/', 'エンスー',
  'When the power grid failed, chaos ensued as hospitals scrambled to activate backup generators.',
  '送電網が故障すると、病院が非常用発電機の起動に奔走する中、混乱が続いて起こった。',
  'A heated argument ensued after the chairman announced the unexpected merger.',
  '会長が予期せぬ合併を発表した後、激しい議論が続いて起こった。'),
(1266, 'array', '[an array of ~]多様な～、数々の～', '/əˈreɪ/', 'アレイ',
  'The museum boasts an impressive array of artifacts from ancient civilizations.',
  'その博物館は古代文明の見事な数々の工芸品を誇っている。',
  'An array of challenges awaits the newly appointed CEO of the struggling company.',
  '苦境にある会社の新任CEOには数々の課題が待ち受けている。'),
(1267, 'galvanize', '(人)に衝撃を与える、~を活気づける;~を電流で刺激する', '/ˈɡælvənaɪz/', 'ガルヴァナイズ',
  'The tragic incident galvanized the community into demanding stricter safety regulations.',
  'その悲劇的な事件は地域社会に衝撃を与え、より厳しい安全規制を求めさせた。',
  'Her passionate speech galvanized thousands of volunteers to join the relief effort.',
  '彼女の情熱的な演説は数千人のボランティアを活気づけ、救援活動に参加させた。'),
(1268, 'revere', '~を崇敬する、あがめる', '/rɪˈvɪr/', 'リヴィア',
  'In many cultures, elders are revered for their wisdom and life experience.',
  '多くの文化において、年長者はその知恵と人生経験ゆえに崇敬されている。',
  'The scientist is revered worldwide for her groundbreaking contributions to genetics.',
  'その科学者は遺伝学への画期的な貢献により世界中で崇敬されている。'),
(1269, 'deteriorate', '(もの・状況・品質などが)悪化する', '/dɪˈtɪriəreɪt/', 'ディティアリオレイト',
  'The patient''s condition began to deteriorate rapidly after the surgery.',
  '患者の状態は手術後に急速に悪化し始めた。',
  'Relations between the two countries have deteriorated significantly over the past decade.',
  '両国間の関係は過去10年間で著しく悪化した。'),
(1270, 'intact', '損なわれていない、無傷で', '/ɪnˈtækt/', 'インタクト',
  'Remarkably, the ancient manuscript remained intact despite centuries of exposure to the elements.',
  '驚くべきことに、その古代の写本は何世紀にもわたる風雨への暴露にもかかわらず無傷のままだった。',
  'The building''s structural integrity remained intact even after the earthquake.',
  '地震の後でさえ、その建物の構造的健全性は損なわれていなかった。'),
(1271, 'entrust', '~を委ねる、任せる', '/ɪnˈtrʌst/', 'エントラスト',
  'The board decided to entrust the management of the new division to a seasoned executive.',
  '取締役会は新部門の管理をベテランの経営者に委ねることを決めた。',
  'Parents entrust teachers with the intellectual development of their children.',
  '親は子供たちの知的発達を教師に任せている。'),
(1272, 'downplay', '~を(実際より)軽く扱う、過小評価する', '/ˈdaʊnpleɪ/', 'ダウンプレイ',
  'The government attempted to downplay the severity of the economic crisis.',
  '政府は経済危機の深刻さを軽く扱おうとした。',
  'Critics accused the corporation of downplaying the environmental impact of its operations.',
  '批評家たちはその企業が事業の環境への影響を過小評価していると非難した。'),
(1274, 'prone', '(好ましくない)傾向がある、～しがちな', '/proʊn/', 'プローン',
  'Coastal regions are prone to severe flooding during the hurricane season.',
  '沿岸地域はハリケーンシーズン中に深刻な洪水が起こりやすい傾向がある。',
  'People who work long hours without breaks are prone to chronic fatigue and burnout.',
  '休憩なしで長時間働く人は慢性的な疲労と燃え尽き症候群になりがちである。'),
(1275, 'surveillance', '(容疑者・囚人などの)監視、見張り', '/sərˈveɪləns/', 'サーヴェイランス',
  'The police placed the suspect under constant surveillance for several weeks.',
  '警察は数週間にわたり容疑者を常時監視下に置いた。',
  'The expansion of government surveillance programs has raised serious privacy concerns.',
  '政府の監視プログラムの拡大は深刻なプライバシーの懸念を引き起こしている。'),
(1276, 'ascribe', '~の原因を(…に)帰する;~を(…の)作とする', '/əˈskraɪb/', 'アスクライブ',
  'Historians ascribe the fall of the empire to a combination of internal corruption and external invasions.',
  '歴史家たちは帝国の滅亡の原因を内部の腐敗と外部からの侵略の組み合わせに帰している。',
  'The painting was originally ascribed to Rembrandt, but later analysis proved otherwise.',
  'その絵画はもともとレンブラントの作とされていたが、後の分析で別人の作と判明した。'),
(1277, 'pinpoint', '(原因など)を特定する;(位置など)を正確に示す;正確な、極小の', '/ˈpɪnpɔɪnt/', 'ピンポイント',
  'Engineers worked tirelessly to pinpoint the source of the structural failure.',
  'エンジニアたちは構造的欠陥の原因を特定するために休むことなく作業した。',
  'Satellite technology allows us to pinpoint the exact location of a distress signal.',
  '衛星技術によって遭難信号の正確な位置を特定することができる。'),
(1278, 'decimate', '(大量に)(人・動物)を殺す;(組織・団体など)を衰退させる', '/ˈdesɪmeɪt/', 'デシメイト',
  'The prolonged drought decimated the region''s agricultural output.',
  '長引く干ばつがその地域の農業生産高を壊滅的に減少させた。',
  'Overfishing has decimated the population of several marine species in the area.',
  '乱獲がその地域のいくつかの海洋種の個体数を激減させた。'),
(1279, 'surcharge', '追加料金、割増料金;~に追加料金を請求する', '/ˈsɜːrtʃɑːrdʒ/', 'サーチャージ',
  'Airlines often impose a fuel surcharge when oil prices rise sharply.',
  '航空会社は原油価格が急騰すると燃料割増料金を課すことが多い。',
  'Customers were outraged when the hotel added a hidden surcharge to their bills.',
  'ホテルが請求書に隠れた追加料金を加えたとき、顧客は憤慨した。'),
(1280, 'cripple', '~を機能不全にする、まひさせる', '/ˈkrɪpl/', 'クリプル',
  'The cyberattack crippled the nation''s banking infrastructure for several days.',
  'そのサイバー攻撃は数日間にわたり国の銀行インフラを機能不全にした。',
  'Excessive regulations can cripple small businesses that lack the resources to comply.',
  '過度な規制は順守するための資源を欠く中小企業をまひさせることがある。'),
(1281, 'discrepancy', '(計算・報告などにおける)矛盾、不一致', '/dɪsˈkrepənsi/', 'ディスクレパンシー',
  'Auditors discovered a significant discrepancy between the reported revenue and the actual figures.',
  '監査人は報告された収益と実際の数字との間に大きな不一致を発見した。',
  'The discrepancy in the witness statements raised doubts about the reliability of the testimony.',
  '証人の供述における矛盾が証言の信頼性に対する疑念を生じさせた。'),
(1282, 'pretext', '口実、言い訳', '/ˈpriːtekst/', 'プリーテクスト',
  'The invasion was carried out under the pretext of restoring democratic governance.',
  'その侵攻は民主的統治を回復するという口実の下で実行された。',
  'He used a minor scheduling conflict as a pretext to avoid attending the meeting.',
  '彼はささいなスケジュールの都合を口実にして会議への出席を避けた。'),
(1283, 'outlay', '支出、費用', '/ˈaʊtleɪ/', 'アウトレイ',
  'The initial capital outlay for the project exceeded the original budget by thirty percent.',
  'そのプロジェクトの初期資本支出は当初の予算を30パーセント超過した。',
  'Despite the considerable outlay, the long-term returns justified the investment.',
  '多大な支出にもかかわらず、長期的なリターンはその投資を正当化した。'),
(1284, 'menace', '脅威;危険(なもの[人])', '/ˈmenɪs/', 'メナス',
  'Plastic pollution has become a growing menace to marine ecosystems worldwide.',
  'プラスチック汚染は世界中の海洋生態系にとって増大する脅威となっている。',
  'The authorities declared the abandoned building a public menace and ordered its demolition.',
  '当局はその廃墟を公共の危険物と宣言し、その取り壊しを命じた。'),
(1286, 'compliance', '(規則・命令などに)従うこと、順守', '/kəmˈplaɪəns/', 'コンプライアンス',
  'The company faces heavy fines for non-compliance with environmental regulations.',
  'その会社は環境規制の不順守に対して多額の罰金に直面している。',
  'Strict compliance with international trade laws is essential for multinational corporations.',
  '国際貿易法の厳格な順守は多国籍企業にとって不可欠である。'),
(1287, 'diversify', '(事業など)を多様化する、多角化する;(出資・資本など)を分散させる', '/daɪˈvɜːrsɪfaɪ/', 'ダイヴァーシファイ',
  'The corporation decided to diversify its product line to reduce dependence on a single market.',
  'その企業は単一市場への依存を減らすため製品ラインを多角化することを決めた。',
  'Financial advisors recommend that investors diversify their portfolios to mitigate risk.',
  'ファイナンシャルアドバイザーはリスクを軽減するために投資家にポートフォリオの分散を勧めている。'),
(1288, 'expulsion', '排除、追放', '/ɪkˈspʌlʃən/', 'エクスパルション',
  'The student faced expulsion from the university for repeated violations of the academic code.',
  'その学生は学則への度重なる違反により大学からの追放に直面した。',
  'The expulsion of the diplomat escalated tensions between the two nations.',
  '外交官の追放は両国間の緊張を高めた。'),
(1289, 'intrigue', '~の興味をそそる;陰謀(を企てること)', '/ɪnˈtriːɡ/', 'イントリーグ',
  'The mysterious artifact intrigued archaeologists, prompting further excavation of the site.',
  'その謎めいた遺物が考古学者の興味をそそり、遺跡のさらなる発掘を促した。',
  'The novel is a tale of political intrigue set in a fictional European monarchy.',
  'その小説は架空のヨーロッパの君主国を舞台にした政治的陰謀の物語である。'),
(1290, 'shortcoming', '短所、欠点', '/ˈʃɔːrtkʌmɪŋ/', 'ショートカミング',
  'The report highlighted several shortcomings in the current healthcare system.',
  'その報告書は現在の医療制度におけるいくつかの欠点を浮き彫りにした。',
  'Acknowledging one''s own shortcomings is the first step toward personal growth.',
  '自分自身の短所を認めることが自己成長への第一歩である。'),
(1291, 'endow', '(人)に(才能などを)授ける;~に(基金などを)寄付する', '/ɪnˈdaʊ/', 'エンダウ',
  'The philanthropist endowed the university with a generous fund for scientific research.',
  'その慈善家は科学研究のための潤沢な基金を大学に寄付した。',
  'Nature has endowed certain species with remarkable abilities to adapt to extreme environments.',
  '自然はある種の生物に過酷な環境に適応する驚くべき能力を授けている。'),
(1292, 'amenity', '(生活・滞在などを快適にする)施設、設備;(場所などの)快適さ', '/əˈmenɪti/', 'アメニティ',
  'The hotel offers a wide range of amenities, including a spa, gym, and rooftop pool.',
  'そのホテルはスパ、ジム、屋上プールを含む幅広い施設を提供している。',
  'Residents complained about the lack of basic amenities in the newly developed housing complex.',
  '住民は新しく開発された住宅団地における基本的な設備の不足について不満を述べた。'),
(1293, 'bleak', '(見通しが)よくない、暗い;(場所・風景が)荒涼とした', '/bliːk/', 'ブリーク',
  'The economic outlook for the region remains bleak due to persistent unemployment.',
  '持続的な失業のため、その地域の経済見通しは依然として暗い。',
  'The bleak landscape of the northern tundra stretched endlessly under a grey sky.',
  '北方のツンドラの荒涼とした風景が灰色の空の下で果てしなく広がっていた。'),
(1294, 'futile', '無益な、無駄な', '/ˈfjuːtl/', 'フューティル',
  'All attempts to negotiate a ceasefire proved futile as both sides refused to compromise.',
  '双方が妥協を拒否したため、停戦交渉のあらゆる試みは無駄に終わった。',
  'It would be futile to try to reverse the environmental damage without global cooperation.',
  '国際的な協力なしに環境被害を元に戻そうとしても無益であろう。'),
(1295, 'guise', '(ごまかすために装った)外観、見せかけ', '/ɡaɪz/', 'ガイズ',
  'The spy entered the country under the guise of a foreign journalist.',
  'そのスパイは外国人記者を装って入国した。',
  'The fraudulent scheme operated under the guise of a legitimate charity organization.',
  'その詐欺的な計画は合法的な慈善団体の見せかけの下で運営されていた。'),
(1296, 'condemnation', '(激しい)非難、糾弾', '/ˌkɑːndemˈneɪʃən/', 'コンデムネイション',
  'The government''s actions drew widespread condemnation from human rights organizations.',
  '政府の行動は人権団体からの広範な非難を招いた。',
  'International condemnation of the nuclear test was swift and unanimous.',
  '核実験に対する国際的な非難は迅速かつ全会一致だった。'),
(1298, 'ambiguity', '(意味などの)あいまいさ、多義性', '/ˌæmbɪˈɡjuːəti/', 'アンビギュイティ',
  'The ambiguity of the contract''s wording led to a prolonged legal dispute.',
  '契約文言のあいまいさが長期にわたる法的紛争を招いた。',
  'Effective legislation must be drafted with minimal ambiguity to prevent misinterpretation.',
  '効果的な法律は誤解を防ぐために最小限のあいまいさで起草されなければならない。'),
(1299, 'prolonged', '長引く、長期間の', '/prəˈlɔːŋd/', 'プロローングド',
  'Prolonged exposure to ultraviolet radiation significantly increases the risk of skin cancer.',
  '紫外線への長期間の曝露は皮膚がんのリスクを著しく高める。',
  'The prolonged negotiations finally resulted in a comprehensive trade agreement.',
  '長引く交渉はついに包括的な貿易協定をもたらした。'),
(1300, 'insidious', '(悪事・病気などが)知らない間に進行する', '/ɪnˈsɪdiəs/', 'インシディアス',
  'The insidious effects of air pollution often go unnoticed until serious health problems emerge.',
  '大気汚染の知らない間に進行する影響は深刻な健康問題が現れるまで気づかれないことが多い。',
  'Misinformation spreads in an insidious manner, gradually eroding public trust in institutions.',
  '偽情報は知らない間に進行する形で広がり、制度に対する国民の信頼を徐々に蝕む。');
