-- words テーブル INSERT文 (No.151 ~ No.200)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(151, 'refute', '~の誤りを証明する、~を反駁する', '/rɪˈfjuːt/', 'リフューt',
  'The scientist was able to refute the long-standing theory with irrefutable empirical evidence.',
  'その科学者は反論の余地のない経験的証拠でその長年の理論の誤りを証明することができた。',
  'The defense attorney skillfully refuted every allegation made by the prosecution.',
  '弁護人は検察側のすべての主張を巧みに反駁した。'),
(152, 'animosity', '(激しい)敵意、憎しみ', '/ˌænɪˈmɒsɪti/', 'アニモスィティ',
  'The deep-seated animosity between the two rival factions has persisted for decades.',
  '二つの対立する派閥間の根深い敵意は何十年も続いている。',
  'Despite the animosity he felt toward his former partner, he maintained a professional demeanor.',
  'かつてのパートナーに対する憎しみにもかかわらず、彼は職業人としての態度を保った。'),
(153, 'fugitive', '逃亡犯、脱走者;逃亡中の、逃げた', '/ˈfjuːdʒɪtɪv/', 'フュージティヴ',
  'The fugitive eluded law enforcement for over three years before finally being apprehended.',
  'その逃亡犯は最終的に逮捕されるまで3年以上にわたって法執行機関の追跡を逃れた。',
  'Several fugitive soldiers crossed the border under cover of darkness.',
  '数人の逃亡中の兵士が闇にまぎれて国境を越えた。'),
(154, 'ramification', '(派生して生じる)影響、結果', '/ˌræmɪfɪˈkeɪʃən/', 'ラミフィケイション',
  'The ramifications of the new trade policy will be felt across multiple industries.',
  '新たな通商政策の影響は複数の産業にわたって感じられるだろう。',
  'Few legislators fully grasped the long-term ramifications of the bill they had passed.',
  'その法案の長期的な影響を十分に理解していた議員はほとんどいなかった。'),
(155, 'adamant', '断固として譲らない、断固として主張する', '/ˈædəmənt/', 'アダマント',
  'The chairman remained adamant that the merger would proceed as planned.',
  '会長は合併が予定通り進められるべきだと断固として主張し続けた。',
  'Despite mounting criticism, she was adamant in her refusal to resign.',
  '批判が高まる中でも、彼女は辞任を断固として拒否した。'),
(156, 'languish', '①辛い状況を強いられる、(長期間)閉じ込められる ②(活動などが)停滞する', '/ˈlæŋɡwɪʃ/', 'ラングウィッシュ',
  'Hundreds of political prisoners continued to languish in overcrowded detention facilities.',
  '数百人の政治犯が過密な収容施設に閉じ込められ続けた。',
  'The economy has languished for years due to ineffective fiscal policies.',
  '効果のない財政政策のせいで経済は何年も停滞している。'),
(157, 'gall', '厚かましさ、ずうずうしさ', '/ɡɔːl/', 'ゴール',
  'She had the gall to demand a promotion after having been reprimanded for chronic tardiness.',
  '慢性的な遅刻で叱責された後に昇進を要求するとは、彼女は厚かましかった。',
  'It takes considerable gall to plagiarize an entire dissertation and submit it as one''s own work.',
  '学位論文をまるごと盗用して自分の研究として提出するには相当なずうずうしさが必要だ。'),
(158, 'meddle', '干渉する、おせっかいを焼く', '/ˈmedl/', 'メドル',
  'Foreign governments were accused of meddling in the country''s internal affairs.',
  '外国政府がその国の内政に干渉したとして非難された。',
  'She resented her mother-in-law''s tendency to meddle in every aspect of their marriage.',
  '彼女は義母が結婚生活のあらゆる面に干渉する傾向を不快に思っていた。'),
(159, 'reprimand', '~を叱責する;叱責、懲戒', '/ˈreprɪmænd/', 'レプリマンド',
  'The officer received a formal reprimand for violating the department''s code of conduct.',
  'その職員は部署の行動規範に違反したとして正式な懲戒処分を受けた。',
  'The manager reprimanded the employee for repeatedly failing to meet deadlines.',
  '上司はその社員を締め切りに繰り返し遅れたことで叱責した。'),
(160, 'engrossed', '没頭して', '/ɪnˈɡroʊst/', 'イングロウスt',
  'She was so engrossed in her research that she lost track of time entirely.',
  '彼女は研究に没頭するあまり、時間の感覚を完全に失っていた。',
  'The audience sat engrossed as the pianist delivered a mesmerizing performance.',
  'ピアニストが魅惑的な演奏を披露する中、聴衆は没頭して座っていた。'),
(161, 'anesthetic', '麻酔(剤)', '/ˌænɪsˈθetɪk/', 'アネスセティック',
  'The surgeon administered a local anesthetic before making the incision.',
  '外科医は切開する前に局所麻酔剤を投与した。',
  'Advances in anesthetic techniques have significantly reduced surgical complications.',
  '麻酔技術の進歩により手術の合併症は大幅に減少した。'),
(162, 'plunder', '(金・財産など)を略奪する、強奪する', '/ˈplʌndər/', 'プランダー',
  'Invading armies systematically plundered the cultural treasures of the conquered cities.',
  '侵略軍は征服した都市の文化的財宝を組織的に略奪した。',
  'Corporate executives were convicted of plundering the company''s pension fund.',
  '企業の幹部たちは会社の年金基金を強奪した罪で有罪判決を受けた。'),
(163, 'grueling', 'へとへとに疲れさせる、厳しい', '/ˈɡruːəlɪŋ/', 'グルーエリング',
  'The athletes endured a grueling training regimen in preparation for the Olympic trials.',
  '選手たちはオリンピック選考会に備えて厳しいトレーニングに耐えた。',
  'After a grueling twelve-hour negotiation, both parties finally reached a compromise.',
  'へとへとになる12時間の交渉の末、両者はついに妥協に達した。'),
(164, 'precursor', '①前兆、前触れ ②先駆者、前任者', '/prɪˈkɜːrsər/', 'プリカーサー',
  'Many historians regard the printing press as a precursor to the modern information age.',
  '多くの歴史家が印刷機を現代の情報化時代の先駆けと見なしている。',
  'A sudden drop in barometric pressure is often a precursor to severe weather.',
  '気圧の急激な低下はしばしば悪天候の前兆である。'),
(165, 'brunt', '(攻撃の)矛先', '/brʌnt/', 'ブラント',
  'Coastal communities bore the brunt of the devastating hurricane.',
  '沿岸地域が壊滅的なハリケーンの矛先を受けた。',
  'Small businesses inevitably bear the brunt of economic recessions.',
  '中小企業は経済不況の矛先を不可避的に受ける。'),
(166, 'litany', '延々と[長々と]続くもの', '/ˈlɪtəni/', 'リタニー',
  'The report detailed a litany of failures that led to the catastrophic data breach.',
  'その報告書は壊滅的なデータ漏洩につながった延々と続く失敗の数々を詳述した。',
  'Residents presented a litany of complaints about the deteriorating infrastructure.',
  '住民たちは悪化するインフラについて長々と続く苦情を提出した。'),
(167, 'repercussion', '(間接的でよくない)影響、余波', '/ˌriːpərˈkʌʃən/', 'リーパーカッション',
  'The diplomatic scandal had serious repercussions for bilateral trade relations.',
  'その外交スキャンダルは二国間の貿易関係に深刻な影響を及ぼした。',
  'He acted impulsively without considering the potential repercussions of his decision.',
  '彼は自分の決定がもたらしうる影響を考慮せずに衝動的に行動した。'),
(168, 'rationale', '(行動・信条の)根拠', '/ˌræʃəˈnæl/', 'ラショナール',
  'The government failed to provide a convincing rationale for the sudden policy reversal.',
  '政府は突然の政策転換について納得のいく根拠を示すことができなかった。',
  'Could you elaborate on the rationale behind your proposed organizational restructuring?',
  '提案された組織再編の根拠について詳しく説明していただけますか。'),
(169, 'clandestine', '秘密の、内密の', '/klænˈdestɪn/', 'クランデスティン',
  'The intelligence agency conducted clandestine operations in several foreign countries.',
  '情報機関はいくつかの外国で秘密の作戦を遂行した。',
  'The activists held clandestine meetings to avoid surveillance by the authorities.',
  '活動家たちは当局の監視を避けるために秘密の会合を開いた。'),
(170, 'irreparably', '修復できないほどに', '/ɪˈrepərəbli/', 'イレパラブリー',
  'The oil spill irreparably damaged the fragile marine ecosystem.',
  '石油流出はその脆弱な海洋生態系を修復できないほどに損傷した。',
  'His credibility was irreparably harmed by the revelations of financial misconduct.',
  '財務上の不正行為の暴露により、彼の信用は修復できないほどに傷ついた。'),
(171, 'preemptive', '先制の', '/priˈemptɪv/', 'プリエンプティヴ',
  'The military launched a preemptive strike to neutralize the imminent threat.',
  '軍は差し迫った脅威を無力化するために先制攻撃を行った。',
  'The company took preemptive measures to mitigate the impact of the anticipated regulatory changes.',
  '会社は予想される規制変更の影響を緩和するために先制的な措置を講じた。'),
(172, 'subvert', '(体制・政府など)を覆そうとする、転覆させようとする', '/səbˈvɜːrt/', 'サブヴァート',
  'The dissident group was accused of attempting to subvert the established government.',
  'その反体制グループは樹立された政府を覆そうとしたとして告発された。',
  'Disinformation campaigns are designed to subvert public trust in democratic institutions.',
  '偽情報キャンペーンは民主的制度に対する国民の信頼を覆すことを目的としている。'),
(173, 'liquidate', '(資産など)を換金する', '/ˈlɪkwɪdeɪt/', 'リクウィデイト',
  'The bankrupt firm was forced to liquidate its assets to repay outstanding debts.',
  '破産した企業は未払いの債務を返済するために資産を換金することを余儀なくされた。',
  'Investors rushed to liquidate their holdings before the market collapsed further.',
  '投資家たちは市場がさらに崩壊する前に保有資産を換金しようと殺到した。'),
(174, 'fruition', '達成、実現', '/fruˈɪʃən/', 'フルイション',
  'After years of meticulous planning, the ambitious urban renewal project finally came to fruition.',
  '綿密な計画の後、その野心的な都市再開発プロジェクトはついに実現した。',
  'Her lifelong dream of establishing a charitable foundation came to fruition upon her retirement.',
  '慈善財団を設立するという彼女の生涯の夢は、退職を機に実現した。'),
(175, 'consternation', '非常な驚き、仰天、狼狽', '/ˌkɒnstərˈneɪʃən/', 'コンスターネイション',
  'The sudden resignation of the CEO caused widespread consternation among shareholders.',
  'CEOの突然の辞任は株主の間に広範な狼狽を引き起こした。',
  'To the consternation of environmentalists, the government approved the controversial pipeline.',
  '環境保護団体が仰天したことに、政府はその物議を醸すパイプラインを承認した。'),
(176, 'garner', '(情報・重要なもの)を獲得する、集める', '/ˈɡɑːrnər/', 'ガーナー',
  'The documentary garnered widespread critical acclaim and several prestigious awards.',
  'そのドキュメンタリーは広範な批評家の称賛と数々の名誉ある賞を獲得した。',
  'The candidate garnered substantial support from voters in rural constituencies.',
  'その候補者は地方選挙区の有権者からかなりの支持を集めた。'),
(177, 'predicament', '窮地、困難な状況', '/prɪˈdɪkəmənt/', 'プリディカメント',
  'The company found itself in a dire predicament after the sudden withdrawal of its primary investor.',
  '主要投資家が突然撤退した後、会社は深刻な窮地に立たされた。',
  'Many refugees face the agonizing predicament of choosing between safety and livelihood.',
  '多くの難民は安全と生計の間で選択を迫られるという苦しい困難な状況に直面している。'),
(178, 'contingency', '(不測の)事態、将来起こりうること', '/kənˈtɪndʒənsi/', 'コンティンジェンシー',
  'The board approved a contingency plan in the event of a prolonged supply chain disruption.',
  '取締役会はサプライチェーンの長期的な途絶に備えた不測の事態への対応計画を承認した。',
  'Prudent organizations allocate resources for contingencies that may arise during large-scale projects.',
  '慎重な組織は大規模プロジェクト中に起こりうる不測の事態のために資源を割り当てる。'),
(179, 'salvage', '(難破船・火災などから)~を運び出す、救出する;(名誉など)を回復する、取り戻す', '/ˈsælvɪdʒ/', 'サルヴィジ',
  'Divers managed to salvage priceless artifacts from the sunken vessel.',
  'ダイバーたちは沈没船から貴重な遺物を運び出すことに成功した。',
  'The public relations team worked tirelessly to salvage the company''s tarnished reputation.',
  '広報チームは傷ついた会社の評判を回復するためにたゆまず働いた。'),
(180, 'barrage', '①(質問などの)集中攻撃 ②弾幕、集中爆撃', '/bəˈrɑːʒ/', 'バラージ',
  'The minister faced a barrage of hostile questions from the press corps.',
  '大臣は報道陣からの敵意ある質問の集中攻撃にさらされた。',
  'The coastal defenses withstood an intense barrage of enemy artillery fire.',
  '沿岸防衛は敵の砲撃による激しい弾幕に耐えた。'),
(181, 'deterrent', '阻止するもの、妨害物', '/dɪˈtɜːrənt/', 'ディターレント',
  'Proponents argue that the death penalty serves as a deterrent against violent crime.',
  '賛成派は死刑が暴力犯罪に対する抑止力として機能すると主張する。',
  'The high cost of litigation acts as an effective deterrent to frivolous lawsuits.',
  '訴訟費用の高さは軽率な訴訟に対する効果的な抑止力として働く。'),
(182, 'berate', '(人)をきつく叱る、叱責する', '/bɪˈreɪt/', 'ビレイト',
  'The coach berated the players for their lackluster performance in the first half.',
  '監督は前半の覇気のないプレーについて選手たちをきつく叱った。',
  'It is counterproductive to berate employees publicly, as it erodes morale and trust.',
  '社員を公の場で叱責するのは逆効果であり、士気と信頼を損なう。'),
(183, 'bask', '①(恩恵・人気などに)浴する ②日光浴をする、暖まる', '/bæsk/', 'バスク',
  'The actor basked in the adulation of fans following the film''s triumphant premiere.',
  'その俳優は映画の大成功した初演の後、ファンの賞賛に浴した。',
  'Tourists basked in the warm Mediterranean sunshine on the pristine beaches.',
  '観光客たちは美しいビーチで温かい地中海の日差しを浴びていた。'),
(184, 'belligerent', '①好戦的な、けんか腰の ②交戦中の', '/bəˈlɪdʒərənt/', 'ベリジェレント',
  'His belligerent attitude during the negotiations ultimately derailed the peace talks.',
  '交渉中の彼の好戦的な態度が最終的に和平交渉を頓挫させた。',
  'The belligerent nations agreed to a temporary ceasefire brokered by the United Nations.',
  '交戦中の国々は国連の仲介による一時停戦に同意した。'),
(185, 'rebut', '(罪状・批判など)を誤りだと論証する、~に反論する', '/rɪˈbʌt/', 'リバット',
  'The defendant''s legal team sought to rebut the prosecution''s key piece of evidence.',
  '被告の弁護団は検察側の重要な証拠に反論しようとした。',
  'The researcher published a comprehensive paper to rebut the criticisms leveled at her methodology.',
  'その研究者は自身の方法論に向けられた批判に反論するために包括的な論文を発表した。'),
(186, 'eulogy', '(死者の徳などをたたえる)弔辞', '/ˈjuːlədʒi/', 'ユーロジー',
  'The late professor''s colleague delivered a deeply moving eulogy at the memorial service.',
  '故教授の同僚が追悼式で深く心を動かす弔辞を述べた。',
  'Writing a eulogy that truly captures the essence of a person''s life is an immensely difficult task.',
  '故人の人生の本質を真に捉えた弔辞を書くことは非常に難しい仕事である。'),
(187, 'commotion', '騒動、大騒ぎ', '/kəˈmoʊʃən/', 'コモーション',
  'The unexpected fire alarm caused a tremendous commotion in the crowded shopping mall.',
  '予期せぬ火災報知器の作動が混雑したショッピングモールで大きな騒動を引き起こした。',
  'The commotion outside the courthouse intensified as the verdict was announced.',
  '評決が発表されると裁判所の外の騒動は激しさを増した。'),
(188, 'accomplice', '共犯者、共謀者', '/əˈkɒmplɪs/', 'アコンプリス',
  'The investigation revealed that the embezzler had several accomplices within the organization.',
  '捜査により、横領犯には組織内に数人の共犯者がいたことが明らかになった。',
  'She was charged as an accomplice to the fraud after evidence of her involvement surfaced.',
  '彼女の関与を示す証拠が浮上した後、彼女は詐欺の共犯者として起訴された。'),
(189, 'fallacy', '誤った考え', '/ˈfæləsi/', 'ファラシー',
  'The notion that economic growth inevitably leads to social equality is a pervasive fallacy.',
  '経済成長が必然的に社会的平等をもたらすという考えは広く浸透した誤った考えである。',
  'The professor urged students to identify logical fallacies in the arguments presented.',
  '教授は学生たちに提示された議論の中の論理的誤謬を特定するよう促した。'),
(190, 'plagiarize', '(他人のアイデアなど)を剽窃する、盗用する', '/ˈpleɪdʒəraɪz/', 'プレイジャライズ',
  'The student was expelled for having plagiarized substantial portions of her thesis.',
  'その学生は論文の大部分を剽窃したとして退学処分を受けた。',
  'Authors who plagiarize the work of others risk irreparable damage to their professional reputations.',
  '他者の作品を盗用する著者は職業上の評判に修復できない損害を被る恐れがある。'),
(191, 'conflagration', '大火災', '/ˌkɒnfləˈɡreɪʃən/', 'コンフラグレイション',
  'The conflagration that swept through the industrial district destroyed dozens of warehouses.',
  '工業地区を襲った大火災は数十の倉庫を破壊した。',
  'Firefighters struggled for days to contain the conflagration fueled by gale-force winds.',
  '消防士たちは強風にあおられた大火災を鎮火するために何日も奮闘した。'),
(192, 'obtrusive', '出しゃばりの、押しつけがましい', '/əbˈtruːsɪv/', 'オブトルーシヴ',
  'The security cameras were deliberately made unobtrusive, unlike the obtrusive ones in the lobby.',
  '防犯カメラはロビーの目立つものとは異なり、意図的に目立たないように設置された。',
  'His obtrusive manner of inserting himself into every conversation irritated his colleagues.',
  'あらゆる会話に割り込む彼の押しつけがましい態度は同僚たちを苛立たせた。'),
(193, 'adroit', '巧みな、抜け目のない', '/əˈdrɔɪt/', 'アドロイト',
  'The diplomat''s adroit handling of the crisis averted a potential international conflict.',
  'その外交官の危機の巧みな対処が国際紛争の可能性を回避させた。',
  'An adroit negotiator can find common ground even in the most contentious disputes.',
  '巧みな交渉者は最も論争的な紛争においても共通の立場を見つけることができる。'),
(194, 'enmity', '(長期にわたる)敵意、憎しみ', '/ˈenmɪti/', 'エンミティ',
  'The enmity between the two neighboring countries can be traced back centuries.',
  '二つの隣国間の敵意は何世紀も前に遡ることができる。',
  'Personal enmity should never be allowed to influence judicial proceedings.',
  '個人的な敵意が司法手続きに影響を及ぼすことは決して許されるべきではない。'),
(195, 'excruciating', '①(苦痛が)非常に激しい ②(苦悩が)極度の、耐えがたい', '/ɪkˈskruːʃieɪtɪŋ/', 'イクスクルーシエイティング',
  'The patient described the pain in his lower back as absolutely excruciating.',
  '患者は腰の痛みをまったく耐えがたいほど激しいと述べた。',
  'Waiting for the medical test results was an excruciating ordeal for the entire family.',
  '検査結果を待つことは家族全員にとって極度に苦しい試練であった。'),
(196, 'versatility', '①汎用性、多用途 ②多芸、多能', '/ˌvɜːrsəˈtɪlɪti/', 'ヴァーサティリティ',
  'The versatility of the new software platform makes it suitable for a wide range of applications.',
  '新しいソフトウェアプラットフォームの汎用性により、幅広い用途に適している。',
  'Her remarkable versatility as a performer allowed her to excel in both comedy and drama.',
  '演者としての彼女の驚くべき多芸さにより、コメディとドラマの両方で優れた成果を上げることができた。'),
(197, 'foliage', '[集合的に](草木の)葉', '/ˈfoʊliɪdʒ/', 'フォウリイジ',
  'The dense foliage of the tropical rainforest blocks out nearly all direct sunlight.',
  '熱帯雨林の密生した葉はほぼすべての直射日光を遮る。',
  'Tourists flock to New England every autumn to admire the spectacular foliage.',
  '毎年秋になると観光客が見事な紅葉を楽しむためにニューイングランドに押し寄せる。'),
(198, 'bequeath', '①(遺言などによって)(動産)を遺す ②~を(後世に)伝える', '/bɪˈkwiːð/', 'ビクウィーズ',
  'The philanthropist bequeathed the entirety of his estate to a charitable trust.',
  'その慈善家は全財産を慈善信託に遺した。',
  'Ancient civilizations bequeathed invaluable knowledge that continues to shape modern science.',
  '古代文明は現代科学を形作り続ける貴重な知識を後世に伝えた。'),
(199, 'cavalier', 'ぞんざいな、気づかいをしない', '/ˌkævəˈlɪr/', 'キャヴァリアー',
  'The executive''s cavalier attitude toward workplace safety regulations drew severe criticism.',
  'その役員の職場安全規制に対するぞんざいな態度は厳しい批判を浴びた。',
  'A cavalier approach to data privacy can expose organizations to significant legal liability.',
  'データプライバシーに対する無頓着な姿勢は組織を重大な法的責任にさらしかねない。'),
(200, 'caliber', '①(高い)質、能力;力量 ②(銃の)口径', '/ˈkælɪbər/', 'キャリバー',
  'The university prides itself on attracting scholars of the highest caliber from around the world.',
  'その大学は世界中から最高の力量を持つ学者を引きつけることを誇りとしている。',
  'A leader of her caliber is precisely what this organization needs to navigate through turbulent times.',
  '彼女ほどの力量を持つリーダーこそ、この組織が困難な時代を乗り越えるために必要な人物だ。');
