-- words テーブル INSERT文 (No.201 ~ No.250)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(201, 'valiant', '勇敢な、勇ましい', '/ˈvæliənt/', 'ヴァリアント',
  'The valiant soldiers held their ground despite being vastly outnumbered by the enemy forces.',
  '勇敢な兵士たちは、敵軍に大幅に数で劣っていたにもかかわらず、陣地を守り抜いた。',
  'She made a valiant effort to salvage the failing company, but the debt was insurmountable.',
  '彼女は破綻しかけた会社を救うために勇敢な努力をしたが、負債は克服できないほどだった。'),
(202, 'incontrovertible', '議論の余地のない、明白な', '/ˌɪnkɒntrəˈvɜːrtɪbl/', 'インコントロヴァーティブル',
  'The DNA evidence presented at the trial was incontrovertible proof of the defendant''s guilt.',
  '裁判で提示されたDNA証拠は、被告人の有罪を示す議論の余地のない証拠だった。',
  'The incontrovertible facts left no room for further debate among the committee members.',
  '明白な事実により、委員会メンバーの間でさらなる議論の余地はなくなった。'),
(203, 'camaraderie', '仲間意識、友情', '/ˌkæməˈrɑːdəri/', 'カマラダリー',
  'The camaraderie among the research team members was evident in their seamless collaboration.',
  '研究チームメンバー間の仲間意識は、彼らのシームレスな協力に表れていた。',
  'Years of working together in adverse conditions forged an unbreakable camaraderie between the firefighters.',
  '過酷な条件下で長年共に働いたことで、消防士たちの間に壊れることのない仲間意識が生まれた。'),
(204, 'embezzle', '(金)を横領する、着服する', '/ɪmˈbɛzl/', 'エンベズル',
  'The chief accountant was found to have embezzled over two million dollars from the corporation.',
  '主任会計士は会社から200万ドル以上を横領していたことが判明した。',
  'He embezzled charitable donations intended for disaster relief and used them for personal gain.',
  '彼は災害救援のための慈善寄付金を着服し、私利私欲のために使った。'),
(205, 'drab', '殺風景な、さえない', '/dræb/', 'ドラブ',
  'The drab office interior, with its grey walls and flickering lights, dampened everyone''s spirits.',
  '灰色の壁とちらつく照明の殺風景なオフィスの内装は、全員の気持ちを沈ませた。',
  'She transformed the drab apartment into a vibrant living space with colorful furnishings.',
  '彼女はさえないアパートをカラフルな家具で生き生きとした住空間に変えた。'),
(206, 'scruple', '(道徳的な)ためらい、良心のとがめ', '/ˈskruːpl/', 'スクループル',
  'He had no scruples about deceiving his business partners to secure the lucrative deal.',
  '彼はその有利な取引を確保するために、ビジネスパートナーを欺くことに何のためらいもなかった。',
  'Her moral scruples prevented her from accepting the bribe, even though it would have solved her financial problems.',
  '彼女の道徳的なためらいが、たとえ経済的問題が解決するとしても、賄賂を受け取ることを妨げた。'),
(207, 'feud', '(長期にわたる)争い、確執', '/fjuːd/', 'フュード',
  'The bitter feud between the two neighboring families had persisted for over three generations.',
  '隣り合う二つの家族間の激しい確執は、三世代以上にわたって続いていた。',
  'A corporate feud over patent rights led to a protracted and costly legal battle.',
  '特許権をめぐる企業間の争いは、長期にわたる費用のかかる法廷闘争に発展した。'),
(208, 'brash', '厚かましい、生意気な', '/bræʃ/', 'ブラッシュ',
  'His brash demeanor during the negotiation alienated potential allies who might have supported his proposal.',
  '交渉中の彼の厚かましい態度は、彼の提案を支持してくれたかもしれない味方を遠ざけた。',
  'The brash young executive made sweeping changes without consulting senior management.',
  '生意気な若い経営幹部は、上級管理職に相談することなく大胆な変更を行った。'),
(209, 'encrypt', '~を暗号化する', '/ɪnˈkrɪpt/', 'エンクリプト',
  'All sensitive data transmitted through the network is encrypted using advanced algorithms.',
  'ネットワークを通じて送信されるすべての機密データは、高度なアルゴリズムを使用して暗号化される。',
  'The whistleblower encrypted the files before sending them to ensure they could not be intercepted.',
  '内部告発者はファイルを送信する前に暗号化し、傍受されないようにした。'),
(210, 'apprehend', '(犯人など)を逮捕する', '/ˌæprɪˈhɛnd/', 'アプリヘンド',
  'Police managed to apprehend the fugitive after a three-month international manhunt.',
  '警察は3か月にわたる国際的な捜索の末、逃亡者を逮捕することに成功した。',
  'The suspect was apprehended at the border while attempting to flee the country with forged documents.',
  '容疑者は偽造書類を持って出国しようとしたところを国境で逮捕された。'),
(211, 'pique', '(好奇心など)を刺激する、かき立てる', '/piːk/', 'ピーク',
  'The professor''s unconventional lecture on quantum mechanics piqued the students'' curiosity.',
  '量子力学に関する教授の型破りな講義は学生たちの好奇心を刺激した。',
  'The mysterious inscription on the ancient artifact piqued the archaeologist''s interest immediately.',
  '古代の遺物に刻まれた謎の碑文は、考古学者の興味を即座にかき立てた。'),
(212, 'infest', '(害虫・害獣などが)(場所)にはびこる', '/ɪnˈfɛst/', 'インフェスト',
  'The abandoned warehouse was infested with rats that had been breeding unchecked for years.',
  '廃倉庫には何年も野放しで繁殖してきたネズミがはびこっていた。',
  'Invasive species of beetles have infested the forest, destroying thousands of hectares of native trees.',
  '外来種のカブトムシが森にはびこり、数千ヘクタールの在来樹木を破壊した。'),
(213, 'gloat', 'ほくそ笑む、満悦する', '/ɡloʊt/', 'グロート',
  'Rather than gloating over his rival''s misfortune, he extended a hand of support.',
  '彼はライバルの不幸にほくそ笑むのではなく、支援の手を差し伸べた。',
  'She could not help but gloat when her controversial prediction turned out to be correct.',
  '彼女の物議を醸した予測が正しいと判明したとき、彼女は満悦せずにはいられなかった。'),
(214, 'archaic', '古い、時代遅れの', '/ɑːrˈkeɪɪk/', 'アーケイイク',
  'The company''s archaic management practices hindered its ability to compete in the modern marketplace.',
  '会社の時代遅れの経営手法は、現代の市場での競争力を妨げていた。',
  'Many archaic laws remain on the statute books despite being completely irrelevant to contemporary society.',
  '現代社会とは全く無関係であるにもかかわらず、多くの古い法律が法令集に残っている。'),
(215, 'veer', '(車・話題などが)方向を変える、それる', '/vɪr/', 'ヴィア',
  'The discussion veered off topic when a participant raised an unrelated but contentious issue.',
  '参加者が無関係だが論争的な問題を持ち出したとき、議論は本題からそれた。',
  'The ship veered sharply to starboard to avoid the submerged reef.',
  '船は沈んだ岩礁を避けるために右舷に急に方向を変えた。'),
(216, 'quell', '(反乱・暴動など)を鎮圧する;(不安・怒りなど)を抑える', '/kwɛl/', 'クウェル',
  'The government deployed additional troops to quell the uprising in the northern provinces.',
  '政府は北部の州での反乱を鎮圧するために追加の部隊を派遣した。',
  'The manager''s reassuring speech did little to quell the employees'' anxiety about impending layoffs.',
  '管理者の安心させるようなスピーチは、差し迫った解雇に対する従業員の不安を抑えるにはほとんど役立たなかった。'),
(217, 'savor', '(活動・経験など)をかみしめる、堪能する;(味・香りを楽しみながら)~を食べる、飲む', '/ˈseɪvər/', 'セイヴァー',
  'After years of relentless work, she finally took a moment to savor her well-deserved success.',
  '何年もの絶え間ない仕事の後、彼女はついに自分のふさわしい成功をかみしめる時間を取った。',
  'The food critic savored each dish meticulously, noting the subtle interplay of flavors.',
  '食評家は各料理を丹念に味わい、風味の繊細な相互作用に注目した。'),
(218, 'frugal', '質素な、倹約的な', '/ˈfruːɡl/', 'フルーガル',
  'Her frugal lifestyle enabled her to accumulate substantial savings despite her modest income.',
  '彼女の質素な生活様式のおかげで、控えめな収入にもかかわらず相当な貯蓄を蓄えることができた。',
  'The frugal entrepreneur reinvested every penny of profit back into the business.',
  '倹約的な起業家は利益の1ペニーたりとも無駄にせず、すべてを事業に再投資した。'),
(219, 'unscathed', '無傷の、無事な', '/ʌnˈskeɪðd/', 'アンスケイズド',
  'Remarkably, all passengers emerged unscathed from the wreckage of the train derailment.',
  '驚くべきことに、列車脱線事故の残骸からすべての乗客が無傷で脱出した。',
  'The company''s reputation remained unscathed despite the intense media scrutiny.',
  '激しいメディアの監視にもかかわらず、会社の評判は無傷のまま残った。'),
(220, 'glut', '供給過剰', '/ɡlʌt/', 'グラット',
  'A glut of crude oil on the global market caused prices to plummet dramatically.',
  '世界市場での原油の供給過剰により、価格が劇的に急落した。',
  'The housing glut in the region has made it exceedingly difficult for developers to sell new properties.',
  'その地域の住宅供給過剰により、デベロッパーが新しい物件を売ることが非常に困難になった。'),
(221, 'knack', 'こつ、要領', '/næk/', 'ナック',
  'She has an uncanny knack for simplifying complex scientific concepts for a lay audience.',
  '彼女は複雑な科学的概念を一般の聴衆向けに簡略化する驚くべきこつを持っている。',
  'Once you get the knack of parallel parking, it becomes almost second nature.',
  '縦列駐車のこつをつかめば、ほとんど無意識にできるようになる。'),
(222, 'farce', '茶番、笑い種', '/fɑːrs/', 'ファース',
  'The election was widely condemned as a farce, with numerous reports of vote rigging.',
  'その選挙は、投票操作の報告が多数あり、茶番として広く非難された。',
  'The so-called investigation turned into a farce when it became clear that key evidence had been deliberately suppressed.',
  '重要な証拠が意図的に隠蔽されていたことが明らかになり、いわゆる調査は茶番に変わった。'),
(223, 'interject', '(言葉)を不意にはさむ、口を出す', '/ˌɪntərˈdʒɛkt/', 'インタージェクト',
  'The chairman interjected a word of caution before the committee proceeded to vote.',
  '委員会が投票に進む前に、議長は注意の言葉を不意にはさんだ。',
  'She politely interjected to correct a factual error in the speaker''s presentation.',
  '彼女は発表者のプレゼンテーションの事実誤認を訂正するために丁寧に口を出した。'),
(224, 'marginally', 'わずかに、かろうじて', '/ˈmɑːrdʒɪnəli/', 'マージナリー',
  'The revised policy has only marginally improved the situation for low-income households.',
  '改定された政策は低所得世帯の状況をわずかに改善したに過ぎなかった。',
  'Sales figures were marginally higher this quarter compared to the same period last year.',
  '今四半期の売上高は昨年の同時期と比べてわずかに高かった。'),
(225, 'broach', '(話題など)を切り出す', '/broʊtʃ/', 'ブローチ',
  'He hesitated to broach the subject of salary negotiations during his first week at the company.',
  '彼は入社最初の週に給与交渉の話題を切り出すことをためらった。',
  'The diplomat carefully broached the sensitive issue of territorial disputes at the summit.',
  '外交官はサミットで領土紛争という微妙な問題を慎重に切り出した。'),
(226, 'misgiving', '(結果・将来などについての)不安、懸念', '/mɪsˈɡɪvɪŋ/', 'ミスギヴィング',
  'Despite her initial misgivings, she accepted the overseas assignment and thrived in the new environment.',
  '当初の不安にもかかわらず、彼女は海外赴任を受け入れ、新しい環境で活躍した。',
  'The board expressed serious misgivings about the proposed merger with the rival firm.',
  '取締役会はライバル企業との合併案について深刻な懸念を表明した。'),
(227, 'reconnaissance', '(軍事的な)偵察、調査', '/rɪˈkɒnɪsəns/', 'リコネサンス',
  'The aerial reconnaissance revealed enemy troop movements along the southern border.',
  '航空偵察により、南部国境沿いの敵軍の動きが明らかになった。',
  'Before launching the operation, the commander ordered a thorough reconnaissance of the terrain.',
  '作戦開始前に、指揮官は地形の徹底的な偵察を命じた。'),
(228, 'infatuated', '夢中になった、のぼせ上がった', '/ɪnˈfætʃueɪtɪd/', 'インファチュエイティド',
  'He became so infatuated with the idea of fame that he neglected his academic responsibilities.',
  '彼は名声という考えに夢中になりすぎて、学業上の責任をおろそかにした。',
  'The public was infatuated with the charismatic leader, overlooking his glaring policy failures.',
  '国民はカリスマ的な指導者にのぼせ上がり、彼の明白な政策の失敗を見過ごした。'),
(229, 'incoherent', '(話・主張などが)筋の通らない、支離滅裂な', '/ˌɪnkoʊˈhɪrənt/', 'インコヒアレント',
  'The witness''s testimony was so incoherent that the jury struggled to extract any useful information.',
  '証人の証言は非常に支離滅裂で、陪審員は有用な情報を引き出すのに苦労した。',
  'His incoherent ramblings during the press conference raised concerns about his fitness for office.',
  '記者会見での彼の支離滅裂なとりとめのない話は、彼の職務適格性に対する懸念を引き起こした。'),
(230, 'morale', '(集団の)士気、やる気', '/məˈræl/', 'モラール',
  'The unexpected victory boosted the team''s morale and reinvigorated their determination to succeed.',
  '予想外の勝利がチームの士気を高め、成功への決意を再び奮い立たせた。',
  'Persistent budget cuts have severely undermined employee morale across the organization.',
  '度重なる予算削減が、組織全体の従業員の士気を著しく損なった。'),
(231, 'substantiate', '(主張・理論など)を実証する、裏づける', '/səbˈstænʃieɪt/', 'サブスタンシエイト',
  'The researcher was unable to substantiate her hypothesis with reproducible experimental data.',
  '研究者は再現可能な実験データで自分の仮説を実証することができなかった。',
  'The auditor demanded documentation to substantiate the company''s financial claims.',
  '監査人は会社の財務上の主張を裏づける書類を要求した。'),
(232, 'erroneous', '誤った、間違いに基づく', '/ɪˈroʊniəs/', 'エロウニアス',
  'The erroneous assumption that demand would continue to grow led to a catastrophic overproduction.',
  '需要が伸び続けるという誤った仮定が、壊滅的な過剰生産を招いた。',
  'Several erroneous entries in the database had to be corrected before the report could be finalized.',
  'レポートを最終決定する前に、データベースのいくつかの誤った項目を修正しなければならなかった。'),
(233, 'exacerbate', '(状況・問題など)を悪化させる', '/ɪɡˈzæsərbeɪt/', 'イグザサベイト',
  'The government''s tariff policies only served to exacerbate the existing trade imbalance.',
  '政府の関税政策は既存の貿易不均衡を悪化させるだけだった。',
  'Prolonged drought has exacerbated the food crisis in the already impoverished region.',
  '長引く干ばつが、すでに貧困にあえぐ地域の食糧危機を悪化させた。'),
(234, 'elusive', 'とらえどころのない、見つけにくい', '/ɪˈluːsɪv/', 'イルーシヴ',
  'A lasting peace agreement in the region has proven to be an elusive goal for decades.',
  'その地域での恒久的な和平合意は、何十年もの間とらえどころのない目標であった。',
  'The elusive snow leopard is rarely spotted in the wild, even by experienced trackers.',
  '見つけにくいユキヒョウは、経験豊富な追跡者でさえ野生で見かけることはめったにない。'),
(235, 'stifle', '(あくび・感情など)を抑える;(発展・自由など)を妨げる', '/ˈstaɪfl/', 'スタイフル',
  'Excessive regulation can stifle innovation and discourage entrepreneurial activity.',
  '過度な規制はイノベーションを妨げ、起業活動を阻害しかねない。',
  'She stifled a yawn during the interminable board meeting, hoping no one would notice.',
  '彼女は果てしなく長い取締役会議の間、誰にも気づかれないようにあくびを抑えた。'),
(236, 'hatch', '(計画・陰謀など)をたくらむ;(卵が)かえる', '/hætʃ/', 'ハッチ',
  'The conspirators hatched an elaborate scheme to overthrow the government from within.',
  '共謀者たちは内部から政府を転覆させるための精巧な計画をたくらんだ。',
  'The sea turtle eggs are expected to hatch within sixty days of being laid on the beach.',
  'ウミガメの卵は浜辺に産み落とされてから60日以内にかえると予想される。'),
(237, 'exorbitant', '(値段・要求などが)法外な、途方もない', '/ɪɡˈzɔːrbɪtənt/', 'イグゾービタント',
  'The exorbitant cost of healthcare has become a major concern for middle-class families.',
  '法外な医療費は中流家庭にとって大きな懸念事項となっている。',
  'Tourists were shocked by the exorbitant prices charged by vendors near the popular landmark.',
  '観光客は人気の名所付近の販売業者が請求する法外な価格に衝撃を受けた。'),
(238, 'confiscate', '(財産・所持品など)を没収する、押収する', '/ˈkɒnfɪskeɪt/', 'コンフィスケイト',
  'Customs officials confiscated a large shipment of counterfeit goods at the port.',
  '税関職員は港で大量の偽造品の出荷を押収した。',
  'The teacher confiscated the student''s mobile phone after it rang during the examination.',
  '試験中に携帯電話が鳴った後、教師は生徒の携帯電話を没収した。'),
(239, 'curtail', '(経費・権利・自由など)を削減する、制限する', '/kɜːrˈteɪl/', 'カーテイル',
  'The company was forced to curtail its expansion plans due to a sudden downturn in the economy.',
  '経済の急激な低迷により、会社は拡大計画を削減せざるを得なかった。',
  'Civil liberties groups protested against the new legislation designed to curtail freedom of speech.',
  '市民的自由団体は、言論の自由を制限するように設計された新しい法律に抗議した。'),
(240, 'cessation', '中止、停止', '/sɛˈseɪʃn/', 'セセイション',
  'Both sides agreed to an immediate cessation of hostilities pending further negotiations.',
  '双方はさらなる交渉を待つ間、敵対行為の即時停止に合意した。',
  'The cessation of funding forced the research institute to abandon several promising projects.',
  '資金の停止により、研究所はいくつかの有望なプロジェクトを断念せざるを得なかった。'),
(241, 'relegate', '(人など)を格下げする、左遷する', '/ˈrɛlɪɡeɪt/', 'レリゲイト',
  'After the restructuring, several senior managers were relegated to advisory roles with diminished authority.',
  '組織再編後、数名の上級管理職は権限が縮小された顧問的役割に格下げされた。',
  'The once-dominant football club was relegated to the second division after a disastrous season.',
  'かつて支配的だったサッカークラブは、悲惨なシーズンの後に2部リーグに降格された。'),
(242, 'bolster', '~を強化する、支える', '/ˈboʊlstər/', 'ボウルスター',
  'The central bank cut interest rates to bolster economic growth during the recession.',
  '中央銀行は不況期の経済成長を支えるために金利を引き下げた。',
  'New clinical trial results significantly bolstered the case for approving the experimental drug.',
  '新しい臨床試験結果は、実験薬の承認に向けた根拠を大幅に強化した。'),
(243, 'reparation', '賠償(金)', '/ˌrɛpəˈreɪʃn/', 'レパレイション',
  'The defeated nation was required to pay substantial reparations to the countries it had invaded.',
  '敗戦国は侵略した国々に対して多額の賠償金を支払うことを求められた。',
  'Advocates have long called for reparations to be paid to descendants of enslaved people.',
  '支持者たちは、奴隷にされた人々の子孫に対する賠償金の支払いを長年求めてきた。'),
(244, 'turmoil', '混乱、騒動', '/ˈtɜːrmɔɪl/', 'ターモイル',
  'The country was plunged into political turmoil following the sudden resignation of the prime minister.',
  '首相の突然の辞任に続いて、国は政治的混乱に陥った。',
  'Financial turmoil in emerging markets sent shockwaves through the global banking system.',
  '新興市場の金融混乱は世界の銀行システムに衝撃を与えた。'),
(245, 'conjure', '(魔法のように)~を出す;~を連想させる', '/ˈkɒndʒər/', 'コンジャー',
  'The chef can conjure up an exquisite meal from the most humble ingredients.',
  'そのシェフは最も素朴な食材から絶品の料理を魔法のように作り出すことができる。',
  'The mere mention of her hometown conjured vivid memories of childhood summers.',
  '故郷の名前を聞くだけで、子供時代の夏の鮮やかな記憶が連想された。'),
(246, 'permeate', '~に浸透する、行き渡る', '/ˈpɜːrmieɪt/', 'パーミエイト',
  'A culture of accountability must permeate every level of the organization for reform to succeed.',
  '改革を成功させるためには、説明責任の文化が組織のあらゆる階層に浸透しなければならない。',
  'The aroma of freshly baked bread permeated the entire neighborhood.',
  '焼きたてのパンの香りが近所全体に行き渡った。'),
(247, 'gist', '要点、骨子', '/dʒɪst/', 'ジスト',
  'Although the lecture was highly technical, she managed to grasp the gist of the argument.',
  '講義は非常に専門的だったが、彼女は議論の要点を把握することができた。',
  'Could you give me the gist of the report? I don''t have time to read the entire document.',
  'レポートの要点を教えていただけますか？全文を読む時間がないのです。'),
(248, 'prolific', '多作の、多産の', '/prəˈlɪfɪk/', 'プロリフィック',
  'The prolific author published over forty novels during her illustrious literary career.',
  'その多作な作家は輝かしい文学的経歴の中で40冊以上の小説を出版した。',
  'The region is known for its prolific agricultural output, supplying produce to the entire country.',
  'その地域は多産な農業生産で知られ、国全体に農産物を供給している。'),
(249, 'admonish', '(人)に忠告する、訓戒する', '/ədˈmɒnɪʃ/', 'アドモニッシュ',
  'The judge admonished the jury to base their verdict solely on the evidence presented in court.',
  '裁判官は陪審員に、法廷で提示された証拠のみに基づいて評決を下すよう訓戒した。',
  'The supervisor admonished the employee for repeatedly violating workplace safety protocols.',
  '上司は職場の安全規定を繰り返し違反した従業員を訓戒した。'),
(250, 'rout', '大敗、惨敗;~を大敗させる', '/raʊt/', 'ラウト',
  'The defending champions suffered a humiliating rout, losing by a margin of six goals.',
  'ディフェンディングチャンピオンは6ゴール差で屈辱的な大敗を喫した。',
  'The opposition forces routed the garrison and seized control of the strategic outpost.',
  '反対勢力は守備隊を大敗させ、戦略的な前哨基地の支配権を奪取した。');
