-- words テーブル INSERT文 (No.301 ~ No.350)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(301, 'penchant', '(強い)好み、嗜好', '/ˈpɛntʃənt/', 'ペンチャント',
  'The renowned architect had a penchant for incorporating natural elements into her ultramodern designs.',
  'その著名な建築家は、超近代的なデザインに自然の要素を取り入れることに強い好みを持っていた。',
  'His penchant for acquiring rare first-edition books eventually transformed his modest apartment into a veritable library.',
  '珍しい初版本を収集する彼の嗜好が、やがて彼の質素なアパートをまさに図書館へと変貌させた。'),
(302, 'vigil', '(夜間の)寝ずの番、見張り', '/ˈvɪdʒɪl/', 'ヴィジル',
  'The community held an all-night vigil outside the hospital while the injured miners underwent emergency surgery.',
  '負傷した鉱山労働者たちが緊急手術を受ける間、地域住民は病院の外で一晩中寝ずの番をした。',
  'Volunteers maintained a constant vigil at the nesting site to protect the endangered sea turtles from poachers.',
  'ボランティアたちは密猟者から絶滅危惧のウミガメを守るため、営巣地で常に見張りを続けた。'),
(303, 'sheepishly', 'きまり悪そうに、おどおどと', '/ˈʃiːpɪʃli/', 'シーピッシュリー',
  'The student sheepishly admitted that he had not read a single chapter of the assigned textbook before the exam.',
  'その学生は、試験前に指定された教科書を一章も読んでいなかったときまり悪そうに認めた。',
  'She sheepishly apologized for accidentally sending the confidential email to the entire company mailing list.',
  '彼女は機密メールを誤って全社メーリングリストに送信してしまったことをおどおどと謝罪した。'),
(304, 'unkempt', '(外見が)だらしない、手入れされていない', '/ʌnˈkɛmpt/', 'アンケンプト',
  'The once-magnificent estate had become unkempt and overgrown after years of neglect by its absentee owners.',
  'かつて壮麗だったその屋敷は、不在の所有者によって何年も放置され、だらしなく草木が生い茂っていた。',
  'Despite his unkempt appearance, the professor was widely regarded as one of the most brilliant minds in quantum physics.',
  'だらしない外見にもかかわらず、その教授は量子物理学において最も優れた頭脳の一人として広く認められていた。'),
(305, 'wince', '(痛み・不快さに)たじろぐ、顔をしかめる', '/wɪns/', 'ウィンス',
  'The patient winced as the nurse carefully removed the bandage from the freshly sutured wound.',
  '看護師が縫合したばかりの傷口から包帯を慎重に外すと、患者は顔をしかめた。',
  'He could not help but wince when he recalled the embarrassing speech he had delivered at the annual gala.',
  '年次ガラで行った恥ずかしいスピーチを思い出すと、彼はたじろがずにはいられなかった。'),
(306, 'dilapidated', '(建物などが)荒れ果てた、老朽化した', '/dɪˈlæpɪdeɪtɪd/', 'ディラピデイティッド',
  'The city council allocated a substantial budget to demolish dilapidated structures that posed safety hazards to residents.',
  '市議会は住民に安全上の危険をもたらす老朽化した建造物を取り壊すために多額の予算を計上した。',
  'What was once a dilapidated warehouse on the waterfront has been transformed into a thriving cultural center.',
  'かつて海岸沿いの荒れ果てた倉庫だった建物が、活気ある文化センターへと生まれ変わった。'),
(307, 'blemish', '欠点、傷;~を傷つける', '/ˈblɛmɪʃ/', 'ブレミッシュ',
  'A single ethical scandal was enough to blemish the politician''s otherwise impeccable reputation irreparably.',
  'たった一つの倫理的スキャンダルで、その政治家の完璧だった評判が取り返しのつかないほど傷ついた。',
  'The antique dealer examined the porcelain vase meticulously for any blemish that might diminish its auction value.',
  '骨董品商はオークション価値を下げる可能性のある傷がないか、磁器の花瓶を綿密に調べた。'),
(308, 'paltry', '(量・金額などが)わずかな、取るに足りない', '/ˈpɔːltri/', 'ポールトリー',
  'The workers went on strike after management offered a paltry two-percent raise despite record-breaking profits.',
  '経営陣が記録的な利益にもかかわらずわずか2パーセントの昇給を提示したため、労働者たちはストライキに入った。',
  'The paltry evidence presented by the prosecution was insufficient to convince the jury of the defendant''s guilt.',
  '検察が提示した取るに足りない証拠は、被告の有罪を陪審員に確信させるには不十分だった。'),
(309, 'ambivalent', '相反する感情を持った、両価的な', '/æmˈbɪvələnt/', 'アンビヴァレント',
  'Many citizens remain ambivalent about the proposed nuclear energy policy, recognizing both its benefits and its risks.',
  '多くの市民は、提案された原子力エネルギー政策について、その利点とリスクの両方を認識し、相反する感情を持ったままである。',
  'She felt ambivalent about accepting the prestigious overseas posting, as it meant leaving her aging parents behind.',
  '彼女は名誉ある海外赴任を受け入れることに相反する感情を抱いていた。年老いた両親を残すことになるからだ。'),
(310, 'hermit', '隠者、世捨て人', '/ˈhɜːrmɪt/', 'ハーミット',
  'After decades of public life, the retired diplomat chose to live as a hermit in a remote mountain cabin.',
  '何十年もの公的生活のあと、引退した外交官は人里離れた山小屋で隠者として暮らすことを選んだ。',
  'The legendary hermit who dwelled in the forest was rumored to possess extraordinary knowledge of medicinal herbs.',
  '森に住む伝説の隠者は、薬草に関する並外れた知識を持っていると噂されていた。'),
(311, 'quench', '(渇き)を癒す;(火)を消す', '/kwɛntʃ/', 'クウェンチ',
  'After the grueling marathon, nothing could quench her thirst quite like a glass of ice-cold spring water.',
  '過酷なマラソンのあと、彼女の渇きを癒すものは氷のように冷たい湧き水に勝るものはなかった。',
  'Firefighters struggled for hours to quench the blaze that had engulfed the historic textile factory.',
  '消防士たちは歴史ある繊維工場を飲み込んだ炎を消すために何時間も奮闘した。'),
(312, 'dispel', '(不安・疑惑など)を払いのける、一掃する', '/dɪˈspɛl/', 'ディスペル',
  'The CEO held an emergency press conference to dispel the rumors of an impending corporate merger.',
  'CEOは差し迫った企業合併の噂を払いのけるために緊急記者会見を開いた。',
  'The comprehensive scientific report helped dispel widespread misconceptions about the safety of genetically modified crops.',
  'その包括的な科学報告書は、遺伝子組み換え作物の安全性に関する広範な誤解を一掃するのに役立った。'),
(313, 'wrath', '猛烈な怒り、激怒', '/ræθ/', 'ラス',
  'The monarch''s wrath was legendary, and even his closest advisors feared contradicting him in matters of state.',
  'その君主の激怒は伝説的であり、最も近い側近でさえ国政の問題で彼に反論することを恐れた。',
  'Environmental activists warned that humanity would face the wrath of nature if deforestation continued unchecked.',
  '環境活動家たちは、森林破壊が抑制されなければ人類は自然の猛烈な怒りに直面するだろうと警告した。'),
(314, 'polarize', '(意見などを)二極化する、対立させる', '/ˈpoʊləraɪz/', 'ポウラライズ',
  'The controversial immigration bill has polarized the electorate into fiercely opposing camps ahead of the election.',
  '物議を醸す移民法案が選挙を前に有権者を激しく対立する陣営に二極化させた。',
  'Social media algorithms tend to polarize public opinion by reinforcing users'' pre-existing beliefs and biases.',
  'ソーシャルメディアのアルゴリズムは、ユーザーの既存の信念や偏見を強化することで世論を二極化する傾向がある。'),
(315, 'condolence', '哀悼、弔意', '/kənˈdoʊləns/', 'コンドウレンス',
  'World leaders conveyed their heartfelt condolences to the families of the victims of the devastating earthquake.',
  '世界の首脳たちは壊滅的な地震の犠牲者の家族に心からの哀悼の意を伝えた。',
  'She sent a handwritten letter of condolence to her colleague, who had recently lost his mother to a prolonged illness.',
  '彼女は長い闘病の末に母親を亡くした同僚に、手書きの弔意の手紙を送った。'),
(316, 'charlatan', 'ペテン師、いんちき', '/ˈʃɑːrlətən/', 'シャーラタン',
  'The investigative journalist exposed the self-proclaimed healer as a charlatan who had defrauded desperate patients.',
  '調査報道のジャーナリストが、自称ヒーラーを絶望した患者を騙したペテン師として暴露した。',
  'Throughout history, charlatans have exploited public ignorance to peddle fraudulent remedies for incurable diseases.',
  '歴史を通じて、ペテン師たちは不治の病に対する詐欺的な治療法を売りつけるために大衆の無知を利用してきた。'),
(317, 'succinct', '簡潔な、簡明な', '/səkˈsɪŋkt/', 'サクスィンクト',
  'The professor was praised for her succinct explanation of an otherwise bewilderingly complex quantum phenomenon.',
  'その教授は、他の方法では途方もなく複雑な量子現象を簡潔に説明したことで称賛された。',
  'In diplomatic communications, a succinct message is often more effective than a lengthy and elaborate memorandum.',
  '外交通信においては、簡潔なメッセージの方が長々とした手の込んだ覚書よりも効果的であることが多い。'),
(318, 'infraction', '(法・規則の)違反', '/ɪnˈfrækʃən/', 'インフラクション',
  'Even a minor infraction of the laboratory safety protocol could result in immediate suspension of research privileges.',
  '研究室の安全規定のわずかな違反でも、研究権限の即時停止につながる可能性がある。',
  'The athlete was penalized for a technical infraction that ultimately cost her team the championship title.',
  'その選手は技術的な違反で罰せられ、最終的にチームの優勝タイトルを失うことになった。'),
(319, 'detract', '(価値・功績など)を損なう', '/dɪˈtrækt/', 'ディトラクト',
  'The minor typographical errors in the manuscript did little to detract from the brilliance of the author''s argument.',
  '原稿の些細な誤植は、著者の論点の素晴らしさをほとんど損なうものではなかった。',
  'Critics argued that the excessive use of special effects actually detracted from the film''s compelling narrative.',
  '批評家たちは、過度な特殊効果の使用が実際には映画の説得力ある物語を損なっていると主張した。'),
(320, 'gorge', '渓谷;大量に食べる、がつがつ食べる', '/ɡɔːrdʒ/', 'ゴージ',
  'Hikers marveled at the breathtaking gorge carved by millennia of relentless river erosion through the limestone plateau.',
  'ハイカーたちは石灰岩台地を何千年もの絶え間ない河川浸食によって刻まれた息をのむような渓谷に感嘆した。',
  'After fasting for the entire day, the pilgrims could not resist the temptation to gorge themselves on the festive feast.',
  '丸一日断食したあと、巡礼者たちは祝祭の宴でがつがつ食べる誘惑に抵抗できなかった。'),
(321, 'acquittal', '無罪判決、無罪放免', '/əˈkwɪtl/', 'アクウィトル',
  'The defendant''s acquittal on all charges sent shockwaves through the legal community and the general public alike.',
  '被告の全ての罪状に対する無罪判決は、法曹界と一般市民の双方に衝撃を与えた。',
  'Despite the acquittal, the prolonged trial had already inflicted irreparable damage on the accused''s professional reputation.',
  '無罪判決にもかかわらず、長期にわたる裁判はすでに被告の職業的評判に取り返しのつかない損害を与えていた。'),
(322, 'lurch', 'よろめく、ふらつく', '/lɜːrtʃ/', 'ラーチ',
  'The overcrowded ferry lurched violently to one side as passengers scrambled to evacuate during the sudden storm.',
  '突然の嵐の中、乗客が避難しようと殺到した際、過密状態のフェリーが片側に激しくよろめいた。',
  'The economy lurched from one crisis to another, leaving policymakers struggling to maintain fiscal stability.',
  '経済が次々と危機によろめき、政策立案者たちは財政の安定を維持するのに苦慮した。'),
(323, 'adorn', '~を飾る、装飾する', '/əˈdɔːrn/', 'アドーン',
  'Intricate mosaics depicting mythological scenes adorned the walls of the recently excavated Roman villa.',
  '神話の場面を描いた精緻なモザイクが、最近発掘されたローマ時代の別荘の壁を飾っていた。',
  'The bride adorned her hair with delicate wildflowers, reflecting the rustic elegance of the countryside wedding.',
  '花嫁は繊細な野の花で髪を飾り、田舎の結婚式の素朴な優雅さを映し出した。'),
(324, 'rubble', 'がれき、瓦礫', '/ˈrʌbl/', 'ラブル',
  'Rescue teams worked around the clock, sifting through the rubble in a desperate search for survivors of the collapsed building.',
  '救助隊は崩壊した建物の生存者を必死に探すため、がれきの中を24時間体制で捜索した。',
  'Years after the devastating conflict, entire neighborhoods remained buried under mountains of rubble and twisted steel.',
  '壊滅的な紛争から何年も経った後も、街区全体ががれきとねじ曲がった鉄骨の山の下に埋もれたままだった。'),
(325, 'homage', '敬意、尊敬', '/ˈhɒmɪdʒ/', 'ホミッジ',
  'The composer''s latest symphony was a profound homage to the indigenous musical traditions of her homeland.',
  'その作曲家の最新の交響曲は、彼女の故郷の先住民の音楽伝統に対する深い敬意の表れだった。',
  'Thousands of admirers gathered at the monument to pay homage to the civil rights leader on the anniversary of his passing.',
  '何千人もの崇拝者が公民権運動の指導者の命日にその記念碑に集まり敬意を表した。'),
(326, 'stint', '(ある仕事・活動の)期間、任期', '/stɪnt/', 'スティント',
  'After a brief stint as an ambassador in Southeast Asia, she returned to academia to pursue her research on geopolitics.',
  '東南アジアでの短い大使在任期間のあと、彼女は地政学の研究を追求するために学界に戻った。',
  'His two-year stint at the startup gave him invaluable experience in entrepreneurship and venture capital negotiation.',
  'スタートアップでの2年間の期間が、彼に起業とベンチャーキャピタル交渉における貴重な経験を与えた。'),
(327, 'procure', '(苦労して)~を入手する、調達する', '/prəˈkjʊr/', 'プロキュア',
  'The humanitarian organization managed to procure essential medical supplies despite the severe trade embargo.',
  '人道支援団体は厳しい通商禁止にもかかわらず、不可欠な医療物資を調達することができた。',
  'It took the museum curator nearly a decade to procure the rare manuscript from a private collector in Vienna.',
  '博物館の学芸員がウィーンの個人収集家からその希少な写本を入手するのにほぼ10年を要した。'),
(328, 'mortify', '(人)に恥をかかせる、屈辱を与える', '/ˈmɔːrtɪfaɪ/', 'モーティファイ',
  'The diplomat was mortified when a recording of his private remarks about the host country was leaked to the press.',
  'その外交官は、受入国に関する私的な発言の録音がマスコミに漏洩した際に屈辱を受けた。',
  'She was utterly mortified to discover that her confidential report had been circulated among all department heads.',
  '彼女は自分の機密報告書が全部門長の間に回覧されていたことを知り、完全に恥辱を感じた。'),
(329, 'fret', 'くよくよする、やきもきする', '/frɛt/', 'フレット',
  'Parents often fret over their children''s academic performance, sometimes to the detriment of the child''s mental health.',
  '親はしばしば子どもの学業成績についてくよくよし、時にはそれが子どもの精神的健康を害することもある。',
  'There is no point in fretting about circumstances that are entirely beyond our control, the therapist advised.',
  '全く自分ではどうにもならない状況についてやきもきしても仕方がない、とセラピストは助言した。'),
(330, 'denigrate', '(人・評判など)をけなす、中傷する', '/ˈdɛnɪɡreɪt/', 'デニグレイト',
  'The opposition party attempted to denigrate the incumbent''s achievements in order to sway undecided voters.',
  '野党は態度未定の有権者を動かすために、現職の実績をけなそうとした。',
  'It is both unprofessional and unethical to denigrate a colleague''s research merely out of personal rivalry.',
  '個人的な対抗心から同僚の研究を中傷するのは、非専門的であり非倫理的でもある。'),
(331, 'consecrate', '~を(神に)ささげる、奉納する', '/ˈkɒnsɪkreɪt/', 'コンセクレイト',
  'The ancient cathedral was originally consecrated in the twelfth century and has undergone numerous restorations since.',
  'その古い大聖堂は12世紀に奉献され、以来数多くの修復が行われてきた。',
  'The memorial site was consecrated to honor the soldiers who had sacrificed their lives during the liberation campaign.',
  'その記念地は解放作戦中に命を犠牲にした兵士たちを称えるために奉納された。'),
(332, 'ultimatum', '最後通告、最終条件', '/ˌʌltɪˈmeɪtəm/', 'アルティメイタム',
  'The labor union issued an ultimatum to the management, demanding improved working conditions within seventy-two hours.',
  '労働組合は経営陣に対し、72時間以内に労働条件を改善するよう最後通告を発した。',
  'Faced with an ultimatum from the international coalition, the regime reluctantly agreed to dismantle its weapons program.',
  '国際連合からの最後通告に直面し、その政権はしぶしぶ兵器プログラムの解体に同意した。'),
(333, 'fidelity', '忠実さ、誠実さ;正確さ', '/fɪˈdɛlɪti/', 'フィデリティ',
  'The translator was commended for her fidelity to the original text, preserving both its meaning and its poetic nuance.',
  'その翻訳者は原文への忠実さが称賛され、意味と詩的なニュアンスの両方を保っていた。',
  'His unwavering fidelity to his principles earned him respect even from those who disagreed with his political stance.',
  '自らの信条への揺るぎない誠実さが、彼の政治的立場に反対する人々からも尊敬を得た。'),
(334, 'premium', '割増金、プレミアム;保険料', '/ˈpriːmiəm/', 'プリーミアム',
  'Consumers are increasingly willing to pay a premium for products that are ethically sourced and environmentally sustainable.',
  '消費者は倫理的に調達され環境的に持続可能な製品に割増金を払うことにますます前向きである。',
  'The sharp rise in natural disaster frequency has driven insurance premiums to unprecedented levels across the region.',
  '自然災害の頻度の急激な増加が、地域全体で保険料を前例のない水準に押し上げた。'),
(335, 'susceptible', '影響を受けやすい、感染しやすい', '/səˈsɛptɪbl/', 'サセプティブル',
  'Elderly individuals and those with compromised immune systems are particularly susceptible to respiratory infections.',
  '高齢者や免疫機能が低下している人は、呼吸器感染症に特に感染しやすい。',
  'Adolescents are especially susceptible to peer pressure, which can profoundly influence their decision-making processes.',
  '青年期の若者は仲間からの圧力に特に影響を受けやすく、それが意思決定に大きな影響を及ぼし得る。'),
(336, 'debris', '破片、がれき', '/dəˈbriː/', 'デブリー',
  'Space debris orbiting the Earth poses an increasing threat to operational satellites and manned spacecraft.',
  '地球を周回する宇宙ゴミが、運用中の人工衛星や有人宇宙船に対する脅威を増大させている。',
  'After the tornado subsided, residents returned to find their homes reduced to scattered debris across the landscape.',
  '竜巻が収まったあと、住民たちは自宅が一面に散らばった破片と化しているのを目の当たりにした。'),
(337, 'revitalize', '~に新しい活力を与える、~を再活性化する', '/riːˈvaɪtəlaɪz/', 'リーヴァイタライズ',
  'The ambitious urban renewal project aims to revitalize the neglected waterfront district into a vibrant commercial hub.',
  'その野心的な都市再開発計画は、放置された臨海地区を活気ある商業拠点へと再活性化することを目指している。',
  'The newly appointed director introduced innovative programs designed to revitalize the museum''s dwindling visitor numbers.',
  '新たに任命された館長は、減少する来館者数を再活性化するために革新的なプログラムを導入した。'),
(338, 'instill', '(思想・感情など)を徐々に教え込む、植え付ける', '/ɪnˈstɪl/', 'インスティル',
  'Effective educators strive to instill a genuine love of learning in their students rather than merely transmitting facts.',
  '優れた教育者は、単に事実を伝えるのではなく、生徒に学ぶことへの本当の愛情を徐々に植え付けようと努力する。',
  'The military academy sought to instill discipline, resilience, and a strong sense of duty in every cadet.',
  '陸軍士官学校は、すべての士官候補生に規律、回復力、そして強い義務感を教え込もうとした。'),
(339, 'hassle', '面倒(なこと)、煩わしさ', '/ˈhæsl/', 'ハッスル',
  'Commuters regard the daily hassle of navigating congested highways as one of the most stressful aspects of urban life.',
  '通勤者たちは混雑した高速道路を走る日々の煩わしさを、都市生活で最もストレスの多い側面の一つと見なしている。',
  'Renewing the visa proved to be such a bureaucratic hassle that many applicants simply gave up midway through the process.',
  'ビザの更新はあまりにも官僚的な面倒であったため、多くの申請者が手続きの途中で諦めてしまった。'),
(340, 'opt', '選ぶ、選択する', '/ɒpt/', 'オプト',
  'An increasing number of graduates are opting for careers in the nonprofit sector over lucrative corporate positions.',
  '高収入の企業の職よりも非営利部門でのキャリアを選ぶ卒業生が増えている。',
  'Several multinational corporations have opted to relocate their headquarters to countries with more favorable tax regimes.',
  'いくつかの多国籍企業が、より有利な税制度を持つ国に本社を移転することを選択した。'),
(341, 'disparate', '(根本的に)異なる、共通点のない', '/ˈdɪspərət/', 'ディスパレト',
  'The committee struggled to reconcile the disparate viewpoints of stakeholders from vastly different cultural backgrounds.',
  '委員会は、大きく異なる文化的背景を持つ利害関係者の根本的に異なる見解を調和させるのに苦労した。',
  'The researcher synthesized data from disparate sources to construct a comprehensive model of climate change impacts.',
  'その研究者は気候変動の影響の包括的なモデルを構築するため、共通点のない情報源からデータを統合した。'),
(342, 'elicit', '(情報・反応など)を引き出す', '/ɪˈlɪsɪt/', 'イリスィト',
  'The prosecutor''s incisive questioning was designed to elicit a confession from the reluctant witness on the stand.',
  '検察官の鋭い質問は、証言台に立つ消極的な証人から自白を引き出すためのものだった。',
  'The controversial artwork elicited a wide range of responses, from enthusiastic praise to vehement condemnation.',
  'その物議を醸す芸術作品は、熱烈な賞賛から激しい非難まで幅広い反応を引き出した。'),
(343, 'robust', '頑丈な、たくましい;(経済などが)力強い', '/roʊˈbʌst/', 'ロウバスト',
  'The country''s robust economic growth over the past decade has lifted millions of citizens out of poverty.',
  'この国の過去10年間の力強い経済成長は、何百万人もの国民を貧困から救い出した。',
  'Engineers designed a robust infrastructure capable of withstanding earthquakes of up to magnitude eight on the Richter scale.',
  '技術者たちはリヒタースケールでマグニチュード8までの地震に耐えられる頑丈なインフラを設計した。'),
(344, 'shun', '(人・場所・物事)を避ける、遠ざける', '/ʃʌn/', 'シャン',
  'After the financial scandal was made public, former allies shunned the disgraced executive at every social gathering.',
  '金融スキャンダルが公になった後、かつての味方はあらゆる社交の場で不名誉な幹部を避けた。',
  'The reclusive author shunned all forms of publicity, preferring to let her literary works speak for themselves.',
  'その引きこもりがちな作家はあらゆる形の宣伝を避け、自らの文学作品にすべてを語らせることを好んだ。'),
(345, 'nomadic', '遊牧の、放浪の', '/noʊˈmædɪk/', 'ノウマディック',
  'The nomadic tribes of Central Asia have preserved their ancestral traditions despite the pressures of modernization.',
  '中央アジアの遊牧民族は、近代化の圧力にもかかわらず先祖代々の伝統を守り続けてきた。',
  'The rise of remote work has given birth to a new generation of nomadic professionals who travel the world while working.',
  'リモートワークの台頭は、働きながら世界を旅する新世代の放浪するプロフェッショナルを生み出した。'),
(346, 'disperse', '散らす、追い散らす;散る、散開する', '/dɪˈspɜːrs/', 'ディスパース',
  'Police used water cannons to disperse the crowd of demonstrators who had blockaded the main government building.',
  '警察は主要な政府庁舎を封鎖したデモ隊を追い散らすために放水砲を使用した。',
  'Seeds of the invasive plant species were dispersed across the continent by migratory birds and prevailing winds.',
  '侵入植物種の種子は渡り鳥と卓越風によって大陸中に散布された。'),
(347, 'havoc', '大損害、大混乱', '/ˈhævək/', 'ハヴォック',
  'The unprecedented cyberattack wreaked havoc on the nation''s financial infrastructure, paralyzing banking operations for days.',
  '前例のないサイバー攻撃が国の金融インフラに大損害をもたらし、銀行業務を数日間麻痺させた。',
  'Climate change continues to wreak havoc on agricultural yields, threatening food security in vulnerable regions worldwide.',
  '気候変動は農業収穫量に大混乱をもたらし続け、世界中の脆弱な地域の食料安全保障を脅かしている。'),
(348, 'mar', '~を台なしにする、損なう', '/mɑːr/', 'マー',
  'An unforeseen diplomatic incident marred the otherwise successful international summit held in the capital.',
  '予期せぬ外交上の事件が、首都で開催されたそれ以外は成功した国際サミットを台なしにした。',
  'The singer''s magnificent performance was marred by persistent technical difficulties with the sound system.',
  'その歌手の素晴らしい演奏は、音響システムの絶え間ない技術的問題によって損なわれた。'),
(349, 'inception', '(組織・制度などの)発足、始まり', '/ɪnˈsɛpʃən/', 'インセプション',
  'Since its inception in the early twentieth century, the organization has championed the rights of displaced populations.',
  '20世紀初頭の発足以来、その組織は避難民の権利を擁護してきた。',
  'The research program has received over two billion dollars in funding since its inception five years ago.',
  'その研究プログラムは5年前の発足以来、20億ドルを超える資金を受けてきた。'),
(350, 'resurgence', '復活、再起', '/rɪˈsɜːrdʒəns/', 'リサージェンス',
  'The resurgence of traditional craftsmanship in rural communities has attracted significant attention from international buyers.',
  '農村地域における伝統的な職人技の復活が、国際的な買い手から大きな注目を集めている。',
  'Public health officials are alarmed by the resurgence of infectious diseases once thought to have been eradicated.',
  '公衆衛生当局は、かつて根絶されたと思われていた感染症の再発に警戒している。');
