-- words テーブル INSERT文 (No.451 ~ No.500)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(451, 'proliferate', '急増する、拡散する;~を急増させる', '/prəˈlɪfəreɪt/', 'プロリファレイト',
  'Social media platforms have allowed misinformation to proliferate at an unprecedented rate across the globe.',
  'ソーシャルメディアのプラットフォームにより、誤情報が世界中でかつてない速さで拡散するようになった。',
  'Invasive species began to proliferate in the lake after the ecosystem was disrupted by industrial pollution.',
  '産業汚染によって生態系が破壊された後、外来種がその湖で急増し始めた。'),
(452, 'boisterous', '(子ども・動物・振る舞いなどが)騒がしい', '/ˈbɔɪstərəs/', 'ボイスタラス',
  'The boisterous children ran through the corridors, their laughter echoing off the stone walls of the old castle.',
  '騒がしい子どもたちが廊下を駆け抜け、笑い声が古い城の石壁に反響した。',
  'The professor struggled to maintain order during the boisterous debate that erupted among the graduate students.',
  '教授は大学院生の間で勃発した騒がしい議論の中で秩序を保つのに苦労した。'),
(453, 'coax', '(人・動物・もの)をうまく連れ出す、救い出す;(人)を説得する、なだめすかす', '/koʊks/', 'コウクス',
  'The veterinarian gently coaxed the frightened kitten out from under the examination table with a soft voice.',
  '獣医は優しい声で怯えた子猫を診察台の下からうまく連れ出した。',
  'She managed to coax her reluctant colleague into presenting the controversial findings at the international conference.',
  '彼女は消極的な同僚を説得して、その物議を醸す研究結果を国際会議で発表させることに成功した。'),
(454, 'teem', '(場所が)(人・動物などが)多い、うようよいる', '/tiːm/', 'ティーム',
  'The tropical rainforest teemed with exotic wildlife that had never been documented by scientists before.',
  'その熱帯雨林にはこれまで科学者に記録されたことのない珍しい野生動物がうようよいた。',
  'On weekends, the bustling marketplace teems with vendors and tourists from every corner of the world.',
  '週末になると、にぎやかな市場は世界中から来た露天商や観光客であふれかえる。'),
(455, 'pariah', 'のけ者、嫌われ者', '/pəˈraɪə/', 'パライア',
  'After the corruption scandal was exposed, the once-revered politician became a pariah in his own community.',
  '汚職スキャンダルが暴露された後、かつて尊敬されていたその政治家は自分のコミュニティでのけ者になった。',
  'The whistleblower was treated as a pariah by former colleagues who viewed the disclosure as a betrayal.',
  '内部告発者は、その情報開示を裏切りと見なした元同僚たちからのけ者扱いされた。'),
(456, 'vanity', '(容姿・能力などについての)うぬぼれ、虚栄心', '/ˈvænəti/', 'ヴァニティ',
  'His excessive vanity prevented him from accepting constructive criticism, ultimately hindering his professional growth.',
  '過度の虚栄心のせいで建設的な批判を受け入れられず、結果的に職業的成長が妨げられた。',
  'The novel explores the destructive nature of vanity through the downfall of its protagonist, a celebrated artist.',
  'その小説は、著名な芸術家である主人公の没落を通して、虚栄心の破壊的な性質を描いている。'),
(457, 'cumbersome', '(大きさ・重さのために)扱いづらい、運びづらい', '/ˈkʌmbərsəm/', 'カンバーサム',
  'The cumbersome bureaucratic procedures deterred many small businesses from applying for government grants.',
  '扱いづらい官僚的な手続きのせいで、多くの中小企業が政府の助成金への申請をためらった。',
  'Transporting the cumbersome equipment through the narrow mountain trails proved far more difficult than anticipated.',
  '狭い山道を通ってその運びづらい機材を輸送するのは、予想よりもはるかに困難であった。'),
(458, 'deplorable', 'ひどい、悲惨な;嘆かわしい、悲しむべき', '/dɪˈplɔːrəbl/', 'ディプローラブル',
  'The humanitarian organization condemned the deplorable living conditions in the overcrowded refugee camp.',
  '人道支援組織は過密状態の難民キャンプの悲惨な生活環境を非難した。',
  'The committee described the lack of funding for public education as deplorable and called for immediate reform.',
  '委員会は公教育への資金不足を嘆かわしいと述べ、即座の改革を求めた。'),
(459, 'extrovert', '外向性の人、社交的な人', '/ˈekstrəvɜːrt/', 'エクストラヴァート',
  'As a natural extrovert, she thrived in roles that required constant interaction with clients and stakeholders.',
  '生まれながらの外向性の人である彼女は、顧客や利害関係者との絶え間ないやり取りを必要とする役割で力を発揮した。',
  'The research suggested that extroverts tend to perform better in collaborative work environments than in isolated settings.',
  'その研究は、外向性の人は孤立した環境よりも協働的な職場環境でより良い成果を出す傾向があると示唆した。'),
(460, 'bravado', '虚勢、強がり', '/brəˈvɑːdoʊ/', 'ブラヴァードウ',
  'Behind his outward bravado, the young soldier was trembling with fear as the battle drew closer.',
  '表面上の虚勢の裏で、その若い兵士は戦闘が近づくにつれ恐怖で震えていた。',
  'Her bravado during the negotiation concealed the fact that she had very little leverage against the opposing party.',
  '交渉中の彼女の強がりは、相手方に対してほとんど交渉力がないという事実を隠していた。'),
(461, 'dogmatic', '独断的な、独善的な;教義上の、教義に関する', '/dɒɡˈmætɪk/', 'ドグマティック',
  'The professor''s dogmatic insistence on outdated theories alienated many of his more progressive students.',
  '時代遅れの理論に対するその教授の独断的な固執は、より進歩的な学生の多くを遠ざけた。',
  'A dogmatic approach to management stifles creativity and discourages employees from proposing innovative solutions.',
  '独断的な経営手法は創造性を抑圧し、従業員が革新的な解決策を提案する意欲を削ぐ。'),
(462, 'lavish', 'ぜいたくな、豪華な;気前のよい、惜しまない', '/ˈlævɪʃ/', 'ラヴィッシュ',
  'The corporation hosted a lavish gala to celebrate its centennial anniversary, sparing no expense on the decorations.',
  'その企業は創立100周年を祝うために豪華なガラパーティーを開催し、装飾に費用を惜しまなかった。',
  'Critics accused the government of lavish spending on ceremonial events while essential public services were underfunded.',
  '批評家たちは、必要不可欠な公共サービスが資金不足であるのに儀式的な行事にぜいたくな支出をしていると政府を非難した。'),
(463, 'contrive', '(装置・方法など)を考案する;(計略・悪事など)を企む、もくろむ', '/kənˈtraɪv/', 'コントライヴ',
  'The engineer contrived an ingenious mechanism that could filter seawater into potable water using minimal energy.',
  'その技術者は最小限のエネルギーで海水を飲料水にろ過できる巧妙な装置を考案した。',
  'The opposition party contrived a scheme to undermine the ruling coalition before the upcoming election.',
  '野党は次の選挙を前に与党連合を弱体化させる策略を企んだ。'),
(464, 'slur', '誹謗、中傷', '/slɜːr/', 'スラー',
  'The journalist filed a defamation lawsuit after a prominent politician directed a racial slur at her during a press conference.',
  'その記者は著名な政治家が記者会見中に人種的な中傷を浴びせた後、名誉毀損訴訟を起こした。',
  'The candidate''s campaign was marred by repeated slurs against his opponents, which alienated moderate voters.',
  'その候補者の選挙運動は対立候補への度重なる誹謗で傷つき、穏健派の有権者を遠ざけた。'),
(465, 'omen', '(よいこと・悪いことの)前兆、前触れ', '/ˈoʊmən/', 'オウメン',
  'The sudden appearance of dark clouds on the morning of the expedition was regarded as an ill omen by the superstitious crew.',
  '遠征の朝に突然現れた暗雲は、迷信深い乗組員たちに不吉な前兆と見なされた。',
  'Many investors interpreted the unexpected surge in stock prices as a favorable omen for the struggling economy.',
  '多くの投資家は株価の予想外の急騰を低迷する経済にとっての良い前兆と解釈した。'),
(466, 'imposition', '(負担などの)押しつけ、無理強い;負荷物、税、負担', '/ˌɪmpəˈzɪʃən/', 'インポジション',
  'The imposition of strict trade tariffs on imported goods sparked a heated diplomatic dispute between the two nations.',
  '輸入品に対する厳格な貿易関税の課税が、二国間の激しい外交紛争を引き起こした。',
  'Many employees viewed the sudden imposition of mandatory overtime as an unreasonable burden on their personal lives.',
  '多くの従業員は突然の強制残業の押しつけを私生活への不当な負担と見なした。'),
(467, 'abdicate', '(王位・権利など)を放棄する', '/ˈæbdɪkeɪt/', 'アブディケイト',
  'King Edward VIII famously abdicated the British throne in 1936 to marry the American divorcée Wallis Simpson.',
  'エドワード8世は1936年にアメリカ人の離婚経験者ウォリス・シンプソンと結婚するために英国王位を放棄したことで有名である。',
  'By refusing to address the crisis, the prime minister was accused of abdicating her responsibility to the nation.',
  '危機に対処することを拒否したことで、首相は国家に対する責任を放棄したと非難された。'),
(468, 'swindle', '(人)をだます、(人から)(金)をだまし取る', '/ˈswɪndl/', 'スウィンドル',
  'The fraudulent investment firm swindled thousands of retirees out of their life savings through an elaborate Ponzi scheme.',
  '詐欺的な投資会社は巧妙なネズミ講を通じて何千人もの退職者から老後の蓄えをだまし取った。',
  'He was sentenced to fifteen years in prison for swindling charitable organizations by fabricating fictitious beneficiaries.',
  '彼は架空の受益者をでっち上げて慈善団体をだましたとして15年の懲役を言い渡された。'),
(469, 'slouch', '前かがみになる、だらけた格好をする', '/slaʊtʃ/', 'スラウチ',
  'The physiotherapist warned her patient that continuing to slouch at his desk would exacerbate his chronic back pain.',
  '理学療法士は患者に、デスクで前かがみの姿勢を続けると慢性的な腰痛が悪化すると警告した。',
  'Despite being told repeatedly to sit upright, the teenagers continued to slouch in their chairs throughout the lecture.',
  '何度も背筋を伸ばして座るように言われたにもかかわらず、ティーンエイジャーたちは講義の間ずっとだらけた格好で椅子に座り続けた。'),
(470, 'lanky', '(人が)やせてひょろっとした', '/ˈlæŋki/', 'ランキー',
  'The lanky teenager towered over his classmates, making him an obvious choice for the school basketball team.',
  'そのやせてひょろっとしたティーンエイジャーはクラスメートよりも背が高く、学校のバスケットボールチームの明らかな候補だった。',
  'Despite his lanky frame, the young athlete possessed surprising strength and agility on the football pitch.',
  'ひょろっとした体格にもかかわらず、その若いアスリートはサッカーのピッチで驚くべき力強さと敏捷性を見せた。'),
(471, 'reprisal', '報復、仕返し', '/rɪˈpraɪzl/', 'リプライザル',
  'The dissidents lived in constant fear of reprisal from the authoritarian government for their outspoken criticism.',
  '反体制派の人々は率直な批判に対する独裁政権からの報復を常に恐れて暮らしていた。',
  'International law strictly prohibits reprisals against civilian populations during armed conflicts.',
  '国際法は武力紛争中の民間人に対する報復を厳しく禁じている。'),
(472, 'desolate', '(場所・土地などが)人けのない、荒れ果てた;(人が)孤独な、寂しい', '/ˈdesələt/', 'デソレット',
  'The once-thriving mining town had become a desolate wasteland after the last of its natural resources were exhausted.',
  'かつて繁栄した鉱山町は、天然資源が最後まで枯渇した後、人けのない荒れ地となっていた。',
  'She felt utterly desolate after the passing of her lifelong companion, unable to find solace in anything.',
  '生涯の伴侶を亡くした後、彼女は何にも慰めを見いだせず、まったくの孤独を感じた。'),
(473, 'perennial', 'いつまでも続く、絶え間ない;(植物が)多年生の', '/pəˈreniəl/', 'ペレニアル',
  'Income inequality remains a perennial challenge that governments around the world have struggled to address effectively.',
  '所得格差は世界中の政府が効果的に対処するのに苦労してきた絶え間ない課題のままである。',
  'The gardener recommended planting perennial flowers along the border, as they would bloom year after year without replanting.',
  '庭師は植え替えなしに毎年咲くため、境界沿いに多年生の花を植えることを勧めた。'),
(474, 'bluff', 'はったりをかける;はったり、こけおどし', '/blʌf/', 'ブラフ',
  'The experienced negotiator saw through his counterpart''s bluff and refused to make any concessions.',
  '経験豊富な交渉人は相手のはったりを見抜き、いかなる譲歩もすることを拒んだ。',
  'She decided to bluff her way through the interview, pretending to have expertise she did not actually possess.',
  '彼女ははったりで面接を切り抜けることにし、実際には持っていない専門知識があるふりをした。'),
(475, 'squirm', '(不快感などから)身をよじる、(逃れようと)もがく', '/skwɜːrm/', 'スクワーム',
  'The witness squirmed uncomfortably in the stand as the defense attorney pressed him with increasingly pointed questions.',
  '弁護人がますます鋭い質問で迫る中、証人は証言台で不快そうに身をよじった。',
  'The children squirmed in their seats during the lengthy ceremony, eager to go outside and play.',
  '子どもたちは長い式典の間、外に出て遊びたくて座席で身をよじっていた。'),
(476, 'transpire', '(事件などが)起こる;…ということが明らかになる;(動植物が)水分を蒸発させる', '/trænˈspaɪər/', 'トランスパイア',
  'It later transpired that the company had been concealing critical safety data from the regulatory authorities for years.',
  'その会社が何年もの間、重要な安全性データを規制当局から隠していたことが後に明らかになった。',
  'Nobody could have predicted what would transpire at the summit, where decades of diplomatic tension finally reached a resolution.',
  '何十年にもわたる外交的緊張がついに解決に至ったその首脳会議で何が起こるかは、誰も予測できなかった。'),
(477, 'aboveboard', '公正明大な、隠しごとをしない', '/əˌbʌvˈbɔːrd/', 'アバヴボード',
  'The auditors confirmed that all financial transactions conducted by the organization were entirely aboveboard.',
  '監査人は、その組織が行ったすべての金融取引が完全に公正明大であったことを確認した。',
  'To maintain public trust, the government must ensure that its procurement processes remain transparent and aboveboard.',
  '国民の信頼を維持するために、政府は調達プロセスが透明で公正であり続けることを確保しなければならない。'),
(478, 'eminent', '高名な、著名な', '/ˈemɪnənt/', 'エミネント',
  'The eminent historian was invited to deliver the keynote address at the international conference on medieval studies.',
  'その著名な歴史学者は中世研究に関する国際会議で基調講演を行うよう招かれた。',
  'Several eminent scientists have publicly endorsed the new climate policy, lending it considerable credibility.',
  '数人の著名な科学者がその新しい気候政策を公に支持し、かなりの信頼性を与えた。'),
(479, 'discerning', '洞察力のある、目の肥えた', '/dɪˈsɜːrnɪŋ/', 'ディサーニング',
  'The restaurant caters to discerning diners who appreciate locally sourced ingredients and innovative culinary techniques.',
  'そのレストランは地元産の食材と革新的な調理技術を高く評価する目の肥えた食事客を対象としている。',
  'A discerning reader will immediately notice the subtle irony woven throughout the author''s seemingly straightforward prose.',
  '洞察力のある読者は、一見平易な著者の散文に織り込まれた微妙な皮肉にすぐに気づくだろう。'),
(480, 'labyrinth', '迷宮、迷路;複雑[難解]なもの[こと]', '/ˈlæbərɪnθ/', 'ラビリンス',
  'Navigating the labyrinth of bureaucratic regulations proved to be the most daunting aspect of establishing the new enterprise.',
  '官僚的な規制の迷路を切り抜けることが、新しい事業を設立する上で最も困難な側面であった。',
  'The ancient ruins contained an underground labyrinth that archaeologists spent years meticulously mapping.',
  'その古代遺跡には地下迷宮があり、考古学者たちは何年もかけて綿密に地図を作成した。'),
(481, 'conciliate', '(人)をなだめる、懐柔する、調停する', '/kənˈsɪlieɪt/', 'コンシリエイト',
  'The mediator worked tirelessly to conciliate the two warring factions and bring them to the negotiating table.',
  '調停者は対立する二つの派閥をなだめて交渉のテーブルにつかせるために精力的に働いた。',
  'The manager attempted to conciliate the disgruntled employees by offering improved benefits and flexible working hours.',
  '管理者は福利厚生の改善とフレックスタイム制を提供することで不満を持つ従業員をなだめようとした。'),
(482, 'perfunctory', '(行為が)いい加減な、通り一遍の;(人が)やる気[熱意]のない', '/pərˈfʌŋktəri/', 'パーファンクトリー',
  'The safety inspector gave the facility only a perfunctory examination, overlooking several critical violations.',
  '安全検査官はその施設をいい加減にしか検査せず、いくつかの重大な違反を見逃した。',
  'His perfunctory apology did nothing to appease the colleagues he had offended with his thoughtless remarks.',
  '彼の通り一遍の謝罪は、軽率な発言で気分を害した同僚たちをなだめるのに何の役にも立たなかった。'),
(483, 'repatriate', '(人)を本国へ送還する', '/riːˈpeɪtrieɪt/', 'リーペイトリエイト',
  'The embassy coordinated efforts to repatriate citizens who had been stranded abroad due to the sudden closure of international borders.',
  '大使館は国境の突然の閉鎖により海外で足止めされた国民を本国へ送還するための取り組みを調整した。',
  'After the conflict subsided, the international community helped repatriate thousands of displaced refugees to their homeland.',
  '紛争が収まった後、国際社会は何千人もの避難民を故国に送還する支援を行った。'),
(484, 'traverse', '(場所)を横切る、越える', '/trəˈvɜːrs/', 'トラヴァース',
  'The expedition team spent three grueling weeks traversing the uncharted desert before reaching the ancient oasis.',
  '探検隊は未踏の砂漠を横切り、古代のオアシスに到達するまで過酷な3週間を費やした。',
  'Fiber-optic cables traverse the ocean floor, connecting continents and enabling instantaneous global communication.',
  '光ファイバーケーブルは海底を横断し、大陸を結び、瞬時のグローバル通信を可能にしている。'),
(485, 'bridle', '(憤慨を表して)つんとする', '/ˈbraɪdl/', 'ブライドル',
  'The ambassador bridled at the suggestion that her country had failed to uphold its treaty obligations.',
  '大使は自国が条約上の義務を果たしていないという示唆に憤慨してつんとした。',
  'He bridled visibly when the interviewer questioned the authenticity of his academic credentials.',
  '面接官が彼の学歴の信憑性に疑問を呈したとき、彼は目に見えてつんとした。'),
(486, 'queasy', '(人・胃が)むかむかする、吐き気がする', '/ˈkwiːzi/', 'クウィージー',
  'Several passengers began to feel queasy as the small boat rocked violently in the turbulent waters.',
  '小さなボートが荒れた海で激しく揺れ、数人の乗客がむかむかし始めた。',
  'The graphic images in the documentary made even the most seasoned medical professionals feel queasy.',
  'そのドキュメンタリーの生々しい映像は、最も経験豊富な医療専門家でさえ吐き気を催させた。'),
(487, 'grapple', '(問題などに)取り組む;(人と)取っ組み合う', '/ˈɡræpl/', 'グラプル',
  'Policymakers continue to grapple with the complex ethical implications of artificial intelligence in healthcare.',
  '政策立案者たちは医療における人工知能の複雑な倫理的影響に取り組み続けている。',
  'The two wrestlers grappled fiercely on the mat, neither willing to concede an inch of ground to the other.',
  '二人のレスラーはマットの上で激しく取っ組み合い、どちらも相手に一歩も譲ろうとしなかった。'),
(488, 'livid', '激怒した、怒り狂った', '/ˈlɪvɪd/', 'リヴィッド',
  'The director was livid when she discovered that confidential documents had been leaked to the press.',
  '機密文書がマスコミに漏洩されたことを知って、その取締役は激怒した。',
  'Residents were livid upon learning that the toxic waste had been illegally dumped near their neighborhood for over a decade.',
  '有害廃棄物が10年以上にわたって近隣に不法投棄されていたことを知り、住民たちは怒り狂った。'),
(489, 'zeal', '(仕事・理想などに対する)熱意、情熱', '/ziːl/', 'ズィール',
  'The young activist pursued environmental reform with such zeal that she quickly became a prominent figure in the movement.',
  'その若い活動家は環境改革を非常な熱意で追求し、すぐにその運動の著名人物となった。',
  'His missionary zeal for educational equity inspired thousands of volunteers to join the literacy campaign.',
  '教育の平等に対する彼の情熱は何千人ものボランティアに識字キャンペーンへの参加を促した。'),
(490, 'stupor', '(飲酒などによる)人事不省、昏睡状態', '/ˈstuːpər/', 'ストゥーパー',
  'The patient was found in a deep stupor, barely responsive to external stimuli, prompting the medical team to order an emergency brain scan.',
  '患者は深い昏睡状態で発見され、外部刺激にほとんど反応せず、医療チームは緊急の脳スキャンを指示した。',
  'After consuming an excessive amount of alcohol, he fell into a stupor from which his friends could not rouse him.',
  '過度の飲酒の後、彼は人事不省に陥り、友人たちは彼を起こすことができなかった。'),
(491, 'harrowing', '悲惨な、痛ましい', '/ˈhæroʊɪŋ/', 'ハロウイング',
  'The survivor gave a harrowing account of her ordeal, leaving the entire courtroom in stunned silence.',
  '生存者は自らの悲惨な体験を語り、法廷全体を驚愕の沈黙に包んだ。',
  'The documentary presented harrowing footage of the famine, compelling international organizations to mobilize emergency aid.',
  'そのドキュメンタリーは飢饉の痛ましい映像を提示し、国際機関に緊急援助の動員を促した。'),
(492, 'brazen', '(人・行為が)厚かましい、図々しい', '/ˈbreɪzn/', 'ブレイズン',
  'The brazen theft of priceless artworks from the national museum shocked the entire country.',
  '国立美術館からの貴重な芸術作品の厚かましい窃盗は国全体に衝撃を与えた。',
  'She made a brazen attempt to take credit for her colleague''s research, but the deception was quickly uncovered.',
  '彼女は同僚の研究の功績を自分のものにしようと図々しい試みをしたが、その欺瞞はすぐに暴かれた。'),
(493, 'elucidation', '解明、明快な説明', '/ɪˌluːsɪˈdeɪʃən/', 'イルースィデイション',
  'The professor''s thorough elucidation of the theorem enabled even the most struggling students to grasp its fundamental principles.',
  '教授による定理の徹底的な解明により、最も苦労している学生でさえその基本原理を理解できるようになった。',
  'Further elucidation of the molecular mechanisms underlying the disease could pave the way for groundbreaking treatments.',
  'その疾患の根底にある分子メカニズムのさらなる解明は、画期的な治療法への道を開く可能性がある。'),
(494, 'repel', '~を追い払う、撃退する;~を不快にする', '/rɪˈpel/', 'リペル',
  'The fortress was strategically designed to repel invaders attempting to cross the narrow mountain pass.',
  'その要塞は狭い山道を越えようとする侵略者を撃退するために戦略的に設計されていた。',
  'The pungent odor emanating from the chemical plant repelled residents and discouraged prospective buyers from purchasing nearby properties.',
  '化学工場から発する刺激臭は住民を不快にさせ、近隣の不動産を購入しようとする買い手を思いとどまらせた。'),
(495, 'scamper', '(子ども・小動物などが)すばやく走る', '/ˈskæmpər/', 'スキャンパー',
  'The squirrels scampered up the oak tree the moment they sensed the approach of the neighborhood cat.',
  'リスたちは近所の猫が近づいてくるのを感じた瞬間、オークの木をすばやく駆け上がった。',
  'The children scampered across the playground with unbridled energy, their joyful shrieks filling the afternoon air.',
  '子どもたちは抑えきれないエネルギーで校庭をすばやく駆け回り、楽しげな叫び声が午後の空気を満たした。'),
(496, 'meander', '(川・道路などが)曲がりくねる;(人が)あてもなくさまよう', '/miˈændər/', 'ミアンダー',
  'The ancient river meanders through the lush valley, carving intricate patterns into the landscape over millennia.',
  'その古い川は緑豊かな谷を曲がりくねって流れ、何千年もかけて地形に複雑な模様を刻んでいる。',
  'On weekends, she liked to meander through the old quarter of the city, discovering hidden cafés and antique shops.',
  '週末には旧市街をあてもなくさまよい、隠れたカフェやアンティークショップを見つけるのが好きだった。'),
(497, 'despondent', '失望した、落胆した、意気消沈した', '/dɪˈspɒndənt/', 'ディスポンデント',
  'The researcher grew despondent after her grant application was rejected for the third consecutive time.',
  '研究助成金の申請が3回連続で却下された後、その研究者は意気消沈した。',
  'Despite feeling despondent about the election results, the activists resolved to continue their campaign for social justice.',
  '選挙結果に落胆しながらも、活動家たちは社会正義のための運動を続けることを決意した。'),
(498, 'wade', '(水の中を苦労して)歩く、歩いて渡る', '/weɪd/', 'ウェイド',
  'The rescue team had to wade through waist-deep floodwater to reach the stranded families on the opposite bank.',
  '救助隊は対岸に取り残された家族のもとに到達するため、腰まである洪水の中を歩いて渡らなければならなかった。',
  'Researchers waded into the shallow estuary to collect water samples for their study on coastal pollution.',
  '研究者たちは沿岸汚染の研究のために水質サンプルを採取するべく浅い河口に入って歩いた。'),
(499, 'inquisitive', '好奇心の強い;詮索好きな、しきりに知りたがる', '/ɪnˈkwɪzətɪv/', 'インクウィジティヴ',
  'The inquisitive child bombarded her parents with an endless stream of questions about how the universe came into existence.',
  '好奇心の強い子どもは宇宙がどのようにして誕生したかについて果てしない質問を両親に浴びせた。',
  'While an inquisitive mind is generally an asset in academia, it can sometimes be perceived as intrusive in social settings.',
  '好奇心の強い精神は学術の世界では一般に長所であるが、社会的な場面では詮索好きと受け取られることもある。'),
(500, 'chastise', '(人)を厳しく非難する、責める', '/tʃæˈstaɪz/', 'チャスタイズ',
  'The editorial chastised the corporation for its blatant disregard of environmental regulations and its refusal to accept accountability.',
  'その社説は、環境規制の露骨な無視と責任を認めることの拒否について、その企業を厳しく非難した。',
  'The coach chastised the players for their lack of discipline, warning that such complacency would not be tolerated in future matches.',
  'コーチは規律の欠如について選手たちを厳しく責め、そのような油断は今後の試合では容認されないと警告した。');
