-- words テーブル INSERT文 (No.501 ~ No.550)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(501, 'retard', '~を遅らせる、妨げる', '/rɪˈtɑːrd/', 'リタード',
  'The heavy snowfall retarded the construction work, pushing the project completion date back by several weeks.',
  '大雪が建設作業を遅らせ、プロジェクトの完了日が数週間延びた。',
  'Economic sanctions were imposed to retard the nation''s nuclear weapons development program.',
  '経済制裁はその国の核兵器開発計画を妨げるために課された。'),
(502, 'complexion', '肌の色、(特に)顔色', '/kəmˈplɛkʃən/', 'コンプレクション',
  'Her pale complexion suggested that she had been confined indoors for an extended period during her illness.',
  '彼女の青白い顔色は、病気の間長期にわたって屋内に閉じこもっていたことを示唆していた。',
  'The political complexion of the region changed dramatically after the landmark election results were announced.',
  'その画期的な選挙結果が発表された後、地域の政治的な様相は劇的に変化した。'),
(503, 'constellation', '星座', '/ˌkɑːnstəˈleɪʃən/', 'カンスタレイション',
  'Ancient mariners relied on the constellation Orion to navigate across vast, uncharted oceans.',
  '古代の船乗りたちは広大な未踏の海を航行するためにオリオン座を頼りにしていた。',
  'The researcher identified a constellation of symptoms that pointed to an entirely new autoimmune disorder.',
  '研究者はまったく新しい自己免疫疾患を示す一群の症状を特定した。'),
(504, 'imbue', '(思想などを)(人・組織)に植え付ける、染み込ませる', '/ɪmˈbjuː/', 'インビュー',
  'The charismatic leader imbued his followers with an unwavering sense of purpose and dedication to the cause.',
  'そのカリスマ的な指導者は信奉者たちに揺るぎない目的意識と大義への献身を植え付けた。',
  'The training program was designed to imbue new recruits with the core values and ethical standards of the organization.',
  'その研修プログラムは新入社員に組織の核心的な価値観と倫理基準を染み込ませるために設計された。'),
(505, 'frenetic', '慌ただしい、狂ったような', '/frəˈnɛtɪk/', 'フレネティック',
  'The frenetic pace of trading on the stock exchange floor intensified as rumors of a merger spread rapidly.',
  '合併の噂が急速に広まるにつれ、証券取引所のフロアでの取引の慌ただしさが増した。',
  'After weeks of frenetic preparation, the diplomatic summit was finally ready to commence on schedule.',
  '数週間にわたる慌ただしい準備の後、外交サミットはようやく予定通りに開始される準備が整った。'),
(506, 'snag', '思いがけない障害[問題]', '/snæɡ/', 'スナッグ',
  'The negotiations hit an unexpected snag when both parties disagreed on the intellectual property clause.',
  '知的財産条項について両者が合意に至らず、交渉は思いがけない障害にぶつかった。',
  'We encountered a technical snag during the satellite launch, forcing engineers to postpone the mission indefinitely.',
  '衛星打ち上げ中に技術的な問題が発生し、エンジニアはミッションを無期限に延期せざるを得なかった。'),
(507, 'rummage', '引っかき回して捜す', '/ˈrʌmɪdʒ/', 'ランメジ',
  'She rummaged through the dusty attic for hours before finally discovering her grandmother''s antique jewelry box.',
  '彼女は何時間も埃だらけの屋根裏を引っかき回して捜し、ようやく祖母のアンティークの宝石箱を見つけた。',
  'Investigators rummaged through the suspect''s belongings in search of evidence linking him to the embezzlement scheme.',
  '捜査官たちは容疑者の横領計画に結びつける証拠を求めて、その所持品を引っかき回して捜した。'),
(508, 'condone', '(罪・違反など)を許す、大目に見る', '/kənˈdoʊn/', 'コンドウン',
  'The university made it clear that it would not condone any form of academic dishonesty, including plagiarism.',
  '大学は盗用を含むいかなる形の学術的不正行為も許さないことを明確にした。',
  'Critics argued that the lenient sentence effectively condoned the corporation''s blatant disregard for environmental regulations.',
  '批判者たちは、その軽い量刑は企業の環境規制に対するあからさまな無視を事実上大目に見るものだと主張した。'),
(509, 'brusquely', 'ぶっきらぼうに、不愛想に', '/ˈbrʌskli/', 'ブラスクリー',
  'The receptionist brusquely dismissed the visitor''s inquiry, leaving a negative impression of the entire organization.',
  '受付係が来訪者の問い合わせをぶっきらぼうにあしらい、組織全体に対して悪い印象を残した。',
  'When asked about the failed merger, the CEO brusquely declined to comment and abruptly ended the press conference.',
  '合併失敗について聞かれると、CEOは不愛想にコメントを拒否し、記者会見を突然打ち切った。'),
(510, 'derogatory', '軽蔑的な、侮蔑的な', '/dɪˈrɑːɡətɔːri/', 'デロガトリー',
  'The politician faced severe backlash after making derogatory remarks about minority communities during a televised debate.',
  'その政治家はテレビ中継された討論会で少数派コミュニティに対して侮蔑的な発言をし、激しい反発を受けた。',
  'The employee filed a formal complaint after enduring months of derogatory comments from a senior colleague.',
  'その従業員は上司の同僚から何か月にもわたる軽蔑的な発言に耐えた後、正式な苦情を申し立てた。'),
(511, 'oblique', '遠回しの、間接的な;(線・面などが)斜めの、傾斜した', '/əˈbliːk/', 'オブリーク',
  'The diplomat''s oblique reference to territorial disputes was carefully noted by every delegate in the assembly.',
  'その外交官の領土紛争への遠回しな言及は、議会のすべての代表者によって注意深く記録された。',
  'The architect incorporated oblique angles into the building''s facade, creating a striking visual effect against the skyline.',
  '建築家は建物のファサードに斜めの角度を取り入れ、スカイラインに対して印象的な視覚効果を生み出した。'),
(512, 'rumble', '(雷などが)ゴロゴロ鳴る、(腹が)グーグー鳴る', '/ˈrʌmbl/', 'ランブル',
  'Thunder rumbled ominously in the distance as the hikers scrambled to find shelter before the storm arrived.',
  '登山者たちが嵐の到来前に避難場所を見つけようと急ぐ中、遠くで雷が不吉にゴロゴロ鳴った。',
  'Discontent had been rumbling among factory workers for months before the strike was officially declared.',
  'ストライキが正式に宣言される何か月も前から、工場労働者の間で不満がくすぶっていた。'),
(513, 'goad', '(人)をけしかける、駆り立てる', '/ɡoʊd/', 'ゴウド',
  'The relentless media coverage goaded the government into launching a full-scale investigation into the scandal.',
  '執拗なメディア報道が政府をけしかけて、そのスキャンダルに対する本格的な調査を開始させた。',
  'His rival''s taunts goaded him into making a reckless decision that ultimately cost him the championship title.',
  'ライバルの挑発が彼を駆り立てて無謀な決断をさせ、結果的にチャンピオンの座を失わせた。'),
(514, 'deduce', '(結論など)を推定する;…であると推定する', '/dɪˈduːs/', 'ディデュース',
  'From the geological evidence collected at the site, scientists deduced that a massive earthquake had occurred millennia ago.',
  '現場で収集された地質学的証拠から、科学者たちは数千年前に大規模な地震が発生したと推定した。',
  'The detective deduced the suspect''s identity by meticulously cross-referencing witness testimonies with surveillance footage.',
  '刑事は目撃者の証言と監視カメラの映像を綿密に照合することで、容疑者の身元を推定した。'),
(515, 'awry', '(ものが)曲がった、ゆがんだ', '/əˈraɪ/', 'アライ',
  'The carefully orchestrated business plan went awry when the principal investor withdrew funding at the last moment.',
  '主要な投資家が土壇場で資金を引き揚げたため、綿密に計画されたビジネスプランが狂った。',
  'Something had clearly gone awry with the experiment, as the results deviated drastically from all theoretical predictions.',
  '結果がすべての理論的予測から大幅に逸脱したため、実験で何かが明らかにうまくいかなかったことがわかった。'),
(516, 'dearth', '不足、欠乏', '/dɜːrθ/', 'ダース',
  'The dearth of affordable housing in major urban centers has become one of the most pressing social issues of our time.',
  '大都市圏における手頃な住宅の不足は、現代で最も差し迫った社会問題の一つとなっている。',
  'A dearth of qualified interpreters hampered international negotiations at the multilateral trade conference.',
  '資格を持つ通訳者の不足が、多国間貿易会議での国際交渉を妨げた。'),
(517, 'detest', '~を憎む、ひどく嫌う', '/dɪˈtɛst/', 'ディテスト',
  'She detested the bureaucratic inefficiency that prevented aid from reaching disaster victims in a timely manner.',
  '彼女は災害被害者に支援が適時に届くのを妨げる官僚的な非効率性をひどく嫌っていた。',
  'The renowned author openly detested the commercialization of literature, calling it a betrayal of artistic integrity.',
  'その著名な作家は文学の商業化を公然と嫌悪し、それを芸術的誠実さへの裏切りだと呼んだ。'),
(518, 'agility', '(動きの)機敏さ、軽快さ;(頭の)回転の速さ', '/əˈdʒɪləti/', 'アジリティ',
  'The gymnast''s remarkable agility and precision earned her the highest score in the international competition.',
  'その体操選手の驚くべき機敏さと正確さにより、国際大会で最高得点を獲得した。',
  'In today''s volatile market, corporate agility is essential for companies to adapt swiftly to changing consumer demands.',
  '今日の不安定な市場では、変化する消費者の需要に迅速に適応するために企業の機敏さが不可欠である。'),
(519, 'uncanny', '不思議な、神秘的な', '/ʌnˈkæni/', 'アンキャニー',
  'The child prodigy displayed an uncanny ability to solve complex mathematical equations far beyond her age level.',
  'その神童は年齢をはるかに超えた複雑な数学の方程式を解く不思議な能力を示した。',
  'There was an uncanny resemblance between the ancient artifact and the modern sculpture, despite centuries separating their creation.',
  '何世紀もの隔たりがあるにもかかわらず、その古代の遺物と現代の彫刻の間には不思議な類似性があった。'),
(520, 'wager', '(~を)賭ける;(~を)請け合う', '/ˈweɪdʒər/', 'ウェイジャー',
  'He wagered his entire reputation on the success of the groundbreaking clinical trial for the experimental drug.',
  '彼はその画期的な実験薬の臨床試験の成功に自分の全名声を賭けた。',
  'I would wager that the proposed legislation will face fierce opposition from both sides of the political spectrum.',
  '提案された法案は政治的スペクトルの両側から激しい反対に直面するだろうと私は請け合う。'),
(521, 'peruse', '~を読む、熟読する', '/pəˈruːz/', 'ペルーズ',
  'The lawyer spent the entire weekend perusing the lengthy contract to identify any potentially disadvantageous clauses.',
  '弁護士は不利になりうる条項を特定するために、その長い契約書を週末いっぱいかけて熟読した。',
  'Before signing any agreement, it is imperative that you peruse every provision to fully understand your obligations.',
  '契約書に署名する前に、自分の義務を十分に理解するためにすべての条項を熟読することが不可欠である。'),
(522, 'invincible', '(人・軍などが)無敵の;(思想・態度などが)不屈の', '/ɪnˈvɪnsəbl/', 'インヴィンシブル',
  'The once seemingly invincible empire crumbled under the weight of internal corruption and external military pressure.',
  'かつて無敵に見えたその帝国は、内部の腐敗と外部の軍事的圧力の重みで崩壊した。',
  'Her invincible determination to succeed against all odds inspired countless young women to pursue careers in science.',
  'あらゆる困難に打ち勝つ彼女の不屈の決意は、数え切れないほどの若い女性たちに科学の道を志す刺激を与えた。'),
(523, 'plenary', '(会議などが)全員出席の', '/ˈpliːnəri/', 'プリーナリー',
  'The plenary session of the United Nations General Assembly addressed the escalating humanitarian crisis in the region.',
  '国連総会の全体会議は、その地域で深刻化する人道危機を取り上げた。',
  'All delegates were required to attend the plenary meeting where the final resolution would be put to a vote.',
  '最終決議が投票にかけられる全体会議には、すべての代表者が出席することが求められた。'),
(524, 'litigate', '訴訟を起こす、法廷で争う', '/ˈlɪtɪɡeɪt/', 'リティゲイト',
  'The pharmaceutical company decided to litigate rather than settle, confident that the patent infringement claims were baseless.',
  'その製薬会社は特許侵害の申し立てに根拠がないと確信し、和解せずに法廷で争うことを決めた。',
  'Small businesses often lack the financial resources to litigate against larger corporations in prolonged legal disputes.',
  '中小企業は大企業との長期の法的紛争において訴訟を起こすための財政的資源が不足していることが多い。'),
(525, 'juncture', '(重大な)時点、時期', '/ˈdʒʌŋktʃər/', 'ジャンクチャー',
  'At this critical juncture in the peace negotiations, any misstep could derail months of diplomatic progress.',
  '和平交渉のこの重大な時点では、いかなる失策も数か月にわたる外交的進展を頓挫させかねない。',
  'The country found itself at a historic juncture, forced to choose between economic reform and political stability.',
  'その国は歴史的な岐路に立たされ、経済改革と政治的安定のどちらかを選ぶことを迫られた。'),
(526, 'sleek', '(デザイン・形などが)しゃれた、かっこいい', '/sliːk/', 'スリーク',
  'The sleek design of the new electric vehicle attracted widespread attention at the international automobile exhibition.',
  'その新しい電気自動車のしゃれたデザインは、国際自動車展示会で広く注目を集めた。',
  'The architect unveiled a sleek, minimalist office building that seamlessly blended functionality with aesthetic appeal.',
  '建築家は機能性と美的魅力を見事に融合させた、しゃれたミニマリストのオフィスビルを発表した。'),
(527, 'indulge', '存分に楽しむ、ふける;(欲望・興味など)を満足させる', '/ɪnˈdʌldʒ/', 'インダルジ',
  'After months of rigorous dieting, she decided to indulge in an elaborate gourmet meal to celebrate her achievement.',
  '数か月にわたる厳格なダイエットの後、彼女は達成を祝うために贅沢なグルメ料理を存分に楽しむことにした。',
  'The government cannot afford to indulge in short-sighted fiscal policies that jeopardize long-term economic stability.',
  '政府は長期的な経済安定を危うくする近視眼的な財政政策にふけることは許されない。'),
(528, 'truce', '休戦(期間);停戦協定', '/truːs/', 'トゥルース',
  'After years of devastating conflict, the warring factions finally agreed to a truce brokered by international mediators.',
  '壊滅的な紛争が何年も続いた後、交戦する各派閥は国際的な調停者の仲介による休戦にようやく合意した。',
  'The fragile truce between the two nations was shattered when border skirmishes erupted without warning.',
  '両国間のもろい停戦協定は、国境での小競り合いが予告なく勃発したことで崩壊した。'),
(529, 'facetious', '(人が)不真面目な、滑稽な;(発言などが)ふざけた', '/fəˈsiːʃəs/', 'ファシーシャス',
  'His facetious remark about the budget deficit was met with stony silence from the board of directors.',
  '財政赤字に関する彼のふざけた発言は、取締役会から冷ややかな沈黙で迎えられた。',
  'While the comment was intended to be facetious, it inadvertently offended several delegates at the formal reception.',
  'そのコメントはふざけたつもりだったが、公式レセプションで数名の代表者をうっかり不快にさせてしまった。'),
(530, 'prelude', '(出来事・事件の)前兆、前段階;前奏曲、序曲', '/ˈprɛljuːd/', 'プレリュード',
  'The minor diplomatic incident proved to be merely a prelude to a far more serious international confrontation.',
  'その小さな外交事件は、はるかに深刻な国際対立の前兆に過ぎなかったことが判明した。',
  'The composer''s haunting prelude set the emotional tone for the entire operatic performance that followed.',
  'その作曲家の忘れがたい前奏曲が、続くオペラ全体の情緒的な基調を定めた。'),
(531, 'libel', '名誉毀損;中傷', '/ˈlaɪbl/', 'ライブル',
  'The celebrity filed a libel suit against the tabloid newspaper for publishing fabricated stories about her personal life.',
  'その有名人は私生活についての捏造された記事を掲載したタブロイド紙に対して名誉毀損訴訟を起こした。',
  'In many jurisdictions, proving libel requires demonstrating that the defamatory statements were made with actual malice.',
  '多くの法域では、名誉毀損を証明するには中傷的な発言が実際の悪意をもってなされたことを立証する必要がある。'),
(532, 'dangle', '(ほうびなど)をちらつかせる;~をぶら下げる、ぶらぶらさせる', '/ˈdæŋɡl/', 'ダングル',
  'The recruiter dangled an extraordinarily generous compensation package to lure the top executive away from a rival firm.',
  'リクルーターはライバル企業からトップの幹部を引き抜くために、非常に寛大な報酬パッケージをちらつかせた。',
  'A single lantern dangled from the ceiling of the ancient temple, casting eerie shadows across the stone floor.',
  '古い寺院の天井から一つの提灯がぶら下がり、石の床に不気味な影を落としていた。'),
(533, 'adjourn', '(法廷・会議など)を中断する、一時休止する;(会議・決定など)を延期する', '/əˈdʒɜːrn/', 'アジャーン',
  'The judge decided to adjourn the trial until the following week to allow both legal teams time to review new evidence.',
  '裁判官は両方の弁護団に新しい証拠を検討する時間を与えるため、翌週まで裁判を中断することを決めた。',
  'The committee voted to adjourn the session after reaching an impasse on the proposed amendment to the constitution.',
  '委員会は憲法修正案をめぐって行き詰まった後、会議を中断することを決議した。'),
(534, 'plausible', '(話・議論などが)もっともらしい', '/ˈplɔːzəbl/', 'プローザブル',
  'The defendant''s alibi seemed plausible at first, but it quickly unraveled under rigorous cross-examination.',
  '被告のアリバイは最初はもっともらしく思えたが、厳しい反対尋問の下ですぐに崩れた。',
  'Scientists proposed a plausible explanation for the anomalous data by accounting for previously overlooked environmental variables.',
  '科学者たちは以前見落とされていた環境変数を考慮することで、異常なデータに対するもっともらしい説明を提案した。'),
(535, 'altercation', '(激しい)口論、論争', '/ˌɔːltərˈkeɪʃən/', 'オルタケイション',
  'A heated altercation broke out between the two senators on the parliament floor over the proposed immigration policy.',
  '提案された移民政策をめぐって、議場で二人の議員の間で激しい口論が勃発した。',
  'The altercation between the neighbors escalated to such an extent that the police had to be called to intervene.',
  '隣人同士の口論は警察が介入のために呼ばれなければならないほどにまで激化した。'),
(536, 'convoluted', '(議論・制度などが)複雑な;渦巻状の', '/ˈkɑːnvəluːtɪd/', 'カンヴォルーティッド',
  'The convoluted tax code made it virtually impossible for ordinary citizens to file their returns without professional assistance.',
  '複雑な税法により、一般市民が専門家の助けなしに確定申告をすることは事実上不可能であった。',
  'Critics dismissed the novelist''s convoluted plot as unnecessarily confusing, though others praised its intellectual depth.',
  '批評家たちはその小説家の複雑なプロットを不必要に混乱させるものだと退けたが、知的な深みを称賛する者もいた。'),
(537, 'immune', '(批判・変化などに)影響されない、動じない;免疫のある', '/ɪˈmjuːn/', 'イミューン',
  'No institution is immune to the effects of rapid technological change, regardless of its size or historical prestige.',
  'どんな機関も、その規模や歴史的な名声に関わらず、急速な技術変化の影響を免れることはできない。',
  'After recovering from the illness, the patient became immune to future infections of the same viral strain.',
  'その病気から回復した後、患者は同じウイルス株の将来の感染に対して免疫を獲得した。'),
(538, 'replicate', '(実験など)を再現する;~を複製する', '/ˈrɛplɪkeɪt/', 'レプリケイト',
  'Independent laboratories failed to replicate the controversial findings, casting serious doubt on the original study''s validity.',
  '独立した研究所がその物議を醸す発見を再現できず、元の研究の妥当性に深刻な疑いが投げかけられた。',
  'The biotech firm developed a technique to replicate complex protein structures with unprecedented accuracy and efficiency.',
  'そのバイオテクノロジー企業は、前例のない正確さと効率性で複雑なタンパク質構造を複製する技術を開発した。'),
(539, 'deter', '(人)に思いとどまらせる、~を抑止する', '/dɪˈtɜːr/', 'ディター',
  'The severe penalties were designed to deter corporations from engaging in illegal dumping of hazardous waste materials.',
  '厳しい罰則は企業が有害廃棄物の不法投棄に関与することを抑止するために設けられた。',
  'The threat of international sanctions did little to deter the regime from pursuing its controversial military expansion.',
  '国際制裁の脅威は、その体制が物議を醸す軍事拡大を追求するのを思いとどまらせるのにほとんど効果がなかった。'),
(540, 'aggravate', '(問題・状況など)を悪化させる;(人・動物)を怒らせる', '/ˈæɡrəveɪt/', 'アグラヴェイト',
  'The government''s delayed response to the crisis only served to aggravate the suffering of the affected communities.',
  '危機に対する政府の対応の遅れは、被災したコミュニティの苦しみを悪化させるだけであった。',
  'Continued deforestation will inevitably aggravate the already dire consequences of climate change in vulnerable regions.',
  '森林伐採の継続は、脆弱な地域における気候変動のすでに深刻な結果を必然的に悪化させるだろう。'),
(541, 'strain', '(人・生物などの)血統、品種', '/streɪn/', 'ストレイン',
  'Researchers identified a new strain of the virus that appeared to be more resistant to existing antiviral treatments.',
  '研究者たちは既存の抗ウイルス治療に対してより耐性があると思われる新しいウイルス株を特定した。',
  'The agricultural institute developed a strain of wheat capable of thriving in arid climates with minimal irrigation.',
  '農業研究所は最小限の灌漑で乾燥した気候でも育つ小麦の品種を開発した。'),
(542, 'faction', '(政党・組織内の)派閥、党派', '/ˈfækʃən/', 'ファクション',
  'A dissident faction within the ruling party threatened to block the passage of the controversial education reform bill.',
  '与党内の反対派閥が物議を醸す教育改革法案の通過を阻止すると脅した。',
  'The warring factions agreed to lay down their arms only after months of painstaking mediation by neutral diplomats.',
  '交戦する各派閥は、中立的な外交官による数か月にわたる粘り強い調停の後にようやく武器を置くことに同意した。'),
(543, 'demise', '(存在・活動などの)終了、終結;逝去、死亡', '/dɪˈmaɪz/', 'ディマイズ',
  'The demise of the once-dominant manufacturing industry left thousands of workers unemployed in the region.',
  'かつて支配的であった製造業の終焉は、その地域で何千人もの労働者を失業させた。',
  'Historians attribute the demise of the ancient civilization to a combination of prolonged drought and internal conflict.',
  '歴史家たちはその古代文明の終焉を長期にわたる干ばつと内部紛争の組み合わせに帰している。'),
(544, 'lethal', '死に至る、致命的な', '/ˈliːθəl/', 'リーサル',
  'Exposure to even minute quantities of the chemical compound proved lethal to laboratory specimens within hours.',
  'その化合物のごく微量への曝露でさえ、数時間以内に実験用検体にとって致命的であることが判明した。',
  'The combination of extreme fatigue and impaired judgment can prove lethal for drivers on long-distance overnight journeys.',
  '極度の疲労と判断力の低下の組み合わせは、長距離の夜間運転をするドライバーにとって致命的になりうる。'),
(545, 'counterfeit', '(貨幣・商品・書類などが)偽の、偽造の', '/ˈkaʊntərfɪt/', 'カウンターフィット',
  'Customs officials seized a massive shipment of counterfeit luxury goods valued at several million dollars at the port.',
  '税関職員は港で数百万ドル相当の偽造高級品の大量の積荷を押収した。',
  'Advanced printing technology has made it increasingly difficult to distinguish counterfeit banknotes from genuine currency.',
  '高度な印刷技術により、偽造紙幣と本物の通貨を区別することがますます困難になっている。'),
(546, 'avert', '(事故・危険など)を防ぐ、回避する;(目・顔など)をそらす', '/əˈvɜːrt/', 'アヴァート',
  'Swift diplomatic intervention managed to avert what could have escalated into a full-scale military confrontation.',
  '迅速な外交的介入により、全面的な軍事衝突に発展しかねなかった事態を回避することができた。',
  'She averted her gaze from the gruesome scene, unable to bear the sight of the devastation caused by the earthquake.',
  '彼女は地震による惨状を目にすることに耐えられず、その凄惨な光景から目をそらした。'),
(547, 'forensic', '科学捜査の、犯罪科学の', '/fəˈrɛnzɪk/', 'フォレンジック',
  'Forensic analysis of the DNA samples provided irrefutable evidence that ultimately led to the conviction of the suspect.',
  'DNA試料の科学捜査分析により、最終的に容疑者の有罪判決につながる反論の余地のない証拠が得られた。',
  'The forensic accountant uncovered a sophisticated money laundering scheme that had evaded detection for over a decade.',
  '法廷会計士は10年以上にわたって発覚を免れていた巧妙な資金洗浄スキームを明らかにした。'),
(548, 'negate', '~(の存在・正当性)を否定する;~(の効果)を無効にする', '/nɪˈɡeɪt/', 'ニゲイト',
  'The newly discovered evidence effectively negated the prosecution''s central argument, forcing them to revise their entire case.',
  '新たに発見された証拠は検察側の中心的な主張を事実上否定し、訴訟全体の見直しを余儀なくさせた。',
  'Years of environmental conservation efforts were negated by a single catastrophic industrial spill in the estuary.',
  '何年にもわたる環境保全の努力が、河口でのたった一度の壊滅的な産業流出事故によって無効にされた。'),
(549, 'feasible', '(計画・方法などが)実現可能な', '/ˈfiːzəbl/', 'フィーザブル',
  'After conducting a thorough cost-benefit analysis, the committee concluded that the proposed infrastructure project was financially feasible.',
  '徹底的な費用便益分析を行った結果、委員会は提案されたインフラプロジェクトが財政的に実現可能であると結論づけた。',
  'Advances in renewable energy technology have made it increasingly feasible to achieve carbon neutrality by the target date.',
  '再生可能エネルギー技術の進歩により、目標日までにカーボンニュートラルを達成することがますます実現可能になっている。'),
(550, 'diminish', '~を減らす、小さくする;減る、減少する', '/dɪˈmɪnɪʃ/', 'ディミニッシュ',
  'The relentless spread of misinformation has significantly diminished public trust in established media institutions.',
  '誤情報の絶え間ない拡散は、既存のメディア機関に対する国民の信頼を著しく減少させた。',
  'Despite the passage of decades, the survivors'' harrowing memories of the conflict showed no signs of diminishing.',
  '数十年が経過したにもかかわらず、生存者たちの紛争に関する悲惨な記憶は薄れる兆しを見せなかった。');
