-- words テーブル INSERT文 (No.51 ~ No.100)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(51, 'fervent', '(思想・信仰などが)熱心な', '/ˈfɜːrvənt/', 'ファーヴァント',
  'The fervent supporters rallied outside the parliament to demand legislative reform.',
  '熱心な支持者たちは立法改革を求めて議会の外に集結した。',
  'She delivered a fervent plea for international cooperation on climate change.',
  '彼女は気候変動に関する国際協力を求める熱烈な嘆願を行った。'),
(52, 'apathetic', '無感動の、無関心な、冷淡な', '/ˌæpəˈθɛtɪk/', 'アパセティック',
  'The electorate has grown increasingly apathetic toward local politics.',
  '有権者は地方政治に対してますます無関心になっている。',
  'His apathetic response to the humanitarian crisis drew widespread criticism.',
  '人道危機に対する彼の冷淡な対応は広範な批判を招いた。'),
(53, 'catalyst', '変化を促すもの、きっかけ;触媒', '/ˈkætəlɪst/', 'キャタリスト',
  'The economic downturn served as a catalyst for sweeping policy reforms.',
  '景気後退は包括的な政策改革のきっかけとなった。',
  'Her groundbreaking research acted as a catalyst for further innovation in the field.',
  '彼女の画期的な研究はその分野におけるさらなる革新の触媒となった。'),
(54, 'wane', '(効力・感情などが)徐々に弱まる、衰える;(月が)欠ける', '/weɪn/', 'ウェイン',
  'Public enthusiasm for the project began to wane after repeated delays.',
  'そのプロジェクトへの世間の熱意は度重なる遅延の後に徐々に弱まり始めた。',
  'As the empire''s influence waned, neighboring states seized the opportunity to expand.',
  '帝国の影響力が衰えるにつれ、近隣諸国は拡大の機会をつかんだ。'),
(55, 'clout', '(経済・政治などにおける)影響力、権威', '/klaʊt/', 'クラウト',
  'The multinational corporation wielded considerable clout in shaping trade regulations.',
  'その多国籍企業は貿易規制の形成において相当な影響力を行使した。',
  'His political clout diminished significantly after the scandal became public.',
  'スキャンダルが公になった後、彼の政治的影響力は大幅に低下した。'),
(56, 'override', '~を覆す;~に優先する', '/ˌoʊvərˈraɪd/', 'オーヴァーライド',
  'The legislature voted to override the president''s veto on the spending bill.',
  '議会は支出法案に対する大統領の拒否権を覆すことを決議した。',
  'Safety concerns should always override considerations of cost and convenience.',
  '安全への懸念は常にコストや利便性の考慮に優先すべきである。'),
(57, 'secede', '(国から)分離独立する;(組織などから)脱退する', '/sɪˈsiːd/', 'シシード',
  'The southern provinces threatened to secede from the federation over economic grievances.',
  '南部の州は経済的不満から連邦からの分離独立を脅かした。',
  'Several member states considered whether to secede from the international alliance.',
  'いくつかの加盟国は国際同盟からの脱退を検討した。'),
(58, 'appall', '~をぞっとさせる、愕然とさせる', '/əˈpɔːl/', 'アポール',
  'The extent of environmental destruction in the region appalled the investigating committee.',
  'その地域の環境破壊の規模は調査委員会を愕然とさせた。',
  'Citizens were appalled by the government''s indifference to the plight of refugees.',
  '市民は難民の窮状に対する政府の無関心にぞっとした。'),
(59, 'debunk', '(人・思想など)の正体を暴露する;(通説)の誤りを指摘する', '/dɪˈbʌŋk/', 'ディバンク',
  'The investigative journalist sought to debunk the widespread myth surrounding the corporation.',
  '調査報道記者はその企業にまつわる広く流布した神話の正体を暴露しようとした。',
  'Recent scientific studies have debunked the long-held assumption that the treatment is effective.',
  '最近の科学的研究がその治療法が効果的であるという長年の通説の誤りを指摘した。'),
(60, 'vent', '(感情など)を発散する、ぶちまける;通気孔、(感情の)はけ口', '/vɛnt/', 'ヴェント',
  'She needed to vent her frustration after months of dealing with bureaucratic obstacles.',
  '彼女は何か月にもわたる官僚的な障害への対応の後、不満を発散する必要があった。',
  'The protest provided a vent for the public''s growing discontent with economic inequality.',
  'その抗議活動は経済的不平等に対する国民の高まる不満のはけ口となった。'),
(61, 'recuperate', '(病気・けがなどから)回復する', '/rɪˈkuːpəreɪt/', 'リクーパレイト',
  'The athlete took several months to recuperate from the severe knee injury.',
  'その選手は深刻な膝のけがから回復するのに数か月を要した。',
  'After the grueling negotiations, the diplomat needed time to recuperate both physically and mentally.',
  '過酷な交渉の後、その外交官は身体的にも精神的にも回復する時間を必要とした。'),
(62, 'epitomize', '~(の特徴)を典型的に表す', '/ɪˈpɪtəmaɪz/', 'イピタマイズ',
  'Her career epitomizes the relentless pursuit of excellence in scientific research.',
  '彼女のキャリアは科学研究における卓越性の絶え間ない追求を典型的に表している。',
  'The abandoned factory epitomizes the decline of the region''s once-thriving industrial sector.',
  'その廃工場はかつて繁栄していたその地域の産業部門の衰退を典型的に表している。'),
(63, 'rift', '仲たがい、亀裂;裂け目、割れ目', '/rɪft/', 'リフト',
  'A deepening rift between the two factions threatened to destabilize the coalition government.',
  '二つの派閥間の深まる亀裂が連立政権を不安定にする恐れがあった。',
  'The ideological rift within the party proved irreconcilable during the leadership election.',
  '党内の思想的な亀裂は党首選挙の間に修復不可能であることが判明した。'),
(64, 'divulge', '(秘密など)を漏らす、明らかにする', '/dɪˈvʌldʒ/', 'ディヴァルジ',
  'The whistleblower chose to divulge classified information to expose corporate misconduct.',
  '内部告発者は企業の不正行為を暴露するために機密情報を漏らすことを選んだ。',
  'The diplomat refused to divulge the details of the confidential negotiations.',
  'その外交官は機密交渉の詳細を明らかにすることを拒んだ。'),
(65, 'dwindle', '(数・量などが)徐々に減る', '/ˈdwɪndl/', 'ドゥウィンドル',
  'The population of the endangered species has dwindled to fewer than a hundred individuals.',
  'その絶滅危惧種の個体数は100匹未満にまで徐々に減少した。',
  'Foreign investment in the country began to dwindle amid political instability.',
  '政治的不安定の中、その国への外国投資が徐々に減り始めた。'),
(66, 'denote', '(文字・符号などが)~を示す、意味する;(ことなど)を示す', '/dɪˈnoʊt/', 'ディノウト',
  'In this diagram, the red arrows denote the flow of capital between institutions.',
  'この図において赤い矢印は機関間の資本の流れを示している。',
  'The sudden rise in unemployment may denote a fundamental shift in the economic landscape.',
  '失業率の急上昇は経済状況の根本的な変化を示しているかもしれない。'),
(67, 'exodus', '大量流出、(一時に多数の人々が)出ていくこと', '/ˈɛksədəs/', 'エクサダス',
  'The prolonged civil conflict triggered an exodus of refugees toward neighboring countries.',
  '長引く内戦が近隣諸国への難民の大量流出を引き起こした。',
  'The exodus of skilled professionals from rural areas has exacerbated the urban-rural divide.',
  '地方からの熟練した専門家の大量流出は都市と地方の格差を悪化させた。'),
(68, 'hereditary', '遺伝性の、遺伝的な;世襲の', '/həˈrɛdɪtɛri/', 'ヘレディタリ',
  'Researchers identified the gene responsible for the hereditary disorder affecting the family.',
  '研究者たちはその家族に影響を与えている遺伝性疾患の原因となる遺伝子を特定した。',
  'The hereditary nature of the monarchy has been a subject of intense debate for centuries.',
  '君主制の世襲的な性質は何世紀にもわたって激しい議論の対象となっている。'),
(69, 'corroborate', '(意見・陳述など)を確証する、裏づける', '/kəˈrɒbəreɪt/', 'コロバレイト',
  'The forensic evidence was sufficient to corroborate the witness''s testimony.',
  '法医学的証拠は証人の証言を裏づけるのに十分であった。',
  'Independent auditors were brought in to corroborate the accuracy of the financial statements.',
  '財務諸表の正確性を確証するために独立監査人が招かれた。'),
(70, 'inscrutable', '不可解な、神秘的な', '/ɪnˈskruːtəbl/', 'インスクルータブル',
  'The diplomat maintained an inscrutable expression throughout the tense negotiations.',
  'その外交官は緊迫した交渉中ずっと不可解な表情を保っていた。',
  'The motives behind his sudden resignation remain inscrutable to political analysts.',
  '彼の突然の辞任の動機は政治アナリストにとって依然として不可解である。'),
(71, 'emaciated', '(食料不足・病気で)やせ衰えた、やせこけた', '/ɪˈmeɪʃieɪtɪd/', 'イメイシエイティド',
  'The emaciated prisoners were barely recognizable when the relief workers arrived.',
  '救援隊員が到着したとき、やせ衰えた囚人たちはほとんど見分けがつかなかった。',
  'Photographs of emaciated children galvanized international efforts to combat the famine.',
  'やせこけた子どもたちの写真が飢饉と闘うための国際的な取り組みを活性化させた。'),
(72, 'affront', '(公然の・故意の)侮辱', '/əˈfrʌnt/', 'アフラント',
  'The ambassador perceived the exclusion from the summit as a deliberate affront to her nation.',
  'その大使はサミットからの排除を自国に対する故意の侮辱と受け止めた。',
  'His dismissive remarks were taken as a personal affront by the entire research team.',
  '彼の見下すような発言は研究チーム全体にとって個人的な侮辱と受け取られた。'),
(73, 'fiasco', '(行事・企てなどの)大失敗', '/fiˈæskoʊ/', 'フィアスコウ',
  'The product launch turned into a complete fiasco due to a critical software malfunction.',
  '致命的なソフトウェアの不具合により、その製品発売は完全な大失敗に終わった。',
  'The diplomatic summit was widely regarded as a fiasco after negotiations collapsed on the first day.',
  '初日に交渉が決裂した後、その外交サミットは大失敗と広くみなされた。'),
(74, 'aloof', '(気取った感じで)冷淡で、よそよそしくて', '/əˈluːf/', 'アルーフ',
  'The manager''s aloof demeanor made it difficult for subordinates to approach him with concerns.',
  '上司のよそよそしい態度は部下が懸念を持ちかけることを難しくした。',
  'She remained deliberately aloof from the office politics that consumed her colleagues.',
  '彼女は同僚たちを巻き込む社内政治から意図的に距離を置いていた。'),
(75, 'altruistic', '利他(主義)的な', '/ˌæltruˈɪstɪk/', 'アルトルイスティック',
  'Her altruistic dedication to providing free medical care earned her widespread admiration.',
  '無料の医療提供に対する彼女の利他的な献身は広い称賛を得た。',
  'Critics questioned whether the corporation''s philanthropic efforts were genuinely altruistic.',
  '批評家たちはその企業の慈善活動が真に利他的であるかどうかを疑問視した。'),
(76, 'quandary', '困惑、葛藤', '/ˈkwɒndəri/', 'クワンダリ',
  'The committee found itself in a quandary over how to allocate the limited funds.',
  '委員会は限られた資金をどのように配分するかという困惑に陥った。',
  'The ethical quandary posed by artificial intelligence continues to challenge policymakers.',
  '人工知能がもたらす倫理的な葛藤は引き続き政策立案者に課題を突きつけている。'),
(77, 'embellish', '(真実)を粉飾する;(話)を面白くする;(服・場所)を美しく飾る', '/ɪmˈbɛlɪʃ/', 'エンベリッシュ',
  'The witness was accused of embellishing her account to make it more compelling.',
  'その証人は証言をより説得力のあるものにするために粉飾したと非難された。',
  'The architect embellished the facade with intricate carvings inspired by classical motifs.',
  '建築家は古典的なモチーフに着想を得た精巧な彫刻でファサードを美しく飾った。'),
(78, 'renege', '(約束などを)破る、反故にする', '/rɪˈnɪɡ/', 'リニグ',
  'The government reneged on its promise to reduce carbon emissions by the agreed deadline.',
  '政府は合意した期限までに炭素排出量を削減するという約束を反故にした。',
  'If the company reneges on the contract, it will face substantial legal repercussions.',
  'もしその企業が契約を破れば、重大な法的影響に直面するだろう。'),
(79, 'nudge', 'ひじで軽くつつくこと;~を(ひじで)軽くつつく', '/nʌdʒ/', 'ナッジ',
  'A gentle nudge from her mentor encouraged her to apply for the prestigious scholarship.',
  '指導者からの穏やかな後押しが彼女に名門の奨学金に応募するよう促した。',
  'The policy was designed to nudge consumers toward more environmentally sustainable choices.',
  'その政策は消費者をより環境的に持続可能な選択へと誘導するよう設計された。'),
(80, 'indoctrinate', '(人)に(思想などを)吹き込む', '/ɪnˈdɒktrɪneɪt/', 'インドクトリネイト',
  'The authoritarian regime sought to indoctrinate the youth through a state-controlled curriculum.',
  '独裁政権は国家管理の教育課程を通じて若者に思想を吹き込もうとした。',
  'Critics argued that the program was designed to indoctrinate rather than educate.',
  '批評家たちはそのプログラムは教育するのではなく思想を吹き込むために設計されたと主張した。'),
(81, 'remorse', '(罪悪などに対する)後悔、良心の呵責', '/rɪˈmɔːrs/', 'リモース',
  'The defendant expressed profound remorse for the suffering he had caused the victims.',
  '被告人は被害者に与えた苦痛に対して深い後悔の念を表した。',
  'Without genuine remorse, rehabilitation of offenders remains an elusive goal.',
  '真の良心の呵責なしには、犯罪者の更生は達成困難な目標のままである。'),
(82, 'delude', '(人)を惑わす、欺く', '/dɪˈluːd/', 'ディルード',
  'Investors were deluded into believing the scheme would yield extraordinary returns.',
  '投資家たちはその計画が異常な利益をもたらすと信じ込まされた。',
  'We should not delude ourselves into thinking that the problem will resolve itself.',
  'その問題が自然に解決するだろうと自分自身を欺くべきではない。'),
(83, 'defuse', '(緊張など)を和らげる', '/diːˈfjuːz/', 'ディフューズ',
  'The skilled negotiator managed to defuse the escalating tension between the two delegations.',
  '熟練した交渉人は二つの代表団間のエスカレートする緊張を和らげることに成功した。',
  'Humor can sometimes be an effective tool to defuse a potentially volatile situation.',
  'ユーモアは潜在的に不安定な状況を和らげる効果的な手段になりうることがある。'),
(84, 'precarious', '(状況・立場などが)不安定な、危うい', '/prɪˈkɛriəs/', 'プリケアリアス',
  'The company''s precarious financial position left it vulnerable to hostile takeover attempts.',
  'その企業の不安定な財務状況は敵対的買収の試みに対して脆弱な状態にした。',
  'Workers in the gig economy often face precarious employment with few legal protections.',
  'ギグエコノミーの労働者はしばしば法的保護がほとんどない不安定な雇用に直面する。'),
(85, 'feign', '~を装う、~のふりをする', '/feɪn/', 'フェイン',
  'The suspect attempted to feign ignorance when confronted with the incriminating evidence.',
  '容疑者は有罪を示す証拠を突きつけられたとき無知を装おうとした。',
  'She feigned enthusiasm for the proposal despite her serious reservations.',
  '彼女は深刻な懸念があるにもかかわらずその提案に対する熱意を装った。'),
(86, 'abject', '(状況などが)悲惨な、ひどい;(結果などが)みじめな', '/ˈæbdʒɛkt/', 'アブジェクト',
  'Millions of people in the region continue to live in abject poverty.',
  'その地域の何百万もの人々が悲惨な貧困の中で暮らし続けている。',
  'The military campaign ended in abject failure, with no strategic objectives achieved.',
  'その軍事作戦は戦略的目標を一つも達成できず、みじめな失敗に終わった。'),
(87, 'ulterior', '(目的・動機などが)隠された、表に現れてこない', '/ʌlˈtɪriər/', 'アルティアリア',
  'Many suspected that the philanthropist had ulterior motives behind his generous donation.',
  '多くの人がその慈善家の寛大な寄付の裏に隠された動機があるのではと疑った。',
  'The seemingly benevolent policy was later revealed to serve an ulterior political agenda.',
  '一見善意のある政策は後に隠された政治的意図に奉仕するものであると明らかになった。'),
(88, 'lambaste', '~を酷評する、こき下ろす', '/læmˈbeɪst/', 'ランベイスト',
  'The film critic lambasted the director''s latest work as pretentious and incoherent.',
  '映画評論家はその監督の最新作を気取っていて支離滅裂だと酷評した。',
  'Opposition leaders lambasted the government''s handling of the economic crisis.',
  '野党の指導者たちは政府の経済危機への対応をこき下ろした。'),
(89, 'commiserate', '同情する、哀れむ', '/kəˈmɪzəreɪt/', 'コミザレイト',
  'Colleagues gathered to commiserate with him after he was passed over for the promotion.',
  '昇進を見送られた後、同僚たちは彼に同情するために集まった。',
  'Rather than merely commiserating, she offered practical assistance to the flood victims.',
  '単に同情するだけでなく、彼女は洪水の被災者に実質的な支援を提供した。'),
(90, 'flagrant', '(不正などが)目に余る、破廉恥な', '/ˈfleɪɡrənt/', 'フレイグラント',
  'The auditor uncovered flagrant violations of financial regulations within the organization.',
  '監査人はその組織内の目に余る財務規則違反を発見した。',
  'The decision to suppress the report constituted a flagrant abuse of executive authority.',
  'その報告書を隠蔽するという決定は行政権の目に余る濫用に該当した。'),
(91, 'flout', '(故意に)(法・規則など)を無視する', '/flaʊt/', 'フラウト',
  'Several corporations were found to have deliberately flouted environmental protection laws.',
  'いくつかの企業が故意に環境保護法を無視していたことが判明した。',
  'Motorists who flout traffic regulations put the lives of pedestrians at risk.',
  '交通規則を無視する運転者は歩行者の命を危険にさらす。'),
(92, 'inculcate', '(思想・知識など)を叩き込む、教え込む', '/ɪnˈkʌlkeɪt/', 'インカルケイト',
  'The educational system aims to inculcate critical thinking skills from an early age.',
  '教育制度は幼少期から批判的思考能力を叩き込むことを目指している。',
  'Parents strive to inculcate a strong sense of moral responsibility in their children.',
  '親は子どもたちに強い道徳的責任感を教え込もうと努力する。'),
(93, 'infer', '(既知の情報などから)…と推量[推測]する', '/ɪnˈfɜːr/', 'インファー',
  'From the available data, researchers inferred that the treatment had a statistically significant effect.',
  '利用可能なデータから、研究者たちはその治療法が統計的に有意な効果があると推測した。',
  'One can infer from his silence that he was not in agreement with the proposed measures.',
  '彼の沈黙から、提案された措置に同意していなかったと推量できる。'),
(94, 'emulate', '(尊敬する人・立派なもの)を見習う、まねる', '/ˈɛmjʊleɪt/', 'エミュレイト',
  'Young entrepreneurs often seek to emulate the success of established industry leaders.',
  '若い起業家はしばしば確立された業界のリーダーの成功を見習おうとする。',
  'The developing nation sought to emulate the educational model that had transformed its neighbor.',
  'その発展途上国は隣国を変革した教育モデルを見習おうとした。'),
(95, 'alleviate', '(一時的に)(苦痛・問題など)を軽減する', '/əˈliːvieɪt/', 'アリーヴィエイト',
  'The humanitarian organization deployed emergency supplies to alleviate the suffering of displaced families.',
  '人道支援組織は避難家族の苦痛を軽減するために緊急物資を配備した。',
  'New infrastructure investments are expected to alleviate chronic traffic congestion in the capital.',
  '新たなインフラ投資により首都の慢性的な交通渋滞が軽減されると期待されている。'),
(96, 'staunch', '誠実な、忠実な', '/stɔːntʃ/', 'ストーンチ',
  'She has been a staunch advocate for gender equality throughout her distinguished career.',
  '彼女は輝かしいキャリアを通じてジェンダー平等の忠実な提唱者であり続けてきた。',
  'Even his most staunch allies began to distance themselves after the allegations surfaced.',
  '疑惑が浮上した後、彼の最も忠実な味方さえも距離を置き始めた。'),
(97, 'disseminate', '(情報・知識など)を広める', '/dɪˈsɛmɪneɪt/', 'ディセミネイト',
  'The organization used social media platforms to disseminate information about public health risks.',
  'その組織は公衆衛生上のリスクに関する情報を広めるためにソーシャルメディアを活用した。',
  'Efforts to disseminate scientific findings to the general public remain woefully inadequate.',
  '科学的知見を一般大衆に広める取り組みは依然としてひどく不十分である。'),
(98, 'baffle', '(人)を困惑させる、悩ませる', '/ˈbæfl/', 'バッフル',
  'The sudden disappearance of the artifacts continued to baffle archaeologists for decades.',
  '遺物の突然の消失は何十年にもわたって考古学者たちを困惑させ続けた。',
  'The complexity of the quantum phenomenon baffled even the most seasoned physicists.',
  'その量子現象の複雑さは最も経験豊富な物理学者さえも悩ませた。'),
(99, 'menial', '(仕事などが)技術を要しない、単調な', '/ˈmiːniəl/', 'ミーニアル',
  'Despite holding a graduate degree, she was relegated to menial tasks at her first job.',
  '大学院の学位を持っているにもかかわらず、彼女は最初の仕事で単調な作業に追いやられた。',
  'Automation has the potential to eliminate many of the menial jobs that workers find unfulfilling.',
  '自動化は労働者がやりがいを感じない多くの単調な仕事をなくす可能性がある。'),
(100, 'candid', '率直な、遠慮のない', '/ˈkændɪd/', 'キャンディッド',
  'The CEO gave a remarkably candid assessment of the company''s strategic failures.',
  'CEOは会社の戦略的失敗について驚くほど率直な評価を行った。',
  'In a candid interview, the politician admitted that the policy had not achieved its intended goals.',
  '率直なインタビューの中で、その政治家は政策が意図した目標を達成できなかったことを認めた。');
