-- words テーブル INSERT文 (No.551 ~ No.600)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(551, 'forge', '(関係など)を築く、強化する;(文書など)を捏造する;(金属)を鍛造する', '/fɔːrdʒ/', 'フォージ',
  'The two nations forged a historic alliance that would reshape the geopolitical landscape of the entire region.',
  '両国は地域全体の地政学的構図を一変させる歴史的な同盟を築いた。',
  'The suspect was arrested for forging official government documents to obtain fraudulent immigration visas.',
  'その容疑者は不正な移民ビザを取得するために政府の公式文書を捏造した罪で逮捕された。'),
(552, 'vie', '競う、張り合う', '/vaɪ/', 'ヴァイ',
  'Several multinational corporations are vying for the lucrative contract to develop the city''s new transportation system.',
  '複数の多国籍企業がその都市の新しい交通システム開発の利益の大きい契約を巡って競い合っている。',
  'The two research teams vied with each other to publish their groundbreaking findings in the prestigious journal first.',
  '二つの研究チームは画期的な研究成果をその権威ある学術誌に先に発表しようと張り合った。'),
(553, 'waive', '(権利など)を放棄する;(規則など)の適用を差し控える', '/weɪv/', 'ウェイヴ',
  'The university agreed to waive the tuition fees for students who had been severely affected by the natural disaster.',
  'その大学は自然災害で深刻な被害を受けた学生の授業料を免除することに同意した。',
  'The defendant chose to waive his right to a jury trial and instead opted for a bench trial before a single judge.',
  '被告は陪審裁判を受ける権利を放棄し、代わりに裁判官一人による法廷裁判を選んだ。'),
(554, 'onset', '(よくないことの)開始、始まり;(病気の)初期', '/ˈɑːnset/', 'オンセット',
  'The onset of the pandemic forced governments worldwide to implement unprecedented lockdown measures.',
  'パンデミックの開始により、世界中の政府が前例のないロックダウン措置を実施せざるを得なくなった。',
  'Early detection of the onset of Alzheimer''s disease can significantly improve the efficacy of treatment options.',
  'アルツハイマー病の初期の早期発見は、治療法の有効性を大幅に向上させることができる。'),
(555, 'slack', '(ロープなどが)緩い、たるんだ;(商売などが)不活発な', '/slæk/', 'スラック',
  'The factory experienced a slack period during the winter months, prompting management to reduce working hours temporarily.',
  'その工場は冬の数か月間に不活発な時期を経験し、経営陣は一時的に労働時間を短縮した。',
  'The mountaineer checked that no slack remained in the safety rope before ascending the treacherous cliff face.',
  '登山者は危険な崖を登る前に、安全ロープにたるみがないことを確認した。'),
(556, 'precedent', '前例、先例', '/ˈpresɪdənt/', 'プレシデント',
  'The landmark Supreme Court ruling set a legal precedent that would influence judicial decisions for decades to come.',
  'その画期的な最高裁判決は、今後数十年にわたり司法判断に影響を与える法的先例を打ち立てた。',
  'There is no precedent for granting such extensive executive powers during peacetime in the nation''s constitutional history.',
  'その国の憲法の歴史において、平時にこれほど広範な行政権を付与した前例はない。'),
(557, 'stark', 'まったくの、完全な、明確な;(場所・建物などが)殺風景な、荒涼とした', '/stɑːrk/', 'スターク',
  'The report revealed a stark contrast between the living standards of urban and rural populations in the developing nation.',
  'その報告書は発展途上国における都市部と農村部の生活水準の明確な格差を明らかにした。',
  'The stark landscape of the abandoned industrial district served as a haunting reminder of the region''s economic decline.',
  '廃墟となった工業地区の荒涼とした風景は、その地域の経済衰退を忘れがたく思い起こさせた。'),
(558, 'anomaly', '異常(なこと)、例外(的なこと)', '/əˈnɑːməli/', 'アノマリー',
  'Scientists discovered a gravitational anomaly in the region that could not be explained by existing theoretical models.',
  '科学者たちはその地域で既存の理論モデルでは説明できない重力の異常を発見した。',
  'The sudden surge in stock prices was dismissed by analysts as a temporary anomaly rather than a sustained market trend.',
  '株価の急騰は、アナリストたちによって持続的な市場トレンドではなく一時的な異常として片付けられた。'),
(559, 'alleged', '(もの・ことが)疑わしい;(証拠もなく)主張された', '/əˈledʒd/', 'アレッジド',
  'The alleged perpetrator was released on bail pending further investigation by the prosecution team.',
  '容疑者は検察チームによるさらなる捜査を待つ間、保釈金を納めて釈放された。',
  'The newspaper retracted its article about the alleged fraud after it was revealed that the evidence had been fabricated.',
  'その新聞は証拠が捏造されていたことが判明した後、疑わしい詐欺に関する記事を撤回した。'),
(560, 'entrench', '(習慣・理念など)を固定化する、根付かせる', '/ɪnˈtrentʃ/', 'イントレンチ',
  'Decades of discriminatory policies have entrenched systemic inequality that persists despite recent legislative reforms.',
  '数十年にわたる差別的な政策が制度的不平等を固定化し、最近の法改正にもかかわらずそれが続いている。',
  'The corporate culture had become so deeply entrenched that any attempt at organizational reform met fierce resistance.',
  '企業文化は非常に深く根付いていたため、組織改革のいかなる試みも激しい抵抗に遭った。'),
(561, 'deportation', '国外追放[退去]', '/ˌdiːpɔːrˈteɪʃən/', 'ディポーテイション',
  'The controversial deportation policy drew widespread criticism from human rights organizations around the world.',
  'その物議を醸す国外追放政策は世界中の人権団体から広範な批判を浴びた。',
  'Facing imminent deportation, the asylum seeker filed an emergency appeal with the immigration tribunal.',
  '差し迫った国外退去に直面し、その亡命希望者は移民裁判所に緊急上訴を行った。'),
(562, 'verdict', '(陪審員の)評決、答申', '/ˈvɜːrdɪkt/', 'ヴァーディクト',
  'The jury reached a unanimous guilty verdict after deliberating for over fourteen hours behind closed doors.',
  '陪審員は14時間以上にわたる非公開の審議の末、全会一致で有罪の評決に達した。',
  'The not-guilty verdict shocked the public, as most had believed the evidence against the defendant was overwhelming.',
  '無罪の評決は世間を驚かせた。ほとんどの人が被告に対する証拠は圧倒的だと考えていたからである。'),
(563, 'strand', '~を立ち往生させる', '/strænd/', 'ストランド',
  'The unprecedented blizzard stranded thousands of passengers at the international airport for nearly three days.',
  '前例のない猛吹雪により、何千人もの乗客が国際空港でほぼ3日間立ち往生した。',
  'When the ferry service was abruptly cancelled, hundreds of tourists were stranded on the remote island without supplies.',
  'フェリーの運航が突然中止されたため、何百人もの観光客が物資のない離島に取り残された。'),
(564, 'eclipse', '~の影を薄くする、~を上回る', '/ɪˈklɪps/', 'イクリプス',
  'The young prodigy''s remarkable achievements quickly eclipsed those of her more experienced colleagues in the department.',
  'その若き天才の目覚ましい業績は、学部のより経験豊富な同僚たちの業績をたちまち上回った。',
  'China''s rapid economic growth has eclipsed that of many Western nations over the past two decades.',
  '中国の急速な経済成長は過去20年間で多くの西側諸国の成長を上回った。'),
(565, 'culprit', '犯人;被告', '/ˈkʌlprɪt/', 'カルプリット',
  'After months of meticulous forensic investigation, the police finally identified the culprit behind the series of arsons.',
  '数か月にわたる綿密な科学捜査の結果、警察はついに連続放火の犯人を特定した。',
  'Excessive consumption of processed foods has been identified as a major culprit in the rising rates of chronic disease.',
  '加工食品の過剰摂取が、慢性疾患の増加率における主要な原因として特定されている。'),
(566, 'prerequisite', '必要条件、前提条件', '/priːˈrekwɪzɪt/', 'プリレクウィジット',
  'A thorough understanding of organic chemistry is a prerequisite for admission to the advanced pharmacology program.',
  '有機化学の十分な理解は、上級薬理学プログラムへの入学の前提条件である。',
  'The committee argued that political stability was an essential prerequisite for sustainable economic development.',
  '委員会は政治的安定が持続可能な経済発展の不可欠な前提条件であると主張した。'),
(567, 'cohesive', '(グループなどが)結束[団結]した、まとまりのある', '/koʊˈhiːsɪv/', 'コウヒーシヴ',
  'The manager''s leadership transformed the dysfunctional team into a cohesive unit capable of tackling complex projects.',
  'そのマネージャーのリーダーシップにより、機能不全のチームが複雑なプロジェクトに取り組める結束した部隊に変わった。',
  'The essay lacked a cohesive argument, jumping erratically from one point to another without logical transitions.',
  'その論文はまとまりのある論旨を欠いており、論理的な流れなく一つの論点から別の論点へと散漫に飛んでいた。'),
(568, 'covert', '密かな、内密の', '/ˈkoʊvɜːrt/', 'コウヴァート',
  'The intelligence agency conducted a covert operation to infiltrate the criminal syndicate operating across three countries.',
  '諜報機関は3か国にまたがって活動する犯罪組織に潜入するための密かな作戦を実施した。',
  'The journalist uncovered a covert agreement between the pharmaceutical company and several government officials.',
  'そのジャーナリストは製薬会社と数人の政府高官との間の内密の合意を暴いた。'),
(569, 'hub', '(活動・商業などの)中心、中枢', '/hʌb/', 'ハブ',
  'Singapore has established itself as a major financial hub, attracting multinational corporations from every continent.',
  'シンガポールは主要な金融の中枢としての地位を確立し、あらゆる大陸から多国籍企業を引きつけている。',
  'The newly constructed innovation hub provides entrepreneurs with shared workspaces and access to venture capital networks.',
  '新設されたイノベーションの中心拠点は起業家に共有ワークスペースとベンチャーキャピタルネットワークへのアクセスを提供している。'),
(570, 'plight', '苦境、深刻な状況', '/plaɪt/', 'プライト',
  'The documentary shed light on the plight of migrant workers who endure exploitative conditions in foreign countries.',
  'そのドキュメンタリーは外国で搾取的な状況に耐える移民労働者の苦境に光を当てた。',
  'International aid organizations have struggled to alleviate the plight of civilians trapped in the conflict zone.',
  '国際援助機関は紛争地帯に閉じ込められた民間人の苦境を緩和するのに苦慮している。'),
(571, 'spearhead', '~の先頭に立つ', '/ˈspɪrhed/', 'スピアヘッド',
  'The renowned scientist spearheaded the research initiative that led to a breakthrough in renewable energy technology.',
  'その著名な科学者は再生可能エネルギー技術における画期的な成果をもたらした研究構想の先頭に立った。',
  'The newly appointed CEO spearheaded a radical restructuring plan to revitalize the struggling company.',
  '新任のCEOは苦境にある会社を再生するための抜本的なリストラ計画の先頭に立った。'),
(572, 'installment', '(分割払いの)1回分の支払い', '/ɪnˈstɔːlmənt/', 'インストールメント',
  'The consumer opted to pay for the expensive appliance in twelve monthly installments rather than a single lump sum.',
  'その消費者は高額な家電を一括払いではなく12回の月々の分割払いで支払うことを選んだ。',
  'Failure to make the required installment payment by the deadline will result in additional penalties and interest charges.',
  '期限までに必要な分割払いを行わない場合、追加の違約金と利息が発生する。'),
(573, 'exemplify', '~の典型例となる、~を例証する', '/ɪɡˈzemplɪfaɪ/', 'イグゼンプリファイ',
  'The architect''s minimalist designs exemplify the modern aesthetic that has dominated urban construction in recent years.',
  'その建築家のミニマリストなデザインは、近年の都市建築を支配してきたモダンな美学を典型的に示している。',
  'Her extraordinary career exemplifies what can be achieved through perseverance and unwavering dedication to one''s craft.',
  '彼女の並外れたキャリアは、忍耐と自らの技術への揺るぎない献身によって何が達成できるかを例証している。'),
(574, 'daunting', '人の気力をくじく、非常に手ごわい', '/ˈdɔːntɪŋ/', 'ドーンティング',
  'The daunting task of rebuilding the war-torn nation''s infrastructure required unprecedented international cooperation.',
  '戦争で荒廃した国のインフラを再建するという非常に手ごわい課題には前例のない国際協力が必要であった。',
  'Many graduates find the prospect of entering the highly competitive job market a daunting experience.',
  '多くの卒業生にとって、競争の激しい就職市場に参入する見通しは気力をくじかれる経験である。'),
(575, 'momentum', '(もの・活動の)勢い、はずみ', '/moʊˈmentəm/', 'モメンタム',
  'The grassroots movement gained significant momentum after several prominent public figures endorsed its cause.',
  'その草の根運動は数人の著名な公人がその大義を支持した後、大きな勢いを得た。',
  'The reform initiative lost momentum when key stakeholders withdrew their support due to budgetary concerns.',
  '予算上の懸念から主要な関係者が支持を撤回したため、改革の取り組みは勢いを失った。'),
(576, 'proximity', '(時間・距離・関係などが)近いこと', '/prɑːkˈsɪməti/', 'プロクシミティ',
  'The proximity of the new residential complex to the industrial zone raised serious concerns about air quality among residents.',
  '新しい住宅団地と工業地帯が近いことが、住民の間で大気の質に関する深刻な懸念を引き起こした。',
  'Research suggests that proximity to green spaces has a measurably positive impact on mental health and well-being.',
  '研究によると、緑地に近いことは精神的健康と幸福に測定可能な良い影響を与えるという。'),
(577, 'ubiquitous', '至るところに存在する、遍在する', '/juːˈbɪkwɪtəs/', 'ユビクウィタス',
  'Smartphones have become so ubiquitous that it is nearly impossible to find someone without one in developed countries.',
  'スマートフォンは非常に遍在するようになり、先進国ではスマートフォンを持たない人を見つけることはほぼ不可能である。',
  'The ubiquitous presence of surveillance cameras in modern cities has sparked an intense debate over personal privacy.',
  '現代都市における監視カメラの至るところに存在する状況が、個人のプライバシーに関する激しい議論を引き起こしている。'),
(578, 'arid', '(土地・気候などが)乾燥した', '/ˈærɪd/', 'アリッド',
  'Innovative irrigation techniques have enabled farmers to cultivate crops even in the most arid regions of the continent.',
  '革新的な灌漑技術により、農家は大陸の最も乾燥した地域でさえ作物を栽培できるようになった。',
  'Climate change is expected to transform currently fertile areas into arid wastelands within the next few decades.',
  '気候変動により、現在肥沃な地域が今後数十年以内に乾燥した荒れ地に変わると予想されている。'),
(579, 'obscurity', '世に知られていないこと、無名', '/əbˈskjʊrəti/', 'オブスキュリティ',
  'The painter lived in complete obscurity during his lifetime, only achieving posthumous recognition for his masterpieces.',
  'その画家は生涯を通じて完全な無名の中で暮らし、傑作が認められたのは死後のことであった。',
  'After decades of obscurity, the forgotten scientific theory was revived and validated by modern experimental methods.',
  '数十年の無名の期間を経て、忘れ去られた科学理論が現代の実験手法によって復活し、実証された。'),
(580, 'banal', '陳腐な、ありふれた', '/bəˈnɑːl/', 'バナール',
  'The film critic dismissed the blockbuster as banal, arguing that its predictable plot offered nothing original to audiences.',
  'その映画評論家はその大作映画を陳腐だと一蹴し、予測可能なプロットは観客に何も新しいものを提供していないと論じた。',
  'What began as a banal conversation about the weather gradually evolved into a profound philosophical discussion.',
  '天気についてのありふれた会話として始まったものが、徐々に深遠な哲学的議論へと発展した。'),
(581, 'encroach', '(領域などに)侵入する;(権利などを)侵害する', '/ɪnˈkroʊtʃ/', 'インクロウチ',
  'Urban development continues to encroach upon the habitats of endangered species at an alarming rate.',
  '都市開発が驚くべき速さで絶滅危惧種の生息地に侵入し続けている。',
  'Critics argued that the new surveillance legislation would encroach upon citizens'' fundamental right to privacy.',
  '批評家たちは新しい監視法が市民のプライバシーの基本的権利を侵害すると主張した。'),
(582, 'blister', '水膨れ、まめ', '/ˈblɪstər/', 'ブリスター',
  'The marathon runner developed painful blisters on both feet after completing the grueling forty-two-kilometer course.',
  'そのマラソンランナーは過酷な42キロのコースを走り終えた後、両足に痛みを伴う水膨れができた。',
  'Prolonged exposure to the scorching sun caused severe blisters on the construction workers'' unprotected skin.',
  '灼熱の太陽への長時間の露出により、建設作業員の保護されていない皮膚にひどい水膨れが生じた。'),
(583, 'longevity', '寿命;長寿', '/lɑːnˈdʒevəti/', 'ロンジェヴィティ',
  'The remarkable longevity of the inhabitants of Okinawa has attracted the attention of researchers worldwide.',
  '沖縄の住民の驚くべき長寿は世界中の研究者の注目を集めてきた。',
  'Advances in medical science have contributed significantly to the increased longevity observed across developed nations.',
  '医学の進歩は先進国全体で観察される寿命の延長に大きく貢献している。'),
(584, 'verification', '確証、証拠', '/ˌverɪfɪˈkeɪʃən/', 'ヴェリフィケイション',
  'The bank requires identity verification through multiple documents before processing any large financial transaction.',
  'その銀行は大口の金融取引を処理する前に、複数の書類による本人確認を要求する。',
  'Independent verification of the experimental results is essential before the findings can be published in a peer-reviewed journal.',
  '実験結果の独立した検証は、その発見を査読付き学術誌に発表する前に不可欠である。'),
(585, 'envoy', '使節、使者', '/ˈenvɔɪ/', 'エンヴォイ',
  'The president dispatched a special envoy to negotiate a ceasefire agreement between the warring factions.',
  '大統領は交戦する派閥間の停戦協定を交渉するために特使を派遣した。',
  'The diplomatic envoy spent months shuttling between the two capitals in an effort to resolve the border dispute.',
  'その外交使節は国境紛争の解決に向けて数か月間二つの首都を往復した。'),
(586, 'incur', '(負債・損害など)を負う、こうむる;(怒り・非難など)を受ける', '/ɪnˈkɜːr/', 'インカー',
  'The company incurred substantial financial losses as a result of the prolonged legal battle with its former partner.',
  'その会社は元パートナーとの長引く法廷闘争の結果、多額の財務的損失を負った。',
  'Patients who seek treatment at out-of-network hospitals may incur significantly higher medical expenses.',
  'ネットワーク外の病院で治療を受ける患者は、大幅に高い医療費を負うことがある。'),
(587, 'gauge', '(状況など)を慎重に評価する、判断する;(計器で)~を正確に測る', '/ɡeɪdʒ/', 'ゲイジ',
  'The survey was designed to gauge public opinion on the government''s proposed reforms to the healthcare system.',
  'その調査は政府が提案した医療制度改革に対する世論を測るために設計された。',
  'It is difficult to gauge the long-term environmental impact of deep-sea mining without comprehensive scientific research.',
  '包括的な科学的研究なしに深海採鉱の長期的な環境への影響を慎重に評価することは困難である。'),
(588, 'foster', '(才能など)を育む、促進する;(他人の子ども)を養育する', '/ˈfɔːstər/', 'フォスター',
  'The educational program was specifically designed to foster critical thinking skills among underprivileged youth.',
  'その教育プログラムは恵まれない若者の批判的思考力を育むために特別に設計された。',
  'The government introduced new incentives to encourage families to foster children who had been placed in institutional care.',
  '政府は施設に入所した子どもを養育する家族を奨励するための新しい優遇措置を導入した。'),
(589, 'smuggle', '(こっそり)(人・もの)を持ち込む、連れ込む;~を密輸する', '/ˈsmʌɡl/', 'スマグル',
  'Customs officials intercepted an attempt to smuggle priceless ancient artifacts out of the country through a hidden compartment.',
  '税関職員は隠し区画を通じて貴重な古代遺物を国外に密輸しようとする試みを阻止した。',
  'The criminal network was dismantled after authorities discovered it had been smuggling counterfeit goods across international borders.',
  '当局が偽造品を国際的な国境を越えて密輸していたことを発見した後、その犯罪ネットワークは解体された。'),
(590, 'eviction', '(土地・建物からの)追い立て、立ち退き', '/ɪˈvɪkʃən/', 'イヴィクション',
  'The mass eviction of tenants from the housing complex sparked widespread protests throughout the city.',
  '住宅団地からの入居者の大量立ち退きは市全体で広範な抗議運動を引き起こした。',
  'Tenants facing eviction are entitled to legal representation and must be given adequate notice under the new housing law.',
  '新しい住宅法の下では、立ち退きに直面する入居者は法的代理人を得る権利があり、十分な通知を受けなければならない。'),
(591, 'lurk', '潜む、潜伏する', '/lɜːrk/', 'ラーク',
  'Cybersecurity experts warned that sophisticated malware could lurk undetected in corporate networks for months.',
  'サイバーセキュリティの専門家は、高度なマルウェアが企業ネットワーク内に何か月も検知されずに潜伏する可能性があると警告した。',
  'Beneath the calm surface of the negotiations, serious disagreements lurked that threatened to derail the entire process.',
  '交渉の穏やかな表面の下には、プロセス全体を頓挫させかねない深刻な意見の相違が潜んでいた。'),
(592, 'dire', '(状況・結果などが)ひどい、悲惨な', '/daɪər/', 'ダイアー',
  'The humanitarian agency issued a dire warning about the famine spreading rapidly through the drought-stricken region.',
  '人道支援機関は干ばつに見舞われた地域で急速に広がる飢饉について悲惨な警告を発した。',
  'The company found itself in dire financial straits after its largest client abruptly terminated the multimillion-dollar contract.',
  '最大の顧客が数百万ドルの契約を突然解除した後、その会社はひどい財政的苦境に陥った。'),
(593, 'wreak', '(損害など)をもたらす', '/riːk/', 'リーク',
  'The category-five hurricane wreaked unprecedented devastation on the coastal communities, displacing tens of thousands of residents.',
  'カテゴリー5のハリケーンは沿岸のコミュニティに前例のない壊滅的被害をもたらし、数万人の住民が避難を余儀なくされた。',
  'Years of neglected maintenance wreaked havoc on the aging infrastructure, leading to a catastrophic bridge collapse.',
  '何年にもわたるメンテナンスの怠慢が老朽化したインフラに大損害をもたらし、壊滅的な橋の崩落につながった。'),
(594, 'burgeon', '急速に発展[成長]する;(植物が)芽吹く', '/ˈbɜːrdʒən/', 'バージョン',
  'The burgeoning technology sector in the region has attracted substantial foreign investment over the past decade.',
  'その地域で急速に発展するテクノロジーセクターは過去10年間で多額の外国投資を呼び込んだ。',
  'As spring arrived, wildflowers burgeoned across the meadows, transforming the barren landscape into a vibrant tapestry of color.',
  '春が訪れると野の花が草原一面に芽吹き、荒涼とした風景を鮮やかな色彩のタペストリーに変えた。'),
(595, 'cumulative', '(効果・影響などが)しだいに増える、累積的な', '/ˈkjuːmjəleɪtɪv/', 'キュームレイティヴ',
  'The cumulative effect of years of air pollution has caused irreversible damage to the region''s ecosystem.',
  '何年にもわたる大気汚染の累積的な影響がその地域の生態系に不可逆的な被害をもたらした。',
  'Researchers found that the cumulative impact of sleep deprivation on cognitive function is far greater than previously assumed.',
  '研究者たちは睡眠不足の認知機能への累積的な影響が以前考えられていたよりもはるかに大きいことを発見した。'),
(596, 'fraught', '(危険・困難などに)満ちた;(人が)心配そうな', '/frɔːt/', 'フロート',
  'The peace negotiations were fraught with tension as both sides remained deeply mistrustful of each other''s intentions.',
  '和平交渉は双方が互いの意図を深く不信に思ったまま緊張に満ちたものだった。',
  'The expedition through the uncharted jungle was fraught with danger, from venomous snakes to flash floods.',
  '未踏のジャングルを通る探検は毒蛇から鉄砲水まで危険に満ちていた。'),
(597, 'decipher', '(暗号など)を解読する;(不明瞭な文字など)を判読する', '/dɪˈsaɪfər/', 'ディサイファー',
  'The cryptographer spent years attempting to decipher the ancient manuscript written in an unknown script.',
  'その暗号解読者は未知の文字で書かれた古代の写本を解読しようと何年も費やした。',
  'Even experienced physicians sometimes struggle to decipher the notoriously illegible handwriting of their colleagues.',
  '経験豊富な医師でさえ、同僚の読みにくいことで有名な手書き文字を判読するのに苦労することがある。'),
(598, 'adherent', '(政党・理念などの)信奉者、支持者', '/ədˈhɪrənt/', 'アドヒアレント',
  'The political movement attracted a growing number of adherents who were disillusioned with the established parties.',
  'その政治運動は既成政党に幻滅した増え続ける信奉者を引きつけた。',
  'Adherents of the philosophical school argued passionately that ethical considerations should take precedence over economic growth.',
  'その哲学学派の支持者たちは倫理的配慮が経済成長よりも優先されるべきだと情熱的に主張した。'),
(599, 'bombardment', '爆撃、砲撃', '/bɑːmˈbɑːrdmənt/', 'ボンバードメント',
  'The relentless bombardment of the besieged city continued for weeks, reducing entire neighborhoods to rubble.',
  '包囲された都市への容赦ない砲撃は数週間続き、地区全体が瓦礫と化した。',
  'Civilians sought refuge in underground shelters to escape the nightly bombardment during the prolonged military conflict.',
  '市民は長引く軍事紛争の間、夜間の爆撃を逃れるために地下シェルターに避難した。'),
(600, 'juggle', '(時間・仕事など)をうまくやり繰りする', '/ˈdʒʌɡl/', 'ジャグル',
  'Many working parents struggle to juggle the competing demands of their careers and their children''s education.',
  '多くの働く親はキャリアと子どもの教育という相反する要求をうまくやり繰りするのに苦労している。',
  'The project manager had to juggle multiple deadlines simultaneously while ensuring that quality standards were not compromised.',
  'そのプロジェクトマネージャーは品質基準が損なわれないようにしながら、複数の締め切りを同時にやり繰りしなければならなかった。');
