-- words テーブル INSERT文 (No.701 ~ No.750)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(701, 'retroactively', '(法律の効力などが)さかのぼって', '/ˌrɛtroʊˈæktɪvli/', 'レトロアクティヴリ',
  'The new tax regulation was applied retroactively, forcing companies to recalculate their earnings from the previous fiscal year.',
  '新しい税制がさかのぼって適用され、企業は前年度の収益を再計算せざるを得なくなった。',
  'The court ruled that the amendment could not be enforced retroactively, as it would violate constitutional protections.',
  '裁判所は、その改正をさかのぼって施行することは憲法上の保護に違反するとの判断を下した。'),
(702, 'rowdy', '乱暴な、騒々しい', '/ˈraʊdi/', 'ラウディ',
  'The rowdy spectators were ejected from the stadium after they hurled objects onto the playing field during the match.',
  '試合中にフィールドに物を投げ込んだ騒々しい観客たちはスタジアムから退場させられた。',
  'The once-quiet neighborhood has become increasingly rowdy since the new entertainment district opened nearby.',
  'かつて静かだったその地域は、近くに新しい歓楽街が開業して以来、ますます騒々しくなった。'),
(703, 'stump', '(難題などが)(人)を困らせる', '/stʌmp/', 'スタンプ',
  'The final question on the examination stumped even the most brilliant students in the advanced mathematics course.',
  '試験の最後の問題は、上級数学コースの最も優秀な学生たちさえも困らせた。',
  'Detectives were completely stumped by the lack of physical evidence at the crime scene.',
  '刑事たちは犯行現場に物的証拠がまったくないことに完全に困惑した。'),
(704, 'protrude', '突き出る', '/proʊˈtruːd/', 'プロトゥルード',
  'A jagged piece of metal protruded from the wreckage, posing a serious hazard to the rescue workers.',
  'ぎざぎざの金属片が残骸から突き出ており、救助隊員にとって重大な危険をもたらしていた。',
  'The geologist noted that several unusual rock formations protruded from the cliff face along the coastline.',
  '地質学者は、海岸線に沿って崖の表面からいくつかの珍しい岩石層が突き出ていることを指摘した。'),
(705, 'laudable', '(目標・努力などが)称賛に値する', '/ˈlɔːdəbl/', 'ローダブル',
  'While the government''s efforts to reduce carbon emissions are laudable, critics argue that the measures fall short of what is needed.',
  '政府の炭素排出量削減への取り組みは称賛に値するが、批評家たちはその対策が不十分だと主張している。',
  'The charity''s laudable mission to provide clean drinking water has transformed countless communities in developing nations.',
  '清潔な飲料水を提供するというその慈善団体の称賛に値する使命は、発展途上国の数え切れない地域社会を変えた。'),
(706, 'chauvinism', '男性優位主義;狂信的な優越心[愛国心]', '/ˈʃoʊvɪnɪzəm/', 'ショウヴィニズム',
  'The pervasive chauvinism in the corporate boardroom prevented qualified women from ascending to executive positions.',
  '企業の役員室に蔓延する男性優位主義が、有能な女性が経営幹部の地位に昇進することを妨げていた。',
  'His blind chauvinism led him to dismiss any criticism of his country''s foreign policy as unpatriotic.',
  '彼の盲目的な愛国心は、自国の外交政策に対するいかなる批判も非愛国的だとして退けることにつながった。'),
(707, 'skirmish', '小規模な戦闘、小競り合い', '/ˈskɜːrmɪʃ/', 'スカーミッシュ',
  'A brief skirmish broke out along the disputed border, raising fears of a full-scale military confrontation between the two nations.',
  '紛争中の国境沿いで小規模な戦闘が発生し、両国間の全面的な軍事衝突への懸念が高まった。',
  'The political skirmish between the two rival factions within the party threatened to derail the upcoming election campaign.',
  '党内の対立する二つの派閥間の小競り合いは、来たる選挙運動を頓挫させる恐れがあった。'),
(708, 'austerity', '(経済政策の)緊縮;厳格さ、厳しさ', '/ɔːˈstɛrəti/', 'オーステリティ',
  'The government''s austerity measures, which included drastic cuts to public services, sparked widespread protests across the nation.',
  '公共サービスの大幅な削減を含む政府の緊縮策は、全国的に広範な抗議活動を引き起こした。',
  'Years of austerity had taken their toll on the country''s healthcare system, leaving hospitals understaffed and underfunded.',
  '何年にもわたる緊縮財政は同国の医療制度に打撃を与え、病院は人手不足かつ資金不足の状態に陥った。'),
(709, 'abort', '(計画など)を中止する;(妊娠)を中絶する', '/əˈbɔːrt/', 'アボート',
  'Mission control made the difficult decision to abort the rocket launch after detecting a critical anomaly in the fuel system.',
  '管制センターは燃料系統に重大な異常を検知した後、ロケット打ち上げを中止するという困難な決断を下した。',
  'The expedition leader chose to abort the climb when the weather conditions deteriorated beyond acceptable safety thresholds.',
  '気象条件が許容できる安全基準を超えて悪化したため、遠征隊のリーダーは登山を中止することを選んだ。'),
(710, 'pry', '(私生活などを)のぞく、詮索する', '/praɪ/', 'プライ',
  'Journalists who pry into the private lives of public figures often face ethical dilemmas about the boundaries of press freedom.',
  '著名人の私生活を詮索するジャーナリストは、報道の自由の境界について倫理的ジレンマに直面することが多い。',
  'She resented her neighbors'' tendency to pry into her personal affairs and spread unfounded rumors throughout the community.',
  '彼女は近隣住民が自分の私事を詮索し、根拠のないうわさを地域中に広める傾向に憤慨していた。'),
(711, 'connoisseur', '(美術・食べ物などの)通、目利き、鑑定家', '/ˌkɒnəˈsɜːr/', 'コナサー',
  'As a connoisseur of fine wines, she could discern subtle differences in flavor that most casual drinkers would never notice.',
  'ワインの通である彼女は、ほとんどの一般的な飲み手には決して気づかないような微妙な味の違いを見分けることができた。',
  'The art connoisseur immediately recognized the painting as a forgery based on inconsistencies in the brushwork and pigmentation.',
  'その美術鑑定家は、筆遣いと色彩の不整合から、その絵画が贋作であることをすぐに見抜いた。'),
(712, 'impassive', '(顔・表情などが)感情を表さない、平然とした', '/ɪmˈpæsɪv/', 'インパッシヴ',
  'The defendant remained impassive throughout the trial, betraying no emotion even as the guilty verdict was announced.',
  '被告は裁判中ずっと平然としており、有罪の評決が言い渡されても一切の感情を見せなかった。',
  'Her impassive demeanor during the crisis earned her a reputation as an unflappable leader among her subordinates.',
  '危機的状況における彼女の平然とした態度は、部下たちの間で動じない指導者としての評判をもたらした。'),
(713, 'extenuating', '酌量すべき', '/ɪkˈstɛnjueɪtɪŋ/', 'イクステニュエイティング',
  'The judge took the extenuating circumstances into account and imposed a more lenient sentence than the prosecution had requested.',
  '裁判官は酌量すべき事情を考慮し、検察が求めたよりも寛大な判決を下した。',
  'Despite the severity of the offense, the defense attorney argued that extenuating factors such as poverty and mental illness should mitigate the penalty.',
  '犯行の重大さにもかかわらず、弁護士は貧困や精神疾患といった酌量すべき要因が刑罰を軽減すべきだと主張した。'),
(714, 'nocturnal', '(動物が)夜行性の、夜行動する', '/nɒkˈtɜːrnl/', 'ノクターナル',
  'Many nocturnal creatures, such as owls and bats, have evolved exceptional night vision to hunt effectively in darkness.',
  'フクロウやコウモリなどの多くの夜行性の生物は、暗闇の中で効果的に狩りをするために優れた夜間視力を進化させてきた。',
  'The researcher spent months documenting the nocturnal habits of the endangered species in its natural habitat.',
  'その研究者は、絶滅危惧種の夜行性の習性を自然の生息地で記録するのに数か月を費やした。'),
(715, 'squalid', '(環境などが)汚い、不潔な', '/ˈskwɒlɪd/', 'スクウォリッド',
  'The humanitarian workers were appalled by the squalid conditions in the refugee camp, where sanitation was virtually nonexistent.',
  '人道支援活動家たちは、衛生設備がほぼ皆無の難民キャンプの不潔な状況に愕然とした。',
  'Tenants living in squalid apartments filed a class-action lawsuit against the negligent landlord for failing to maintain habitable conditions.',
  '不潔なアパートに住む入居者たちは、居住可能な状態を維持しなかった怠慢な家主に対して集団訴訟を起こした。'),
(716, 'posthumous', '死後の、死後に起きた;(作品が)著者の死後に出版された', '/ˈpɒstʃʊməs/', 'ポスチュマス',
  'The novelist received a posthumous award for her final manuscript, which was published two years after her untimely death.',
  'その小説家は、早すぎる死から2年後に出版された最後の原稿で死後の賞を受けた。',
  'A posthumous exhibition of the artist''s previously unseen works attracted record-breaking attendance at the national gallery.',
  'その芸術家の未公開作品による死後の展覧会は、国立美術館で記録的な来場者数を集めた。'),
(717, 'maneuver', '(軍隊などの)作戦行動、軍事演習;操作、策略', '/məˈnuːvər/', 'マヌーヴァー',
  'The admiral''s brilliant naval maneuver caught the enemy fleet off guard and secured a decisive victory in the strait.',
  '提督の見事な海軍作戦行動は敵艦隊の不意を突き、海峡での決定的な勝利を確保した。',
  'The CEO''s political maneuver to restructure the board of directors was widely seen as an attempt to consolidate power.',
  '取締役会を再編するという最高経営責任者の政治的策略は、権力を強化する試みと広く見なされた。'),
(718, 'brawl', '(公衆の場での集団の)騒々しいけんか、乱闘', '/brɔːl/', 'ブロール',
  'A violent brawl erupted outside the nightclub, resulting in several injuries and multiple arrests by the responding officers.',
  'ナイトクラブの外で激しい乱闘が発生し、数人が負傷し、駆けつけた警察官によって複数人が逮捕された。',
  'The parliamentary session descended into a brawl when opposing lawmakers exchanged insults over the controversial legislation.',
  '物議を醸す法案をめぐって対立する議員たちが罵り合いを始め、国会の審議は乱闘に陥った。'),
(719, 'chiseled', '筋骨隆々の;(顔などが)彫りの深い', '/ˈtʃɪzld/', 'チズルド',
  'The marble statue featured a chiseled physique that embodied the classical ideals of strength and beauty.',
  'その大理石像は、古典的な力と美の理想を体現する筋骨隆々の体格を特徴としていた。',
  'His chiseled jawline and piercing gaze made him an ideal candidate for the lead role in the historical drama.',
  '彼の彫りの深い顎のラインと鋭いまなざしは、時代劇の主役にうってつけだった。'),
(720, 'deadlock', '(交渉などの)行き詰まり、こう着状態;(競技の)同点', '/ˈdɛdlɒk/', 'デッドロック',
  'Negotiations between the labor union and management reached a deadlock over the issue of pension reform.',
  '年金改革の問題をめぐって、労働組合と経営側の交渉は行き詰まりに達した。',
  'The committee chair proposed a compromise to break the deadlock that had stalled the legislative process for weeks.',
  '委員長は、数週間にわたって立法手続きを停滞させていたこう着状態を打開するための妥協案を提案した。'),
(721, 'zest', '熱意、熱情、強い喜び;面白味、魅力', '/zɛst/', 'ゼスト',
  'Her infectious zest for life inspired everyone around her to pursue their passions with renewed vigor and enthusiasm.',
  '彼女の人生に対する伝染力のある熱意は、周囲のすべての人に新たな活力と情熱をもって夢を追い求めるよう促した。',
  'The addition of exotic spices lent a distinctive zest to the dish that elevated it far beyond ordinary cuisine.',
  'エキゾチックなスパイスの追加がその料理に独特の魅力を与え、平凡な料理をはるかに超えるものにした。'),
(722, 'omit', '(人・もの・情報など)を抜かす、省略する', '/oʊˈmɪt/', 'オミット',
  'The editor decided to omit several controversial passages from the memoir to avoid potential defamation lawsuits.',
  '編集者は名誉毀損訴訟の可能性を避けるため、回顧録からいくつかの物議を醸す箇所を省略することに決めた。',
  'Critics accused the historian of deliberately omitting crucial evidence that contradicted his central thesis.',
  '批評家たちは、その歴史家が自身の中心的な論点と矛盾する重要な証拠を意図的に省略したと非難した。'),
(723, 'audacity', '(人・計画・行為などの)大胆さ;厚かましさ', '/ɔːˈdæsəti/', 'オーダシティ',
  'The entrepreneur''s audacity in challenging the industry giants ultimately paid off when her startup captured a significant market share.',
  '業界の巨人たちに挑戦するというその起業家の大胆さは、彼女のスタートアップが大きな市場シェアを獲得したことで最終的に報われた。',
  'He had the audacity to demand a promotion after only three months on the job, which astonished his senior colleagues.',
  '彼は入社わずか3か月で昇進を要求するという厚かましさを見せ、先輩の同僚たちを驚かせた。'),
(724, 'devoid', '欠いている', '/dɪˈvɔɪd/', 'ディヴォイド',
  'The abandoned factory was devoid of any signs of life, its corridors echoing with nothing but the howl of the wind.',
  '廃工場には生命の気配が一切なく、廊下には風の唸り声だけが響いていた。',
  'His speech was technically flawless yet devoid of genuine emotion, leaving the audience feeling strangely unmoved.',
  '彼のスピーチは技術的には完璧だったが真の感情が欠けており、聴衆は奇妙なほど心を動かされなかった。'),
(725, 'malaise', '(人の)不調、不快感', '/mæˈleɪz/', 'マレイズ',
  'A general malaise swept through the workforce as rumors of impending layoffs circulated throughout the organization.',
  '差し迫った解雇のうわさが組織全体に広まるにつれ、全般的な不調感が従業員の間に広がった。',
  'The patient complained of a persistent malaise that defied diagnosis despite numerous medical examinations.',
  '患者は数多くの医療検査にもかかわらず診断がつかない持続的な不快感を訴えた。'),
(726, 'avenge', '(こと)の復讐をする、仕返しをする', '/əˈvɛndʒ/', 'アヴェンジ',
  'The protagonist swore to avenge his brother''s death, embarking on a perilous quest that would consume the rest of his life.',
  '主人公は兄の死の復讐を誓い、残りの人生を費やすことになる危険な旅に出た。',
  'Rather than seeking to avenge the injustice through violence, she channeled her anger into a powerful campaign for legal reform.',
  '暴力によって不正の復讐をするのではなく、彼女は怒りを法改正のための力強い運動に注いだ。'),
(727, 'blare', '騒々しく不快な音を立てる', '/blɛr/', 'ブレア',
  'Car horns blared incessantly in the gridlocked traffic, adding to the cacophony of the already chaotic downtown area.',
  '渋滞の中で車のクラクションが絶え間なく鳴り響き、すでに混沌とした繁華街の不協和音に拍車をかけた。',
  'The emergency sirens blared throughout the city, warning residents to evacuate immediately ahead of the approaching hurricane.',
  '非常警報が街中で鳴り響き、接近するハリケーンに先立って直ちに避難するよう住民に警告した。'),
(728, 'regurgitate', '(飲み込んだ食べ物)を口に戻す、吐く;(他人の言葉など)を受け売りする', '/rɪˈɡɜːrdʒɪteɪt/', 'リガージテイト',
  'Students who merely regurgitate textbook information without critical analysis will struggle in advanced academic settings.',
  '批判的分析なしに教科書の情報をただ受け売りするだけの学生は、高度な学術環境では苦労するだろう。',
  'Certain bird species regurgitate partially digested food to nourish their young during the first weeks after hatching.',
  '特定の鳥類は、孵化後最初の数週間に半消化の食べ物を口に戻してひなに栄養を与える。'),
(729, 'convene', '(人・会議など)を招集する;(会議)を開催する', '/kənˈviːn/', 'コンヴィーン',
  'The United Nations convened an emergency session to address the escalating humanitarian crisis in the conflict-affected region.',
  '国連は、紛争の影響を受けた地域で深刻化する人道的危機に対処するため緊急会合を招集した。',
  'The board of directors will convene next week to deliberate on the proposed merger with the multinational corporation.',
  '取締役会は来週、多国籍企業との合併案について審議するために招集される予定である。'),
(730, 'sever', '(関係・つながり)を断つ;(ひも・体の一部など)を切断する', '/ˈsɛvər/', 'セヴァー',
  'The two countries severed diplomatic relations following a series of provocative military exercises near the shared border.',
  '共有する国境付近での一連の挑発的な軍事演習を受けて、両国は外交関係を断絶した。',
  'The accident severed the main power cable, plunging the entire district into darkness for several hours.',
  'その事故で主要な電力ケーブルが切断され、地区全体が数時間にわたって停電した。'),
(731, 'scuttle', '(計画など)を駄目にする、水の泡にする', '/ˈskʌtl/', 'スカトル',
  'The leaked documents effectively scuttled the merger negotiations, as both parties lost confidence in maintaining confidentiality.',
  '流出した文書によって合併交渉は事実上駄目になった。双方とも機密保持への信頼を失ったためである。',
  'Opposition lawmakers worked tirelessly to scuttle the controversial bill before it could reach the final vote in parliament.',
  '野党の議員たちは、物議を醸す法案が国会の最終投票に達する前にそれを廃案にしようと精力的に活動した。'),
(732, 'intravenous', '静脈注射の、点滴の', '/ˌɪntrəˈviːnəs/', 'イントラヴィーナス',
  'The patient was administered intravenous antibiotics to combat the severe infection that had spread to the bloodstream.',
  '血流に広がった重度の感染症と闘うため、患者に静脈注射で抗生物質が投与された。',
  'Intravenous hydration therapy is commonly used to treat patients suffering from acute dehydration caused by heatstroke.',
  '点滴による水分補給療法は、熱中症による急性脱水症状の患者の治療に一般的に用いられる。'),
(733, 'surreptitiously', 'ひそかに、こっそりと', '/ˌsʌrəpˈtɪʃəsli/', 'サレプティシャスリ',
  'The spy surreptitiously photographed classified documents while the security guard was distracted by a staged commotion.',
  'スパイは、警備員が仕組まれた騒動に気を取られている間に、機密文書をこっそりと撮影した。',
  'The executive surreptitiously transferred company funds into a personal offshore account over the course of several years.',
  'その幹部は数年にわたり、会社の資金をひそかに個人のオフショア口座に移していた。'),
(734, 'painstaking', '細心の注意を払った、丹念な;骨の折れる', '/ˈpeɪnzteɪkɪŋ/', 'ペインステイキング',
  'The restoration of the centuries-old fresco required painstaking effort by a team of highly skilled conservators.',
  '数世紀前のフレスコ画の修復には、高度な技術を持つ修復専門家チームによる丹念な作業が必要だった。',
  'Through painstaking research spanning over a decade, the archaeologist finally unearthed evidence of the lost civilization.',
  '10年以上にわたる骨の折れる研究を経て、その考古学者はついに失われた文明の証拠を発掘した。'),
(735, 'illegible', '(文字・印刷などが)読みにくい、判読できない', '/ɪˈlɛdʒəbl/', 'イレジブル',
  'The ancient manuscript had become so faded and worn that many passages were virtually illegible to modern scholars.',
  'その古代の写本は非常に色あせて傷んでおり、多くの箇所が現代の学者にはほぼ判読できない状態だった。',
  'The pharmacist refused to fill the prescription because the doctor''s handwriting was completely illegible.',
  '医師の手書きの文字がまったく読めなかったため、薬剤師は処方箋の調剤を拒否した。'),
(736, 'ratification', '(合意・条約などの)批准、承認', '/ˌrætɪfɪˈkeɪʃn/', 'ラティフィケイション',
  'The ratification of the international climate accord required the approval of at least two-thirds of the member states.',
  '国際気候協定の批准には、少なくとも加盟国の3分の2の承認が必要だった。',
  'Delays in the ratification process threatened to undermine the fragile peace agreement between the warring factions.',
  '批准手続きの遅れは、交戦中の派閥間の脆弱な和平合意を損なう恐れがあった。'),
(737, 'scam', '詐欺、ぺてん', '/skæm/', 'スキャム',
  'Thousands of elderly citizens fell victim to an elaborate online scam that siphoned millions from their retirement savings.',
  '何千人もの高齢者が、退職貯蓄から数百万を吸い上げる巧妙なオンライン詐欺の被害者になった。',
  'The investment scam promised unrealistically high returns, which should have been a clear warning sign for potential investors.',
  'その投資詐欺は非現実的に高いリターンを約束しており、潜在的な投資家にとって明確な警告サインであるべきだった。'),
(738, 'equitable', '(決定・分配などが)公平な、公正な', '/ˈɛkwɪtəbl/', 'エクウィタブル',
  'The mediator proposed an equitable distribution of assets that both parties in the divorce proceedings found acceptable.',
  '調停人は、離婚手続きの双方が受け入れ可能な公平な資産分配を提案した。',
  'Achieving equitable access to quality healthcare remains one of the most pressing challenges facing developing nations.',
  '質の高い医療への公平なアクセスを実現することは、発展途上国が直面する最も喫緊の課題の一つであり続けている。'),
(739, 'innately', '生まれつき、生来、本質的に', '/ɪˈneɪtli/', 'イネイトリ',
  'Some researchers argue that humans are innately predisposed to acquire language, citing evidence from infant developmental studies.',
  '一部の研究者は、乳児の発達研究からの証拠を挙げて、人間は生まれつき言語を習得する素質を持っていると主張している。',
  'The prodigy seemed innately gifted in mathematics, solving equations at the age of four that would challenge most adults.',
  'その神童は生まれつき数学の才能に恵まれているようで、大人でも苦労するような方程式を4歳で解いていた。'),
(740, 'grudge', '恨み、悪意', '/ɡrʌdʒ/', 'グラッジ',
  'She harbored a deep grudge against her former business partner, who had embezzled funds from their joint venture.',
  '彼女は、共同事業から資金を横領した元ビジネスパートナーに対して深い恨みを抱いていた。',
  'Holding a grudge for years can have detrimental effects on both mental health and interpersonal relationships.',
  '何年も恨みを抱き続けることは、精神的健康と対人関係の両方に悪影響を及ぼしうる。'),
(741, 'optimum', '(条件・状態などが)最適の、最高の', '/ˈɒptɪməm/', 'オプティマム',
  'The research team identified the optimum temperature for cultivating the rare bacterial strain used in the experimental vaccine.',
  '研究チームは、実験的ワクチンに使用される希少な細菌株を培養するための最適温度を特定した。',
  'Athletes must maintain optimum nutrition and hydration levels to perform at their peak during competitive events.',
  'アスリートは競技イベントで最高のパフォーマンスを発揮するために、最適な栄養と水分補給のレベルを維持しなければならない。'),
(742, 'converge', '(人・乗り物などが)集まる、集結する、群がる', '/kənˈvɜːrdʒ/', 'コンヴァージ',
  'Thousands of demonstrators converged on the capital to demand comprehensive reforms to the electoral system.',
  '数千人のデモ参加者が選挙制度の包括的な改革を要求するために首都に集結した。',
  'Several independent lines of scientific evidence converge to support the theory of anthropogenic climate change.',
  '複数の独立した科学的証拠が集約され、人為的な気候変動の理論を裏付けている。'),
(743, 'snowball', '雪だるま式に増加する', '/ˈsnoʊbɔːl/', 'スノウボール',
  'What began as a minor accounting error snowballed into a massive financial scandal that brought down the entire corporation.',
  '些細な会計ミスとして始まったことが雪だるま式に膨れ上がり、会社全体を倒産に追い込む大規模な金融スキャンダルとなった。',
  'Public outrage over the incident snowballed after a video of the confrontation went viral on social media platforms.',
  'その事件に対する世論の怒りは、対立の映像がソーシャルメディアで拡散した後、雪だるま式に増加した。'),
(744, 'abridged', '短縮された、簡約版の', '/əˈbrɪdʒd/', 'アブリッジド',
  'The publisher released an abridged version of the epic novel to make it more accessible to younger readers.',
  '出版社は、その大作小説をより若い読者にとって読みやすくするために簡約版を出版した。',
  'Scholars criticized the abridged edition for omitting critical passages that were essential to understanding the author''s intent.',
  '学者たちは、著者の意図を理解するのに不可欠な重要な箇所を省略した簡約版を批判した。'),
(745, 'thrifty', '質素な、倹約する', '/ˈθrɪfti/', 'スリフティ',
  'Her thrifty habits, cultivated during years of financial hardship, enabled her to accumulate substantial savings over time.',
  '長年の経済的困難の中で培われた彼女の倹約の習慣により、時間をかけて相当な貯蓄を蓄えることができた。',
  'The thrifty homeowner installed solar panels and rainwater collection systems to reduce long-term utility expenses.',
  '倹約家のその住宅所有者は、長期的な光熱費を削減するためにソーラーパネルと雨水収集システムを設置した。'),
(746, 'mutter', '(~を)つぶやく;(~と)不平を言う', '/ˈmʌtər/', 'マター',
  'The disgruntled employee muttered complaints under his breath as he reluctantly carried out the tedious assignment.',
  '不満を抱えた従業員は、退屈な作業を渋々こなしながら小声で不平をつぶやいた。',
  'She muttered an apology so quietly that no one in the conference room could actually hear what she said.',
  '彼女はあまりにも静かに謝罪をつぶやいたため、会議室の誰も実際に彼女が何を言ったか聞き取れなかった。'),
(747, 'enunciate', '(言葉)を明瞭に発音する', '/ɪˈnʌnsieɪt/', 'イナンシエイト',
  'The speech therapist taught her patient to enunciate each syllable clearly, which dramatically improved his public speaking ability.',
  '言語療法士は患者に各音節を明瞭に発音するよう指導し、それが彼のスピーチ能力を劇的に向上させた。',
  'When addressing a multilingual audience, it is essential to enunciate your words carefully to ensure comprehension.',
  '多言語の聴衆に語りかける際は、理解を確実にするために言葉を注意深く明瞭に発音することが不可欠である。'),
(748, 'inhale', '(空気・煙などを)吸い込む、吸入する', '/ɪnˈheɪl/', 'インヘイル',
  'Residents near the chemical plant were advised not to inhale the toxic fumes that had been released during the industrial accident.',
  '化学工場の近隣住民は、産業事故で放出された有毒ガスを吸い込まないよう忠告された。',
  'The yoga instructor guided participants to inhale deeply through the nose and exhale slowly through the mouth.',
  'ヨガのインストラクターは参加者に、鼻から深く吸い込み、口からゆっくり吐き出すよう指導した。'),
(749, 'consignment', '発送された商品[荷物]', '/kənˈsaɪnmənt/', 'コンサインメント',
  'The customs officials inspected the consignment of electronics and discovered a large quantity of counterfeit goods concealed within.',
  '税関職員が電子機器の荷物を検査したところ、中に大量の偽造品が隠されているのを発見した。',
  'The first consignment of humanitarian aid arrived at the disaster-stricken area within forty-eight hours of the earthquake.',
  '人道支援物資の最初の荷物は、地震から48時間以内に被災地に届いた。'),
(750, 'frazzled', 'へとへとに疲れた', '/ˈfræzld/', 'フラズルド',
  'After working sixteen-hour shifts for an entire week, the frazzled medical staff desperately needed time to recuperate.',
  '丸一週間16時間交代で働いた後、へとへとに疲れた医療スタッフは回復するための時間が切実に必要だった。',
  'The frazzled executive finally decided to take a sabbatical after years of relentless pressure from the demanding corporate environment.',
  'へとへとに疲れたその幹部は、厳しい企業環境からの何年にもわたる絶え間ないプレッシャーの末、ついにサバティカルを取ることに決めた。');
