-- words テーブル INSERT文 (No.851 ~ No.900)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(851, 'inveterate', '(病気・悪習・感情などが)根深い、頑固な', '/ɪnˈvɛtərɪt/', 'インヴェタリト',
  'The inveterate gambler squandered his entire inheritance despite repeated warnings from his family.',
  'その根深い賭博癖のある男は、家族からの再三の忠告にもかかわらず、遺産をすべて使い果たした。',
  'Her inveterate optimism remained unshaken even in the face of the most daunting professional setbacks.',
  '最も困難な仕事上の挫折に直面しても、彼女の根深い楽観主義は揺るがなかった。'),
(852, 'pester', '(人)をしつこく悩ます、困らせる', '/ˈpɛstər/', 'ペスター',
  'Lobbyists continued to pester the senator with demands for deregulation throughout the legislative session.',
  'ロビイストたちは立法会期を通じて規制緩和の要求で上院議員をしつこく悩ませ続けた。',
  'The journalist pestered the company spokesperson until she finally obtained a comment on the scandal.',
  'そのジャーナリストは、ついにスキャンダルに関するコメントを得るまで、会社の広報担当者をしつこく困らせた。'),
(853, 'mirage', '蜃気楼;幻覚、幻想', '/mɪˈrɑːʒ/', 'ミラージュ',
  'The economic recovery touted by the administration turned out to be nothing more than a mirage concealing deeper structural problems.',
  '政権が喧伝した景気回復は、より深い構造的問題を隠す幻想にすぎなかった。',
  'Exhausted travelers in the desert often mistake a mirage on the horizon for a genuine body of water.',
  '砂漠で疲弊した旅行者は、地平線上の蜃気楼を本物の水辺と見間違えることがよくある。'),
(854, 'ingratiate', '(人)のご機嫌を取る、~に取り入る', '/ɪnˈɡreɪʃieɪt/', 'イングレイシエイト',
  'The ambitious intern tried to ingratiate himself with the executives by volunteering for every menial task.',
  '野心的なインターンは、あらゆる雑務に自ら志願することで幹部たちに取り入ろうとした。',
  'Politicians often attempt to ingratiate themselves with voters by making extravagant promises during election campaigns.',
  '政治家は選挙運動中に大げさな公約をすることで有権者のご機嫌を取ろうとすることが多い。'),
(855, 'transgression', '違反、犯罪', '/trænzˈɡrɛʃən/', 'トランズグレッション',
  'The diplomat''s transgression of established protocol created a serious rift between the two allied nations.',
  'その外交官の確立された外交儀礼の違反は、二つの同盟国間に深刻な亀裂を生じさせた。',
  'Even minor transgressions against the company''s code of conduct can result in immediate termination.',
  '会社の行動規範に対する軽微な違反であっても、即座の解雇につながりうる。'),
(856, 'usurp', '(権力・地位など)を不法に奪う、強奪する', '/juːˈzɜːrp/', 'ユーザープ',
  'The military general attempted to usurp the president''s authority by declaring a state of emergency without parliamentary consent.',
  'その軍の将軍は、議会の同意なしに緊急事態を宣言して大統領の権限を不法に奪おうとした。',
  'Critics accused the judiciary of usurping legislative power by effectively rewriting the statute through its interpretation.',
  '批評家たちは、司法が解釈を通じて事実上法律を書き換えることで立法権を強奪していると非難した。'),
(857, 'exasperate', '(人)をいら立たせる、激しく怒らせる', '/ɪɡˈzæspəreɪt/', 'イグザスパレイト',
  'The government''s repeated failure to address the housing crisis has exasperated citizens across the political spectrum.',
  '住宅危機への対処を繰り返し怠ったことが、政治的立場を問わず国民をいら立たせている。',
  'The interminable bureaucratic delays exasperated the researchers who were eager to commence their clinical trials.',
  '終わりのない官僚的な遅延が、臨床試験を早く開始したいと切望していた研究者たちを激しく怒らせた。'),
(858, 'resuscitate', '~を蘇生させる;~を復活させる、復興する', '/rɪˈsʌsɪteɪt/', 'リサシテイト',
  'Paramedics worked frantically to resuscitate the drowning victim before the helicopter arrived.',
  '救急隊員たちはヘリコプターが到着する前に溺水者を蘇生させようと必死に処置した。',
  'The new CEO''s bold strategy managed to resuscitate the ailing corporation and restore investor confidence.',
  '新CEOの大胆な戦略は、経営不振の企業を復活させ、投資家の信頼を回復することに成功した。'),
(859, 'sojourn', '(一時的な)滞在', '/ˈsoʊdʒɜːrn/', 'ソウジャーン',
  'During her sojourn in Vienna, the scholar gained invaluable insights into the origins of psychoanalytic theory.',
  'ウィーンでの一時的な滞在中に、その学者は精神分析理論の起源について貴重な知見を得た。',
  'His brief sojourn in the rural village profoundly altered his perspective on sustainable agriculture.',
  '田舎の村での短い滞在が、持続可能な農業に対する彼の見方を根本的に変えた。'),
(860, 'parry', '(質問・議論など)をそらす、受け流す;(攻撃など)をかわす', '/ˈpæri/', 'パリー',
  'The prime minister deftly parried the opposition''s probing questions about the defense budget scandal.',
  '首相は防衛予算スキャンダルに関する野党の追及をうまくそらした。',
  'The fencer parried her opponent''s thrust with remarkable precision, then launched an immediate counterattack.',
  'そのフェンサーは見事な正確さで相手の突きをかわし、すぐさま反撃に転じた。'),
(861, 'pageant', '野外劇、歴史ショー', '/ˈpædʒənt/', 'パジャント',
  'The town staged an elaborate historical pageant to commemorate the 500th anniversary of its founding.',
  'その町は創立500周年を記念して精巧な歴史ショーを上演した。',
  'The medieval pageant attracted thousands of visitors who marveled at the authentic costumes and dramatic reenactments.',
  '中世の野外劇は何千人もの来場者を引きつけ、本物の衣装や迫力ある再現劇に感嘆した。'),
(862, 'omniscient', '全知の、博識の', '/ɑːmˈnɪʃənt/', 'アムニシャント',
  'The novel employs an omniscient narrator who reveals the innermost thoughts of every character simultaneously.',
  'その小説は、全知の語り手を用いてすべての登場人物の最も内面的な思考を同時に明らかにしている。',
  'No regulatory body is omniscient enough to foresee every potential risk in the rapidly evolving financial markets.',
  '急速に進化する金融市場のあらゆる潜在的リスクを予見できるほど全知の規制機関は存在しない。'),
(863, 'propitious', '好都合な、幸先のよい', '/prəˈpɪʃəs/', 'プロピシャス',
  'The ceasefire agreement created propitious conditions for the commencement of formal peace negotiations.',
  '停戦合意は正式な和平交渉の開始にとって好都合な条件を生み出した。',
  'Analysts believe the current economic climate is propitious for investment in renewable energy infrastructure.',
  'アナリストたちは、現在の経済状況は再生可能エネルギーのインフラ投資に好都合だと考えている。'),
(864, 'fumble', '(不器用に)手探りする', '/ˈfʌmbl/', 'ファンブル',
  'The nervous candidate fumbled for words when confronted with an unexpected question about fiscal policy.',
  '財政政策に関する予想外の質問に直面し、緊張した候補者は言葉を探して手探りした。',
  'He fumbled with the unfamiliar controls of the laboratory equipment, nearly causing a hazardous spill.',
  '彼は実験装置の不慣れな操作部を手探りし、危険な漏出を引き起こしかけた。'),
(865, 'enumerate', '~を数え上げる、列挙する', '/ɪˈnuːməreɪt/', 'イニューマレイト',
  'The report enumerates the specific violations committed by the corporation over the past decade.',
  'その報告書は、過去10年間にその企業が犯した具体的な違反を列挙している。',
  'The professor asked students to enumerate the key factors that contributed to the collapse of the ancient empire.',
  '教授は学生に、古代帝国の崩壊に寄与した主要な要因を数え上げるよう求めた。'),
(866, 'petulant', 'いらいらした、すねた', '/ˈpɛtʃələnt/', 'ペチュラント',
  'The petulant executive stormed out of the board meeting when his proposal was met with unanimous opposition.',
  'いらいらした幹部は、自分の提案が満場一致の反対に遭うと取締役会から怒って退席した。',
  'Critics dismissed the ambassador''s petulant response to the trade sanctions as diplomatically counterproductive.',
  '批評家たちは、貿易制裁に対する大使のすねた反応を外交的に逆効果だと一蹴した。'),
(867, 'hamper', '(動き・活動など)を妨害する;(進行など)を阻止する', '/ˈhæmpər/', 'ハンパー',
  'Severe flooding hampered rescue operations, leaving thousands of stranded residents without access to essential supplies.',
  '深刻な洪水が救助活動を妨害し、何千人もの取り残された住民が必需品を入手できなくなった。',
  'Excessive regulation continues to hamper innovation in the pharmaceutical industry, delaying the development of life-saving drugs.',
  '過度な規制が製薬業界の革新を妨害し続け、命を救う医薬品の開発を遅らせている。'),
(868, 'dismantle', '(機械など)を分解する、解体する;(組織・制度など)を廃止する', '/dɪsˈmæntl/', 'ディスマントル',
  'The government pledged to dismantle the outdated surveillance apparatus that had been criticized for infringing on civil liberties.',
  '政府は市民的自由を侵害していると批判された旧式の監視体制を廃止すると誓った。',
  'Engineers carefully dismantled the decommissioned nuclear reactor over a period of several years.',
  '技術者たちは数年をかけて、廃炉となった原子炉を慎重に解体した。'),
(869, 'stigma', '汚名、烙印、悪いイメージ', '/ˈstɪɡmə/', 'スティグマ',
  'The stigma associated with mental illness often prevents individuals from seeking the professional help they need.',
  '精神疾患に伴う汚名は、しばしば個人が必要な専門的支援を求めることを妨げる。',
  'The organization launched a nationwide campaign to eliminate the stigma surrounding addiction and substance abuse.',
  'その団体は、依存症と薬物乱用にまつわる悪いイメージを払拭するための全国的キャンペーンを開始した。'),
(870, 'deviate', '(車などが)それる;(人・行為などが)(規範などから)逸脱する', '/ˈdiːvieɪt/', 'ディーヴィエイト',
  'Any attempt to deviate from the established safety protocols will result in severe disciplinary action.',
  '確立された安全手順から逸脱するいかなる試みも、厳しい懲戒処分の対象となる。',
  'The spacecraft deviated from its planned trajectory due to an unforeseen gravitational anomaly.',
  '宇宙船は予期せぬ重力異常のために計画された軌道からそれた。'),
(871, 'fortify', '(都市など)の防御を固める、~を要塞化する', '/ˈfɔːrtɪfaɪ/', 'フォーティファイ',
  'The ancient city was fortified with massive stone walls that withstood numerous sieges over the centuries.',
  'その古代都市は巨大な石壁で防御を固められ、何世紀にもわたる数々の包囲戦に耐えた。',
  'The government allocated additional funds to fortify the coastal defenses against the threat of rising sea levels.',
  '政府は海面上昇の脅威に対して沿岸防御を強化するために追加資金を割り当てた。'),
(872, 'cerebral', '知的な、理性的な;脳の', '/ˈsɛrəbrəl/', 'セレブラル',
  'The film''s cerebral approach to exploring existential themes alienated mainstream audiences but captivated critics.',
  'その映画の実存的テーマを探求する知的なアプローチは一般の観客を遠ざけたが、批評家を魅了した。',
  'The patient was diagnosed with a cerebral hemorrhage and immediately transferred to the neurosurgery unit.',
  '患者は脳出血と診断され、直ちに脳神経外科に転送された。'),
(873, 'coalesce', '(グループなどが)連合する、合併する', '/ˌkoʊəˈlɛs/', 'コウアレス',
  'Several disparate opposition factions coalesced into a unified political movement to challenge the ruling party.',
  'いくつかの異なる野党勢力が連合し、与党に対抗する統一的な政治運動を形成した。',
  'The various research findings gradually coalesced into a comprehensive theory of cognitive development.',
  'さまざまな研究結果が徐々に合わさって、認知発達の包括的な理論となった。'),
(874, 'forage', '(食べ物を)あさる、探し回る', '/ˈfɔːrɪdʒ/', 'フォーリジ',
  'During the prolonged siege, desperate civilians were forced to forage for edible plants in the surrounding countryside.',
  '長期の包囲戦の間、絶望した市民たちは周辺の田園地帯で食用植物をあさることを余儀なくされた。',
  'Bears frequently forage near campgrounds in autumn as they prepare for hibernation.',
  '熊は冬眠の準備のため、秋にはキャンプ場の近くで食べ物を探し回ることが多い。'),
(875, 'hedge', '(金銭的損失からの)防護手段、損失防止策;生け垣、垣根', '/hɛdʒ/', 'ヘッジ',
  'Sophisticated investors use derivatives as a hedge against the volatility of international currency markets.',
  '洗練された投資家は、国際通貨市場の変動に対する防護手段としてデリバティブを利用する。',
  'The finance minister''s ambiguous statement was widely perceived as an attempt to hedge against potential policy failures.',
  '財務大臣のあいまいな発言は、潜在的な政策失敗に対する防護策を講じる試みとして広く受け止められた。'),
(876, 'shackle', '~を制限する、束縛する', '/ˈʃækl/', 'シャクル',
  'Outdated labor laws continue to shackle workers, preventing them from negotiating fair wages and conditions.',
  '時代遅れの労働法が労働者を束縛し続け、公正な賃金や条件の交渉を妨げている。',
  'The country''s economic growth has been shackled by an enormous national debt accumulated over decades.',
  'その国の経済成長は、何十年もかけて蓄積された巨額の国家債務によって制限されてきた。'),
(877, 'relinquish', '(権利・権力など)を放棄する', '/rɪˈlɪŋkwɪʃ/', 'リリンクウィッシュ',
  'The aging monarch reluctantly relinquished the throne to the crown prince amid mounting public pressure.',
  '高齢の君主は、高まる国民の圧力の中、しぶしぶ王位を皇太子に放棄した。',
  'The corporation was compelled to relinquish its patent rights as part of the antitrust settlement.',
  'その企業は独占禁止法の和解の一環として特許権を放棄することを余儀なくされた。'),
(878, 'smear', '~を塗りつける;~を汚す', '/smɪr/', 'スミアー',
  'The opposition party launched a vicious smear campaign designed to tarnish the incumbent''s reputation before the election.',
  '野党は選挙前に現職の評判を傷つけるための悪意ある中傷キャンペーンを展開した。',
  'The whistleblower alleged that the company had deliberately smeared the names of former employees who spoke out.',
  '内部告発者は、会社が声を上げた元従業員の名前を意図的に汚したと主張した。'),
(879, 'benevolent', '慈悲深い、親切な;慈善を行う', '/bəˈnɛvələnt/', 'ベネヴォレント',
  'The benevolent philanthropist donated an unprecedented sum to establish scholarships for underprivileged students.',
  '慈悲深い慈善家は、恵まれない学生のための奨学金を設立するために前例のない額を寄付した。',
  'What initially appeared to be a benevolent corporate initiative was later exposed as a calculated public relations strategy.',
  '当初は慈善的な企業の取り組みに見えたものが、後に計算された広報戦略であると暴露された。'),
(880, 'scourge', '災いの元凶;天罰、たたり', '/skɜːrdʒ/', 'スカージ',
  'Malaria remains a devastating scourge in tropical regions where access to preventive healthcare is severely limited.',
  'マラリアは、予防医療へのアクセスが著しく制限されている熱帯地域において依然として壊滅的な災いの元凶である。',
  'The international community must unite to combat the scourge of human trafficking that afflicts every continent.',
  '国際社会は、あらゆる大陸を苦しめている人身売買という災いの元凶と闘うために団結しなければならない。'),
(881, 'segregate', '(もの・場所など)を分ける、分割する;(人・集団)を差別する', '/ˈsɛɡrɪɡeɪt/', 'セグリゲイト',
  'The landmark court ruling declared it unconstitutional to segregate public schools on the basis of race.',
  '画期的な裁判所の判決は、人種に基づいて公立学校を分離することは違憲であると宣言した。',
  'Environmentalists demanded that the factory segregate its hazardous waste from recyclable materials.',
  '環境活動家たちは、工場が有害廃棄物をリサイクル可能な資材から分別することを要求した。'),
(882, 'preside', '(会議などで)議長[司会]を務める', '/prɪˈzaɪd/', 'プリザイド',
  'The chief justice will preside over the impeachment trial, ensuring that all proceedings adhere to constitutional guidelines.',
  '最高裁判所長官が弾劾裁判の議長を務め、すべての手続きが憲法の指針に従うことを保証する。',
  'She presided over the international summit with remarkable composure, mediating heated disputes between rival delegations.',
  '彼女は見事な冷静さで国際サミットの議長を務め、対立する代表団間の白熱した紛争を仲裁した。'),
(883, 'circumspect', '(人・行為などが)慎重な、用心深い', '/ˈsɜːrkəmspɛkt/', 'サーカムスペクト',
  'The seasoned diplomat was characteristically circumspect in her remarks, carefully avoiding any provocative statements.',
  '経験豊富な外交官はいつものように発言に慎重で、挑発的な発言を注意深く避けた。',
  'Investors should remain circumspect when evaluating startups that promise extraordinarily high returns.',
  '投資家は、異常に高いリターンを約束するスタートアップを評価する際には用心深くあるべきである。'),
(884, 'conglomeration', '集合体、集塊、寄せ集め;複合企業化', '/kənˌɡlɑːməˈreɪʃən/', 'コングラマレイション',
  'The city''s cultural district is a fascinating conglomeration of galleries, theaters, and independent bookshops.',
  'その都市の文化地区は、ギャラリー、劇場、独立系書店の魅力的な集合体である。',
  'The proposed merger would create an unwieldy conglomeration of businesses with little strategic synergy.',
  '提案された合併は、戦略的相乗効果がほとんどない扱いにくい企業の寄せ集めを生み出すことになる。'),
(885, 'venerable', '(人が)尊敬すべき;(建物・場所などが)由緒ある', '/ˈvɛnərəbl/', 'ヴェネラブル',
  'The venerable institution has produced numerous Nobel laureates throughout its distinguished three-century history.',
  'その由緒ある機関は、輝かしい3世紀の歴史を通じて数多くのノーベル賞受賞者を輩出してきた。',
  'The venerable professor emeritus delivered a keynote address that drew upon decades of pioneering research.',
  '尊敬すべき名誉教授は、数十年にわたる先駆的研究に基づく基調講演を行った。'),
(886, 'combustion', '燃焼;酸化', '/kəmˈbʌstʃən/', 'コンバスチョン',
  'The rapid transition away from internal combustion engines is reshaping the global automotive industry.',
  '内燃機関からの急速な転換が、世界の自動車産業を再形成している。',
  'The forensic investigator determined that spontaneous combustion of improperly stored chemicals caused the warehouse fire.',
  '法医学調査官は、不適切に保管された化学物質の自然発火が倉庫火災の原因であると断定した。'),
(887, 'illicit', '違法な、不法な;(道徳的に)許されない、不義の', '/ɪˈlɪsɪt/', 'イリシト',
  'International authorities dismantled a vast network responsible for the illicit trafficking of endangered species.',
  '国際当局は、絶滅危惧種の不法取引を行っていた広大なネットワークを解体した。',
  'The investigation revealed that illicit funds had been laundered through a series of offshore shell companies.',
  '捜査により、不法な資金がいくつかのオフショアのペーパーカンパニーを通じて洗浄されていたことが明らかになった。'),
(888, 'sequester', '(陪審員など)を隔離する', '/sɪˈkwɛstər/', 'シクウェスター',
  'The judge ordered the jury to be sequestered for the duration of the high-profile murder trial.',
  '裁判官は、注目を集める殺人裁判の期間中、陪審員を隔離するよう命じた。',
  'Scientists have explored innovative methods to sequester carbon dioxide deep beneath the ocean floor.',
  '科学者たちは、海底の深部に二酸化炭素を隔離する革新的な方法を模索してきた。'),
(889, 'sustenance', '生命の維持;食物;生計', '/ˈsʌstənəns/', 'サステナンス',
  'The refugees relied on humanitarian aid organizations for basic sustenance during the prolonged conflict.',
  '難民たちは長引く紛争の間、基本的な食物を人道支援団体に頼っていた。',
  'The artist found emotional sustenance in her creative work, which helped her endure years of personal hardship.',
  'その芸術家は創作活動に精神的な糧を見いだし、それが何年もの個人的苦難を乗り越える支えとなった。'),
(890, 'subjugate', '~を征服する;~を服従させる', '/ˈsʌbdʒʊɡeɪt/', 'サブジュゲイト',
  'The colonial empire sought to subjugate indigenous populations through a combination of military force and cultural suppression.',
  '植民地帝国は、軍事力と文化的抑圧の組み合わせによって先住民を征服しようとした。',
  'The authoritarian regime subjugated the press, silencing any form of dissent through censorship and intimidation.',
  '独裁政権は報道機関を服従させ、検閲と威嚇によってあらゆる形の反対意見を封じた。'),
(891, 'covet', '(他人のものなど)をひどく欲しがる', '/ˈkʌvɪt/', 'カヴィト',
  'Rival nations have long coveted the region''s vast reserves of rare earth minerals essential for modern technology.',
  '敵対する国々は、現代技術に不可欠なレアアース鉱物の膨大な埋蔵量を持つその地域を長い間欲しがってきた。',
  'The young researcher coveted the prestigious fellowship that would grant her access to the world''s foremost laboratory.',
  'その若い研究者は、世界最高の研究所へのアクセスを与えてくれる名誉あるフェローシップをひどく欲しがった。'),
(892, 'abominable', '嫌悪感を抱かせる、ひどい', '/əˈbɑːmɪnəbl/', 'アボミナブル',
  'The committee condemned the abominable treatment of prisoners, which violated fundamental human rights conventions.',
  '委員会は、基本的人権条約に違反する囚人へのひどい扱いを非難した。',
  'Working conditions in the unregulated factories were so abominable that international organizations demanded immediate reform.',
  '規制のない工場での労働条件は非常にひどく、国際機関が即座の改革を要求した。'),
(893, 'soggy', '湿った;(食べ物が)しなりした', '/ˈsɑːɡi/', 'ソギー',
  'The incessant rainfall left the cricket pitch so soggy that officials had no choice but to postpone the match.',
  '絶え間ない降雨でクリケット場が非常に湿ったため、関係者は試合を延期するしかなかった。',
  'The architect warned that the soggy terrain would require extensive drainage work before construction could commence.',
  '建築家は、湿った地盤では建設を開始する前に大規模な排水工事が必要になると警告した。'),
(894, 'precipitate', '(突然)(よくない状態・結果)を引き起こす', '/prɪˈsɪpɪteɪt/', 'プリシピテイト',
  'The sudden collapse of the investment bank precipitated a financial crisis that reverberated across global markets.',
  '投資銀行の突然の破綻が、世界の市場に波及する金融危機を引き起こした。',
  'Analysts warned that escalating trade disputes could precipitate a severe recession in multiple economies simultaneously.',
  'アナリストたちは、激化する貿易紛争が複数の経済で同時に深刻な不況を引き起こす可能性があると警告した。'),
(895, 'foray', '襲撃、急襲;(不慣れな分野への)進出', '/ˈfɔːreɪ/', 'フォーレイ',
  'The technology giant''s foray into the healthcare sector was met with skepticism from established medical institutions.',
  'そのテクノロジー大手のヘルスケア分野への進出は、既存の医療機関から懐疑的に受け止められた。',
  'The rebel forces launched a daring foray across the border, catching the garrison completely off guard.',
  '反乱軍は国境を越えた大胆な襲撃を開始し、守備隊は完全に不意を突かれた。'),
(896, 'prodigy', '神童、天才児', '/ˈprɑːdɪdʒi/', 'プロディジー',
  'The musical prodigy performed a flawless concerto at the age of seven, astonishing the audience and critics alike.',
  'その音楽の神童は7歳で完璧な協奏曲を演奏し、聴衆と批評家の双方を驚嘆させた。',
  'Once hailed as a mathematical prodigy, she went on to develop groundbreaking algorithms in artificial intelligence.',
  'かつて数学の神童と称えられた彼女は、その後人工知能における画期的なアルゴリズムを開発した。'),
(897, 'allure', '魅力、魅惑', '/əˈlʊr/', 'アルアー',
  'The allure of quick profits in speculative markets has led many inexperienced investors to financial ruin.',
  '投機市場での手っ取り早い利益の魅力が、多くの経験の浅い投資家を経済的破滅に導いてきた。',
  'Despite the allure of metropolitan life, a growing number of professionals are relocating to smaller regional cities.',
  '大都市生活の魅惑にもかかわらず、より小さな地方都市に移住する専門家が増えている。'),
(898, 'decoy', 'おとり(役)', '/ˈdiːkɔɪ/', 'ディーコイ',
  'Undercover agents used an elaborate decoy operation to lure the arms dealers into revealing their supply network.',
  '潜入捜査官たちは、武器商人に供給ネットワークを暴露させるために精巧なおとり作戦を使った。',
  'The military deployed decoy vehicles across the desert to mislead enemy reconnaissance aircraft.',
  '軍は敵の偵察機を欺くために砂漠中におとりの車両を配備した。'),
(899, 'furtive', '(行為などが)人目を盗んだ、内緒の', '/ˈfɜːrtɪv/', 'ファーティヴ',
  'The journalist observed the official casting furtive glances at classified documents during the confidential briefing.',
  'ジャーナリストは、機密ブリーフィング中にその当局者が機密文書に人目を盗んだ視線を向けるのを目撃した。',
  'His furtive manner during the interrogation only served to heighten the detectives'' suspicion of his involvement.',
  '尋問中の彼の内緒めいた態度は、彼の関与に対する刑事たちの疑念を強めるだけだった。'),
(900, 'snub', '(人)を冷たくあしらう;(申し出など)をはねつける', '/snʌb/', 'スナブ',
  'The ambassador''s decision to snub the formal reception was interpreted as a deliberate diplomatic affront.',
  '大使が公式レセプションを冷たくあしらう決定をしたことは、意図的な外交的侮辱と解釈された。',
  'The committee snubbed the renowned scientist''s application, prompting widespread criticism from the academic community.',
  '委員会が著名な科学者の申請をはねつけたことは、学術界からの広範な批判を引き起こした。');
