-- words テーブル INSERT文 (No.951 ~ No.1000)

INSERT INTO words (word_number, word, meaning, pronunciation, katakana, example1_en, example1_ja, example2_en, example2_ja) VALUES
(951, 'wrench', '(ものなど)をもぎ取る;(人)を引き離す;レンチ、スパナ;(別れなどの)つらい悲しみ', '/rɛntʃ/', 'レンチ',
  'She wrenched the door open with all her strength, desperate to escape the smoke-filled corridor.',
  '彼女は煙が充満した廊下から逃げようと必死で、力いっぱいドアをこじ開けた。',
  'It was a terrible wrench to leave the country where she had spent the most formative years of her career.',
  'キャリアの最も重要な時期を過ごした国を離れることは、とてもつらい悲しみだった。'),
(952, 'ecstatic', '興奮した、有頂天になった', '/ɪkˈstætɪk/', 'エクスタティック',
  'The researchers were ecstatic when the clinical trials yielded results far exceeding their initial projections.',
  '臨床試験が当初の予測をはるかに上回る結果をもたらしたとき、研究者たちは有頂天になった。',
  'Fans were ecstatic upon hearing that the legendary orchestra would perform a series of concerts in their city.',
  'あの伝説的なオーケストラが自分たちの街で連続公演を行うと聞いて、ファンたちは興奮した。'),
(953, 'quirk', '(行動・考えの)変わった癖、奇行', '/kwɜːrk/', 'クワーク',
  'One of the professor''s endearing quirks was his habit of pacing back and forth while delivering lectures on quantum physics.',
  'その教授の愛すべき癖の一つは、量子物理学の講義中に行ったり来たりする習慣だった。',
  'By a quirk of fate, the two estranged siblings ended up working for the same multinational corporation.',
  '運命のいたずらで、疎遠になっていた二人の兄弟は同じ多国籍企業で働くことになった。'),
(954, 'regale', '(話・冗談などで)(人)を楽しませる', '/rɪˈɡeɪl/', 'リゲイル',
  'The retired diplomat regaled the audience with fascinating anecdotes from his decades of service in conflict zones.',
  '退職した外交官は、紛争地帯での数十年にわたる任務から得た興味深い逸話で聴衆を楽しませた。',
  'Every holiday gathering, the patriarch of the family would regale the children with tales of his youth in the countryside.',
  '休日の集まりのたびに、一家の長は田舎での若き日の話で子供たちを楽しませたものだった。'),
(955, 'vacillate', '(心・考えなどが)ぐらつく、揺れる', '/ˈvæsɪleɪt/', 'ヴァシレイト',
  'The committee vacillated for months over whether to approve the controversial urban redevelopment project.',
  '委員会は、物議を醸す都市再開発プロジェクトを承認するかどうかについて何ヶ月も揺れ動いた。',
  'Unable to vacillate any longer, the prime minister finally committed to a definitive course of action on the trade agreement.',
  'これ以上ためらうことができず、首相はついに貿易協定に関する明確な行動方針を決めた。'),
(956, 'concoct', '(話・言い訳など)を考え出す、でっち上げる;(材料を混ぜて)(食べ物など)を作る', '/kənˈkɒkt/', 'コンコクト',
  'The defendant concocted an elaborate alibi, but forensic evidence ultimately dismantled his fabricated story.',
  '被告は手の込んだアリバイをでっち上げたが、法医学的証拠が最終的に彼の作り話を覆した。',
  'The chef concocted a remarkable fusion dish by blending traditional Japanese ingredients with French culinary techniques.',
  'そのシェフは日本の伝統的な食材とフランスの料理技法を融合させ、見事な創作料理を作り上げた。'),
(957, 'pilfer', '~をくすねる、ちょろまかす', '/ˈpɪlfər/', 'ピルファー',
  'The employee was dismissed after surveillance footage revealed that he had been pilfering office supplies for months.',
  '監視カメラの映像で数ヶ月にわたり事務用品をくすねていたことが発覚し、その従業員は解雇された。',
  'Tourists were warned not to leave valuables unattended, as petty criminals frequently pilfered from unsuspecting visitors.',
  '軽犯罪者が油断した観光客から頻繁にくすねるため、貴重品を放置しないよう観光客は警告された。'),
(958, 'prescient', '予知する、先見の明がある', '/ˈprɛʃənt/', 'プレシェント',
  'The economist''s prescient warnings about the housing bubble went largely unheeded until the market collapsed spectacularly.',
  'その経済学者の住宅バブルに関する先見の明のある警告は、市場が劇的に崩壊するまでほとんど無視された。',
  'In retrospect, the novelist''s portrayal of a surveillance-driven society proved remarkably prescient.',
  '振り返ってみると、その小説家が描いた監視社会の姿は驚くほど予見的であった。'),
(959, 'suffocate', '~を窒息(死)させる', '/ˈsʌfəkeɪt/', 'サフォケイト',
  'The thick smoke from the industrial fire threatened to suffocate residents in the adjacent apartment complex.',
  '工場火災からの濃い煙が、隣接するマンションの住民を窒息させる恐れがあった。',
  'Excessive bureaucratic regulations can suffocate innovation and deter entrepreneurs from launching new ventures.',
  '過度な官僚的規制はイノベーションを窒息させ、起業家が新しい事業を立ち上げるのを阻止しかねない。'),
(960, 'intrepid', '恐れを知らない、勇敢な', '/ɪnˈtrɛpɪd/', 'イントレピッド',
  'The intrepid journalist ventured into the war-torn region to document the humanitarian crisis firsthand.',
  'その勇敢なジャーナリストは、人道危機を直接記録するために紛争地帯に足を踏み入れた。',
  'Only the most intrepid mountaineers dared to attempt the treacherous ascent during the winter season.',
  '冬季にその危険な登頂に挑戦しようとしたのは、最も恐れを知らない登山家だけだった。'),
(961, 'matrimony', '結婚、婚姻', '/ˈmætrɪmoʊni/', 'マトリモニー',
  'The couple entered into matrimony in a ceremony that blended both Eastern and Western cultural traditions.',
  'その夫婦は東洋と西洋の文化的伝統を融合させた式で婚姻を結んだ。',
  'In many societies, the institution of matrimony has undergone significant transformation over the past century.',
  '多くの社会において、婚姻という制度はこの一世紀で大きな変化を遂げた。'),
(962, 'subservient', '従属的な、へつらった', '/səbˈsɜːrviənt/', 'サブサーヴィエント',
  'The dictator demanded that all government officials remain unquestioningly subservient to his directives.',
  'その独裁者は、すべての政府高官が自分の指令に無条件に従属的であることを要求した。',
  'Critics argued that the nation''s foreign policy had become subservient to the economic interests of a single allied power.',
  '批評家たちは、その国の外交政策が一つの同盟国の経済的利益に従属的になっていると主張した。'),
(963, 'interlude', '合い間、合い間の出来事;(劇・映画などの)幕間;間奏曲', '/ˈɪntərluːd/', 'インタールード',
  'The brief interlude of peace between the two conflicts gave the exhausted population a chance to rebuild their shattered infrastructure.',
  '二つの紛争の間の束の間の平和な期間は、疲弊した人々に破壊されたインフラを再建する機会を与えた。',
  'During the musical interlude, the audience reflected on the powerful themes presented in the first act of the opera.',
  '間奏曲の間、観客はオペラの第一幕で提示された力強いテーマについて思いをめぐらせた。'),
(964, 'decorum', '礼儀正しい行動、上品さ', '/dɪˈkɔːrəm/', 'デコーラム',
  'The ambassador maintained impeccable decorum throughout the tense diplomatic negotiations, never losing composure.',
  'その大使は緊迫した外交交渉を通じて完璧な礼儀正しさを保ち、決して冷静さを失わなかった。',
  'The judge admonished the spectators for their lack of decorum, threatening to clear the courtroom if order was not restored.',
  '裁判官は傍聴人の礼儀のなさをたしなめ、秩序が回復しなければ法廷から退去させると警告した。'),
(965, 'rescind', '(法律・契約など)を撤回する、無効にする', '/rɪˈsɪnd/', 'リシンド',
  'The government was compelled to rescind the executive order after the supreme court ruled it unconstitutional.',
  '最高裁判所が違憲と判断した後、政府はその行政命令を撤回せざるを得なかった。',
  'The university decided to rescind the scholarship offer upon discovering that the applicant had falsified academic records.',
  '応募者が学業成績を偽造していたことが判明し、大学は奨学金の提供を撤回することを決定した。'),
(966, 'ruse', '策略、計略', '/ruːz/', 'ルーズ',
  'The spy employed an ingenious ruse to gain access to the classified documents stored in the embassy vault.',
  'そのスパイは、大使館の金庫に保管された機密文書にアクセスするために巧妙な策略を用いた。',
  'What initially appeared to be a generous business proposal turned out to be nothing more than a ruse to acquire the company''s patents.',
  '当初は寛大な事業提案に見えたものは、会社の特許を取得するための策略にすぎないことが判明した。'),
(967, 'undermine', '(自信・権威など)をひそかに傷つける、(健康など)をむしばむ', '/ˌʌndərˈmaɪn/', 'アンダーマイン',
  'The relentless spread of misinformation on social media has the potential to undermine public trust in democratic institutions.',
  'ソーシャルメディア上の絶え間ない偽情報の拡散は、民主主義制度に対する国民の信頼をひそかに傷つける可能性がある。',
  'Years of chronic stress and sleep deprivation gradually undermined her physical health, culminating in a serious illness.',
  '長年の慢性的なストレスと睡眠不足が徐々に彼女の健康をむしばみ、ついには重い病気に至った。'),
(968, 'scarcity', '(食料・資源などの)不足、欠乏', '/ˈskɛrsɪti/', 'スケアシティ',
  'The scarcity of clean drinking water in the region has precipitated a public health emergency of unprecedented proportions.',
  'その地域の清潔な飲料水の不足は、前例のない規模の公衆衛生上の緊急事態を引き起こした。',
  'Economists predict that the growing scarcity of rare earth minerals will drive up the cost of electronic devices worldwide.',
  '経済学者たちは、レアアースの不足が深刻化し、世界中で電子機器のコストが上昇すると予測している。'),
(969, 'profound', '(影響などが)深刻な、重大な;(もの・ことが)深い', '/prəˈfaʊnd/', 'プロファウンド',
  'The discovery of antibiotics had a profound impact on modern medicine, saving countless lives over the past century.',
  '抗生物質の発見は現代医学に重大な影響を与え、過去一世紀にわたって無数の命を救った。',
  'The philosopher''s profound insights into the nature of consciousness continue to influence academic discourse to this day.',
  'その哲学者の意識の本質に関する深い洞察は、今日に至るまで学術的議論に影響を与え続けている。'),
(970, 'deploy', '(部隊など)を展開させる、配置する', '/dɪˈplɔɪ/', 'デプロイ',
  'The military command decided to deploy additional troops along the border in response to the escalating territorial dispute.',
  '軍司令部は、激化する領土紛争に対応して国境沿いに追加の部隊を展開させることを決定した。',
  'The technology firm plans to deploy its new artificial intelligence system across all branches by the end of the fiscal year.',
  'そのテクノロジー企業は、会計年度末までに新しい人工知能システムを全支店に配置する予定である。'),
(971, 'denounce', '(人・行為など)を(公然と)非難する、責める;(人)を告発する、訴える', '/dɪˈnaʊns/', 'デナウンス',
  'Human rights organizations were quick to denounce the government''s decision to impose restrictions on freedom of the press.',
  '人権団体は、報道の自由に制限を課すという政府の決定を直ちに非難した。',
  'The whistleblower publicly denounced the corporation''s illegal dumping of toxic waste into the river.',
  '内部告発者は、その企業が有毒廃棄物を川に不法投棄していることを公然と告発した。'),
(972, 'slash', '(価格・予算など)を大幅に削減する;~をざっと切る、切り裂く;斜線、スラッシュ', '/slæʃ/', 'スラッシュ',
  'In an effort to remain competitive, the airline slashed its international fares by nearly forty percent.',
  '競争力を維持するため、その航空会社は国際線の運賃をほぼ40パーセント大幅に削減した。',
  'The municipal government was forced to slash its education budget, prompting widespread protests from parents and teachers.',
  '市政府は教育予算の大幅な削減を余儀なくされ、保護者や教師からの広範な抗議を招いた。'),
(973, 'liaison', '連絡、連携;連絡係', '/liˈeɪzɒn/', 'リエイゾン',
  'She was appointed as the liaison between the research department and the executive board to streamline communication.',
  '彼女はコミュニケーションを円滑にするため、研究部門と経営陣の間の連絡係に任命された。',
  'Effective liaison between emergency services proved critical in coordinating the disaster relief operations.',
  '緊急サービス間の効果的な連携は、災害救援活動の調整において極めて重要であることが証明された。'),
(974, 'rigorous', '厳しい、厳格な', '/ˈrɪɡərəs/', 'リゴラス',
  'The pharmaceutical company subjected the new vaccine to rigorous clinical trials before seeking regulatory approval.',
  'その製薬会社は、規制当局の承認を求める前に、新しいワクチンを厳格な臨床試験にかけた。',
  'Candidates for the elite diplomatic corps must undergo a rigorous selection process that evaluates both intellectual and interpersonal abilities.',
  'エリート外交官団の候補者は、知的能力と対人能力の両方を評価する厳しい選考過程を経なければならない。'),
(975, 'mitigate', '(苦痛・悲しみなど)を和らげる、鎮める', '/ˈmɪtɪɡeɪt/', 'ミティゲイト',
  'The government introduced a series of fiscal measures designed to mitigate the economic impact of the global recession.',
  '政府は、世界的な不況の経済的影響を和らげるために一連の財政措置を導入した。',
  'Planting mangrove forests along the coastline can significantly mitigate the damage caused by storm surges and tsunamis.',
  '海岸線に沿ってマングローブ林を植えることで、高潮や津波による被害を大幅に和らげることができる。'),
(976, 'imperative', '絶対必要で、必須で;命令的な', '/ɪmˈpɛrətɪv/', 'インペラティヴ',
  'It is imperative that world leaders collaborate to address the existential threat posed by climate change.',
  '気候変動がもたらす存亡の危機に対処するため、世界の指導者たちが協力することが絶対に必要である。',
  'The surgeon stressed that it was imperative to operate within the next twenty-four hours to prevent further complications.',
  '外科医は、さらなる合併症を防ぐために24時間以内に手術することが必須であると強調した。'),
(977, 'depict', '(絵画・彫刻などで)~を表現する;(言葉で)~を描写する', '/dɪˈpɪkt/', 'デピクト',
  'The mural vividly depicts the struggles and triumphs of the nation''s independence movement.',
  'その壁画は、国の独立運動の苦闘と勝利を生き生きと表現している。',
  'The documentary aims to depict the daily realities faced by refugees fleeing armed conflict in the region.',
  'そのドキュメンタリーは、その地域の武力紛争から逃れる難民が直面する日常の現実を描写することを目的としている。'),
(978, 'amass', '(時間をかけて)(財産・情報など)を集める、蓄える', '/əˈmæs/', 'アマス',
  'Over the course of three decades, the philanthropist amassed a vast fortune through shrewd investments in emerging markets.',
  '30年にわたり、その慈善家は新興市場への賢明な投資を通じて莫大な財産を蓄えた。',
  'The intelligence agency amassed a comprehensive dossier on the suspected espionage network operating within the country.',
  '情報機関は、国内で活動しているとされるスパイネットワークに関する包括的な調査書類を集めた。'),
(979, 'dissent', '異議、不賛成', '/dɪˈsɛnt/', 'ディセント',
  'The authoritarian regime ruthlessly suppressed all forms of political dissent, imprisoning activists and silencing journalists.',
  'その権威主義体制は、活動家を投獄しジャーナリストを黙らせ、あらゆる形の政治的異議を容赦なく弾圧した。',
  'Several members of the committee voiced their dissent, arguing that the proposed policy would disproportionately affect vulnerable communities.',
  '委員会の数名のメンバーが異議を唱え、提案された政策が脆弱な地域社会に不均衡な影響を与えると主張した。'),
(980, 'replenish', '~を補充する、補給する;~を再び満たす', '/rɪˈplɛnɪʃ/', 'リプレニッシュ',
  'The humanitarian organization dispatched supply convoys to replenish the dwindling food reserves in the besieged city.',
  '人道支援団体は、包囲された都市の減少する食料備蓄を補充するために補給車列を派遣した。',
  'Sustainable forestry practices are essential to replenish the natural resources that have been depleted by decades of overexploitation.',
  '数十年にわたる過剰利用で枯渇した天然資源を補充するには、持続可能な林業の実践が不可欠である。'),
(981, 'tangible', '(事実・証拠などが)明白な、確実な;(ものが)触れられる', '/ˈtændʒɪbl/', 'タンジブル',
  'Despite years of negotiation, the peace talks have yet to produce any tangible results that would satisfy both parties.',
  '何年にもわたる交渉にもかかわらず、和平交渉は両者を満足させる明白な成果をまだ生み出していない。',
  'The new vocational training program has delivered tangible benefits to unemployed youth in the rural communities.',
  '新しい職業訓練プログラムは、農村地域の失業中の若者に確実な恩恵をもたらした。'),
(982, 'splurge', '散財する、ぜいたくをする', '/splɜːrdʒ/', 'スプラージ',
  'After receiving an unexpected bonus, she decided to splurge on a luxury vacation to celebrate her promotion.',
  '予想外のボーナスを受け取った後、彼女は昇進を祝って豪華な休暇に散財することにした。',
  'Financial advisors caution against the tendency to splurge impulsively, especially during periods of economic uncertainty.',
  'ファイナンシャルアドバイザーは、特に経済が不安定な時期に衝動的に散財する傾向に注意を促している。'),
(983, 'savvy', '(実際的な)知識を持った、やり手の', '/ˈsævi/', 'サヴィ',
  'The savvy investor diversified her portfolio well before the market downturn, thereby minimizing her financial losses.',
  'そのやり手の投資家は市場の低迷前にポートフォリオを十分に分散させ、それによって経済的損失を最小限に抑えた。',
  'In today''s digital landscape, even small businesses must be technologically savvy to remain competitive.',
  '今日のデジタル環境では、中小企業でさえ競争力を維持するために技術に精通していなければならない。'),
(984, 'acclaim', '(人・業績に対する)称賛、歓呼;~を称賛する', '/əˈkleɪm/', 'アクレイム',
  'The novelist''s debut work received widespread critical acclaim and was subsequently nominated for several prestigious literary awards.',
  'その小説家のデビュー作は広く批評家から称賛を受け、その後いくつかの権威ある文学賞にノミネートされた。',
  'The humanitarian worker was acclaimed internationally for her tireless efforts to provide medical aid in conflict zones.',
  'その人道支援活動家は、紛争地帯での医療支援へのたゆまぬ努力で国際的に称賛された。'),
(985, 'gadget', '(小型で有用な)装置、機械', '/ˈɡædʒɪt/', 'ガジェット',
  'The exhibition showcased an array of innovative gadgets designed to assist elderly individuals with daily household tasks.',
  'その展示会では、高齢者の日常の家事を支援するために設計された様々な革新的な装置が展示された。',
  'While modern gadgets have undeniably improved efficiency, critics argue they have also diminished interpersonal communication.',
  '現代の機器が効率を向上させたことは否定できないが、批評家は対人コミュニケーションを減少させたとも主張している。'),
(986, 'postulate', '(自明なものとして)(もの・こと)を仮定する', '/ˈpɒstʃəleɪt/', 'ポスチュレイト',
  'The theoretical physicist postulated the existence of a previously undetected subatomic particle to explain the anomalous experimental data.',
  'その理論物理学者は、異常な実験データを説明するためにこれまで検出されていない素粒子の存在を仮定した。',
  'Several scholars have postulated that the decline of the ancient civilization was triggered by a prolonged period of severe drought.',
  '数人の学者が、その古代文明の衰退は長期にわたる深刻な干ばつによって引き起こされたと仮定している。'),
(987, 'manifest', '(目で見て)明らかな、はっきりした;(感情・態度など)をはっきりと示す', '/ˈmænɪfɛst/', 'マニフェスト',
  'The tension between the two delegations was manifest from the outset of the bilateral negotiations.',
  '二国間交渉の最初から、両代表団間の緊張は明らかだった。',
  'The disease may not manifest symptoms for several years, making early detection exceedingly difficult.',
  'その病気は数年間症状をはっきりと示さない場合があり、早期発見が非常に困難である。'),
(988, 'affinity', '親近感、相性、親和性;類似性', '/əˈfɪnɪti/', 'アフィニティ',
  'The young diplomat demonstrated a natural affinity for languages, becoming fluent in five by the age of twenty-five.',
  'その若い外交官は言語に対する天賦の親和性を示し、25歳までに5か国語に堪能になった。',
  'Researchers discovered a remarkable affinity between the two plant species, suggesting they share a common evolutionary ancestor.',
  '研究者たちは二つの植物種の間に顕著な類似性を発見し、共通の進化的祖先を持つことを示唆した。'),
(989, 'revert', '(元の状態・話題などに)戻る', '/rɪˈvɜːrt/', 'リヴァート',
  'After the experimental policy failed to deliver improvements, the administration decided to revert to the original framework.',
  '実験的な政策が改善をもたらさなかった後、行政は元の枠組みに戻すことを決定した。',
  'Ecologists warned that the restored wetland could revert to its degraded state without continued maintenance and monitoring.',
  '生態学者は、継続的な維持管理と監視がなければ、復元された湿地が劣化した状態に戻る可能性があると警告した。'),
(990, 'vilify', '~を中傷する、けなす', '/ˈvɪlɪfaɪ/', 'ヴィリファイ',
  'The opposition party sought to vilify the incumbent leader by circulating misleading information about her policy record.',
  '野党は、現職の指導者の政策実績に関する誤解を招く情報を流布して彼女を中傷しようとした。',
  'Throughout history, whistleblowers have often been vilified by the very institutions whose wrongdoing they exposed.',
  '歴史を通じて、内部告発者はしばしば自らが不正を暴いた組織そのものから中傷されてきた。'),
(991, 'incapacitate', '(病気・事故などが)(人)から能力を奪う;~を正常に機能しないようにする', '/ˌɪnkəˈpæsɪteɪt/', 'インキャパシテイト',
  'The debilitating injury incapacitated the star athlete, forcing her to withdraw from the international championship.',
  '衰弱させるけがによってそのスター選手は能力を奪われ、国際選手権からの棄権を余儀なくされた。',
  'A severe cyberattack incapacitated the hospital''s electronic medical records system, disrupting patient care for several days.',
  '深刻なサイバー攻撃が病院の電子カルテシステムを機能不全にし、数日間にわたり患者のケアを妨げた。'),
(992, 'calamity', '災難、惨事', '/kəˈlæmɪti/', 'カラミティ',
  'The earthquake that struck the coastal city was the worst natural calamity the nation had experienced in over a century.',
  '沿岸都市を襲った地震は、その国がこの一世紀以上で経験した最悪の自然災害だった。',
  'Had the levees not been reinforced in time, the flooding would have resulted in a calamity of catastrophic proportions.',
  '堤防が間に合って補強されていなければ、洪水は壊滅的な規模の災難をもたらしていただろう。'),
(993, 'mortality', '死亡(数、率);死ぬ運命', '/mɔːrˈtælɪti/', 'モータリティ',
  'Advances in neonatal care have dramatically reduced infant mortality rates in developed countries over the past five decades.',
  '新生児医療の進歩により、過去50年間で先進国の乳児死亡率は劇的に低下した。',
  'The philosopher''s meditation on mortality compelled readers to confront the finite nature of human existence.',
  'その哲学者の死すべき運命についての瞑想は、読者に人間の存在の有限性と向き合うことを迫った。'),
(994, 'onslaught', '(人・事柄に対する)激しい攻撃;(処理し切れないほどの)大量', '/ˈɒnslɔːt/', 'オンスロート',
  'The coastal defenses proved insufficient against the relentless onslaught of the typhoon that battered the region for days.',
  '沿岸の防衛施設は、数日間にわたってその地域を襲った台風の容赦ない猛攻に対して不十分であることが判明した。',
  'The company faced an onslaught of criticism from shareholders after the quarterly earnings report revealed significant losses.',
  '四半期決算報告で大幅な損失が明らかになった後、その企業は株主からの激しい批判の嵐に直面した。'),
(995, 'revelation', '驚くべき新事実;(秘密などの)暴露、摘発', '/ˌrɛvəˈleɪʃən/', 'レヴェレイション',
  'The journalist''s revelation of widespread corruption within the ministry sent shockwaves through the political establishment.',
  'そのジャーナリストによる省内の広範な汚職の暴露は、政治体制に衝撃を与えた。',
  'The revelation that the pharmaceutical company had concealed adverse trial results led to a massive class-action lawsuit.',
  'その製薬会社が有害な試験結果を隠していたという新事実の発覚は、大規模な集団訴訟につながった。'),
(996, 'lull', '(人)を寝かしつける;(感情など)を鎮める', '/lʌl/', 'ラル',
  'The gentle rhythm of the waves lulled the exhausted survivors into a much-needed sleep aboard the rescue vessel.',
  '波の穏やかなリズムが、疲れ果てた生存者たちを救助船上でまどろみへと誘った。',
  'A temporary lull in hostilities allowed humanitarian convoys to deliver desperately needed supplies to the besieged population.',
  '一時的な敵対行為の鎮静により、人道支援車列が包囲された住民に切実に必要な物資を届けることができた。'),
(997, 'surmise', '~と推測する', '/sərˈmaɪz/', 'サーマイズ',
  'Based on the archaeological evidence, researchers surmised that the ancient settlement had been abandoned due to a volcanic eruption.',
  '考古学的証拠に基づき、研究者たちはその古代集落が火山噴火のために放棄されたと推測した。',
  'We can only surmise what motivated the artist to destroy the majority of his early works before his untimely death.',
  '早すぎる死の前にその芸術家が初期の作品の大部分を破壊した動機について、我々は推測することしかできない。'),
(998, 'harness', '(自然の力など)を利用する;(馬)に馬具をつける;馬具', '/ˈhɑːrnɪs/', 'ハーネス',
  'Engineers have developed innovative methods to harness solar energy more efficiently, even in regions with limited sunlight.',
  '技術者たちは、日照の限られた地域でもより効率的に太陽エネルギーを利用する革新的な方法を開発した。',
  'The research team is exploring ways to harness the potential of artificial intelligence to accelerate drug discovery.',
  '研究チームは、創薬を加速するために人工知能の可能性を利用する方法を模索している。'),
(999, 'solicit', '(金銭・援助・情報など)を請い求める', '/səˈlɪsɪt/', 'ソリシット',
  'The nonprofit organization solicited donations from corporate sponsors to fund its educational programs in underserved communities.',
  'その非営利団体は、恵まれない地域での教育プログラムの資金を確保するために企業スポンサーからの寄付を請い求めた。',
  'The committee solicited expert opinions from leading economists before formulating its recommendations on fiscal reform.',
  '委員会は、財政改革に関する提言を策定する前に、一流の経済学者から専門家の意見を請い求めた。'),
(1000, 'dispatch', '(部隊・使者など)を派遣する;(手紙・小包など)を急送する', '/dɪˈspætʃ/', 'ディスパッチ',
  'The government dispatched a team of specialists to the disaster zone to assess the extent of the structural damage.',
  '政府は構造的被害の程度を評価するために専門家チームを被災地に派遣した。',
  'The commander dispatched reinforcements to the front line after intelligence reports indicated an imminent counteroffensive.',
  '情報報告が差し迫った反撃を示した後、司令官は前線に増援部隊を派遣した。');
